### ISSUE TITLE
builds broke on macos

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#1006]
Might be a duplicate! Is /usr/bin/cmake hard-coded? Which cmake file can I find these commands in?

/bin/sh: cmake: command not found
make: *** [/Users/USER/code/cpp-ethereum-build/CMakeFiles/BuildInfo.h] Error 127
Command /bin/sh failed with exit code 2

cd /Users/USER/code/cpp-ethereum-origin/libweb3jsonrpc && cmake -E rename webthreestubclient.h ../test/webthreestubclient.h
/bin/sh: cmake: command not found
make: *** [jsonrpcstub_buildpart_0] Error 127
Command /bin/sh failed with exit code 2

$ which cmake
/usr/local/bin/cmake

**Comment by caktux** [comment]
Similar here, not sure why the builds passed though
```
Scanning dependencies of target BuildInfo.h
[  1%] [  1%] Unrecognized option or missing parameter, use --help.
make[2]: *** [jsonrpcstub] Error 255
make[1]: *** [libweb3jsonrpc/CMakeFiles/jsonrpcstub.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  2%] Automatic moc for target sc
Automatic moc for target checkRandomTest
Built target secp256k1
[  2%] [  2%] Built target sc_automoc
Built target checkRandomTest_automoc
[  2%] Built target BuildInfo.h
[  7%] Built target devcore
make: *** [all] Error 2
```

**Comment by caktux** [comment]
For some reason I had a lingering `jsonrpc3`, had to do `brew remove jsonrpc3` and `brew install jsonrpc` to clean things up... Note we'll be switching to the official Homebrew`libjson-rpc-cpp` soon.
