### ISSUE TITLE
Proposal: ABI docs on chain

### ISSUE THREAD

**Issue by ebuchman** [ethereum/cpp-ethereum#1018]
Is there a current standard for where to store ABI docs? I suspect something like swarm might fill this purpose, but why not put them on chain with the code? Ie. the code slot in a contract account should be an rlp encoded list. If the list has only one element, its just the evm code. If two, the first is the evm code and the second the json encoded abi doc

**Comment by chriseth** [comment]
Thank you for this suggestion, but the ABI spec will need too much space in the blockchain. We will provide convenient means for accessing all this information in the future.
