### ISSUE TITLE
Tests for eth_newFilterString

### ISSUE THREAD

**Issue by cubedro** [ethereum/cpp-ethereum#1026]
Tests and examples of what is sent and received using eth_newFilterString (pending/chain). Right now eth_changed for both 'pending' and 'chain' is returning:
```
{"id":19,"jsonrpc":"2.0","result":[{"address":"0x0000000000000000000000000000000000000000","data":"0x0000000000000000000000000000000000000000000000000000000000000000","number":0}]}
```

**Comment by gavofyork** [comment]
This is valid behaviour, but does need documenting. patches welcome :)
