### ISSUE TITLE
mix - graphics error

### ISSUE THREAD

**Issue by androlo** [ethereum/cpp-ethereum#1049]
Hi. I'm getting this error on ubuntu 14.04 (amd64) when running `mix` after having pulled in and installed ethereum, ethereum-dev and the mix files as per the PPA installation instructions. 

```
$ mix

QML debugging is enabled. Only use this in a safe environment.
*** [ 19:54:49 | main ] Opened blockchain DB. Latest: eaa9eae946492b0d61a0819cbd33be8e9429fee840885341cc55910d2e4651a3
compiler/qv4isel_p.cpp:220: virtual void QV4::IR::IRDecoder::visitMove(QV4::IR::Move*): Unimplemented code.
var %6 = call 5()
compiler/qv4isel_p.cpp:220: virtual void QV4::IR::IRDecoder::visitMove(QV4::IR::Move*): Unimplemented code.
var &0 = call 5()
Segmentation fault (core dumped)
```

**Comment by androlo** [comment]
I tried twice, and also made sure everything was in order. Alethzero starts and runs, and there are no issues with graphics (although i can't seem to mine). This is `develop` btw. I did the Ethereum dev installation.

**Comment by androlo** [comment]
I get a transparent mix window btw. before it crashes. I can see the frame.

**Comment by androlo** [comment]
Fresh trusty installation btw. just a few hours old. Sorry for the spam.

**Comment by arkpar** [comment]
Hi, thanks for the feedback.
Could you get a backtrace for the segfault with gdb?

$ gdb ./mix
run
... wait for segfault ...
bt full
... copy the output of bt ...

**Comment by androlo** [comment]
right, so i built from source instead of using the PPAs and the source build works. was gonna do a debug build to give some more info but nm i suppose. super excited about this tool btw (and solidity).
