### ISSUE TITLE
client does not connect to any peers

### ISSUE THREAD

**Issue by psalami** [ethereum/cpp-ethereum#1054]
I am seeing the following message in the log output, repeated roughly every 30 seconds (for eth and AlethZero):

```
Terminating discover after 0 rounds.
```

My client does not connect to any other nodes (as indicated by the output of the peerCount JSON-RPC call). This happens regardless of whether I specify a node to connect to at startup (using the -r command line flag) or I specify the -b parameter. The message originates in NodeTable.cpp, on the following line:
https://github.com/ethereum/cpp-ethereum/blob/57f6aacf9ed981811873f8012586259ddfbc3ac3/libp2p/NodeTable.cpp#L183

This started happening somewhere between 90d309ec933bcf4b66bac98e6284597cfd51d55c and 03d87a6da54b1e9346c25f8857226ec5cff46b69.

**Comment by subtly** [comment]
Are you able to connect via alethzero menu?

It's possible the node may have been done around this time. Also possible the -r parameter isn't recognized for alethzero (I'll look into that).

The terminating discovery message is a normal message. I'll bump it's loglevel a bit so it's not confusing.

**Comment by psalami** [comment]
I was unable to connect regardless of whether I'm using alethzero or the eth cli and also regardless of whether I'm using -r or not (however, it works on the previous build that I referenced, with and without -r). I can check again on the latest build.

**Comment by faizkhan00** [comment]
@psalami do *not* use host:port syntax on the CLI, ```./eth -m off -r 5.1.83.226  -p 30303``` is correct, ```./eth -m off -u 193.138.219.234 -r 5.1.83.226:30303``` is not.

**Comment by chevdor** [comment]
I am having the same issue on the current/latest version.

**Comment by subtly** [comment]
@chevdor @psalami
This should be fixed now.

**Comment by joeykrug** [comment]
On latest dev build on OS X I get this error as well: 
```*N* [ 14:53:55 | p2p ] p2p.started id: 6f65dbaa…
*P* [ 14:53:55 | p2p ] Terminating discover after 0  rounds.```

**Comment by subtly** [comment]
Try with local networking enabled and/or upnp disabled. 
-L -u off

**Comment by subtly** [comment]
@psalami @joeykrug @chevdor Squashed a few more bugs. Is this still an issue with the latest develop?

**Comment by caktux** [comment]
note there's no more -L option

**Comment by joeykrug** [comment]
Still getting it here, can't connect on Windows either :/

**Comment by subtly** [comment]
@joeykrug Leaving the window open for a few minutes might help as well. Sometimes the server has too many connections. Could you try and connect again?

**Comment by joeykrug** [comment]
Still not connecting to any peers (only tested on Windows, travelling a few days and left my Mac @ home)

**Comment by psalami** [comment]
@subtly @joeykrug I'm still getting the same issue (no connections to any peers) I'm on the latest develop build on Mac OS X. I'm using with the eth cli and I tried the -u off flag
@caktux why was the -L option removed? Is there a different way to start the cli and have it connect only to local nodes (or even better, is there a way I can specify a whitelist of IPs or subnets)? I was using this flag to set up a local testnet on my laptop for demos.

**Comment by psalami** [comment]
@subtly @joeykrug specifying the -b (bootstrap) option works and I'm connecting to peers right away.
@caktux should I just leave out the -b option to create a testnet?
Thanks!

**Comment by joeykrug** [comment]
-b option worked for me too!

**Comment by memento** [comment]
Hi !
I have the same issue.
I'm on Ubuntu 14.04
I tried to lauch :
eth
eth -b
eth -L -u off
eth -u off

Nothing.
Does anyone have a clue ?
