### ISSUE TITLE
core: Pending not updated with new pending.

### ISSUE THREAD

**Issue by gavofyork** [ethereum/cpp-ethereum#1057]

**Comment by ethers** [comment]
Is 1057 the same issue as below:

In AZ, Click "Preview Pending Transactions"
load ethereum.js/example/contract.html
Click on create contract
In AZ, click Mine.
OBSERVED: The blockchain pane doesn't update (even though command line shows new blocks found).  It is only when "Preview Pending Transactions" is clicked again (ie turning it off) that the blockchain pain shows the new blocks.
EXPECTED: The blockchain pane keeps updating as new blocks are mined

**Comment by gavofyork** [comment]
fixed now.
