### ISSUE TITLE
--json-rpc-port gets ignored, only uses 8080

### ISSUE THREAD

**Issue by caktux** [ethereum/cpp-ethereum#1058]
Also makes it impossible to run a local cluster for testing, as only the first client to be launched will be responding to json-rpc requests.

**Comment by davidhq** [comment]
for me it works on `ethereum/0.8.1-53-5` (via homebrew)

**Comment by debris** [comment]
eth has configurable port eg. `-j --json-rpc-port 8079`. And, if you are talking about AZ, I will add this command line option

**Comment by caktux** [comment]
I know it's supposed to have a configurable port, I know AZ doesn't as it stands, don't answer me like I'm new here.
I'm saying the option isn't being respected, probably because of the 0.4.2 upgrade.

**Comment by debris** [comment]
You are right, sorry for this answer.
I cannot reproduce this issue on my machine. I am using osx 10.9.
What system are you using? It should't be platform related, but I need more details to find the issue.

**Comment by caktux** [comment]
I'm on 10.10 here but yeah, it shouldn't be platform specific. Basically it only listens on 8080 no matter what.

**Comment by AFDudley** [comment]
Are there tests of some kind for these types of issues?

**Comment by gavofyork** [comment]
works fine on linux.

**Comment by caktux** [comment]
Yep works fine now, closing
