### ISSUE TITLE
HttpSyncProvider is painfully slow in AZ

### ISSUE THREAD

**Issue by caktux** [ethereum/cpp-ethereum#1059]
Loading a DApp freezes the client for many seconds, which was not the case with QtSyncProvider.

**Comment by debris** [comment]
i will check this with profiler

**Comment by debris** [comment]
i had problems with setting up profiler, but did a simple test in javascript... results confirmed the issue. QtSyncProvider is around 20 times faster

**script A**:
```javascript
x = Date.now(); for (var i = 0; i < 100; i++) { web3.eth.coinbase; }; console.log(Date.now() - x);
```

**script B**:
```javascript
x = Date.now(); for (var i = 0; i < 100; i++) { web3.eth.balanceAt(web3.eth.coinbase); }; console.log(Date.now() - x);
```

|  | Qt | Http |
|-----|:----:|:-----:|
| A.1 | 16 | 191 |
| A.2 | 10 | 180 |
| A.3 | 9 | 178 |
| A.4 | 7 | 180 |
| **A.average** | **10.5** | **182.25** |
| B.1 | 16 | 384 |
| B.2 | 23 | 383 |
| B.3 | 15 | 382 |
| B.4 | 15 | 415 |
| **B.average** | **17.25** | **391** |


@gavofyork what should we do with this? QtWebEngine doesn't have possibility to create Qt bindings, right?

**Comment by gavofyork** [comment]
correct. there is nothing major that we can do prior to release. likely the HTTP handshake required for each RPC call is the slowdown. is there something to be done with optimising multiple http calls?

**Comment by debris** [comment]
[libjson-rpc-cpp #98](https://github.com/cinemast/libjson-rpc-cpp/issues/98) should fix the issue

**Comment by debris** [comment]
libjson-rpc-cpp does support persistent connection now. Unfortunately requests are only 2x faster.

**Comment by debris** [comment]
We have reduced number of HTTP threads and we do have persistant connection now. I don't think that we can do anything more. If it's still a huge problem, the only solution is fallback to QtProvider (but i'm not sure if it is possible with QtWebEngine).
