### ISSUE TITLE
had to install libmicrohttpd manually

### ISSUE THREAD

**Issue by androlo** [ethereum/cpp-ethereum#1060]
Hello. Not a big issue but FYI: I had to build and install libmicrohttpd manually today. same thing when using the PPAs it seems. I have lost the actual error message but it wasn't weird, basically just that MHD header and lib checks failed. This was after a clean ubuntu install which is why i didn't have it. Everything besides that seems to work great btw.

**Comment by androlo** [comment]
btw. i got all the deps from the PPAs. ethereum and ethereum-dev (this is all `develop`).

**Comment by gavofyork** [comment]
worked ok for me on a clean ubuntu 14.04 box...

**Comment by androlo** [comment]
local weirdness then I guess.
