### ISSUE TITLE
CORS problems

### ISSUE THREAD

**Issue by davidhq** [ethereum/cpp-ethereum#1062]
Hi,

We run `eth` client like this: `eth -j -m 10 -n off --json-rpc-port 8090`

Then from JS:
`web3.setProvider(new web3.providers.HttpSyncProvider('http://localhost:8090'));`

Server for the webapp is on port `8888`.

Browser of course reports:

```
[Error] XMLHttpRequest cannot load http://localhost:8090/. Origin http://0.0.0.0:8888 is not allowed by Access-Control-Allow-Origin.
	send (ethereum.min.js, line 1)
	o (ethereum.min.js, line 1)
	(anonymous function) (ethereum.min.js, line 1)
	createContract (etherstarter_create.html, line 21)
	(anonymous function) (etherstarter_create.html, line 34)
	dispatch (jquery-2.1.3.min.js, line 3)
	handle (jquery-2.1.3.min.js, line 3)
```

I made a node server that proxies /client requests to eth (`localhost:8888/client` goes to port 8090), 

Server is here: https://gist.github.com/davidhq/17f459fc9972f47a45d8

Eth endpoint is referenced like this: `web3.setProvider(new web3.providers.HttpSyncProvider('http://localhost:8888/client'));`

My question: is this the most optimal solution or can eth server set CORS headers somehow?

**Comment by davidhq** [comment]
Also we probably need a different solution when dapp is actually deployed... there this solution won't work because if proxy is run on the server, it cannot call eth client's port on user's local machine..

**Comment by debris** [comment]
can you check if this issue still occurs in latest develop? during the weekend we upgraded the version of libjson-rpc-cpp, and cors should be working fine now.
