### ISSUE TITLE
Add localStorage

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/cpp-ethereum#1063]
If `web3.db` is going to be removed ( https://github.com/ethereum/go-ethereum/issues/311 ) , `localStorage` should be made available.

**Comment by gavofyork** [comment]
web3.db won't be removed yet.

**Comment by debris** [comment]
QtWebEngine in AlethZero supports `localStorage`

**Comment by rangelife** [comment]
I'm not sure why web3.db is still present in the geth console when it doesn't work. What is localStorage and how do you use it from the geth console?

**Comment by bobsummerwill** [comment]
Please ask in https://gitter.im/ethereum/go-ethereum, @rangelife.

This is a cpp-ethereum bug from pre-history!
