### ISSUE TITLE
build error ASTJsonConverter.h  #include <json/json.h>

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1085]
build error on Ubuntu 14.04 64bit: 

ASTJsonConverter.h:30:23: fatal error: json/json.h: No such file or directory
 #include <json/json.h>

**Comment by debris** [comment]
please clean build directory and rerun cmake. If you have more errors (related with json-rpc-cpp or microhttpd), please uninstall these libraries, and install again latest versions.

**Comment by ethers** [comment]
thanks, the key step is "rm -rf build"
cmake and then building works.
