### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by novusopt** [ethereum/cpp-ethereum#1096]
I downloaded the latest develop branch and i was trying to build and i get following error:

Scanning dependencies of target eth
[ 78%] Building CXX object eth/CMakeFiles/eth.dir/main.cpp.o
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/main.cpp: In function ‘int main(int, char**)’:
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/main.cpp:388:125: error: cannot allocate an object of abstract type ‘WebThreeStubServer’
   jsonrpcServer = shared_ptr<WebThreeStubServer>(new WebThreeStubServer(*jsonrpcConnector.get(), web3, vector<KeyPair>({us})));
                                                                                                                             ^
In file included from /home/bitcoin/Desktop/cpp-ethereum-develop/eth/main.cpp:41:0:
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/WebThreeStubServer.h:41:7: note:   because the following virtual functions are pure within ‘WebThreeStubServer’:
 class WebThreeStubServer: public dev::WebThreeStubServerBase, public dev::WebThreeStubDatabaseFace
       ^
In file included from /home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/WebThreeStubServerBase.h:31:0,
                 from /home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/WebThreeStubServer.h:31,
                 from /home/bitcoin/Desktop/cpp-ethereum-develop/eth/main.cpp:41:
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:301:22: note: 	virtual bool AbstractWebThreeStubServer::eth_setListening(const bool&)
         virtual bool eth_setListening(const bool& param1) = 0;
                      ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:303:22: note: 	virtual bool AbstractWebThreeStubServer::eth_setMining(const bool&)
         virtual bool eth_setMining(const bool& param1) = 0;
                      ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:308:22: note: 	virtual bool AbstractWebThreeStubServer::eth_setDefaultBlock(const int&)
         virtual bool eth_setDefaultBlock(const int& param1) = 0;
                      ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:315:24: note: 	virtual double AbstractWebThreeStubServer::eth_transactionCountByNumber(const int&)
         virtual double eth_transactionCountByNumber(const int& param1) = 0;
                        ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:317:24: note: 	virtual double AbstractWebThreeStubServer::eth_uncleCountByNumber(const int&)
         virtual double eth_uncleCountByNumber(const int& param1) = 0;
                        ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:323:29: note: 	virtual Json::Value AbstractWebThreeStubServer::eth_blockByNumber(const int&)
         virtual Json::Value eth_blockByNumber(const int& param1) = 0;
                             ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:324:29: note: 	virtual Json::Value AbstractWebThreeStubServer::eth_transactionByHash(const string&, const int&)
         virtual Json::Value eth_transactionByHash(const std::string& param1, const int& param2) = 0;
                             ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:325:29: note: 	virtual Json::Value AbstractWebThreeStubServer::eth_transactionByNumber(const int&, const int&)
         virtual Json::Value eth_transactionByNumber(const int& param1, const int& param2) = 0;
                             ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:326:29: note: 	virtual Json::Value AbstractWebThreeStubServer::eth_uncleByHash(const string&, const int&)
         virtual Json::Value eth_uncleByHash(const std::string& param1, const int& param2) = 0;
                             ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:327:29: note: 	virtual Json::Value AbstractWebThreeStubServer::eth_uncleByNumber(const int&, const int&)
         virtual Json::Value eth_uncleByNumber(const int& param1, const int& param2) = 0;
                             ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:334:22: note: 	virtual bool AbstractWebThreeStubServer::eth_uninstallFilter(const int&)
         virtual bool eth_uninstallFilter(const int& param1) = 0;
                      ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:335:29: note: 	virtual Json::Value AbstractWebThreeStubServer::eth_changed(const int&)
         virtual Json::Value eth_changed(const int& param1) = 0;
                             ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:336:29: note: 	virtual Json::Value AbstractWebThreeStubServer::eth_filterLogs(const int&)
         virtual Json::Value eth_filterLogs(const int& param1) = 0;
                             ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:350:22: note: 	virtual bool AbstractWebThreeStubServer::shh_uninstallFilter(const int&)
         virtual bool shh_uninstallFilter(const int& param1) = 0;
                      ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:351:29: note: 	virtual Json::Value AbstractWebThreeStubServer::shh_changed(const int&)
         virtual Json::Value shh_changed(const int& param1) = 0;
                             ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/abstractwebthreestubserver.h:352:29: note: 	virtual Json::Value AbstractWebThreeStubServer::shh_getMessages(const int&)
         virtual Json::Value shh_getMessages(const int& param1) = 0;
                             ^
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/main.cpp:477:127: error: cannot allocate an object of abstract type ‘WebThreeStubServer’
     jsonrpcServer = shared_ptr<WebThreeStubServer>(new WebThreeStubServer(*jsonrpcConnector.get(), web3, vector<KeyPair>({us})));
                                                                                                                               ^
In file included from /home/bitcoin/Desktop/cpp-ethereum-develop/eth/main.cpp:41:0:
/home/bitcoin/Desktop/cpp-ethereum-develop/eth/../libweb3jsonrpc/WebThreeStubServer.h:41:7: note:   since type ‘WebThreeStubServer’ has pure virtual functions
 class WebThreeStubServer: public dev::WebThreeStubServerBase, public dev::WebThreeStubDatabaseFace
       ^
make[2]: *** [eth/CMakeFiles/eth.dir/main.cpp.o] Error 1
make[1]: *** [eth/CMakeFiles/eth.dir/all] Error 2
make: *** [all] Error 2

**Comment by LefterisJP** [comment]
Upgrade your json-rpc-cpp version as seen in the wiki:
https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu

The relevant libraries that changed are:
```
libjson-rpc-cpp-dev libmicrohttpd-dev libjsoncpp-dev
```

Make sure that there are no remnants of the previous version left after installing the latest version.

**Comment by ethers** [comment]
also, look at the output of cmake and the json lines, and if they say "/usr/local/include", try deleting (or moving the files in those locations), because the files of the new libraries are under /usr/include.  Then recreate the build directory, and run cmake again to check that it is using the new libraries.

**Comment by gavofyork** [comment]
i'll assume this is fixed now
