### ISSUE TITLE
Create contract with RPC returns \u0001

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/cpp-ethereum#1102]
Try to run https://github.com/ethereum/ethereum.js/blob/develop/example/contract.html and inspect the JSONRPC response for the `eth_transact` that is supposed to create the contract:
```
{"id":2,"jsonrpc":"2.0","result":"\u0001"}
```

commit f110bfb

This happens with AlethZero, as well as `eth -j`

**Comment by caktux** [comment]
Confirmed contract creation is broken because of this.

**Comment by debris** [comment]
should be fixed in latest develop, please check ;)

**Comment by caktux** [comment]
Issue is back with 8f31bc8

**Comment by jorisbontje** [comment]
Working fine.
