### ISSUE TITLE
Using web3.eth.transact causes alethzero GUI to malfunction

### ISSUE THREAD

**Issue by KenKappler** [ethereum/cpp-ethereum#1103]
Various problems arise when using web3.eth.transact in the JS console, the main one which Is replicated across several builds is that the GUI stops updating the information in any of its panes, (blockchain, contract etc..). Can be fixed by toggling 'preview pending transactions' on and off.

May be linked to:

https://github.com/ethereum/ethereum.js/issues/68

**Comment by androlo** [comment]
seems to be fine now.

**Comment by gavofyork** [comment]
reopen if not.
