### ISSUE TITLE
Mix crashes during start

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/cpp-ethereum#1117]
This is my backtrace when starting mix:

christoph@ThinkPad:~/software/Ethereum/cpp-ethereum/build/mix$ gdb ./mix
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./mix...(no debugging symbols found)...done.
(gdb) break fpc_raiseexception
Function "fpc_raiseexception" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Haltepunkt 1 (fpc_raiseexception) anstehend.
(gdb) run
Starting program: /home/christoph/software/Ethereum/cpp-ethereum/build/mix/mix 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
QML debugging is enabled. Only use this in a safe environment.
[New Thread 0x7fffdfda3700 (LWP 7426)]
[New Thread 0x7fffd6f83700 (LWP 7427)]
[New Thread 0x7fffd6782700 (LWP 7428)]
[New Thread 0x7fffce4b0700 (LWP 7430)]
[New Thread 0x7fffcdcaf700 (LWP 7431)]
[New Thread 0x7fffcd4ae700 (LWP 7432)]
[New Thread 0x7fffcccad700 (LWP 7433)]
[New Thread 0x7fffbb7ff700 (LWP 7434)]
*** [ 16:30:55 | main ] Opened blockchain DB. Latest: eaa9eae946492b0d61a0819cbd33be8e9429fee840885341cc55910d2e4651a3
[Thread 0x7fffcdcaf700 (LWP 7431) exited]
[New Thread 0x7fffcdcaf700 (LWP 7435)]
[Thread 0x7fffcdcaf700 (LWP 7435) exited]
qrc:/qml/ProjectModel.qml:126:9: Unable to assign [undefined] to int

WARNING: This project is using the experimental QML API extensions for QtWebEngine and is therefore tied to a specific QtWebEngine release.
WARNING: The experimental API will change from version to version, or even be removed. You have been warned!

[New Thread 0x7fffcdcaf700 (LWP 7436)]
[New Thread 0x7fffa996e700 (LWP 7438)]
[New Thread 0x7fffa916d700 (LWP 7439)]
[New Thread 0x7fffa896c700 (LWP 7440)]
[New Thread 0x7fffa894b700 (LWP 7441)]
[New Thread 0x7fffa892a700 (LWP 7442)]
[New Thread 0x7fff929b2700 (LWP 7443)]
[New Thread 0x7fff921b1700 (LWP 7444)]
[New Thread 0x7fff919b0700 (LWP 7445)]
[New Thread 0x7fff911af700 (LWP 7446)]
[New Thread 0x7fff909ae700 (LWP 7447)]
[New Thread 0x7fff87ffe700 (LWP 7448)]
[New Thread 0x7fff877fd700 (LWP 7449)]
[New Thread 0x7fff86ffc700 (LWP 7450)]
[New Thread 0x7fff867fb700 (LWP 7451)]
[New Thread 0x7fff857f9700 (LWP 7453)]
[New Thread 0x7fff85ffa700 (LWP 7452)]
[New Thread 0x7fff84ff8700 (LWP 7454)]
[New Thread 0x7fff57d5a700 (LWP 7457)]
[New Thread 0x7fff57559700 (LWP 7458)]

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: Datei oder Verzeichnis nicht gefunden.

**Comment by CJentzsch** [comment]
Datei oder Verzeichnis nicht gefunden. = File not found.
It is working with root permissions.

**Comment by arkpar** [comment]
Can you run the "bt" command in gdb for a mode detailed backtrace?

**Comment by CJentzsch** [comment]
(gdb) run
Starting program: /home/christoph/software/Ethereum/cpp-ethereum/build/mix/mix 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
QML debugging is enabled. Only use this in a safe environment.
[New Thread 0x7fffdfda3700 (LWP 17289)]
[New Thread 0x7fffd6f83700 (LWP 17290)]
[New Thread 0x7fffd6782700 (LWP 17291)]
[New Thread 0x7fffce4b0700 (LWP 17293)]
[New Thread 0x7fffcdcaf700 (LWP 17294)]
[New Thread 0x7fffcd4ae700 (LWP 17295)]
[New Thread 0x7fffcccad700 (LWP 17296)]
[New Thread 0x7fffbb7ff700 (LWP 17297)]
*** [ 08:14:00 | main ] Opened blockchain DB. Latest: eaa9eae946492b0d61a0819cbd33be8e9429fee840885341cc55910d2e4651a3
[Thread 0x7fffcdcaf700 (LWP 17294) exited]
[New Thread 0x7fffcdcaf700 (LWP 17298)]
[New Thread 0x7fffab8ab700 (LWP 17299)]
[Thread 0x7fffcd4ae700 (LWP 17295) exited]
[Thread 0x7fffcdcaf700 (LWP 17298) exited]
qrc:/qml/ProjectModel.qml:126:9: Unable to assign [undefined] to int

WARNING: This project is using the experimental QML API extensions for QtWebEngine and is therefore tied to a specific QtWebEngine release.
WARNING: The experimental API will change from version to version, or even be removed. You have been warned!

[New Thread 0x7fffcdcaf700 (LWP 17300)]
[New Thread 0x7fffcd4ae700 (LWP 17302)]
[New Thread 0x7fffa916d700 (LWP 17303)]
[New Thread 0x7fffa896c700 (LWP 17304)]
[New Thread 0x7fffa894b700 (LWP 17305)]
[New Thread 0x7fffa8929700 (LWP 17306)]
[New Thread 0x7fff9a9b2700 (LWP 17307)]
[New Thread 0x7fff9a1b1700 (LWP 17308)]
[New Thread 0x7fff999b0700 (LWP 17309)]
[New Thread 0x7fff991af700 (LWP 17310)]
[New Thread 0x7fff989ae700 (LWP 17311)]
[New Thread 0x7fff8fffe700 (LWP 17312)]
[New Thread 0x7fff8f7fd700 (LWP 17313)]
[New Thread 0x7fff8effc700 (LWP 17314)]
[New Thread 0x7fff8e7fb700 (LWP 17315)]
[New Thread 0x7fff8d7f9700 (LWP 17316)]
[New Thread 0x7fff8dffa700 (LWP 17317)]
[New Thread 0x7fff8cff8700 (LWP 17318)]
[New Thread 0x7fff5fd5a700 (LWP 17321)]
[New Thread 0x7fff5f559700 (LWP 17322)]

Program received signal SIGSEGV, Segmentation fault.
strlen () at ../sysdeps/x86_64/strlen.S:106
106     ../sysdeps/x86_64/strlen.S: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff7b7c8a1 in QCoreApplication::arguments() ()
   from /opt/qt54/lib/libQt5Core.so.5
#2  0x00007fffe1b1bcc2 in ?? () from /opt/qt54/plugins/platforms/libqxcb.so
#3  0x00007fffe1b1c9a5 in ?? () from /opt/qt54/plugins/platforms/libqxcb.so
#4  0x00007fffe16bed37 in _SmcProcessMessage ()
   from /usr/lib/x86_64-linux-gnu/libSM.so.6
#5  0x00007fffe14af8c7 in IceProcessMessages ()
   from /usr/lib/x86_64-linux-gnu/libICE.so.6
#6  0x00007ffff7ba9031 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /opt/qt54/lib/libQt5Core.so.5
#7  0x00007ffff7c262be in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) () from /opt/qt54/lib/libQt5Core.so.5
#8  0x00007ffff7bb5ec9 in QSocketNotifier::event(QEvent*) ()
   from /opt/qt54/lib/libQt5Core.so.5
#9  0x00007ffff6e39eec in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /opt/qt54/lib/libQt5Widgets.so.5
#10 0x00007ffff6e3ef00 in QApplication::notify(QObject*, QEvent*) ()
   from /opt/qt54/lib/libQt5Widgets.so.5
#11 0x00007ffff7b797d5 in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /opt/qt54/lib/libQt5Core.so.5
#12 0x00007ffff7bd1a85 in ?? () from /opt/qt54/lib/libQt5Core.so.5
#13 0x00007ffff14f5e04 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff14f6048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff14f60ec in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff7bd0b4c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qt54/lib/libQt5Core.so.5
#17 0x00007ffff7b7773b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qt54/lib/libQt5Core.so.5
#18 0x00007ffff7b7eda6 in QCoreApplication::exec() ()
   from /opt/qt54/lib/libQt5Core.so.5
#19 0x0000000000657756 in main ()
(gdb)

**Comment by arkpar** [comment]
should be fixed in develop
