### ISSUE TITLE
[mix] doesn't show number of line with error

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#1118]
Tested on osx 10.9

mix doesn't show number of line with error.
If I press "see log" right panel is opened, but I still can't see where the error occurred

![screen shot 2015-02-23 at 16 39 04](https://cloud.githubusercontent.com/assets/2613714/6330674/9e4a528a-bb7a-11e4-86d5-7067c9aa3f96.png)

**Comment by arkpar** [comment]
Will fix, but for now L2 in the message means line 2

**Comment by debris** [comment]
ok, thanks!
