### ISSUE TITLE
Struct return values (question)

### ISSUE THREAD

**Issue by androlo** [ethereum/cpp-ethereum#1121]
I have this simple setup:

``` javascript
contract TestDep {
    struct TestStruct {
        address a0;
    }
    function getTestStruct() constant returns (TestStruct ts) {}
}

contract Caller {
    function testGetting(address addr){
        address a0 = TestDep(addr).getTestStruct().a0;   
    }   
}
```

This causes an error:

``` javascript
Exception during compilation: /home/user/cpp-ethereum/libevmcore/Instruction.h(214): Throw in function dev::eth::Instruction dev::eth::swapInstruction(unsigned int)
Dynamic exception type: N5boost16exception_detail10clone_implIN3dev3eth13InvalidOpcodeEEE
std::exception::what: std::exception
[PN3dev11tag_commentE] = Invalid SWAP instruction requested.
```

I assume this is because Caller does not know what 'TestStruct' is. Just want to make sure that I'm not messing something up since structs are returned just fine into javascript as an array of values. 

This is not an issue per se, as I can just as well return stuff as individual fields. Just curious.

**Comment by chriseth** [comment]
Structs are not yet supported as function (return) parameter types, although they should not cause such exceptions.

**Comment by iurimatias** [comment]
:+1: for return struct support

**Comment by iurimatias** [comment]
Is this supported now?

**Comment by chriseth** [comment]
It is not supported yet (and will probably take quite some time), but the bug is fixed.
