### ISSUE TITLE
Mix ~ Error creating new project on Windows (PoC8)

### ISSUE THREAD

**Issue by qualiabyte** [ethereum/cpp-ethereum#1122]
When running the latest PoC8 release of Mix on Windows 8.1 (be5c8b7),
I'm unable to create new projects or open existing ones.

Clicking on "File" > "New Project" does nothing,
but gives an error in the console.

It may be related to finding QtWebEngineProcess.exe,
or creating and loading files in the project directory.

Otherwise it started quite smoothly!

![mix - error creating project](https://cloud.githubusercontent.com/assets/532779/6343635/fd7e16bc-bba0-11e4-865a-c9d91806d0e1.png)

**Comment by arkpar** [comment]
Did you use the browse button to select a folder in a project creation dialog? 
Looks like it adds an extra "/" to the beginning of the selected path. If you delete it before clicking "OK" it should create the project. Will fix that.

**Comment by arkpar** [comment]
fixed in develop
