### ISSUE TITLE
Aleth does not recognize protected/private but online compiler does.

### ISSUE THREAD

**Issue by androlo** [ethereum/cpp-ethereum#1123]
Can't push contracts with `protected` functions anymore. I think it happened yesterday.

Also I think it's not possible to copy address by double clicking contracts right now, nor is there a right-click menu with the `copy` alternative.

**Comment by LefterisJP** [comment]
Solidity syntax, as is the whole language, is under quite heavy development so things are quite fluid at the moment. 

Protected functions got renamed to `inheritable`, and right soon after to `internal`. So the keyword you are looking for at the moment is `internal`. Here is the relevant PR: https://github.com/ethereum/cpp-ethereum/pull/1107

**Comment by androlo** [comment]
thanks. will keep up better with the prs/commits.
