### ISSUE TITLE
Mix ~ Missing return values from function calls

### ISSUE THREAD

**Issue by qualiabyte** [ethereum/cpp-ethereum#1124]
Hi! While testing Mix, I've been experiencing issues with getting undefined values when calling Solidity methods from JavaScript. It doesn't seem to happen with automatically generated accessors, only explicitly defined methods.

Here's a simple "Hello World" example where it occurs:
https://github.com/qualiabyte/open-source-economy/tree/master/examples/Hello

And screenshot:
![2015 02 24 mix - missing return value](https://cloud.githubusercontent.com/assets/532779/6346811/ca70a9fc-bbc7-11e4-8943-2b22544aef52.png)

In this case, I'm expecting getMessage() to return the "Hello, Mix!" string.
This is in VirtualBox using a Windows 8.1 host with an Ubuntu 14.04 guest.

**Comment by arkpar** [comment]
Javascript API currently does not allow returning values from functions that are not marked as constant.
Add a "constant" modifier to geMessage and it should work.

By the way, you don't need to create a contract object explicitly when developing in Mix. It is already exposed as window.contracts.Hello.contract
