### ISSUE TITLE
mix, event watch stops working after exception

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#1127]
Tested on mac 10.9

Events in mix are working properly (WebThreeStubServerBase.cpp eth_changed method is being called) until there is exception in javascript code.

```
*** [ 15:26:53 | main ] FIRING WATCH 0 1
qml: {"jsonrpc":"2.0","method":"eth_balanceAt","params":["0xc6d9d2cd449a754c494264e1809c50e34d64562b"],"id":269}
qml: {"id":269,"jsonrpc":"2.0","result":"0x"}

qml: http://localhost:8893/index.html:10:Uncaught TypeError: Cannot set property 'innerText' of null
*** [ 15:27:31 | <unknown> ] Closing blockchain DB
*** [ 15:27:31 | <unknown> ] Opened blockchain DB. Latest: 5c38f0e9d12c199878464e96e802129baa8936c39be68d232f3060d636fd7268
qml: {"jsonrpc":"2.0","method":"eth_uninstallFilter","params":[0],"id":270}
qml: {"id":270,"jsonrpc":"2.0","result":true}
```

Since this exception eth_changed is not being polled any more. 

Even if js code is fixed, eth_changed is not being called. Mix requires restart.

**Comment by debris** [comment]
steps to reproduce:
1. create contract with an event && function (which triggers this event)
2. create javascript code where you are listening to an event and call contract function
3. make sure, everything works
4. create a bug in javascript code
5. save javascript code
6. fix the bug
7. call contract function. event is not triggered.

**Comment by arkpar** [comment]
Need to restart poll function in web3.reset() somehow if it has stopped.
