### ISSUE TITLE
Contract Creation - creation of 2 contracts return the same address.

### ISSUE THREAD

**Issue by yann300** [ethereum/cpp-ethereum#1133]
Adresses generated in Executive.cpp in create(...) are differents..
will try to get in eth_transact, maybe the nonce is not incremented here: (WebThreeStubServerBase.cpp
toJS(right160(sha3(rlpList(t.from, client()->countAt(t.from))))); 

Using this rpc request:

var jsonRpcRequestId = 0;
					var requests = [];
					requests.push({
									  jsonrpc: "2.0",
									  method: "eth_transact",
									  params: [ { "gas": 20000, "code": "0x60056011565b600180601c6000396000f35b6008600081905550560000" } ],
									  id: jsonRpcRequestId++
								  });

					var jsonRpcUrl = "http://localhost:8080";
					var rpcRequest = JSON.stringify(requests);
					var httpRequest = new XMLHttpRequest();
					httpRequest.open("POST", jsonRpcUrl, true);
					httpRequest.setRequestHeader("Content-type", "application/json");
					httpRequest.setRequestHeader("Content-length", rpcRequest.length);
					httpRequest.setRequestHeader("Connection", "close");
					httpRequest.onreadystatechange = function() {
						if (httpRequest.readyState === XMLHttpRequest.DONE) {
							console.log(httpRequest.responseText);
							var requests = [];

							requests.push({
											  jsonrpc: "2.0",
											  method: "eth_transact",
											  params: [ { "gas": 20000, "code": "0x60056011565b600180601c6000396000f35b6009600081905550560000" } ],
											  id: jsonRpcRequestId++
										  });
							rpcRequest = JSON.stringify(requests);
							httpRequest = new XMLHttpRequest();
							httpRequest.open("POST", jsonRpcUrl, true);
							httpRequest.setRequestHeader("Content-type", "application/json");
							httpRequest.setRequestHeader("Content-length", rpcRequest.length);
							httpRequest.setRequestHeader("Connection", "close");
							httpRequest.onreadystatechange = function() {
								if (httpRequest.readyState === XMLHttpRequest.DONE) {
									console.log(httpRequest.responseText);
								}
							}
							httpRequest.send(rpcRequest);
						}
					}
					httpRequest.send(rpcRequest);

**Comment by yann300** [comment]
The nonce is incremented only when the block is mined (makes sense as for some reason the contract creation can fails).
It should be useful to include the ability to predict contract addresses if there is more than one creation.

**Comment by gavofyork** [comment]
You must wait until the transactionCount for the sender address is incremented.

watching on 'pending' will allow you to do this without polling.
