### ISSUE TITLE
mix - web3.eth.transact return not usable address

### ISSUE THREAD

**Issue by yann300** [ethereum/cpp-ethereum#1141]
The address returned by: 
web3.eth.transact({code: web3.eth.solidity(source)});
is not the same that the address displayed in the TransactionLog.

**Comment by gavofyork** [comment]
Correct - transact no longer blocks - it should only be used after it has been confirmed that the transaction has been accepted and run (i.e. transactionCount has been incremented on the sender address)

**Comment by arkpar** [comment]
That also means that contract address returned by js transact call is not reliable and can not be used in general case. Why not remove it from the API?

**Comment by debris** [comment]
fixed in #2404
