### ISSUE TITLE
Solidity- The "stack too deep" compiler errors are getting out of hand

### ISSUE THREAD

**Issue by drcode** [ethereum/cpp-ethereum#1145]
...I'm guessing you folks are starting to repurpose some EVM "stack registers" for alternate purposes, breaking existing contracts by progressively shortening the stack...

This contract compiled a couple of weeks ago, now gives the dreaded "stack too deep" all of a sudden: https://github.com/drcode/ethereum-order-statistic-tree/blob/master/OrderStatisticTree.sol

Is this regression expected? Is there any relief in sight (i.e. pushing stack data into memory?)
Or, is my best course of action to refactor my code for a lower stack depth?

Thanks for any tips!

**Comment by chriseth** [comment]
Basically every local variables occupies a slot on the stack. We plan to optimize this at some point, but we are not yet there.
It seems like Solidity has problems to compile `rotate` or `remove_helper`.
Is it possible to refactor them to use less local variables? You can introduce helper functions at almost no cost.

**Comment by chriseth** [comment]
This should compile now:
```
    function remove_helper(uint value) private {
        Node n=nodes[value];
        uint parent=n.parent;
        bool side=n.side;
        Node p=nodes[parent];
        uint left=n.children[false];
        uint right=n.children[true];
        if ((left == 0) && (right == 0)) {
            p.children[side]=0;
            zero_out(value);
            fix_parents(parent,side);
        }
        else if ((left !=0) && (right != 0)) {
            uint ipn=rightmost_leaf(left);
            Node i=nodes[ipn];
            remove_helper(ipn);
            n=nodes[value];
            parent=n.parent;
            p=nodes[parent];
            side=n.side;
            right=n.children[true];
            left=n.children[false];
            p.children[side]=ipn;
            i.parent=parent;
            i.side=side;
            i.count=n.count+i.dupes-n.dupes;
            i.height=n.height;
            if (left!=0) {
                i.children[false]=left;
                nodes[left].parent=ipn;
            }
            if (right!=0) {
                i.children[true]=right;
                nodes[right].parent=ipn;
            }
            zero_out(value);
            update_counts(ipn);
        }
        else {
            uint child=left+right;
            Node c=nodes[child];
            p.children[side]=child;
            c.parent=parent;
            c.side=side;
            zero_out(value);
            fix_parents(parent,side);
        }
    }
```

**Comment by drcode** [comment]
Thanks chriseth, thanks for the helpful info and the suggested fix- I will test this fix and update my repo (and will start using the static arrays shortly!)
