### ISSUE TITLE
BlockLimitGasReached?

### ISSUE THREAD

**Issue by simondlr** [ethereum/cpp-ethereum#1151]
Currently when I transact in in AlethZero, the default is that with one transaction it adds network fees that buys up all the gas in a block.

ie, fees are based on the gasLimit in the block.

This is not right is it? Although I get unused gas back, it means that if you wait a few seconds before clicking transact, the next block's limit might have decreased and thus results in an error specifying that I can't transact since BlockGasLimitReached.

EDIT:

Sorry, let me add. It makes more sense when gasPrice is variable that one can decide to buy up all the gas in a block with 1 transaction (its up to miners to accept it), but due to current gasPrice being so low in the test chains, it means that AlethZero is buying up all the gas with every transaction, which causes transactions to fail if you wait too long on a prompt.

**Comment by gavofyork** [comment]
blockgaslimit now targets ~3m gas so shouldn't be an issue any more.
