### ISSUE TITLE
Building on Ubuntu, package errors

### ISSUE THREAD

**Issue by tinybike** [ethereum/cpp-ethereum#1152]
Going through https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu and getting cpp-ethereum set up on my Xubuntu 14.04 machine.  I don't see either of these packages in my apt repositories:

libcryptopp-dev -- should be libcrypto++-dev

libjson-rpc-cpp-dev -- had to compile from source (https://github.com/cinemast/libjson-rpc-cpp)

Wanted to check to see if I'm maybe missing a ppa or something?

**Comment by gavofyork** [comment]
@caktux any ideas?

**Comment by caktux** [comment]
Probably an outdated issue, @tinybike can you confirm the latest instructions are working for you?
