### ISSUE TITLE
Serpent support removed in poc8?

### ISSUE THREAD

**Issue by janx** [ethereum/cpp-ethereum#1154]
Serpent code no longer compiles in poc8, no bytecodes given. Is this a bug or serpent support removed?

![selection_507](https://cloud.githubusercontent.com/assets/5958/6406967/5947b042-be72-11e4-8bb1-95687db45252.png)

**Comment by phaldenby** [comment]
I'm getting the same issue. 
I'm on v0.8.2 (windows and mac)

**Comment by LefterisJP** [comment]
try adding a comment on first line:
```
//ser
```

**Comment by phaldenby** [comment]
Thanks for the suggestion!
But looks like we haven't solved it yet..

![image](https://cloud.githubusercontent.com/assets/792272/6602330/6520436a-c7f1-11e4-8c09-8cd022f4de17.png)

![image](https://cloud.githubusercontent.com/assets/792272/6602769/2c176cee-c7f4-11e4-8712-3adc45dcdcee.png)

**Comment by janx** [comment]
@LefterisJP thanks it works.

@phaldenby I'm running rev 10839cf7423fe667352b07087d86ae68735f69f6
