### ISSUE TITLE
RPC concurrency 

### ISSUE THREAD

**Issue by arkpar** [ethereum/cpp-ethereum#1159]
Right now the json RPC mostly directly maps to the Client API we have in C++. And while the C++ API allows concurrent access, RPC does not, making some of the methods unusable in the environment where multiple clients can connect to a single RPC server. Two issues I've found so far:

1. Address returned by eth_transact on contract creation is not guaranteed to be the address that the contract will actually get, if multiple clients are creating transactions at the same time, making this value useless.

2. eth_setDefault  can not be used reliably, because it can be changed any time by any client. This can be resolved by moving this state variable from server to client, or by API refactoring.

**Comment by subtly** [comment]
Concurrency has been implemented in the ethereumx branch however that forgoes json-rpc. It provides multiplexing for concurrent requests and has "client" logic for setting state information such as the coinbase. Notably, the coinbase is universal and doesn't support mining to concurrent coinbases so one recommendation is that a confirmation dialogue is triggered for the coinbase to be modified. I can't say how difficult it would be to adopt this compared to a server-pool for json-rpc; guessing a server-pool for json-rpc may be more difficult unless it's supports out of the box.

**Comment by gavofyork** [comment]
both should be addressed with web3.js and API changes.
