### ISSUE TITLE
Aleth Stable/Dev Crashes on "Go" Connect (Win7 x64)

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/cpp-ethereum#1173]
Run in admin, w/ virus software off, roaming/ethereum cleared, MSVC x86 installed. Aleth boots fine, but the second I hit "Connect to Network" or "Go" I get a "alethzero.exe has stopped working". Feels like QT, is this normal or to be expected at this stage?

**Comment by subtly** [comment]
This should be fixed now. Does it still crash w/latest develop? (Note: Go node isn't always available to connect)

**Comment by gavofyork** [comment]
please test again on latest develop.

**Comment by debris** [comment]
Cannot reproduce anymore. Please reopen if it still occurs.
