### ISSUE TITLE
eth --db-path writes data to OS default

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/cpp-ethereum#1183]
When running `eth -d /tmp/ethereum -j -m on -f`, there is still some data being written to the OS default path:
```
$ ls -alF ~/Library/Application Support/Ethereum
total 8
drwxr-xr-x    4 mids  staff   136 Mar  2 16:37 ./
drwx------+ 111 mids  staff  3774 Mar  2 16:37 ../
drwxr-xr-x    8 mids  staff   272 Mar  2 16:37 .web3/
-rw-r--r--    1 mids  staff    55 Mar  2 16:37 config.rlp
```

I would expect that this `.web3` directory and `config.rlp` file to only be stored in the `--db-path` as specified as command line argument.

**Comment by gavofyork** [comment]
think that's fixed now.
