### ISSUE TITLE
natspec.js

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#1194]
few things to do with the natspec.js

* [x] move it to separate repository
* [x] accept transaction object as the input
* [x] decode transaction object params (using `ethereum.js` probably)
* [x] connect it with `WebThreeStubServer`
* [ ] pass ABI to natspec.js

**Comment by gavofyork** [comment]
this done yet?

**Comment by debris** [comment]
not completely. The ABI is still not passed to natspec.js

**Comment by debris** [comment]
#1245 refers to the same thing
