### ISSUE TITLE
Simple trace can dump a lot of memory

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#1196]
I think the amount of memory dumped by simple trace should be limited or optional.

The profiler shows that when executing VM SHA3 test memory dump consumes 99.9% of the runtime.
![trace_fail](https://cloud.githubusercontent.com/assets/573380/6466702/d0a4d8b8-c1c9-11e4-882a-0203586e237a.png)

**Comment by CJentzsch** [comment]
fixed by https://github.com/ethereum/cpp-ethereum/pull/1155/files (already merged)

**Comment by chfast** [comment]
Cool, but you forgot about `FakeExtVM`.

**Comment by CJentzsch** [comment]
fixes (PRs) are more than welcome :-)
