### ISSUE TITLE
Client-side routing works but doesn't update url

### ISSUE THREAD

**Issue by cslarson** [ethereum/cpp-ethereum#1215]
Not really an important issue but it would be nice if the url updated to reflect the current client-side route.

**Comment by gavofyork** [comment]
please give more information.

**Comment by cslarson** [comment]
On further inspection it seems as though the URL bar in the Alethzero browser doesn't update correctly. Using the Alethzero browser:
1. paste "http://en.wikipedia.org/wiki/Main_Page" into the URL bar
2. click on any link on that page
3. the browser now shows that new page but the address in the url bar has not changed and still shows "http://en.wikipedia.org/wiki/Main_Page".

I've tested this on both the master branch and develop branch. I use a linux os based on Ubuntu 14.04.
