### ISSUE TITLE
Alethzero and command line eth are inconsistent

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1217]
I ran "rm -rf ~/.ethereum" and am local mining several blocks with  ```./eth -a <address> -j -m on -f```
Now when I run ./alethzero, the coinbase is correct but balance is 0, and AZ doesn't show any of the blocks that was mined by the ./eth command line.

Did I miss something?  (I checked with others and we think it's a bug)

**Comment by androlo** [comment]
agree. it's maybe intentional, and certainly no big issue, but if the change is a simple one then i'd support. are you running latest dev btw? having some issues lately, seems to be related to mining. race conditions most likely.

**Comment by ethers** [comment]
@androlo This was filed on f4c93bb.  Probably open another issue with what you are currently seeing.  I disagree and think that the inconsistency is a big issue, from both user experience (eg where is the blockchain eth command line is using if it uses a different one) and developer experience (eg how to use Alethzero debugger on a contract created via eth command line).

**Comment by ethers** [comment]
I also exported the private key from AZ, and used it on ./eth using -s switch and ./eth is still using a different blockchain than AZ.  Below is now using same address as AZ 29d33c02a200937995e632c4597b4dca8e503978, but gets NotEnoughCash.

```
--- [ 14:17:20 | main ] Spawning eth
Address: 
29d33c02a200937995e632c4597b4dca8e503978
--- [ 14:17:20 | main ] startWorking for thread p2p
--- [ 14:17:20 | main ] Spawning p2p
--- [ 14:17:20 | p2p ] startWorking for thread ethsync
--- [ 14:17:20 | p2p ] Spawning ethsync
--- [ 14:17:20 | p2p ] startWorking for thread anon
--- [ 14:17:20 | p2p ] Spawning anon
--- [ 14:17:20 | main ] startWorking for thread eth
--- [ 14:17:20 | main ] startWorking for thread miner-0
--- [ 14:17:20 | main ] Spawning miner-0
--- [ 14:17:20 | main ] startWorking for thread miner-1
--- [ 14:17:20 | main ] Spawning miner-1
--- [ 14:17:20 | main ] startWorking for thread miner-2
--- [ 14:17:20 | main ] Spawning miner-2
--- [ 14:17:20 | main ] startWorking for thread miner-3
--- [ 14:17:20 | main ] Spawning miner-3
*** [ 14:17:20 | eth ] New block on chain: Restarting mining operation.
*** [ 14:17:20 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
*** [ 14:17:22 | p2p ] UPnP device: http://ip/InternetGatewayDevice.xml [st: urn:schemas-upnp-org:device:InternetGatewayDevice:1 ]
*N* [ 14:17:22 | p2p ] Punched through NAT and mapped local port 30303 onto external port 30303 .
*N* [ 14:17:22 | p2p ] External addr: <ip>
*N* [ 14:17:22 | p2p ] p2p.started id: a38bc91f…
--- [ 14:18:04 | <unknown> ] startWorking for thread eth
*** [ 14:18:04 | <unknown> ] New transaction {[CREATE]/0$0+3000000@10000000000000<-29d33c02… #5810}
!!! [ 14:18:04 | eth ] Sync went wrong
cpp-ethereum/libethereum/Executive.cpp(97): Throw in function bool dev::eth::Executive::setup()
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::NotEnoughCash>
std::exception::what: std::exception
[dev::tag_required*] = 30000000000000000000
[dev::tag_got*] = 0
```

Go CLI and Mist both operate on the same blockchain, and suggest the same consistent behavior for cpp ./eth and AZ.  Perhaps an extra cmd line flag to ./eth, say --newChain, can be added if a separate blockchain from ./eth and AZ is desired; but default behavior would be for both to use the same chain like Go does.

**Comment by ethers** [comment]
nice thanks!
