### ISSUE TITLE
Block 5475

### ISSUE THREAD

**Issue by mike80439** [ethereum/cpp-ethereum#1219]
Unknown parent of block!!! ca45542a… /tmp/ethereum-1MLtd4/libethereum/BlockChain.cpp(243): Throw in function h256s dev::eth::BlockChain::import(const bytes &, const dev::OverlayDB &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception

**Comment by gavofyork** [comment]
did this cause a crash? how can it be reproduced?
