### ISSUE TITLE
Solidity: ETA on msg.sig?

### ISSUE THREAD

**Issue by simondlr** [ethereum/cpp-ethereum#1221]
Hi. I see on the pivotal tracker that msg.sig was been planned since January. What is the ETA on this? Would be very useful.

I want to get the function signature from msg.data, but can't do it yet (or I'm missing something).

**Comment by chriseth** [comment]
It is the next unstarted story. We are currently having problems with out work-in-progress, but apart from that, it should not take long.
You can get msg.sig from msg.data (as an integer), though:
`(((uint(msg.data[0]) * 256 | uint(msg.data[1])) * 256 | uint(msg.data[2])) * 256 | uint(msg.data[3])`

**Comment by simondlr** [comment]
Ah, that helps in the meanwhile! Was wondering how to get to msg.sig from msg.data. Thanks @chriseth

**Comment by simondlr** [comment]
I see it has been implemented. Thank guys!

**Comment by chriseth** [comment]
Thanks for grooming our issues :-)
