### ISSUE TITLE
Clicking mine, hangs AlethZero, on OS X.

### ISSUE THREAD

**Issue by simondlr** [ethereum/cpp-ethereum#1244]
Not sure if related to https://github.com/ethereum/cpp-ethereum/issues/1176, https://github.com/ethereum/cpp-ethereum/issues/1189 or https://github.com/ethereum/cpp-ethereum/issues/1185.

No additional logs (have to force quit). It just starts hanging when I click "mine" in AlethZero. Based on revision: 35ad8b70b4e4e30c2602a3e5ccf5b8bb00ec2f57

**Comment by mtbitcoin** [comment]
Click connect/go in Windows for the latest "Windows 32-bit, cutting-edge" causes it to hang. Not sure if this is related ?

**Comment by androlo** [comment]
been this way all weekend on linux for me as well.

**Comment by gavofyork** [comment]
duplicate of #1362
