### ISSUE TITLE
natspec evaluation

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#1245]
connect natspec.js properly in [OurWebThreeStubServer.cpp](https://github.com/ethereum/cpp-ethereum/blob/develop/alethzero/OurWebThreeStubServer.cpp#L134-L135) and/or in [Transact.cpp](https://github.com/ethereum/cpp-ethereum/blob/develop/alethzero/Transact.cpp#L253-L254). By saying 'properly' i mean, pass to the NatspecExpressionEvaluator constructor abi, transation object && called method name.

**Comment by gavofyork** [comment]
this done now?

**Comment by chriseth** [comment]
Still not done yet? @debis?

**Comment by debris** [comment]
natspec evaluation is done. We just do not have a storage/database for natspecs.

**Comment by LefterisJP** [comment]
Then perhaps close this issue and open a more specific issue for the storage/database?
