### ISSUE TITLE
[eth] mining on Win32 fails.

### ISSUE THREAD

**Issue by Genoil** [ethereum/cpp-ethereum#1267]
Built eth on Win32. After succesfully generating the 1GB dagger dataset it starts mining, but when a block is found, assertion fails at ProofOfWork.cpp:91 
```
assert(verify(test)); 
```
That boils down to Ethasher.cpp:105: 
```
return (u256)e.value <= boundary && e.mixHash == _header.mixHash; 
```
both of these expressions evaluate to false.

**Comment by gavofyork** [comment]
please check latest develop.

**Comment by Genoil** [comment]
it works now. thanks for responding.

**Comment by Genoil** [comment]
Sorry, jumped the gun there. It did start to mine after rebuilding the latest develop, but on subsequent launches, I get the same assertion issue in

ProofOfWork.cpp
```
assert(Ethasher::eval(_header, (Nonce)(u64)tryNonce).value == val);
```

As I was stepping through the code while it was running, I noticed that in ethash_hash(...) the full_nodes parameter actually contained data, but in the subsequent launches, it is always NULL. 

I'm sorry I can't be more specific, I'm just a tiny bit beyond staring at this code in awe ...

**Comment by Genoil** [comment]
I found the culprit. It's in CommonIO.cpp::writeFile. Win32 requires the ios::binary flag when writing out the dag file.
