### ISSUE TITLE
Logs don't seem to work

### ISSUE THREAD

**Issue by frozeman** [ethereum/cpp-ethereum#1269]
Using ethereum.js i want to get logs for my coinbase adress with 11 outgoing transactions, but i get none:

```js
web3.eth.getTransactionCount(web3.eth.coinbase)
// 11
var test = web3.eth.filter({fromBlock: 1, address: web3.eth.coinbase});
// undefined
test.watch(function(res){console.log(res)});
// undefined
test.get()
// []
```

**Comment by gavofyork** [comment]
logs only work with the LOG* instructions (i.e. they're only applicable to contracts). there is *no way whatsoever* of generally and automatically determining if/when a standard address can been transacted with through ethereum.js - if you need this functionality use a contract.
