### ISSUE TITLE
boost::exception_detail::clone_impl<dev::BadHexCharacter> with basic hex.

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/cpp-ethereum#1291]
Clean Ubuntu 14 VMWare, with stable cpp-ethereum from PPA. etheum.js->Eth CLI.

$ eth -j -b -f -n no -m yes
[...]
*** [ 19:24:18 | <unknown> ] New transaction {[CREATE]/3$0+992212@10000000000000<-ddd41bfc… #0}
*** [ 19:24:19 | eth ] Additional transaction ready: Restarting mining operation.
*** [ 19:24:19 | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
!!! [ 19:24:33 | <unknown> ] /build/buildd/cpp-ethereum-0.8.2+23trusty/libdevcore/CommonData.cpp(78): Throw in function int dev::fromHex(char)
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadHexCharacter>
std::exception::what: std::exception
[dev::tag_invalidSymbol*] = N

!!! [ 19:24:33 | <unknown> ] /build/buildd/cpp-ethereum-0.8.2+23trusty/libdevcore/CommonData.cpp(78): Throw in function int dev::fromHex(char)
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadHexCharacter>
std::exception::what: std::exception
[dev::tag_invalidSymbol*] = N

sol:
contract test {  function multiply(uint a) returns(uint d) { return a * 7; }}

hex of multiply contract, compiled with Aleth, from ethereum.js Examples (i.e. contract.js):
603580600c6000396000f30060003560e060020a90048063c6888fa114601557005b601e6004356028565b8060005260206000f35b600081600702905091905056

Is this hex bad, or is there something else going on here?

**Comment by gavofyork** [comment]
what did you do immediately prior to the exception?

**Comment by chriseth** [comment]
Closing due to missing information.
