### ISSUE TITLE
poc9 Alethzero compiler/debugger seems broken

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1302]
In AZ commit f4fb199

Paste this lll as data for a New Transaction:
```
(return 0 
  (lll 
    (with '__funid 
      (div (calldataload 0) 
        26959946667150639794667015087019630673637144422540572481103610249216
      )
      (unless (iszero (eq (get '__funid) 3264763256)) 
        (seq 
          (set '_temp_421 13)
          (return (ref '_temp_421) 32)
        )
      )
    )
    0
  )
)
```
The intent of the code is to simply return 13.

The bottom of Alethzero shows this code which has lost 13 (0xd)
```
Code
PUSH1 0x2 DUP1 PUSH1 0xc PUSH1 0x0 CODECOPY PUSH1 0x0 RETURN STOP PUSH1 0xe0 
Hex
600280600c6000396000f30060e0
```

So the contract, instead of returning 13, is returning 60 e0:
RETURN
0000 `?               60 e0

Note: you can obtain the above lll via putting this code in a file and running ``serpent compile_to_lll <file>``
```
def foo():
    return(13)
```

**Comment by gavofyork** [comment]
that is not valid lll; it's vitalik's flavour (`with` is one of vitalik's serpent-specific additions).

if you use:

```
(return 0 
  (lll 
        (seq 
          (set '_temp_421 13)
          (return (ref '_temp_421) 32)
        )
    0
  )
)
```

it works as expected.
