### ISSUE TITLE
Crash when operating browser or mining

### ISSUE THREAD

**Issue by MrChico** [ethereum/cpp-ethereum#1303]
The latest version of alethzero for windows (network protocol 56; client database 7) shuts down when I try to connect to a network or open a page in the browser. In the command prompt I see the following message: UPnP device not found. I am running windows 8.1 and am not experiencing any problems on the stable version

![upnp device not found](https://cloud.githubusercontent.com/assets/8930559/6628615/4dd2426e-c907-11e4-8f00-41b00e51b63d.png)

**Comment by subtly** [comment]
There is an option to disable UPnP in the Network menu. If this is unchecked, does AlethZero still crash?

Also helpful. What is the model of the router connected to the computer?

**Comment by MrChico** [comment]
If I uncheck UPnP in Network menu, it no longer crashes when I press Go! in network menu, but still when I try to open anything in the browser or mine.
The router is Belkin N600 DB Wireless Dual-Band N+ Router

**Comment by SilentCicero** [comment]
I get the same.

**Comment by gavofyork** [comment]
does this issue remain?

**Comment by gavofyork** [comment]
assuming fixed - please reopen with more information if not.
