### ISSUE TITLE
AZ: Allow configuration of GasPricer

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1305]
In Alethzero commit f4fb199, choose New Transaction and paste this code for data:
```
(seq 
          (set '_temp_421 13)
          (return (ref '_temp_421) 32)
        )
```
Now change the default gas price to 9 szabo, and click Execute.  The contract does not show up in the pending transactions, and it cannot be mined into the blockchain.

If you set the gas price back to 10 szabo and click Execute, the contract can be mined into the blockchain.

**Comment by ethers** [comment]
maybe another UI needs to be added to AZ?
Per @CJentzsch  The interface is for changing the gasPricer is there in Client.h but as far as I can see currently not avaiable in Alethzero.

**Comment by ethers** [comment]
suggestion/reminder in the new UI is to use finney, instead of szabo for gasprice.  This would align with upcoming guides that primarily stick with "finney" and "ether".  So example UI would have 0.01 finney, instead of 10 szabo.

**Comment by gavofyork** [comment]
sure - that's really an enhancement though.

**Comment by gavofyork** [comment]
latest ui for this doesn't use szabo
