### ISSUE TITLE
Source location problems with parenthesized expressions

### ISSUE THREAD

**Issue by chriseth** [ethereum/cpp-ethereum#1307]
Expressions like `(a + (a - b)) ^ 2` get parsed correctly but the source location of e.g. the addition is `a + (a - b`, i.e. it does not include the closing parenthesis. This is due no the fact that the end location is set to be equal to the end location of the subtraction. A refactoring to how the end locations are set might be needed here.

**Comment by gavofyork** [comment]
guessing this is fixed?

**Comment by chriseth** [comment]
No, not fixed.

**Comment by LianaHus** [comment]
This issue has been moved to ethereum/solidity repository:
https://github.com/ethereum/solidity/issues/9
