### ISSUE TITLE
Stack size is too small on Windows

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#1313]
By default binaries built by MSVC have 1MB stack size. It's too small to handle max 1024 call depth. In Debug build I need to increase it to something between 16 ~ 32 MB. The proper configuration options should be added to build scripts.

**Comment by winsvega** [comment]
Also got a crash "bad allocation" on line:
m_fulls[_header.seedHash()] = bytesRef(new byte[p.full_size], p.full_size);
with p.full_size = 1073739904

I've set Stack Reserve Size to: 100000000
