### ISSUE TITLE
Alethzero contracts are not displayed in contract pane / window

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1317]
In AZ 23b5398, create trivial contract with the following code/data: it correctly shows up in pending transactions.  Now mine it to a block.

```
(seq 
          (set '_temp_421 13)
          (return (ref '_temp_421) 32)
        )
```

After it is mined, the contract is not displayed in the Contract pane / window.

**Comment by TYDIRocks** [comment]
I'm also getting this problem. Once moved from pending it seems to dissappear.

**Comment by caktux** [comment]
This also affects eth/neth, and valid, mined contracts aren't just not displayed, they simply don't get stored on the chain. There's also no account addresses whatsoever.

**Comment by ethers** [comment]
Contracts not displayed are still an issue.
But if you're contract is not getting stored on the chain, try bumping up the gas: I observed even with the trivial example above, the default/computed gas setting in AZ was insufficient, and bumping it up and using the rpc eth_getData confirmed that the contract did get stored on the chain.

**Comment by caktux** [comment]
I'm not using AZ for this, so that is another issue about computed gas, or that same issue could be more serious in that the contracts do get accepted and mined but not included because of such gas issue.

**Comment by gavofyork** [comment]
Yeah I'd love to put in a quick fix, but at present it's *very* difficult to determine a sensible hard minimum and resetting the value to a "suggested" maximum amount every keypress would be plain annoying.

**Comment by TYDIRocks** [comment]
@gavofyork Do you have any recommendations for where I can work on developing contracts for now then? I'm getting an error in Mix too. I'm very excited to start developing.

**Comment by gavofyork** [comment]
Should be better in AZ now - I increased the default minimum to 1/10th of the gas left in the block. Mix should be best for development though - if not, please report issues as you find them.

**Comment by gavofyork** [comment]
Works For Me™.

@ethers please retry with latest develop.

**Comment by ethers** [comment]
Still not seeing mined contracts in the pane / window using develop branch 46f10bf
#1403

**Comment by TYDIRocks** [comment]
Same here. In fact it doesn't even go into the pending window for me now, even though I'm providing enough gas.

**Comment by ethers** [comment]
@TYDIRocks does coinbase have enough balance?  eg #1322 was just closed recently

**Comment by TYDIRocks** [comment]
@ethers Seems the incorrect amount of gas was entered. Anyways now I'm getting that the block is malformed, so adding a contract screws up the entire chain. Can't mine on that chain after that.

**Comment by ethers** [comment]
To reset the chain, in AZ choose Special->Kill Blockchain

**Comment by TYDIRocks** [comment]
Yeah I know, but the contract kills every chain so I can't really do anything with AZ until this is fixed.

**Comment by ethers** [comment]
if your concerns aren't resolved by issues like 1403, you may want to open a new issue
