### ISSUE TITLE
Cannot get after block #701 on OSX

### ISSUE THREAD

**Issue by chevdor** [ethereum/cpp-ethereum#1320]
I am using fef4ed9f154b169e43571e4d2e2a50efa0a8e105 and for about a week, I cannot get after block 701. 

It usually stops at ```Terminating discover after 2 rounds```

**Comment by gavofyork** [comment]
not sure if there was more that 701 to get :-)

please retry with latest develop and mine.

**Comment by chevdor** [comment]
Ah. There was a reset? If so, that explains :))) I will test again and
update.
