### ISSUE TITLE
natspec fails building on osx

### ISSUE THREAD

**Issue by chevdor** [ethereum/cpp-ethereum#1321]
I am getting a compile error here:
```
private:
    friend class QJSValuePrivate;
    // force compile error, prevent QJSValue(bool) to be called
    QJSValue(void *) Q_DECL_EQ_DELETE;
```
which for some reason the comment seems to be suggesting this is expected.

**Comment by gavofyork** [comment]
still have this problem?

**Comment by chevdor** [comment]
I just got the develop version and yes I still have the issue.

**Comment by debris** [comment]
reason was 2 qt versions (4 && 5) installed at the same time

**Comment by chevdor** [comment]
:+1: fix was simply to uninstall qt to have only qt5 left:
````
brew uninstall qt
`````
