### ISSUE TITLE
eth_getCode returns "0x" with no errors on contract creation

### ISSUE THREAD

**Issue by caktux** [ethereum/cpp-ethereum#1322]

**Comment by ethers** [comment]
Just a suggestion is to also try eth_getData (eth_getCode is no longer on the wiki https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgetdata )

**Comment by caktux** [comment]
The wiki is outdated, `eth_getData` was removed in 4495de3 and there's only `eth_getCode`

**Comment by gavofyork** [comment]
Just tested: this works 100% for me on latest develop. Please give complete minimum viable test from empty blockchain with all instructions required to reproduce.

**Comment by caktux** [comment]
Create a contract, leave it in pending transactions, call eth_getCode with the contract's address and pending as defaultBlock. No gas exceptions or any other error, so if the issue is elsewhere, that fails silently as well.

**Comment by jorisbontje** [comment]
@caktux couldn't reproduce:

using cpp-ethereum develop commit bbcd9bf
deleted my Ethereum directory
started node with `eth -j -s 0xc85ef7d79691fe79573b1a7064c19c1a9819ebdbd1faaab1a8ec92344438aaf4 -m off`
Test HTML used https://gist.github.com/jorisbontje/445851f9cb50054d7604

after creating the contract, 'getCode' always returns the contract bytecode in the console.

**Comment by caktux** [comment]
then the issue lies deeper, more complex contracts / serpent compiled evm fail silently while returning a contract address

**Comment by gavofyork** [comment]
please provide minimum failing test case.

**Comment by gavofyork** [comment]
are you sure you're not running into the deposit cost?

re run in AZ develop and it'll mention it (i just put a lot of this transaction debugging info in with the `ExecutionResult` class).

**Comment by caktux** [comment]
Yep, that was it, thanks. There really needs to be an exception being raised when that happens, having contract creation silently fail like that really is a problem. I'll open a different issue as this one is just a side effect.

**Comment by joeykrug** [comment]
Am getting this same issue on both geth and Alethzero, spent a bunch of time on this until caktux explained this error.  Even a simple message such as "Hey, your contract returned 0x, you probably didn't send enough gas" & a more accurate calculator would be great

**Comment by gavofyork** [comment]
AlethZero's transact now includes both accurate gas calculation and according message if not enough gas for contract creation supplied.

See #1598 for a more expansive solution.
