### ISSUE TITLE
User-augmented whisper identity removal

### ISSUE THREAD

**Issue by frozeman** [ethereum/cpp-ethereum#1324]
For the RPC tests i create whisper identities. But in the long run this creates a lot, which are all stored.

We need a way to remove them once in a while.
Also you should be aware that the RPC tests won't always have access to node it tests. When we later run in on a build bot, the nodes will probably run somewhere else.

We should also create a separate repo for those kind of cross implementation issues, otherwise they will only be discussed inside the respective group (GO, cpp, python etc..)

**Comment by gavofyork** [comment]
Should only be user that can remove them; this probably requires LRU timestamping and additional UI.

**Comment by chriseth** [comment]
Closing as out of scope.
