### ISSUE TITLE
core dumped in BlockChain::treeRoute

### ISSUE THREAD

**Issue by youlian** [ethereum/cpp-ethereum#1334]
alethzero: cpp-ethereum/libethereum/BlockChain.cpp:461: dev::h256s dev::eth::BlockChain::treeRoute(dev::h256, dev::h256, dev::h256*, bool, bool) const: Assertion `_to' failed.
Aborted (core dumped)

git show HEAD
commit bbcd9bf6a352ed03878d63d59ef0118408b1c64a
Merge: 2100951 2589570

**Comment by gavofyork** [comment]
Looks like you've a bad blockchain - could you tar up your
.ethereum/AlethZero directory and upload it for me to get?

Also, what did you do to get this?

Gav.

On 17 March 2015 at 01:53, youlian <notifications@github.com> wrote:

> alethzero: cpp-ethereum/libethereum/BlockChain.cpp:461: dev::h256s
> dev::eth::BlockChain::treeRoute(dev::h256, dev::h256, dev::h256*, bool,
> bool) const: Assertion `_to' failed.
> Aborted (core dumped)
>
> git show HEAD
> commit bbcd9bf
> <https://github.com/ethereum/cpp-ethereum/commit/bbcd9bf6a352ed03878d63d59ef0118408b1c64a>
> Merge: 2100951
> <https://github.com/ethereum/cpp-ethereum/commit/21009510a66211a2d968b69af2a3b3054beadebc>
> 2589570
> <https://github.com/ethereum/cpp-ethereum/commit/2589570d9a523c37a49572b0b35cff9b46f81101>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/cpp-ethereum/issues/1334>.
>



-- 
Gav Wood

**Comment by youlian** [comment]
i did nothing. regarding .ethereum folder. i always delete the old one. so nothing there. don't i start clean then? 
then i just pull, compile. start alethzero and get a core dumped. from scratch.

**Comment by gavofyork** [comment]
could you retry with latest develop?

**Comment by youlian** [comment]
just did. still the same, namely, copy & paste;
BlockChain.cpp:460: dev::h256s dev::eth::BlockChain::treeRoute(dev::h256, dev::h256, dev::h256*, bool, bool) const: Assertion `_to' failed.
Aborted (core dumped)
-----------------------------------------------------
uname -a
3.16.0-29-lowlatency #39-Ubuntu SMP PREEMPT Tue Dec 16 21:12:19 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
gcc -v
Target: x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) 
-----------------------------------------------------
META: the feeling that it's getting flakier and flakier is getting overwhelming, unfortunately... my senses have been tested for over a quarter of a century of software crafting, so the feeling might not be entirely baseless... you know

**Comment by youlian** [comment]
btw noticed the following weird block appear, after i have deleted the .ethereum folder. is that normal?
~~~~~
fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca
#0   Wed 31 Dec 1969 07:00:00 PM EST
D/TD: 131072/131072 = 2^17/2^17
   Children: 0
Gas used/limit: 0/3141592
Beneficiary: 0000000000000000000000000000000000000000
Seed hash: 0000000000000000000000000000000000000000000000000000000000000000
Mix hash: 0000000000000000000000000000000000000000000000000000000000000000
Nonce: 000000000000002a
Hash w/o nonce: 6c09f5ade6a10c8346b3db76d1fada3abb447149c5e6d4530ad041c5fa517bd5
Difficulty: 131072
Proof-of-Work: Phil has nothing to prove
Parent: It was a virgin birth
Log Bloom: Uneventful
Transactions: 0 @56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
Uncles: 0 @1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
Pre: Nothing is before Phil
Receipts: @56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421:
Post: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e
Dump: f901f3a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a09178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4ea056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008302000080832fefd8808080a0000000000000000000000000000000000000000000000000000000000000000088000000000000002a
Receipts-Hex: c0
~~~~~

**Comment by gavofyork** [comment]
well that's the genesis block, so not really supposed to appear "normal".

try with:
`cmake .. -DCMAKE_BUILD_TYPE=Debug -DVMTRACE=0 -DPARANOIA=0 -DEVMJIT=0`?
