### ISSUE TITLE
eth --address does not work

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1352]
Usage eth [OPTIONS] <remote-host>
Options:
    -a,--address <addr>  Set the coinbase (mining payout) address to addr (default: auto).

Seems broken since eth keeps using address f52a423ecad0b6c70b5adf69edbe51b9db11c7c9 regardless of -a or --address option.
```
eth --address 32ad27653e4df5d81728d16d8e251fee34f53d30 -j -m on -f
```
Ethereum (++) 0.9.1
  Code by Gav Wood et al, (c) 2013, 2014, 2015.
  Based on a design by Vitalik Buterin.

*N* [ 15:29:08 | main ] IP Address: <ip>  = [LOCAL]
*N* [ 15:29:08 | main ] Id: a38bc91fcded45ed499337411ab7ebf804f4e566da6a911b323ed21765cba723d37ac65b0db0989d0de27a3f2e67fdc89da2b02a57c7b2817a0923e115e8cc7f
*** [ 15:29:08 | main ] Opened blockchain DB. Latest: e66c1d9559864a00f3b0e4dfd4af9f00e3adc3adda377100d6b85b8e65ba0068
*** [ 15:29:08 | main ] Opened state DB.
*** [ 15:29:12 | main ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000 } )
--- [ 15:29:13 | main ] startWorking for thread eth
--- [ 15:29:13 | main ] Spawning eth
Address: 
#### f52a423ecad0b6c70b5adf69edbe51b9db11c7c9

**Comment by gavofyork** [comment]
Fixed in 2c9c4ba..7b6710a
