### ISSUE TITLE
RPC returning malformed hex

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1354]
Develop commit b54134a
Mine this contract:
```
def foo(inStr:str):
    return(inStr)
```

The bytecode via serpent compile is:
61006d8061000e60003961007b56600060ff537c01000000000000000000000000000000000000000000000000000000006000350463f31a696981141561006b5760246004358080602001599059016000905281815260208101905090506040528082604051378082019150505060405160e052602060e0f35b505b6000f3

make a call() to foo('test'), here's the ABI data:
0xf31a6969000000000000000000000000000000000000000000000000000000000000000474657374

Here's the response with malformed result:
```
{"id":4,"jsonrpc":"2.0","result":"0x{5629, 0000000000000000000000000000000000000000, 0000000000000000000000000000000000000000000000000000000000000120}"}
```

For reference, here's the request payload:
{"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0x29d33c02a200937995e632c4597b4dca8e503978","gas":"0x7a120","to":"0xb8e116ddf8b8d451e04c5733a96a853b9036e883","data":"0xf31a696900000000000000000000000000000000000000000000000000000000000000047465737400000000000000000000000000000000000000000000000000000000","gasPrice":"0x0","value":"0x0"},"latest"],"id":4}

**Comment by jorisbontje** [comment]
Having the same issue with 497dff0
