### ISSUE TITLE
web3.eth.filter watch not working

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1361]
On develop branch commit 497dff0

filter watch just returns 0: here's the JS console output from Chrome:

```
Object {address: "0x0000000000000000000000000000000000000000", data: "0x", hash: "0x0000000000000000000000000000000000000000000000000000000000000000", number: 0, topics: Array[0]}
```

The code is simply what's in the docs:
```
web3.eth.filter('pending').watch(function (log) {
  console.log(log);
});

web3.eth.filter('latest').watch(function (log) {
  console.log(log);
});
```

A week or 2 ago, some data was being returned.

**Comment by gavofyork** [comment]
this is by design. you'll get pertinent information if you filter for specific logs. catch-all events like  "pending" or "latest" will just give you a callback. @debris this terminology is removed in the latest ethereum.js, no?

**Comment by debris** [comment]
so `web3.eth.filter('pending')` &&` web3.eth.filter('latest')` are still there. And they do trigger callback with data following data on new block/pending: 
```
Object {address: "0x0000000000000000000000000000000000000000", data: "0x", hash: "0x0000000000000000000000000000000000000000000000000000000000000000", number: 0, topics: Array[0]}
```

So everything works as expected.
