### ISSUE TITLE
suggestion: eth cmd line option to kill blockchain

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1367]
Similar to AZ option Special->Kill Blockchain

Or are there specific files/directories that can be manually deleted, without deleting entire ~/.ethereum and thus needing to re-create the ethash dag?

**Comment by subtly** [comment]
I'm not fully up to speed on pow changes but this would be useful for system testing.

If the dag is based on genesis hash (?) then it'll have to be reset for testnets; alternatively, a naming scheme can be employed such that the dag is <genesisHash>.dag (or whatever extension is). First pass it'll simply reset the blockchain+dag (sysadmins can script stopping eth and renaming the dag before calling this method).

**Comment by gavofyork** [comment]
note: if you want to kill the DAG, just `rm -f ~/.ethash`
