### ISSUE TITLE
core dump: Assertion `sha3(_code) == m_codeHash' failed

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1372]
Built develop commit 0ff3080 and was sending a transaction that I believe was successfully being sent with prior build.  Got this:
```
*** [ 17:20:20 | <unknown> ] New transaction {3f6559ff…/61$0+3000000@10000000000000<-f52a423e… #1258}
eth: cpp-ethereum/libethereum/Account.h:163: void dev::eth::Account::noteCode(dev::bytesConstRef): Assertion `sha3(_code) == m_codeHash' failed.
[1]    27048 abort (core dumped)  ./eth/eth -j -m on
```
If more info needed, pls let me know what's needed (eg how to get a backtrace)

**Comment by gavofyork** [comment]
i need everything required to reproduce.

**Comment by ethers** [comment]
IIRC I was able to repro this on ( 0ff3080 ) by simply calling getCode RPC (unable to confirm currently since eth core dumps #1381 ) as in:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getCode","params":["0x3f6559ff5bc12ff5cf7cff65b656f4466880ac4e", "latest"],"id":1}' http://localhost:8080
```   

With eth running, getCode should have just returned 0x because I had mistakenly used an address that only has code when running Alethzero.  Here is the result of getCode against AZ:
http://pastebin.com/wKNdQL7f

**Comment by ethers** [comment]
on develop e904462 i've been able to run eth cli and not seeing this anymore.  Since eth and AZ are now using the same blockchain, this may have existed in an intermediate state as eth and AZ were "converted" to use share the same blockchain (https://github.com/ethereum/cpp-ethereum/issues/1217)
