### ISSUE TITLE
eth_getFilterChanges returning [null] on initial call on `latest` block filter

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/cpp-ethereum#1383]
Initial call to `eth_getFilterChanges` on `latest` block filter returns `[null]`. Subsequent calls return as expected.

Request:
```
{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0xc"],"id":23}
```

Response:
```
{"id":23,"jsonrpc":"2.0","result":[null]}
```

`[null]` shouldn't be a valid result to a `eth_getFilterChanges` call.

This filter was created with:
```
{"jsonrpc":"2.0","method":"eth_newBlockFilter","params":["latest"],"id":3}
```

Response:
```
{"id":3,"jsonrpc":"2.0","result":"0xc"}
```

develop branch, commit e01002b

**Comment by gavofyork** [comment]
Correct behaviour. This is the initial callback.

**Comment by jorisbontje** [comment]
why `[null]` instead of an empty array?
