### ISSUE TITLE
ethereum.js should help to find & deliver web3 object

### ISSUE THREAD

**Issue by gavofyork** [ethereum/cpp-ethereum#1394]
Thus providing abstraction mechanism between internal (AZ, Mist dapps) and external (running some browser).

Either provide a function:

```
var web3 = getWeb3();
```

or just provide it in root namespace automatically (prefered).

Seem this is basically going to be the same as running either:

```
var web3 = parent.web3;
```

or

```
var web3 = require('ethereum.js');
web3.setProvider(new web3.providers.HttpProvider());
```

**Comment by simondlr** [comment]
Would this map to default RPC ports only? Or would there be some other discovery mechanism (to find the port numbers of AZ/Mist)?

**Comment by gavofyork** [comment]
i know of no other discovery mechanism; ideas welcome.
