### ISSUE TITLE
Run Transactions never finishes in Mix tutorial.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1397]
In the course of hunting down another issue, I discovered the current Mix tutorial is broken. After a setRating transaction is added to the state, that state will never finish.

Specifically, it will display "Running transactions..." at the top forever, and in the terminal, puke:

/usr/include/boost/multiprecision/cpp_int.hpp(1396): Throw in function void       boost::multiprecision::backends::cpp_int_backend<MinBits, MaxBits, SignType, Checked, Allocator>::do_assign_string(const char*, const false_&) [with unsigned int MinBits = 0u; unsigned int MaxBits = 0u; boost::multiprecision::cpp_integer_type SignType = (boost::multiprecision::cpp_integer_type)1u; boost::multiprecision::cpp_int_check_type Checked = (boost::multiprecision::cpp_int_check_type)0u; Allocator = std::allocator<long long unsigned int>; mpl_::false_ = mpl_::bool_<false>]
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::runtime_error> >
std::exception::what: Unexpected character encountered in input.
qrc:/qml/StatusPane.qml:82: TypeError: Cannot read property 'length' of null

I have attempted to duplicate the tutorial's project as close as possible, several times, and it has always done this. I can get one of these projects up on pastebin or somewhere if necessary.

EDIT: This is the absolute latest Ubuntu binary from ethereum-dev.

**Comment by yann300** [comment]
I have made a pr for those two bugs. Please could you close these 2 issues when it's merged and working on your side?

**Comment by Smithgift** [comment]
The latest update fixed it, yes. Thank you.
