### ISSUE TITLE
Calling contracts in mix's browser does not work.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1399]
I have had no success calling any function of any contract in mix's browser on the latest Ubuntu dev binary. Take the following stupid contract:

```
contract Niner {
   function nine() returns (uint) {
   	return 9;
   }
}
```

Creating it and calling it through transaction in the state editor works fine and as expected: returning 9.

Using `contracts["Niner"].contract.nine()` the browser's expressions pane, however, returns undefined. Using JavaScript to call it, ala `<input type=button onclick="console.log(contracts['Niner'].contract.nine())" value="PRINT NINE!">` also returns undefined. Using .call() gives `JavaScript	error	10:30:07 24.03.2015	WebContainer.html - line 1 - Uncaught TypeError: undefined is not a function` and, yes, returns undefined.

`contracts` itself gives
```
{
  "Niner": {
    "contract": {
      "_options": {},
      "address": "0x78dfc5983baecf65f73e3de3a96cee24e6b7981e",
      "_isTransaction": null
    }
  }
}
```
Which appears to me to show that there is no ABI in there.

**Comment by Smithgift** [comment]
Fixed in latest version.

**Comment by willwarren89** [comment]
I'm currently having the same issue on windows with Mix v1.0.2.

**Comment by bobsummerwill** [comment]
Hey @willwarren89.
Please could you open a new issue in http://github.com/ethereum/mix, and point back here?  Thanks!
