### ISSUE TITLE
Remove Contracts, Addresses panes when ETH_FATDB is 0

### ISSUE THREAD

**Issue by jamescarlyle** [ethereum/cpp-ethereum#1403]
On AlethZero/v0.9.1/Release/linux/g++/int - latest update/upgrade on ethereum-dev today 24/03 on Ubuntu. 

1. I can create a new transaction with the most trivial Solidity contract from one of the tutorials,
2. Submit
3. See it in the pending pane in AZ, 
4. See a block mined, and 
5. The contract disappears from the pending pane and appears in the blockchain pane but not in the Contracts pane

**Comment by ethers** [comment]
+1 still doesn't work for me either on develop branch 46f10bf

**Comment by gavofyork** [comment]
*from one of the tutorials*

please give specifics. this works 100% for me.

**Comment by gavofyork** [comment]
Just tried:

- New Transaction
- Data:
```
contract C {
function() { suicide(msg.sender); }
}
```
- [Specifies: `INFO Gas required: 26880 total = 22856 base, 4024 exec`]
- Execute
- [Appears in Pending pane]
- Mine
- [Appears in Block Chain pane and Contracts pane]

**Comment by caktux** [comment]
@gavofyork I can confirm there's an issue here, with valid contracts mined and working 100%, I'm seeing `ethereum()->addresses()` as being empty, same with eth/neth for `c->addresses()`

**Comment by KenKappler** [comment]
@gavofyork using your example I am not seeing anything appear in the contract pane. produces this transaction: https://gist.github.com/KenKappler/3573935b2fe4c51bcca7 
This bug is present on commit 46f10bf20819e1bfe06366dc2f5e65ed56cc8259

**Comment by gavofyork** [comment]
heh. confirmed... sort of :-)

**Comment by caktux** [comment]
How is this a fix? It just adds more confusion as the panes will now simply not show up on default installs...

**Comment by jamescarlyle** [comment]
<noob apology etc.>
Having a populated Contracts pane was kinda intuitive, so my question becomes "can we include FATDB in the builds available through ppa for Ubuntu?" - I can't see any references in the documentation, searching for ETH_FATDB or FATDB via Google

**Comment by caktux** [comment]
Yeah that's just what I'll do for PPA and Homebrew builds... That option should be inverted, defaulting to a large DB and having LIGHTDB instead. The introduction of that option was a breaking change, and having a lighter DB for future light clients makes more sense than forcing everyone to not be able to see accounts and contracts...

**Comment by caktux** [comment]
@gavofyork please notify if you do invert the option
