### ISSUE TITLE
same filter.watch firing twice

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1421]
cpp develop 263dd51  with ethereum.js develop b78dffa

This code
``web3.eth.filter({'address': <address>}).watch...``

is firing 2 times.  First time is when a transaction is created and is in pending state.  Second time is when tx is actually mined.
Since documentation https://github.com/ethereum/ethereum.js/issues/136 hasn't been completed, it is not clear what the expected behavior is, and how to only get a callback when a tx is mined.

**Comment by gavofyork** [comment]
the watch interface does not guard against false positives - this is acceptable behaviour.

**Comment by ethers** [comment]
is it possible to improve this with cpp, since Geth does not have this issue: Geth only fires filter.watch once
