### ISSUE TITLE
eth cli wrong result for eth_getStorageAt index 0x1

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1422]
develop 263dd51

The expected result is 0x10, but cpp eth cli returns 0x00 when the index is specified as 0x1.
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getStorageAt","params":["0x3a2cfa2d577856a32db16cd7788bdca983395b34", "0x1" , "latest"],"id":1}' http://localhost:8080
{"id":1,"jsonrpc":"2.0","result":"0x00"}
```

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getStorageAt","params":["0x3a2cfa2d577856a32db16cd7788bdca983395b34", "0x10" , "latest"],"id":1}' http://localhost:8080
{"id":1,"jsonrpc":"2.0","result":"0x10"}
```

**Comment by gavofyork** [comment]
could you check if within the AZ JS console the following works as expected?

```
web3.eth.getStorageAt("0x3a2cfa2d577856a32db16cd7788bdca983395b34", "0x1")
```

**Comment by gavofyork** [comment]
also; i'm not sure precisely what the issue is and why you've given two JSONRPC conversations

**Comment by ethers** [comment]
0x1 in the AZ JS console doesn't work.
>web3.eth.getStorageAt("0x3a2cfa2d577856a32db16cd7788bdca983395b34", "0x1")
 "0x00"
>web3.eth.getStorageAt("0x3a2cfa2d577856a32db16cd7788bdca983395b34", "0x10")
 "0x10"

I provided 2 JSONRPC conversations to show the inconsistency between the 2 (with 0x10 returning the correct expected result).

**Comment by gavofyork** [comment]
why is the expected result 0x10 in both situations? have you written 0x10 to both locations of contract storage? could you prove this (i.e. give full contract code, transactions &c.)

**Comment by ethers** [comment]
sorry, must have confused 0x10 with 0x01.  closing this.
