### ISSUE TITLE
Force CLI client to use private blockchain

### ISSUE THREAD

**Issue by rekoil** [ethereum/cpp-ethereum#1428]
It would be nice to be able to have a private blockchain during the development and testing of dapps.

**Comment by gavofyork** [comment]
just make sure network is disabled and start with `-d ~/myprivatechain` and you're done.

**Comment by rekoil** [comment]
The thing I want to be able to do is have several nodes over network to have a private blockchain. As I understand it this would be done by being able to set some parameter in the genesis block.
