### ISSUE TITLE
RPC return value for 0

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1433]
return values of 0x00 should be 0x

**Comment by gavofyork** [comment]
according to latest docs:

How to encode types for JSONRPC:
When encoding UNFORMATTED DATA ("byte arrays"): encode as hex, prefix with "0x", two hex digits per byte. Examples:
- 0x41 (size 1, "A")
- 0x004200 (size 3, "\0B\0")
- 0x (size 0, "")
- WRONG: 0xf0f0f (must be even number of digits)
- WRONG: 004200 (must be prefixed 0x)

When encoding QUANTITIES ("integers", "numbers"): encode as hex, prefix with "0x", the most compact representation (slight exception: zero should be represented as "0x0"). Examples:
- 0x41 (65 in decimal)
- 0x400 (1024 in decimal)
- WRONG: 0x (should always have at least one digit - zero is "0x0")
- WRONG: 0x0400 (no leading zeroes)
- WRONG: ff (must be prefixed 0x)

**Comment by ethers** [comment]
what's the link to "latest docs" ?  I searched these and didn't see the notes above:
https://github.com/ethereum/wiki/wiki/JSON-RPC
https://github.com/ethereum/wiki/wiki/JavaScript-API
