### ISSUE TITLE
Syntax highlighting for Solidity in Sublime

### ISSUE THREAD

**Issue by abrkn** [ethereum/cpp-ethereum#1445]
This is probably the wrong place for this issue, I've simple found no better repo. Any redirection would be appreciated.

**Comment by gavofyork** [comment]
the sublime repo, perhaps? :-)

**Comment by abrkn** [comment]
Woo, celebrity in the issue :) I'd say it's more likely for Ethereum users to have Sublime than the other way. Let's see if anyone bites or I won't mind the issue being closed.

**Comment by LefterisJP** [comment]
So I guess there are 2 ways to deal with such requests:

1. A kind soul who likes Solidity and knows about sublime can take up the task.
2. The sublime guys do it when a language reaches a certain amount of popularity/use.

I suspect the first will happen. We already have a [mode for VIM](https://github.com/ethereum/emacs-solidity) that does just that and an [emacs-mode](https://github.com/ethereum/emacs-solidity) that does a bit more.

**Comment by androlo** [comment]
I have one for WebStorm. Syntax highlighting and code completion. Will probably export it and make it available once i find out how...

**Comment by caktux** [comment]
lmgtfy... https://packagecontrol.io/packages/Ethereum

**Comment by alexfisher** [comment]
@androlo Did you ever figure-out a way to export your WebStorm syntax highlighting and code completion for Solidity?

**Comment by androlo** [comment]
yes. it is easy. can't send the jar though, because it gives "zip within a
zip" warning, but the xml language file is easy to send and just copy into
the settings folder. at least on ubuntu. i can send if you want.

**Comment by alexfisher** [comment]
Yeah, that'd be awesome.  Pastebin it?

**Comment by androlo** [comment]
This file can be sent. Just can't export as jar and then send.

The file is supposed to be in "~/.Webstorm11/config/filetypes" on Ubuntu,
can't remember on mac.

**Comment by cassiopaia** [comment]
@androlo if u may send me your **Webstorm syntax hightlight and code completion for Solidity** as well? This would be great! Thanks in advance

**Comment by androlo** [comment]
oh, didn't know stuff ended up here. Sure. I'll find somewhere to upload it later.

**Comment by androlo** [comment]
@alexfisher Did you ever receive the file?

**Comment by androlo** [comment]
Sorry otherwise. I responded as if it was an e-mail. didn't see where it was from.

**Comment by androlo** [comment]
On ubuntu, save this as as `~/.Webstorm11/config/filetypes/Solidity.xml`
```
<filetype binary="false" description="Solidity code" name="Solidity">
  <highlighting>
    <options>
      <option name="LINE_COMMENT" value="//" />
      <option name="COMMENT_START" value="/*" />
      <option name="COMMENT_END" value="*/" />
      <option name="HEX_PREFIX" value="0x" />
      <option name="NUM_POSTFIXES" value="" />
    </options>
    <keywords keywords="as;break;continue;contract;delete;do;else;enum;event;for;from;function;if;import;library;mapping;modifier;new;private;public;return;returns;struct;super;this;using;while" ignore_case="false" />
    <keywords2 keywords="anonymous;constant;external;indexed;internal;is;memory;storage" />
    <keywords3 keywords="address;bool;byte;bytes;bytes1;bytes10;bytes11;bytes12;bytes13;bytes14;bytes15;bytes16;bytes17;bytes18;bytes19;bytes2;bytes20;bytes21;bytes22;bytes23;bytes24;bytes25;bytes26;bytes27;bytes28;bytes29;bytes3;bytes30;bytes31;bytes32;bytes4;bytes5;bytes6;bytes7;bytes8;bytes9;int;int104;int112;int120;int128;int136;int144;int152;int16;int160;int168;int176;int184;int192;int200;int208;int216;int224;int232;int24;int240;int248;int256;int32;int40;int48;int56;int64;int72;int8;int80;int88;int96;real;string;uint;uint104;uint112;uint120;uint128;uint136;uint144;uint152;uint16;uint160;uint168;uint176;uint184;uint192;uint200;uint208;uint216;uint224;uint232;uint24;uint240;uint248;uint256;uint32;uint40;uint48;uint56;uint64;uint72;uint8;uint80;uint88;uint96;ureal;var" />
    <keywords4 keywords="balance;block;blockhash;coinbase;data;difficulty;erecover;false;gas;gaslimit;gasprice;msg;now;null;number;origin;ripemd160;send;sender;sha256;sha3;sig;suicide;timestamp;true;tx;value" />
  </highlighting>
  <extensionMap>
    <mapping pattern="PropertyAddressMapper" />
    <mapping ext="slib" />
    <mapping ext="sol" />
    <mapping ext="slb" />
  </extensionMap>
</filetype>
```

**Comment by alexfisher** [comment]
No, I didn't.  I'd still be interested in a copy!

--Alex

On Tue, Jan 12, 2016 at 10:14 AM, Andreas Olofsson <notifications@github.com

**Comment by alexfisher** [comment]
Thanks!

--Alex

On Tue, Jan 12, 2016 at 10:20 AM, Andreas Olofsson <notifications@github.com

**Comment by cassiopaia** [comment]
Thanks

**Comment by furiousOyster** [comment]
In windows, location for xml file is: 
C:\Users\[username]\.WebStorm2016.1\config\filetypes\Solidity.xml

**Comment by bgrieder** [comment]
[This article](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519) provides the various locations based on the Jetbrains product and Operating System

On OSX,  IntelliJ 2016.x, the location is `/Users/[username]/Library/Preferences/IntelliJIdea2016.x/filetypes`

**Comment by jacovorkin** [comment]
PhpStorm code completion Solidity 0.4.18
~/Library/Preferences/PhpStormX.Y/filetypes/Solidity.xml
https://gist.github.com/jacovorkin/a260086d0ebf295df1d367575c0cb908
