### ISSUE TITLE
Mix segfaults immediately when opening another project while a project is open.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1446]
On the latest dev binary on Ubuntu 14.04, opening another project while one is open leads immediately to a segfault. It has done this without fail and with multiple "to-from" project pairs.

**Comment by yann300** [comment]
should be fixed by this pr:
https://github.com/ethereum/cpp-ethereum/pull/1443

**Comment by Smithgift** [comment]
I've updated to the latest dev binary, and changing projects still consistently segfaults, with the exception of once freezing.

**Comment by yann300** [comment]
Are you sure the binary you have include the pr #1443 because when I posted the first message #1443 was not merged.

**Comment by Smithgift** [comment]
I had updated at least an hour after #1443 was merged, but updating again just a few minutes ago seems to have fixed it.
