### ISSUE TITLE
-DHEADLESS=on -DJSONRPC=off # fails to compile

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#1450]
Suggest excluding libtestutils for !jsonrpc/headlines configuration. FixedWebThreeServer.h is only included by ethrpctest and not used elsewhere. json-rpc doesn't need to be a dependency of libtestutils if it's only used by ethrpctest (class can be moved). If nothing uses jsonrpc from libtestutils, can FixedWebThreeServer.h be moved to ethrpctest?

**Comment by debris** [comment]
`FixedWebThreeServer` will be used by testeth target, so let's leave it in libtestutils.
In #1451 I modified libtestutils cmake file, so it does not include `FixedWebThreeServer` if `JSONRPC` is set to `off`.
