### ISSUE TITLE
Unable to run a test-net-in-a-box with Docker

### ISSUE THREAD

**Issue by abrkn** [ethereum/cpp-ethereum#1471]
I'm trying to create an isolated testing environment using Docker. The idea is to have two nodes running and mining. However, authentication seems to fail:

Here's the output of the second `eth` instance trying to network with the first: https://gist.github.com/abrkn/97a89fb68f9a0a6565c2

Here's the scripts: https://github.com/abrkn/ethereum-cpp-docker

Any ideas on how to get this working?

**Comment by subtly** [comment]
This looks like an old version of the client as it shouldn't attempt connections to 0.0.0.0. Are you trying to connect it to another instance on the same machine?

Can you paste output of eth -h?

**Comment by gavofyork** [comment]
inactive - closing.
