### ISSUE TITLE
Mix freezes when sending a transaction through javascript after "New Block" is pressed.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1473]
On the latest Ubuntu development binary, after the "New Block" button is pressed on the right panel window thing, sending a transaction through javascript will inevitably cause it to be unresponsive forever. No additional message appears in the terminal.

**Comment by yann300** [comment]
I can't reproduce. When you clicked on "New Block", have you waited the block to be mined? After a  max of 30s the status pane sohuld display "New Block created"

**Comment by Smithgift** [comment]
After clicking "New Block", a lot more than 30s pass and the program never becomes responsive again.

**Comment by Smithgift** [comment]
This seems not to be happening in the latest mix, or at least it's happening differently. Closing for now.
