### ISSUE TITLE
closing alethzero does not exit application when blockchain is being downloaded

### ISSUE THREAD

**Issue by youlian** [ethereum/cpp-ethereum#1492]
the latest as of time of writing, pull, compile, run on ubuntu. just closed the main window, expecting that all activity will cease. run from a terminal, i see it's doing something, new hashes are created in BlockChain.cpp. it just keeps on going and going, and it probably would take a looong time before it stops, if the amount of blocks i have to download is large. the expected behavior would be all activity to stop cleanly, no? as it is now i have to control-c.

**Comment by gavofyork** [comment]
yes indeed. this is during blockchain download, then, i take it?

**Comment by arkpar** [comment]
fixed in develop
