### ISSUE TITLE
Build on Ubuntu 14.04.1 : CMake Error at CMakeLists.txt:36

### ISSUE THREAD

**Issue by Arpazak** [ethereum/cpp-ethereum#1493]
<b> If you try to do :</b>
~/cpp-ethereum/build cmake .. 

<b>And it says you :</b>
CMake Error at CMakeLists.txt:36 (message):   
	Paranoia requires debug. Call Stack (most recent call first):   
		CMakeLists.txt:128 (configureProject)   
-- Configuring incomplete, errors occurred! 
See also "/home/itsmyname/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".

<b>Do : </b>
~/cpp-ethereum/build cmake -DPARANOIA=0 ..

**Comment by gavofyork** [comment]
paranoia is off by default - did you previously build with paranoia enabled? in any case, the error message is self-explanatory.

**Comment by Arpazak** [comment]
I did not build with paranoia enabled, I had just installed ubuntu on USB key and then i followed this link bellow, step by step, nothing more: 
https://github.com/ethereum/cpp-ethereum/wiki/Installing-clients

**Comment by gavofyork** [comment]
that is for binary installation, not compilation. presumably you followed a different guide.
