### ISSUE TITLE
Allow custom proof engine in libethereum

### ISSUE THREAD

**Issue by arkpar** [ethereum/cpp-ethereum#1497]
There needs to be a proof engine interface, and a way to switch to a different engine at runtime. This is required for simpler POW engine in Mix and also might be useful to switch between CPU/GPU miners

**Comment by gavofyork** [comment]
Three options:
- Virtualise `ProofOfWork` class, include in `BlockChain` (it's already in `State`), pass through to `BlockInfo` for PoW verification and use in `Client` as well as any other data routing necessary. A fairly big task and a bit of a pain to maintain, but would provide a decent abstraction mechanism.
- Provide a PoW singleton and allow it to be configured. Easier to integrate - no additional data paths to plumb - but singletons are a bit hacky and there's no ability to have two different PoW chains in the process.
- Massively reduce difficulty (e.g. to 1) and provide a "slow" miner that doesn't use the DAG but the verification code. Easy, doesn't require any major changes. Not sure how fast it'll mine though...

**Comment by arkpar** [comment]
Trying option 1

**Comment by arkpar** [comment]
Implemented option 3 instead)
