### ISSUE TITLE
RPC: eth_getUncleByBlockHashAndIndex returns invalid params

### ISSUE THREAD

**Issue by frozeman** [ethereum/cpp-ethereum#1499]
sending: 

```
{"jsonrpc":"2.0","method":"eth_getUncleByBlockHashAndIndex","params":["0xc9ec9406a96d000df82ba4e5e9b3dc19c7361299eb1102ddd6d657d0fb34e08b","0x1",false],"id":4}
```

returns
```
{"error":{"code":-32602,"message":"INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised"},"id":4,"jsonrpc":"2.0"}
```

With the fixed blockchain loaded this block should contain and uncle: https://github.com/ethereum/tests/blob/develop/BlockTests/bcJS_API_Test.json#L146-L163

I'm currently working with go on thos uncle methods, and they say its actually not reliable to get full uncle objects. We should have a discussion about that.

**Comment by gavofyork** [comment]
it's perfectly reliable.

**Comment by gavofyork** [comment]
Ahh - i see your documentation is simply wrong.

uncle blocks are, in general, headers only. the transaction information is not maintained. so they'll never have any transactions. i updated the documentation accordingly.

**Comment by frozeman** [comment]
youre right. ethereum.js was automatically adding the third parameter, thats why i got the same issue even when try two.

Thanks. output seems correct so far.
