### ISSUE TITLE
Avoid out of control "Unknown parent of block"s when peer's chain turns out to be flawed

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1507]
develop 54f20f1

Run AZ with usual poc9ethdev peer.
There are many many logs of the following, and once it stops, a few minutes later AZ keeps cycling back through them:

!!! [ 12:46:15 AM | eth ] Unknown parent of block!!! c6b0b3a3… cpp-ethereum/libethereum/BlockChain.cpp(296): Throw in function dev::h256s dev::eth::BlockChain::import(const bytes&, const dev::OverlayDB&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception

!!! [ 12:46:15 AM | eth ] Unknown parent of block!!! 750cc734… cpp-ethereum/libethereum/BlockChain.cpp(296): Throw in function dev::h256s dev::eth::BlockChain::import(const bytes&, const dev::OverlayDB&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception

!!! [ 12:46:15 AM | eth ] Unknown parent of block!!! feda7107… cpp-ethereum/libethereum/BlockChain.cpp(296): Throw in function dev::h256s dev::eth::BlockChain::import(const bytes&, const dev::OverlayDB&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception

!!! [ 12:46:15 AM | eth ] Unknown parent of block!!! 01339230… cpp-ethereum/libethereum/BlockChain.cpp(296): Throw in function dev::h256s dev::eth::BlockChain::import(const bytes&, const dev::OverlayDB&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception

!!! [ 12:46:15 AM | eth ] Unknown parent of block!!! 4de5f54e… cpp-ethereum/libethereum/BlockChain.cpp(296): Throw in function dev::h256s dev::eth::BlockChain::import(const bytes&, const dev::OverlayDB&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception

!!! [ 12:46:16 AM | eth ] Unknown parent of block!!! aee37389… cpp-ethereum/libethereum/BlockChain.cpp(296): Throw in function dev::h256s dev::eth::BlockChain::import(const bytes&, const dev::OverlayDB&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception

!!! [ 12:46:16 AM | eth ] Unknown parent of block!!! e7185b13… cpp-ethereum/libethereum/BlockChain.cpp(296): Throw in function dev::h256s dev::eth::BlockChain::import(const bytes&, const dev::OverlayDB&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception

**Comment by ethers** [comment]
In case helpful, after the flood of unknown parent, here are some of the logs after:
http://pastebin.com/rcVtVm4f

**Comment by ethers** [comment]
Seems "Might have put a limit on how many unknown parent blocks can be tolerated."
Additionally, in case this is caused by a block/s a Go peer sent that cpp didn't import, a suggestion is to also have logging that can help determine which block/s easier.

**Comment by cubedro** [comment]
I'm having the same issue: https://github.com/ethereum/go-ethereum/issues/642

**Comment by gavofyork** [comment]
go should be fixed now, but cpp could still do with an enhancement to prevent this kind of log spamming and potential dos attack

**Comment by gavofyork** [comment]
Fixed in latest develop. Peers giving recognisably bad chains will be barred.
