### ISSUE TITLE
AZ hangs and does not get blocks after FIRING WATCH

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1516]
Rebuilt develop eaf6c65 (from b9074ff)

Running AZ, the blockchain started back at genesis.  Was unable to get the chain because it keeps hanging after:

```
*** [ 06:43:52 PM | eth ] noteChanged( { 0000000000000000000000000000000000000000000000000000000000000000, 0000000000000000000000000000000000000000000000000000000000000001 } )
*** [ 06:43:52 PM | main ] FIRING WATCH 5 1
*** [ 06:43:52 PM | main ] FIRING WATCH 6 1
```

Restarted AZ and it was able to get few more blocks, before hanging again at block 3928.

For now, I am using eth CLI and it is getting blocks.

**Comment by gavofyork** [comment]
please recheck with latest develop. i cannot reproduce.

**Comment by ethers** [comment]
can't repro either anymore; will get bt next time I see it happen.
