### ISSUE TITLE
Blank screen when opening AZ in a remote desktop session on Windows

### ISSUE THREAD

**Issue by mtbitcoin** [ethereum/cpp-ethereum#1517]
When attempting to open AZ on a windows server during a remote desktop session, all you get is a blank screen (this is with the latest develop).

The error messages are ...

"*** [ 04:09:52 | eth ] noteChanged( { 000000000000000000000000000000000000000000
0000000000000000000000 } )
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
bool __thiscall QOpenGLTextureBlitter::create(void) Could not link shader progra
m:
 ""
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed:..."

**Comment by gavofyork** [comment]
Qt failure.
