### ISSUE TITLE
PARANOIA broken

### ISSUE THREAD

**Issue by youlian** [ethereum/cpp-ethereum#1521]
pull latest as of time of writing, compile (cmake .. -DCMAKE_BUILD_TYPE=Debug -DVMTRACE=1 -DPARANOIA=1 -DEVMJIT=1), run on ubuntu. all previous data was deleted.
alethzero won't come up. 

*** [ 11:43:37 PM | main ] Opened state DB.
!!! [ 11:43:37 PM | main ] BAD TRIE [unenforced refs]
*** [ 11:43:37 PM | main ] {}
!!! [ 11:43:37 PM | main ] BAD TRIE beginning of Genesis construction.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::InvalidTrie>'
  what():  std::exception
Aborted (core dumped)

**Comment by gavofyork** [comment]
run without PARANOIA.

**Comment by gavofyork** [comment]
disabled paranoia.
