### ISSUE TITLE
mix: go to next problem shortcut

### ISSUE THREAD

**Issue by gavofyork** [ethereum/cpp-ethereum#1525]
need a shortcut to let us jump directly to the exact site of the (next) compilation issue.

**Comment by yann300** [comment]
Is that needed for POC9? For now this is not available in the sol library.

**Comment by arkpar** [comment]
We can do "jump to current error" for now

**Comment by yann300** [comment]
Just need some ui redesign by Alex

**Comment by arkpar** [comment]
implemented
