### ISSUE TITLE
Log window broken on mix.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1529]
On the latest dev ubuntu binary, clicking on the log message brings up a partially messed-up window.

The terminal says:
qrc:/qml/StatusPane.qml:234: ReferenceError: LogsPaneStyle is not defined

**Comment by arkpar** [comment]
Are you sure you have the latest code? This was fixed in PR #1520

**Comment by Smithgift** [comment]
Not actually the latest. See: #1530
