### ISSUE TITLE
JS api completely missing on mix.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1530]
On the latest ubuntu dev binary, the JS api seems to be completely missing in mix. `contracts` is undefined. So is `web3`.

**Comment by arkpar** [comment]
Are you sure you have the latest code? This was fixed in PR #1520

**Comment by Smithgift** [comment]
As it happens, I see that the develop build is failing for linux, therefore this isn't the latest. Never mind.
