### ISSUE TITLE
Alethzero jsonrpc port

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1536]
Suggestions for jsonrpc port:
* AZ should not start if the port is in use (eg if Geth or some other client happens to be using the port already)
* Allow port to be configured via alethzero.conf
* Avoid 8080 as default port

**Comment by gavofyork** [comment]
avoided use of 8080 as default (8545 now).

**Comment by gavofyork** [comment]
moved to https://github.com/ethereum/alethzero/issues/4
