### ISSUE TITLE
Setting coinbase in Alethzero

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1539]
I added a 2nd account and couldn't see how to change back the coinbase to the 1st account in AZ.

An alethzero.conf option would also be nice.

**Comment by gavofyork** [comment]
drag'n'drop in owned accounts. top account is prefered signer, bottom is prefered coinbase.

**Comment by gavofyork** [comment]
if you find someone in similar trouble on the forums, pass it on ;-)
