### ISSUE TITLE
JS api partially broken on alethzero

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1545]
On the ubuntu develop ppa (specifically `cpp-ethereum_0.9.5+629SNAPSHOT20150407103608trusty-0ubuntu1`) web3 is missing in the alethzero browser before the page is loaded and right afterwards.

Try the following: 
```html
<html>
<head>
<script>
console.log(web3)

function loaded()
{
	console.log(web3)
}
function test1()
{
	console.log(web3)
}
</script>
</head>
<body onload="loaded()" >
<input type="button" value="Test1" onclick="test1()" />
<input type="button" value="Test2" onclick="console.log(web3)" />
</body>
</html>
```
The direct test in script and the onload test will both say that web3 is undefined, while the two buttons (one running a function, the other inline) will happily talk about web3.

**Comment by gavofyork** [comment]
web3 isn't guaranteed to be around before page load.
