### ISSUE TITLE
JS api inconsistent on mix (too functional.)

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1560]
Bizarrely, mix works TOO well. The code from #1545, for example, will show web3 is functional even before the page load on mix, whereas AZ will neither acknowledge web3 before the page is loaded or during the body tag's onload. This gives new developers (such as say, myself) the false impression that their initialization code will be run on a real system, when, in fact, it will not.

Aside: Is body onload really supposed to be not-guaranteed to have web3 when it triggers? This would require a kludge for any initialization code.

**Comment by gavofyork** [comment]
perhaps @arkpar and @debris can shed some light onto this?

**Comment by debris** [comment]
I have checked and that's true. Mix code editor is an iframe with [web3 object injected from parent](https://github.com/ethereum/cpp-ethereum/blob/develop/mix/qml/WebPreview.qml#L187) **before** the page is loaded. Whereas in alethzero we are [adding web3 object](https://github.com/ethereum/cpp-ethereum/blob/develop/alethzero/MainWin.cpp#L186-L192) **after** the page is loaded. We should unify this in AZ, mix and mist.

I opt for delivering web3 object as fast as we can.

**Comment by Smithgift** [comment]
I can confirm web3 is now existent before page load. I think the issue can be closed now.
