### ISSUE TITLE
web3_clientVersion showing linux even though i'm on osx

### ISSUE THREAD

**Issue by cubedro** [ethereum/cpp-ethereum#1564]
web3_clientVersion returning Ethereum(++)/v0.9.6/Release/linux/clang/int even though i'm on linux. Should return Ethereum(++)/v0.9.6/Release/darwin/clang/int

**Comment by debris** [comment]
That's probably because cmake's `LINUX` is returning true also on OSX. I take care of this

**Comment by debris** [comment]
should be fixed in #1592
