### ISSUE TITLE
suggestion: jsonrpc return numbers as decimal

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1574]
*suggestion* is for the RPC to return numbers as decimal (instead of hex).  (Filing this suggestion here since there's no specific repo for RPC)

For comparison, here are some examples in Bitcoin:
https://bitcoin.org/en/developer-reference#getbalance
https://bitcoin.org/en/developer-reference#getblockcount
https://bitcoin.org/en/developer-reference#getdifficulty
https://bitcoin.org/en/developer-reference#listreceivedbyaccount

**Comment by gavofyork** [comment]
the decision to return values in hex was not taken lightly. consistency was judged the most important attribute. it's easy to convert from hex -> decimal if you need.
