### ISSUE TITLE
InvalidNonce Error when submitting transaction via RPC

### ISSUE THREAD

**Issue by Georgi87** [ethereum/cpp-ethereum#1578]
I am submitting multiple contracts one after the other via the RPC interface. I always wait for a new block before sending the next contract. Sometimes the contract is not successfully committed because an InvalidNonce error occures.

```
*** [ 06:25:52 | eth ] New block on chain: Restarting mining operation.
*** [ 06:25:52 | eth ] Dropping invalid transaction:
*** [ 06:25:52 | eth ] /build/buildd/cpp-ethereum-0.9.6+645SNAPSHOT20150408115741trusty/libethereum/Executive.cpp(93): Throw in function void dev::eth::Executive::initialize(const dev::eth::Transaction&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InvalidNonce>
std::exception::what: std::exception
[dev::tag_required*] = 83
[dev::tag_got*] = 82
```

I am working with:

eth version 0.9.6
eth network protocol version: 60
Client database version: 12041

Starting the client with: eth -m on -j
Using only one thread for mining.

**Comment by gavofyork** [comment]
Please review with latest develop - https://github.com/ethereum/cpp-ethereum/commit/71c83172c5bd55f9297113a8007f79e70bd040c5 may have fixed it.

**Comment by gavofyork** [comment]
assuming fixed until reopened with reproduction instructions.
