### ISSUE TITLE
Suggestion for mix: Have a way to see the balances of accounts during debugging.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1584]
As it is, the only way is to use expressions in the javascript console to call web3.eth.getBalance on the accounts manually. That is possible, but inconvenient. Could we have, say, a section on the right view that lists the accounts in the state and their balances?

**Comment by yann300** [comment]
Yes, this will be addressed soon we are redesigning the right view, balances should be included in this view.
