### ISSUE TITLE
suggestion: jsonrpc method to view pending transactions

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1589]
discussed briefly with Gav earlier: add/expose eth_getPendingTransactions or eth_getPendingTransactionHashes to jsonrpc

**Comment by gavofyork** [comment]
please try existing methods such as eth.block('pending')

**Comment by gavofyork** [comment]
*bump*

fixed now?

**Comment by ethers** [comment]
not able to verify on 84ecbaf because:

curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["pending",true],"id":1}' http://localhost:8080

gives:
{
  "jsonrpc": "2.0",
  "id": 1,
  "error": {
    "message": "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised",
    "code": -32602
  }
}

Maybe fix for #1774 is also needed?

**Comment by ethers** [comment]
good thanks
