### ISSUE TITLE
JSONRPC wiki question marks

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1596]
This is to track further clarification/cleanup of RPC wiki (defer/prioritize as needed).  Examples:  https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_flush has no explanation.  There are also a number of other places where there are "?"
There's quite a bit for dapp developers to grasp, and interacting with RPC is one of the most useful ones, so we should eventually have the RPC wiki as accurate as we can, eg if any methods are no longer supported, we should remove from wiki, so that devs are not trying out such methods.

**Comment by gavofyork** [comment]
partly fixed. i removed `eth_flush` :)
