### ISSUE TITLE
alethzero: Undefined symbol at run-time _ZN7jsonrpc10HttpServerC1EiRKSsS2_i

### ISSUE THREAD

**Issue by tglauner** [ethereum/cpp-ethereum#1606]
Replication steps on ubuntu 14.04 LTS

1. suod apt-get update
2. sudo apt-get upgrade
3. sudo apt-get install alethzero
4. alethzero

Then, I get an undefined symbol error.

Here is the output for command 3 and 4:
cmt@ubuntu:~$ sudo apt-get install alethzero
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  alethzero
0 upgraded, 1 newly installed, 0 to remove and 6 not upgraded.
Need to get 0 B/376 kB of archives.
After this operation, 1,279 kB of additional disk space will be used.
Selecting previously unselected package alethzero.
(Reading database ... 329183 files and directories currently installed.)
Preparing to unpack .../alethzero_0.9.7+665SNAPSHOT20150413093719trusty-0ubuntu1_amd64.deb ...
Unpacking alethzero (0.9.7+665SNAPSHOT20150413093719trusty-0ubuntu1) ...
Setting up alethzero (0.9.7+665SNAPSHOT20150413093719trusty-0ubuntu1) ...
cmt@ubuntu:~$ alethzero
State root: 9178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4e
Block Hash: fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca
Block RLP: [ [ "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x1DCC4DE8DEC75D7AAB85B567B6CCD41AD312451B948A7413F0A142FD40D49347, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x9178D0F23C965D81F0834A4C72C6253CE6830F4022B1359AAEBFC1ECBA442D4E, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x20000, 0x0, 0x2FEFD8, 0x0, 0x0, 0x0, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", "\x00\x00\x00\x00\x00\x00\x00*" ], [ ], [ ] ]
Block Hex: f901f8f901f3a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a09178d0f23c965d81f0834a4c72c6253ce6830f4022b1359aaebfc1ecba442d4ea056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b90100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008302000080832fefd8808080a0000000000000000000000000000000000000000000000000000000000000000088000000000000002ac0c0
eth Network protocol version: 60
Client database version: 12041
*N* [ 09:04:28 PM | main ] Id: cf3e30ab9412f0183b79afc9103987c9ff2887e12452b2044c96696d53aced446989b3fa485ce4d49ea3807207782c3836c1c9ae4e42d2eb82f83fb1ff80aba8
*** [ 09:04:29 PM | main ] Opened blockchain DB. Latest: fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca
*** [ 09:04:29 PM | main ] Opened state DB.
*** [ 09:04:29 PM | main ] startWorking for thread eth
*** [ 09:04:29 PM | main ] Spawning eth
alethzero: symbol lookup error: alethzero: undefined symbol: _ZN7jsonrpc10HttpServerC1EiRKSsS2_i
cmt@ubuntu:~$

**Comment by debris** [comment]
I've reproduced your issue. It looks like, you have old version of libjson-rpc-cpp installed. To fix this, I followed this steps:

1. I've removed libjson-rpc-cpp from `/usr` directory

```bash
sudo rm -rf /usr/lib/libjson*
sudo rm -rf /usr/include/jsonrpccpp
```

2. I started synoptic (I not very familiar with ubuntu apt-get) and removed `libjson-rpc-cpp` from the system (together with alethzero, eth... )
3. I installed again alethzero
4. Everything is working fine now :)

**Comment by debris** [comment]
please reopen if the problem still occurs

**Comment by deskenny** [comment]
i have same problem. Followed debris instruction, still have the problem.
