### ISSUE TITLE
opencl - why is cl.hpp included?

### ISSUE THREAD

**Issue by Genoil** [ethereum/cpp-ethereum#1616]
Built (eth) with #1614  of today on Win32 with NVidia OpenCL. Wouldn't build with cl.hpp included from ethash-cl, but would with cl.cpp that always sits in the same directory as %VENDOR_OPENCL_INCLUDE%/CL/opencl.h.

**Comment by gavofyork** [comment]
cl.hpp 1.2 headers broken on nvidia. not much point building on win32 since it can't allocate the 1GB necessary for the dag. we have a local build tested on win64; this will be pushed to develop imminently.

**Comment by Genoil** [comment]
I got the GPU benchmark from the ethash project running on Win32, although I did have to make some changes to the file loading function, to read directly into mapped opencl memory space.

Latest build also built on Win32 with the NVidia cl.hpp, but didn't mine very well...

Looking forward to x64 support!
