### ISSUE TITLE
Only mining two blocks

### ISSUE THREAD

**Issue by Genoil** [ethereum/cpp-ethereum#1617]
The latest build of eth only mines two blocks, It easier to see with the new opencl miner because that only uses a single CPU thread, and it seems no longer possible to limit the amount of CPU threads with a command line option. The big difference between mining the first and second block is:
```
OK- ready for chain insertion
OK - queued for future
```

[update]
I found that when I set some breakpoints and stepped through the code, I slowed down the mining process in such a  way that I didn't hit "OK - queued for the future" and mined a couple of blocks more. 
[/update]

On the CPU miner there's more blocks mined, but also only two imported. And all mining threads last message is
```
OK- ready for chain insertion
```

btw I haven't managed to connect to anything remote with eth as of yet, but at least the previous miners where happily chugging along locally.

**Comment by Genoil** [comment]
Built on a different Win32 machine now. Just CPU mining for now, 2 cores. Works like a charm.

**Comment by Genoil** [comment]
dug into this again. It seems the process halts when an ImportResult::FutureTime happens. When I increase the delay in Client::doWork from 20 to 1000 milliseconds, it all goes well. Around 500ms it becomes unstable.

**Comment by Genoil** [comment]
I found a fix for this. See last commit in #1653

**Comment by Genoil** [comment]
Note that for CPU mining with many threads, the problem still persists. Worked fine with 1 and 2 threads, but with 4 in hung after a while, with 8 after just a few blocks. 

I think the problem is related to mulitple blocks being found in different threads, within a second.

**Comment by gavofyork** [comment]
yeah - it should be sorted now; please try with threadfix branch.

**Comment by gavofyork** [comment]
now in develop.
