### ISSUE TITLE
tests: Test RLP 0x81xx is invalid when xx < 128

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#1639]
https://github.com/ethereum/yellowpaper/issues/116

it is defined that if one byte is < 128 then it's RLP encoding should be the byte itself.
however if we put it as byte array length of 1 it is still a valid encoding. 

that is incorrect with YP st.160

**Comment by gavofyork** [comment]
should be fixed now. needs tests.

**Comment by winsvega** [comment]
tests
https://github.com/ethereum/tests/commit/ebe1f586678c1a631bafef23e3a96e3cf5180b60
