### ISSUE TITLE
Suggestion: Allow mix to deploy to private testchain.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1659]
As it is, going from a mix-based test environment to an alethzero-based test environment (on a private chain) requires doing it manually. Can we have some way to test a Dapp with real software without unleashing it into the real world?

**Comment by arkpar** [comment]
Deploy-to-network feature in Mix uses a connection to an ethereum client such as AlethZero. It deploys contracts to whatever blockchain the client is on.

**Comment by Smithgift** [comment]
Well, mix claims that my sending account (on AZ) has 0 wei, which is true of the live network, but on my private test chain I have 4500 finney. That's why I believed it to be impossible.

(have to run now. More details later.)

**Comment by Smithgift** [comment]
This seems to be working now, more or less. Closing.
