### ISSUE TITLE
can gasprices lower than 10 szabo be specified ?

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1660]
Is there a way to do this or a lighter fix than #1305 ?
I also opened this issue (even though it is similar to 1305) so easier for people to find, because it will confuse people that low gasprices easily work on Go and not in cpp.  Since 1305 is marked for 1.0 instead of Frontier, maybe another option is to add this caveat somewhere in a cpp wiki

**Comment by gavofyork** [comment]
in the CLI eth, yes. for AZ, #1305
