### ISSUE TITLE
web3 missing after traversing links.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1669]
On both AZ and mix, after clicking on a link, web3 is no longer accessible. This is not even confined to loading; even after the new page is fully loaded, web3 will still be undefined.

**Comment by gavofyork** [comment]
web3 is probably going to be removed from injection for basic webpages soon; it will be injected only for HTML/JS components of dapp package downloads.

**Comment by arkpar** [comment]
Fixed in Mix for navigating DApp pages
