### ISSUE TITLE
Solidity/JS API: Array accessors "present" but nonfunctional.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1671]
Marking an array `public` will cause an accessor to appear in the ABI, regardless that arrays are not supposed to have accessors or that the "accessor" does not even work.

**Comment by chriseth** [comment]
Could you please explain what your expectation for array accessors are?
They should work, as shown in the unit test at https://github.com/ethereum/cpp-ethereum/blob/develop/test/libsolidity/SolidityEndToEndTest.cpp#L966.

**Comment by Smithgift** [comment]
My expectation was that they did not exist, because of a line in the "Solidity Features" page implying this. My mind must have added "not planned, either," though I'm not sure why.

What was happening was that it was returning nothing [to JS], but I suspect what was happening was a misunderstanding on my part about array lengths. Removing a kludge from my code and using the array's accessors directly seems to show this was a false alarm.
