### ISSUE TITLE
Are mapping accessors supposed to return structs [to JS API] while functions cannot?

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1673]
Calls to public mapping accessors seem to return the structs as [JS] arrays to javascript. This is fine. However, the solidity compiler will complain if a struct is in a return type of a public function. That's also OK, but it's inconsistent.

**Comment by chriseth** [comment]
Yes, the compiler/language is still in development. ;-)
The feature is planned, even in the form it is used in accessor functions:
If a function returns `(uint, uint, uint)` and it contains a statement `return x;` where `x` is of type `struct s { uint a; uint b; uint c }` then the members will be assigned to the return values in order.
