### ISSUE TITLE
crash in rangemask when downloading blocks

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#1674]
Main thread crashed. All other threads had already advanced.

(lldb) bt
* thread #1: tid = 0x31918, 0x00000001000305fa AlethZero`std::__1::__tree_node_base<void*>* std::__1::__tree_next<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*) [inlined] std::__1::__tree_node_base<void*>* std::__1::__tree_min<std::__1::__tree_node_base<void*>*>(__x=0xbaddc0dedeadbead) + 4 at __tree:134, name = 'CrBrowserMain', queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00000001000305fa AlethZero`std::__1::__tree_node_base<void*>* std::__1::__tree_next<std::__1::__tree_node_base<void*>*>(std::__1::__tree_node_base<void*>*) [inlined] std::__1::__tree_node_base<void*>* std::__1::__tree_min<std::__1::__tree_node_base<void*>*>(__x=0xbaddc0dedeadbead) + 4 at __tree:134
    frame #1: 0x00000001000305f6 AlethZero`std::__1::__tree_node_base<void*>* std::__1::__tree_next<std::__1::__tree_node_base<void*>*>(__x=0x0000600000a5e2a0) + 38 at __tree:158
    frame #2: 0x0000000100086338 AlethZero`dev::RangeMask<unsigned int>::RangeMask(dev::RangeMask<unsigned int> const&) [inlined] std::__1::__tree_const_iterator<std::__1::__value_type<unsigned int, unsigned int>, std::__1::__tree_node<std::__1::__value_type<unsigned int, unsigned int>, void*>*, long>::operator++(this=0x00007fff5fbf9c58) + 18 at __tree:747
    frame #3: 0x0000000100086326 AlethZero`dev::RangeMask<unsigned int>::RangeMask(dev::RangeMask<unsigned int> const&) [inlined] std::__1::__map_const_iterator<std::__1::__tree_const_iterator<std::__1::__value_type<unsigned int, unsigned int>, std::__1::__tree_node<std::__1::__value_type<unsigned int, unsigned int>, void*>*, long> >::operator++(this=0x00007fff5fbf9c58) + 14 at map:750
    frame #4: 0x0000000100086318 AlethZero`dev::RangeMask<unsigned int>::RangeMask(dev::RangeMask<unsigned int> const&) + 660 at map:1061
    frame #5: 0x0000000100086084 AlethZero`dev::RangeMask<unsigned int>::RangeMask(dev::RangeMask<unsigned int> const&) + 607 at map:885
    frame #6: 0x0000000100085e25 AlethZero`dev::RangeMask<unsigned int>::RangeMask(dev::RangeMask<unsigned int> const&) [inlined] std::__1::map<unsigned int, unsigned int, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<unsigned int const, unsigned int> > >::map(this=0x00007fff5fbfa228, __m=0x0000000109045c90) + 28 at map:886
    frame #7: 0x0000000100085e09 AlethZero`dev::RangeMask<unsigned int>::RangeMask(this=0x00007fff5fbfa220, (null)=0x0000000109045c88) + 89 at RangeMask.h:39
    frame #8: 0x0000000100085d9d AlethZero`dev::RangeMask<unsigned int>::RangeMask(this=0x00007fff5fbfa220, (null)=0x0000000109045c88) + 29 at RangeMask.h:39
  * frame #9: 0x000000010008247d AlethZero`dev::eth::DownloadMan::blocksGot(this=0x0000000109045ad8) const + 61 at DownloadMan.h:149
    frame #10: 0x000000010007fa65 AlethZero`DownloadView::paintEvent(this=0x000061800007c080, (null)=0x00007fff5fbfab70) + 1557 at DownloadView.cpp:54
    frame #11: 0x000000010084fc0b QtWidgets`QWidget::event(QEvent*) + 2123
    frame #12: 0x000000010081032b QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
    frame #13: 0x0000000100813648 QtWidgets`QApplication::notify(QObject*, QEvent*) + 8136
    frame #14: 0x0000000107ea4d83 QtCore`QCoreApplication::notifyInternal(QObject*, QEvent*) + 115
    frame #15: 0x0000000100849370 QtWidgets`QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 3152
    frame #16: 0x0000000100849c9a QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1226
    frame #17: 0x0000000100849700 QtWidgets`QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4064
    frame #18: 0x0000000100849c9a QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1226
    frame #19: 0x0000000100849700 QtWidgets`QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4064
    frame #20: 0x0000000100849c9a QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 1226
    frame #21: 0x0000000100849b20 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 848
    frame #22: 0x0000000100849b20 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 848
    frame #23: 0x0000000100849b20 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 848
    frame #24: 0x0000000100849b20 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 848
    frame #25: 0x0000000100849b20 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 848
    frame #26: 0x0000000100849b20 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 848
    frame #27: 0x0000000100849b20 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 848
    frame #28: 0x0000000100849b20 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 848
    frame #29: 0x0000000100849b20 QtWidgets`QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 848
    frame #30: 0x0000000100849700 QtWidgets`QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) + 4064
    frame #31: 0x000000010081cd76 QtWidgets`___lldb_unnamed_function223$$QtWidgets + 4230
    frame #32: 0x000000010081d0b3 QtWidgets`___lldb_unnamed_function228$$QtWidgets + 499
    frame #33: 0x00000001008400cc QtWidgets`QWidgetPrivate::syncBackingStore() + 236
    frame #34: 0x000000010084fed4 QtWidgets`QWidget::event(QEvent*) + 2836
    frame #35: 0x0000000100952b21 QtWidgets`QMainWindow::event(QEvent*) + 929
    frame #36: 0x000000010081032b QtWidgets`QApplicationPrivate::notify_helper(QObject*, QEvent*) + 251
    frame #37: 0x0000000100813648 QtWidgets`QApplication::notify(QObject*, QEvent*) + 8136
    frame #38: 0x0000000107ea5a5b QtCore`QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 971
    frame #39: 0x000000010c97bb8e libqcocoa.dylib`___lldb_unnamed_function440$$libqcocoa.dylib + 190
    frame #40: 0x000000010c97c411 libqcocoa.dylib`___lldb_unnamed_function452$$libqcocoa.dylib + 33
    frame #41: 0x00007fff95134a01 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    frame #42: 0x00007fff95126b8d CoreFoundation`__CFRunLoopDoSources0 + 269
    frame #43: 0x00007fff951261bf CoreFoundation`__CFRunLoopRun + 927
    frame #44: 0x00007fff95125bd8 CoreFoundation`CFRunLoopRunSpecific + 296
    frame #45: 0x00007fff958db56f HIToolbox`RunCurrentEventLoopInMode + 235
    frame #46: 0x00007fff958db2ea HIToolbox`ReceiveNextEventCommon + 431
    frame #47: 0x00007fff958db12b HIToolbox`_BlockUntilNextEventMatchingListInModeWithFilter + 71
    frame #48: 0x00007fff925ce9bb AppKit`_DPSNextEvent + 978
    frame #49: 0x00007fff925cdf68 AppKit`-[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 346
    frame #50: 0x00007fff925c3bf3 AppKit`-[NSApplication run] + 594
    frame #51: 0x000000010c97b2fd libqcocoa.dylib`___lldb_unnamed_function434$$libqcocoa.dylib + 2189
    frame #52: 0x0000000107ea237d QtCore`QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 381
    frame #53: 0x0000000107ea535a QtCore`QCoreApplication::exec() + 346
    frame #54: 0x000000010019e667 AlethZero`main(argc=3, argv=0x00007fff5fbfe6c0) + 183 at main.cpp:11
    frame #55: 0x00007fff9a7805c9 libdyld.dylib`start + 1

**Comment by gavofyork** [comment]
check latest develop. much threading stuff has changed.

**Comment by subtly** [comment]
Indeed -- have downloaded from a few machines, no problems.
