### ISSUE TITLE
AlethZero crash when starting mining

### ISSUE THREAD

**Issue by tymat** [ethereum/cpp-ethereum#1675]
**Version**

Latest develop branch

````
4fa948d10a52c1efebab49613803b484950022de
````

**Stack Trace**

https://gist.github.com/tymat/8df265cf4a3901b2695f

**Comment by gavofyork** [comment]
could you check again - a bunch of stuff was recently changed.

**Comment by tymat** [comment]
Thanks.  Latest develop branch works now.  

66a4752cf2e127b93b0cdb2c1ec52288edb4c55a
