### ISSUE TITLE
Mix: contract non-constant public functions default to actual transactions.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1677]
When calling a function of a contract in mix (i.e. contracts["Foo"].contract.bar()), constant functions such as accessors will use call() by default, while others will blithely send a real transaction. If this is intended behavior, it's the opposite of what's documented.

The contract object itself has a `_isTransaction: Error: Object.getOwnPropertyNames called on non-object` in it, which might be where it is breaking.

**Comment by yann300** [comment]
This is the correct behavior. Where did you found the documentation?

**Comment by Smithgift** [comment]
JS API on the main wiki, example for web3.eth.contract implies that JS default is the same as .call().

If this is intended, I'm going ahead and closing this.
