### ISSUE TITLE
Sending transactions in AlethZero causes hang

### ISSUE THREAD

**Issue by tymat** [ethereum/cpp-ethereum#1680]
This transaction just freezes AlethZero (develop) on OS X

66a4752cf2e127b93b0cdb2c1ec52288edb4c55a

![Screenshot](http://i.imgur.com/nuw6HDD.png "Screenshot")

**Comment by oed** [comment]
Can confirm this on archlinux as well. Both transactions from within Alethzero and from web3.js causes hang.

**Comment by angseus** [comment]
I also have this problem on Mac OS X.

**Comment by tehMalone** [comment]
I have this problem too - my full description:

Every time I try to send a transaction, the GUI freezes. I can see in my terminal that I'm continuing to sync my block chain, but the GUI is totally unresponsive. I'm on Ubuntu 14.04 and I just updated Alethzero to 0.9.13, yet this didn't solve the problem.

**Comment by Lollike** [comment]
Same issue here on Mac OS X and Ubuntu 14.04

**Comment by hedmanw** [comment]
I have the same issue with 7023867 on arch linux.
