### ISSUE TITLE
Suggestion/question: Inversing a mapping in the JS API.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1703]
My testing DApp has since gone to arrays, but consider something as simple as a sub-coin. Suppose you wanted to make a list of every coin-holder and display it to the user. How do you get from the positions of data in storage back to the original addresses?

This doesn't seem theoretically impossible to do, though if there's a current way to do it, I haven't stumbled on it.

**Comment by gavofyork** [comment]
there's no simple way of doing this.
