### ISSUE TITLE
Dynamic call in solidity

### ISSUE THREAD

**Issue by nmushegian** [ethereum/cpp-ethereum#1705]
I would like to be able to be able to do a call to a solidity contract if I know the function signature at 
runtime but not compile time. 

something like: a.call("f", args, types)

The minimum required to enable this in solidity is the ability to set calldata (is that already a feature?)

**Comment by chriseth** [comment]
It is already there, almost in the same way you describe:
`a.call(bytes4(sha3("f(uint256,uint256)"), 12, 13);`
should work

**Comment by chriseth** [comment]
Did you try again?
