### ISSUE TITLE
abi executable issues

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#1722]
Issues that i've found in abi executable. To test abi, I moved the code to a separate library and created a test suite. Code is available [here](https://github.com/ethereum/cpp-ethereum/pull/1489)
- [ ] when encoding methods with number of input params > 0, we need to add additional command line param, which is unused
- [ ] formatting negative ints is not correct (see encode_negative_int test_case)
- [x] usage of --format-prefix is not clear or do not work

**Comment by gavofyork** [comment]
format prefix is mostly unimplemented; only works for `0x`, i think.

**Comment by axic** [comment]
`ethabi` tool has been removed
