### ISSUE TITLE
cmake full gui=0 fails

### ISSUE THREAD

**Issue by slothbag** [ethereum/cpp-ethereum#1723]
For some reason cmake is ignoring the if (GUI) and failing with this..

CMake Error at cmake/EthDependencies.cmake:140 (find_package):
  By not providing "FindQt5WebEngine.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5WebEngine", but CMake did not find one.

**Comment by gavofyork** [comment]
not sure... any idea @debris  ?

**Comment by gavofyork** [comment]
could you paste the output from cmake?

**Comment by slothbag** [comment]
This was the outout..

```
CMake Error at cmake/EthDependencies.cmake:140 (find_package):
By not providing "FindQt5WebEngine.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"Qt5WebEngine", but CMake did not find one.
```

./cmake/ethDependencies.cmake line 140 references QT, but on line 121 there is a if (GUI) which doesn't appear to be working.

**Comment by debris** [comment]
I cannot reproduce. I uninstalled qt, run `cmake -DGUI=OFF ..` and everything works as expected. Can you double check that you are trying to build the project with exactly this options?

also
> ```
CMake Error at cmake/EthDependencies.cmake:140 (find_package):
By not providing "FindQt5WebEngine.cmake" in CMAKE_MODULE_PATH this project
has asked CMake to find a package configuration file provided by
"Qt5WebEngine", but CMake did not find one.
```

is failing for you, cause GUI is still set to ON && you have old version of Qt. Version 5.4 is recommended.

**Comment by slothbag** [comment]
cmake DGUI=OFF works.. Wiki incorrectly says to use -DGUI=0

https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu

**Comment by debris** [comment]
`-DGUI=0` also works. The issue was `-DBUNDLE=full`. It should be used only to build everything (including `GUI`). I updated wiki page.
