### ISSUE TITLE
eth_hashrate RPC method

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#1724]
In [go implementation](https://github.com/ethereum/go-ethereum/pull/698) hashrate is available at `ext_hashrate`, not `eth_hashrate`. Should we fix this in cpp implementation?

**Comment by gavofyork** [comment]
go is incorrect. it should be `eth_hashrate`.

**Comment by obscuren** [comment]
There is no `eth_hashrate`. `ext_hashrate` because it's an extension on the regular rpc interface.

**Comment by tgerring** [comment]
How about `eth_miningRate`? It removes the unit from the name scheme (hashes/sec) and lexically keeps it close to related calls
