### ISSUE TITLE
solidity bytes encoding

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#1733]
I think that [ABI documentation](https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#examples) might be misleading a little.

Are bytes32 encoded in the same way as bytes? I found this sentence in the documentation:

> A bytes of length N is encoded the same way as bytes<N>

And later in the examples, encoding of bytes 'dave' is done like:

>0x0000000000000000000000000000000000000000000000000000000000000004: the size of the first dynamic parameter, measured as the bytes type length in bytes. In this case, 4.
...
0x6461766500000000000000000000000000000000000000000000000000000000: the first parameter: the UTF-8 (equal to ASCII in this case) encoding of "dave".

But when I call a function which returns `bytes32` (eg. [namereg](https://github.com/ethereum/wiki/wiki/Registrar-ABI) ) it does only return the parameter without it's dynamic length.

```
"0x6761766f66796f726b0000000000000000000000000000000000000000000000"
```

Is this expected behaviour?  If the length is specified in the type, is it omitted in bytes?

I would like to compare it with `bytes`, but I'm unable to compile function which returns `bytes`.

**Comment by chriseth** [comment]
`bytes32` has fixed length, so its value is encoded without an explicit length. I think the cited part of the specification refers to the data part of the `bytes` type which is indeed encoded in exactly the same way.
