### ISSUE TITLE
 NotEnoughCash Exception when sending transaction with web3

### ISSUE THREAD

**Issue by tehMalone** [ethereum/cpp-ethereum#1739]
Whenever I try to send a transaction through my GUI client I get this error:
  ℹ  12:33:04 PM|alethzero  New transaction {aa6416e3…/20$0+2398510@10000000000000<-78ceb033… #4}
  ℹ  12:33:04 PM|eth  #cc50952e… Dropping invalid transaction: /build/buildd/cpp-ethereum-0.9.13+750SNAPSHOT20150424081335trusty/libethereum/State.cpp(965): Throw in function void dev::eth::State::subBalance(dev::Address, dev::bigint)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::NotEnoughCash>
std::exception::what: std::exception

The code I'm using 

$("#useClip").on('click', function(){
	machineInstance.sendTransaction().buyCoffee();
});

Is this a bug or am I doing something wrong?

**Comment by CJentzsch** [comment]
Looks like you balance is not high enough for the transaction. A transaction costs at least 21000 * gasPrice wei.

**Comment by tehMalone** [comment]
But shouldn't sendTransaction default the gas price to what I have in my balance? That what I got from https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsendtransaction

Otherwise, how do I make sure that I send enough gas with the transaction?

**Comment by CJentzsch** [comment]
Currently it defaults to 10 szabo, it has nothing to do with your balance. What is your balance?

**Comment by tehMalone** [comment]
23985 finney

**Comment by CJentzsch** [comment]
How much value are you trying to send? What is the gasLimit? What is your data? With it I can calculate exactly what it should cost.

**Comment by tehMalone** [comment]
We haven't figured out how to get the gasLimit - do you have a resource for this? The one I'm trying here doesn't take any data - the solidity code it's running is this:

	function buyCoffee() returns (bool success){
		if(clipcards[msg.sender].name == "") {
			return false;
		}
		deductClip(msg.sender);
		return true;
	}

	function deductClip(address beneficiary) returns (bool success) {
		Clipcard c = clipcards[beneficiary];
		if(c.amountOfClips < 0){
			return false;	
		}
		c.amountOfClips -= 1;
		return true;
	}

I searched to figure out how to determine how much gas an operation needs, but the resources are quite vague imho.

**Comment by CJentzsch** [comment]
The transaction doesn't make it that far because of exception you described above.
You can set all values of the tx as described here: https://github.com/ethereum/wiki/wiki/JavaScript-API#parameters-22 (your link).
It looks like gasPrice (usually 10 szabo) * gas (at least 21000, but for a contract call much more) + value < your balance.

**Comment by tehMalone** [comment]
Is there anyway to calculate the gas a contract call uses? Because it shouldn't be more than my balance (I can use the "Send Transaction" dialogue just fine)

**Comment by CJentzsch** [comment]
thats not trivial, generally it can depend on block number, and many other environment paramters. But you can now exactly how much ether you need for a transaction by specifiying gas (=gasLimit) and gasPrice, and you get back the gas you didnt use. Just try it out, then you know how much gas it used.

**Comment by tehMalone** [comment]
Thank you very much - I'll tinker around with it.

I also see that the descriptions for the Javascript API has been changed since I looked at them (a few days ago)

**Comment by tehMalone** [comment]
Is my understanding correct when I think that

	machineInstance.buyCoffee({gas: 1000000});

Should send 10 ether as gas? Because I can't see how my method would cost more that 10 ether in gas?

**Comment by CJentzsch** [comment]
this is  1000000 wei. 1 ether = 10^18 wei. 1 finney = 10^15 wei, 1 szabo = 10^12 wei.

**Comment by tehMalone** [comment]
Turns out that this piece of code, which is essentially copied from the JavaScript API, doesn't send the transaction with the right value or gas specified.

machineInstance.buyClipcard($("#cardname").val(), {from: web3.eth.coinbase, value: price, gas: web3.toWei(1000, "finney")});

It still sends a transaction with 0 value and 33000 (or so) gas
