### ISSUE TITLE
GET_BLOCKS was answered with BLOCKS one block short

### ISSUE THREAD

**Issue by romanman** [ethereum/cpp-ethereum#1741]
Here is the request for 100 blocks 
with the actual hashes but the
response was with block number - 28 missing

http://pastebin.com/raw.php?i=ciddk76Q

**Comment by romanman** [comment]
tried on older commit `e725f9a2796db5a0d267ef15c5b3f34fced43b4c`
and it was ok...

**Comment by gavofyork** [comment]
er... and?!

there is no guarantee here.

**Comment by romanman** [comment]
@gavofyork : So how you deal with that missing blocks ?
