### ISSUE TITLE
error while loading shared libraries: libethash.so

### ISSUE THREAD

**Issue by jeffanthony** [ethereum/cpp-ethereum#1760]
After today's update via ppa -- attempting to run mix, alethzero, or eth responds:

"error while loading shared libraries: libethash.so: cannot open shared object file: No such file or directory"

**Comment by LefterisJP** [comment]
This should probably address your issue: https://github.com/ethereum/cpp-ethereum/pull/1756

**Comment by jeffanthony** [comment]
Working. Thank you. I added the development ppa and reinstalled cpp-ethereum, eth, elethzero, and mix.
