### ISSUE TITLE
javascript console

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#1763]
This is a roadmap for [v8console](https://github.com/debris/cpp-ethereum/tree/v8console) branch. The goal is to have javascript console similar to one in geth.

- [x] utilize v8 (FindV8.cmake)
- [x] utilize brew version of v8 (it's using libstdc++)
- [x] prepare libjsengine
- [x] prepare libjsconsole
- [x] repl
- [x] repl multiline expressions
- [x] eth `--console` option
- [x] fix xcode build of libjsengine ([`CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY`](http://stackoverflow.com/questions/19345180/what-cmake-variable-is-used-to-set-c-standard-library-in-xcode))
- [x] make v8 optional global dependency
- [x] load web3 into js namespace
- [x] pretty print console output
- [x] write tests for handling incorrect input
- [x] connect web3 to rpc provider
- [x] add v8 dependency to homebrew ([PR](https://github.com/ethereum/homebrew-ethereum/pull/22))
- [x] test on linux
- [x] add v8 dependency to linux ppa
- [x] make `readline` optional for `libjsconsole`
- [x] test on windows

**Comment by caktux** [comment]
Added `libv8-dev` in ethereum/ethereum-ppa@48fdb76
