### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by conradjohnson** [ethereum/cpp-ethereum#1780]
From latest pull: 
cmake -DETHASHCL=1 ..
finished successfully

make produced this:
Building CXX object libethereum/CMakeFiles/ethereum.dir/Interface.cpp.o
Building CXX object libethereum/CMakeFiles/ethereum.dir/Client.cpp.o
[ 46%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Account.cpp.o
/home/jimmy/gitrepo/cpp-ethereum/libethereum/Client.cpp: In member function ‘dev::eth::State dev::eth::Client::state(unsigned int) const’:
/home/jimmy/gitrepo/cpp-ethereum/libethereum/Client.cpp:738:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors
make[2]: *** [libethereum/CMakeFiles/ethereum.dir/Client.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libethereum/CMakeFiles/ethereum.dir/all] Error 2
make: *** [all] Error 2

**Comment by gavofyork** [comment]
fixed in latest develop.
