### ISSUE TITLE
Implement newBlockFilter proposal

### ISSUE THREAD

**Issue by frozeman** [ethereum/cpp-ethereum#1815]
Please implement the following spec:
https://github.com/ethereum/wiki/wiki/newBlockFilter-Improvement-Proposal#new-proposal

The JSON RPC specs are also updated accordingly: 
- https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newblockfilter
- https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_newpendingtransactionfilter
- https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getfilterchanges

**Comment by debris** [comment]
done in #2108
