### ISSUE TITLE
verifyParent minimum gas limit off-by-one

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/cpp-ethereum#1832]
In BlockTests/bcGasPricerTest.json highGasUsage we have genesis block gas limit: https://github.com/ethereum/tests/blob/develop/BlockTests/bcGasPricerTest.json#L406
```
0x01df5e70 == 31415920
```
According to YP eq 41 a block's gas limit must be greater than parent gas limit minus floor of parent gas limit divided by 1024.

In this case we get:
```
 31415920 - floor(31415920 / 1024) == 31385241
```
The first block in this test has a gas limit of 0x01dee698 == 31385240.

Go considers this invalid, and rejects the block. The test passes in cpp.

https://github.com/ethereum/cpp-ethereum/blob/develop/libethcore/BlockInfo.cpp#L257
```
gasLimit < _parent.gasLimit * (c_gasLimitBoundDivisor - 1) / c_gasLimitBoundDivisor
```
Since cpp code is known to occasionally enjoy the wonders of operator overloading, I'll just assume the integer division here behaves as is defined for non-overloaded cpp integer division operator, which for positive operands returns the algebraic quotient with any fractional part discarded.

```
31415920 * (1024 - 1) / 1024 == 31385240.390625
```
which truncates to 31385240

We thus get a behavior different from the YP spec resulting in consensus failure between Go and cpp.

For more information on how to properly handle limits, please see https://www.youtube.com/watch?v=BhsTmiK7Q2M#t=18s

**Comment by CJentzsch** [comment]
yeah, the problem here is that the multiplication is done before the division. Which is wrong, https://github.com/ethereum/cpp-ethereum/pull/1853 fixes it.
