### ISSUE TITLE
Can't get past block #29999 - Import queue contains block with unknown parent

### ISSUE THREAD

**Issue by cslarson** [ethereum/cpp-ethereum#1845]
I'm using the latest develop branch, and on downloading blocks, seem to get stuck at #29999 (according to eth stats the most recent block as of writing this is #295,619). The console then keeps repeating the following:

```
  ✘  12:08:28|eth  ODD: Import queue contains block with unknown parent. /home/carl/src/cpp-ethereum-develop/libethereum/BlockChain.cpp(415): Throw in function dev::eth::ImportRoute dev::eth::BlockChain::import(const bytes&, const dev::OverlayDB&, dev::eth::ImportRequirements::value)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::UnknownParent>
std::exception::what: std::exception
```

I've tried killing the blockchain and connecting to different peers from http://stats.ethdev.com/ but the same happens (3 times). I've also tried "Retry Unknown Parent Blocks".
If I keep the client connected should I expect it to eventually resolve itself?

**Comment by chriseth** [comment]
Is this still happening with the latest version?

**Comment by cslarson** [comment]
No, I've not seen this issue since.
