### ISSUE TITLE
Both AZ and eth think another instance is running (9.17)

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#1846]
Installed 9.17 on buntu 14.04 via dev PPA as per https://github.com/ethereum/cpp-ethereum/wiki/Installing-clients

Ran AlethZero once, quit
rebooted machine

now when i either start AZ or eth:

```
Client database version: 12041
⧎ ℹ  12:33:28|alethzero  Id: ##ced661ac…
  ℹ  12:33:28|alethzero  Opened blockchain DB. Latest: #3aee018d…
  ✘  12:33:28|alethzero  Database already open. You appear to have another instance of ethereum running. Bailing.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::eth::DatabaseAlreadyOpen>'
  what():  std::exception
Aborted (core dumped)
```

Tried reinstalling, no dice.

**Comment by stephantual** [comment]
I have a strange feeling this could be related to the fact that Go and Cpp seem to compete for ~/.ethereum  on buntu, as wiping the folder solves the issue, only for the problem to reappear when i run either client.

**Comment by abueesp** [comment]
Agree Stephan

  ✘  21:56:59|alethzero  Database already open. You appear to have another instance of ethereum running. Bailing.
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::eth::DatabaseAlreadyOpen>'
  what():  std::exception
Aborted (core dumped)

When I delete .ethereum folder created by Go, Alethzero cpp could run. 
Any ideas to re-path .ethereum on one of those?

**Comment by abueesp** [comment]
on geth (Go) you can use datadir:
geth  --datadir "/datadirectorytobeused/.ethereum"

**Comment by gavofyork** [comment]
fixed in latest.
