### ISSUE TITLE
ethminer doesn't play nice with geth

### ISSUE THREAD

**Issue by kobigurk** [ethereum/cpp-ethereum#1850]
after playing with it *a lot* I believe ethminer produces blocks with invalid nonce
[I use geth as farm server and ethminer as miner, and always gets invalid nonce on the produced blocks.
which logs would help you debug it?

**Comment by Genoil** [comment]
Is it different for you when using ++eth as farm server? I had set that up, and also noticed a fairly high rate of bad blocks from ethminer. I'll try to post some output later.

**Comment by nethyb** [comment]
I've also been able to repeat this behaviour. Using ethminer with geth as the farm server. Using OpenCL mining with ethminer (tested both on AMD and NVIDIA hardware). Maybe around 5% of mined blocks would be accepted, the others we're mostly 'Block's nonce is invalid' or "block time stamp equal to previous" 

Here is some geth log output:

I0511 14:56:16.142178    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 6.502009ms. #304035 [a180d723 / a180d723]
I0511 14:56:16.954775    6999 worker.go:326] commit new work on block 304036 with 4 txs & 0 uncles
I0511 14:56:20.023282    6999 chain_manager.go:558] INVALID block #304034 (8273e032d8fe742ca1c288db645e59479f62384855d68f6dfb091eed1377b92b)
I0511 14:56:20.023408    6999 chain_manager.go:559] **block time stamp equal to previous**
I0511 14:56:20.741601    6999 worker.go:326] commit new work on block 304036 with 4 txs & 0 uncles
I0511 14:56:27.821639    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 672.894998ms. #304036 [179e33a6 / 179e33a6]
I0511 14:56:27.822641    6999 chain_manager.go:628] imported 0 block(s) (0 queued 1 ignored) in 575.887574ms. #304036 [179e33a6 / 179e33a6]
I0511 14:56:27.975724    6999 worker.go:326] commit new work on block 304037 with 2 txs & 0 uncles
I0511 14:56:32.520809    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 5.900926ms. #304037 [e3766ece / e3766ece]
I0511 14:56:32.774144    6999 worker.go:326] commit new work on block 304038 with 2 txs & 0 uncles
I0511 14:56:52.351441    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 11.9602ms. #304037 [f905426d / f905426d]
I0511 14:56:59.866454    6999 chain_manager.go:580] Split detected. New head #304038 (8f44035b) TD=21626962493764, was #304037 (e3766ece) TD=21626677925362
I0511 14:56:59.867244    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 6.380856ms. #304038 [8f44035b / 8f44035b]
I0511 14:57:00.053201    6999 worker.go:326] commit new work on block 304039 with 2 txs & 0 uncles
I0511 14:57:10.023291    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 8.133817ms. #304039 [29f9693f / 29f9693f]
I0511 14:57:10.210790    6999 worker.go:326] commit new work on block 304040 with 2 txs & 0 uncles
I0511 14:57:10.883123    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 129.713511ms. #304040 [09b72e26 / 09b72e26]
I0511 14:57:10.883256    6999 worker.go:215]   **Mined block #304040**
I0511 14:57:10.883938    6999 worker.go:326] commit new work on block 304041 with 0 txs & 0 uncles
I0511 14:57:16.048014    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 5.397393ms. #304041 [2de9ae16 / 2de9ae16]
I0511 14:57:16.048825    6999 worker.go:326] commit new work on block 304042 with 0 txs & 0 uncles
I0511 14:57:22.415186    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 10.797833ms. #304042 [200d5dff / 200d5dff]
I0511 14:57:22.416032    6999 worker.go:326] commit new work on block 304043 with 0 txs & 0 uncles
I0511 14:57:49.682218    6999 chain_manager.go:628] imported 0 block(s) (0 queued 1 ignored) in 54.694177ms. #304043 [c3c41659 / c3c41659]
I0511 14:57:49.683525    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 98.080243ms. #304043 [c3c41659 / c3c41659]
I0511 14:57:49.684438    6999 worker.go:326] commit new work on block 304044 with 0 txs & 0 uncles
I0511 14:58:02.689132    6999 chain_manager.go:558] INVALID block #304044 (ca89231a9c4c6b7d80357a285becd13e2910ff50a43f20c2d2b1321079ff6801)
I0511 14:58:02.689215    6999 chain_manager.go:559] **Block's nonce is invalid (= 0000000003a6597f)**
I0511 14:58:02.689926    6999 worker.go:326] commit new work on block 304044 with 0 txs & 0 uncles
I0511 14:58:06.234120    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 6.325277ms. #304044 [5567cb9d / 5567cb9d]
I0511 14:58:06.234868    6999 worker.go:326] commit new work on block 304045 with 0 txs & 0 uncles
I0511 14:58:10.183578    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 218.283556ms. #304038 [4b2573f1 / 4b2573f1]
I0511 14:58:17.791307    6999 chain_manager.go:628] imported 1 block(s) (0 queued 0 ignored) in 6.486431ms. #304045 [3acd8e39 / 3acd8e39]
I0511 14:58:17.940849    6999 worker.go:326] commit new work on block 304046 with 1 txs & 0 uncles
I0511 14:58:24.875937    6999 chain_manager.go:558] INVALID block #304045 (1fc44170b2fb0366771ff703283835644cac479ea63c36291f7a79f96963978f)
I0511 14:58:24.876020    6999 chain_manager.go:559] **Block's nonce is invalid (= 0000000003a6597f)**
I0511 14:58:25.295357    6999 worker.go:326] commit new work on block 304046 with 2 txs & 0 uncles

**Comment by arhuaco** [comment]
geth mines Ok with CPU and ethminer passes the GPU benchmark with "min/mean/max: 1835008/1852484/1922389 H/s.

If I connected from ethminer I get:

- "GPU mining. GPU memory fragmentation?"
- "Mining on PoWhash #e38c9b83… : 0 H/s = 0 hashes / 1.002 s".

If I switch to mine from the eth binary mining works (getting core dumps with FP exceptions once in a while but it works).

**Comment by kobigurk** [comment]
It works great after today's commits.
