### ISSUE TITLE
AlethZero will bail after geth downloads chain

### ISSUE THREAD

**Issue by Azulan** [ethereum/cpp-ethereum#1852]
http://pastebin.com/JZf0zFk3 is the output I get after starting AlethZero. Using the precompiled binary built at 5/10/15 05:57 CST found at https://build.ethdev.com/builds/Windows%20C%2B%2B%20develop%20branch/. I used geth to download the full blockchain, terminated that process and started alethzero. It consistently bails with this and similar messages. If I delete all of the chain data it will operate normally, but this is not ideal.

**Comment by chriseth** [comment]
Created new issue: #2354 - closing this.
