### ISSUE TITLE
OSX via Brew : folders for config files/blockchains could lead to key loss in the future

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#1862]
AlethZero
~/Library/Application Support/Ethereum (contains the blockchain state)
 ~/Library/Preferences/com.ethereum.alethzero.plist (contains AZ preferences and your keys)
 
Eth:
~/Library/Application Support/Ethereum (contains the blockchain state, shares it with alethzero)
~/Library/Application Support/Ethereum/config.rlp (contains your keys)

First, I'm not sure how Eth and AZ behave when sharing the same blockchain folder (about to find out, but wanted to post this before i climb back the chain on AZ which takes a while). 

Second, if you delete ~/Library/Application Support/Ethereum  in order to clear the blockchain state, you'd end up wiping your config.rlp, which just happens to contain your eth keys. 

Not a problem on testnet but when we're live this could lead to tears. 

Proposal: at the very list put the eth keys in a plist or a file separate from where AZ does its business.

**Comment by gavofyork** [comment]
keys now stored elsewhere (.web3)
