### ISSUE TITLE
eth interactive mode starts mining a 0kh, then can't hang on minestop

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#1867]
```
eth -i
minestart
```

notice how the node stop receiving blocks/talking to the network 

```
minestop
```

eth hangs, needs restart.

**Comment by chriseth** [comment]
It does not exactly hang for me, but it does not stop generating the DAG upon `minestop`. Is that the issue?

**Comment by gavofyork** [comment]
please verify this is still the case.

**Comment by LefterisJP** [comment]
Stephan said this is no longer an issue
