### ISSUE TITLE
alethzero can't get past 137xxx block, OSX

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#1868]
OSX Mav,
commit is 88fc3214b0417b7e21e64ba33d89965e3ef6da78
brewed from tap

Completely deleted, including config files and reinstalled
AZ always hangs around block 137512

Force Quit AZ, restart, block shows 137555 

Never climbs above that.

Log fills with: 

```
22:18:12|p2p|a6c4f3a0…|++eth/v0.9.17/Release/Darwin/clang/int  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  22:18:12|p2p|a6c4f3a0…|++eth/v0.9.17/Release/Darwin/clang/int  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▣┅▶  22:18:12|p2p|a6c4f3a0…|++eth/v0.9.17/Release/Darwin/clang/int  OK - ready for chain insertion.
▣┅▶  22:18:12|p2p|a6c4f3a0…|++eth/v0.9.17/Release/Darwin/clang/int  Queuing block #7689ebcf… for import...
```

**Comment by iurimatias** [comment]
getting the same thing, but on block #137501

also see issue #1877

**Comment by stephantual** [comment]
Tried with be292df191251de2b93e0822e9777fd24212f244, brewed from tap, wiped the chain, wiped everything clean

Didn't even load AZ in case it was an AZ thing... and sure enough, eth hangs at block 137555

**Comment by stephantual** [comment]
tried to get a log for you guys - but how do you make eth silent on screen and piping all its output to a text file?

**Comment by stephantual** [comment]
Update: wanted to get to the bottom of this so let it run overnight - it hung at 137555 again, but this morning (around 8h later) is now at 240xxx and climbing.

**Comment by stephantual** [comment]
update: you know what's odd? If I eth -E ~/file then wipe everything, upon eth -I ~/file it hangs and goes 100% cpu time on that very same block 137555. So it's nothing to do with network etc.

**Comment by stephantual** [comment]
For what it's worth, i took a screeshot - as you can see even on a manual import using -I it takes approx 45 to load block 137555 . there are  few blocks after that hangs, total load time (no network involved) is approx 8h. 

http://monosnap.com/image/SeSC8ePb9IlsopkBZChl6tkWodcVME
