### ISSUE TITLE
AlethZero can't understand any of its peers. 

### ISSUE THREAD

**Issue by etherum** [ethereum/cpp-ethereum#1872]
Built from master ~30 minutes ago on OSX.

    !N! [ 00:22:29 | p2p | 88 ] Error reading: Connection reset by peer
    !P! [ 00:22:31 | p2p ] Exception processing message from 115.187.251.154 : 41043
    !P! [ 00:22:31 | p2p ] Exception processing message from 92.51.165.126 : 30303
    !P! [ 00:22:31 | p2p ] Exception processing message from 217.91.30.228 : 30303
    *P* [ 00:22:31 | p2p ] Terminating discover after 3  rounds.
    !P! [ 00:22:31 | p2p ] Exception processing message from 217.91.30.228 : 30303
    !N! [ 00:22:34 | p2p | 78 ] Error reading: Connection reset by peer
    !N! [ 00:22:34 | p2p | 76 ] Error reading: Connection reset by peer
    *P* [ 00:22:36 | p2p ] Noting active node: 01365d37… 69.164.196.239 : 30303
    !P! [ 00:22:36 | p2p ] Exception processing message from 69.164.196.239 : 30303
    !N! [ 00:22:37 | p2p | 94 ] Error reading: Connection reset by peer
    !N! [ 00:22:38 | p2p | 90 ] Error reading: Connection reset by peer
    !N! [ 00:22:38 | p2p | 85 ] Error reading: Connection reset by peer
    *P* [ 00:22:40 | p2p ] Noting active node: a0fd3473… 115.187.251.154 : 41043
    !N! [ 00:22:42 | p2p | 83 ] Error reading: Connection reset by peer
    *P* [ 00:22:43 | p2p ] Noting active node: 82995248… 52.10.246.62 : 30303
    !P! [ 00:22:43 | p2p ] Exception processing message from 52.10.246.62 : 30303
    !N! [ 00:22:43 | p2p | 98 ] Error reading: Connection reset by peer
    !N! [ 00:22:46 | p2p | 97 ] Error reading: Connection reset by peer
    !N! [ 00:22:49 | p2p | 102 ] Error reading: Connection reset by peer
    !N! [ 00:22:54 | p2p | 80 ] Error reading: Connection reset by peer
    !N! [ 00:22:54 | p2p | 105 ] Error reading: Connection reset by peer
    !N! [ 00:22:54 | p2p | 95 ] Error reading: Connection reset by peer
    !N! [ 00:22:56 | p2p | 100 ] Error reading: Connection reset by peer
    !N! [ 00:22:58 | p2p | 112 ] Error reading: Connection reset by peer
    !P! [ 00:23:01 | p2p ] Exception processing message from 115.187.251.154 : 41043
    !P! [ 00:23:01 | p2p ] Exception processing message from 92.51.165.126 : 30303
    *P* [ 00:23:01 | p2p ] Terminating discover after 3  rounds.
    !P! [ 00:23:02 | p2p ] Exception processing message from 217.91.30.228 : 30303
    !P! [ 00:23:02 | p2p ] Exception processing message from 217.91.30.228 : 30303
    !N! [ 00:23:03 | p2p | 62 ] Error reading: Connection reset by peer
    !N! [ 00:23:07 | p2p | 108 ] Error reading: Connection reset by peer
    !N! [ 00:23:10 | p2p | 87 ] Error reading: Connection reset by peer
    !N! [ 00:23:10 | p2p | 119 ] Error reading: Connection reset by peer
    !N! [ 00:23:11 | p2p | 67 ] Error reading: Connection reset by peer
    !N! [ 00:23:11 | p2p | 63 ] Error reading: Connection reset by peer
    !N! [ 00:23:13 | p2p | 109 ] Error reading: Connection reset by peer
    !N! [ 00:23:14 | p2p | 101 ] Error reading: Connection reset by peer
    !N! [ 00:23:14 | p2p | 113 ] Error reading: Connection reset by peer

Never manages to sync, seemingly as a result of not being able to talk to any peers. go-ethereum happily syncs on the same machines, same network, without a problem.

**Comment by 18dew** [comment]
Same error alethezero not understanding langua of peers

**Comment by 18dew** [comment]
Followed by connection reset by peers

**Comment by arkpar** [comment]
could you please retest on latest develop?

**Comment by subtly** [comment]
This was due to go issuing bad neighbours packets and has been resolved. Please reopen if issue has persisted.
