### ISSUE TITLE
Mix binary broken? libethash.so missing.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1874]
Mix no longer starts in the latest dev binary on Ubuntu, complaining of a missing library. I suspect some package is missing, but nothing I've tried downloading has repaired it, which makes me further suspect something didn't make it into the dev packages in the first place. 

```
mix: error while loading shared libraries: libethash.so: cannot open shared object file: No such file or directory
```

**Comment by debris** [comment]
Can you pull latest develop, rerun cmake and try again? #1871 probably fixed the issue

**Comment by Smithgift** [comment]
This is from the *binary package* (I believe `cpp-ethereum_0.9.18+828SNAPSHOT20150512102356trusty-0ubuntu1`) I'm not actually building it myself. (As this is not on the most  modern laptop, I don't know if I *could* build it myself within a reasonable time.)

**Comment by gavofyork** [comment]
should be fixed in latest.
