### ISSUE TITLE
eth stuck during sync, saying "block hash bad! ... No more peers"

### ISSUE THREAD

**Issue by carver** [ethereum/cpp-ethereum#1877]
I have killed my local blockchain and restarted a couple times, but never seem to get past block 239999.

The console repeats logs like this
```
  ✘  12:09:30|p2p|a979fb57…|Geth/v0.9.18/linux/go1.4.2  block hash bad! #dcf1e20e… . Bailing...
⧎ ◌  12:09:30|p2p|a979fb57…|Geth/v0.9.18/linux/go1.4.2  Transition! Nothing from Hashes , syncing 
⧎ ℹ  12:09:30|p2p|a979fb57…|Geth/v0.9.18/linux/go1.4.2  Finishing hashes fetch...
⧎ ℹ  12:09:30|p2p|a979fb57…|Geth/v0.9.18/linux/go1.4.2  No more peers to sync with.
Press Enter
> block
Current block: 239999
```

I started eth with: `eth --db-path "/home/jcarver/.cpp-ethereum" --interactive --mining off --address "0x1cdc8315bdb1362de8b7b2fa9ee75dc873037179" --opencl`

**Comment by iurimatias** [comment]
getting the same thing, but on block #137501

**Comment by carver** [comment]
Ok, good to know it's a cross-platform issue: I'm on Ubuntu 14.04

Also, I'm using:
```
$ eth -V
eth version 0.9.17
eth network protocol version: 60
Client database version: 12041
Build: Linux/g++/int/Release
```

**Comment by gavofyork** [comment]
known bug in all versions < 0.9.19 - please update to latest develop, kill ~/.ethereum/status and retry.

**Comment by carver** [comment]
Works for me, thanks!
