### ISSUE TITLE
State is previewed as though I mined block when when "Preview Pending Transactions" is unchecked.

### ISSUE THREAD

**Issue by kaeptnjoda** [ethereum/cpp-ethereum#1885]
The amount of ether changes when I checks in tick boxes change without any transaction taking place. 

This behavior appears at least during the blockchain downloading/synchronization process. Will update issue in case the behavior persists once blockchain is up to date.

**Comment by kaeptnjoda** [comment]
![screenshot from 2015-05-13 11 20 26](https://cloud.githubusercontent.com/assets/8157688/7607546/9ec51fbc-f962-11e4-9468-a496cea2b7a4.png)
![screenshot from 2015-05-13 11 19 27](https://cloud.githubusercontent.com/assets/8157688/7607549/a2eb994a-f962-11e4-85a6-ff1b840557d9.png)

**Comment by kaeptnjoda** [comment]
Eventually as expected the "strange behavior" doesn't persist once that blockchain is synchronized

**Comment by kaeptnjoda** [comment]
I've sent 1000 ether from one address to the other. Balance of account changes during blockchain synchronization:
![screenshot from 2015-05-13 14 57 38](https://cloud.githubusercontent.com/assets/8157688/7610875/807cb600-f980-11e4-9d98-d57a283da529.png)
![screenshot from 2015-05-13 14 57 07](https://cloud.githubusercontent.com/assets/8157688/7610879/831e1570-f980-11e4-9293-6fe69ad89e56.png)

**Comment by gavofyork** [comment]
the coinbase address changes dynamically; at present everything is shown at the end of the presently mined block, which it assumes you have mined.

**Comment by kaeptnjoda** [comment]
But why the additional 1.7 ether? what's the reward?

**Comment by kaeptnjoda** [comment]
I see, it contains the transaction fees as well...

**Comment by gavofyork** [comment]
i think this is fixed in recent develop.
