### ISSUE TITLE
Difficulty with coinbase address (cpp-ethereum Ubuntu 14.04, Alethzero Win32)

### ISSUE THREAD

**Issue by NginUS** [ethereum/cpp-ethereum#1895]
I have cpp-ethereum cli client running on a linux box, & it appears to be mining just fine [1].
When I start the client, I had to disable uPnP & define the external IP address before it would run right. I'd like to define my coinbase address so that I can keep the proceeds of its mining, but I don't see where to generate one.
I read somewhere online that the Alethzero GUI client can generate addresses, so I tried running that on the linux box, but I get a QT5 crash error [2].
So I installed the Alethzero client on my Windows box, & even with forwarding port 30303 to that box, it doesn't appear to get up & running. [3]
On the Windows Alethzero, I see where the addresses go when I create a new one, so I know I have an address, but I can't view or copy the whole thing for use in the linux box's startup arguments for the cpp-ethereum cli.
I posted to the Ethereum forums, but get no reply. [4]
Thus, I'm here for assistance. Thanks in advance.
[1] http://imgur.com/sDTzLrj
[2] http://imgur.com/tsrrbxU
[3] http://imgur.com/LSiZklz
[4] http://is.gd/BYtcmF

**Comment by NginUS** [comment]
Found the commands here:

http://skilledtests.com/wiki/Ethereum

**Comment by NginUS** [comment]
But I still get:

Invalid argument: address

when I do ./eth address


How do I get the address?

**Comment by chriseth** [comment]
Sorry for the late reply. You can generate an address in the following way:
Launch eth in interactive mode: `eth -i`
Then you can use `newaccount` to create a new account. Use `accounts` to list the accounts and `eth -a "your_address_here"` to set the coinbase address.
