### ISSUE TITLE
Core dump from: eth --opencl

### ISSUE THREAD

**Issue by carver** [ethereum/cpp-ethereum#1897]
```
$ eth --opencl
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)
```

It works fine without --opencl.

Other programs also can't use opencl on my system, similar to this [StackOverflow question](http://askubuntu.com/questions/576338/why-opencl-is-not-default-14-04-nvidia-331?lq=1).  Unfortunately, when I follow the [instructions to fix opencl](http://askubuntu.com/a/543420), apt asks me to downgrade eth back to 0.8.  Apparently, the package that will make openCL work is incompatible with eth.

**Comment by debris** [comment]
We should definitely look more carefully into this. Similar issue: #1915

**Comment by stephantual** [comment]
Yes that's definitely the look of a machine that doesn't have fglrx installed.

**Comment by anthony-cros** [comment]
Yes, I had the same issue before installing fglrx

**Comment by carver** [comment]
Looks like I needed an `apt-get install nvidia-modprobe clinfo`. I love that 10x boost to hashing.  Thanks!
