### ISSUE TITLE
0 H/s with eth -G -M

### ISSUE THREAD

**Issue by arhuaco** [ethereum/cpp-ethereum#1913]
This was after a reboot. The benchmark did run yesterday with non-zero results.

    $ git/cpp-ethereum/build/eth/eth -G -M
    Benchmarking on platform: { "platform": "NVIDIA CUDA", "device": "GeForce GTX 560M", "version": "OpenCL 1.1 CUDA" }
    Preparing DAG...
      ℹ  16:08:53|eth  Loading from libethash...
      ℹ  16:08:53|eth  Done loading.
     Warming up...
      ℹ  16:08:53|gpuminer0  workLoop 0 #00000000… #00000000…
    Using platform: NVIDIA CUDA
    Using device: GeForce GTX 560M(OpenCL 1.1 CUDA)
    Trial 1... 0
    Trial 2... 0
    Trial 3... 0
    Trial 4... 0
    Trial 5... 0
    min/mean/max: 0/0/0 H/s
    inner mean: 0 H/s
    Phoning home to find world ranking...
    Error phoning home. ET is sad.

**Comment by arhuaco** [comment]
This only happens the first time. The second time I got mean 1835008 H/s. Closing.

**Comment by SjonHortensius** [comment]
This happened the first time for me too. I'd consider this a bug that requires fixing
