### ISSUE TITLE
 'cl::Error' buntu 14.04

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#1915]
using 0.9.21+847SNAPSHOT20150514192857trusty-0ubuntu1 PPA
commit db7b5484f2edc067d0ddb2f9be8413ddc612bf30

```
gozer@gozer001:~$ eth -M --opencl
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)
gozer@gozer001:~$ eth -M --opencl --opencl-device 0
terminate called after throwing an instance of 'cl::Error'
  what():  clGetPlatformIDs
Aborted (core dumped)
```

**Comment by stephantual** [comment]
This could be a bug in buntu - had just reinstalled from scratch, fglrx isn't accessible in 14.04.02 unless 'proposed' is checked in 'updates'. 

Enabling trusty-proposed solves this.

**Comment by debris** [comment]
:+1:
