### ISSUE TITLE
clicking Mine produces core dump

### ISSUE THREAD

**Issue by youlian** [ethereum/cpp-ethereum#1917]
on ubuntu
cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUNDLE=full -DFATDB=1 -DSOLIDITY=1 -DEVMJIT=1 -DJSCONSOLE=1
> Bus error (core dumped)

**Comment by chriseth** [comment]
Can you provide a bit more information please?

**Comment by chriseth** [comment]
Please reopen if this problem is still present.
