### ISSUE TITLE
byteswap.h is not available on FreeBSD and related platforms

### ISSUE THREAD

**Issue by tymat** [ethereum/cpp-ethereum#1918]
Needs to be implemented using bswap32 and bswap64

**Comment by tymat** [comment]
https://github.com/ethereum/cpp-ethereum/pull/1919

**Comment by debris** [comment]
Can it be closed @LefterisJP ?

**Comment by LefterisJP** [comment]
Hmmm actually @tymat did not open a PR on the ethash repo itself. I can copy paste the code myself if he does not respond soon.
