### ISSUE TITLE
ethminer v.0.9.21 does not detect GPU

### ISSUE THREAD

**Issue by 0xABCD** [ethereum/cpp-ethereum#1933]
This issue is resolved - totally missed --with-gpu-mining (cmake -DETHASHCL=1)
----------------------------------------
When metrics are run both -C and -G return same results

Version:

MP02s-Mac-Pro:~ mp02$ ethminer -V
eth version 0.9.21
eth network protocol version: 60
Client database version: 12041
Build: Darwin/clang/int/Release

With option -G

MP02s-Mac-Pro:~ mp02$ ethminer -G -M
Benchmarking on platform: 8-thread CPU
Preparing DAG...
  ℹ  20:23:49|main  Loading from libethash...
  ℹ  20:23:49|main  Done loading.
Warming up...
Trial 1... 615333
Trial 2... 608058
Trial 3... 598734
Trial 4... 611462
Trial 5... 605657
min/mean/max: 598734/607848/615333 H/s
inner mean: 606084 H/s

With option -C

MP02s-Mac-Pro:~ mp02$ ethminer -C -M
Benchmarking on platform: 8-thread CPU
Preparing DAG...
  ℹ  20:27:56|main  Loading from libethash...
  ℹ  20:27:56|main  Done loading.
Warming up...
Trial 1... 602529
Trial 2... 601000
Trial 3... 597203
Trial 4... 608927
Trial 5... 606988
min/mean/max: 597203/603329/608927 H/s
inner mean: 602376 H/s

Hardware data:

  Model Name:	Mac Pro
  Model Identifier:	MacPro6,1
  Processor Name:	Quad-Core Intel Xeon E5
  Processor Speed:	3,7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	10 MB
  Memory:	12 GB
  Boot ROM Version:	MP61.0116.B11
  SMC Version (system):	2.20f18
  Illumination Version:	1.4a6

Card 1:

AMD FirePro D300:

  Chipset Model:	AMD FirePro D300
  Type:	GPU
  Bus:	PCIe
  Slot:	Slot-1
  PCIe Lane Width:	x16
  VRAM (Total):	2048 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x6810
  Revision ID:	0x0000
  ROM Revision:	113-C4012F-687
  gMux Version:	4.0.11 [3.2.8]
  EFI Driver Version:	01.00.687

Card 2:

AMD FirePro D300:

  Chipset Model:	AMD FirePro D300
  Type:	GPU
  Bus:	PCIe
  Slot:	Slot-2
  PCIe Lane Width:	x16
  VRAM (Total):	2048 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x6810
  Revision ID:	0x0000
  ROM Revision:	113-C4012F-687
  gMux Version:	4.0.11 [3.2.8]
  EFI Driver Version:	01.00.687

With some assistance I can help to debug this issue.

**Comment by veox** [comment]
You can close the issue if it's resolved.
