### ISSUE TITLE
Message "Error GPU mining. GPU memory fragmentation?" followed by "Segmentation fault: 11" on Mac Pro with two graphics cards

### ISSUE THREAD

**Issue by 0xABCD** [ethereum/cpp-ethereum#1936]
Version 0.9.21, was built with def --with-gpu-mining

ethminer works fine when run with option -C -M, but fails when run with option -G -M.

The following is output with three different --opencl-device values.

--opencl-device 0

mp02$ ethminer -G -M --opencl-device 0
Benchmarking on platform: { "platform": "Apple", "device": "Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz", "version": "OpenCL 1.2 " }
Preparing DAG...
  ℹ  23:18:05|main  Loading from libethash...
  ℹ  23:18:05|main  Done loading.
Warming up...
  ℹ  23:18:05|gpuminer0  workLoop 0 #00000000… #00000000…
Using platform: Apple
Using device: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz(OpenCL 1.2 )
  ✘  23:18:05|gpuminer0  Error GPU mining. GPU memory fragmentation?
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0
min/mean/max: 0/0/0 H/s
inner mean: 0 H/s

--opencl-device 1

mp02$ ethminer -G -M --opencl-device 1
Benchmarking on platform: { "platform": "Apple", "device": "AMD Radeon HD - FirePro D300 Compute Engine", "version": "OpenCL 1.2 " }
Preparing DAG...
  ℹ  23:18:31|main  Loading from libethash...
  ℹ  23:18:31|main  Done loading.
Warming up...
  ℹ  23:18:31|gpuminer0  workLoop 0 #00000000… #00000000…
Using platform: Apple
Using device: AMD Radeon HD - FirePro D300 Compute Engine(OpenCL 1.2 )
Segmentation fault: 11

--opencl-device 2

mp02$ ethminer -G -M --opencl-device 2
Benchmarking on platform: { "platform": "Apple", "device": "AMD Radeon HD - FirePro D300 Compute Engine", "version": "OpenCL 1.2 " }
Preparing DAG...
  ℹ  23:18:42|main  Loading from libethash...
  ℹ  23:18:42|main  Done loading.
Warming up...
  ℹ  23:18:42|gpuminer0  workLoop 0 #00000000… #00000000…
Using platform: Apple
Using device: AMD Radeon HD - FirePro D300 Compute Engine(OpenCL 1.2 )
Segmentation fault: 11

Technical specs of the system:

  Model Name:	Mac Pro
  Model Identifier:	MacPro6,1
  Processor Name:	Quad-Core Intel Xeon E5
  Processor Speed:	3,7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	10 MB
  Memory:	12 GB
  Boot ROM Version:	MP61.0116.B11
  SMC Version (system):	2.20f18
  Illumination Version:	1.4a6

Card 1:

  Chipset Model:	AMD FirePro D300
  Type:	GPU
  Bus:	PCIe
  Slot:	Slot-1
  PCIe Lane Width:	x16
  VRAM (Total):	2048 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x6810
  Revision ID:	0x0000
  ROM Revision:	113-C4012F-687
  gMux Version:	4.0.11 [3.2.8]
  EFI Driver Version:	01.00.687

Card 2:

  Chipset Model:	AMD FirePro D300
  Type:	GPU
  Bus:	PCIe
  Slot:	Slot-2
  PCIe Lane Width:	x16
  VRAM (Total):	2048 MB
  Vendor:	ATI (0x1002)
  Device ID:	0x6810
  Revision ID:	0x0000
  ROM Revision:	113-C4012F-687
  gMux Version:	4.0.11 [3.2.8]
  EFI Driver Version:	01.00.687

The same happened on the office MacPro which has 2x AMD FirePro D500 with 3GB each.

My c++ or OpenCL skills are limited, but I can help with core dumps or debugging with gdb if that helps.

**Comment by larspensjo** [comment]
The error message ```GPU memory fragmentation?``` seems to be when you try to do OpenCL mining on the CPU. But that doesn't explain your seg fault.

**Comment by gillhofer** [comment]
I have a similar issue.

```
[michi@user eth]$ ./eth -M -G --opencl-device 0
Benchmarking on platform: { "platform": "NVIDIA CUDA", "device": "GeForce GTX 560", "version": "OpenCL 1.1 CUDA" }
Preparing DAG...
  ℹ  17:47:40|eth  Loading from libethash...
  ℹ  17:47:40|eth  Done loading.
Warming up...
  ℹ  17:47:40|gpuminer0  workLoop 0 #00000000… #00000000…
Using platform: NVIDIA CUDA
Using device: GeForce GTX 560(OpenCL 1.1 CUDA)
  ✘  17:47:41|gpuminer0  Error GPU mining. GPU memory fragmentation?
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0
min/mean/max: 0/0/0 H/s
inner mean: 0 H/s
Phoning home to find world ranking...
Ranked: 144 of all benchmarks.
```

**Comment by Ulysseus** [comment]
Getting the exact same behavior same system Mac pro etc, results are exactly the same

**Comment by subtly** [comment]
@0xABCD I'll work on a patch for this. OSX doesn't like the const &c_zero being passed into enqueueWriteBuffer and haven't found a workaround for this yet.

@gillhofer Does the GPU card have 2GB of memory?

**Comment by gillhofer** [comment]
Actually, i completly failed finding out how much video memory my gtx560 has onboard.
a `lshw -C video` results in this.

```
*-display               
       description: VGA compatible controller
       product: GF114 [GeForce GTX 560]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:37 memory:f4000000-f5ffffff memory:e0000000-e7ffffff memory:e8000000-ebffffff ioport:e000(size=128) memory:f6000000-f607ffff
```

and a `lspci -v -s 01:00.0` brings this up. 


```
01:00.0 VGA compatible controller: NVIDIA Corporation GF114 [GeForce GTX 560] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: Micro-Star International Co., Ltd. [MSI] Device 2326
	Flags: bus master, fast devsel, latency 0, IRQ 37
	Memory at f4000000 (32-bit, non-prefetchable) [size=32M]
	Memory at e0000000 (64-bit, prefetchable) [size=128M]
	Memory at e8000000 (64-bit, prefetchable) [size=64M]
	I/O ports at e000 [size=128]
	[virtual] Expansion ROM at f6000000 [disabled] [size=512K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Endpoint, MSI 00
	Capabilities: [b4] Vendor Specific Information: Len=14 <?>
	Capabilities: [100] Virtual Channel
	Capabilities: [128] Power Budgeting <?>
	Capabilities: [600] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
	Kernel driver in use: nvidia
	Kernel modules: nouveau, nvidia
```

**Comment by LefterisJP** [comment]
@gillhofer Is [this](http://graphics-cards.specout.com/l/84/Nvidia-nVidia-GeForce-GTX-560-Ti) your GPU? If so then it's quite probable you don't have enough GPU memory.

I can check a lot of info on my NVIDIA GPU by calling `nvidia-settings`

**Comment by gillhofer** [comment]
Ahh, thx. Here we go. My card has 1GB memory.

**Comment by lexansoft** [comment]
Same here with just one card:

nduserca312:cpp-ethereum alexn$ eth -M -G --opencl-device 2
Benchmarking on platform: { "platform": "Apple", "device": "GeForce GT 750M", "version": "OpenCL 1.2 " }
Preparing DAG...
  ℹ  15:04:45|main  Loading from libethash...
  ℹ  15:04:45|main  Done loading.
Warming up...
  ℹ  15:04:45|gpuminer0  workLoop 0 #00000000… #00000000…
Using platform: Apple
Using device: GeForce GT 750M(OpenCL 1.2 )
Trial 1... Segmentation fault: 11

**Comment by Ulysseus** [comment]
Both cards have 2gb of VRAM

**Comment by Ulysseus** [comment]
It's a late 2014 MacPro

**Comment by rachimo34** [comment]
Same here I have a GPU NVIDIA GeForce GTX 775M 2048 MB but refuse to work :(
risproduction$ eth -m on -G -M --opencl-platform 1 --opencl-device 1 -i -v 8
Benchmarking on platform: { "platform": "Apple", "device": "GeForce GTX 775M", "version": "OpenCL 1.2 " }
Preparing DAG...
  ℹ  17:10:50|main  Loading from libethash...
  ℹ  17:10:50|main  Done loading.
  ℹ  17:1Warming up...
0:50|gpuminer0  workLoop 0 #00000000… #00000000…
  ℹ  17:10:50|gpuminer0  Initialising miner...
Using platform: Apple
Using device: GeForce GTX 775M(OpenCL 1.2 )
Segmentation fault: 11

**Comment by reignbeau** [comment]
Segmentation Fault with Ubuntu.
NVidia GTX 970.


![screenshot from 2015-05-22 01_12_15](https://cloud.githubusercontent.com/assets/12384173/7781541/9527db54-00a4-11e5-8da2-f26cea332775.png)

If I run a CPU mine first and then swap to GPU mine while in AlethZero, I get a different error message.

![screenshot from 2015-05-22 01_22_40](https://cloud.githubusercontent.com/assets/12384173/7781547/af3720fe-00a4-11e5-9c15-77c60e6746df.png)

**Comment by rachimo34** [comment]
ok I have finally solve this seg problem
My ethminer wasn't install correctly
cd cpp-ethereum
cmake -DETHASHCL=1 -DGUI=0
make -j4
make install

However my hashrate looks very low 2.5MH/s against 0.8MH/s with my 8 core CPU

**Comment by debris** [comment]
> However my hashrate looks very low 2.5MH/s against 0.8MH/s with my 8 core CPU

This looks fine. Mining on macbooks gpu's won't be much faster than on cpu.

**Comment by debris** [comment]
Can we close this?

**Comment by rachimo34** [comment]
Hey debris It's fine for me
