### ISSUE TITLE
fatal error: json/json.h: No such file or directory

### ISSUE THREAD

**Issue by larspensjo** [ethereum/cpp-ethereum#1939]
This happens on Linux Mint when compiling libdevcore/StructuredLogger.cpp:26.

If I make a symbolic link from /usr/include/jsoncpp/json to /usr/include/json, then I can compile.

**Comment by debris** [comment]
That's weird. Similar issue was reported few months ago, but it was fixed. Can you give us more details? What cmake version are you using? And what target was being compiled when issue occurs?

**Comment by larspensjo** [comment]
I checked with Ubuntu 14 (don't know if it is .4), and the json include fils are located at /usr/include/jsoncpp. Same way for Mint 17.1. So I don't know how /usr/include/json

**Comment by larspensjo** [comment]
I compiled old source code, and it seems to indeed work with newer source.
