### ISSUE TITLE
After DAG transition, mining error

### ISSUE THREAD

**Issue by carver** [ethereum/cpp-ethereum#1945]
After the 360k block hit, my DAG started generating.  In the meantime, the miner was reporting `Error GPU mining. GPU memory fragmentation?`.  After the DAG finished generating, the error never went away (waited roughly 2 minutes after "Full DAG loaded").  Closing ethminer and restarting resolved the issue.

```
DAG  21:36:42|gpuminer0  Generating DAG file. Progress: 100 %
  ℹ  21:36:42|gpuminer0  Done loading.
  ℹ  21:36:42|gpuminer0  Full DAG loaded
  ℹ  21:36:42|ethminer  Mining on PoWhash #9c8aff42… : 0 H/s = 0 hashes / 69.602 s
  ℹ  21:36:43|ethminer  Mining on PoWhash #9c8aff42… : 0 H/s = 0 hashes / 70.102 s
  ℹ  21:36:43|ethminer  Mining on PoWhash #9c8aff42… : 0 H/s = 0 hashes / 70.603 s
  ℹ  21:36:44|ethminer  Mining on PoWhash #9c8aff42… : 0 H/s = 0 hashes / 71.104 s
  ℹ  21:36:44|ethminer  Mining on PoWhash #9c8aff42… : 0 H/s = 0 hashes / 71.605 s
  ℹ  21:36:44|ethminer  Got work package:
  ℹ  21:36:44|ethminer    Header-hash: f167e81581a8f0073b6c939d830ee689c42882837507427868c516762a42f906
  ℹ  21:36:44|ethminer    Seedhash: 4db8c3d89b7de6ddb733a736d664ebda3b6c5c5131f406df463e8f83d7805283
  ℹ  21:36:44|ethminer    Target: 00000000f5e19493d93083ffb152557c858ff5b826ed09f325d552892723d548
 ⚡   21:36:48|gpuminer0  Worker stopping 69.2801 s
  ℹ  21:36:48|gpuminer0  workLoop 1 #4db8c3d8… #4db8c3d8…
  ✘  21:36:48|gpuminer0  Error GPU mining. GPU memory fragmentation?
```

**Comment by larspensjo** [comment]
What happens when you do a benchmark test? E.g.
```eth -M -G -d /lars/.cpp-ethereum --opencl-device 0``` or ```ethminer -M -G --opencl-device 0```?

In my case, I get successful GPU mining for both, but when I start the real mining, I get the same error as you.

**Comment by carver** [comment]
`Error GPU mining. GPU memory fragmentation?` seems to be a pretty generic error.  This particular issue thread is about being able to mine successfully, but having that break down at the new DAG transition.  

I've had other issues like yours, which generate that same error message at the beginning, but usually ethminer starts to work after running `clinfo` to be sure opencl is working and restarting a few times.

**Comment by larspensjo** [comment]
The ```Error GPU mining. GPU memory fragmentation?``` is, as you say, a generic error as a result from a try-catch. So we don't know exactly why. When I debugged it, I found that there was a failure to allocate a large enough GPU buffer for mining. When a new DAG was generated, maybe it had larger size requirements, leading to allocation problems in your case. If you free the previous buffer (about 1,6 GB for the DAG), and allocate another one that is a little bigger, it will almost certainly fail, because of memory fragmentation on the GPU. Restarting the miner will free all resources, which could explain why that worked.

**Comment by carver** [comment]
I don't know much about GPU memory management.  Would it be possible to have ethminer delegate memory allocation to a subprocess, which exits out and starts again when a new DAG is needed?  Maybe that would really free the memory for a contiguous block of RAM.

**Comment by larspensjo** [comment]
Could be, I don't know what solution is best. To me, your error report seems to be a real error case, and I'll leave it to the developers to manage.

**Comment by larspensjo** [comment]
I think this happened again now? My mining stopped "tonight", and didn't get going again by itself. I don't have the log when it happened :-(. It was somewhere between block 389688 and 391192 (http://etherapps.info/mined/0x8686578c4f7c75246f548299d6ffdac3b67b5cd1). When I restarted ethminer, it had to recompute the DAG first.

Looks like it was at the 390k block limit?

**Comment by carver** [comment]
Yeah, that breakdown was apparent across the network at the 390k block.  Until this is resolved, the workaround is to precompute the next DAG and restart ethminer every 30k blocks.

**Comment by subtly** [comment]
It takes forever to test this

**Comment by subtly** [comment]
Oops. Fat fingered on phone.

This is a know issue and we're working on a fix. There's a bit of trickery getting cross platform support and it takes awhile to setup a gpu and dag across 3 OSes so the feedback here is helpful.

Helpful things to know, if you can post them:
CPU or GPU, GPU type, logs (via gist).

Should have a few updates in develop before the next epoch.

Note: on MacOS and windows the dag path recently changed. So if you startedining just before the epoch it's possible that it would've regenerated prev dag and then generated new dag. It's not yet dart enough to know if/when it's genearing a dag and the blockchain clears a new epoch -- it'll genrare both.

**Comment by carver** [comment]
I'm GPU mining on Nvidia GRID K520 with driver v349, in Ubuntu 14.04.  All my logs are, gone except for the ones in the original post.

**Comment by gavofyork** [comment]
possibly fixed in the latest. please retry.

**Comment by carver** [comment]
I didn't see the same issue in 0.9.23 at the 480k block
