### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by t128** [ethereum/cpp-ethereum#1947]
Hi,

when i start eth/AZ/ethminer it just hangs without any output. Im at the current develop branch (93752ed1cf83feef36f035661efa10153d20b99e). Looks like the problem was introduced in 19f3a5802194f8a891ef1aa44f03a7b1573881ef. I reverted the cl_miner changes, looks better now, im getting output.

**Comment by LefterisJP** [comment]
You can adjust verbosity with ``` -v,--verbosity <0 - 9>  Set the log verbosity from 0 to 9 (default: 8).```.

As for the mining issue it's already known and [reported](https://github.com/ethereum/cpp-ethereum/issues/1942).

**Comment by t128** [comment]
I think this is an other issue. i get ***no*** output on the console after starting one of the cpp-ethereum apps, it's not even asking for the password.

**Comment by LefterisJP** [comment]
Please provide more information. Operating system? What exactly are you trying to execute and you don't see any output? What's the exact command you type?

**Comment by larspensjo** [comment]
I think this is the same issue as #1935

**Comment by larspensjo** [comment]
Something must be seriously wrong. I have tested this on both Mint and Ubuntu, and the SW downloaded from ppa fails to output anything whatsoever, and haven't done so for several days. Using gdb, I get this stack trace (which is the same on Ubuntu and Mint). This happens when running "eth -h"! That is, I don't even get a help message.
```
#0  0x00007ffff68934d4 in __GI___pthread_mutex_lock (mutex=0x7ffff7ffd968 <_rtld_global+2312>)
    at ../nptl/pthread_mutex_lock.c:114
#1  0x00007ffff7ddb150 in tls_get_addr_tail (ti=0x7ffff68716f8, dtv=0x7fffecb32090, the_map=0x7ffff7e17000)
    at dl-tls.c:722
#2  0x00007ffff65e2aec in __cxa_get_globals () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff65e2a19 in std::uncaught_exception() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff45c9ff0 in CryptoPP::AlgorithmParametersBase::~AlgorithmParametersBase() ()
   from /usr/lib/libcryptopp.so
#5  0x00007ffff4683402 in CryptoPP::AlgorithmParametersTemplate<int>::~AlgorithmParametersTemplate() ()
   from /usr/lib/libcryptopp.so
#6  0x00007ffff4683432 in CryptoPP::AlgorithmParametersTemplate<int>::~AlgorithmParametersTemplate() ()
   from /usr/lib/libcryptopp.so
#7  0x00007ffff45bf7ab in CryptoPP::member_ptr<CryptoPP::AlgorithmParametersBase>::~member_ptr() ()
   from /usr/lib/libcryptopp.so
#8  0x00007ffff45bf86b in CryptoPP::AlgorithmParameters::~AlgorithmParameters() ()
   from /usr/lib/libcryptopp.so
#9  0x00007ffff45d66d0 in CryptoPP::BaseN_Decoder::BaseN_Decoder(int const*, int, CryptoPP::BufferedTransformation*) () from /usr/lib/libcryptopp.so
#10 0x00007ffff45d674a in CryptoPP::HexDecoder::HexDecoder(CryptoPP::BufferedTransformation*) ()
   from /usr/lib/libcryptopp.so
#11 0x00007ffff464b83e in CryptoPP::EcRecommendedParameters<CryptoPP::ECP>::NewEC() const ()
   from /usr/lib/libcryptopp.so
#12 0x00007ffff465e30b in CryptoPP::DL_GroupParameters_EC<CryptoPP::ECP>::Initialize(CryptoPP::OID const&) ()
   from /usr/lib/libcryptopp.so
#13 0x00007ffff465db2c in CryptoPP::DL_GroupParameters_EC<CryptoPP::ECP>::DL_GroupParameters_EC(CryptoPP::OID const&) () from /usr/lib/libcryptopp.so
#14 0x00007ffff71f84e9 in dev::crypto::Secp256k1::Secp256k1() () from /usr/lib/libdevcrypto.so
#15 0x00007ffff71c90a9 in ?? () from /usr/lib/libdevcrypto.so
#16 0x00007ffff7dea13a in call_init (l=<optimized out>, argc=argc@entry=2, argv=argv@entry=0x7fffffffde68, 
    env=env@entry=0x7fffffffde80) at dl-init.c:78
#17 0x00007ffff7dea223 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, 
    l=<optimized out>) at dl-init.c:36
#18 _dl_init (main_map=0x7ffff7ffe1c8, argc=2, argv=0x7fffffffde68, env=0x7fffffffde80) at dl-init.c:126
#19 0x00007ffff7ddb30a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#20 0x0000000000000002 in ?? ()
#21 0x00007fffffffe221 in ?? ()
---Type <return> to continue, or q <return> to quit---
#22 0x00007fffffffe22e in ?? ()
#23 0x0000000000000000 in ?? ()
```
There is a static symbol of type Secp256k1 that hangs during initialization. This happens before main() is called, which explains why "eth -h" doesn't produce any output. I don't know why it gets stuck though, but it sure looks like some kind of mutex.

**Comment by larspensjo** [comment]
Success!

When I update the fglrx version, I no longer get stuck as shown above. A little unexpected, there is nothing in the stack trace that would indicate a dependency of the graphic drivers.
