### ISSUE TITLE
ethminer 100% CPU

### ISSUE THREAD

**Issue by poiuty** [ethereum/cpp-ethereum#1949]
Try GPU mining.
When start => ethminer use 100% cpu.
https://poiuty.com/img/28f3ea0a58c67ddcb55e225cb542.png

fglrx-14.501.1003
```
# aticonfig --adapter=all --odgt
Adapter 0 - Supported device 67B1
            Sensor 0: Temperature - 29.00 C
```

**Comment by poiuty** [comment]
If try get version
./ethminer -V => 100% cpu use.

**Comment by poiuty** [comment]
Find same problem in this post
https://forum.ethereum.org/discussion/comment/8603/#Comment_8603

**Comment by carver** [comment]
I'm also seeing 100% of one CPU core being used during hashing, when mining on Nvidia GPUs.

htop says that 1/3 to 1/2 of the usage is in kernel space.  I tried changing the --farm-recheck arg anywhere from 100 to 2000, without effect.  What other information/logging/tests would be useful?

CPU: Intel Xeon E5-2670 2.6 GHz (8 core)

**Comment by LefterisJP** [comment]
Does this still occur for you guys? Please have a look.

**Comment by poiuty** [comment]
No. It`s work now.

**Comment by Polymetric** [comment]
Hate to reopen a bug, but this is occuring on my ethminer. Mining at a local geth node, GPU only on an nvidia gtx970.

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/webthree-umbrella/issues/314, @Polymetric.
This is an inactive repo now.
