### ISSUE TITLE
When a state instructs mix to deploy a contract in the new way, it does not appear in the contracts object.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1967]
There is all sorts of strange bugginess involving contract constructors, especially if it's an old project. The worst is that in deploying a contract in the new way (where the entry on the window says "Deploy Foo") it does not actually appear in the contracts object, and it is therefore inaccessible.

**Comment by Smithgift** [comment]
I found this in the terminal after once such failure, and it may be to blame:
```
  ✘  01:20:23 PM|Thread (pooled)  /build/buildd/cpp-ethereum-0.9.23+862SNAPSHOT20150518153921trusty/libdevcore/CommonData.cpp(78): Throw in function int dev::fromHex(char)
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadHexCharacter>
std::exception::what: std::exception
[dev::tag_invalidSymbol*] = t

  ✘  01:20:23 PM|Thread (pooled)  /build/buildd/cpp-ethereum-0.9.23+862SNAPSHOT20150518153921trusty/libdevcore/CommonData.cpp(78): Throw in function int dev::fromHex(char)
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadHexCharacter>
std::exception::what: std::exception
[dev::tag_invalidSymbol*] = h

  ✘  01:20:23 PM|Thread (pooled)  /build/buildd/cpp-ethereum-0.9.23+862SNAPSHOT20150518153921trusty/libdevcore/CommonData.cpp(78): Throw in function int dev::fromHex(char)
Dynamic exception type: boost::exception_detail::clone_impl<dev::BadHexCharacter>
std::exception::what: std::exception
[dev::tag_invalidSymbol*] = n
```
NINJA EDIT: My contract is named E*t**h*Fe*n*ce, which may explain this message. Another contract I made to test called aceface in the bizarre case hexadecimal was responsible still did not deploy successfully.

**Comment by Smithgift** [comment]
FURTHER UPDATE: I went into the local .mix and found that "isFunctionCall": in the offending contract deployment transaction was set to false. Setting it to true made it work again.

**Comment by yann300** [comment]
isFunctionCall should have been set to true by default. Could you send me your project please?

**Comment by Smithgift** [comment]
Actually, it seems to be working fine, now. Closing.
