### ISSUE TITLE
60 minutes to import block chain after rebuild resets block to 0

### ISSUE THREAD

**Issue by levijiles** [ethereum/cpp-ethereum#1969]
In wake of the recent issues with the APT version, I have had to rebuild from source multiple times.  (https://github.com/ethereum/cpp-ethereum/issues/1935)

Running a newly built from source ETH or Alethzero client resets my blockchain to zero. (Even though it will read the previous private keys...)

Our options seem limited to re-downloading or importing.  

I am on a Quad Core 4.2 ghz AMD processor and still get at most 100blocks per second during the import.

360,000 blocks / 100 blocks per second = 36,000 seconds  / 60 seconds per minute

=  60 minutes (MINIMUM) to IMPORT (eth -i blockchainbackup)  the blockchain.

(This is for the "Imported and best XXXXX (XXXX)" / "Commited: stateRoot XXXX"  part of the block sync not the initial queue which is fast)

Edit: This post is to make development aware of the blockchain-deleting-initialization-process going on somewhere, and the tediousness of trying multiple builds when each one requires a blockchain resync at over 1h each. The rate of import slows a lot near the end. Perhaps to even 10 blocks per second in the 350k+ range. Actual time on this last syn was almost 3 hours.

**Comment by gavofyork** [comment]
any database clears are done as a necessity since we may have undergone a protocol change. however, it should not have required a manual redownload; rather it should have been auto re-imported. i may have already fixed this, so please reopen if it happens again.

the import times will reduce once we go into optimisation phase.
