### ISSUE TITLE
Send Ether Bug

### ISSUE THREAD

**Issue by joeykrug** [ethereum/cpp-ethereum#1971]
On Alethzero if you try to send to an address encoded like `0xe956d63ca15052ff707f68537e58b34c749999ee` it will automatically send to `0x0000000000000000000000000000000000000000`

Not sure if this is a bug or intended behavior, but if intended this is a vote towards that it probably shouldn't be (esp. since this is accepted behavior in geth).

**Comment by levijiles** [comment]
Also if you try to send to NameReg or an unknown address, it goes to 0x0000...

**Comment by gavofyork** [comment]
jup - don't prefix with `0x`?

**Comment by joeykrug** [comment]
Not prefixing with 0x fixes it, but I can see this being a major issue down the road for average users.  E.g. my friend on Alethzero asks for my address, I call eth.getCoinbase and send them `0x...` they then paste into Alethzero to send me some money and the money they send me just essentially vanishes to the 0x000000 address

**Comment by arkpar** [comment]
fixed in develop
