### ISSUE TITLE
block 137555 causing Gas overflow in VM.cpp

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/cpp-ethereum#1977]
#### Observed problem

When importing the downloaded blockchain I was constantly stuck at block 137555. It could never get out of there no matter how many times I deleted the entire blockchain or try different peers.

 After some debugging along with @arkpar we found out there is an overflow in VM.cpp in the `boost::u256` number. The overflow happens around [VM.cpp:625](https://github.com/ethereum/cpp-ethereum/blob/develop/libevm/VM.cpp#L625)

as you can see from the gdb output

```
EVM  02:47:17 PM|eth   < 0 : @79652f18… : #39627 : 3140 : SUB : 17 : -3 : 0x32 >
EVM  02:47:17 PM|eth  
    STACK
0000000000000000000000000000000000000000000000000000000045d96cd7
000000000000000000000000000000000000000000000000000000000001d9a0
000000000000000000000000000000000000000000000000000000000001d9dc
000000000000000000000000000000000000000000000000000000000001da40
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000a20
0000000000000000000000000000000000000000000000000000000000000064
000000000000000000000000000000000000000000000000000000000001d9dc
0000000000000000000000000000000000000000000000000000000000000000
00000000000000000000000079652f18f281c113fac20e8434e223228340e383
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe4
    MEMORY
 mem size greater than 1000 bytes     STORAGE

EVM  02:47:17 PM|eth   < 0 : @79652f18… : #39628 : 3141 : CALL : 14 : -115792089237316195423570985008687907853269984665640564039457584007913129639948 : 0x32 >

Breakpoint 8, dev::eth::VM::go(dev::eth::ExtVMFace&, std::function<void (unsigned long, dev::eth::Instruction, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<0u, 0u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long> >, (boost::multiprecision::expression_template_option)1>, dev::eth::VM*, dev::eth::ExtVMFace const*)> const&, unsigned long) (this=0x7fffac015f30, _ext=..., _onOp=..., _steps=18446744073709511986)
    at /home/lefteris/ew/cpp-ethereum/libevm/VM.cpp:626
626                             if (m_stack[m_stack.size() - 3] > 0)
(gdb) p gas
$22 = {m_backend = {<boost::multiprecision::backends::cpp_int_base<256u, 256u, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void, false>> = {static limb_bits = 64, static max_limb_value = 18446744073709551615, 
      static sign_bit_mask = <optimized out>, static internal_limb_count = 4, static variable = false, static upper_limb_mask = <optimized out>, m_wrapper = {m_data = {18446744073709551588, 18446744073709551615, 18446744073709551615, 18446744073709551615}, 
        m_first_limb = 18446744073709551588, m_double_first_limb = 0xffffffffffffffffffffffffffffffe4}, m_limbs = 4}, <No data fields>}}
```

It's due to a CALL having an insanely negative amount of gas and there seems to be no overflow checking inside that `case` branch. 

The mystery is why does this happen only to me and to none else? The answer is probably a later version of the boost library as compared to Ubuntu. ArchLinux has upgraded to 1.58.0-1.

#### Reason this happens

After some more debugging the culprit has been found. The condition in [this line](https://github.com/ethereum/cpp-ethereum/blob/develop/libevm/VM.cpp#L202) does not work as expected. It actually seems to cast `runGas` to a `u256` and because runGas is ```115792089237316195423570985008687907853269984665640564039457584007913129639948``` which is bigger than `u256::max` we have an overflow.

The above can be seen below:

```
    at /home/lefteris/ew/cpp-ethereum/libevm/VM.cpp:202
202                     cout << "runGas: " << runGas << endl;
(gdb) p runGas
$5 = {
  m_backend = {<boost::multiprecision::backends::cpp_int_base<0u, 4294967295u, (boost::multiprecision::cpp_integer_type)1, (boost::multiprecision::cpp_int_check_type)0, std::allocator<unsigned long long>, false>> = {<std::allocator<unsigned long long>> = {<__gnu_cxx::new_allocator<unsigned long long>> = {<No data fields>}, <No data fields>}, static limb_bits = 64, static max_limb_value = 18446744073709551615, static sign_bit_mask = <optimized out>, static internal_limb_count = 2, static variable = true, m_data = {ld = {capacity = 8, 
          data = 0x7fffb0081640}, la = {8, 140736146708032}, first = 8, double_first = 0x00007fffb00816400000000000000008}, m_limbs = 5, m_sign = false, m_internal = false}, <No data fields>}}
(gdb) n
runGas: 115792089237316195423570985008687907853269984665640564039457584007913129639948
203                     cout << "m_gas: " << m_gas << endl << endl;
(gdb) n
m_gas: 14

204                     if (m_gas < runGas)
```

It is reproducible with this simple test:

```c++
BOOST_AUTO_TEST_CASE(u256_overflow_test)
{
	dev::u256 a = 14;
	dev::bigint b = dev::bigint("115792089237316195423570985008687907853269984665640564039457584007913129639948");
	cout << b;
	BOOST_ASSERT(a < b);
}
```

It's definitely a boost issue .. or less likely a compiler issue.

**Boost version**: 1.58.0-1
**gcc version**:  4.9.2-4

#### Suggested solution

A way to fix this is to explicitly cast `m_gas` to `bigint`. This causes aforementioned test to work. Note that all such comparisons in VM.cpp would need changing.

**Comment by chfast** [comment]
Not confirmed on boost 1.55, gcc 4.9.2.

**Comment by chfast** [comment]
Your suggested solution fixes the problem only in VM. But this comparison happens all over the places, e.g. https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/Executive.cpp#L169-L170

It the library is broken we should fix the library. How can we rely on big number implementation that we know has a bug?

**Comment by chfast** [comment]
The bug is in boost 1.58+. 
https://svn.boost.org/trac/boost/ticket/11328

**Comment by LefterisJP** [comment]
I agree with you Pawel. In Skype chat we also theorised its probably a bug in boost but as I just took a 5 day vacation I could not investigate further immediately. 

Thanks for opening a bug with them.  Lets see how it goes.

**Comment by gavofyork** [comment]
until we get clarification from those guys about for now we have to assume it's not a bug in boost but rather a "fix".

as such we should make explicit for all comparisons.

**Comment by LefterisJP** [comment]
Bug is confirmed.

https://svn.boost.org/trac/boost/ticket/11328#comment:1

**Comment by LefterisJP** [comment]
This issue was solved by boost developers. We are injecting the fix ourselves if the user has the affected version with https://github.com/ethereum/cpp-ethereum/pull/2065. And I suppose future versions of boost will contain that fix too so the issue is now closed.
