### ISSUE TITLE
Error GPU mining: clEnqueueMapBuffer ( -4 )

### ISSUE THREAD

**Issue by gillhofer** [ethereum/cpp-ethereum#1982]
a `./eth -M -G --opencl-device 0` results in 
```
[user@pc eth]$ ./eth -M -G --opencl-device 0
Benchmarking on platform: { "platform": "NVIDIA CUDA", "device": "GeForce GTX 560", "version": "OpenCL 1.1 CUDA" }
Preparing DAG...
  ℹ  21:57:41|eth  Loading from libethash...
  ℹ  21:57:41|eth  Done loading.
Warming up...
  ℹ  21:57:41|gpuminer0  workLoop 0 #00000000… #00000000…
Using platform: NVIDIA CUDA
Using device: GeForce GTX 560(OpenCL 1.1 CUDA)
  ✘  21:57:42|gpuminer0  Error GPU mining: clEnqueueMapBuffer ( -4 )
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0
min/mean/max: 0/0/0 H/s
inner mean: 0 H/s
Phoning home to find world ranking...
Error phoning home. ET is sad.
```

**Comment by awrelll** [comment]
I'm having a similar issue 

```
 ℹ  10:27:49|ethminer  Getting work package...
  ℹ  10:28:04|ethminer  Loading from libethash...
  ℹ  10:28:04|ethminer  Done loading.
  ℹ  10:28:04|ethminer  Getting work package...
  ℹ  10:28:14|ethminer  Loading from libethash...
  ℹ  10:28:14|ethminer  Done loading.
  ℹ  10:28:14|ethminer  Got work package:
  ℹ  10:28:14|ethminer    Header-hash: c569cedde3bf8a6133744f153da4c89dea5f6c6e7776cc9be77d6e74689fc132
  ℹ  10:28:14|ethminer    Seedhash: 9b1ca7a86d339a3f175e48937848ac1cc012678e046b8c433a226d06f0f9bf9b
  ℹ  10:28:14|ethminer    Target: 0000000072c7dddfbb5390fd64d16dbd48050b82e9dbdd702c41cfa889460b34
  ℹ  10:28:14|gpuminer0  workLoop 0 #00000000… #9b1ca7a8…
Using platform: AMD Accelerated Parallel Processing
Using device: Tahiti(OpenCL 1.2 AMD-APP (1445.5))
  ℹ  10:28:15|ethminer  Mining on PoWhash #c569cedd… : 0 H/s = 0 hashes / 0.5 s
  ℹ  10:28:15|ethminer  Got work package:
  ℹ  10:28:15|ethminer    Header-hash: fd6a75b0a2aba7e06e4169245136506eabad74f9880626fc21cf98d81be29b60
  ℹ  10:28:15|ethminer    Seedhash: 9b1ca7a86d339a3f175e48937848ac1cc012678e046b8c433a226d06f0f9bf9b
  ℹ  10:28:15|ethminer    Target: 0000000072c7dddfbb5390fd64d16dbd48050b82e9dbdd702c41cfa889460b34
  ✘  10:28:15|gpuminer0  Error GPU mining: clCreateBuffer ( -61 )
  ℹ  10:28:18|gpuminer0  workLoop 1 #9b1ca7a8… #9b1ca7a8…
  ✘  10:28:18|gpuminer0  Error GPU mining: clEnqueueWriteBuffer ( -38 )
```

**Comment by veox** [comment]
These are different failures. An error code expansion [like this](https://stackoverflow.com/questions/24326432/convenient-way-to-show-opencl-error-codes) might be useful.

**Comment by gillhofer** [comment]
Thank you, I didn't know that. I edited the issue title.

**Comment by namjar** [comment]
$ ethminer -G -M --opencl-device 2
Benchmarking on platform: { "platform": "Apple", "device": "AMD Radeon HD Verde XT Prototype Compute Engine", "version": "OpenCL 1.2 " }
Preparing DAG...
  ℹ  15:28:05|main  Loading from libethash...
  ℹ  15:28:05|main  Done loading.
Warming up...
  ℹ  15:28:05|gpuminer0  workLoop 0 #00000000… #00000000…
  ℹ  15:28:05|gpuminer0  Initialising miner...
Using platform: Apple
Using device: AMD Radeon HD Verde XT Prototype Compute Engine(OpenCL 1.2 )
  ✘  15:28:06|gpuminer0  Error GPU mining: clEnqueueNDRangeKernel ( -4 )
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0
min/mean/max: 0/0/0 H/s
inner mean: 0 H/s
Phoning home to find world ranking...
Error phoning home. ET is sad.

**Comment by kejace** [comment]
@veox I'm having the exact same issue as you do. What cards are you using? This happens for me on my 6990. A 290x runs fine on the same machine. I suspect it either being because it is a dual-core card, or the fact that is only supporting OpenCL 1.2.

**Comment by lexansoft** [comment]
Same here


nduserca312:cpp-ethereum alexn$ eth -M -G --opencl-device 1
Benchmarking on platform: { "platform": "Apple", "device": "GeForce GT 750M", "version": "OpenCL 1.2 " }
Preparing DAG...
  ℹ  16:44:46|main  Loading from libethash...
  ℹ  16:44:46|main  Done loading.
Warming up...
  ℹ  16:44:46|gpuminer0  workLoop 0 #00000000… #00000000…
  ℹ  16:44:46|gpuminer0  Initialising miner...
Using platform: Apple
Using device: GeForce GT 750M(OpenCL 1.2 )
  ✘  16:44:48|gpuminer0  Error GPU mining: clEnqueueNDRangeKernel ( -4 )
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0
 ⚡   16:45:08|gpuminer0  Worker stopping 0.255179 s
min/mean/max: 0/0/0 H/s
inner mean: 0 H/s
Phoning home to find world ranking...
Error phoning home. ET is sad.

**Comment by gavofyork** [comment]
probably to do with trying to allocate a single 1GB slab.

**Comment by charlieknoll** [comment]
--use-chunks will force the dag to be written in 4 chunks.  Use GPU Caps Viewer to determine the opencl max buffer size for your card.  The dag is 1.07G, so max buffer size must be at least that large to not use the --use-chunks flag.  My testing with --use-chunks does not throw an error but I have never found a target with over 100G hashes attempted.

**Comment by lexansoft** [comment]
eth does not understand --use-chunks key...


Alexandre Naverniouk

**Comment by chriseth** [comment]
Is this still an issue?

**Comment by gillhofer** [comment]
Well, the 'fix' was to not support cards with 1G memory.

So, its still an issue, but probably not for ethereum.

**Comment by LefterisJP** [comment]
We can't do anything for cards with less than 1G of memory. Actually cards with 2G of memory is the absolute minimum. This is how the PoW algorithms works. Closing this issue.
