### ISSUE TITLE
JS API should give specific error when over-gassy transaction

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#1986]
When making a transaction which would go over the block's remaining gas limit, there's an error like this:

```
JavaScript	error	11:11:58	webthree.js - line 3491 - Uncaught Error: INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised
Run	info	11:11:38	Run complete
Run	info	11:11:38	Running transactions...
```

I *do appreciate* that mix will not keep stuffing transactions in. It's a kind of hint that gas isn't free. My recommendation would be to just put a decent error message in for the moment, or until mix is (ever?) sophisticated to deal with more complex blockchain situations.

**Comment by yann300** [comment]
JS API should returns the underlying exception instead of throwing INVALID_PARAM.
