### ISSUE TITLE
Avoid mining functionality for win32

### ISSUE THREAD

**Issue by Marren85** [ethereum/cpp-ethereum#1989]
Title says it all, fatal crash when creating the DAG, doesn't even start

The Visual C++ Redistributable Package for Visual Studio 2013 32 bit is already installed.

![creatdagfatal](https://cloud.githubusercontent.com/assets/12530085/7730940/1d8c9f2a-ff15-11e4-8b48-a36f6b6d5278.jpg)

**Comment by sontol** [comment]
Last time I saw there's problem with writing DAG to the Disk because of wchar/char confusion. You can try to hardcode all the path in libethash's io.c to static location and recompile

**Comment by gavofyork** [comment]
mining isn't supported for 32-bit windows.

**Comment by Marren85** [comment]
It's a 64 bit windows OS, the Wiki says to install the 32 bit C++ Redistributable Package even if on a 64 bit OS which is exactly what I did

**Comment by sontol** [comment]
https://github.com/ethereum/cpp-ethereum/pull/1965 doesn't fix it for you? Another issue that I often encountered is you need to change libcurld.dll to libcurl.dll

**Comment by Marren85** [comment]
I'm not sure, I can't get past [this](https://github.com/ethereum/cpp-ethereum/issues/1985) showstopper at the minute.

**Comment by sontol** [comment]
Oh, I see. Maybe you can try the eth instead of AlethZero? See if that works.

**Comment by gavofyork** [comment]
win32 no longer a supported platform
