### ISSUE TITLE
 ethminer Segmentation fault

### ISSUE THREAD

**Issue by rachimo34** [ethereum/cpp-ethereum#1990]
No matter what I do I have a Segmentation fault : 11 in result
Hardware: imac late 2013, GPU NVIDIA GeForce GTX 775M 2048 MB

$ eth -m on -G -M --opencl-platform 1 --opencl-device 1 

Benchmarking on platform: { "platform": "Apple", "device": "GeForce GTX 775M", "version": "OpenCL 1.2 " }
Preparing DAG...
ℹ 17:10:50|main Loading from libethash...
ℹ 17:10:50|main Done loading.
ℹ 17:1Warming up...
0:50|gpuminer0 workLoop 0 #00000000… #00000000…
ℹ 17:10:50|gpuminer0 Initialising miner...
Using platform: Apple
Using device: GeForce GTX 775M(OpenCL 1.2 )
Trial 1...Segmentation fault: 11

It doesn't matter which opencl device or platform I select.
Anyone have an idea what can be wrong?

**Comment by sontol** [comment]
I think NVidia doesn't allow you allocate huge chunk of memory at once. Probably will need to subdivide the dag.

**Comment by rachimo34** [comment]
Hey sontol
thx for your help 
I think I found the problem, it was related with cmake -DETHASHCL=1
I had to re-install the ethminer from scratch and somehow its worked
OSX GeForce GTX 775M(OpenCL 1.2 )
2443419/2513231/2531527 H/s

**Comment by gavofyork** [comment]
very odd... can't imagine what you did the first time...
