### ISSUE TITLE
filter.watch is firing before transaction is on the blockchain

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#1997]
develop ce205f3

have code that sets up 1) filter.watch then 2) sendTransaction  [sample code below if it helps]

cpp eth cli will fire the filter.watch almost instantly, even though the transaction may never end up on the blockchain.  The event should only be fired when the transaction is in a block, as Geth does.
with cpp, the result callback of filter.watch is returning with a blockNumber of 0.  Here is an example of the result object from a filter.watch from Geth, non-zero blockNumber:

address: "0xc72369303ce552f5500bb7f398f2a1916c450e7e"args: ObjectblockHash: "0x637828d196cf43fbc33fa407132bc2556fb9c5e71842c50d29493f71491e07f5"blockNumber: 398856event: "rvalReserveTicket"logIndex: 0transactionHash: "0x7c934234617bc3e3d5713c01052eb26be739e3edd8444f19dcc01f411c7fffb3"transactionIndex: 0

Sample code.  (The same code was run against both Geth and cpp)
```
var rvalFilter = contract.rvalReserveTicket({ ticketId: ticketId });
rvalFilter.watch(function(err, res) {
  // res.blockNumber is 0 for cpp eth  <----------------- problem
});

contract.reserveTicket.sendTransaction(ticketId, txHash, objParam, function(err, txHash) {
  console.log('txHash: ', txHash)
});
```

**Comment by gavofyork** [comment]
actually, here Go is incorrect - *if* you're watching for pending transactions, you should get the log filter before it gets mined.

**Comment by ethers** [comment]
I am using an event, `rvalReserveTicket`, and don't specify anything in the `watch`.  It isn't clear what is the default in the documentation?
https://github.com/ethereum/wiki/wiki/JavaScript-API#contract-events
https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethfilter

If the default is 'latest', then there's a cpp issue?  Does 'pending' make sense for an event?  Thanks

**Comment by frozeman** [comment]
In go the defaults are currently `fromBlock: 'latest'` and `toBlock: 'latest'`, meaning you would only get the last mined logs.

Pending logs are currently not yet working see https://github.com/ethereum/go-ethereum/issues/852

**Comment by frozeman** [comment]
Pending transactions filter, don't have the filter options, so they are always pending :)

**Comment by debris** [comment]
fixed in #2108. Logs has additional field `type`. Field can have values `pending` for pending logs, and `block` for mined.

**Comment by frozeman** [comment]
Why not `type: 'pending' and `type: 'mined'`?

`type: 'block'` sounds odd.

**Comment by debris** [comment]
> Why not `type: 'pending'` and `type: 'mined'`?
`type: 'block'` sounds odd.

sure. it will be `mined`
