### ISSUE TITLE
display full transaction hash on New transaction

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#2000]
eth cli logs a truncated hash.  Especially for "New transaction", it would be helpful to have the full transaction hash.  Otherwise, how to query for this transaction?

Example eth output:
```
  ℹ  02:25:43|libmicrohttpd  New transaction a4ce4a84…{9dbe0ff2…/516$0+900000@10000000000000<-cd2a3d9f…
```

**Comment by gavofyork** [comment]
it's only there for recognition purposes, not for providing full information for querying into the chain. can't be logging 64-length hex bombs for all of these log entries.
