### ISSUE TITLE
CL_INVALID_BUFFER_SIZE and CL_INVALID_MEM_OBJECT for OpenCL 1.2 cards

### ISSUE THREAD

**Issue by kejace** [ethereum/cpp-ethereum#2010]
I'm getting mining errors:

```
gpuminer0  Error GPU mining: clCreateBuffer ( -61 ) // CL_INVALID_BUFFER_SIZE
gpuminer0  workLoop .....
gpuminer0  Error GPU mining: clEnqueueWriteBuffer ( -38 ) // CL_INVALID_MEM_OBJECT
```

This has been confirmed on both Radeon Tahiti and Cayman platforms. At least in the Cayman case, this is a dual-core card. But I know of other dual-core cards that work, for example 290x2, so it is maybe the OpenCL 1.2 that is the issue - or the combination of the two.

Does anyone know of things to try? I'm happy playing around with the code.

See also #1982

**Comment by kejace** [comment]
Looking closer at this, I think this is related to the issue of certain Radeon cards (OpenCL 1.2?). They can only allocate memory in maximum 512mb blocks.

```(there is a 512MB limit per allocation call but you can allocate as much as you like)
....
It's very simple, all you do is allocate in chunks of 512MB or less and make sure the chunks are rounded to about 0x4000 bytes, then they will be placed contiguously.```

from http://opencl33.rssing.com/chan-5296704/all_p4.html

So for example on my setup the maximum memory to allocate in **in one chunk** is 536870912 bytes but the `_dagSize` is 1182786944 bytes.

Can anyone help dividing up the DAG and upload it in 512mb chunks? This will probably not affect performance on newer cards much.

**Comment by kejace** [comment]
I've been able to verify and replicate the issue using the code here https://community.amd.com/thread/158397 .

**Comment by cslarson** [comment]
this looks like it's the same issue I'm experiencing on my radeon r7 265 card. it does complete the benchmarking but I see these same errors when trying to mine. thanks for looking into it further.

**Comment by kejace** [comment]
Yeah, I'm working on a patch - I know how to do it in C but its slightly trickier using the OpenCL C++ wrappers that cpp-ethereum uses.

I didn't have any luck, but you might want to try the environment variable trick mentioned here: https://community.amd.com/thread/158397

I suspect it might work on older(?) drivers.

**Comment by kejace** [comment]
So the code in the post above (https://community.amd.com/thread/158397) works on these cards. It is just a matter of using a similar approach in the miner code. The problem for me is that I don't know how to translate the code using cl_mem into the cl::Buffer that the C++ wrapper uses.

How can one allocate multiple buffers, or chunks, and get one address that points to a continuous chunk? In C it seems to work automatically, but more work is needed to work with the cl::Buffer.

Any help would be appreciated!

**Comment by kejace** [comment]
I think this is what @gavofyork addressed in commit cbdb46ea435c34485f178f7d9a77ee59a75d8db9

**Comment by sontol** [comment]
I have a working code (in private network, I haven't mine in Olympic because of shitty graphic card) that subdivide dag into 4 but https://xkcd.com/1513/. It is a bit messy because you need to include the .cl file (it compensates for the 4 division) with the distribution. I'm not really sure how to show it (or if anyone would appreciate it). Creating a fork of the repo seems a bit overkill. Only changes are in the ethash_cl_miner.cpp and ethash_cl_miner_kernel.cl.

**Comment by kejace** [comment]
Oh, yeah I thought of passing four(?) different buffers and changing the .cl code, but I guess I had the same reservations about it as you. Still, I'm super keen on testing it.

FYI, I just decided to upload a third of the DAG on the card and mine away. It works, but I'm not hoping to win any blocks!

**Comment by kejace** [comment]
Could you email it? I'm at gmail with the same handle.

**Comment by sontol** [comment]
Done

**Comment by cslarson** [comment]
GPU mining is successful for me now (9.2ishMH/s in alethzero). I changed to the drivers from http://support.amd.com/en-us/kb-articles/Pages/OpenCL2-Driver.aspx. I also rebuilt from the latest develop, though it didn't appear to have any mining related changes. I had previously set
```
export GPU_MAX_HEAP_SIZE=95
export GPU_MAX_ALLOC_PERCENT=100
```
though it didn't seem to make a difference. It's presently at GPU_MAX_HEAP_SIZE=75. So the main difference I can tell is the driver. Sorry it's not more helpful.

**Comment by kejace** [comment]
Yeah, it seems like a good workaround. Unfortunately, the 2.0 drivers don't support multiple gpu's. Your R7 265 is only one core, right?

**Comment by geoah** [comment]
Same issue with an `ATI 5850R`.
@kejace and @sontol would you mind sharing your fixes?

**Comment by sontol** [comment]
Based on Google that is a 1GB Card? You need at least a 2GB  to mine...

**Comment by brisedarius** [comment]
I think i have the same issue here with my Radeon r9 270x 2 GB card on Ubuntu 14.04.2. According to clinfo i have an available max memory size of round about 1.2 GB. With i think is now to less for the current DAG size. I constanlty ran into gpu memory fragmentation errors. 

I've tried several drivers for my card: fglrx, fglrx-updates and the latest driver from the ATI website - none has worked so far. However i will try the OpenCL 2 driver tonight...

Setting the GPU_MAX_HEAP_SIZE or GPU_MAX_ALLOC_PERCENT environment variables did not work for me on ubuntu - i tried this with different drivers. Suprisingly settings those variables worked fine under Windows.

<b>@sontol</b> Could you please mail me your code that splits up the buffer into 4 parts. I would realy give a try.

**Comment by sontol** [comment]
give me your address

**Comment by sontol** [comment]
does github has pm? Still a noob here

**Comment by sontol** [comment]
or should i just fork it?

**Comment by geoah** [comment]
@sontol didn't know the 2gb limit. thanks

You could make a fork for the ones who'd like to merge it themselves and then maybe a pull request to ethereum/cpp-ethereum and ask for any tips on coding/optimisations if you'd like.

**Comment by sontol** [comment]
Since there seems to be quite a bit of interest I've placed the two files (ethash_cl_miner.cpp and ethash_cl_miner_kernel.cl) in my own repo of ethash (please use it only with ethminer, not with benchmark). The drawback is that I have changed ethash_cl_miner.cpp so that the .cl file needs to be placed in the same folder as the the executable (I don't like recompiling everytime I change the .cl). I am also allergic to cmake.

I don't think I should make the pull request though. There seems to be performance hit if you compare (not too much but still noticeable) if you compare it with the original one.

**Comment by brisedarius** [comment]
<b>@sontol</b> Thanks.

**Comment by brisedarius** [comment]
Iam not able to test it yet on my machine, but as soon as iam - i'll give feedback.

**Comment by gavofyork** [comment]
fork and provide a PR; we'll knock it into shape one way or another :)

**Comment by sontol** [comment]
Oh, yeah there's header (ethash_cl_miner.h) change as well.

**Comment by kejace** [comment]
FWIW I commited my fork. All credit goes to @sontol for the actual code changes.
