### ISSUE TITLE
error on getstuff building cpp-ethereum

### ISSUE THREAD

**Issue by marimes** [ethereum/cpp-ethereum#2015]
Hello Ethereum Team,

When following the instructins on https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Windows I got an error on step getstuff.bat:

DISPLAY: '{C6C015EB-03F3-4974-87B7-EB3236CB1CE7}' TYPE: DOWNLOAD STATE: TRANSIENT_ERROR
PRIORITY: NORMAL FILES: 0 / 1 BYTES: 226498725 / 895703351 (25%)
ERROR FILE:    https://build.ethdev.com/builds/windows-precompiled/qt-5.4.1.tar.gz -> C:\cpp-ethereum\extdep\d ERROR CODE:    0x80070057
ERROR CONTEXT: 0x00000005

Any help is much appreciated :-)

Best,
Marius

**Comment by debris** [comment]
Have you tried running this command again? Dependency server might have been temporarily unavailable.

**Comment by marimes** [comment]
Many thanks for the upodate. Great, now getstuff ran to completion. Next problem is that I am stuck with a nasty error when trying to install the Windows SDKs. If you have a hint, great but I am not expecting you to solve this - looks like my problem...

07:44:52 Montag, 1. Juni 2015: [SDKSetup:Error] Config_Products_Install: Windows SDK Setup (failed): Installation of the "Microsoft Windows SDK for Windows 7" product has reported the following error: Please refer to Samples\Setup\HTML\ConfigDetails.htm document for further information. Stack:    bei SDKSetup.Product.ConfigureNewProduct(ManualResetEvent CancelEvent)	   bei SDKSetup.Product.SetupProduct(TaskMode taskMode, ManualResetEvent CancelEvent)	   bei SDKSetup.ProductCollection.SetupProducts(TaskMode taskMode, DownloadManager downloadManager, ManualResetEvent cancelEvent)	   bei SDKSetup.ConfigProducts.DoCurrentTask(TaskMode Task)

Consequently cmake does not run through:

The C compiler identification is MSVC 18.0.31101.0
The CXX compiler identification is MSVC 18.0.31101.0
Check for working C compiler using: Visual Studio 12 2013 Win64
Check for working C compiler using: Visual Studio 12 2013 Win64 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 12 2013 Win64
Check for working CXX compiler using: Visual Studio 12 2013 Win64 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
FindWindowsSDK: Detected Visual Studio 2012 or newer, not using the _xp toolset variant: including SDK versions that drop XP support in search!
Found WindowsSDK: C:/Program Files (x86)/Windows Kits/8.1;C:/Program Files (x86)/Microsoft SDKs/Windows/v8.0A;C:/Program Files (x86)/Windows Kits/8.0;C:/Program Files (x86)/Microsoft SDKs/Windows/v8.1A;C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A  
 - Found Windows SDK v8.1 at C:/Program Files (x86)/Windows Kits/8.1
 - Found Windows SDK v8.0A at C:/Program Files (x86)/Microsoft SDKs/Windows/v8.0A
 - Found Windows SDK v8.0 at C:/Program Files (x86)/Windows Kits/8.0
 - Found Windows SDK v8.1A at C:/Program Files (x86)/Microsoft SDKs/Windows/v8.1A
 - Found Windows SDK v7.1A at C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A
 - WindowsSDK dirs: C:/Program Files (x86)/Windows Kits/8.1;C:/Program Files (x86)/Microsoft SDKs/Windows/v8.0A;C:/Program Files (x86)/Windows Kits/8.0;C:/Program Files (x86)/Microsoft SDKs/Windows/v8.1A;C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A
ctest path: C:/Program Files (x86)/CMake/bin/ctest.exe
CMake Error at cmake/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CryptoPP (missing: CRYPTOPP_INCLUDE_DIR CRYPTOPP_LIBRARY)
  (Required is exact version "5.6.2")
Call Stack (most recent call first):
  cmake/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindCryptoPP.cmake:107 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/EthDependencies.cmake:44 (find_package)
  CMakeLists.txt:292 (include)

Configuring incomplete, errors occurred!
See also "C:/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".

**Comment by debris** [comment]
WindowsSDK is installed properly. CryptoPP is the missing one. Dependency directory is probaly malformed/not downloaded properly. Can you remove `extdep/install` && `extdep/download` and run `getstuff` again? If it does not help, please tell me what version of cmake you have.

**Comment by marimes** [comment]
Now the download stopped at the following point:

DISPLAY: '{35C6845A-308A-4C42-82D8-AD9DD35ACC34}' TYPE: DOWNLOAD STATE: TRANSIENT_ERROR
PRIORITY: NORMAL FILES: 0 / 1 BYTES: 62181026 / 895703351 (6%)
ERROR FILE:    https://build.ethdev.com/builds/windows-precompiled/qt-5.4.1.tar.gz -> C:\cpp-ethereum\extdep\d ERROR CODE:    0x80070057
ERROR CONTEXT: 0x00000005

**Comment by sontol** [comment]
Not really sure if you are still experiencing. But normally after pressing Enter several times the download will resume
