### ISSUE TITLE
web3.sha3() cannot hash as much as Solidity's sha3().

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#2020]
Solidity's sha3() can hash a group of numbers, while web3.sha3() can only hash a single string. 

Consider a contract (an auction, say, or in my case a simple game) with secret numerical bids. Suppose the contract stores preimages of the bid hashed with a nonce and maybe a salt. When the bidding is over, the bidders can submit the bid and the nonce to confirm the bid, and solidity can hash them all to confirm the bid is accurate, then work with the bid. This part works fine.

But how does the client generate the preimages to send? web3.sha3() can only hash one string. The string "100" is not the same as the integer one hundred. If I send the string "100" however, the contract would have to waste gas parsing the string. It'd be far easier if web3.sha3 could just hash numbers on its own.

**Comment by gavofyork** [comment]
should really be in the web3.js repo

**Comment by Smithgift** [comment]
I'll put this in over there, then.
