### ISSUE TITLE
alethzero crashes on malformed  eth subprotol  status packet

### ISSUE THREAD

**Issue by wanderer** [ethereum/cpp-ethereum#2042]
He is the output
```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::BadCast>'
  what():  std::exception
fish: Job 1, “./alethzero/alethzero ” terminated by signal SIGABRT (Abort)
```

**Comment by wanderer** [comment]
i was not added  the prefix  to the packet, So actully cpp is crashing on a malformed hello packet, not status

**Comment by gavofyork** [comment]
could you give an example of such a malformed packet?

**Comment by wanderer** [comment]
@gavofyork here is the hex before encryption. 
`00f8483c8083020000a0fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdcaa0fd4af92a79c7fc2fd8bf0d342f2e832e1d4f485c85b9152d2039e03bc604fdca`

This is being send after we do the handshake. cpp-eth is expecting the eth status packet here. It works fine if we add the correct eth-subprotocol prefix, so its not a problem with encryption.

**Comment by gavofyork** [comment]
presumably fixed in latest. if not, reopen.
