### ISSUE TITLE
Windows 8.1 Build Errors

### ISSUE THREAD

**Issue by carloscarlson** [ethereum/cpp-ethereum#2043]
Forgive me if I am not reading this error log correctly.

I receive these errors when I  try to use msbuild to compile from the command line:

Done Building Project "C:\cpp-ethereum\build\ALL_BUILD.vcxproj.metaproj" (defau
lt targets) -- FAILED.

Done Building Project "C:\cpp-ethereum\build\ethereum.sln" (default targets) --
 FAILED.

Build FAILED.

"C:\cpp-ethereum\build\ethereum.sln" (default target) (1) ->
"C:\cpp-ethereum\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"C:\cpp-ethereum\build\abi\abi.vcxproj.metaproj" (default target) (6) ->
"C:\cpp-ethereum\build\libethereum\ethereum.vcxproj.metaproj" (default target)
(17) ->
"C:\cpp-ethereum\build\libethereum\ethereum.vcxproj" (default target) (32) ->
(ClCompile target) ->
  c:\cpp-ethereum\libethereum\BlockDetails.h(66): warning C4267: '=' : conversi
on from 'size_t' to 'unsigned int', possible loss of data [C:\cpp-ethereum\buil
d\libethereum\ethereum.vcxproj]
  c:\cpp-ethereum\libethereum\BlockDetails.h(67): warning C4267: '=' : conversi
on from 'size_t' to 'unsigned int', possible loss of data [C:\cpp-ethereum\buil
d\libethereum\ethereum.vcxproj]
  c:\cpp-ethereum\libethereum\BlockDetails.h(76): warning C4267: '=' : conversi
on from 'size_t' to 'unsigned int', possible loss of data [C:\cpp-ethereum\buil
d\libethereum\ethereum.vcxproj]
  c:\cpp-ethereum\libethereum\BlockDetails.h(77): warning C4267: '=' : conversi
on from 'size_t' to 'unsigned int', possible loss of data [C:\cpp-ethereum\buil
d\libethereum\ethereum.vcxproj]
  c:\cpp-ethereum\libethereum\BlockDetails.h(86): warning C4267: '=' : conversi
on from 'size_t' to 'unsigned int', possible loss of data [C:\cpp-ethereum\buil
d\libethereum\ethereum.vcxproj]
  c:\cpp-ethereum\libethereum\BlockDetails.h(87): warning C4267: 'argument' : c
onversion from 'size_t' to 'unsigned int', possible loss of data [C:\cpp-ethere
um\build\libethereum\ethereum.vcxproj]
  c:\cpp-ethereum\libethereum\BlockDetails.h(87): warning C4267: '=' : conversi
on from 'size_t' to 'unsigned int', possible loss of data [C:\cpp-ethereum\buil
d\libethereum\ethereum.vcxproj]
  c:\cpp-ethereum\libdevcore\TrieCommon.h(49): warning C4267: 'return' : conver
sion from 'size_t' to 'unsigned int', possible loss of data [C:\cpp-ethereum\bu
ild\libethereum\ethereum.vcxproj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(307): warning C4244: 'initializing
' : conversion from 'time_t' to 'unsigned int', possible loss of data [C:\cpp-e
thereum\build\libethereum\ethereum.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\algorithm(4141
): warning C4267: 'argument' : conversion from 'size_t' to 'const unsigned int'
, possible loss of data [C:\cpp-ethereum\build\libethereum\ethereum.vcxproj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(360): warning C4267: 'argument' :
conversion from 'size_t' to 'unsigned int', possible loss of data [C:\cpp-ether
eum\build\libethereum\ethereum.vcxproj]

"C:\cpp-ethereum\build\ethereum.sln" (default target) (1) ->
"C:\cpp-ethereum\build\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"C:\cpp-ethereum\build\abi\abi.vcxproj.metaproj" (default target) (6) ->
"C:\cpp-ethereum\build\libethereum\ethereum.vcxproj.metaproj" (default target)
(17) ->
"C:\cpp-ethereum\build\libethereum\ethereum.vcxproj" (default target) (32) ->
(ClCompile target) ->
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(108): error C2317: 'try' block sta
rting on line '106' has no catch handlers [C:\cpp-ethereum\build\libethereum\et
hereum.vcxproj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(109): error C2318: no try block as
sociated with this catch handler [C:\cpp-ethereum\build\libethereum\ethereum.vc
xproj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(111): error C2065: 'uncle' : undec
lared identifier [C:\cpp-ethereum\build\libethereum\ethereum.vcxproj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(111): error C2228: left of '.data'
 must have class/struct/union [C:\cpp-ethereum\build\libethereum\ethereum.vcxpr
oj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(112): error C2065: 'uncle' : undec
lared identifier [C:\cpp-ethereum\build\libethereum\ethereum.vcxproj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(112): error C2228: left of '.data'
 must have class/struct/union [C:\cpp-ethereum\build\libethereum\ethereum.vcxpr
oj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(123): error C2318: no try block as
sociated with this catch handler [C:\cpp-ethereum\build\libethereum\ethereum.vc
xproj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(125): error C2065: 'uncle' : undec
lared identifier [C:\cpp-ethereum\build\libethereum\ethereum.vcxproj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(125): error C2228: left of '.data'
 must have class/struct/union [C:\cpp-ethereum\build\libethereum\ethereum.vcxpr
oj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(125): error C2065: '_e' : undeclar
ed identifier [C:\cpp-ethereum\build\libethereum\ethereum.vcxproj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(125): error C2228: left of '.what'
 must have class/struct/union [C:\cpp-ethereum\build\libethereum\ethereum.vcxpr
oj]
  C:\cpp-ethereum\libethereum\BlockQueue.cpp(125): error C2661: 'dev::eth::badB
lockHeader' : no overloaded function takes 1 arguments [C:\cpp-ethereum\build\l
ibethereum\ethereum.vcxproj]

    11 Warning(s)
    12 Error(s)

Time Elapsed 00:00:20.74

**Comment by debris** [comment]
Can you pulled latest develop and check again? It should be solved in https://github.com/ethereum/cpp-ethereum/pull/2041
