### ISSUE TITLE
Mix/JS API: contract event.watch() broken.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#2059]
I have an event used like this in the JS API: (efc is my contract)
```javascript
var challengeMadeEvent = efc.challengeMade({}, {fromBlock: 0, toBlock: 'latest'});
```
Setting a callback on it through .watch() gives the following immediately when the transaction for causing it becomes pending:
```
JavaScript	error	17:04:55	webthree.js - line 2211 - Uncaught TypeError: Cannot read property 'data' of null
```
The callback does not appear to be actually called, either.

**Comment by debris** [comment]
should be fixed in #2108
