### ISSUE TITLE
[mix] doesn't display transactions made from contract

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#2063]
It would be nice to see what's exactly happening.

![screen shot 2015-06-02 at 10 18 52](https://cloud.githubusercontent.com/assets/2613714/7931459/354da20c-0911-11e5-9842-32ea73bb3a90.png)
![screen shot 2015-06-02 at 10 19 07](https://cloud.githubusercontent.com/assets/2613714/7931460/367a7d94-0911-11e5-9c0d-a9e07ca6cace.png)

**Comment by arkpar** [comment]
Technically there is no additional transaction, this is just a regular call into other contract and all balance changes happen in the same transaction. This particular case will become more user-friendly once we get acconts/balances display done
