### ISSUE TITLE
[mix] display latest address information

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#2064]
It would be nice to see in the right panel addresses latest balance, nonce, code.

**Comment by yann300** [comment]
PR #2359 (balance)

**Comment by yann300** [comment]
@debris does it really worth to display nonce? do you have use case for that where dapp developers needs to see account nonce?
For the code, it is available in the mix editor. but you're right that users might want to use contract and see code for contract which are in the mainchain. This will be added later when we will work on importing the live state.

**Comment by gavofyork** [comment]
Please move all mix issues to [the Mix Issues repo](https://github.com/ethereum/mix/issues).
