### ISSUE TITLE
got that today - on latest

### ISSUE THREAD

**Issue by romanman** [ethereum/cpp-ethereum#2071]
commit 2cd1b68333667669f86d4b31c200835410c69fa4

```
requested; peer on different chain?
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

```

**Comment by LefterisJP** [comment]
Dupolicate issue: https://github.com/ethereum/cpp-ethereum/issues/2083

**Comment by romanman** [comment]
@LefterisJP : I am not sure it is the same one , 
the one gives concrete exception , the other not...
