### ISSUE TITLE
Segfault in EvmJit

### ISSUE THREAD

**Issue by arkpar** [ethereum/cpp-ethereum#2086]
Race condition on std::set here:
https://github.com/ethereum/cpp-ethereum/blob/develop/evmjit/libevmjit/Array.cpp#L303

**Comment by arkpar** [comment]
Another race condition on g_listener here:
https://github.com/ethereum/cpp-ethereum/blob/develop/evmjit/libevmjit/Cache.cpp#L28

**Comment by chfast** [comment]
Thanks for that reports. Can you tell me how can these can be reproduced?

**Comment by arkpar** [comment]
Enable evmjit in alethzero, kill blockchain and start downloading a blockchain. Eventually it will crash in one of these two locations. AZ executes contracts in both UI and importing thread. Eth only does that in single thread.
