### ISSUE TITLE
segfault during blockchain download

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/cpp-ethereum#2101]
thats the trace: https://gist.github.com/CJentzsch/5f947229c87693781b13 
(here another one with the same issue: https://gist.github.com/CJentzsch/7644cb7cd9c790e925b6)

**Comment by gavofyork** [comment]
looks like it's in the libp2p network code.

**Comment by chfast** [comment]
It looks like the object that implements the Worker interface is null and when boost tries to execute virtual method doWork() the program crashes.

**Comment by gavofyork** [comment]
not seen this recently. presumably fixed.
