### ISSUE TITLE
Uncaught Error: solc error: signal: aborted (core dumped)

### ISSUE THREAD

**Issue by SilentCicero** [ethereum/cpp-ethereum#2105]
When I compile a Solidity contract that's natSpec is slightly invalid (I had a typo in an @param variable name), this error is returned: `Uncaught Error: solc error: signal: aborted (core dumped)`

From my understanding the compiler should not abort because of an invalid @param variable name in a natSpec comment. 

I'm using web3.js v5.0 in a client-side meteor project. I'm using the web3.eth.compile.solidity method with a solidity contract that contains natSpec commenting.

Note, when the natSpec is valid, everything works like a charm and a nice contract object is returned.

**Comment by LianaHus** [comment]
https://github.com/ethereum/cpp-ethereum/pull/2193
