### ISSUE TITLE
solc crashes with "--optimize on" on my code.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#2135]
[This](https://github.com/Smithgift/EthFence/blob/master/EthFence.sol) is a very large solidity contract I've made, and using solc --optimize on causes solc to crash.
```
Exception during compilation: /build/cpp-ethereum-IWk3iK/cpp-ethereum-0.9.24+924SNAPSHOT20150609140815trusty/libevmasm/../libevmasm/CommonSubexpressionEliminator.h(174): Throw in function _AssemblyItemIterator dev::eth::CommonSubexpressionEliminator::feedItems(_AssemblyItemIterator, _AssemblyItemIterator) [with _AssemblyItemIterator = __gnu_cxx::__normal_iterator<dev::eth::AssemblyItem*, std::vector<dev::eth::AssemblyItem> >]
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::OptimizerException>
std::exception::what: std::exception
[dev::tag_comment*] = Invalid use of CommonSubexpressionEliminator.
```
solc will compile it fine without the optimizer, but it's too large to fit in a single block unoptimized. solc also *used* to compile it with optimizer fine (I have bytecode it made earlier, appearing to be from June 4th), but not any more.

**Comment by chriseth** [comment]
Unfortunately, I was not able to reproduce your crash on latest develop. But the pull request above might fix it.

**Comment by chriseth** [comment]
Closed accidentally by smart github.

**Comment by Smithgift** [comment]
Seems to be working now.
