### ISSUE TITLE
Mix: Possibility to specify different chain or node to use?

### ISSUE THREAD

**Issue by step21** [ethereum/cpp-ethereum#2136]
Not sure if this is possible, but it seems mix can't just deploy and anyway I would prefer it to use my remote node, which is always running and always in sync (or at least more in sync than my laptop)
So is it possible to specify a different network or node to use (like can be done when specifying a different provider with web3.js) I already searched for a config file or something, is there some way to set this or could this be possible in the future?

**Comment by yann300** [comment]
This will be added (new option to change the default URL) to be able to connect to a remote node.
