### ISSUE TITLE
assertion failed during blockchain download

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/cpp-ethereum#2142]
During blockchain download I got the following output (in gdb in Debug mode):

▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  OK - queued as unknown parent: #f27d4c29…
☍ ℹ  15:00:15|eth     Imported and best 43525294845  (# 40131 ). Has 0 siblings. Route: [#6f9b3861…, #36a210c9…]
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  Queuing block #e01e3967… for import...
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  OK - queued as unknown parent: #e2b4dfdf…
☍ ◌  15:00:15|eth  Attempting import of #0c130765… ...
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  Queuing block #f27d4c29… for import...
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  OK - queued as unknown parent: #c412a60e…
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  Queuing block #e2b4dfdf… for import...
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  OK - queued as unknown parent: #3f1bcf95…
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  Queuing block #c412a60e… for import...
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  OK - queued as unknown parent: #4490f61b…
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  Queuing block #4490f61b… for import...
▣┅▶  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  OK - queued as unknown parent: #c6803e7c…
⧎ ◌  15:00:15|p2p|4c03c40e…|Geth/v0.9.26/darwin/go1.4.2  0 imported OK, 8 with unknown parents, 0 with future timestamps, 0  already known, 0  repeats received.
⧎ ✘  15:00:15|p2p|fdd29901…|Geth/v0.9.29-dffe6d32/linux/go1.4.2  Error reading: Operation canceled
⧎ ◌  15:00:15|ethsync|fdd29901…|Geth/v0.9.29-dffe6d32/linux/go1.4.2  Closing peer session :-(
⧎ ◌  15:00:15|ethsync|fdd29901…|Geth/v0.9.29-dffe6d32/linux/go1.4.2  Aborting Sync :-(
⚙ ◎  15:00:15|eth  Committing to disk: stateRoot #fb988159… = #fb988159… = f90211a0d522470346eebf1e34851e746b2cb09f695884fb4dde26aa5ea2e6da4da14a36a07024f79d3bfe3908bbeb8fd6e2407448b9b09bd452d2e7b97fa359fdec37fd8da064cd433cdbd1cfd26164c0c85671ca875b90dcd8dbe87d68ec6b11a33b6523fba05c4b5f2ea4e4cd8698dd8addd90cfbf89fb1dc2e333ac6a5df289e65c93435dfa0d0c2e48379fdbac6c7d7fe78c6f5a976cc7994455a63473462158f950bf0d555a0558dc2f96d2c454c81cf0f27dd33962c10db1511e7b4d5ecc13fc71e0cd45b2fa0f50f4ed4350247d016efc8f59855875c3ac43d18660f6675e38508a571981ed1a0c60d25a20281bdbf225a36d94dcb4f1aa5fbaa5a4f297411c85b0e8077e4eed4a0d0ef86feb0b19a78b2d5662dccd882d58068be465af69a7af94f446387290773a0dd438843fa76d492dddebab28fb611e0ffed13a21bf7ee9797aae0f3a479cc69a0caa0ed8ea3c1734826532588c3ae684e52bbf0312d018a999d446cc262c6038aa0658f4260cd158d999f56588e13503398ccfca7e8c676114ffe67e5fe47dd45fea0f9af95ed3b3a0030aee749a15c0905b0c6ed2f91e0e1fa6cf4c674d5e9cc88dba0a7008b2f31696985f6226b004df11d09fb92b4e43f27e808e674eb84bfbcf4f5a012895b8ff2c3898299649cba17ad55e12da2765b160a1940be20654355112690a0dd60c6569551f1264cdd9f19d5bc05fbcf72157779c3a4a73b5341e0d50ab1dd80
Press Entereth: /home/christoph/software/Ethereum/cpp-ethereum/libethereum/EthereumHost.cpp:395: void dev::eth::EthereumHost::onPeerBlocks(dev::eth::EthereumPeer*, const dev::RLP&): Assertion `_peer->m_asking == Asking::Nothing' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffcbfff700 (LWP 6828)]
0x00007ffff53a3cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

So we have an assertion failure here:  https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/EthereumHost.cpp#L395

that might be related to https://github.com/ethereum/cpp-ethereum/issues/2101

(full backtrace: https://gist.github.com/CJentzsch/ab58dc79ff51550fb8e8)

**Comment by chfast** [comment]
Nope. Still there.

https://gist.github.com/chfast/01aca976f9be03135412
