### ISSUE TITLE
eth gets stuck and stops getting more blocks

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#2162]
develop 3f94350

Ran eth, it got stuck on block 0x8d2fa (per RPC).
Been more than 10 mins stuck so here are the logs after block 0x8d2fa was imported

http://pastebin.com/adnpxXrv
http://pastebin.com/dfJgSF8k

**Comment by arkpar** [comment]
Please try with latest develop. Should be resolved

**Comment by ethers** [comment]
building right now, thanks @arkpar

**Comment by ethers** [comment]
on develop deb0f46  eth fell behind, got stuck on 0x8efc5 

here's some log: http://pastebin.com/v9KMxxrZ

**Comment by CJentzsch** [comment]
sounds related to https://github.com/ethereum/cpp-ethereum/issues/2209

**Comment by arkpar** [comment]
A few sync issues fixed in develop
