### ISSUE TITLE
Crash in dev::eth::EthereumPeer::setAsking and high memory usage

### ISSUE THREAD

**Issue by Benoit9** [ethereum/cpp-ethereum#2181]
Version AlethZero/v0.9.25/Release/Darwin/clang/int
41397c35a19e89031acfddf1dda8a131ea4d9017
CLEAN

Report: https://gist.github.com/Benoit9/2ea8b7f1f139b1bd16fc

**Comment by arkpar** [comment]
Same as #2109, but thanks for reporting
