### ISSUE TITLE
AlethZero does not update the block chain on OS X when display is off

### ISSUE THREAD

**Issue by Benoit9** [ethereum/cpp-ethereum#2182]
When display turns off (as specified in the Energy Saver System Preferences), AlethZero does not download the latest blocks. It starts to catch up as soon as the display goes back on (and the app window is visible).

**Comment by uberlaufer** [comment]
i was syncing the blockchain with AlethOne v1.1.4 on MacBook Air OSX 10.10.5,
starting yesterday 10 pm, leaving it running all night,
then looked at it again today 10 pm, and from midnight until now the syncing was quite discontinuous, only really picking up again now that i actually checked it again...

i'd guess the reasons are my energy saver settings, i had the following enabled:
- Put hard disks to sleep when possible
- Wake for network access
- Enable Power Nap while plugged into a power adapter


see http://pastebin.com/kbje8Mxa for the whole log,
a summory of which is this:

200024	23:00 
475763 	00:00 (275739.0/h)
484642	01:00 (008879.0/h)
488829	03:00 (002093.5/h)
494604	05:00 (002887.5/h)
499762	07:00 (002579.0/h)
501890	08:00 (002128.0/h)
503078	09:00 (001188.0/h)
506074	11:00 (001498.0/h)
508420	13:00 (001173.0/h)
513611	14:00 (005191.0/h)
519730	15:00 (006119.0/h)
524176	17:00 (002223.0/h)
529018	19:00 (002421.0/h)
533207	20:00 (004189.0/h)
539836	22:00 (003314.5/h)
766862	23:00 (227026.0/h)

**Comment by bobsummerwill** [comment]
AlethZero has been discontinued.   Closing issue.   Will never be addressed.
