### ISSUE TITLE
Mix 'edit transaction' populates bytes32 function parameters incorrectly

### ISSUE THREAD

**Issue by aeronbuchanan** [ethereum/cpp-ethereum#2194]
When a transaction that involves a contract function call with parameters of bytes32 is edited, the edit dialogue populates the parameter fields with the wrong form of the values.

E.g. 
bytes32 key = "Hello"
appears as: "Hello" 0x48656c6c6f0000000...
raising the error "Some parameters are invalid: bytes32 should not contain more than 32 characters"

**Comment by chriseth** [comment]
Note that eventually, it should be possible to use strings and hex as input format for bytesX types.

**Comment by arkpar** [comment]
@chriseth This is already supported. Use double quotes for strings, 0x prefix for hex
