### ISSUE TITLE
JSConsole not building

### ISSUE THREAD

**Issue by youlian** [ethereum/cpp-ethereum#2213]
clone, compile...

JSConsole.cpp:42:109: error: no matching function for call to \u2018dev::WebThreeStubServer::WebThreeStubServer(jsonrpc::AbstractServerConnector&, dev::WebThreeDirect&, const std::shared_ptr<dev::eth::AccountHolder>&, std::vector<dev::KeyPair>)\u2019
  m_jsonrpcServer.reset(new WebThreeStubServer(*m_jsonrpcConnector.get(), _web3, _accounts, vector<KeyPair>()));

**Comment by debris** [comment]
fixed in latest develop
