### ISSUE TITLE
eth catches up when restarted then slowly lags behind and stops updating

### ISSUE THREAD

**Issue by Benoit9** [ethereum/cpp-ethereum#2218]
I have observed this between 10 and 20 times (killing/restarting) over the last few days with multiple develop versions (currently 4e3d24a).

eth (CLI, Ubuntu) quickly but briefly catches up with the latest blocks when its started. Then it slowly lags behind and stops getting new blocks altogether. If miners are attached, it slowly mines its own fork.

This may be exacerbated to the slow block propagation, but it clearly does something at startup that it does not do later on.

**Comment by LefterisJP** [comment]
Should be fixed now. Make sure you build with the latest develop that contains https://github.com/ethereum/cpp-ethereum/pull/2198

**Comment by Benoit9** [comment]
It does seem better, but it is not clearly solved. Client still lags behind by more than a block or two.

**Comment by LefterisJP** [comment]
Does it ever get stuck? It could be some network issues we are experiencing or something. I believe Arkadiy is going to refactor that code a bit more soon.

**Comment by Benoit9** [comment]
Not stuck, but constantly lagging by several blocks. Sure, it could be the
network issues, but there may be more to it.
