### ISSUE TITLE
Multiple instances of a struct inside another struct causes "recursive struct" compiler error. 

### ISSUE THREAD

**Issue by dennismckinnon** [ethereum/cpp-ethereum#2223]
Minimal test case:

```
contract test {
	struct inner {
		uint temp;
	}

	struct outer {
		inner innerone;
		inner innertwo;
	}
}
```

compiling this gives the error:
```
test.sol:2:2: Parser error: Recursive struct definition.
	struct inner {
 ^
Spanning multiple lines.
```

commenting out the `inner innertwo;` line removes this message. I should be able to create a structe which has two copies of another struct within it shouldn't I?

**Comment by dennismckinnon** [comment]
Also the error message is unhelpful since this is not a recursive definition.

**Comment by chriseth** [comment]
Seems to be a bug in the implementation that checks for recursive struct definitions.
