### ISSUE TITLE
Mix: *.sol files should be renamed after contract name

### ISSUE THREAD

**Issue by step21** [ethereum/cpp-ethereum#2247]
So currently in the mix I am using - develop with designDeubgPanel branch from Yann - when I add a new contract file, it renames inside Mix as soon as I name the contract, but on the file level this is not represented but instead there is contract[1 - n].sol As unfortunately we still have to deal with files for git commits and so on, would be great if there would be an option to directly rename those if the contract is renamed or at least rename them manually in the GUI, so that it is not necessary to edit the .mix file by hand.

**Comment by gavofyork** [comment]
Please move all mix issues to [the Mix Issues repo](https://github.com/ethereum/mix/issues).
