### ISSUE TITLE
seg fault during blockchain download

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/cpp-ethereum#2251]
backtrace: https://gist.github.com/CJentzsch/94b39940995ff3a28ba0

**Comment by CJentzsch** [comment]
Here another extended back trace: https://gist.github.com/CJentzsch/c24f82be168e1f7d5a07
Its rather lenghty. But we see that he starts a lot of threads before segfaulting.

**Comment by arkpar** [comment]
should be fixed in develop
