### ISSUE TITLE
dev::h256::ref::copyTo(dev::bytesRef)  wont work

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#2252]
dev::h256::ref::copyTo(dev::bytesRef out)
I have this function failing to copy the contents of bytes vector. 
See the commit with test below.

https://github.com/winsvega/cpp-ethereum/commit/30890121c73a647f97b5322118a68cce5fb3f11a

**Comment by CJentzsch** [comment]
The target need to have the size of the source in order for the copyTo to work.

**Comment by winsvega** [comment]
Nope the size wont really solve the issue.
I will investigate more.

https://github.com/ethereum/cpp-ethereum/pull/2259/files

**Comment by winsvega** [comment]
ok. you were right. it is due to the buffer size. 
some changes need to be done to fix the core code accordingly. 
this seems to be the issue of stPreCompiledContracts from transaction CALL
