### ISSUE TITLE
output when calling preCompiledContracts from transaction

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#2270]
so debugging my issue I noticed that m_ext vm class is not being initialized when I am sending a transaction with data to a preCompiledContract
https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/Executive.cpp#L269

thus it will never reach a code in this function:
https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/Executive.cpp#L316

so there will be no output printed from the contract

**Comment by chfast** [comment]
Yes, it looks strange but it is ok.

When you call Executive::call it will report if Executive::go should be called after. In case of precompiled contracts it is not needed, they are executed in Executive::call.

Making this interface user friendly is another story.

**Comment by winsvega** [comment]
Anyways right now if I call preCompiledContract from a transaction I won't get any output.
It was not like that two-three weeks ago, so smth has changed in a way that should not.
PreCompiledContracts should return output if called from a transaction.

**Comment by winsvega** [comment]
the 'out' was disabled.
