### ISSUE TITLE
Alethzero crashes on "Opened Blockchain DB"

### ISSUE THREAD

**Issue by VivaLaPanda** [ethereum/cpp-ethereum#2274]
OS: Windows 7
Version: Supposedly newest binary from [https://github.com/ethereum/cpp-ethereum/wiki/Installing-clients

Pretty simple, whenever I try to launch, the alethzero.exe goes to Opening BlockchainDB, and then fails to respond.

Here are some system info: 
http://pastebin.com/N1vzv1iF
http://pastebin.com/JxmtwM49

**Comment by arkpar** [comment]
Fixed in latest
