### ISSUE TITLE
AlethZero crash while syncing blockchain

### ISSUE THREAD

**Issue by Quiark** [ethereum/cpp-ethereum#2294]
OS X 10.10.3

Today's version from
https://build.ethdev.com/builds/OSX%20C%2B%2B%20GUI%20develop%20branch/AlethZero-OSX-latest.dmg

AlethZero/v0.9.27/Release/Darwin/clang/int
aceecf65b1a786e82b72155b27dc239840ce6499
CLEAN

Actions:
* started from the .dmg
* I think I had some old blockchain, after  a while I nuked it and started to download again

crashlog:
http://hastebin.com/efemesipey.avrasm

**Comment by Quiark** [comment]
Maybe it's caused by some outdated files in `.ethereum`, I've nuked them all and trying again.

**Comment by Quiark** [comment]
Um, this time it got to 200k or so but then crashed somewhere else :cry: 

http://hastebin.com/ayunekoleb.avrasm

**Comment by arkpar** [comment]
The first crash looks to be fixed in latest develop. The second is probably caused by running out of memory.  Please reopen if it still crashes with the latest version.

**Comment by Quiark** [comment]
I think I got another crash http://hastebin.com/oliqosokiv.avrasm somewhere around block 200 000. After restarting I got all the way to 550 000+, then got bored :)

It's this version
AlethZero/v0.9.30/Release/Darwin/clang/int
9f66e20405f2e175e71e0b1888d0874f4489eec6
CLEAN
