### ISSUE TITLE
solc variable scope error in for loop

### ISSUE THREAD

**Issue by danielnovy** [ethereum/cpp-ethereum#2304]
Just got a weird behavior in solc compiler. If you have two loops of format `for (uint i = 0; i < x; i++) {` in the same scope, the compiler throws a `Identifier already declared` for the second `uint i = 0`. In other words, the compiler thinks that the variable `i` is outside the scope of the for loop.

Test contract:
```
contract test {
    function x() {
        for (uint i = 0; i < 1; i++) {
        }
        for (uint i = 0; i < 1; i++) {
        }
    }
}
```

solc result:
```
test.sol:5:14: Declaration error: Identifier already declared.
        for (uint i = 0; i < 1; i++) {
             ^--------^
The previous declaration is here: test.sol:3:14: 
        for (uint i = 0; i < 1; i++) {
             ^--------^
```

**Comment by chriseth** [comment]
Solidity inherited the scoping rules from JavaScript. At some point, we will also introduce the `let` keyword to declare variables with block-scope.
