### ISSUE TITLE
ethminer reporting a fraction of the mining hash

### ISSUE THREAD

**Issue by conradjohnson** [ethereum/cpp-ethereum#2306]
Normally get 23+ MH/s but getting this for a R9 290:
 ℹ  18:24:10|ethminer  Mining on PoWhash #74fab611… : 12184428 H/s = 91553792 hashes / 7.514 s
  ℹ  18:24:10|ethminer  Mining on PoWhash #74fab611… : 12183236 H/s = 97648640 hashes / 8.015 s
  ℹ  18:24:11|ethminer  Mining on PoWhash #74fab611… : 12184108 H/s = 103759872 hashes / 8.516 s
  ℹ  18:24:11|ethminer  Mining on PoWhash #74fab611… : 12183067 H/s = 109854720 hashes / 9.017 s
  ℹ  18:24:12|ethminer  Mining on Po

and this for a 7990 (one of the cores) which normally gets 18 MH/s for a single of it's core:
18:24:55|ethminer  Mining on PoWhash #1539dcc5… : 6117129 H/s = 21446656 hashes / 3.506 s
  ℹ  18:24:55|ethminer  Mining on PoWhash #1539dcc5… : 6116911 H/s = 24510464 hashes / 4.007 s
  ℹ  18:24:56|ethminer  Mining on PoWhash #1539dcc5… : 6118098 H/s = 27574272 hashes / 4.507 s
  ℹ  18:24:56|ethminer  Mining o

**Comment by LefterisJP** [comment]
Thank you for reporting. We are aware of the issue. It concerns some recent changes to the locking mechanism of the OpenCL miner and the surrounding code. We will investigate and fix as soon as possible.

**Comment by LefterisJP** [comment]
If this still persists please open another issue
