### ISSUE TITLE
ethminer crash on ethash_cl_miner::getDevices

### ISSUE THREAD

**Issue by Genoil** [ethereum/cpp-ethereum#2314]
For some vague reason all my CUDA installs settle on opencl platform id 1. On one system I got AMD APP on 0 (weird, the system has never had any AMD in it), on the other Intel OpenCL (fair enough). Don't know why, don't care either, I want CUDA. I used to be able to specify "--opencl-platform 1" (heck that's my own PR), but my ethminer crashes on:

ethash_cl_miner::getDevices:108

```
	_platforms[platform_num].getDevices(
		s_allowCPU ? CL_DEVICE_TYPE_ALL : ETHCL_QUERIED_DEVICE_TYPES,
		&devices
	);
```

when platform_num = 0. when I pass 1 (i.e, start the search loop on 1), it all works fine.

Now that's probably got something to do with my system. But it would be nice that if I specify a particular platform on the command line, it wouldn't try getting all this info from platforms I don't want anyway.

**Comment by LefterisJP** [comment]
So let me see if I understand correctly.

You have 2 platforms at indices 0 and 1.
The one you are interested in is at index 1.

By default platform number is 0 and then you get a segfault. If you specifcy `--open-cl-platform 1` everything works fine?

**Comment by Genoil** [comment]
no, it will still crash. the getDevices call iterates over all platforms regardless of what was specified at the cmd line. when platform_num is 0, it tries to get Devices from my platform 0, which in this case, is some rogue install of AMD APP (i don't know how it got there...it's a reasonably fresh install.)

my suggestion is, when the user specifies --opencl-platform at the command line, the code should completely ignore any other opencl platform present.
