### ISSUE TITLE
'solc --combined-json ast' is very slow

### ISSUE THREAD

**Issue by ralph-pichler** [ethereum/cpp-ethereum#2319]
Using 'solc --combined-json ast' with the following contract takes up to 18s to compile.
However 'solc --ast stdout' finishes instantly. 
Using '--combined-json asm,binary,json-abi,natspec-dev,natspec-user,opcodes,sol-abi' finishes instantly as well.

contract slow {
    function func (address a, address b, address c, address d) {
        a = b;
        c = d;
    }
}

**Comment by chriseth** [comment]
I cannot observe this effect. Which system are you using? Are you calling solc by specifying a file or do you use stdin to supply it?

**Comment by ralph-pichler** [comment]
Still having the same issue (commit 5440ee64a95ac2a4cf38f9f0280f4200e7371680).

It happens in both cases (file or stdin).

I tested it on OSX 10.10.3

**Comment by ralph-pichler** [comment]
Looks like the issues was with an old libjsoncpp. After updating it to the latest version, the issue is gone.

**Comment by LefterisJP** [comment]
This is interesting. Can you report at which libjsoncpp version you observed the offending behaviour?

**Comment by ralph-pichler** [comment]
Unfortunately I have overwritten all the old files already, so I can't check anymore, but it was at least a few months old.
