### ISSUE TITLE
'solc --natspec-dev' crashes when documenting nonexistent argument

### ISSUE THREAD

**Issue by ralph-pichler** [ethereum/cpp-ethereum#2320]
Using the following contract solc aborts with:
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<dev::solidity::DocstringParsingError>: std::exception
Abort trap: 6

contract crash {
	/// @param arg0 argument does not exist
	function func () {
	}
}

**Comment by chriseth** [comment]
Thanks for reporting, we are already working on it in #2105.
