### ISSUE TITLE
Feature request: Solc named output files or output directory flag

### ISSUE THREAD

**Issue by androlo** [ethereum/cpp-ethereum#2335]
Would be nice if output files could be named so it becomes easier to put them in a different folder then the sources. Would be especially useful in makefiles.

**Comment by chriseth** [comment]
As part of https://www.pivotaltracker.com/n/projects/1189488/stories/93978600 , it is planned to name a specific output directory for all files to be put in.

**Comment by androlo** [comment]
thanks. didn't see that.
