### ISSUE TITLE
Invariant failed

### ISSUE THREAD

**Issue by CJentzsch** [ethereum/cpp-ethereum#2365]
invariant failed here: https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/BlockChainSync.cpp#L783

backtrace: https://gist.github.com/CJentzsch/08c6e2c765ae6deefa50

this happend today (2nd July) on latest develop: commit 56ed8a920702169ad1a2e9e39acb29ea506e6dce

**Comment by arkpar** [comment]
fixed in latest
