### ISSUE TITLE
solidity logo / swag

### ISSUE THREAD

**Issue by androlo** [ethereum/cpp-ethereum#2382]
is there one? i did not find.

also swag.

this is important. please just throw us something. some ascii art or w/e. as long as it's official.

**Comment by LefterisJP** [comment]
Hehe ... nothing as of now but yeah I also agree and like the idea.

Ofcourse we are a little bit pressed with more important release related things right now but it's a good idea to have some solidity swag.

**Comment by androlo** [comment]
Of course. Great progress with the language + tools (i use it all the time). Just wanted to raise the issue. It'll be nice with a logo to put in third party stuff. Working on some solidity unit testing and build automation libraries for javascript myself.
