### ISSUE TITLE
solc JSON ABI is not JSHint compliant

### ISSUE THREAD

**Issue by kejace** [ethereum/cpp-ethereum#2395]
In particular, it should use single-quotes and space after comma.

**Comment by chriseth** [comment]
Could you please elaborate on why the json abi should be JSHint compliant?
Concerning single quotes: It is json, so it cannot use single quotes.
Concerning space after comma: We do not use any additional whitespace.

**Comment by kejace** [comment]
Sometimes one uses the resulting ABI through copy-and-paste within a
javascript file. I guess I should keep it as a separate JSON and parse it
instead. I understand now that the issue I raised is more of a design
choice. Feel free to close.
