### ISSUE TITLE
Solidity feature request: macros

### ISSUE THREAD

**Issue by nmushegian** [ethereum/cpp-ethereum#2437]
I want this:

    #define PROD false
    #define DEFAULT(TYPE, ADDR) #if PROD TYPE(ADDR) #else new TYPE() #endif
    #define LOG(what) #if PROD ; #else log(what) #endif

and so on. Don't tell me it's unsafe, I'm gonna use gcc to do it if you don't!

**Comment by debris** [comment]
if macros are considered I would suggest something like rust's [`macro_rules!`](http://rustbyexample.com/macros.html)

```rust
// This is the simplest macro, `say_hello` is the name of the macro
macro_rules! say_hello {
    // `()` indicates that the macro takes no argument
    () => (
        // the macro will expand into the contents of this block
        println!("Hello!");
    )
}
```

**Comment by chriseth** [comment]
Yes, I would also prefer a token-based macro system like the one used by rust.

**Comment by LefterisJP** [comment]
+1 for native macros instead of preprocessor based. Rust's macros are not particularly nice though, we could do better.

**Comment by LianaHus** [comment]
This issue has been moved to ethereum/solidity repository 
https://github.com/ethereum/solidity/issues/10
