### ISSUE TITLE
ethminer: improve logs about a found solution

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#2440]
It would be nice to have logs about a found solution with higher priority (lower level) than normal operational logs ethminer is throwing away. Currently both occupy the same `cnote` level. I would lower the other stuff.

**Comment by LefterisJP** [comment]
That would require ethminer to actually use our logging framework, so introduce a dependency to our devcore

**Comment by chfast** [comment]
The logs are here: https://github.com/ethereum/cpp-ethereum/blob/develop/ethminer/MinerAux.h#L512

**Comment by LefterisJP** [comment]
Something like this https://github.com/ethereum/cpp-ethereum/pull/2443/?

**Comment by chfast** [comment]
Almost.

**Comment by LefterisJP** [comment]
Closing this since the PR got merged.
