### ISSUE TITLE
X crashes when mining with ethminer

### ISSUE THREAD

**Issue by Phistr90** [ethereum/cpp-ethereum#2449]
X crashes when mining with the newest ethminer commit, although I use the --cl-extragpu-mem flag.
After a short time it shows vertical stripes in the colour of the background and freezes totally.
I could my rig without X of course, but I guess that's not an option for most casual users.

System:
Ubuntu 14 trusty
multi gpu rig: 3x r9 280x, 1x 7950

I try to reproduce the problem with a single gpu only and will report.
What kind of logs are needed?

**Comment by LefterisJP** [comment]
How much memory do your GPU have and what value do you provide to `--cl-extra-gpu-mem`?

**Comment by subtly** [comment]
@Phistr90 A few bugs were fixed. Is it still crashing?

**Comment by Phistr90** [comment]
Solved this problem by switching gpus. maybe just my configuration... cant reproduce on other rig.

**Comment by Phistr90** [comment]
If noone else has this problem, i would consider it as solved.
