### ISSUE TITLE
solc --sol-abi file clobbers the original source

### ISSUE THREAD

**Issue by tymat** [ethereum/cpp-ethereum#2450]
It should accept an argument for the target filename rather than overwriting an existing solidity source file.

**Comment by chriseth** [comment]
This will be handled as part of a general overhaul of the commandline interface.

**Comment by LianaHus** [comment]
https://github.com/ethereum/cpp-ethereum/pull/2528#issuecomment-123346054

**Comment by LianaHus** [comment]
fixed in https://github.com/ethereum/cpp-ethereum/pull/2528#issuecomment-123346054
