### ISSUE TITLE
Build fails on OSX 10.9.5

### ISSUE THREAD

**Issue by keo** [ethereum/cpp-ethereum#2451]
Tried to install cpp-ethereum from homebrew without success. Make failed at linking libwhisper with `clang: error: no such file or directory: '../secp256k'`

I cloned the git repo and started building from source (from master).

Here are the logs: https://gist.github.com/keo/79ebd0ad924025b3e880 Looks like here it fails on something else, related to clang.

CPU: dual-core 64-bit penryn
OS X: 10.9.5-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
Clang: 6.0 build 600
X11: 2.7.5 => /opt/X11

**Comment by subtly** [comment]
Thanks for reporting. Fix pending PR.
