### ISSUE TITLE
Proper -DBUNDLE=default processing for the build system

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/cpp-ethereum#2459]
The build system currently sets the default options in the [beginning of CmakeLists.txt](https://github.com/ethereum/cpp-ethereum/blob/develop/CMakeLists.txt#L27) and we use the fake value `-DBUNDLE=default` to specify that these are the defaults we need. 

This means that any value given to the cmake argument BUNDLE is taken as default. It can even be `-DBUNDLE=dsadasd`. It would _nice_to_have_ if we have a proper default check and throw an error if an illegal bundle value is given.

**Comment by subtly** [comment]
To do this also means for it to actually accept other -DOPTIONS when -DBUNDLE is used. Currently when -DBUNDLE is used it overrides options.

**Comment by LefterisJP** [comment]
Yes I am aware of that. This is why this is a "good to have" enhancement for when we rehaul/improve the build system. Nothing urgent.

**Comment by chfast** [comment]
I would like to have a bundle for software releases? "release" is not the best name as it interferes with "release" build type. Maybe "stable"?

**Comment by gavofyork** [comment]
done
