### ISSUE TITLE
solc:  Need clarity about when solc emits STOP vs RETURN vs exceptions

### ISSUE THREAD

**Issue by nmushegian** [ethereum/cpp-ethereum#2469]
I recall reading that unrecognized function signatures cause a STOP operation, and that ends execution and applies the transaction state changes. Is that right? Do I have to do this:

    contract Safe {
        function() { 
            1/0; // throw somehow
        }
    }

If so that is terrible =[

Can we get a compiler mode which is very generous with using exceptions so we can be safe calling our own contracts?

I'm really hoping the evm doesn't have to change to make STOP an implicit return or if there was a try-like mechanism to prevent your callees from stopping you..

Can you point me to documentation? Hoping I just misunderstood how this contraption works

**Comment by chriseth** [comment]
Moved to the forum: https://forum.ethereum.org/post/editdiscussion/2451

**Comment by nmushegian** [comment]
public link https://forum.ethereum.org/discussion/2451/exceptions-in-solidity-stop-vs-return
