### ISSUE TITLE
Function is returning inconsistent values with the same parameter.

### ISSUE THREAD

**Issue by lumichael94** [ethereum/cpp-ethereum#2483]
Hello, I'm running into some trouble with this code below. I've narrowed it down to the array declaration where if I declare uint[1], it causes function calc1 to return drastically different results than if I used uint[]. Notice that I don't actually use the array for anything. My goal is to have function calc1 return the same results as calc2. I'm using the most updated version of pyethereum and solc. Any thoughts?

main.sol  

      contract helperContract {
          function justReturn(uint x) returns(uint);
        }

        contract MarketsContract {

          event Log(uint);

          event LogArray(uint[]);

          event LogAddress(address);

          /* external contracts*/
          helperContract help = helperContract({helper_address});

        function calc_1() returns (uint){
            uint[1] share_distribution;
            share_distribution[0] = 0;
            return calc_2();

          }
          function calc_2() returns (uint){
            uint b = calc_3(2);
            Log(8888);
            Log(b);
            return b;
          }

          function calc_3(uint n) returns(uint){
                return help.justReturn(n);
          }
        }

helper.sol

        contract helperContract {

          event Log(uint);

          event LogArray(uint[]);

          event LogAddress(address);

          function justReturn(uint x) returns(uint){
            return x;
          }
        }

test.py

        from unittest import TestCase, main
        from ethereum import tester as t
        from rlp.utils import encode_hex
        from ethereum.tester import keys, accounts

        class TestContract(TestCase):

            def setUp(self):
                self.s = t.state()
                t.gas_limit = 3141592
                self.coinbase = encode_hex(self.s.block.coinbase)

                # create contracts
                helper_code = open('helper.sol').read()
                self.helper_contract = self.s.abi_contract(helper_code, language='solidity')
                helper_contract_address = '0x' + self.helper_contract.address.encode("hex")

                main_code = open('main.sol').read().replace('{helper_address}', helper_contract_address)
                self.main_contract = self.s.abi_contract(main_code, language='solidity')

            def test_1(self):
                print 'test 1: '
                self.main_contract.calc_1()

            def test_2(self):
                print 'test 2: '
                self.main_contract.calc_2()

        if __name__ == '__main__':
            main()

**Comment by chriseth** [comment]
Please use `uint[1] memory` to declare a temporary array that is not stored in storage, otherwise it will point to storage and be treated as a "dangling storage null pointer".
Sorry, the compiler does not yet warn about such cases.
