### ISSUE TITLE
Solidity: boolean operators should not apply to integers

### ISSUE THREAD

**Issue by chriseth** [ethereum/cpp-ethereum#2496]
This should create a type error:
```js
contract x {
    function f() {
        uint x = 1;
        uint y = 2;
        uint a = x || y;
    }
}
```

**Comment by M1Reeder** [comment]
I think the ethereum tutorial for tokens makes this mistake https://www.ethereum.org/token.

The bit that matters:
```
  function token(uint supply) {
        coinBalanceOf[msg.sender] = (supply || 10000);
  }
```
Solidity throws ```Operator || not compatible with types uint256 and int_const 10000```

wrapping with ```uint(10000)``` gives ```Type error: Operator || not compatible with types uint256 and uint256```

**Comment by chriseth** [comment]
The example is fixed now.
