### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range' 

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#2501]
Ubuntu 15.04.  8gb ram, core i3 (it's the mining rig from the tutorial)

Fresh install, never installed eth prior on that machine

eth -j -i -b was used to start

Climbs the chain up to 534608 then crashes with this log:

http://pastebin.com/3LjW1vFg

**Comment by chriseth** [comment]
Do you still have the core dump file?

**Comment by chriseth** [comment]
Closing as duplicate of #2646
