### ISSUE TITLE
Program received signal SIGBUS, Bus error

### ISSUE THREAD

**Issue by stephantual** [ethereum/cpp-ethereum#2506]
ubuntu 15.04

log: http://pastebin.com/zKZ7qRnH

backtrace: http://pastebin.com/tTYxMKnP

**Comment by arkpar** [comment]
crashed in leveldb. Ran out of disk or memory perhaps?

**Comment by stephantual** [comment]
That error could be linked to SSD issues I had around the same time. I'm currently rebuilding with a different SSD brand in order to test. Will revert back.

**Comment by gavofyork** [comment]
closing - reopen if it persists after hardware sorted.
