### ISSUE TITLE
DVE-2015-0101 Insecure File Permissions in eth CLI

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#2509]
Severity: Low
Risk: Medium
Complexity: Low
Access Vector: Local

System local attackers can access the node key and other sensitive Ethereum configuration data stored in the configuration directory because the directory and the files therein are readable by all users.

**Comment by subtly** [comment]
Default files permissions are set based on the user's shell environment (see: man 2 umask) and a concerned user would create a dedicated service account with a secure umask configuration. As this is a system configuration, it is out of scope, however we should consider creating files with custom permissions when key material is stored.

**Comment by chriseth** [comment]
The same issue also applies to the private keys, where we should certainly ensure that they are not world-writable regardless of the system settings.

**Comment by kaeptnjoda** [comment]
Renamed issues according to naming convention for audit findings
