### ISSUE TITLE
AlethZero quit unexpectedly - OSX Mavericks/Yosemite

### ISSUE THREAD

**Issue by glensimister** [ethereum/cpp-ethereum#2516]
Problem keeps persisting on macbook pro on both OSX Mavericks and Yosomite.
When i double click the icon it just hangs for a couple of minutes and then gives me the above error. 

Thanks

**Comment by debris** [comment]
is there anything else besides 'AlethZero quit unexpectedly'?

**Comment by glensimister** [comment]
Mac specs...

Processor: 2.4 GHz Intel Core 2 Duo
Memory: 4 GB 1067 MHz DDR3
OSX: 10.10.3

What info do you need? 

I managed to install it on a n imac at work. Perhaps it is conflicting with something else on my mac. I'm sorry, haven't got time to look further into this.

**Comment by chriseth** [comment]
Could you run it inside a terminal and/or send us the log?
