### ISSUE TITLE
develop: windows mining fails

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#2534]
Hash rate shows zero and GPU load is zero, so no work is being done. It doesn't matter whether it is 1 GPU or 2. And --list-devices properly lists available devices.

'''
C:\code\cpp-ethereum\build\ethminer\Debug>ethminer.exe -F http://192.168.1.42:8545 -t 2 --opencl-device 0,1 -G
[OPENCL]:Found suitable OpenCL device [Tahiti] with 3221225472 bytes of GPU memory
  D  00:03:43|main  start()
miner  00:03:43|main  Getting work package...
miner  00:03:43|main  Grabbing DAG for #7e7d8befΓÇª
miner  00:04:08|main  Got work package:
  i  00:04:08|<unknown>  Loading full DAG of seedhash: #5a46dd85ΓÇª
miner  00:04:08|main    Header-hash: b453cbd82d8c9b2119e3e88cecdcab96253d92619abcf306c6e81613f0dcfaae
miner  00:04:08|main    Seedhash: 7e7d8bef9d86983accafa937aed08042391d6f435bc640e50a9c38927de9b299
miner  00:04:08|main    Target: 000000004eafd12c6550669be58b22484b34df3c7e96267dd12172222368cf6e
  D  00:04:08|main  Farm::setWork()
miner  00:04:08|main  Mining on PoWhash #b453cbd8ΓÇª : 0 H/s = 0 hashes / 0.54 s
miner  00:04:32|main  Got work package:
miner  00:04:32|main    Header-hash: a2109c35451572ce9f64fe4a620e9cad57fd641edb415e8a5931636d55c45e8f
miner  00:04:32|main    Seedhash: 7e7d8bef9d86983accafa937aed08042391d6f435bc640e50a9c38927de9b299
miner  00:04:32|main    Target: 000000004eafd3a1e48ee650d742ca2b62022f4b0ce06af13a29960e1dc35c34
  D  00:04:32|main  Farm::setWork()
  i  00:04:32|<unknown>  Full DAG loaded
miner  00:04:33|main  Mining on PoWhash #a2109c35ΓÇª : 0 H/s = 0 hashes / 0.5 s
miner  00:04:33|main  Got work package:
miner  00:04:33|main    Header-hash: 3975e4ea030ded0dbf14b7de6d543af45300d509784f2298c38729ee9106d285
miner  00:04:33|main    Seedhash: 7e7d8bef9d86983accafa937aed08042391d6f435bc640e50a9c38927de9b299
miner  00:04:33|main    Target: 000000004ec3834799adb1026e24f9d334e18cb9b09d029364767a02a20d15bf
  D  00:04:33|main  Farm::setWork()
miner  00:04:33|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 0.5 s
miner  00:04:34|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 1.01 s
miner  00:04:34|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 1.51 s
miner  00:04:35|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 2.63 s
miner  00:04:36|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 3.13 s
miner  00:04:36|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 3.63 s
miner  00:04:37|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 4.13 s
miner  00:04:37|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 4.63 s
miner  00:04:38|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 5.13 s
miner  00:04:38|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 5.63 s
miner  00:04:39|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 6.13 s
miner  00:04:40|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 7.06 s
miner  00:04:40|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 7.56 s
miner  00:04:41|main  Mining on PoWhash #3975e4eaΓÇª : 0 H/s = 0 hashes / 8.06 s
miner  00:04:41|main  Got work package:
miner  00:04:41|main    Header-hash: 3ba09795d557543c5b3e47d1df038ac43f44b108f9fff75a5a6e4628bc3e9076
miner  00:04:41|main    Seedhash: 7e7d8bef9d86983accafa937aed08042391d6f435bc640e50a9c38927de9b299
miner  00:04:41|main    Target: 000000004ecd5cf3270671ffd75c7be60cfc871e0ae526bcf2f6d5bed8cb2e7c
  D  00:04:41|main  Farm::setWork()
miner  00:04:41|main  Mining on PoWhash #3ba09795ΓÇª : 0 H/s = 0 hashes / 0.5 s
miner  00:04:42|main  Mining on PoWhash #3ba09795ΓÇª : 0 H/s = 0 hashes / 1 s
miner  00:04:42|main  Mining on PoWhash #3ba09795ΓÇª : 0 H/s = 0 hashes / 1.5 s
miner  00:04:43|main  Mining on PoWhash #3ba09795ΓÇª : 0 H/s = 0 hashes / 2.45 s
miner  00:04:43|main  Got work package:
miner  00:04:43|main    Header-hash: 29999e8e0c119f4b565ad9d90aa128bb2fc385af0305508edcc5f8203272eeee
miner  00:04:43|main    Seedhash: 7e7d8bef9d86983accafa937aed08042391d6f435bc640e50a9c38927de9b299
miner  00:04:43|main    Target: 000000004ed737da16dce8c5a196b2babd29c653b3715d4d22c319bb440e33a0
  D  00:04:43|main  Farm::setWork()
miner  00:04:44|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 0.5 s
miner  00:04:44|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 1 s
miner  00:04:45|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 1.5 s
miner  00:04:45|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 2 s
miner  00:04:46|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 2.5 s
miner  00:04:46|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 3 s
miner  00:04:47|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 3.51 s
miner  00:04:47|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 4.01 s
miner  00:04:48|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 4.89 s
miner  00:04:49|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 5.39 s
miner  00:04:49|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 5.89 s
miner  00:04:50|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 6.39 s
miner  00:04:50|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 6.89 s
miner  00:04:51|main  Mining on PoWhash #29999e8eΓÇª : 0 H/s = 0 hashes / 7.39 s
'''

**Comment by LefterisJP** [comment]
Does this only happen on Windows? Have you checked it in any other OS? Since when does this happen? Has it only started occuring after the whizz branch merge? Or even before?

**Comment by LefterisJP** [comment]
I just checked in Ubuntu. This does not occur there. I get a proper hashrate when mining in Ubuntu. Haven't mined a block yet but hopefully it will.

I don't have a GPU enabled windows machine to test with if this is a Windows only issue.

**Comment by LefterisJP** [comment]
Alex I am closing this. After latest develop changes and #2564 this shoudl be fixed. If not then it's indeed a Windows specific issue. In which case please reopen and let's investigate this together.
