### ISSUE TITLE
mining block header streamed as array (should be list)

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#2538]
https://github.com/ethereum/cpp-ethereum/blob/develop/libethcore/EthashSealEngine.cpp#L62

Somewhere in this function blockheader and perhaps other data is being streamed as array
thus It will be thrown an exception as blockheader should be a list but A0 byte (160dec) (meanin array 32) received

**Comment by gavofyork** [comment]
??? please rephrase with example code and expected behaviour.

**Comment by winsvega** [comment]
this occurs when running testeth -t BlockChainTests --filltests 
this PR should fix this https://github.com/ethereum/cpp-ethereum/pull/2556
