### ISSUE TITLE
EC recover returns address for invalid sigs where pubkey is point at infinity

### ISSUE THREAD

**Issue by Gustav-Simonsson** [ethereum/cpp-ethereum#2544]
https://github.com/ethereum/tests/pull/94

This affects both txs and the precompiled EC recover contract.

YP Appendix E

**Comment by Gustav-Simonsson** [comment]
Go: https://github.com/ethereum/go-ethereum/blob/develop/core/vm/contracts.go#L107
The actual check in libsecp256k1 is at https://github.com/ethereum/go-ethereum/blob/master/crypto/secp256k1/secp256k1/src/ecdsa_impl.h#L219

cpp: https://github.com/ethereum/cpp-ethereum/blob/develop/libdevcrypto/CryptoPP.cpp#L289

**Comment by chriseth** [comment]
We use CryptoPP and libsecp256k1, but a very old version of it which does not include the check.
I guess we could either modify our copy of libsecpk256k1 locally or just update it.
For CryptoPP, I will add the check.

**Comment by chriseth** [comment]
Tried to update libsecp256k1 but ran into a lot of issues. Someone who imported it in the first place should perhaps take a look. @subtly @gavofyork ?

**Comment by chriseth** [comment]
This is still not fixed in our copy of libsecp256k1.

**Comment by CJentzsch** [comment]
tests are merged and failing! https://github.com/ethereum/tests/pull/94

**Comment by gavofyork** [comment]
fixed now.
