### ISSUE TITLE
Enum as output parameter return empty bytes array

### ISSUE THREAD

**Issue by yann300** [ethereum/cpp-ethereum#2570]
eth::Execution.output is q bytes array containing only empty values, for the first value of an enum. maybe we should return 0 instead

**Comment by chriseth** [comment]
I think this requires a deeper analysis. The source code returns 32 bytes and this would have certainly triggered some solidity unit tests to fail: They explicitly distinguish between 32 zero bytes and the empty byte array.

**Comment by gavofyork** [comment]
please rephrase with additional clarity.

**Comment by yann300** [comment]
if we have 
enum t
{
  value1,
  value2
}

function get() returns (t)
{
return t.value1;
}

get() returns 32 bytes of empty values instead of 0 bytes.

**Comment by gavofyork** [comment]
Please move all mix issues to [the Mix Issues repo](https://github.com/ethereum/mix/issues).
