### ISSUE TITLE
Parent issue for reducing `sha` count emitted by solc

### ISSUE THREAD

**Issue by nmushegian** [ethereum/cpp-ethereum#2584]
My understanding is that all `mapping`s are compiled into a storage lookup by concatenating the map name and keys, and using the sha3 as the storage key.

The gas price for sha3 is completely off (last I checked it was equal to CALL). If gas prices adjusted in 1.1 people are going to be mad their old contracts suddenly cost much more.

It is straightforward to compile a collection of 1d maps where the key space fits inside the storage space

Direct access to `storage` like in serpent would at least let users roll their own solution

**Comment by chriseth** [comment]
I am not sure where this issue leads to.
Mappings without the need for sha3 are on our backlog.
If your key is an integer, please consider using a fixed-size array, they do not need sha3.

Are you saying that sha3 is priced too cheap compared to its execution time? Why do you think so?

**Comment by nmushegian** [comment]
My napkin math said that to add 1 millisecond of cpu time you need to do sha3 less than 10 times.

I can't think of any other op that optimizes as badly. I'm thinking about servers that can hold all or all the most frequently used state in memory so CALL/STORE/CREATE/etc can be as fast as real VMs.

Yeah, the array trick makes this not important

**Comment by chriseth** [comment]
The prime optimisation goal for Solidity is gas costs. The compiler cannot make assumptions about how the EVM is implemented and there are at least three high-performing implementations that are really different.

The C++ implementation, for example, uses a sha3 implementation that takes about 30 microseconds for typical byte array lengths.

Closing as not specific enough.

**Comment by nmushegian** [comment]
> The prime optimisation goal for Solidity is gas costs.

This is very intimately linked with EVM implementations. There will be a fastest EVM implementation that is constrained by physics or slow-moving hardware design. So solidity compiler designers should consider such constraints.

You can't make sha3 faster. You can make very other op faster when your state is in memory.
