### ISSUE TITLE
Mix: doesn't start

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#2589]
os: 10.10.3
clang version: Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
branch/commit: develop e1d58ffafc73a995ffc5ed719794bb0694467a14

This is first time I started Mix on this machine. I installed all dependencies via homebrew, compiled mix manually and started it. I can see mix icon open in the dock (so it hasn't crashed, pic. 0), but nothing else happend.

(pic. 0)
<img width="117" alt="screen shot 2015-07-27 at 10 20 03" src="https://cloud.githubusercontent.com/assets/2613714/8901489/984dd256-3449-11e5-9a86-a760d00fdf03.png">

**Comment by arkpar** [comment]
can you start it via command line and get the logs?

**Comment by debris** [comment]
Tried, there are no logs.

**Comment by debris** [comment]
Update* 
When I started:
/mix/mix.app/Contents/MacOS/mix

I got logs:

```
objc[58924]: Class NotificationReceiver is implemented in both /Users/marek/projects/ethereum/cpp-ethereum/build/mix/mix.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets and /usr/local/Cellar/qt5/5.5.0/lib/QtWidgets.framework/QtWidgets. One of the two will be used. Which one is undefined.
QQmlApplicationEngine failed to load component
qrc:/qml/Application.qml:-1 File not found
```

**Comment by LianaHus** [comment]
@arkpar isn't this the same issue? as here https://github.com/ethereum/cpp-ethereum/issues/2588
