### ISSUE TITLE
VerifiedBlockRef failing without exception

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#2595]
and attemt to import mined block to blockchain 
m_blockchain->attemptImport(blockStream.out(), m_state.db());

cause failing somewhere in line (without any exception or debug information)
https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/BlockChain.h#L406

example code: http://pastie.org/10314409

**Comment by arkpar** [comment]
Check the return value of attemptImport
