### ISSUE TITLE
Mix: Graphic and design tweaks to deployment panel 1

### ISSUE THREAD

**Issue by kaeptnjoda** [ethereum/cpp-ethereum#2603]
*Align Deployment option on the LHS
Shift "Deployment options" "Account" and "Gas Price" and "Deplyment" cost to left 
*Introduce a horizontal line btw. contract to improve readability
* Remove repeated "Deploy" from list of contracts in scenario. Instead introduce head: Contracts to deploy
![image](https://cloud.githubusercontent.com/assets/8157688/8912250/a7c4442a-3491-11e5-84ce-feac7f403174.png)

**Comment by yann300** [comment]
in PR #2629
