### ISSUE TITLE
homebrew with --devel does not seem to install v8 dependency

### ISSUE THREAD

**Issue by KenKappler** [ethereum/cpp-ethereum#2607]
$ eth
dyld: Library not loaded: /usr/local/opt/v8-315/lib/libv8.dylib
  Referenced from: /usr/local/bin/eth
  Reason: image not found
Trace/BPT trap: 5

master branch is not effected.

**Comment by debris** [comment]
fix is waiting for merge [here](https://github.com/ethereum/homebrew-ethereum/pull/30)

**Comment by gavofyork** [comment]
fix merged
