### ISSUE TITLE
Mac OS X 10.10.4 brew install error

### ISSUE THREAD

**Issue by RCasatta** [ethereum/cpp-ethereum#2625]
brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/homebrew-ethereum
Error: No available formula for libjson-rpc-cpp (dependency of cpp-ethereum)

**Comment by debris** [comment]
did you run `brew update` before `brew install cpp-ethereum` ? If not, please do :)

**Comment by RCasatta** [comment]
correct, didn't update sorry :)
