### ISSUE TITLE
Problem with named anonymous function in Account.cpp.

### ISSUE THREAD

**Issue by xakkep9000** [ethereum/cpp-ethereum#2637]
https://github.com/ethereum/cpp-ethereum/blob/block/libethereum/Account.cpp#L36

In this case, anonymous function should be defined out of AccountMap dev::eth::jsonToAccountMap and refactored as inline function.

Wiki says:
[begin wiki quote]<<Anonymous functions can be used for containing functionality that need not be named and possibly for short-term use. Some notable examples include closures and currying.

Anonymous functions are a matter of style. Using them is never required; anywhere you could use them, you could define a separate normal function that accomplishes the same thing. Some programmers use anonymous functions to encapsulate specific, non-reusable code without littering the code with a lot of little one-line normal functions.>> [end wiki quote]

But in this case our anonymous function has got name and more than one line of code.

This anonymous function should be refactored as simple function in this cpp file for more readability.

HOWTO-Example:
inline u256 u256Safe(std::string const& s)
{
    bigint ret(s);
    if (ret >= bigint(1) << 256)
        BOOST_THROW_EXCEPTION(ValueTooLarge() << errinfo_comment("State value is equal or greater than 2**256") );
    return (u256)ret;
}

**Comment by LefterisJP** [comment]
This is a styling issue and the proposed fix does not solve anything.
