### ISSUE TITLE
Fix windows cmake jamming on boost_random

### ISSUE THREAD

**Issue by pompomJuice** [ethereum/cpp-ethereum#2639]
cmake fails on finding boost_random.

Update https://build.ethdev.com/builds/windows-precompiled/boost-1.55.0-x64.tar.gz

**Comment by pompomJuice** [comment]
![libboost_random-vc120-mt-1_55](https://cloud.githubusercontent.com/assets/1815319/8968397/2a8d23fc-363d-11e5-8e6b-02e89601bdd2.jpg)

For the impatient, just rename this file to .lib and copy it into your lib folder... poof cmake subverted.

**Comment by pompomJuice** [comment]
http://sourceforge.net/projects/boost/files/boost-binaries/1.55.0/boost_1_55_0-msvc-12.0-64.exe/download

**Comment by gavofyork** [comment]
i believe @debris fixed this around 12 hours ago?

**Comment by gavofyork** [comment]
fixed in latest.
