### ISSUE TITLE
[OS X] boost w/c++11 support not needed

### ISSUE THREAD

**Issue by taoeffect** [ethereum/cpp-ethereum#2644]
Going off of my exploration in #2643:

- The default (precompiled) version of boost 1.58 was successfully installed using Homebrew.
- I edited the cpp-ethereum brewfile to comment out the c++11 stuff

          depends_on 'boost' # => "c++11"
          depends_on 'boost-python' # => "c++11"

- I installed cpp-ethereum using `brew install ethereum/ethereum/cpp-ethereum --devel --build-from-source` as per the [the docs](https://github.com/ethereum/cpp-ethereum/wiki/Building-on-MacOS).
- I chose not to compile latest version of LLVM for EVMJIT support.

Since compiling boost takes insanely long, and llvm takes insanely longer, this should be unnecessary unless there is no other way around it.

At least `ethminer` ran fine (after I specified the opencl device, see #2643).

The docs and brewfile should be updated to reflect this. Asking that a custom version of boost be compiled should be removed if it is not necessary (perhaps relegated to an option like `--link-boost-c11`).

**Comment by gavofyork** [comment]
indeed, `ethminer` is designed not to need any of boost's non-header-only libraries, however, ethminer is very much a special case.

if you'd like to create a PR with an alternative, ethminer-only build, then i'd be happy to review.
