### ISSUE TITLE
Installing on Arch LInux

### ISSUE THREAD

**Issue by QM-Hacker** [ethereum/cpp-ethereum#2663]
So I've been having some issues building on a newly reinstalled arch machine.
After three days of troubleshooting, I figured I should reach out.

Here is what I have done: (the nvidia driver is already installed)
```
pacman -S opencl-nvidia opencl-headers cuda
pacman -Sy
pacman -S base-devel cmake scons clang llvm boost leveldb crypto++ qt5-base qt5-webengine qt5-quick1 jsoncpp miniupnpc libcpuid
```
I installed all base-devel packages except gcc since gcc-multilib is a requirement for lib32-flex

```
yaourt -S argtable libjson-rpc-cpp
```
returns error related to unable to validate package key for argtable
after running
```
pacman -S archlinux-keyring
```
the previous command installs the packages successfully

Next, I cloned from github and attempted to use cmake
```
git clone https://github.com/ethereum/cpp-ethereum
cd cpp-ethereum
git checkout develop 
mkdir build
cd build
cmake .. -DETHASHCL=1
```
The final line returns an error complaining that v8 can not be found. I then followed the suggestion in #2598 and installed v8-3.14.
```
yaourt -S v8-3.14
```
Running cmake ..-DETHASHCL=1 again returns the following error that I can't seem to fix
```
[cgeorgen@compute-node-1 build]$ cmake .. -DETHASHCL=1
-- ctest path: /usr/bin/ctest
 - CryptoPP header: /usr/include
 - CryptoPP lib   : /usr/lib64/libcryptopp.so
 - LevelDB header: /usr/include
 - LevelDB lib: /usr/lib64/libleveldb.so
-- Could NOT find rocksdb (missing:  ROCKSDB_INCLUDE_DIR ROCKSDB_LIBRARY) 
 - v8 header: /usr/include
 - v8 lib   : /usr/lib64/libv8.so
 - Jsoncpp header: /usr/include
 - Jsoncpp lib   : /usr/lib64/libjsoncpp.so
 - json-rpc-cpp header: /usr/include
 - json-rpc-cpp lib   : /usr/lib64/libjsonrpccpp-common.so;/usr/lib64/libjsonrpccpp-server.so;/usr/lib64/libjsonrpccpp-client.so
 - microhttpd header: /usr/include
 - microhttpd lib   : /usr/lib64/libmicrohttpd.so
 - microhttpd dll   : 
 - readline header: /usr/include
 - readline lib   : /usr/lib64/libreadline.so
 - miniupnpc header: /usr/include
 - miniupnpc lib   : /usr/lib64/libminiupnpc.so
 - gmp header: /usr/include
 - gmp lib   : /usr/lib64/libgmp.so
 - curl header: /usr/include
 - curl lib   : /usr/lib64/libcurl.so
 - cpuid header: /usr/include
 - cpuid lib   : /usr/lib64/libcpuid.so
 - opencl header: /usr/include
 - opencl lib   : /usr/lib64/libOpenCL.so
 - jsonrpcstub location    : /usr/bin/jsonrpcstub
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   regex
--   chrono
--   filesystem
--   unit_test_framework
--   program_options
--   random
 - boost header: /usr/include
 - boost lib   : /usr/lib64/libboost_thread.so;/usr/lib64/libboost_date_time.so;/usr/lib64/libboost_system.so;/usr/lib64/libboost_regex.so;/usr/lib64/libboost_chrono.so;/usr/lib64/libboost_filesystem.so;/usr/lib64/libboost_unit_test_framework.so;/usr/lib64/libboost_program_options.so;/usr/lib64/libboost_random.so
------------------------------------------------------------------------
--                  CMake Version                            3.2.3
-- CMAKE_BUILD_TYPE Build type                               RelWithDebInfo
-- TARGET_PLATFORM  Target platform                          Linux
-- BUNDLE           Build bundle                             
--------------------------------------------------------------- features
--                  Chromium support                         1
--                  Hardware identification support          TRUE
--                  HTTP Request support                     TRUE
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- NOBOOST          No BOOST macros in test functions        OFF
-- FATDB            Full database exploring                  ON
-- JSONRPC          JSON-RPC support                         ON
-- USENPM           Javascript source building               OFF
-- ROCKSDB          Prefer rocksdb to leveldb                OFF
-- FRONTIER         Default to the Frontier network          ON
------------------------------------------------------------- components
-- MINER            Build miner                              ON
-- ETHKEY           Build wallet tools                       ON
-- TOOLS            Build basic tools                        ON
-- SOLIDITY         Build Solidity language components       ON
-- SERPENT          Build Serpent language components        ON
-- GUI              Build GUI components                     ON
-- TESTS            Build tests                              ON
-- ETHASHCL         Build OpenCL components                  ON
-- JSCONSOLE        Build with javascript console            ON
-- EVMJIT           Build LLVM-based JIT EVM                 ON
------------------------------------------------------------------------

-- CXXFLAGS: -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -Werror -pedantic -DSHAREDLIB -fPIC  -fuse-ld=gold
CMake Error at evmjit/CMakeLists.txt:41 (message):
  No LLVM package found!


-- Configuring incomplete, errors occurred!
See also "/home/cgeorgen/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".
```
This error appears with multiple verions of v8 (3.14, 3.15, dev...).

Earlier on I was having problems after this step when running make -m# but I can no longer even get to that point. If anyone has managed to install this successfully on arch (or any derivative) or sees what I'm doing wrong, I would really appreciate the help.

I believe the problem lies with v8, javascript, and the GUI because I can successfully compile Genoil's CUDA fork, which lacks the v8 dependency, if I disable the gui when running cmake.

Thanks a bunch

**Comment by LefterisJP** [comment]
The v8 dependency you solved. You need either v8 3.15 or v8 3.14.
The LLVM dependency is a bit more difficult to address for now in ArchLinux. You can wait a few weeks until llvm3.7 is officially released there.

In the meantime you can either try to compile llvm from source or .. just add `-DEVMJIT=0` in the cmake configuration step.

**Comment by QM-Hacker** [comment]
Thanks for the suggestion! Adding ```-DEVMJIT=0``` worked and allowed me to both make and install everything.

It seems like the last problem I'm having is with the miner. Running ```ethminer -M -G``` to benchmark returns
```
ethminer: error while loading shared libraries: libethcore.so: cannot open shared object file: No such file or directory
```
But I check for the file that is supposedly missing I find it located in /cpp-ethereum/build/libethcore, any idea what this could be?

**Comment by LefterisJP** [comment]
Since you are building cpp-etherem you can also try running the cpp CLI client located under `./eth/eth` which has a GPU miner integrated.

This is a strange error you are getting with etminer. I am also running ArchLinux and I am in the latest develop branh tip. Are you sure that have latest develop pulled? 

Can you also re-specify the cmake configure step and the make step?

**Comment by QM-Hacker** [comment]
Here is exactly what I ran to install and compile
```
git clone https://github.com/ethereum/cpp-ethereum
cd cpp-ethereum
git checkout develop 
git pull
mkdir build
cd build
cmake .. -DETHASHCL=1 -DGUI=0 -DEVMJIT=0
make -j12
```

**Comment by QM-Hacker** [comment]
How do I run the miner from eth?

**Comment by LefterisJP** [comment]
`./eth/eth -G -m on` plus all the other arguments you need. Please read the onlne guides.

As for your ethminer problem, are you sure it compiled correctly? Are you sure you are in the latest develop?

**Comment by QM-Hacker** [comment]
So I've been working through the installation (and documenting everything along the way). I've resolved the errors with the shared libraries by copying them all over to a new directory and adding it to my path.

After updating my libOpenCL.so file, I am getting the following error after running ethminer

```
~./libdevcrypto.so: undefined symbol: _ZN3dev4sha3ENS_10vector_refIKhEE
```
Does anyone have any thoughts about this?

**Comment by LefterisJP** [comment]
Again this problem sounds really strange. There should be no need to move any shared files at all.

A few things to try.
1. `cd` into the cpp-ethereum directory

2. Make sure you are in latest develop.
   `git pull origin develop`

3. Totally remove all cmake build/cache files and build from scratch. 
    `rm -rf build && mkdir build && cd build && cmake .. -DEVMJIT=0 -DGUI=0


And on anothere note. I just re-read your original post. You wrote:
```
I installed all base-devel packages except gcc since gcc-multilib is a requirement for lib32-flex
```

Do you have a compiler installed? What does `gcc --version` or `g++ --version` return?

**Comment by QM-Hacker** [comment]
I have gcc-multilib. The system complains about lib32-flex if I were to replace it with gcc.

**Comment by LefterisJP** [comment]
All right, did you try pulling latest develop and rebuilding from scratch as I told you above? If that does not solve it for your I am really wondering what could be the problem. I have never seen such an error before, let alone on ArchLinux.

**Comment by Vermilingua** [comment]
Hi all,
trying to CMake on Arch doesn't provide me with a makefile, even though it seems to run correctly. The [CMake output is here](https://gist.github.com/52dab7af6f9a77e66208). Every directory in build/ is empty besides another empty dir titled CMakeFiles.

**Comment by LefterisJP** [comment]
@Vermilingua OpenCL is a requirement to build. Even if you don't have openCL capable graphics card you can simply get the [ocl-icd](https://www.archlinux.org/packages/extra/x86_64/ocl-icd/) package which acts as a loader of whatever actual OpenCL library you got. 

As per the [ArchLinux GPGPU wik](https://wiki.archlinux.org/index.php?title=GPGPU&redirect=no) you would also need [opencl-headers](https://www.archlinux.org/packages/?name=opencl-headers).

**Comment by Vermilingua** [comment]
Thanks, I feel like an idiot now. Works a charm.

**Comment by jencka** [comment]
I've gotten the 3.8.0 LLVM/Clang dependencies fulfilled on Arch by using the clang-svn & llvm-svn packages. I wasn't able to get the either to compile straight from the AUR, but I luckily found a repo (http://pkgbuild.com/~lcarlier/mesa-git/) that has binary builds.

**Comment by seyuf** [comment]
Need some help, neither eth -G nor etheminer -G are working. 
I followed suggestions above for the build with success
```
cmake .. -DGUI=0 -DETHASHCL=1
```
Anyway there are the issues im facing

```
./eth/eth: /opt/cuda/lib64/libOpenCL.so.1: no version information available (required by XXX/cpp-ethereum/build/libethash-cl/libethash-cl.so)
[OPENCL]:No OpenCL platforms found
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

```

lspci of my card

```
 01:00.0 VGA compatible controller: NVIDIA Corporation GK107M [GeForce GT 750M] (rev ff)

```

**Comment by QM-Hacker** [comment]
Do you have cuda, opencl-nvidia, opencl-headers, and ocl-icd installed through pacman?

**Comment by seyuf** [comment]
pacman Ss:
 - cuda: community/cuda 7.0.28-2
 - nvidia: extra/opencl-nvidia 352.30-1
 - opcl-headers: community/opencl-headers

I do not have ocl-lcd in my pacman, yaourt the same

**Comment by seyuf** [comment]
I solved my issue by installing lib32-opencl-nvidia:

```
sudo pacman -S lib32-opencl-nvidia
```

Still not enough memory on the card snif snif
```
[OPENCL]:OpenCL device GeForce GT 750M has insufficient GPU memory.1073545216 bytes of memory found < 1423739904 bytes of memory required
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

```

**Comment by LefterisJP** [comment]
Opencl-ICD for Arch is [here](https://www.archlinux.org/packages/?name=ocl-icd).  For ArchLinux and GPUs always refer to the [ArchLinux GPGPU wiki](https://wiki.archlinux.org/index.php?title=GPGPU&redirect=no)  since it's always gonna be up to date.

**Comment by lenage** [comment]
Just installed and share my 2 cents here

1. install gcc47 on AUR `yaourt -S gcc47` as CUDA dones't support gcc > 5
2. set  `CUDA_HOST_COMPILER` to gcc-4.7 `set(CUDA_HOST_COMPILER /usr/bin/gcc-4.7)`
2. remove `-fuse-ld=gold` flag when build

See diff
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 231743e30..786967593 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -13,6 +13,10 @@ endif()

 set(CMAKE_AUTOMOC ON)

+# use gcc-4.7 for CUDA
+set(CUDA_HOST_COMPILER /usr/bin/gcc-4.7)
+find_package(CUDA)
+
 # link_directories interprate relative paths with respect to CMAKE_CURRENT_SOURCE_DIR
 cmake_policy(SET CMP0015 NEW)

diff --git a/cmake/EthCompilerSettings.cmake b/cmake/EthCompilerSettings.cmake
index 069a8b96b..9ee181e1f 100644
--- a/cmake/EthCompilerSettings.cmake
+++ b/cmake/EthCompilerSettings.cmake
@@ -80,10 +80,10 @@ endif ()
 if (("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU") OR ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang"))
        option(USE_LD_GOLD "Use GNU gold linker" ON)
        if (USE_LD_GOLD)
-               execute_process(COMMAND ${CMAKE_C_COMPILER} -fuse-ld=gold -Wl,--version ERROR_QUIET OUTPUT_VARIABLE LD_VERSION)
+               execute_process(COMMAND ${CMAKE_C_COMPILER} -Wl,--version ERROR_QUIET OUTPUT_VARIABLE LD_VERSION)
                if ("${LD_VERSION}" MATCHES "GNU gold")
-                       set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fuse-ld=gold")
-                       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fuse-ld=gold")
+                       set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
+                       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
                endif ()
        endif ()
 endif ()
```
