### ISSUE TITLE
BadCast: I've got this error when I run freshly built eth

### ISSUE THREAD

**Issue by benadrasni** [ethereum/cpp-ethereum#2665]
~/cpp-ethereum/build/eth$ ./eth
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::BadCast>'
  what():  BadCast
Aborted (core dumped)

**Comment by gavofyork** [comment]
please clear out your `.eth` directory first, particularly the config.rlp file.

**Comment by gavofyork** [comment]
addressed in 1d80280d7581015a1dbe73246627c37799349e12 - please let me know if the latest develop (or a build in an hour's time) doesn't fix it.
