### ISSUE TITLE
Solidity: Subcalls that run out of gas kill entire transaction and spend all gas

### ISSUE THREAD

**Issue by PeterBorah** [ethereum/cpp-ethereum#2666]
Minimal example:

    contract Target {       
      uint stuff;           
                            
      function expensive() {
        stuff++;            
      }                     
    }                       
    
    contract Delegator {             
      Target public target;          
      uint public times_called;      
                                     
      function Delegator() {         
        target = new Target();       
      }                              
                                     
      function delegate(uint _gas) { 
        times_called++;              
        target.expensive.gas(_gas)();
      }                              
    }

And then in geth console (v 1.0.0):

    > delegator.delegate(1000000, {from: eth.coinbase, gas: 2000000})
    '0xa67385a43e2bb97a898bdbe74e67c4fd38977078ced4f771a35ef86610c560a0'
    > delegator.times_called()
    '1'
    > eth.getTransactionReceipt('0xa67385a43e2bb97a898bdbe74e67c4fd38977078ced4f771a35ef86610c560a0')
    {
    	[snip]
      gasUsed: 62204,
    	[snip]
    }
    > delegator.delegate(5000, {from: eth.coinbase, gas: 2000000})
    '0xfa6b502d572df5e5721d0e4379214ab19af5f1c028b6c8d81463f5b088d39430'
    > delegator.times_called()
    '1'
    > eth.getTransactionReceipt('0xfa6b502d572df5e5721d0e4379214ab19af5f1c028b6c8d81463f5b088d39430')
    {
      	[snip]
      gasUsed: 2000000,
    	[snip]
    }

Based on this, it looks like this behavior might be intentional:

https://github.com/ethereum/wiki/wiki/Solidity-Tutorial#exceptions

However, this behavior pretty severely limits the usefulness of calling other contracts. If you call a contract you don't completely control, you run the risk of being locked out of your own contract. And to add insult to injury, it spends all your gas!

In my personal case, I'm building a game that will call user-supplied contracts. I need to be able to limit the amount of gas they can use, and I need to be able to react to the fact that they ran out of gas. With the current behavior, my contract will just become completely unusable if an infinite loop contract is submitted.

Is there a workaround for this? And if not, is there any chance this behavior could be made optional?

**Comment by chriseth** [comment]
Exceptions are forwarded by Solidity across external calls to fully abort unexpected situations. The problem is that the EVM only has one exception type, which is "OutOfGas". This means that any exception unfortunately has to consume all gas.

Of course, if you call a manually gas-limited function, the situation that it might run out of gas is not really unexpected. Unfortunately, we do not yet have a way to retrieve both the return value and the fact whether it ran out of gas or not. If you want to access both, you have to wait for us to implement [catching exceptions](96274794).

If you are not interested in the return value, you can use `otherContract.call`: This function does not forward exceptions but instead returns `1` in the failure case.

**Comment by PeterBorah** [comment]
Thank you for your answer! I had just figured out the `.call(). workaround. For those following along at home:

`address.call()` accepts an arbitrary number of arbitrary types. (https://github.com/ethereum/wiki/wiki/Solidity-Features#generic-call-method) It also doesn't forward exceptions. You can therefore manually implement the ABI, by having the first argument be the first four bytes of the SHA3 of the function signature. (As described here: https://github.com/ethereum/wiki/wiki/Ethereum-Contract-ABI#function-selector)

So this works for my usecase:

`target.call.gas(_gas)(0x0bc07a88);`

Thanks again!

**Comment by chriseth** [comment]
Thanks for the explanation! Just one tiny addition: You can even use e.g.
`target.call.gas(_gas)(bytes4(sha3("functionName(uint256,address)")), 123, address(0x123))`
the optimizer will do its best to put the four-byte constant in the source.

**Comment by nmushegian** [comment]
@chriseth I think you have this backwards:
> This function does not forward exceptions but instead returns 1 in the failure case.

ctrl+f "Returns0" and "Returns1": https://github.com/nexusdev/dappsys/blob/develop/contracts/lang/fallback_tests.sol
