### ISSUE TITLE
Eth/AlethZero does not accept master password after restart.

### ISSUE THREAD

**Issue by snario** [ethereum/cpp-ethereum#2675]
I'm having an issue where my MASTER password is 50 characters long, I set the password on first-time client start (and I was _extremely_ careful to ensure I was pasting it in correctly) but when I open the client a second time it asks for the password and says it is invalid.

```
Please enter your MASTER password:
Password invalid. Try again.
```

This has happened to me 3 times in a row. I delete the `~/.ethereum` folder and reset password to fix.

**Comment by Gustav-Simonsson** [comment]
![rceyl51](https://cloud.githubusercontent.com/assets/293096/9009781/a849f7ea-37a3-11e5-8b79-9b5f695904d4.jpg)

**Comment by snario** [comment]
I'm not crazy I swear :p

**Comment by Gustav-Simonsson** [comment]
@snario hehe :D well, is there anything peculiar about the password? like does it contain spaces, tabs, newlines, unicode chars or anything funky like that?

**Comment by gavofyork** [comment]
did you upgrade/reinstall the client between the first time and the second time?

**Comment by gavofyork** [comment]
check the contents of `~/.ethereum/keys.info` and `~/.ethereum/keys.info.seed`? also check around `KeyManager` to see if there's any suspicious code, especially when writing.

not sure how those flags in particular could result in an invalid keys file. `KeyManager` is in a different part of the codebase.

**Comment by LianaHus** [comment]
I don't think we should blame --frontier and --turbo.
I was trying to reproduce the bug, I had --frontier and was playing around with accounts, new/delete, kill blockchein then connect to the network with new account... and as last time I've got the problem when I switched to debug run. will try to debug

**Comment by LianaHus** [comment]
ok steps to reproduce:
open AZ
kill the default account
restart AZ

**Comment by chriseth** [comment]
Once this is reproducible reliably (did not yet succeed myself), we might check which exception is thrown at `KeyManager::load`, it might be some unrelated exception we can recover from.

**Comment by LianaHus** [comment]
exceptions are from the constructor of RLP.cpp if you just do what I wrote above you get 2nd exception. but sometimes(if I'm not mistaken when you're creating another accounts and then delete default one) you can get the first one.

**Comment by gavofyork** [comment]
fixed now?

**Comment by LianaHus** [comment]
yes
