### ISSUE TITLE
CanonBlockChain opens DB twice

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#2681]
In CanonBlockChain constructor it is called openDatabase method:
BlockChain::openDatabase(_path, _we, _pc);
https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/CanonBlockChain.cpp#L48-L50

But before this method called, it is initialized a FullBlockChain class which constructor is also calling the openDatabase method.

https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/BlockChain.h#L406

**Comment by gavofyork** [comment]
CanonBlockChain should be using the constructor at https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/BlockChain.h#L508 to avoid opening it twice.

**Comment by gavofyork** [comment]
please give specific expects vs actuals, logs and backtraces. as it is, this is a non-issue.

**Comment by winsvega** [comment]
BOOST_AUTO_TEST_CASE(bcMining)
{
	try
	{
		dev::TransientDirectory m_td;				//BlockChain Dir
		dev::TransientDirectory m_td2;				//State Dir

		CanonBlockChain<BasicAuthority> m_blockchain(m_td.path(), WithExisting::Kill);
		OverlayDB stateDB = State::openDB(m_td2.path(), m_blockchain.genesisHash());
		State m_state (m_blockchain.genesisState(stateDB));

		m_state.sync(m_blockchain);
		mine(m_state, m_blockchain);
	}
	catch (Exception const& _e)
	{
		BOOST_ERROR("Mining Error! " << _e.what());
	}
	catch (std::exception const& _e)
	{
		BOOST_ERROR("Mining Error! " << _e.what());
	}
	catch(...)
	{
		BOOST_ERROR("Mining Error!");
	}
}
