### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by sebastiandeutsch** [ethereum/cpp-ethereum#2691]
I've compiled eth on my MacBook - but unfortunately it gives the error: "Illegal instruction: 4". Does anyone know how to avoid the problem?

**Comment by gavofyork** [comment]
presumably being built for the wrong processor. can you paste the output of the window when you hold Alt, click the Apple icon and hit System Information?

**Comment by RyanMarr** [comment]
I had exactly the same issue.

Here's my system info:

Model Name:	Mac Pro
  Model Identifier:	MacPro3,1
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	24.50 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	6 MB
  Memory:	4 GB
  Bus Speed:	1.33 GHz

**Comment by RyanMarr** [comment]
I fixed the issue by running `brew install llvm --HEAD --with-clang` then reinstalling.
