### ISSUE TITLE
The custom genesis.json doesn't changing traffic values

### ISSUE THREAD

**Issue by romanman** [ethereum/cpp-ethereum#2693]
trying to import back `olympic.json` into the cpp peer 
and getting that bug: 

In the log
```
¹  05:21:32|eth  Opened blockchain DB. Latest: #fd4af92aג¦ (rebuild not needed)
  ג
  
```  

In the STATUS

```
  Recv:   [STATUS protocolVersion=60 networkId=121 totalDifficulty=0400000000 
    bestHash=d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3 
    genesisHash=d4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3]
```

**Comment by gavofyork** [comment]
and you expected?

**Comment by romanman** [comment]
@gavofyork : well it looks like the genesis for the olympics is loaded correctly
but when the traffic starts the hash on `STATUS`  is from the frontier

**Comment by gavofyork** [comment]
the genesis information is orthogonal to the network. you can have custom genesis blocks for either protocol. if you want to switch between the networks, use `--olympic` and `--frontier`. if you're talking about the network ID only, use `--network-id`.
