### ISSUE TITLE
Windows 7 x64 Nvidia GTX 760 2Gb mining issue

### ISSUE THREAD

**Issue by 42mind** [ethereum/cpp-ethereum#2696]
Hello guys,

I have installed geth, synchronised with the network, downloaded latest Etehreum Win64 package. 
When I'm running ethminer with -G flag, I getting "No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G ar
gument" error. Latest official Nvidia driver is installed.

Guys, do you have any ideas what to do next to resolve this issue?

Here is some useful information from the system.
https://15254b2dcaab7f5478ab-24461f391e20b7336331d5789078af53.ssl.cf1.rackcdn.com/ethereum.vanillaforums.com/editor/hf/037g3k6q06r2.png

https://15254b2dcaab7f5478ab-24461f391e20b7336331d5789078af53.ssl.cf1.rackcdn.com/ethereum.vanillaforums.com/editor/dv/d3wlhch6fb6f.png

https://15254b2dcaab7f5478ab-24461f391e20b7336331d5789078af53.ssl.cf1.rackcdn.com/ethereum.vanillaforums.com/editor/i2/bnexu2qhzqx5.png

**Comment by gavofyork** [comment]
nvidia drivers tend not to be able to allocate a single 1GB+ chunk of memory, necessary to be able to mine at present. reworking this is a non-trivial undertaking; patches for a so-called "chunked" implementation are most welcome :)

**Comment by 42mind** [comment]
@gavofyork so it means, i should wait for a patch? :)
Btw, mobile Nvidia on Mbpro is good with mining. 
Is it any workaround? Maybe it will work on Linux? 

Thank you!

**Comment by subtly** [comment]
Please try setting GPU_MAX_ALLOC_PERCENT to a large value (95 or 100; lower if main display shares GPU).

**Comment by 42mind** [comment]
@subtly I have tried, with no success. Thank you for your advice.

**Comment by hitchcott** [comment]
I seem to be having the same issue with my GTX 960. Setting GPU_MAX_ALLOC_PERCENT does not fix it.

Using `--list-devices`:
```
[0] GeForce GTX 960
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294967296
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073741824
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
```

**Comment by LefterisJP** [comment]
Yes you can't allocate the DAG in a single chunk at the moment. You will need a GPU that can have a `CL_DEVICE_MAX_MEM_ALLOC_SIZE` of at least 2GB.
