### ISSUE TITLE
Can't make - llvm errors with new dependencies

### ISSUE THREAD

**Issue by conradjohnson** [ethereum/cpp-ethereum#2707]
llvm has a whole new set of dependencies...  

Trying to build on Ubuntu 14.04.2 -  
cpp build worked great up until last release...
get llvm error when trying to make.

Backing up in instructions, notice there's new prerequisites: 
sudo apt-get -y install build-essential git cmake libboost-all-dev libgmp-dev libleveldb-dev libminiupnpc-dev libreadline-dev libncurses5-dev libcurl4-openssl-dev libcryptopp-dev libjson-rpc-cpp-dev libmicrohttpd-dev libjsoncpp-dev libargtable2-dev llvm-3.8-dev libedit-dev mesa-common-dev ocl-icd-libopencl1 opencl-headers libgoogle-perftools-dev qtbase5-dev qt5-default qtdeclarative5-dev libqt5webkit5-dev libqt5webengine5-dev ocl-icd-dev libv8-dev

Try to run above command and get this:
The following packages have unmet dependencies:
 llvm-3.8-dev : Depends: libllvm3.8 but it is not going to be installed
                Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04 is to be installed
                Depends: llvm-3.8 (= 1:3.8~svn243996-1~exp1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Try to manually install any of those and no dice for any of them...

Using any obscure or bleeding edge library dependencies?

**Comment by LefterisJP** [comment]
Did you follow the entire guide from [here](https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu#install-dependencies)? Notice that you also need to add a specific PPA.

**Comment by conradjohnson** [comment]
I did.    Getting to the sudo apt-get command above - this is where it falls off.  Previous attempts to make on this version result in 'no llvm package found' errors.

**Comment by chfast** [comment]
> Using any obscure or bleeding edge library dependencies?

Yes, LLVM 3.7 / 3.8.
