### ISSUE TITLE
solc chokes when you give it too many files

### ISSUE THREAD

**Issue by nmushegian** [ethereum/cpp-ethereum#2726]
(lldb) target create "solc"
    Current executable set to 'solc' (x86_64).
    (lldb) r <a huge list of contracts> --combined-json binary,json-abi
    Process 57432 launched: '/usr/local/bin/solc' (x86_64)
    Internal compiler error during compilation:
    /Users/nikolai/cpp-ethereum/libsolidity/CompilerContext.cpp(71): Throw in function const bytes &dev::solidity::CompilerContext::getCompiledContract(const dev::solidity::ContractDefinition &) const
    Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
    std::exception::what: std::exception
    [dev::tag_comment*] = Compiled contract not found.
    Process 57432 exited with status = 1 (0x00000001)
    (lldb) bt
    error: invalid thread

**Comment by nmushegian** [comment]
solc, the solidity compiler commandline interface
Version: 0.1.0-40073996/RelWithDebInfo-Darwin/clang/int

**Comment by nmushegian** [comment]
I actually was missing a contact definition. It should give an error isntead of crashing though.

**Comment by chriseth** [comment]
It should not crash indeed. Would you be able to give a minimal example for the crash?

**Comment by nmushegian** [comment]
Can't reproduce now =\

There was 1) a lot of contracts and 2) a missing import dependency in one of them

**Comment by LianaHus** [comment]
This issue has been moved to ethereum/solidity repository
https://github.com/ethereum/solidity/issues/12
