### ISSUE TITLE
secp256k1 does not build on 32-bit

### ISSUE THREAD

**Issue by witten** [ethereum/cpp-ethereum#2727]
In attempting to build cpp-ethereum on a 32-bit Debian Jessie machine, I've come across a build error in secp256k1 that appears to indicate a lack of support for 32-bit machines:

```
make -j2 solc
...
[ 42%] Building C object secp256k1/CMakeFiles/secp256k1.dir/secp256k1.c.o
In file included from /home/me/Downloads/cpp-ethereum/secp256k1/secp256k1.c:11:0:
/home/me/Downloads/cpp-ethereum/secp256k1/util.h:101:37: error: ‘__int128’ is not supported for this target
 SECP256K1_GNUC_EXT typedef unsigned __int128 uint128_t;
```

I believe this is because __int128 isn't supported on 32-bit. You may want to either fix this by working around the apparent lack of __int128 support, or just declare a hard requirement on 64-bit.

```
$ llvm-config-3.8 --version
3.8.0
$ grep 'model name' /proc/cpuinfo
model name	: Genuine Intel(R) CPU           T2500  @ 2.00GHz
model name	: Genuine Intel(R) CPU           T2500  @ 2.00GHz
$ uname -a
Linux me 3.16-3-686-pae #1 SMP Debian 3.16.5-1 (2014-10-10) i686 GNU/Linux
```

**Comment by phonikg** [comment]
I'm getting some secp256k1 errors when trying to compile on armhf (32bit) as well:

cmake .. -DCMAKE_BUILD_TYPE=Release -DBUNDLE=minimal  ***-->Completes without errors

Then:

make -j2

[  5%] Building CXX object libdevcore/CMakeFiles/devcore.dir/RLP.cpp.o
In file included from /home/odroid/cpp-ethereum/secp256k1/secp256k1.c:11:0:
/home/odroid/cpp-ethereum/secp256k1/util.h:101:37: error: '__int128' is not supported for this target
 SECP256K1_GNUC_EXT typedef unsigned __int128 uint128_t;
                                     ^
In file included from /home/odroid/cpp-ethereum/secp256k1/field_5x52_impl.h:22:0,
                 from /home/odroid/cpp-ethereum/secp256k1/field_impl.h:19,
                 from /home/odroid/cpp-ethereum/secp256k1/secp256k1.c:13:
/home/odroid/cpp-ethereum/secp256k1/field_5x52_int128_impl.h: In function 'secp256k1_fe_mul_inner':
/home/odroid/cpp-ethereum/secp256k1/field_5x52_int128_impl.h:50:5: warning: right shift count >= width of type
     d += (c & M) * R; c >>= 52;
     ^
/home/odroid/cpp-ethereum/secp256k1/field_5x52_int128_impl.h:54:5: warning: right shift count >= width of type
     t3 = d & M; d >>= 52;
     ^

**Comment by phonikg** [comment]
$ llvm-config-3.8 --version
3.8.0svn
$ grep 'model name' /proc/cpuinfo
model name      : ARMv7 Processor rev 3 (v7l)
model name      : ARMv7 Processor rev 3 (v7l)
model name      : ARMv7 Processor rev 3 (v7l)
model name      : ARMv7 Processor rev 3 (v7l)
model name      : ARMv7 Processor rev 3 (v7l)
model name      : ARMv7 Processor rev 3 (v7l)
model name      : ARMv7 Processor rev 3 (v7l)
model name      : ARMv7 Processor rev 3 (v7l)
$ uname -a
Linux odroid 3.10.82-40 #1 SMP PREEMPT Tue Jul 14 09:37:06 BRT 2015 armv7l armv7l armv7l GNU/Linux

**Comment by subtly** [comment]
Check PM. Haven't compiled on arm and there's a pending PR for 32-bit. Will incorporate config.h defs once we've got a build.

**Comment by gavofyork** [comment]
is this sorted yet?

**Comment by phonikg** [comment]
Not that I'm aware of...

**Comment by phonikg** [comment]
I believe this is now taken care of... issue no longer exists for armhf anyway...

**Comment by iljah** [comment]
I see the same problem on 32 bit fedora, g++ (GCC) 7.1.0, latest git:

```
In file included from .../cpp-ethereum/build/deps/src/secp256k1/src/secp256k1.c:9:0:
.../cpp-ethereum/build/deps/src/secp256k1/src/util.h:110:37: virhe: ”__int128” is not supported on this target
 SECP256K1_GNUC_EXT typedef unsigned __int128 uint128_t;
                                     ^~~~~~~~
```

**Comment by Kamalakirthi** [comment]
Appreciate Any Work Around For This. Thanks
I Tried With Fedora 25, I Have This
CMakeFiles/secp256k1.dir/build.make:73: recipe for target 'deps/src/secp256k1-stamp/secp256k1-install' failed
gmake[2]: *** [deps/src/secp256k1-stamp/secp256k1-install] Error 1
CMakeFiles/Makefile2:210: recipe for target 'CMakeFiles/secp256k1.dir/all' failed
gmake[1]: *** [CMakeFiles/secp256k1.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
gmake: *** [all] Error 2

Log Says
~/.../cpp-ethereum/build/deps/src/secp256k1/src/util.h:110:37: error: ‘__int128’ is not supported on this target
 SECP256K1_GNUC_EXT typedef unsigned __int128 uint128_t;

My GCC Is
gcc (GCC) 6.4.1 20170727 (Red Hat 6.4.1-1)

**Comment by jcktm** [comment]
I'm also seeing this today on arm, with tag v1.6.0
