### ISSUE TITLE
ethminer seems to be producing incorrect results.

### ISSUE THREAD

**Issue by jbrukh** [ethereum/cpp-ethereum#2758]
I am on Ubuntu 15.04, my GPU is AMD r9 295x2. I am running ethminer which I have built from scratch on this machine; its version shows as 0.9.40.

    ethminer version 0.9.40 Build: Linux/g++/JIT/RelWithDebInfo

When I connect to ethpool.org with this setup, their server seems to be getting [bad PoW hashes](https://www.reddit.com/r/etherpool/comments/3g3v04/etherpool_doesnt_pick_up_my_miner_instance/ctulgfh).

Additionally, I see the following in the ethminer log:

     ⚡   17:05:01|gpuminer0  Worker stopping 843 ms
      ℹ  17:05:01|gpuminer0  workLoop 1 #290decd9… #290decd9…
     ⚡   17:05:01|gpuminer1  Worker stopping 863 ms
      ℹ  17:05:01|gpuminer1  workLoop 1 #290decd9… #290decd9…
      ℹ  17:05:02|ethminer  Solution found; Submitting to http://ethpool.org/miner/0x67e68cf48fd1ac929f4e963dd2abfed39f7f94f2/51 ...
      ℹ  17:05:02|ethminer    Nonce: 5cfe0778627877ae
      ℹ  17:05:02|ethminer    Mixhash: 415b56989f646f848fa6fd479d04e9c34d10f00c48d7eaa04d4de58ac2284246
      ℹ  17:05:02|ethminer    Header-hash: fe710e0708f667de36eb3f2c777715669ba13e94ce4be3ff29c1d045fa96a1ee
      ℹ  17:05:02|ethminer    Seedhash: 290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563
      ℹ  17:05:02|ethminer    Target: 00000000d7972c01e761a4609dd060d6db445fac38d966391ad498740083b455
      ℹ  17:05:02|ethminer    Ethash: 1eca8f07bebb17f062d7417ed36844bb868510b11ec4182fb616cdd6b6c8b984
      ✘  17:05:02|ethminer  FAILURE: GPU gave incorrect result!

And this:

    miner  17:06:32|ethminer  Mining on PoWhash #fb1fd914… : 50099340 H/s = 82313216 hashes / 1.643 s
    miner  17:06:33|ethminer  Mining on PoWhash #fb1fd914… : 50380616 H/s = 112197632 hashes / 2.227 s
      ℹ  17:06:33|ethminer  Solution found; Submitting to http://ethpool.org/miner/0x67e68cf48fd1ac929f4e963dd2abfed39f7f94f2/51 ...
      ℹ  17:06:33|ethminer    Nonce: 73d872a152684d00
      ℹ  17:06:33|ethminer    Mixhash: cca19867666d322079b635c1e2e4c57859d0f6668542965b72e13b7c3c054d22
      ℹ  17:06:33|ethminer    Header-hash: fb1fd914cf6a526217e576b6727c5899e84617c25aab1a58e56d26838b5f028e
      ℹ  17:06:33|ethminer    Seedhash: 290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563
      ℹ  17:06:33|ethminer    Target: 00000000d7972c01e761a4609dd060d6db445fac38d966391ad498740083b455
      ℹ  17:06:33|ethminer    Ethash: 00000000a577429738e552eb18926e1f2f406dcbaa3e14b214e6b5dadd39420e
      ✘  17:06:34|ethminer  :-( Not accepted.
    
Any advice?

**Comment by gavofyork** [comment]
has it mined any blocks?

i just checked your PoW and the server was indeed wrong to throw it out:

```
➜  cpp-ethereum git:(develop) ./build.gcc/ethminer/ethminer -w fb1fd914cf6a526217e576b6727c5899e84617c25aab1a58e56d26838b5f028e 290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563 5100000000 73d872a152684d00
INVALID :-(
0f0101f710adffec8f5a2c2500a15352a212386edb24da972b47086cd7b1cd1a >= 00000000d7972c01e761a4609dd060d6db445fac38d966391ad498740083b455
  where 00000000d7972c01e761a4609dd060d6db445fac38d966391ad498740083b455 = 2^256 / 5100000000
  and 0f0101f710adffec8f5a2c2500a15352a212386edb24da972b47086cd7b1cd1a = ethash(fb1fd914cf6a526217e576b6727c5899e84617c25aab1a58e56d26838b5f028e, 73d872a152684d00)
  with seed as 290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563
SHA3( light(seed) ) = 35ded12eecf2ce2e8da2e15c06d463aae9b84cb2530a00b932e4bbc484cde353
```

**Comment by jbrukh** [comment]
Hi, thanks for taking a look. 

I haven't mined a block doing solo mining on this GPU. I'm not sure what Etherpool uses on their backend, but it seems to be an issue on their end. (They are also not averse to customizing the software they use, so it may be related.) 

They ask users to send a parameter with their mining call, which they use to adjust the difficulty of shares such that the user finds a share every 1-2 minutes. Apparently setting this parameter too high results in the behavior above, and the error seems to go away when the parameter is set slightly below my actual hashrate.

**Comment by gregory0219998** [comment]
I have the failure error too + json error sometimes with the last version of cpp ethereum

**Comment by aki199** [comment]
Yep, same here - failure error and json error. Running on r9 r295x2 and radeon 7950

**Comment by tritonresearch** [comment]
Are you mining on Etherpool? The JSON error is probably due to their server dropping requests (either because of their CloudFlare configuration or otherwise). You can try to set --farm-recheck to 2000, 3000, or more to see if it will make them less frequent.

I find the incorrect results will go away if you lower your hashrate parameter to Etherpool.

Anyway, since this doesn't seem to be an ethminer issue, I think we can close this.

**Comment by jbrukh** [comment]
Are you mining on Etherpool? The JSON error is probably due to their server dropping requests (either because of their CloudFlare configuration or otherwise). You can try to set --farm-recheck to 2000, 3000, or more to see if it will make them less frequent.

I find the incorrect results will go away if you lower your hashrate parameter to Etherpool.

Anyway, since this doesn't seem to be an ethminer issue, I think we can close this.

**Comment by efaysal** [comment]
this issue in now clarified by the current is updated during the time a solution is found.

**Comment by efaysal** [comment]
I'm posting my observation,  just to share them with you, it needs more elaboration, in process. 

The Problem Formulation:

cpp-ethereum/ethminer/MinerAux.h 

function doFarm

The used standard pattern allows a callback function to be registered with a class method and the arguments of the callback function  will be extracted from the actual context of the class members.

In our case, GenericFarm<EthashProofOfWork> f is the class. 
Target member is EthashProofOfWork::Solution to be assigned to the local 
variable in the function doFarm, EthashProofOfWork::Solution solution;
This will be a solution to form a potential block for the blockchain.

This solution will be evaluated using a lambda function (callback) in the 
GenericFarm<EthashProofOfWork>.onSolutionFound(callback)

f.onSolutionFound(
  [&](EthashProofOfWork::Solution sol)
{
    #  lambdaStatements
  solution = sol;
  return completed = true;
});

our lambda function has the following structure:
  
[ captures ] (parameters) { lambdaStatements; }

captures: solution ( to be assigned)
parameters: sol ( should be captured adequately and in a efficient manner ) 

The interesting thing in this process,  we need to "capture" sol 
( the argument of lambda function) and assign it  to solution. 

Normally,  sol will be defined by the actual "value" of EthashProofOfWork::Solution in the class
GenericFarm<EthashProofOfWork> via object f. Once sol is determined, it will be assigned to solution and the flag completed is true, the process get out from the loop and a new block will be checked. One obvious serious issue, everything is working asynchronously and I can even say in a "blind" manner. No one knows when that will happen  adequately or not! Many threads may be involved, threads from the code itself and threads from the operating system. 

Second obvious serious issue may prevent the solution to be established if current have been updated in the mean-time, hence, "FAILURE: GPU gave incorrect result!". 

Here we need to assess the following questions:

1) Is sol captured correctly, the most updated solution in object f,  is the one assigned to solution accordingly to the most updated current?

2) While the loop is running in a specific thread and the f.onSolutionFound(lambda) is in a second thread, a mechanism is needed  to give more priority to the process in f.onSolutionFound(lambda), once a solution is found, to handle any check of the block preventing any update of the current?
this will eliminate the famous "FAILURE: GPU gave incorrect result!"

3) The loop is active every  m_farmRecheckPeriod = 500 ms, is this an optimal value to prevent wrong update when a solution is determined in f.onSolutionFound(lambda)? 

4) to be continued ...

**Comment by htso** [comment]
I'm having this same issue on a Nvidia gtx 980. This happened quite a few times since I started using ethminer yesterday. It's mentioned above that some parameters need to be set correctly. I'm taking all the default with,

 ethminer -F http://us1.ethermine.org:5555/0x<my-wallet> -G

What could be done ?

**Comment by efaysal** [comment]
stay away from C++.
Why you do not use rust?

**Comment by htso** [comment]
@efaysal  Any suggestion as far as mining tool similar to ethminer?

**Comment by efaysal** [comment]
I guess Rust/Parity is good, or go?

**Comment by efaysal** [comment]
Look around this to figure out https://etherchain.org/statistics/basic

**Comment by htso** [comment]
Does Parity make use of GPUs? Thks for the link to the basic stat page, what should i be looking for?

**Comment by htso** [comment]
I see why you point me there. OK, parity is gaining market share. Good to know. Wonder what that 91% are using?

**Comment by efaysal** [comment]
Second, Dr. Wood can help you if you have any question, he is very academic
and professional in the same time.
Check gitter Parity:  https://gitter.im/ethcore/parity
A lot of skilled people around, help you till you will 100% convinced.

During my review of Ether-C++, it was clear that it's hard to handle
Ethereum with that monster language.
I like C++, I'm using it any time, in my scientific computation.
When it comes to stuff related to networking, asio library is not really
for Ethereum and more those lambda function not really suitable to handle
the mining process, hence the observed errors, see my comment above!

Who are those 91%, my be these are miners from Paradise!

**Comment by htso** [comment]
No rust coder here. Followed the install instruction, but cargo not found. Any pointer appreciated.

**Comment by efaysal** [comment]
you can down load rust, https://doc.rust-lang.org/book/getting-started.html

**Comment by htso** [comment]
Not sure about internal C++ issue. The error I saw say GPU failed to come up with correct result.

**Comment by efaysal** [comment]
It's  long time, my input was somewhere that explain the issue. 
The issue is related to an update that is not good and take the process to that  condition even a block has been found. 

How to approach now your problem, you need to know who are those miners 80% now deciding the fate of the blockchain? If they are using C++ then just use C++ even it's lossy ... 

Rust is going toward 20% may more in future, a plan B.

**Comment by whotheff** [comment]
Sorry for te late entry, It's been several versions of ETHminer and still GPU gives incorrect result even in 14rc4. Can you confirm if it is a SW or HW issue?
