### ISSUE TITLE
ethminer fails after 1st workloop, Frontier.help!

### ISSUE THREAD

**Issue by boondogger** [ethereum/cpp-ethereum#2761]
recent openCL drivers, ubuntu15.04, fresh install, all new pulls/drivers

initial all and geth work fine.
used this build recipe:
http://forum.ethereum.org/discussion/2695/frontier-mining-setup-notes-ubuntu-15-04-geth-v1-0-amd-ethminer

[OPENCL]:Creating one big buffer for the DAG

Allocating/mapping single buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.[OPENCL]:clEnqueueWriteBuffer(-38)
FAIL.

**Comment by jbrukh** [comment]
It looks like it could not fit the DAG into the memory of your GPU. How much memory does your GPU have? (It needs at least 2 GB.) There is also an env flag they wrote about in the forums that might help the GPU allocate enough memory. Hope that helps.

**Comment by LefterisJP** [comment]
Write ` ethminer --list-devices` and you can see how much memory OpenCL sees for your GPU. As the above poster said it needs 2 GB

**Comment by boondogger** [comment]
a@a:~$ ethminer --list-devices
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Tahiti
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 1839202304
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073741824
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

**Comment by boondogger** [comment]
shows 3G total....is it the workgroup size?
the error comes from a worksize that is larger than the GDDR.  wierd.
however my adapter list shows:
a@a:~$ aticonfig --list-adapters
* 0. 01:00.0 AMD Radeon HD 7900 Series
  1. 02:00.0 AMD Radeon HD 7900 Series
  2. 06:00.0 AMD Radeon HD 7900 Series
  3. 07:00.0 AMD Radeon HD 7900 Series
  4. 08:00.0 AMD Radeon HD 7900 Series

all cards are similar r9-280x

**Comment by LefterisJP** [comment]
your OpenCL drivers see a `CL_DEVICE_MAX_MEM_ALLOC_SIZE` of 1073741824. This is not enough to allocate the DAG in a single chunk I am afraid.

**Comment by 5chdn** [comment]
I have the same problem, the GPU has 2GB available, but `CL_DEVICE_MAX_MEM_ALLOC_SIZE` only shows `1284243456`:

      ~ $ ethminer --list-devices
    [OPENCL]:
    Listing OpenCL devices.
    FORMAT: [deviceID] deviceName
    [0] Pitcairn
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 1907359744
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1284243456
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
    [1] Pitcairn
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 2089811968
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1399062528
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

I noticed, restarting the computer allows me to access the full memory again. Setting `GPU_MAX_ALLOC_PERCENT` to 95 or 100 manually does not affect that.

    export GPU_MAX_ALLOC_PERCENT=95

Not certainly an eth/ethminer issue I guess, but does anyone have a clue why this happens?

**Comment by JCBauza** [comment]
Any updates, I have the same issue with a 2gb card

**Comment by ry60003333** [comment]
I am also experiencing this issue with all my MSI R9 270 cards; They have 2 GB of memory. ```ethminer --list-devices``` results in the following output:

```
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Pitcairn
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 2089811968
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1399062528
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] Pitcairn
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 2089811968
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1399062528
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[2] Pitcairn
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 2089811968
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1396703232
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
```

**Comment by TheDeafMute** [comment]
This keeps on happening even after I think I fix it, eventually ---

Says can't allocate DAG and I have 3GB memory on 1 card 2GB on the other, but the CL_DEVICE_MAX_ALLOC_SIZE continues to shrink ...

**Comment by MariusCC** [comment]
I have the same issue using latest version of ethminer:

ethminer --version
ethminer version 1.2.3

ethminer --list-devices                                                                                                                               [OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
 [0] Fiji
         CL_DEVICE_TYPE: GPU
         CL_DEVICE_GLOBAL_MEM_SIZE: 2157868902
         CL_DEVICE_MAX_MEM_ALLOC_SIZE: 588398592
         CL_DEVICE_MAX_WORK_GROUP_SIZE: 256


Running like this:
export GPU_FORCE_64BIT_PTR=1; export GPU_MAX_ALLOC_PERCENT=80; export GPU_USE_SYNC_OBJECTS=1; export GPU_MAX_HEAP_SIZE=80; ethminer -G -F http://somepool  --cl-extragpu-mem 1024 --farm-recheck 256 --cl-global-work 32768 --cl-local-work 256

I get 
[OPENCL]:Allocating/mapping single buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.

**Comment by HuaHub** [comment]
+1
