### ISSUE TITLE
Deterministic Addresses

### ISSUE THREAD

**Issue by xcthulhu** [ethereum/cpp-ethereum#2766]
It would be nice if cpp-ethereum supported creating deterministic private keys from a set passphrase.

Maybe [BIP 0032](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) is worth implementing, of course it is important to remember criticisms of such HDM wallet schemes (see [Buterin (2013)](https://bitcoinmagazine.com/8396/deterministic-wallets-advantages-flaw/)).

**Comment by gavofyork** [comment]
deterministic wallets partially in - AlethZero -> Tools -> Import Brain Wallet... still need to do CLI for that, though.

HD wallets will need substantial additional UI, but definitely doable.
