### ISSUE TITLE
Problem with transactions under eth wrong ts time=1970-01-05 ?

### ISSUE THREAD

**Issue by reb0rn21** [ethereum/cpp-ethereum#2767]
I am using latest ethereum ++ console under windows and sanding transactions is expansive

If I do not set gas limit and gas price there is no way to sand... I get ID from ethconsole but it never go in blockchain

If I buff gasprice and gaslimit my transfer only then go! and I mean buff a lot like 60 000 gas limit and gas price to 5-10x more then default

If I close eth ++ wallet and start Alethzero I can transfer my funds with no problems with default "cheap" fee at once

Also when I open ethconsole.exe I get:
'setTimeout not available in this environment'

I managed to copy/paste message from eth++ wallet screen after I tried transfer of 5eth:
web3.eth.sendTransaction({from: web3.eth.coinbase, to: '0x27e806e70622d2864e1b1f4426d72ffb0457c83a', value: web3.toWei(5, "ether")})

Paste from eth wallet screen:
{"eth.tx.received":{"remote_id":"664b099bGÇª","ts":"1970-01-05T00:48:48.650Z","t
x_hash":"0e0c1243GÇª"}}

i 01:22:52| New transaction 0e0c1243GÇª{27e806e7GÇª/0$5000000000000
000000+22000@10000000000000<-664b099bGÇª #8}

**Comment by reb0rn21** [comment]
I managed to copy/paste message from eth++ wallet screen after I tried transfer of 5eth:
web3.eth.sendTransaction({from: web3.eth.coinbase, to: '0x27e806e70622d2864e1b1f4426d72ffb0457c83a', value: web3.toWei(5, "ether")})

Paste from eth wallet screen:
{"eth.tx.received":{"remote_id":"664b099bGÇª","ts":"1970-01-05T00:48:48.650Z","t
x_hash":"0e0c1243GÇª"}}

  i  01:22:52|<unknown>  New transaction 0e0c1243GÇª{27e806e7GÇª/0$5000000000000
000000+22000@10000000000000<-664b099bGÇª #8}

**Comment by gavofyork** [comment]
Seems there are at least two bugs here:

- [ ] 'setTimeout not available in this environment' - @debris?
- [ ] No default for gasPrice & gasLimit

**Comment by debris** [comment]
should default value of `gasPrice` and `gasLimit` be set in web3.js? I assumed, that clients should handle that.

**Comment by LefterisJP** [comment]
The referenced PR should fix the wrong default gas issue. As for the `setTimeout` not available in this environment issue I am not sure yet. I also see the same message, but it seems to be related to the V8 library version and not to our codebase.

**Comment by subtly** [comment]
@debris Can you look into timestamp issue?

**Comment by reb0rn21** [comment]
Problem is that I also tried using gasprice 50 szhabo and gas 21000, and none gone trought

Only one that gone trought was with 800 shannon as gasprice, also even then I need few times to sand it to go in blockchain... maybe queue backlog is not working @ethconsole or eth.exe

Also offtopic but for last 48h all new build at:
build.ethdev.com/builds/Windows%20C%2B%2B%20develop%20branch/
are zero byte lenght

**Comment by gavofyork** [comment]
btw 21000 isn't enough; the actual amount is a little over - make sure you put 22000 minimum
