### ISSUE TITLE
alethzero crashes when you try importing json key made by geth

### ISSUE THREAD

**Issue by corsaro1** [ethereum/cpp-ethereum#2782]
If trying to import on alethzero an UTC-xxxx json file made by geth, alethzero crashes.

Solved editing the UTC-xxx json file. Just lower case the C of the word: "Crypro", from "Crypto" to "crypto"

Can you fix?

**Comment by gavofyork** [comment]
this is a bug in go's format. please file an issue in go-ethereum instead. 

see format spec: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

**Comment by gavofyork** [comment]
crashing, however, is no good. i'll see to that :)
