### ISSUE TITLE
Improve network diagnostics in AlethZero

### ISSUE THREAD

**Issue by alper** [ethereum/cpp-ethereum#2788]
I start AlethZero and nothing happens except:

  ◇  10:30:43|CrBrowserMain  Trying 5003
  ◇  10:30:43|CrBrowserMain  Unknown

I'm not behind a firewall etc. This is on version:
AlethZero/v0.9.40/RelWithDebInfo/Darwin/clang/JIT
f9677e6267722823480eea8d30d98cf9592980c8
CLEAN

**Comment by alper** [comment]
And then all of a sudden it came to life.

**Comment by alper** [comment]
I'm reopening this because I was asked to, here: https://www.reddit.com/r/ethereum/comments/3gl80t/cant_connect_keeps_saying_handshake_failed/

A lot of the time when I try to connect to the network there are large dead spells where I only get: "Handshake Failed". And then sometimes it will just come to life but it is mostly unpredictable.

**Comment by arkpar** [comment]
make sure Network->Hermit mode is not checked

**Comment by alper** [comment]
That is unchecked for sure. I've also been trying various configurations with and without UPnP and turn my VPN on and off. Right now I'm having more luck but the bug here would be two part:

* Make it that I can launch AlethZero and get connected straight away
* When I can't get connected for a longer period of time, be able to figure out whether it's me or whether it's the network.

**Comment by gavofyork** [comment]
there are some network fixes and improvements recently in develop branch that will be merged to master imminently.

**Comment by alper** [comment]
Cool! Let me know when they hit a bleeding edge build.

**Comment by gavofyork** [comment]
Moved to https://github.com/ethereum/alethzero/issues
