### ISSUE TITLE
Brain wallet in eth & ethkey

### ISSUE THREAD

**Issue by gavofyork** [ethereum/cpp-ethereum#2790]

**Comment by ryancdotorg** [comment]
Do you want people to get robbed? This is how people get robbed. ಠ_ಠ

**Comment by fluffypony** [comment]
Yay, easy money!

**Comment by gavofyork** [comment]
it's a feature people want. as in AZ, it comes with a lot of warnings and a secure random phrase generator.

**Comment by ryancdotorg** [comment]
@gavofyork People wanting a dangerous feature doesn't mean you should give it to them. I am not familiar with "AZ". If you're *not allowing* chosen passphrases this is fine (except for the issue of them forgetting).

**Comment by gavofyork** [comment]
this entire platform is a dangerous feature.
