### ISSUE TITLE
Solidity: Allow to get return value from low-level calls

### ISSUE THREAD

**Issue by nmushegian** [ethereum/cpp-ethereum#2823]
If I do `ADDRESS.call(data)`, Solidity helpfully returns a bool to tell me if the call succeeded:

"call returns a boolean indicating whether the invoked function terminated (true) or caused an EVM exception (false). It is not possible to access the actual data returned (for this we would need to know the encoding and size in advance)."

https://github.com/ethereum/wiki/wiki/Solidity-Tutorial

But I really really want the return value! I'll risk having a too-small buffer.

What about something like this attached to the `address` type?:
`function raw_return(uint how_many_bytes, bytes calldata) returns (bytes raw_return)`

**Comment by nmushegian** [comment]
I'm confused about the behavior of RETURN.

The yellow paper says that H_return is an empty set on exception, and an empty sequence on STOP or SUICIDE.

How does solidity detect the difference? Is there something like an exception flag, or is it an encoding thing? How will try/catch work? The fact that try/catch is planned implies I can somehow control when state changes are applied or not.

I can't find much documentation.

**Comment by chriseth** [comment]
CALL will put different values on the stack depending on whether an EVM-exception occurred in the called contract. This is the only information we have (apart from the fact that the return area in memory is not written if there was no proper RETURN).

**Comment by nmushegian** [comment]
So the return status is on the stack while the return value is in memory. When do you specify where in memory to copy this return value, is it on the stack when you CALL?

So what happens when you do a send to a contract with a fallback function with a return type? The caller isn't allocating memory for the return value because it doesn't know the size, but the callee wants to write the return somewhere!

**Comment by chriseth** [comment]
Comments on issues are not a good way to discuss the internals of the EVM, so please let us keep this short.
The EVM arguments to CALL contain two pointers to the input and output, respectively.
Fallback functions cannot have return values. If a contract returns more than was expected, only the beginning is copied to the output area in memory, the rest is discarded. This case cannot be detected by the caller.

**Comment by nmushegian** [comment]
> Fallback functions cannot have return values.

`solc` thinks they can, making a new issue.

> If a contract returns more than was expected, only the beginning is copied

How do you specify what is expected, how long "the beginning" is? Or is it one word?

**Comment by nmushegian** [comment]
Actually @chriseth I think you are wrong, I successfully returned a value from a callback:

    import 'dappsys/test/test.sol';

    contract IntReturnerInterface {
        function get() returns (int);
    }
    contract FallbackReturner {
        function() returns (int) {
            return 42;
        }
    }
    contract FallbackTest is Test {
        FallbackReturner f;
        function setUp() {
            f = new FallbackReturner();
        }
        function testFallbackReturn() {
            var ret = IntReturnerInterface(f).get();
            assertEq(ret, 42, "wrong return value");
        }
    }

**Comment by LianaHus** [comment]
This issue has been moved to ethereum/solidity repository
https://github.com/ethereum/solidity/issues/14
