### ISSUE TITLE
solc: Fallback functions incorrectly allowed to have a return type

### ISSUE THREAD

**Issue by nmushegian** [ethereum/cpp-ethereum#2828]
This compiles fine in 1.0.0 but is illegal[1]:

    contract broken {
        byte[10000] buffer;
        function() returns (byte[10000]) {
            return buffer;
        }
    }

[1]https://github.com/ethereum/cpp-ethereum/issues/2823#issuecomment-131108174

**Comment by nmushegian** [comment]
Perhaps its type signature is distinct because of the return type, and so it is compiled as a case in the function switch instead of as the fallback. But then it's really confusing about what I should expect to happen on `.send()`

**Comment by nmushegian** [comment]
Nevermind, you totally can return a value from a fallback and the reference in the OP is wrong. See other issue.

**Comment by chriseth** [comment]
With the same argument, you can say that it actually is possible to provide arguments for the fallback function. I would say it still is a type error and should not be allowed, but I am not yet 100% sure about that. Leaving open.

**Comment by nmushegian** [comment]
I guess I should say that the point is, I have a real use case where I want to directly pass the calldata and "unsafely" get the return type. Either fixed at one word size, or with a max buffer size. The alternative would have been to encode all return types with RLP, if I understand that correctly

**Comment by LianaHus** [comment]
This issue has been moved to ethereum/solidity repository
https://github.com/ethereum/solidity/issues/15
