### ISSUE TITLE
Array of addresses causes massive gas usage.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/cpp-ethereum#2830]
It appears that the following contract code causes extremely high gas usage.

```
contract Expensive {
    address[] x;
    
    function Expensive() {
        x[0] = msg.sender;
    }
}
```

According to the [browser compiler]() it uses `50304840` gas.  Attempts to deploy a contract with similar code end up with an empty contract (I believe because it runs out of gas).  Mix exibits similar behavior and hangs/terminates on the assignment.

**Comment by chriseth** [comment]
What you experience is a Solidity exception because you access the array out of bounds (its length is zero initially):
https://github.com/ethereum/wiki/wiki/Solidity-Tutorial#exceptions
