### ISSUE TITLE
Solidity compiler often creates different bytecode in different environments

### ISSUE THREAD

**Issue by jase1981** [ethereum/cpp-ethereum#2841]
I've been following other people projects, reading the solidity contracts and trying to verify the bytecode of live contracts. I noticed that they often don't match. First I noticed that published bytecode (eth.getCode(address)) is somewhat shorter than locally compiled one, but this is not the problem; I just trim the beginning bytes until length is the same and then they usually match. But not always.

I've been testing this for the last two days by compiling the contracts myself under various scenarios: 
* geth console
* solc.exe (windows)
* browser solidity compiler
* time delay (I leave browser compiler tab open and try again later)
* solc (linux vm)

Sometimes the output is the same, usually with shorter contracts, but often it is different, specially with longer contracts, like this one:
https://raw.githubusercontent.com/ethereum/dapp-bin/master/wallet/wallet.sol

Do others have similar experience? Is there some other way I can verify live contract against source?

**Comment by chriseth** [comment]
Deployed code is always different from the compiled code in the following way: The output of the compiler is the creation-time code, i.e. the code that contains constructors and returns the final code which is stored on the blockchain and returned by `eth.getCode`. The compiler can actually also generate the latter, there is just no interface for that yet.

The same version of solc should actually generate the same code in all environments. If this is not the case, please report this here with the exact environment, source code and compiler options.

**Comment by jase1981** [comment]
These are my environments and solc versions:

OS Name:                   Microsoft Windows 7 Ultimate
OS Version:                6.1.7601 Service Pack 1 Build 7601
D:\Programs\Ethereum (++) 0.9.40\Release>solc --version
solc, the solidity compiler commandline interface
Version: 0.1.1-ac9911c1/Release-Windows/msvc/JIT

lubuntu@lubuntu-VirtualBox:/media/sf_D_DRIVE/solc-test$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="15.04 (Vivid Vervet)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.04"
VERSION_ID="15.04"
lubuntu@lubuntu-VirtualBox:/media/sf_D_DRIVE/solc-test$ solc --version
solc, the solidity compiler commandline interface
Version: 0.1.1-0/Release-Linux/g++/int

web:
https://chriseth.github.io/browser-solidity/
Solidity realtime compiler and runtime
Version: 0.1.1-34172c3b/RelWithDebInfo-Emscripten/clang/int


I created automated python script to compile and extract & hash the relevant (longest) contract bytecode. Below are the hashes and file lengths:

    Created new hashfile hash/BoardRoom.linux2.txt.hash.6a029cdd4cf76ff821124814b1192c2049d362f11f0a4b275aa62ff30b2082f5.len.25122.txt
    ERROR! Created new hashfile hash/BoardRoom.web-error.txt.hash.0e3e26e880f6b6a366a5e0f20c4f347d1939b19e1b9bf88bffb4ed8fd7e8e027.len.97.txt
    Created new hashfile hash/BoardRoom.win32.txt.hash.bd29ec5bd71410557128143fda91f7851d006ae8aeaaa53a780a8e581377f9e2.len.25122.txt
    Created new hashfile hash/ExpRegistrar.linux2.txt.hash.e8e3a5156a0efc3302e35674d051da96f89e5a19913917d9c3ab94a7361dfc6f.len.11974.txt
    Created new hashfile hash/ExpRegistrar.web.txt.hash.e8e3a5156a0efc3302e35674d051da96f89e5a19913917d9c3ab94a7361dfc6f.len.11974.txt
    Created new hashfile hash/ExpRegistrar.win32.txt.hash.e8e3a5156a0efc3302e35674d051da96f89e5a19913917d9c3ab94a7361dfc6f.len.11974.txt
    Created new hashfile hash/Game.linux2.txt.hash.7c872a51ef00ff9248a352f35ab66e49b3cdd14879a2ac164c1d8f5071d28c59.len.12350.txt
    Created new hashfile hash/Game.web.txt.hash.7c872a51ef00ff9248a352f35ab66e49b3cdd14879a2ac164c1d8f5071d28c59.len.12350.txt
    Created new hashfile hash/Game.win32.txt.hash.1e78d6360e82466112c5c8813134d74cb51798358bb7ea031b77c98fac0d31a9.len.12350.txt
    Created new hashfile hash/Government.linux2.txt.hash.7ef99fbd3867c960dab78909542ef477809636c48ece72885cb2287752f79252.len.5368.txt
    Created new hashfile hash/Government.web.txt.hash.f1b19c1a77c12e7fceffbd2dba0710291d5173de0b2943ac97ecd7963473bc82.len.5368.txt
    Created new hashfile hash/Government.win32.txt.hash.4ecfd688296a9ebadec959bc100805243c3fdb71b699df5eebc08b8165454940.len.5368.txt
    Created new hashfile hash/Lotto.linux2.txt.hash.f15df945d4fbedb9d33654e222b3dfefd5abcb4978c54d1a282730d7aabe3700.len.4792.txt
    Created new hashfile hash/Lotto.web.txt.hash.f15df945d4fbedb9d33654e222b3dfefd5abcb4978c54d1a282730d7aabe3700.len.4792.txt
    Created new hashfile hash/Lotto.win32.txt.hash.bddf257c10137769197b1a44f8ed491cd1d8e9aa0c6e34610081d7a013bbcaa8.len.4792.txt
    Created new hashfile hash/SHA3compete.linux2.txt.hash.5bc8a617c1643fab601d476301087b3fb2548ff89de88dca02d6a8079cd9159b.len.6462.txt
    Created new hashfile hash/SHA3compete.web.txt.hash.0cf705b4ced76f71d1a79d70ac512accaa6a3ef7cdbff2662cc8035251de02b6.len.6462.txt
    Created new hashfile hash/SHA3compete.win32.txt.hash.0995393e96d412cc7a92422d2c483bc2e6f93215c3747ae545dbb1a5d568bc7d.len.6462.txt
    Created new hashfile hash/dice.linux2.txt.hash.2d0a04fdbc273f04c007596185ce593ada6dd1567a81776a0784063c6a5ad662.len.7424.txt
    Created new hashfile hash/dice.web.txt.hash.f9b3c072d9a91b07b0372b50297e6f95b5315f348fa8d6f6d511b252ed72d986.len.7424.txt
    Created new hashfile hash/dice.win32.txt.hash.e9d176ad6b25944f2a1dd6cfcd0d26ee2b1a218a77752f469f6a79a397fa1a41.len.7424.txt
    Created new hashfile hash/fun_distributor.linux2.txt.hash.c22bdc12c462228dcc51abef9c97822c90d897e322881a82bb8a36549ea62cb5.len.1454.txt
    Created new hashfile hash/fun_distributor.web.txt.hash.c22bdc12c462228dcc51abef9c97822c90d897e322881a82bb8a36549ea62cb5.len.1454.txt
    Created new hashfile hash/fun_distributor.win32.txt.hash.c22bdc12c462228dcc51abef9c97822c90d897e322881a82bb8a36549ea62cb5.len.1454.txt
    Created new hashfile hash/wallet.linux2.txt.hash.fe99309662249a7832b2841115ccb1c1de320f98673b767e90f8417143b5426e.len.12872.txt
    Created new hashfile hash/wallet.web.txt.hash.fe99309662249a7832b2841115ccb1c1de320f98673b767e90f8417143b5426e.len.12872.txt
    Created new hashfile hash/wallet.win32.txt.hash.b32a3c918b4eaf85c98d22a9f1c1a86fa3467ade45f3652202e8c2ae633466c2.len.12872.txt



Some files compile into same bytecode (fun_distributor, ExpRegistrar), some files have two matching and one different bytecode (Game, Lotto, wallet), others are completely off (dice, SHA3compete, Government). This is just the last run. I've made 4 test runs and there are differences among them as well.

Below is a zipped file of scripts, source files, compiled and extracted & hashed bytecode only files, if any additional information or testing is necessary.

https://drive.google.com/file/d/0B27o9CYAlaNjRkw4ZHRvd3ZmcGM/view?usp=sharing
https://www.dropbox.com/s/hey21bgdxehh8hu/solc-test.zip?dl=0

**Comment by LianaHus** [comment]
This issue has been moved to ethereum/solidity repository
https://github.com/ethereum/solidity/issues/17
