### ISSUE TITLE
Contracts cannot make external calls which modify their own internal state.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/cpp-ethereum#2845]
Consider the following contracts.

```
contract Sub {
        function add(int a, int b) public {
                int sum = a + b;
                msg.sender.call(bytes4(sha3("register(int256)")), sum);
        }
}

contract Master {
        int public retVal;

        function register(int value) public {
                retVal = value;
        }

        function delegated(address to, int a, int b) public {
                bytes32 argsHash = sha3(a, b);
                to.call(bytes4(sha3("add(int256,int256)")), a, b);
        }
}
```

These contracts implement a chain of function calls (using the low level `address.call(...)` way to call other contracts without knowledge of their code)

* `Master.delegate(...)` calls `Sub.add(..)`.
* `Sub.add(..)` does the computation and then calls `Master.register(...)` with the return value.
* `Master.register(...)` stores the value passed into it
* `Master.delegate()` should then be able to grab that value from it's own storage and use it.

However when `Sub.add()` calls `Master.register()` the call fails.  This can be verified by catching the return value of `msg.sender.call("...")` and logging it.

If in the above example, `Master.register()` is altered to not modify storage, the call begins succeeding.

This seems to indicate that a contract is not able to make an external call that results (in a round-about-way) to a modification of it's own storage.  

Is this a known limitation?  If so it seems significant and worth documenting because it basically eliminates the ability for contracts to communicate with each other in certain meaningful ways.

**Comment by pipermerriam** [comment]
Here is a link to the full source (with events) of the code I've been using to test this situation.

https://gist.github.com/pipermerriam/3bc8c8fc9e443fccd909#file-simple-sol

**Comment by pipermerriam** [comment]
Logs of this for anyone interested https://gist.github.com/pipermerriam/ae14b2bdfa9f4cc69f79

Contract Addresses are `Master: 0x20d609890d533acbf86fcc47a19d7af6b594f4eb` and `Sub: 0x9c3d19b95c7bb2ccd4fdfed4834d6cd0e56676e1`

**Comment by pipermerriam** [comment]
Ok, this is really weird.  From what I can tell, this will fail until `retVal` has had something assigned to it via some other mechanism, at which point it begins to work.  I really don't know what to make of this but it seems worth someone with deeper knowledge checking it out.

**Comment by chriseth** [comment]
Seems to be a gas issue. Do you use the gas value computed by AlethZero? That seems to be too low.

**Comment by pipermerriam** [comment]
Ultimately, I am unsure if there was actually any issue here at all despite not being able to zero in on anything I was doing incorrectly.  As for the gas, I was using a hard coded `1,000,000` gas which *should* be plenty for this sort of thing.  

I'm comfy closing this for now as I can't point to exactly what isn't working.
