### ISSUE TITLE
Gpu mining problem on Windows

### ISSUE THREAD

**Issue by zikilemini** [ethereum/cpp-ethereum#2846]
Hello,

I'm trying to mine with geth and ethminer. When i mine with my CPU everything works fine (but a bit slow). But when i'm trying to mine with my gpu it say that to me : 
"
E:\Ethereum\Release>ethminer -G
Found suitable OpenCL device [Pitcairn] with 2147483648 bytes of GPU memory
miner  23:46:36|main  Getting work package...
miner  23:46:36|main  Grabbing DAG for #356e5a2cÔÇª
  i  23:46:36|<unknown>  Loading full DAG of seedhash: #b903bd76ÔÇª
miner  23:46:36|main  Got work package:
miner  23:46:36|main    Header-hash: 502fb2cac3f8a1d490f507383fea7e8f74a5cc117ce20c8ba689fddb7e2732cb
miner  23:46:36|main    Seedhash: 356e5a2cc1eba076e650ac7473fccc37952b46bc2e419a200cec0c451dce2336
miner  23:46:36|main    Target: 000000000049519dfe4dd96a2329ed0cceeab7e2ccbb6a758a662dda28ecc9c0
  i  23:46:36|gpuminer0  workLoop 0 #00000000ÔÇª #356e5a2cÔÇª
  i  23:46:36|gpuminer0  Initialising miner...
miner  23:46:37|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 0.5 s
Using platform: AMD Accelerated Parallel Processing
  i  23:46:37|<unknown>  Full DAG loaded
Using device: Pitcairn(OpenCL 1.2 AMD-APP (1084.4))
miner  23:46:38|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 1.27 s
miner  23:46:38|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 1.773 s
miner  23:46:39|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 2.277 s
Printing program log
LOOP UNROLL: pragma unroll (line 266)
    Unrolled as requested!
LOOP UNROLL: pragma unroll (line 361)
    Unrolled as requested!
LOOP UNROLL: pragma unroll (line 361)
    Unrolled as requested!
LOOP UNROLL: pragma unroll (line 300)
    Unrolled as requested!
LOOP UNROLL: pragma unroll (line 300)
    Unrolled as requested!

Creating one big buffer for the DAG
Allocating/mapping single buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.
clEnqueueWriteBuffer(-38)
miner  23:46:39|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 2.781 s
miner  23:46:40|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 3.288 s
miner  23:46:40|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 3.795 s

[...]

miner  23:47:08|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 31.205 s
miner  23:47:08|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 31.712 s
miner  23:47:09|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 32.22 s
miner  23:47:09|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 32.728 s
miner  23:47:10|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 33.236 s
miner  23:47:10|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 33.744 s
miner  23:47:11|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 34.252 s
miner  23:47:11|main  Mining on PoWhash #502fb2caÔÇª : 0 H/s = 0 hashes / 34.76 s
miner  23:47:11|main  Got work package:
miner  23:47:11|main    Header-hash: f04234c486d10365ba1d7b84725ca57414db3a4ea8a6a612f5935531312cee2d
miner  23:47:11|main    Seedhash: 356e5a2cc1eba076e650ac7473fccc37952b46bc2e419a200cec0c451dce2336
miner  23:47:11|main    Target: 0000000000495ac95778c22637a0086ccd45dc35eaf04d9219ea1f0ff1a7b1ee"

And say no more. Somebody have the same issue ?

**Comment by LefterisJP** [comment]
>Creating one big buffer for the DAG
>Allocating/mapping single buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.

Your GPU does not have enough memory I am afraid. We can, at the moment, only support GPUs that have at least  2GB of memory and can allocate more than 1GB in a single chunk.

**Comment by zikilemini** [comment]
But my memori card ave 2 Go !

**Comment by LefterisJP** [comment]
> and can allocate more than 1GB in a single chunk.

This is a limitation that we have. Even if your card has 2GB, if it can't allocate more than 1GB (usual size of DAG in the first epochs) in one chunk then it can't GPU mine.

**Comment by LefterisJP** [comment]
One thing that may or may not work for you is to set the `GPU_MAX_ALLOC_PERCENT` environment variable to 95 as described [here](https://forum.ethereum.org/discussion/2737/some-cards-need-export-gpu-max-alloc-percent-95)

**Comment by zikilemini** [comment]
Ok i'll try.

But it's weird because when i try it on a PC with a bad Graphic card, it automatically says to me that i have not enough space and don't even try to begin the process.
