### ISSUE TITLE
Enable selection of transactions with cursor

### ISSUE THREAD

**Issue by kaeptnjoda** [ethereum/cpp-ethereum#2854]
Right now when a transactions in the right panel is selected, "arrow up" and "arrow down" open the file menu. "arrow up" and "arrow down" should navigate btw. transactions if a transaction is selected.  This might require to have a second level selection.

**Comment by gavofyork** [comment]
Please move all mix issues to [the Mix Issues repo](https://github.com/ethereum/mix/issues).
