### ISSUE TITLE
`constant` state vars do not create accessors

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/cpp-ethereum#2857]
contract Lotto{
        uint constant public ticketPrice = 1;
    }

no `ticketPrice` accessor is created

    solc --v
    solc, the solidity compiler commandline interface
    Version: 0.1.1-0/Release-Linux/g++/int

**Comment by LianaHus** [comment]
This issue has been moved to ethereum/solidity repository
https://github.com/ethereum/solidity/issues/16
