### ISSUE TITLE
Memory usage (Windows) way too high

### ISSUE THREAD

**Issue by Rav3nPL** [ethereum/cpp-ethereum#2860]
eth.exe/altethzero.exe memory usage is about 1.4GB private bytes (+160M working set) after sync.
Even Bitcoin Core is not that memory hungry.
ethminer.exe is eating 90MB+ private and 1.1GB+ in working set

**Comment by LefterisJP** [comment]
If you are mining this is expected. Your client also has to load the DAG file in memory in order to do so. The DAG file sizes are always over 1 GB. So are you mining when you see this?

**Comment by Rav3nPL** [comment]
```eth.exe -b -j  --upnp off --no-precompute```
1GB RAM in 10 mins after start

**Comment by LefterisJP** [comment]
Hmm so you are not mining. This then does not sound right. We need to investigate more.

Can you give us the exact version you are running? Did you use the installer?

**Comment by Rav3nPL** [comment]
Ethereum (++)-win64-latest.exe 
```
eth -V
eth version 0.9.40
eth network protocol version: 61
Client database version: 12041
Build: Windows/msvc/JIT/Release
```

**Comment by chfast** [comment]
When using GPU mining, can DAG be freed on the host after sent to GPU?

**Comment by LefterisJP** [comment]
@chfast Not with the current organization of the code. The miner gets initialized with the DAG data every workloop. With some rearranging we could enhance it and then initialize only once per epoch. 

Then we could probably free the DAG data at the host after a `cl_miner` has been initialized.
