### ISSUE TITLE
CUDA implementation of Ethash

### ISSUE THREAD

**Issue by Genoil** [ethereum/cpp-ethereum#2882]
When linking against extdep OpenCL.lib, my hashrate is almost 10% lower than when I link against NVidia CUDA 7.5RC.

**Comment by LefterisJP** [comment]
That's a known problem with NVidia OpenCL drivers. And unfortunately it's not happening only in Windows. 

We really need to incorporate your NVIDIA Cuda fork back into the main repo. Can you try and open a PR and attempt to make it work for all platforms? I can try and help with that.

**Comment by Genoil** [comment]
working on it :). but i don't have much time so be patient ;)
