### ISSUE TITLE
DAG file generation and update on epoch switch is unreliable

### ISSUE THREAD

**Issue by sammy007** [ethereum/cpp-ethereum#2885]
I noticed several issues with DAG:

1. After epoch switch some rigs still mine on old DAG:
<code>Invalid header on mined block: Block's nonce is invalid</code>.
This is very big loss (10% of the rigs are wasting power)

2. After node restart some rigs suddenly can start DAG regeneration without a reason (node in sync, epoch is the same).
3. After ethminer restart it can force DAG regeneration without a reason.

// ethminer, Windows rigs

**Comment by LefterisJP** [comment]
Hello and thanks for the bug report.

Can you try to create a minimal setup that would reproduce the problem and describe it here?

From your current description I can see that you are having some problems but I have no way to reproduce and investigate.

**Comment by gavofyork** [comment]
2 is a geth bug and is being addressed.

**Comment by gavofyork** [comment]
could do with additional information for 1.

**Comment by sammy007** [comment]
Regarding 1st issue I noticed many invalid blocks, this is clearly wrong DAG was used for mining, because after deleting all DAGs everything is fine now. Ethminer should smoothly handle epoch switch and don't use wrong DAGs for mining if node already switched to another epoch. Need more time for investigation how that happened, I have no logs from last switch.

**Comment by gavofyork** [comment]
It certainly *should* smoothly handle epoch switch. This may be another geth bug, though. Please run ethminer with high verbosity around the time of the epoch change.

**Comment by gavofyork** [comment]
@LefterisJP please put additional logging into `MinerAux`'s farm mode so we know exactly what is coming from geth and when. I want to know whether `seedHash` is valid or not.
