### ISSUE TITLE
Solidity intX, X != 256 not converted from internal representation when returned?

### ISSUE THREAD

**Issue by androlo** [ethereum/cpp-ethereum#2886]
Tried with web compiler and latest dev ubuntu PPA version (as of yesterday). This may be an error. First: If I use `uint128`, for example, and i set it to 1, the output will be `000...001`.

```
contract Property {
  uint128 public intVal;
  function Property() {
    intVal = 1;
   }
}
```

Output:
```
{ value: '0000000000000000000000000000000000000000000000000000000000000001',
  offset: undefined }
```

In the case of `int128`.

```
contract Property {
  int128 public intVal;
  function Property() {
    intVal = 1;
   }
}
```

Output:
```
{ value: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF80000000000000000000000000000000',
  offset: undefined }

```

Not using the current VM but I see in the assembly output that the values are being converted in the `Property` function - both in the case of `int`'s and `uint`'s, but i only see the back conversion in the getter function when it's `uint`'s.

**Comment by gavofyork** [comment]
please move to solidity repository.

**Comment by androlo** [comment]
oh. thanks.
