### ISSUE TITLE
Ethminer failed to submit hashrate

### ISSUE THREAD

**Issue by reignbeau** [ethereum/cpp-ethereum#2889]
Trying to mine on Geth with Ethminer, after failing to mine on Eth.

![screenshot from 2015-08-21 20 27 02](https://cloud.githubusercontent.com/assets/12384173/9422312/5bd5ecce-4843-11e5-9158-f481c5175727.png)

With Eth, the Ethminer does not give an error message but the total Hashes does not increment just like with Geth, although it used to.

![screenshot from 2015-08-21 20 31 30](https://cloud.githubusercontent.com/assets/12384173/9422323/d0e8e4a8-4843-11e5-9a0c-9fd36c918204.png)

Haven't mined anything in days on 4 different 290x running continuously.

Edit: Upgraded Geth to Version 1.1 and Ethminer still has the total time spent and total hashes wrong.

![screenshot from 2015-08-21 22 00 19](https://cloud.githubusercontent.com/assets/12384173/9422610/2ee77dec-4850-11e5-93f2-516ea6767fd3.png)

**Comment by sammy007** [comment]
I checked geth sources and realized that geth has no eth_submitHashrate handler. Can anyone tell me what a purpose of this method? it's mich better to add rig identity to ethminer instead of random id so people with many rigs can track who is down or does not submit shares.

**Comment by LefterisJP** [comment]
Geth's latest develop version implements `eth_submitHashrate()` so the next release will contain it. Absence of this function does not affect mining. It will just give you a warning.

Can you please elaborate on:
> With Eth, the Ethminer does not give an error message but the total Hashes does not increment just like with Geth, although it used to.

I am not sure I understand what you mean. Can you state:
 - Expected behaviour in detail. What it is that you expected to happen?
 - What actually happens and why you consider it to be a problem.

**Comment by reignbeau** [comment]
In prior versions, it would say
Ethminer Mining on PoWHash  50000000 H/s = 25000000 Hashes / 0.5 s
Ethminer Mining on PoWHash  50000000 H/s = 50000000 Hashes / 1.0 s
Ethminer Mining on PoWHash  50000000 H/s = 75000000 Hashes / 1.5 s
Ethminer Mining on PoWHash  50000000 H/s = 100000000 Hashes / 2.0 s

Ethminer would track the total time spent and total hashes done.

Now, it says
Ethminer Mining on PoWHash  50000000 H/s = 25000000 Hashes / 0.5 s
Ethminer Mining on PoWHash  50000000 H/s = 25000000 Hashes / 0.5 s
Ethminer Mining on PoWHash  50000000 H/s = 25000000 Hashes / 0.5 s
Ethminer Mining on PoWHash  50000000 H/s = 25000000 Hashes / 0.5 s

Based upon this change, I could not rule out the possibility that Ethminer was unable to send its work over to Geth/Eth and was simply restarting the mining process continuously. If you say it actually has no effect on mining, I will be inclined to believe you and assume that I have merely been having very bad luck.
