### ISSUE TITLE
cmake failed!

### ISSUE THREAD

**Issue by smartbitcoin** [ethereum/cpp-ethereum#2904]
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    EthPolicy

CMake Error at CMakeLists.txt:10 (eth_policy):
  Unknown CMake command "eth_policy".

-- Configuring incomplete, errors occurred!

**Comment by kmokeddem** [comment]
Same issue here

**Comment by General-Beck** [comment]
add git clone https://github.com/ethereum/cpp-ethereum-cmake
see https://github.com/ethereum/cpp-ethereum/wiki/Building-on-Ubuntu

**Comment by conradjohnson** [comment]
Still getting this and no instructions on the links provided.  

Where would I add this cpp-ethereum-cmake repository?  Next to my WebThree repo?  Inside?

**Comment by LefterisJP** [comment]
Look [here](https://github.com/ethereum/webthree-umbrella/wiki/Building-on-Linux) for instructions to build on Linux
