### ISSUE TITLE
No support for int[][] (string[], etc.) function parameters.

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/cpp-ethereum#2939]
`function f3(string[2] ss) {}` results in compiler error:
```
Type error: Internal type is not allowed for public and external functions.
    function f3(string[2] ss) {
                ^----------^
```
Looks like the ABI supports this, but the Solidity compiler doesn't

**Comment by gavofyork** [comment]
please place this in the solidity repository's issue tracker https://github.com/ethereum/solidity/issues.

**Comment by 5chdn** [comment]
just for refence https://github.com/ethereum/solidity/issues/40
