### ISSUE TITLE
Ethminer GPU failure handling

### ISSUE THREAD

**Issue by sammy007** [ethereum/cpp-ethereum#2940]
In multi AMD GPU rig if one GPU fails, ethminer does not produce hashes, but still polling for new work (sometimes it does not poll) and the rest of GPU still running under load and consume energy for nothing.

Rarely if one GPU fails, ethminer continue to run on the rest of GPUs, but failed GPU will never backup. I am wondering if it's possible to fix?

**Comment by LefterisJP** [comment]
What do you mean by `if one GPU fails`. What does a GPU failing mean?

**Comment by sammy007** [comment]
On a slightly downvolted GPU MSI Afterburner usually displays 0% or 100% load and this is a signal that card is sick/dead. If GPU operates fine it's 99% load. You can see on a screenshot that time in cmd and system time are different. This is a case when ethminer hang and 5th GPU load in afterburner has 0% load - sick.

![img_28082015_121228-1](https://cloud.githubusercontent.com/assets/7374093/9543189/3dac52f4-4d90-11e5-8c33-8b18d28e6a46.png)

**Comment by sammy007** [comment]
Another screenshot when miner polling for new job and does not mine, 1 of 5 GPU is sick.

![img_28082015_140012](https://cloud.githubusercontent.com/assets/7374093/9545103/e1c494e6-4d9f-11e5-8f62-ef9184ffe67c.png)

**Comment by sammy007** [comment]
Also, in 50% of rigs, miner won't hash until you click cmd window showing 100% CPU load. Problem appears after ethminer restart, after full system reboot everything is fine.
