### ISSUE TITLE
"Debug" builds not working on macos and windows

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#2948]
cc @arkpar @LefterisJP @chfast

**Comment by chfast** [comment]
Is it build issue? Or runtime issue?

**Comment by debris** [comment]
@chfast it is a build issue for multiconfiguration generators. although `Debug` works for me. What does not work is `RelWithDebugInfo`. Also the issue will be fixed in https://github.com/ethereum/cpp-ethereum/pull/2955

**Comment by chfast** [comment]
Have you used [CMAKE_CFG_INTDIR](http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_CFG_INTDIR.html)?
