### ISSUE TITLE
make[1]: *** [libethash/CMakeFiles/ethash.dir/all] Error 2 make: *** [all] Error 2

### ISSUE THREAD

**Issue by rverbee** [ethereum/cpp-ethereum#2960]
Build Output:

make -j6
[  4%] Built target scrypt
[  5%] Building CXX object libnatspec/CMakeFiles/natspec.dir/NatspecExpressionEvaluator.cpp.o
[  6%] Built target secp256k1
clang: error: unknown argument: '-fstack-protector-strong' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make[2]: *** [libnatspec/CMakeFiles/natspec.dir/NatspecExpressionEvaluator.cpp.o] Error 1
make[1]: *** [libnatspec/CMakeFiles/natspec.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target ethash
Scanning dependencies of target Sentinel.jsonstub
[  6%] Building C object libethash/CMakeFiles/ethash.dir/io.c.o
[  7%] Building C object libethash/CMakeFiles/ethash.dir/internal.c.o
[  7%] Building CXX object evmjit/libevmjit/CMakeFiles/evmjit.dir/JIT.cpp.o
clang: error: unknown argument: '-fstack-protector-strong' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make[2]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/JIT.cpp.o] Error 1
make[1]: *** [evmjit/libevmjit/CMakeFiles/evmjit.dir/all] Error 2
[  7%] Built target Sentinel.jsonstub
[  7%] Building C object libethash/CMakeFiles/ethash.dir/io_posix.c.o
[  8%] Building CXX object libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o
clang: error: unknown argument: '-fstack-protector-strong' [-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in the future
make[2]: *** [libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  8%] Built target ConfigInfo.h
[  8%] Built target BuildInfo.h
make[1]: *** [libethash/CMakeFiles/ethash.dir/all] Error 2
make: *** [all] Error 2

**Comment by timnugent** [comment]
I'm getting this issue too. All prerequisites installed with brew.

**Comment by debris** [comment]
Please build cpp-ethereum using [webthree-umbrella](https://github.com/ethereum/webthree-umbrella) from now on. Instructions are available [here](https://github.com/ethereum/webthree-umbrella/wiki/building)
