### ISSUE TITLE
alethone / alethzero cmake

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#2961]
The "appdmg" target is named generically which creates a conflict. (issue in eth_package macro)

CMake Error at /Users/home/cpp-ethereum-cmake/EthExecutableHelper.cmake:180 (add_custom_target):
  add_custom_target cannot create target "appdmg" because another target with

**Comment by debris** [comment]
It was caused by creating target with the same name (`appdmg`) in `eth_package` macro. This is fixed in https://github.com/ethereum/cpp-ethereum/pull/2955 . `eth_package` does not longer exist. Instead there is a macro called `eth_appdmg` which is called only one from main CMakeLists.txt file.
