### ISSUE TITLE
No GPU device with sufficient memory was found on 3Gb video memory

### ISSUE THREAD

**Issue by acid009** [ethereum/cpp-ethereum#2962]
Hi All,
I got this strange error trying to mine with ethminer on Radeon R9 280 and HD7950 both 3 Gb Ram.
Any suggestions on how to fix this ?

ethminer --list-devices shows correct output:

Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Tahiti
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2951741440
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] Tahiti
CL_DEVICE_TYPE: GPU
CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2951741440
CL_DEVICE_MAX_WORK_GROUP_SIZE: 256

Windows 7 64

thanks

**Comment by 5paceManSpiff** [comment]
I'm getting a similar error with my 3GB ASUS 7970.  I'm using the the `opencl-mesa` platform on `cpp-ethereum` running on a 64 bit arch linux system.

```
$ eth --list-devices
(++)Ethereum
Beware. You're entering the Frontier!
[OPENCL]:
Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] AMD TAHITI
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 1073741824
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 268435456
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
```

**Comment by chfast** [comment]
@5paceManSpiff in your case the OpenCL driver allows applications to allocate max 1GB of memory. The driver implementation probably takes that value out of nowhere. I had something similar with Intel's OpenCL implementation.

You might want to checkout the mesa source code and try to modify the part responsible for GPU memory limit.

**Comment by 5paceManSpiff** [comment]
@chfast Thanks for the advice.  I'm going to try compiling the development version of the driver before messing with the source code as my `opencl-mesa` package is one version behind.

**Comment by gamusin** [comment]
this is really strange with Claymore I don't get this error. Claymore has some sort of workaround or what? I'm stuck with claymore on linux, and I'm not using the open mesa drivers but the amdgpu pro drivers.
