### ISSUE TITLE
Solution validation in ethminer fails when a new work package arrives and in the meantime a solution for previous package is found

### ISSUE THREAD

**Issue by RoBiK75** [ethereum/cpp-ethereum#2967]
The file MinerAux.h in the ethminer project contains the method doFarm. This method sets up a callback that gets called when a new solution is found:

				bool completed = false;
				EthashProofOfWork::Solution solution;
				f.onSolutionFound([&](EthashProofOfWork::Solution sol)
				{
					solution = sol;
					return completed = true;
				});

The inner loop is checking for new work packages and if there is a new work package it changes the `current.headerHash`, `current.seedHash` and `current.boundary` variables:

					if (hh != current.headerHash)
					{
						current.headerHash = hh;
						current.seedHash = newSeedHash;
						current.boundary = h256(fromHex(v[2].asString()), h256::AlignRight);
						minelog << "Got work package:";
						minelog << "  Header-hash:" << current.headerHash.hex();
						minelog << "  Seedhash:" << current.seedHash.hex();
						minelog << "  Target: " << h256(current.boundary).hex();
						f.setWork(current);
					}

The inner loop exists once `completed` is set to true - which happens in the callback. If a new solution is found in the same loop iteration as when a new work package was received the loop exits. The problem is that the solution is checked against the new work package:

				cnote << "Solution found; Submitting to" << _remote << "...";
				cnote << "  Nonce:" << solution.nonce.hex();
				cnote << "  Mixhash:" << solution.mixHash.hex();
				cnote << "  Header-hash:" << current.headerHash.hex();
				cnote << "  Seedhash:" << current.seedHash.hex();
				cnote << "  Target: " << h256(current.boundary).hex();
				cnote << "  Ethash: " << h256(EthashAux::eval(current.seedHash, current.headerHash, solution.nonce).value).hex();
				if (EthashAux::eval(current.seedHash, current.headerHash, solution.nonce).value < current.boundary)
				{
					bool ok = rpc.eth_submitWork("0x" + toString(solution.nonce), "0x" + toString(current.headerHash), "0x" + toString(solution.mixHash));
					if (ok)
						cnote << "B-) Submitted and accepted.";
					else
						cwarn << ":-( Not accepted.";
				}
				else
					cwarn << "FAILURE: GPU gave incorrect result!";

Because `current.headerHash`, `current.seedHash` and `current.boundary` were overridden when the new work package arrived the check fails and we get the warning "FAILURE: GPU gave incorrect result!".

**Comment by speedmax** [comment]
+1 i can see this problem too

**Comment by sammy007** [comment]
Me too.
