### ISSUE TITLE
Errors cmake (fedora)

### ISSUE THREAD

**Issue by Sta7i0n** [ethereum/cpp-ethereum#2976]
I installed llvm-3.7 from source (in repo 3.5 max) and i have some errors:

-- test: ClientBase |  --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=10
-- test: JsonRpc |  --eth_testfile=BlockTests/bcJS_API_Test; --eth_testfile=BlockTests/bcValidBlockTest
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MHD_LIBRARY (ADVANCED)
    linked by target "jsconsole" in directory /home/station/test/cpp-ethereum/libjsconsole
    linked by target "ethereum" in directory /home/station/test/cpp-ethereum/libethereum
    linked by target "testutils" in directory /home/station/test/cpp-ethereum/libtestutils

-- Configuring incomplete, errors occurred!

**Comment by debris** [comment]
Please build cpp-ethereum using [webthree-umbrella](https://github.com/ethereum/webthree-umbrella) from now on. Instructions are available [here](https://github.com/ethereum/webthree-umbrella/wiki/building)

**Comment by debris** [comment]
also make sure, that you have all dependencies installed. It looks like you don't have microhttpd installed on your machine

**Comment by Sta7i0n** [comment]
CMake Error at webthree-helpers/cmake/UseQt.cmake:59 (find_package):
  By not providing "FindQt5WebEngine.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5WebEngine", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebEngine" with
  any of the following names:

    Qt5WebEngineConfig.cmake
    qt5webengine-config.cmake

qt5-qtbase already installed.

**Comment by Sta7i0n** [comment]
but after re-install amd catalyst I had this CMakeError.log

Determining if the CL_VERSION_2_0 exist failed with the following output:
Change Dir: /home/station/test/cpp-ethereum/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTryCompileExec3419932884/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec3419932884.dir/build.make CMakeFiles/cmTryCompileExec3419932884.dir/build
gmake[1]: Entering directory '/home/station/test/cpp-ethereum/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/station/test/cpp-ethereum/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec3419932884.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec3419932884.dir/CheckSymbolExists.c.o   -c /home/station/test/cpp-ethereum/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/home/station/test/cpp-ethereum/CMakeFiles/CMakeTmp/CheckSymbolExists.c: In function ‘main’:
/home/station/test/cpp-ethereum/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: ‘CL_VERSION_2_0’ undeclared (first use in this function)
   return ((int*)(&CL_VERSION_2_0))[argc];
                   ^
/home/station/test/cpp-ethereum/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/cmTryCompileExec3419932884.dir/build.make:57: recipe for target 'CMakeFiles/cmTryCompileExec3419932884.dir/CheckSymbolExists.c.o' failed
gmake[1]: Leaving directory '/home/station/test/cpp-ethereum/CMakeFiles/CMakeTmp'
gmake[1]: *** [CMakeFiles/cmTryCompileExec3419932884.dir/CheckSymbolExists.c.o] Error 1
Makefile:117: recipe for target 'cmTryCompileExec3419932884/fast' failed
gmake: *** [cmTryCompileExec3419932884/fast] Error 2

File /home/station/test/cpp-ethereum/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include </usr/include/CL/cl.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef CL_VERSION_2_0
  return ((int*)(&CL_VERSION_2_0))[argc];
#else
  (void)argc;
  return 0;
#endif
}

**Comment by hsanjuan** [comment]
For anyone landing here, the CL_VERSION_2_0 undeclared error was fixed by upgrading Cmake for me (from 3.0.2 to 3.5.2) in OpenSUSE.
