### ISSUE TITLE
VM trace BlockGasLimitReached exception

### ISSUE THREAD

**Issue by fe80ac** [ethereum/cpp-ethereum#2977]
I am trying to get a VM trace for a historical transaction using the admin_eth_vmTrace JSON RPC in eth/cpp-ethereum.

I trigger the call with curl and get no result:
```
% curl -X POST --data '{"jsonrpc":"2.0","method":"admin_eth_vmTrace","params":["0x8fadc1f1bbfdbdafee19e358cd5e3731cedd871f24be078c3aef071b8c78f470",6,"XXXXXXXXXXX="],"id":1}' http://localhost:8545

{"id":1,"jsonrpc":"2.0","result":null}
```

I believe that should return a VM trace for the transaction at index six of the block 0x8fadc1f1bbfdbdafee19e358cd5e3731cedd871f24be078c3aef071b8c78f470 (block #237,298, tx 0x87bc16547fe2be8f7e360df63ed1b88ca7a0c8b69cbc400681bc0be0e30761a8). 'XXXXXXXXXXX=' is the JSON RPC admin session key--if incorrect, the RPC returns an 'Invalid privilege' message.

When eth runs the command, it outputs a message like this:
```
 ✘  15:43:52|  /tmp/cpp-ethereum20150914-80200-1jb1ne0/libethereum/Executive.cpp(196): Throw in function void dev::eth::Executive::initialize(const dev::eth::Transaction &)
Dynamic exception type: boost::exception_detail::clone_impl
std::exception::what: BlockGasLimitReached
[dev::tag_required*] = 5000
[dev::tag_got*] = 21000
```

The same thing happens with other transactions.

This is an OS X homebrew install with `--with-vmtrace`. Here is some status/version info:

```
% curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' http://localhost:8545
{"id":1,"jsonrpc":"2.0","result":"0x3caa5"}
```

(0x3caa5 = 248,485 > 237,298)

```
% curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' http://localhost:8545

{"id":1,"jsonrpc":"2.0","result":"++eth-v0.9.41-ed7a8a35//Debug-Darwin/clang/int"}
```

```
% eth --version

eth version 0.9.41
eth network protocol version: 61
Client database version: 12041
Build: Darwin/clang/int/Debug
```

The same issue is reported under 0.9.42 here: https://forum.ethereum.org/discussion/3515/vm-trace-blockgaslimitreached-exception .

**Comment by fe80ac** [comment]
On a clean build of webthree-umbrella on Ubuntu 14.04, a similar message from eth:

```
  ✘  20:01:23|libmicrohttpd  /home/ubuntu/webthree-umbrella/libethereum/libethereum/Executive.cpp(194): Throw in function void dev::eth::Executive::initialize(const dev::eth::Transaction&)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::BlockGasLimitReached>
std::exception::what: BlockGasLimitReached
[dev::tag_required*] = 5000
[dev::tag_got*] = 1500000
```

Version:

```
% eth --version

eth version 0.9.92
eth network protocol version: 61
Client database version: 12041
Build: /g++/int/.
```

**Comment by mtbitcoin** [comment]
I am running into a similar message too (windows build 0.9.92)
