### ISSUE TITLE
Error: No such file or directory - test/testeth

### ISSUE THREAD

**Issue by aakilfernandes** [ethereum/cpp-ethereum#2980]
==> Installing cpp-ethereum from ethereum/homebrew-ethereum
==> Downloading http://52.28.164.97/job/ethbinaries-build/label=macosx_slave/16/artifact/webthree-umbrella/bu

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "cpp-ethereum"
Download failed: http://52.28.164.97/job/ethbinaries-build/label=macosx_slave/16/artifact/webthree-umbrella/build/cpp-ethereum-1.0rc2.yosemite.bottle.16.tar.gz
Warning: Bottle installation failed: building from source.
==> Cloning https://github.com/ethereum/webthree-umbrella.git
Updating /Library/Caches/Homebrew/cpp-ethereum--git
==> Checking out branch develop
Warning: EVMJIT needs the latest version of LLVM (3.7 or above), currently
only available with --HEAD. If an older version was already installed
or it did not install automatically, make sure to install it with
`brew install llvm --HEAD --with-clang`
==> cmake -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-et
==> make
==> make install
Error: No such file or directory - test/testeth

**Comment by aakilfernandes** [comment]
Seems to be happening with and without --devel

**Comment by aakilfernandes** [comment]
clang --version
    Apple LLVM version 7.0.0 (clang-700.0.72)
    Target: x86_64-apple-darwin14.5.0
    Thread model: posix

**Comment by jaguarg** [comment]
same issue here. Any idea?
clang --version
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by Zb3n** [comment]
same here

Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

**Comment by zynis** [comment]
I have the same issue...
