### ISSUE TITLE
alethzero not peering or downloading blockchain

### ISSUE THREAD

**Issue by SkillfulHacking** [ethereum/cpp-ethereum#2982]
After a  reboot of my pc I reloaded alethzero, entered my master password and the GUI loaded, then it was unable to download the chain/sync with peers.  I removed the folder containing the block chain thinking perhaps my copy wasn't valid for some reason. After doing so I continued to have the same issues.  At most I connect to 2 peers and often it drops back to one peer. Port 30303 is forwarded in the nat table on my router and previously I was able to download the whole 1GB+ chain.  I have since rebooted the computer again and attempted to run alethzero without being successful at making network connections that accommodate downloading of blocks.

**Comment by SkillfulHacking** [comment]
Is it possible I can get an update or perhaps some steps to troubleshoot the issue?  I am still down and unable to connect to the network.

**Comment by Goefells** [comment]
I went to Network, Connect To Peer, made sure Required was ticked, then went okay. Started updating the blockchain then. Hope that helps

**Comment by chriseth** [comment]
Please report it in github.com/ethereum/webthree-umbrella if this issue is still relevant.
