### ISSUE TITLE
Error reading - Abrupt peer disconnect: End of file

### ISSUE THREAD

**Issue by jpritikin** [ethereum/cpp-ethereum#2984]
eth 0.9.41+364SNAPSHOT20150819084559vivid-0ubuntu1

Today I started seeing errors in the log about disconnects:

````
⧎ ✘  14:59:37|p2p|dead745c…|Ethereum(J)/v1.0.0/Dev/Linux/Java  Error reading - Abrupt peer disconnect: End of file
⧎ ✘  14:48:04|p2p|2676755d…|pyethapp/v0.9.19/linux2/py2.7.9  Error reading - Abrupt peer disconnect: End of file
⧎ ✘  14:36:19|p2p|0a7d3a65…|Ethereum(J)/v1.0.0-stage/Dev/Mac/Java  Error reading - Abrupt peer disconnect: End of file
⧎ ✘  14:32:09|p2p|dead745c…|Ethereum(J)/v1.0.0/Dev/Linux/Java  Error reading - Abrupt peer disconnect: End of file
⧎ ✘  14:17:37|p2p|bafc7bba…|Geth/v1.2.0/linux/go1.5  Error reading - Abrupt peer disconnect: End of file
````

The errors seem to be coming from across different O/S platforms and different clients. I don't think these errors are stopping me from participating in the network. I still seem to be GPU mining with 11Mh/s.

Should I be worried?

**Comment by chriseth** [comment]
As long as you are still connected to some peers, this is nothing to worry about.

**Comment by jpritikin** [comment]
OK, I guess there is nothing to worry about :-)
