### ISSUE TITLE
Creating one big buffer for the DAG Allocating/mapping single buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing. clEnqueueWriteBuffer(-38)

### ISSUE THREAD

**Issue by danderson198** [ethereum/cpp-ethereum#2988]
Receiving this error. Wont mine.

**Comment by danderson198** [comment]
C:\Users\dande_000\Desktop\ethereum-mining-windows\ethminer-opencl-0.9.41>setx G
PU_MAX_ALLOC_PERCENT 95

SUCCESS: Specified value was saved.

C:\Users\dande_000\Desktop\ethereum-mining-windows\ethminer-opencl-0.9.41>setx G
PU_USE_SYNC_OBJECTS 1

SUCCESS: Specified value was saved.

C:\Users\dande_000\Desktop\ethereum-mining-windows\ethminer-opencl-0.9.41>setx C
L_DEVICE_MAX_MEM_ALLOC_SIZE 2147483648

SUCCESS: Specified value was saved.

C:\Users\dande_000\Desktop\ethereum-mining-windows\ethminer-opencl-0.9.41>ethmin
er.exe -G -F http://eth-us.suprnova.cc:3000/danderson198.1/5 -t 1
Found suitable OpenCL device [Cayman] with 2147483648 bytes of GPU memory
miner  20:05:10|main  Getting work package...
miner  20:05:10|main  Grabbing DAG for #526ee6e6ΓÇª
  i  20:05:11|<unknown>  Loading full DAG of seedhash: #3db89d40ΓÇª
miner  20:05:11|main  Got work package:
miner  20:05:11|main    Header-hash: a9f225967876375c99d454fd5d63db83f1614300ac0
f3241410fa50dd36af209
miner  20:05:11|main    Seedhash: 526ee6e688a9b3d466fe4a7355197a89898593509d75c5
70942cc73a5ca8299d
miner  20:05:11|main    Target: 0000000e5109ec205d7bea6a7ad66e448f8a5a6fc66fc9ca
c81e1fb408bef9b3
  i  20:05:11|gpuminer0  workLoop 0 #00000000ΓÇª #526ee6e6ΓÇª
  i  20:05:11|gpuminer0  Initialising miner...
miner  20:05:12|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.5 s
Using platform: AMD Accelerated Parallel Processing
  i  20:05:12|<unknown>  Full DAG loaded
Using device: Cayman(OpenCL 1.2 AMD-APP (1642.5))
miner  20:05:13|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.842
s
miner  20:05:13|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.604
s
miner  20:05:14|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.608
s
miner  20:05:15|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.659
s
miner  20:05:15|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.609
s
Printing program log

Creating one big buffer for the DAG
Allocating/mapping single buffer failed with: clCreateBuffer(-61). GPU can't all
ocate the DAG in a single chunk. Bailing.
clEnqueueWriteBuffer(-38)
miner  20:05:16|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.634
s
miner  20:05:16|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.616
s
miner  20:05:17|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.609
s
miner  20:05:18|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.604
s
miner  20:05:19|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 1.025
s
miner  20:05:19|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.649
s
miner  20:05:20|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.605
s
miner  20:05:21|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.602
s
miner  20:05:21|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.627
s
miner  20:05:22|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.602
s
miner  20:05:22|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.669
s
miner  20:05:23|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.797
s
miner  20:05:24|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.605
s
miner  20:05:24|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.624
s
miner  20:05:25|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.613
s
miner  20:05:26|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.607
s
miner  20:05:26|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.738
s
miner  20:05:27|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.64 s

miner  20:05:28|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.607
s
miner  20:05:28|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.607
s
miner  20:05:29|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.664
s
miner  20:05:30|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.61 s

miner  20:05:30|main  Mining on PoWhash #a9f22596ΓÇª : 0 H/s = 0 hashes / 0.611
s
miner  20:05:30|main  Got work package:
miner  20:05:30|main    Header-hash: aa88c64d17208c207695cf2047356bd1894a270e24d
e83b4863058e14ad8020b
miner  20:05:30|main    Seedhash: 526ee6e688a9b3d466fe4a7355197a89898593509d75c5
70942cc73a5ca8299d
miner  20:05:30|main    Target: 0000000e5109ec205d7bea6a7ad66e448f8a5a6fc66fc9ca
c81e1fb408bef9b3

**Comment by LefterisJP** [comment]
Your GPU does not have enough memory to mine.

**Comment by danderson198** [comment]
How many gigs of RAM is needed with ethminer? Do you know of another miner that I could use to mine Ethereum?

**Comment by dagelf** [comment]
The same error pops up even on cards that do have enough memory. 

Maybe the isolation between different OpenCL devices is buggy? 

I'm getting the same error when trying to mine with 2 x Radeon R9 270's - that run fine with geth, just ethminer that gives problems. If I manually specify only the last one, it works fine, first one I get this error. Boot into Windows, it runs fine, so either an ethminer or Linux AMD driver problem.

**Comment by bobsummerwill** [comment]
Thanks for the update, @dagelf!   Re-opening the issue.

**Comment by dagelf** [comment]
I can provide access to the rig if needed, or if I can see how it's fixed and what is looked for I might be drawn into ethereum dev... Seeing as that 14.04 will be supported through 2019, it might be worth figuring it out or at least documenting workarounds.

**Comment by gregbkr** [comment]
Hello, I got the same DAG error on windows8.1. After lot of investigation and reboot, I think the problem comes from graphic card driver & soft (for me catalys amd 6900 series). 

I can mine with default driver, but very low perf (I think) =5MH

    ethminer --list-devices 
    CL_DEVICE_GLOBAL_MEM_SIZE: 2 147 483 648
    CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1 877 999 616  --> 1.9GB (DAG ok)

With catalyst drivers, seems like whatever option I setx (+ some reboot), it is stuck on 500MB, so I can't create DAG. I understand somehow catalyst soft hardfixe that value.

    ethminer --list-devices 
    CL_DEVICE_GLOBAL_MEM_SIZE: 2 147 483 648
    CL_DEVICE_MAX_MEM_ALLOC_SIZE: 536 870 912 -->500MB (DAG FAILS)

I tried to install lastest amd drivers only without catalyst soft, but couldn't get the card detected, or just got the value hard stuck.

I will be glad to get any suggestion....

Thank you!

**Comment by bobsummerwill** [comment]
See also https://github.com/ethereum/libethereum/pull/203

**Comment by tommytcchan** [comment]
@dagelf I'm getting the same issue on 15.10. I tried you suggestion but I'm still getting an error. Did you have to do anything after `apt-get install fglrx`?

**Comment by dagelf** [comment]
It's very driver specific - my guess is that the default 15.10 fglrx driver
is too new. See if you can force the exact driver that 14.04 uses, or
download and install it manually from AMD's site or a cache (not sure if
they serve old versions)

**Comment by PontiacGTX** [comment]
Hello, I have this issue but running on win8.1 core 64bit,Catalyst 15.11.1, on pool mining with their proxy, but I just got this error after a week of mining and I tried deleting the DAGs on Ethash folder and it just generated a new DAG and got the program stuch at DAG fully loaded and then when i closed the proxy miner and the ethminer bat with the pool configuration  it got stuck with this error

**Comment by DrengorDraxlon** [comment]
I fixed this problem with a different environement variable.

GPU_SINGLE_ALLOC_PERCENT

  I've got mine set to 90.

**Comment by novice987** [comment]
I am getting same error "GPU can't allocate the DAG in a single chunk. Bailing. clEnqueueWriteBuffer(-38)" with the following device list.

ethminer --list-devices 

Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Intel(R) HD Graphics 5600
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 5109950055
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1277487513
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] GeForce GTX 960M
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 536870912
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

How can I fix it?

**Comment by l29ah** [comment]
Got this on HD7870 w/ 2GB RAM.
[OPENCL]:Using device: AMD PITCAIRN (DRM 2.43.0 / 4.6.3-grsec+, LLVM 3.8.1)(OpenCL 1.1 Mesa 12.1.0-devel (git-cfbf956))
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1503238553
Nothing else is occupying the GPU. I wonder what's the problem here.

**Comment by danderson198** [comment]
This may help idk for sure though cause I think I've tried it...idk 

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 12, 2016 at 11:15 AM, Sergey Alirzaev<notifications@github.com> wrote:   
Got this on HD7870 w/ 2GB RAM.
[OPENCL]:Using device: AMD PITCAIRN (DRM 2.43.0 / 4.6.3-grsec+, LLVM 3.8.1)(OpenCL 1.1 Mesa 12.1.0-devel (git-cfbf956))
 CL_DEVICE_TYPE: GPU
 CL_DEVICE_GLOBAL_MEM_SIZE: 2147483648
 CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1503238553
Nothing else is occupying the GPU. I wonder what's the problem here.

**Comment by l29ah** [comment]
Huh?

**Comment by Qalander** [comment]
I have NVIDIA 720M GTx and i tried to mine Ether, but got error ''GPU can’t allocate the DAG in a single chunk'' what should I do here.

**Comment by chfast** [comment]
How much VRAM?

**Comment by Qalander** [comment]
I set it at 12 GB min and max at 32 GB but after researching found that I need latest drivers and vram should be 16 GB  so I have to set it like that let me check if it works.

**Comment by shadowvex** [comment]
Setting GPU_SINGLE_ALLOC_PERCENT to 90 worked for me too.

**Comment by jaacsinpoker** [comment]
sgminer 5.5.5-gm - Started: [2019-07-26 23:37:08] - [0 days 00:00:08]                                                   --------------------------------------------------------------------------------                                        (5s):0.000 (avg):0.000h/s | A:0  R:0  HW:0  WU:0.000/m                                                                  ST: 2  SS: 0  NB: 2  LW: 7  GF: 0  RF: 0                                                                                Connected to eu1.ethermine.org (stratum) diff 4G as user 0x36ee666186474615778f82e3798a688dd56bf8d6                     Block: 9ce38d2b...  Diff:0  Started: [23:37:16]  Best share: 0                                                          --------------------------------------------------------------------------------                                        [P]ool management [G]PU management [S]ettings [D]isplay options [Q]uit                                                  GPU 0:  44.0C    0RPM | OFF   / 0.000h/s | R:  0.0% HW:0 WU:0.000/m xI:1024                                             --------------------------------------------------------------------------------                                        [23:37:06] Started sgminer 5.5.5-gm                                                                                     [23:37:06] * using Jansson 2.7                                                                                          [23:37:06] WARNING: GPU_USE_SYNC_OBJECTS is not specified!                                                              [23:37:06] Probing for an alive pool                                                                                    [23:37:07] Startup GPU initialization... Using settings from pool eu1.ethermine.org.                                    [23:37:07] Startup Pool No = 0                                                                                          [23:37:07] Initialising kernel ethash.cl with nfactor 10, n 1024                                                        [23:37:13] Error -61: Creating the DAG buffer failed.                                                                   [23:37:13] Error: clSetKernelArg of all params failed.                                                                  [23:37:13] GPU 0 failure, disabling!

**Comment by jaacsinpoker** [comment]
Mine is not working. I have the virtual memory config 3000-30000. What could it be?

**Comment by jaacsinpoker** [comment]
It is a rx580 radeon amd and even cudominer is not working with the gpu but it detects it.
