### ISSUE TITLE
Running Mix in a VM - requires software gl

### ISSUE THREAD

**Issue by liorsaar1** [ethereum/cpp-ethereum#2989]
As a user, I would like to run Mix in a vagrant/vb/x11 vm, since it doesn't build on mac osx 10.11.
This will require replacing the ```libgl1-mesa-dev``` dependency with ```libgl1-mesa-swx11```.
Any pointers on how I can do this myself will be appreciated.

**Comment by chriseth** [comment]
Please report in github.com/ethereum/mix thanks!
