### ISSUE TITLE
ethminer low GPU utilization on El Capitan

### ISSUE THREAD

**Issue by serkut-c** [ethereum/cpp-ethereum#2992]
On OS X 10.11.1, while in farming and benchmarking mode, `ethminer` reports the hash rate expected for the GPUs attached (R9 290 and R9 380). However, iStat Menus show low GPU utilization and cards remain cool. Number of shares submitted to pool are much lower than would be expected at the self-reported hash rate. The binaries used were built from source and, separately, via homebrew. `--cl-ms-per-block` and the worksize tuning parameters did increase utilization.

I can rule out hardware problems: Ethminer behaves as expected on the same machine in Windows.
OpenCL compatibility also does not seem like an issue: OpenCL benchmarking applications are able to heat up and cause high GPU utilization in iStat Menus.

Thanks!

**Comment by axic** [comment]
If this is still an issue please open one at https://github.com/ethereum-mining/ethminer
