### ISSUE TITLE
Latest Version crashes - JSON RPC Error - Probably cannot connect

### ISSUE THREAD

**Issue by billprescott** [ethereum/cpp-ethereum#2994]
Hi

Did an update today for ethminer and the miner has stopped working.. Now been mining for many months but the latest updates have stopped it from connecting to geth.

15.04 Ubuntu

Start using following

geth --rpc --rpccorsdomain localhost 2>> geth.log &
ethminer -G

Error - JSON RPC Error - Probably cannot connect 

repeats over and over.

Any suggestions?

thanks

Bill

**Comment by chriseth** [comment]
We switched all our c++ code to github.com/ethereum/webthree-umbrella could you please report the issue there?  Thanks!
