### ISSUE TITLE
dev::ExternalFunctionFailure

### ISSUE THREAD

**Issue by index932** [ethereum/cpp-ethereum#2997]
Hi Guys, I got this error and I am stuck. Both of my rigs are down. please advise. any help is greatly appreciated.

miner  11:44:26.215|ethminer  Mining on PoWhash #a5bc2433… : 0 H/s = 0 hashes / 0.5 s
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Tahiti(OpenCL 1.2 AMD-APP (1729.3))
miner  11:44:50.089|ethminer  Got work package:
miner  11:44:50.089|ethminer    Header-hash: 01aded3cd39a7d655bb5c34ec7b07536b363cbfde7fd6087ab58cc0c8df758e2
miner  11:44:50.089|ethminer    Seedhash: 1250db2965df18ca201a546442dab4fdea6f6ed1a13e86ed691dc897dcb9799c
miner  11:44:50.089|ethminer    Target: 00000000dbe6fecebdedd5beb573440e5a884d1b2fbf06fcce912adcb8d8422e
terminate called after throwing an instance of 'boost::exception_detail::clone_impldev::ExternalFunctionFailure'
  what():  std::exception
Aborted (core dumped)

**Comment by chriseth** [comment]
Please give some more information. Which version of ethminer do you use? Do you use it together with cpp-ethereum or go-ethereum? In both cases: Which version? Do you mine in a pool or do you solo mine?

The error says "core dumped" which means it created a file called `core`. Can you send that over to us?
