### ISSUE TITLE
Ubuntu stopped mining and syncing unexpectly

### ISSUE THREAD

**Issue by Viking-yu** [ethereum/cpp-ethereum#3005]
Using eth 1.2.2 on Ubuntu 14.04 LTS. Setup to mine but always stop running after a few minutes. What's wrong? Appreciate any help.

The output of console is following:

`-> % sudo eth -i -v 1 -a 0x00b5bc422c05e94146209f2ac7047ef05a6ebbba  -x 50 -m on -G`
(++)Ethereum
[OPENCL]:Found suitable OpenCL device [GeForce GTX 750] with 2146762752 bytes of GPU memory

Please enter your MASTER password: 
cpp-ethereum 1.2.2
  By cpp-ethereum contributors, (c) 2013-2016.
  See the README for contributors and credits.
Transaction Signer: XE072ZGXMSHVUS8HM9MFJF2UDQLMA9CP8A (710ef39a-53d2-9a8d-f272-c6b51e941a90 - 00b5bc42)
Mining Beneficiary: XE072ZGXMSHVUS8HM9MFJF2UDQLMA9CP8A (710ef39a-53d2-9a8d-f272-c6b51e941a90 - 00b5bc42)
Foundation: XE55PXQKKK4B9BYPBGT1XCYW6R5ELFAT6EM (00000000-0000-0000-0000-000000000000 - de0b2956)
  ℹ  17:35:39.638|p2p  UPnP device: http://192.168.1.1:5000/rootDesc.xml [st: urn:schemas-upnp-org:device:InternetGatewayDevice:1 ]
Node ID: enode://d463f732e694891725b0d8067111f5b54cf7f1c813b4c806cf043bba8a70f9e699da06453089e4ed0cb9ac0b3cf735bad4c039b1aa4b5a4c47bc4f87b5e53b9d@100.93.175.23:30303
JSONRPC Admin Session Key: W+2QQ0cObZ0=
  ℹ  17:35:39.832|gpuminer0  workLoop 0 #00000000… #39238891…
  ℹ  17:35:39.832|gpuminer0  Initialising miner...
[OPENCL]:Using platform: NVIDIA CUDA
[OPENCL]:Using device: GeForce GTX 750(OpenCL 1.2 CUDA)
[OPENCL]:Printing program log
[OPENCL]:

[OPENCL]:Creating one big buffer for the DAG
[OPENCL]:Loading single big chunk kernels
[OPENCL]:Mapping one big chunk.
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
  ℹ  17:35:56.549|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:35:56.846|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:35:57.014|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:35:57.180|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:35:57.609|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:36:00.256|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:36:00.425|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:36:00.593|gpuminer0  workLoop 1 #39238891… #39238891…
......
 ℹ  17:39:06.496|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:39:06.664|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:39:08.756|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:39:10.229|gpuminer0  workLoop 1 #39238891… #39238891…
  ℹ  17:39:10.388|gpuminer0  workLoop 1 #39238891… #39238891…

**** then no any output. check the state of mining as following: ****
>web3.eth
 syncing: {
    currentBlock: 1171534,
    highestBlock: 1171544,
    startingBlock: 1171520
  },
 blockNumber: 1171534,
defaultBlock: 'latest',
...

>web3.net
...
peerCount: 17,
....

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/webthree-umbrella/issues/380.
