### ISSUE TITLE
ethminer  Dynamic exception type: jsonrpc::JsonRpcException std::exception::what: Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out

### ISSUE THREAD

**Issue by dikpuncher** [ethereum/cpp-ethereum#3010]
out of the blues i get this,

Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out

**Comment by Tyler-H** [comment]
Run geth with the command `geth --rpc` first
