### ISSUE TITLE
On Running Mix Getting below Error

### ISSUE THREAD

**Issue by haldhar** [ethereum/cpp-ethereum#3011]
QOpenGLShader: could not create shader
shader compilation failed:
""
QOpenGLShaderProgram::uniformLocation( matrix ): shader program is not linked
QOpenGLShaderProgram::uniformLocation( color ): shader program is not linked
QOpenGLShaderProgram::uniformLocation( textureScale ): shader program is not lin
ked
QOpenGLShaderProgram::uniformLocation( dpr ): shader program is not linked
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed:
""
QOpenGLShaderProgram::uniformLocation( qt_Matrix ): shader program is not linked

QOpenGLShaderProgram::uniformLocation( opacity ): shader program is not linked
QOpenGLShaderProgram: could not create shader program
QOpenGLShader: could not create shader
QOpenGLShader: could not create shader
shader compilation failed:
""
QOpenGLShaderProgram::uniformLocation( qt_Matrix ): shader program is not linked

QOpenGLShaderProgram::uniformLocation( opacity ): shader program is not linked
![error](https://cloud.githubusercontent.com/assets/9881711/14374624/b2e7317a-fd75-11e5-8b9a-cf584c892b65.PNG)

**Comment by bobsummerwill** [comment]
Moved to https://github.com/ethereum/mix/issues/292.
