### ISSUE TITLE
Install Failure: ValueError, "insecure string pickle"

### ISSUE THREAD

**Issue by raineorshine** [ethereum/cpp-ethereum#3016]
I am trying to install the Mix IDE but am getting an error when I try to install via brew. It fails at the qt5 make step. Running OSX 10.11.4.

```
$ brew install cpp-ethereum --with-gui
```

Excerpt from `/Users/raine/Library/Logs/Homebrew/qt5/02.make`:

```
...
bootstrapping ninja...
Traceback (most recent call last):
  File "configure.py", line 436, in <module>
    if has_re2c():
  File "configure.py", line 432, in has_re2c
    proc = subprocess.Popen(['re2c', '-V'], stdout=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
/private/tmp/qt5-20160504-33639-1g1pghg/qt-everywhere-opensource-src-5.6.0/qtwebengine/src/3rdparty/ninja/ninja  -C /private/tmp/qt5-20160504-33639-1g1pghg/qt-everywhere-opensource-src-5.6.0/qtwebengine/src/core/Release
make[4]: /private/tmp/qt5-20160504-33639-1g1pghg/qt-everywhere-opensource-src-5.6.0/qtwebengine/src/3rdparty/ninja/ninja: No such file or directory
make[4]: *** [invoke_ninja] Error 1
make[3]: *** [sub-gyp_run-pro-make_first] Error 2
make[2]: *** [sub-core-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtwebengine-make_first] Error 2
make: *** Waiting for unfinished jobs....
...
```

[This description of the error](http://stackoverflow.com/questions/1746825/python-valueerror-insecure-string-pickle) does not offer much that I can apply to this situation.

I have even fully uninstalled homebrew and re-installed it, same problem. Could anyone offer some help?

**Comment by bobsummerwill** [comment]
Hey.   Are you the same person as "metaraine" from ...

https://gitter.im/ethereum/cpp-ethereum?at=570eb13f3ddb73ba105bce6e

Same issue?   Same machine?

**Comment by raineorshine** [comment]
Yes. Same machine, same face :P.

**Comment by bobsummerwill** [comment]
Did you try nuking your whole Homebrew setup?   Uninstall that as a whole, and reinstall Homebrew, then packages?

**Comment by raineorshine** [comment]
Yes, as mentioned in the ticket, I uninstalled all of Homebrew and
re-installed. Same issue.

**Comment by bobsummerwill** [comment]
OK - so I think you next step needs to be logging a ticket on https://github.com/Homebrew/homebrew with regard to that Qt5 formula, asking for their help.    If they don't have bright ideas (though they probably will - they are very savvy!) then you might need to talk to the Qt5 team.

Good luck!    Sorry that you are hitting such a weird and unique issue :-(

Another option is trying the DMG (which is for Yosemite but *might* work on El Capitan too):
https://github.com/ethereum/webthree-umbrella/releases/download/v1.2.4/cpp-ethereum-v1.2.4.dmg

I'm working on finishing up El Capitan automation at the moment.     There is also a known issue where that DMG seems to contain an older version of Mix, but it does not.    On Yosemite at least :-(

**Comment by raineorshine** [comment]
Thank you! I didn't know I could just try the Yosemite DMG. It installed
and I was able to create a new project, so good so far!

**Comment by bobsummerwill** [comment]
OK - I'll close this issue.   Good luck!
