### ISSUE TITLE
OSX Mix keeps crashing - how to report

### ISSUE THREAD

**Issue by miohtama** [ethereum/cpp-ethereum#3017]
OSX Mix keeps crashing me under normal usage (editing transactions) for every 1-2 minutes. 

How to get stacktraces and report issues?

**Comment by bobsummerwill** [comment]
Sorry, @miohtama,
Only just spotted this issue.

Mix has been discontinued.   See https://blog.ethereum.org/2016/07/08/c-dev-update-summer-edition/.

Some alternatives are listed on http://solidity.readthedocs.org
