### ISSUE TITLE
ethminer 100% CPU and no log with three GPUs, works with two

### ISSUE THREAD

**Issue by slundell** [ethereum/cpp-ethereum#3019]
I use an old mobo that I had laying around, with three pcie ports (one 16x, and two 1x). Using powered pcie1x->pci16x risers I attatch three GPUs (various amd cards). I use ubuntu wily and start ethminer in rc.local.

When I have two cards attached, everything works just fine. Hashing along at the expected rate. When I add the third card (no matter which card or slot it seems) ethminer will not start.

It hogs the CPU at 100% (let it run for over an hour to no avail) and outputs nothing to stderr or stdout. Not even that detected the GPU or anything.

All three cards are detected fine by ubuntu and is shown correctly with "lspci | grep VGA".

I use an antec 1200W power supply, so power should not be an issue (in that case there should at least be some init messages in the log, and problems arise first when mining actually starts)

a plain "ethminer -G -M" exhibits the same problem. I have noticed that it seems to run only one process when this error occurs, when it works (with two cards) it uses two or more processes.

ethminer version is 1.2.4

**Comment by bobsummerwill** [comment]
Thanks for the report, @slundell.

Have you tried http://github.com/Genoil/cpp-ethereum?

That CUDA miner has been given a lot more love that the official miner, and might give you better results.

We do plan to upstream its changes, if we are able to, but in the meantime, you might be better trying to use that fork.

**Comment by axic** [comment]
If this is still an issue please open one at https://github.com/ethereum-mining/ethminer

**Comment by DeadManWalkingTO** [comment]
I found some tweaks for windows 10 and achieve more than 50% less CPU usage.

New CPU Usage: 45% 

[Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW)
Just let me know about your results.

Have a nice mining!
