### ISSUE TITLE
Mix-ide not responding on start

### ISSUE THREAD

**Issue by ResourceHog** [ethereum/cpp-ethereum#3021]
The mix ide starts but everything is grayed out and is stuck in a "not responding" state.

**Comment by bobsummerwill** [comment]
Please could you log this issue against http://github.com/ethereum/mix?   Thanks!   Please can you also list your operating system, and whether you built it yourself, etc.

Also, be aware .... https://gitter.im/ethereum/mix?at=57570ee9662b042b7e594571.   Thanks!
