### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by PontiacGTX** [ethereum/cpp-ethereum#3022]
solved

**Comment by bobsummerwill** [comment]
Your best form of help on mining is outside of the Ethereum Foundation, though we do have some miners on https://gitter.im/ethereum/cpp-ethereum now.

https://gitter.im/ethereum/minercommunitysupport
https://www.reddit.com/r/ethermining
http://ethereum.stackexchange.com/?tags=mining

Also, have you tried the @Genoil miner?   http://github.com/Genoil/cpp-ethereum?    If not, you should.

See http://github.com/ethereum/webthree-umbrella/issues/313 and github.com/ethereum/webthree-umbrella/issues/315.

**Comment by PontiacGTX** [comment]
Both miners do the same
and it seems none driver allow to change core clocks with voltages

**Comment by PontiacGTX** [comment]
Here I found a issue on event viewer

Faulting application name: ethminer.exe, version: 0.0.0.0, time stamp: 0x55d441bd
Faulting module name: amdocl64.dll, version: 10.0.2079.4, time stamp: 0x57509edb
Exception code: 0xc0000005
Fault offset: 0x0000000000e2aaed
Faulting process id: 0x136c
Faulting application start time: 0x01d1d14b5f8372e5
Faulting application path: C:\Program Files\Ethereum 0.9.41\Release\ethminer.exe
Faulting module path: C:\Windows\SYSTEM32\amdocl64.dll
Report Id: 7165de17-bb11-48d7-b7c1-f17a9e6701d6
Faulting package full name: 
Faulting package-relative application ID:

**Comment by PontiacGTX** [comment]
the issue from windows report

Problem signature
Problem Event Name:	APPCRASH
Application Name:	ethminer.exe
Application Version:	0.0.0.0
Application Timestamp:	55d441bd
Fault Module Name:	amdocl64.dll
Fault Module Version:	10.0.2079.4
Fault Module Timestamp:	573929ee
Exception Code:	c0000005
Exception Offset:	0000000000e2baad
OS Version:	10.0.10586.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	1618
Additional Information 2:	1618dcc8ca7e37b662bb620ca1ae2f71
Additional Information 3:	f80f
Additional Information 4:	f80ff3627ab563c6df6432748492dc6c
