### ISSUE TITLE
opencl 2.0 error - can't enable all OpenCL extensions or unrecognized OpenCL extension

### ISSUE THREAD

**Issue by AgeManning** [ethereum/cpp-ethereum#3023]
I am not sure if anyone else has this issue. I've updated to latest opencl AMD drivers on an up to date arch linux distro. I get the following error when running ethminer. I'm using opencl 2.0 and 1.2 drivers.

[OPENCL]:"/tmp/OCL4733T2.cl", line 11: error: can't enable all OpenCL extensions or
unrecognized OpenCL extension
#pragma OPENCL EXTENSION cl_clang_storage_class_specifiers : enable
^
1 error detected in the compilation of "/tmp/OCL4733T2.cl".
Frontend phase failed compilation.

The error is caused by the line 
"#pragma OPENCL EXTENSION cl_clang_storage_class_specifiers : enable" 
in
libethereum/libethash-cl/ethash_cl_miner_kernel.cl

which was added in the following commit:

80b971951092ddfb8f2affdd6d1083f238a62a2a

If other's have this issue, simply remove the #pragma line and re-compile. 
Cheers

**Comment by bobsummerwill** [comment]
Oh dear, sorry about that, @AgeManning.

https://github.com/ethereum/libethereum/commit/80b971951092ddfb8f2affdd6d1083f238a62a2a

That change was from @lvella to enable Mesa Open Drivers.

Do either of you know if there is some conditional we can add here?

like "If extension available then enable extension"

I am very ignorant on OpenCL, I am afraid.

**Comment by lvella** [comment]
According to [the docs](https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/EXTENSION.html), surrounding the offending line with:

```
#ifdef cl_clang_storage_class_specifiers
#pragma OPENCL EXTENSION cl_clang_storage_class_specifiers : enable
#endif
```

Should fix the problem everybody. Please test it, and prefer this solution over removing the line. Sorry about that.

**Comment by AgeManning** [comment]
Tested. Can confirm this fixes the issue. 
Cheers, guys

**Comment by bobsummerwill** [comment]
Committed.   Thanks!

https://github.com/ethereum/libethereum/pull/322
