### ISSUE TITLE
ethminer -G segmentation fault

### ISSUE THREAD

**Issue by pelisboule** [ethereum/cpp-ethereum#3033]
I'm having a very weird issue... My rig has 3 RX 480 and it seems unstable as soon as I install the driver. I've tested all OS (windows 8 32 bits, 8.1 64 bits, Windows 10, Ubuntu server) and I'm now on an Ubuntu Desktop LTS 16.04.

I managed to install the AMD drivers but lost the X11 interface so I'm connected using SSH.

As I'm a big noob I've struggled for days to get ethminer installed and it's now setup from apt-get (couldn't get the git version to work).

ethminer runs well (but no hashrate) but when I type -G I have the following error:

```
~/Downloads/cpp-ethereum/build$ ethminer -G
Segmentation fault
```

But when typing ethminer -F $URL I have the following issue:

```
miner  10:47:27.154|ethminer  Getting work package...
  ✘  10:47:27.307|ethminer  Failed to submit hashrate.
  ✘  10:47:27.307|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 52

JSON-RPC problem. Probably couldn't connect. Retrying in 1... 
```

I'm totally stuck and have exhausted all my options, can you please help? Just for information, I don't have the blockchain locally as I'm trying to mine from a pool.

Many thanks in advance,

**Comment by bobsummerwill** [comment]
Hey, @pelisboule,

Have you tried ...

- https://gitter.im/ethereum/minercommunitysupport
- https://reddit.com/r/ethermining
- http://ethereum.stackexchange.com/questions/tagged/mining

The mining community are by the experts here.

Also, have you tried @Genoil's ethminer?   http://github.com/Genoil/cpp-ethereum, which has a lot more love paid to it than the official miner.

Those see github.com/ethereum/webthree-umbrella/issues/313 and github.com/ethereum/webthree-umbrella/issues/315.

Best wishes!

**Comment by pelisboule** [comment]
HI @bobsummerwill, thanks for the feedback ;)

I've tried the gitter community and they redirected me here. Couldn't find any useful answer on reddit and I thought github was more suitable than stackexchange for that issue if it is an issue?

Regarding Genoil I've tried to install it but got too many errors I finally dropped the idea as I couldn't get around the compilation process :(

What are the two last links?

**Comment by bobsummerwill** [comment]
Sorry - fixed those URLs.

Essentially, ethminer is very unloved.   I hope to improve on that, with a first step being to upstream Genoil's changes.

Right now, the official miner is pretty much "at your own risk".    If it doesn't work for you, then you may well be out of luck :-(

**Comment by pelisboule** [comment]
ok I get it, so you advise me to switch on Genoil?

**Comment by bobsummerwill** [comment]
Yes, I would.   It's the best option for right now.

Good luck :-)

**Comment by 5chdn** [comment]
fyi, there are also 3 questions with the same title on stack exchange.

- http://ethereum.stackexchange.com/q/2667/87
- http://ethereum.stackexchange.com/q/8039/87
- http://ethereum.stackexchange.com/q/7931/87

**Comment by bobsummerwill** [comment]
Thanks for the links, @5chdn, but there is no quick fix coming here.

The official `ethminer` is effectively unsupported.

This is something which I hope to address with http://github.com/ethereum/webthree-umbrella/issues/313 and http://github.com/ethereum/webthree-umbrella/issues/315, and have been working to make possible for several months.

If you would like to point those StackExchange issues here, and/or merge them then please do.

But the bottom line at the moment really is "Use @Genoil's ethminer", if that doesn't work then sorry, you are out of luck right now, unless you are a software engineer who can troubleshoot and help to fix the issue.

**Comment by axic** [comment]
If this is still an issue please open one at https://github.com/ethereum-mining/ethminer
