### ISSUE TITLE
CI/Windows: tests.bat script does not check any errors

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3039]
The script https://github.com/ethereum/cpp-ethereum/blob/develop/scripts/tests.bat that is responsible to run tests on Windows does not check any return codes from the test tools. It looks that the script does not even reach the end -- https://ci.appveyor.com/project/bobsummerwill/cpp-ethereum/build/1.0.50#L1661

**Comment by bobsummerwill** [comment]
The tests do reach the end and complete, but you are quite right in nothing that the error handling is missing, and we should fix that ASAP.

This is expected.   The GitHub deployment is whitelisted onto to occur from the `release` branch, so that turns into a null-op at the end there.

    Skip "GitHub" deployment as no branches matched (build branch is "develop", deploy on branches "rel

**Comment by chfast** [comment]
Maybe we should switch to PowerShell on AppVeyor? It supports global flag to stop on error. http://stackoverflow.com/questions/9948517/how-to-stop-a-powershell-script-on-the-first-error

**Comment by bobsummerwill** [comment]
Yes.   It would actually be better to use PowerShell than batch, which is very limited.

I've not done any PowerShell myself before.   Have you?

But yeah - we should switch.

**Comment by chfast** [comment]
I have not tried either but I will.
