### ISSUE TITLE
Modify dockerfile to run as user

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3053]
The current dockerfile at https://github.com/ethereum/cpp-ethereum/blob/develop/scripts/Dockerfile is built by docker hub https://hub.docker.com/r/ethereum/client-cpp/ and the way to run it is as follows:

    sudo docker run --net=host -v ~/.ethereum:/root/.ethereum -v ~/.web3:/root/.web3/ ethereum/client-cpp

So the ethereum data file of the current user on the host is made available inside the docker container. The problem is that this way, as the default user to run inside the container is root, all files in the host directory are later owned by root.

This issue is about changing the docker file and documenting the command to run it, so that the user used inside the container coincides with the user starting the process.

**Comment by chriseth** [comment]
anyone: Please feel free to take this if you know something about docker (or want to learn how to use it)!

**Comment by konradkonrad** [comment]
I'll take this one :)

**Comment by chriseth** [comment]
Fixed in the PR.
