### ISSUE TITLE
Brew install error "Could not find remote branch merge_repos"

### ISSUE THREAD

**Issue by him0** [ethereum/cpp-ethereum#3064]
I tried to install cpp-ethereum via brew, and failed. Running OSX 10.11.6.

```
$ brew -v
Homebrew 0.9.9 (git revision 7b1c5; last commit 2016-08-20)
Homebrew/homebrew-core (git revision 7f296; last commit 2016-08-19)
$ brew update 
Already up-to-date.
$ brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/bobsummerwill/cpp-ethereum.git
Cloning into '/Users/xxx/Library/Caches/Homebrew/cpp-ethereum--git'...
warning: Could not find remote branch merge_repos to clone.
fatal: Remote branch merge_repos not found in upstream origin
Error: Failed to download resource "cpp-ethereum"
Failure while executing: git clone --depth 1 --branch merge_repos https://github.com/bobsummerwill/cpp-ethereum.git /Users/xxx/Library/Caches/Homebrew/cpp-ethereum--git
```

**Comment by bobsummerwill** [comment]
Oh dear.

Please can you try again?   It should work now, after https://github.com/ethereum/homebrew-ethereum/pull/84.

**Comment by him0** [comment]
Thank you for fixing, it works 👍 

```
$ brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Cloning into '/Users/xxx/Library/Caches/Homebrew/cpp-ethereum--git'...
remote: Counting objects: 1416, done.
remote: Compressing objects: 100% (732/732), done.
remote: Total 1416 (delta 744), reused 1164 (delta 673), pack-reused 0
Receiving objects: 100% (1416/1416), 1.99 MiB | 423.00 KiB/s, done.
Resolving deltas: 100% (744/744), done.
Checking connectivity... done.
==> Checking out branch develop
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/cpp-ethereum/1.3.0 -D
==> make
==> make install
==> Caveats
To have launchd start ethereum/ethereum/cpp-ethereum now and restart at login:
  brew services start ethereum/ethereum/cpp-ethereum
==> Summary
🍺  /usr/local/Cellar/cpp-ethereum/1.3.0: 36 files, 24.6M, built in 25 minutes 26 seconds
```

**Comment by bobsummerwill** [comment]
Works for me - please scream if you are still having issues!   Thanks for the report.

**Comment by bobsummerwill** [comment]
Hurray!   Thanks for the confirmation.

When we are hooked hack up to TravisCI, we will have bottles again too, so there is no need to suffer a 25 minute wait :-)

**Comment by alailsonribeiro** [comment]
MacBook-Pro-de-Alailson:xgminer alailsonribeiro$ brew install cpp-ethereum
==> Installing cpp-ethereum from ethereum/ethereum
==> Installing dependencies for ethereum/ethereum/cpp-ethereum: cmake, gperftools, snappy, leveldb
==> Installing ethereum/ethereum/cpp-ethereum dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.12.1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring cmake--3.12.1.high_sierra.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.12.1: 2,417 files, 33.6MB
==> Installing ethereum/ethereum/cpp-ethereum dependency: gperftools
==> Downloading https://homebrew.bintray.com/bottles/gperftools-2.7.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gperftools--2.7.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/gperftools/2.7: 103 files, 4.3MB
==> Installing ethereum/ethereum/cpp-ethereum dependency: snappy
==> Downloading https://homebrew.bintray.com/bottles/snappy-1.1.7_1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring snappy--1.1.7_1.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/snappy/1.1.7_1: 18 files, 118.1KB
==> Installing ethereum/ethereum/cpp-ethereum dependency: leveldb
==> Downloading https://homebrew.bintray.com/bottles/leveldb-1.20_2.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring leveldb--1.20_2.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/leveldb/1.20_2: 26 files, 1.2MB
==> Installing ethereum/ethereum/cpp-ethereum
==> Cloning https://github.com/ethereum/cpp-ethereum.git
Cloning into '/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git'...
warning: Could not find remote branch develop to clone.
fatal: Remote branch develop not found in upstream origin
Error: Failed to download resource "cpp-ethereum"
Failure while executing; `git clone --depth 1 --branch develop https://github.com/ethereum/cpp-ethereum.git /Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git` exited with 128. Here's the output:
Cloning into '/Users/alailsonribeiro/Library/Caches/Homebrew/cpp-ethereum--git'...
warning: Could not find remote branch develop to clone.
fatal: Remote branch develop not found in upstream origin

**Comment by bobsummerwill** [comment]
I don't believe that the Homebrew is being maintained anymore, eh, @axic?
It should probably be deleted if that is the case.

**Comment by alailsonribeiro** [comment]
See [https://github.com/ethereum/homebrew-ethereum/issues/185](url)
