### ISSUE TITLE
Super noob warning - ubuntu 14.04 - cmake / crypto++ error while trying to make miner

### ISSUE THREAD

**Issue by NateSlackerman** [ethereum/cpp-ethereum#3066]
I'm trying to make my cudaminer, however I keep getting the error that cmake cant find cryptopp although I verified my cryptopp install and tested without failures. I attached my terminal output. Also super sorry if I sound like this is my first time using ubuntu but it's actually my 3rd... lol
[TerminalOutput.docx](https://github.com/ethereum/cpp-ethereum/files/429946/TerminalOutput.docx)

**Comment by bobsummerwill** [comment]
Are you building from https://github.com/ethereum/cpp-ethereum or https://github.com/Genoil/cpp-ethereum or some other branch?

**Comment by NateSlackerman** [comment]
ethereum/cpp-ethereum yeah

**Comment by bobsummerwill** [comment]
Did you use `./scripts/install_deps.sh`?

**Comment by bobsummerwill** [comment]
Hey @NateSlackerman!
Please come to https://gitter.im/ethereum/cpp-ethereum-development and we can take through your issue.   I don't think there is a bug here.

**Comment by NateSlackerman** [comment]
I didnt use that where can i find it?

**Comment by bobsummerwill** [comment]
Just run `./scripts/install_dep.sh` from the root directory of your cloned `cpp-ethereum`.

Just follow these instructions ... http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html
