### ISSUE TITLE
ecRecoverInfinityTestFiller

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3082]
_From @eth-jenkins-bot on September 30, 2015 12:6_

Moved here from [cpp-ethereum](https://github.com/ethereum/cpp-ethereum/issues/2591)

correct test filler ecRecoverInfinity
blockChain emptyMining Test

_Copied from original issue: ethereum/webthree-umbrella#55_

**Comment by bobsummerwill** [comment]
_From @chriseth on March 29, 2016 14:40_

@winsvega can you comment on whether this can be closed?

**Comment by winsvega** [comment]
those tests are not exist any more or were changed

**Comment by chriseth** [comment]
Please feel free to close the issue in such cases.
