### ISSUE TITLE
Libethereum coverage questions

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3086]
_From @winsvega on October 20, 2015 9:9_

**Block.cpp** (PR https://github.com/ethereum/libethereum/pull/64)

**1)====**
Line 529 is unreachable when importing a block with uncle that have unknown parent hash
probably because of it's being checked at function BlockChain::verifyBlock line 458

`528          44 :                                 if (!_bc.isKnown(uncle.parentHash()))`
`529           0 :                                         BOOST_THROW_EXCEPTION(UnknownParent() << errinfo_hash256(uncle.parentHash()));`

**2)====**
Block class before syncing with blockchain has to be = blockchain.genesisblock(genesisDB)
`block b = blockchain.genesisBlock(genesisDB))`
in order to get state root of the blockchain otherwise it wont sync with blockchain.
such interface is unclear. why block class wont simply sync with blockchain?

**3)====**
populateFromChain wont work as expected on genesisBlock hash
`b.populateFromChain(blockchain, genesisBlock.hash());`==> b.info() != genesisBlock.info()

**4)===**
Block::vmTrace is private and never used

**5)===**
block.sync(blockchain);  wont adjust states as if to use 
block.populateFromChain(blockchain, blockchain.lastblock.hash());

Example:
`block1.sync(blockchain)  //block1 should be updated to blockchain latest block state`

`block2.populateFromChain(blockchain, blockchain.lastblock.hash()); // block2 should also be updated to blockchain latest block state`

but

 It is unclear that  block.sync(blockchain) not only will update the block to the latest blockchain state but also will reset it as a fresh new block on top of blockchain

**6)===**
Similar variable name inside the same scope might be confusing. 
  290          18 :                 for (auto const& t: ts)
  297             : //                                              Timer t;

**7)===**
when block.sync drop some transaction and catching an exception 
( example  Block.cpp line 310    12     catch (InvalidNonce const& in) )
it would be good to have some debug stack so it would be possible to get out what exactly went wrong  (exception) and check it with boost. right now it just uses clog to print information about catched exceptions. 

so something like  get_last_exception is needed for test purposes

**8)===**
functions like this does not check out of range in vector. possible segfault exception:
https://github.com/ethereum/libethereum/blob/develop/libethereum/Block.h#L179

_Copied from original issue: ethereum/webthree-umbrella#74_

**Comment by bobsummerwill** [comment]
_From @winsvega on October 27, 2015 11:35_

**TransactionQueue.cpp** (PR https://github.com/ethereum/libethereum/pull/75)

**1)===**
when setting tq limit and importing a transaction off max limit.
the ImportResult would be still success. however transaction is being dropped due to 

TransactionQueue.cpp line:180
while (m_current.size() > m_limit)
{
	clog(TransactionQueueTraceChannel) << "Dropping out of bounds transaction" << _h;
	remove_WITH_LOCK(m_current.rbegin()->transaction.sha3());
}

**2)===**
if transactionQueue future limit is set. future transaction beyond that limit would be dropped after importing a new transaction
Example:
tq have limit of future transactions set to 3
tq.waiting(from) == 5     // 5 transactions are made to be future through (tq.setFuture) without dropping any transaction (thus allows to create more future transaction that set by limit future transaction in tq)

now import anothe new transaction
tq.import(transaction)    //future transactions recalculated
tq.waiting(from) == 4     //now it is 3 future transactions (2 have been dropped) + 1 imported

**3)===**
it is not clear that TransactionQueue.enqueue accepts RLPStream (list)  of transaction's rlps and not a single Transaction RLP
commet says "_data RLP encoded transaction data."

**Comment by bobsummerwill** [comment]
_From @winsvega on October 28, 2015 9:38_

**CanonBlockChain.cpp** (PR https://github.com/ethereum/libethereum/pull/76)

**1)===**
https://github.com/ethereum/libethereum/blob/develop/libethereum/CanonBlockChain.cpp#L104
the static function   setGenesis(https://github.com/ethereum/libethereum/blob/develop/libethereum/CanonBlockChain.cpp#L130)
wont affect the changes of previous static functions. (such as forceGenesisGasLimit/forceGenesisDifficulty and other)

**2)===**
Still the concept of mining is not user friendly: (especially where block should be = blockchain.genesisBlock with specific database. otherwise it wont mine)
...
OverlayDB const& genesisDB = OverlayDB(State::openDB(tDir.path(), h256{}, WithExisting::Kill));
Block block = cBc.genesisBlock(genesisDB);
try
{
	block.sync(cBc);
	//transaction sync (optional)
	dev::eth::mine(block, cBc);
}
...
cBc.import(block.blockData(), block.db());

without this example it is really hard to get what it needs to mine a block in the code.

**Comment by bobsummerwill** [comment]
_From @winsvega on November 3, 2015 10:4_

**BlockChain.cpp** (PR https://github.com/ethereum/libethereum/pull/80)
1)===
why ldb::Slice dev::eth::toSlice(uint64_t _n, unsigned _sub)  is defined at blockchain.cpp?

2)===
BlockChain.cpp:999 void BlockChain::rescue(OverlayDB& _db)  
function does not change _db. it could be set to const&

3)===
BlockChain::rebuild function does not seem to work. 
it always fails with exception on line 304
 Block s = genesisBlock(State::openDB(path, m_genesisHash, WithExisting::Kill));

4)===
why  template <class K, class T> static unsigned getHashSize(unordered_map<K, T> const& _map) is defined at blockchain.cpp?

5)===
Memblocks on BlockChain::Statistics return very high value on a chain without any blocks imported (no autoupdate?. default value for memBlock are too high. however memTransactionAddresses is set to 1 )

**Comment by bobsummerwill** [comment]
How are you doing your coverage analysis here, @winsvega?

I also created an issue asking about Coverage in general - https://github.com/ethereum/webthree-umbrella/issues/224

Do we have any consistent in our approach to coverage, or is this just something you've done ad-hoc occasionally?

It's probably something similar to @chfast's work on profiling, which might make sense to measure systematically and continuously.

**Comment by bobsummerwill** [comment]
_From @chfast on July 14, 2016 9:45_

Coverage with gcc/clang should be quite easy to setup. It would need additional option or build type in cmake -- not sure what is the best practice.

It should not take more time than testing, so we could do it every build and use some external coverage reporting tools like https://codecov.io.

**Comment by bobsummerwill** [comment]
_From @winsvega on July 29, 2016 10:47_

@bobsummerwill  I just run testeth using lcov tool like this
https://github.com/ethereum/webthree-umbrella/blob/crgav_test/getcoverage.sh

and looked  if in some core class there were untouched lines. 
then I tried to write some coverage test code that would execute this line in core class. 

and these are the questions to Gavin I had while doing such analysis. 
still some of my coverage tests shows that some of libethereum functions might work different from time to time (like in a sync test) or trigger mining hang error. (10 min error)

**Comment by winsvega** [comment]
outdated
