### ISSUE TITLE
Provide simple way to convert eth keys to geth keys

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3113]
_From @bobsummerwill on February 17, 2016 15:48_

We should provide documentation or a simple command to convert eth keys to geth keys.

Initial description:

Posted by @5chdn.   Moved from https://github.com/ethereum/libethereum/issues/161

it seems ethkey export function does not work. i want to export private keys.

calling export simply does nothing.

```
 $ ethkey
8766c082-432f-5548-608c-6eec600757f9
 $ ethkey list
Please enter your MASTER passphrase: 
8766c082-432f-5548-608c-6eec600757f9 006ed403… XE871TJEHQTCYKGJ2ETMECEX4AVZLMG4MZ  Default key
               (Brain)               005d30aa… XE501J3WPGKSICM9OPEDT43FBF0DYWO226  asdf
 $ ethkey export XE871TJEHQTCYKGJ2ETMECEX4AVZLMG4MZ
 $ ethkey export 8766c082-432f-5548-608c-6eec600757f9
 $ ethkey export asdfsdlfhsldghjg
 $ ethkey export
 $ ethkey --version
ethkey version 1.1.1
Build: Linux/g++/JIT/.
```

using ethkey 1.1.1 in archlinux.

_Copied from original issue: ethereum/webthree-umbrella#238_

**Comment by bobsummerwill** [comment]
_From @chriseth on February 17, 2016 19:0_

This seems to be just not implemented. Not clear what the export format should be.

**Comment by bobsummerwill** [comment]
_From @jjviscomi on March 18, 2016 5:40_

What is the status on this, I am trying to export my keys and import them into Ethereum Wallet. is this related?

**Comment by bobsummerwill** [comment]
_From @chriseth on March 18, 2016 23:50_

In general, you can take the files in `~/.web3/keys` (actual path depending on OS) and copy them into `~/.ethereum/keystore` (again actual path depending on OS), the only problem is that the filenames in the target directory need to follow a certain pattern:
`UTC--2016-03-01T19-42-49.995765660Z--1234567890123456789012345678901234567890`, where the last part is the address. This address has not been part of the file previously, but it is now added if you run a current version of eth once.
We will add a proper export functionality soon, but you can already do that manually if you want.

**Comment by chriseth** [comment]
We retired the ethkey command and files are now compatible, no need to stick to a certain file naming scheme. I think we are fine here. Key management is not something we highly support, it should be moved out of the node's domain anyway.
