### ISSUE TITLE
check permissions for ipc socket

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3115]
_From @chriseth on February 24, 2016 17:9_

We should check whether there are any security issues with the ipc socket. It should only be accessible from the user that created the socket and it should not be possible to read communications by other processes that go over that socket.
The situation where the socket file already exists should also be considered and of course the different platforms (linux, macos, windows).

_Copied from original issue: ethereum/webthree-umbrella#259_

**Comment by bobsummerwill** [comment]
Please could you elaborate on this?
Pretty please, @chriseth?  :-)

**Comment by axic** [comment]
@chfast is this done or needed?
