### ISSUE TITLE
Implement EIP-5 (gas for memory during call)

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3118]
_From @chriseth on February 28, 2016 14:4_

Currently, the caller provides a memory area where the return value is copied to by the callee. This needs to change to a model where the callee's memory area is kept alive until the caller has copied the return value.

_Copied from original issue: ethereum/webthree-umbrella#274_

**Comment by chfast** [comment]
Obsolated by #3520
