### ISSUE TITLE
shh topics are formated differently

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3130]
_From @bobsummerwill on March 10, 2016 23:37_

Originally logged by @simon-jentzsch as https://github.com/ethereum/webthree/issues/81

when posting a whisper-message like:

```
web3.shh.post({
 "topics": [ "0xad5e5a5bc4654dbef0d5cabd7abeb426769c073a" ],
 "payload": [ web3.fromAscii("open") ],
});
```

the inputPostFormatter-function will convert each topic to hex(

```
 post.topics = post.topics.map(function(topic){
    return utils.fromUtf8(topic);
});
```

)

But if I listen to the exact same topic like:

```
web3.shh.filter({ 
   'topics': [ "0xad5e5a5bc4654dbef0d5cabd7abeb426769c073a" ] 
}).watch(function(error,m) {
    // do something, but he never hits this line.
});
```

It is not converted.

The result: the topics don't match and I will never receive this message!

_Copied from original issue: ethereum/webthree-umbrella#340_

**Comment by bobsummerwill** [comment]
_From @chriseth on March 29, 2016 14:30_

@bobsummerwill isn't that a web3.js bug?

**Comment by bobsummerwill** [comment]
It's an old bug, certainly :-)
Maybe ended up in cpp-ethereum because that is where the Whisper implementation it was talking to lived.   Is there any Whisper implementation in geth?

If you think we should move it to web3.js, let's do so.

I think I was just slewing it across to empty out webthree's issue tracker.

**Comment by bobsummerwill** [comment]
There is only one left in there now:  https://github.com/ethereum/webthree/issues
If you want to slew-and-kill the Github Issues tracker for that repo - go for it!

**Comment by axic** [comment]
Whisper is scheduled for deletion.
