### ISSUE TITLE
Windows - Add support for Chocolatey packages

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3132]
_From @bobsummerwill on March 11, 2016 21:24_

See http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/windows-chocolatey.html.

@tgerring has been doing some Chocolatey work.    I'm sure we can get that going between us.

Effectively "apt-get for Windows"

_Copied from original issue: ethereum/webthree-umbrella#345_

**Comment by bobsummerwill** [comment]
_From @smartbitcoin on March 15, 2016 16:4_

sounds interesting.  I just like apt-get or yum if it works on windows.

**Comment by bobsummerwill** [comment]
Yes, it's a really useful tool from what I understand, @smartbitcoin.

It is built on top of NuGet packages.   It has been around for a few years now, and is pretty popular.

**Comment by GoZippy** [comment]
Bob, where is this at now? I have been away from this for over a year - busy with life - and have not followed. I should have left my rigs up it seems, lol.

**Comment by bobsummerwill** [comment]
I haven't been working on cpp-ethereum for nearly a year now, @GoZippy.

The packaging focus has switched to Docker now.   I'm not sure of the state of OS X or Windows builds, but I am sure Chocolatey won't be happening, so I'll close this issue.
