### ISSUE TITLE
Try doing Unity Builds for our apps (AKA BulkBuild)

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3142]
_From @bobsummerwill on March 30, 2016 1:40_

http://buffered.io/posts/screencast-setting-up-unity-builds/
https://cheind.wordpress.com/2009/12/10/reducing-compilation-time-unity-builds/

They make a huge difference.   Every single team at EA has used them (some since around 2006).    It's a hell of a good C+ build system hack.

_Copied from original issue: ethereum/webthree-umbrella#415_

**Comment by bobsummerwill** [comment]
_From @chriseth on March 31, 2016 23:1_

I don't really see the point. I'm using ccache on an SSD. Is unity beneficial in that case? :-)

**Comment by bobsummerwill** [comment]
Yep.   It is amazingly fast and quite magic.

All really due on the ugliness of the C++ compilation model.    Doing everything in a single compilation unit is much, much faster, and the code optimizes better too.

**Comment by bobsummerwill** [comment]
See https://github.com/bobsummerwill/cpp-ethereum/pull/6

**Comment by chfast** [comment]
MacOS builds on CircleCI: https://circleci.com/gh/ethereum/cpp-ethereum/2645.
