### ISSUE TITLE
Windows - Try to use NuGet C++ packages

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3164]
_From @bobsummerwill on May 10, 2016 18:5_

We should try to use NuGet C++ packages for our external dependencies on Windows, if there are sufficient binaries there for us, and if they work.     That would free us from the need to maintain our own binary builds at https://builds.ethereum.org/builds/windows-precompiled/ (or an equivalent on Github).

Maybe even only a subset of packages in this way would be a win?
- https://www.nuget.org/packages/boost-vc120/
- https://www.nuget.org/packages/boost-vc140/
- https://www.nuget.org/packages/curl/
- https://www.nuget.org/packages/jsoncpp.redist/ (OLD)
- https://www.nuget.org/packages/LevelDB/
- https://www.nuget.org/packages/libgmp_vc120/
- https://www.nuget.org/packages/libssh2/
- https://www.nuget.org/packages/openssl/

_Copied from original issue: ethereum/webthree-umbrella#509_

**Comment by seusher** [comment]
Certain NuGet packages (ex: LevelDB) are only available as source packages and do not provide a compiled library. Is the project willing to to have the Windows build of cpp-ethereum include building dependencies such as LevelDB? It looks like the alternative is to provide a custom NuGet package which includes the built library, which isn't an improvement on the current situation.

**Comment by chfast** [comment]
We don't want to deal with another Microsoft package manager.
