### ISSUE TITLE
Linux/OS X - jsonrpcstub CMake error: No such file or directory: PersonalFace.h.tmp

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3165]
_From @bobsummerwill on May 14, 2016 15:38_

We've had this issue several times and never REALLY got to the bottom of it.

See https://github.com/ethereum/webthree-umbrella/issues/109, for example.   We've hit this on Arch Linux, on Ubuntu and on OS X.

Now I have it at https://circleci.com/gh/bobsummerwill/cpp-ethereum/34?utm_campaign=build-failed&utm_medium=email&utm_source=notification, and have added some extra debug information to try to nail it down.

I think that it is actually a bug in the `jsonrpcstub` tool which comes with json-rpc-cpp.   For Ubuntu it looks like we have an orphaned copy of this in our PPA.    For the old OS X issue, the workaround was to rebuild that package from source.

    Executing process: /usr/bin/jsonrpcstub /home/ubuntu/cpp-ethereum/libweb3jsonrpc/net.json
			--cpp-server=dev::rpc::NetFace --cpp-server-file=/home/ubuntu/cpp-ethereum/libweb3jsonrpc/NetFace.h.tmp
			--cpp-client=NetClient --cpp-client-file=/home/ubuntu/cpp-ethereum/build/libweb3jsonrpc/NetClient.h.tmp
    CMake Error at /home/ubuntu/cpp-ethereum/cmake/scripts/jsonrpcstub.cmake:70 (file):
  file failed to open for reading (No such file or directory):

        /home/ubuntu/cpp-ethereum/libweb3jsonrpc/NetFace.h.tmp

Maybe try building from source on Ubuntu too, as a first step?

_Copied from original issue: ethereum/webthree-umbrella#513_

**Comment by bobsummerwill** [comment]
Any insight on this one, @chfast, @chriseth?

It looks like the `jsonrpcstub` tool is just broken in these failing cases.   Maybe missing .so files?   Maybe bad binaries?  Maybe just a bug?    We're using our own binaries in our own PPA on Ubuntu Trusty here, for example.

The OS X failure had a workaround of "rebuild from source and it works".

So I think there may be some actual bug in the application itself (or in our binaries for it).   Looks like we are using an old version of the package.

See https://github.com/cinemast/libjson-rpc-cpp/releases.   We're on 0.4.2.   There are 0.5 and 0.6 versions since.

Maybe we should refresh this package?   Homebrew is using 0.6 already (https://github.com/Homebrew/legacy-homebrew/blob/master/Library/Formula/libjson-rpc-cpp.rb), but we're stuck back on 0.4.2 for Ubuntu, and on 0.5.0 for Windows.    The mixture isn't so great.   Would be better to be on 0.6 for everything, eh?

**Comment by bobsummerwill** [comment]
Yeah, so building libjson-rpc-cpp-0.6.0 from source gets past this issue:

- https://travis-ci.org/bobsummerwill/cpp-ethereum/builds/130323280

So I think we should update our PPA and Windows binaries to 0.6.0, to match OS X.

**Comment by bobsummerwill** [comment]
Same "trick" has worked for CircleCI:
https://circleci.com/gh/bobsummerwill/cpp-ethereum/42

**Comment by bobsummerwill** [comment]
_From @Arachnid on May 21, 2016 15:22_

Just ran into this trying to build cpp-ethereum head from source on OSX, too. Likewise, the homebrew build is broken with the same error.

**Comment by bobsummerwill** [comment]
_From @Arachnid on May 21, 2016 15:24_

(Unhelpfully, using brew to try and build libjson-rpc-cpp from source also fails, with a link error)

**Comment by bobsummerwill** [comment]
Weird indeed.   I wish we had some kind of error message from that app.

If you ever get a reproducible case where you can could run that `jsonrpcstub` step from within a debugger, please do.   Because your failure case here on OS X will be against 0.6, won't it?   So maybe there is still no fix and there is an outstanding bug here which still needs fixing.   We just haven't found the root cause yet.

Building json-rpc-cpp from source here on OS X might get around the issue here too, but isn't a fix.

**Comment by bobsummerwill** [comment]
What link error do you get when trying that, btw?

**Comment by bobsummerwill** [comment]
_From @Arachnid on May 22, 2016 7:27_

The link error turned out to be json-rpc-cpp trying to build against an old version of jsonrpc that didn't have a symbol it needed; updating jsonrpc fixed it.

**Comment by bobsummerwill** [comment]
jsoncpp, you mean, I assume?    Did you have to do anything fancier here than `brew update`, `brew upgrade`?   What did you have to "build from source"?

**Comment by bobsummerwill** [comment]
_From @Arachnid on May 22, 2016 9:19_

Yes, jsoncpp is what I meant. I needed to do `brew uninstall jsoncpp && brew install --build-from-source libjson-rpc-cpp`, which also prompts brew to install jsoncpp from source (probably unnecessary, but it works).

**Comment by bobsummerwill** [comment]
Right, @Arachnid.   Yeah - so that kind of makes sense.

All I can think is that there must be different "modes" or something here, so that Homebrew and the PPA end up with "bad binaries" somehow.

**Comment by bobsummerwill** [comment]
Hello, @giacecco (who is seeing this issue on Fedora 23).

Coming from https://github.com/ethereum/webthree-umbrella/issues/525.

If anybody gets this issue in a reproducible state (maybe you do right now, @giacecco), the key to finding a solution will be to debug the failing execution of the `jsonrpcstub` application.    That application is just silently failing for some reason (maybe permissions?) and then everything falls apart.

If somebody has a reproducible, has built json-rpc-cpp from source, and can just step through that in a debugger, we should have our answer.

Building from source has sometimes "fixed this".    Using 0.6.0 "fixed this" for my new CircleCI automation.    Maybe we're missing .SO files?     It will be something really dumb, I'm sure.

**Comment by bobsummerwill** [comment]
_From @giacecco on May 25, 2016 15:23_

Thanks @bobsummerwill. The issue can be reproduced systematically starting from the official Fedora 23 docker image. The steps are trivial, below. Note that in the instructions:

- I've intentionally avoided another issue, described at https://github.com/ethereum/webthree-umbrella/issues/524 , thanks to your help, and
- I've used the latest libjson-rpc-cpp instead of 0.6.0 because there are no binaries for Fedora, and the source of 0.6.0 does not compile because of [another issue](https://github.com/cinemast/libjson-rpc-cpp/issues/148).

```
- dnf install git automake autoconf libtool cmake gcc gcc-c++ xkeyboard-config leveldb-devel boost-devel gmp-devel cryptopp-devel miniupnpc-devel mesa-dri-drivers snappy-devel ncurses-devel readline-devel curl-devel python-devel jsoncpp-devel argtable-devel make llvm-devel llvm-static ocl-icd-devel beignet-devel libmicrohttpd-devel qt5-*-devel*
- [install the latest libjson-rpc-cpp from source]
- git clone --recursive <https://github.com/cinemast/libjson-rpc-cpp.git>
- cd libjson-rpc-cpp
- mkdir build
- cd build
- cmake -DEVMJIT=0 ..
- make 
```

Can you explain what you need me to do to "debug the failing execution of the ```jsonrpcstub``` application"?

**Comment by bobsummerwill** [comment]
If you look at the generated Makefile, you will see that there are steps in there for running jsonrpcstub to generate code from json files.

Within the makefile, I believe it creates targets which are invoking CMake :-)

Like so ... 

    minerfarm.jsonstub: ethminer/CMakeFiles/minerfarm.jsonstub.dir/build.make
    	cd /Users/bob/SourceTreeProjects/cpp-ethereum/ethminer && /usr/local/Cellar/cmake/3.5.2/bin/cmake -DETH_SPEC_PATH="/Users/bob/SourceTreeProjects/cpp-ethereum/ethminer/minerfarm.json" -DETH_SOURCE_DIR="/Users/bob/SourceTreeProjects/cpp-ethereum" -DETH_CMAKE_DIR="/Users/bob/SourceTreeProjects/cpp-ethereum/cmake" -DETH_CLIENT_DIR="/Users/bob/SourceTreeProjects/cpp-ethereum/ethminer" -DETH_CLIENT_NAME=FarmClient -DETH_CLIENT_FILENAME=FarmClient -DETH_JSON_RPC_STUB="/usr/local/bin/jsonrpcstub" -P /Users/bob/SourceTreeProjects/cpp-ethereum/cmake/scripts/jsonrpcstub.cmake
     .PHONY : minerfarm.jsonstub

**Comment by bobsummerwill** [comment]
Which is this CMake file:   https://github.com/ethereum/webthree-helpers/blob/develop/cmake/scripts/jsonrpcstub.cmake

If you do a very verbose run, I *think* that you should be able see the actual command-line that executes, which will be something like `jsonrpcstub --cpp-client=xxx --cpp-client-file=yyyy`

If you could run that command-line via gdb, or even step through it in an interactive debugger, we should find out WHY that app is failing.

**Comment by bobsummerwill** [comment]
Thanks for your help!    Maybe we can nail this bugger soon :-)

**Comment by bobsummerwill** [comment]
_From @giacecco on May 26, 2016 13:15_

This is the output of ```make --debug=v``` just before it fails https://gist.github.com/giacecco/443a54ffecb2eca4465ffe77553f0f00 . I don't think I understand enough of the process to try make hypothesis around what's happening, nor I see the commands that it tries to execute, but rather just the output. Perhaps I should run ```make``` some other way?

**Comment by bobsummerwill** [comment]
Yeah - I think you'll need to work out the command-line which the CMake ends up calling.

So either this webthree/libweb3jsonrpc/CMakeFiles/personal.jsonstub.dir/build.make or the other one is a generated makefile with the parameters used to call the jsonrpcstub.cmake file.

You'll have to pretend to be CMake, and work out what command-line that is actually calling in this case.

**Comment by bobsummerwill** [comment]
Something like `/path/jsonrpcstub --cpp-client=xxx --cpp-client-file=yyyy` but with the actual parameters from those generate make files.

**Comment by bobsummerwill** [comment]
_From @sanblch on June 14, 2016 22:30_

Ubuntu 16.04 x86_64
Same error when compiling with custom built libjsonrpccpp. `cmake -DCOMPILE_STUBGEN=NO ..` for the last one solves the problem.

**Comment by bobsummerwill** [comment]
Hmm, @sanblch,

But if you don't compile the stub-generator then what executable would be used in our CMake files for that stub-generation?

There must be some bug in that stub-generation executable, but we have never had that executable in a debugger at the point of failure to understand what the root issue is.

**Comment by 5chdn** [comment]
FYI, I just ran into that issue again. I had to upgrade `libjson-rpc-cpp` from 0.6 to 0.7 to fix it, as documented here: https://github.com/ethereum/webthree-umbrella/issues/109#issuecomment-171637662

**Comment by bobsummerwill** [comment]
Thanks for the note, @5chdn.

Yeah - it is very odd and we still don't know the root cause.   We need a reproducible, and then somebody to debug that invocation.   Maybe missing directory or similar?

**Comment by windemut** [comment]
I had this problem, and in my case it was solved by setting the library path:

export LD_LIBRARY_PATH=/usr/local/lib

I noticed that when I called jsonrpcstub by itself, it failed to load it's library, like so:

> jsonrpcstub
jsonrpcstub: error while loading shared libraries: libjsonrpccpp-stub.so.0: cannot open shared object file: No such file or directory

So I used find to search for the library, and found it in /usr/local/lib. It might have been there to begin with, or it might have gotten there by me trying to install libjson-rpc-cpp.

After the above export, jsonrpcstub behaved more reasonably:

> jsonrpcstub
Invalid arguments: specfile must be provided.

And I was able to continue compiling cpp-ethereum.

Only too be stopped later by a different error (../libweb3jsonrpc/libweb3jsonrpc.so: error: undefined reference to 'pthread_create'), but I am assuming that one is unrelated. Still working on that one.

I am running Ubuntu 16.10

**Comment by chfast** [comment]
jsonrpcstub is not needed any more to build cpp-ethereum because someone pushed generated files to the repo. In case jsonrpcstub binary is needed again let me know. We build jsonrpc from source as of now so building jsonrpcstub by the way should not be a problem.
