### ISSUE TITLE
Arch Linux: error: ignoring attributes on template argument 'cl_int {aka int}' 

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3166]
_From @moneroexamples on May 15, 2016 8:10_

Cant pass the following error on Arch Linux when compiling webthree-umbrella

```bash
/webthree-umbrella/libethereum/libethash-cl/cl.hpp:2423:28: error: ignoring attributes on template argument 'cl_int {aka int}' [-Werror=ignored-attributes]
         VECTOR_CLASS<cl_int>* binaryStatus = NULL,
```

gcc version 6.1.1 20160501 (GCC) 

Any ideas how to fix that?

_Copied from original issue: ethereum/webthree-umbrella#515_

**Comment by bobsummerwill** [comment]
Thanks for the report, @moneroexamples!

Do you see this issue too, @5chdn?   Maybe something which has appeared at HEAD as a consequence of changes we've made in webthree-helpers?

FYI, Afri is the maintainer for the Arch Linux package for eth.

**Comment by bobsummerwill** [comment]
_From @5chdn on May 16, 2016 20:30_

can reproduce this. do you need more verbose output? @bobsummerwill

**Comment by bobsummerwill** [comment]
Hmm.   I wonder whether Arch is the first distro on which we are hitting GCC 6.x?

See http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1221.

As in, maybe GCC has been updated in Arch Linux after the cpp-ethereum-1.2.4 release, and now we have a pickier compiler?

We could obviously just suppress the warning, but that is a bit lame.    Does either of you have time to have a quick "fiddle", and see whether we can modify to code in some minor way to stop GCC from bleating?   Thanks!

**Comment by bobsummerwill** [comment]
_From @moneroexamples on May 17, 2016 1:17_

Thank you for the response @bobsummerwill

The problem can be overcome by adding  `-Wignored-attributes` pragma to cl.hpp after the already existing pragma `"-Wdeprecated-declarations"`:

```
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#pragma GCC diagnostic ignored "-Wignored-attributes" # <-- new pragma
```

**Comment by bobsummerwill** [comment]
Oh - I see this is externally authored code too as well.

So yeah, if either of you would like to submit a PR with this one-liner edit, I would be happy to merge it.   Thanks :-)

**Comment by 5chdn** [comment]
can not reproduce anymore.

**Comment by bobsummerwill** [comment]
Looks like we fixed it, but just forgot to close the issue.

See https://github.com/ethereum/cpp-ethereum/commits/develop/libethash-cl/cl.hpp

Thanks!
