### ISSUE TITLE
Fedora - make fails with "No rule to make target '/usr/lib/libLLVMCore.a"

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3167]
_From @giacecco on May 23, 2016 13:33_

Hi All, I'm building from source for Fedora 23, using the general instructions at http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html . I got successfully through the ```cmake``` stage but now I'm stuck with this error at ```make```. The error is below, it looks like a problem with the makefile, rather than with a missing dependency. What do you reckon? Thank you in advance for any suggestion.

```
[giacecco@giaceccos-linux build]$ sudo make
Scanning dependencies of target cpp-ethereum_BuildInfo.h
[  0%] Built target cpp-ethereum_BuildInfo.h
Scanning dependencies of target scrypt
[  0%] Building C object webthree-helpers/utils/libscrypt/CMakeFiles/scrypt.dir/crypto-scrypt-saltgen.c.o
(...)
Scanning dependencies of target evmjit
[ 20%] Building CXX object libethereum/evmjit/libevmjit/CMakeFiles/evmjit.dir/JIT.cpp.o
(...)
[ 24%] Building CXX object libethereum/evmjit/libevmjit/CMakeFiles/evmjit.dir/support/Path.cpp.o
make[2]: *** No rule to make target '/usr/lib/libLLVMCore.a', needed by 'libethereum/evmjit/libevmjit/libevmjit.so.0.9.0.2'.  Stop.
CMakeFiles/Makefile2:851: recipe for target 'libethereum/evmjit/libevmjit/CMakeFiles/evmjit.dir/all' failed
make[1]: *** [libethereum/evmjit/libevmjit/CMakeFiles/evmjit.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[giacecco@giaceccos-linux build]$
```

_Copied from original issue: ethereum/webthree-umbrella#524_

**Comment by bobsummerwill** [comment]
Any thoughts on this one, @tflux99, @3esmit?

I'm assuming you **do** have LLVM installed, right?    Also, if you cannot work out what is misaligned with your LLVM quickly, you could do `cmake -DEVMJIT=0` to turn off the JIT (which removes the LLVM dependency).

**Comment by bobsummerwill** [comment]
_From @giacecco on May 23, 2016 16:29_

I do have LLVM installed, but perhaps I'm missing some piece of it?

```
[giacecco@giaceccos-linux ~]$ sudo dnf list installed | grep llvm
llvm.x86_64                           3.7.0-4.fc23              @updates        
llvm-devel.x86_64                     3.7.0-4.fc23              @updates        
llvm-libs.x86_64                      3.7.0-4.fc23              @updates        
[giacecco@giaceccos-linux ~]$ 
```

**Comment by bobsummerwill** [comment]
_From @chfast on May 24, 2016 8:59_

Looks like `llvm-devel.x86_64` package is broken (at least cmake shared files includes) because it allowed cmake configuration to be successful but referenced libraries that does not exist.

Can you check if `/usr/lib/libLLVMCore.a` exists? If not you should report the issue to the `llvm-devel.x86_64` to the package maintainer.

**Comment by bobsummerwill** [comment]
Something else to note, @giacecco, is that the instructions there were for earlier versions of Fedora.

You might well be the first person to try to get it working on Fedora 23 :-)

So maybe some things have changed slightly since Fedora 22?

**Comment by bobsummerwill** [comment]
_From @giacecco on May 25, 2016 9:31_

@chfast @bobsummerwill this morning I'm attempting installation on a clean Fedora 23 docker container to document the process for everybody. So far, it looks simpler than what it's on the website at the moment, but for bumps such as this.

After installing the packages I described above, ```find / -name 'libLL*'``` only returns ```/usr/lib64/llvm/libLLVM-3.7.0.so``` and ```/usr/lib64/llvm/libLLVM-3.7.so```, there's no ```libLLVMCore.a```. If there was, it would probably be in ```/usr/lib64``` rather than ```/usr``` as suggested by @chfast.

I've created the bug on Red Hat's Bugzilla at https://bugzilla.redhat.com/show_bug.cgi?id=1339532 .

**Comment by bobsummerwill** [comment]
_From @giacecco on May 25, 2016 10:33_

Hold on, there's a development. 

Static llvm libraries are distributed in Fedora through dedicated packages ```llvmXX-static```, where XX is the version, e.g. 35 for version 3.5, or nothing for the latest (3.7 at the moment of writing). 

The libraries are installed in ```/usr/lib64/llvm/```, but the makefile is looking for them in ```/usr/lib/```. 

So, part of the solution is installing the ```llvm-static``` pacakge, but we also need to look for the libraries in Fedora's chosen place. 

Before finding out this, I was installing ```llvm-devel```. That was sufficient to make ```cmake``` succeed. Perhaps this is an issue, too?

**Comment by bobsummerwill** [comment]
_From @chfast on May 25, 2016 11:1_

This is still the Fedora package issue. The path `/usr/lib/libLLVMCore.a` comes from `llvm-devel.x86_64` package, not from our guessing. I cannot do anything about Fedora not being able to package LLVM correctly.

**Comment by bobsummerwill** [comment]
_From @giacecco on May 25, 2016 12:50_

@chfast that's interesting thanks. Why do you say that Fedora's ```llvm-devel``` and ```llvm-static``` contradict each other? I've tried running ``` llvm-config-64 --libdir``` from the former, and I get ```/usr/lib64/llvm/``` "correctly".

If I understand enough of the problem I can go back to Fedora's Bugzilla and document the matter. Thanks.

**Comment by bobsummerwill** [comment]
_From @chfast on May 25, 2016 15:15_

`llvm-config` might be right, but `/usr/share/llvm/cmake/LLVMConfig.cmake:10` is wrong.

**Comment by bobsummerwill** [comment]
_From @giacecco on May 25, 2016 16:13_

Thanks @chfast, I've raised the issue with the package maintainers at https://bugzilla.redhat.com/show_bug.cgi?id=1339697 .

**Comment by bobsummerwill** [comment]
Thanks, @chfast and @giacecco.

Is there anything that WE can do to workaround the issue in the meantime, or are we just screwed in this situation?

BTW - You mentioned, @giacecco, that you think you can make the written process for Fedora builds simpler?   If so, that is great.    If you would like to submit PRs on simplifying the instructions on older Fedora versions too, that would be great.     I think we should probably split the Linux instructions out into RST files per distro, rather than the one monster `linux.rst` file we have now:

https://github.com/ethereum/homestead-guide/tree/master/source/ethereum-clients/cpp-ethereum/building-from-source

**Comment by bobsummerwill** [comment]
See also https://github.com/ethereum/evmjit/issues/58.

**Comment by bobsummerwill** [comment]
See also https://github.com/ethereum/webthree-umbrella/issues/631.

But even with LLVM building-from-source, are we still screwed by this Fedora packaging issue?   Maybe not, eh?

**Comment by bobsummerwill** [comment]
_From @chfast on July 9, 2016 9:39_

Building from source should not be affected as long as CMake has not cached
LLVM_DIR.

**Comment by chfast** [comment]
Fixed. See https://github.com/ethereum/evmjit/issues/58.
