### ISSUE TITLE
OS X - Switch from SHA1 to SHA256 for Homebrew bottles

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3169]
_From @bobsummerwill on May 28, 2016 3:28_

There is a warning when installing the Homebrew bottles, saying that SHA1 is deprecated, and to switch to SHA256.   We should do that.

![image](https://pbs.twimg.com/media/CjgjLSNUoAEnEjV.jpg)

_Copied from original issue: ethereum/webthree-umbrella#533_

**Comment by axic** [comment]
Current homebrew (https://github.com/ethereum/homebrew-ethereum/blob/master/cpp-ethereum.rb) uses git hashes so this doesn't apply.
