### ISSUE TITLE
Switch to C++14

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3171]
_From @chfast on June 2, 2016 14:34_

As soon as Visual Studio 2015 is in place we should switch to C++14. Visual Studio is not full C++14 but standard library is, so we get some nice features like `std::make_unique`.

The switch is about flags to GCC/clang. Without it C++14 features are not available.
https://github.com/ethereum/webthree-helpers/blob/develop/cmake/EthCompilerSettings.cmake#L19

_Copied from original issue: ethereum/webthree-umbrella#550_

**Comment by bobsummerwill** [comment]
I don't know that this is necessarily the best idea, because it will constrain our portability.

"nice" is just that.    CC @chriseth.

**Comment by bobsummerwill** [comment]
_From @chfast on June 6, 2016 8:44_

There might be a problem with GCC on Ubuntu 14.04.
But on the other hand we are updating the cmake, why not the compiler.

**Comment by bobsummerwill** [comment]
_From @chriseth on June 6, 2016 9:57_

I tend to agree with @bobsummerwill - what is our current situation regarding portability?

**Comment by bobsummerwill** [comment]
We are exceedingly portable.    I made a page to track that yesterday:

http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/portability.html#cpp-ethereum-portability

If we did want to introduce any C++14 usage, I think we would need to do it "Boost-style", within ifdefs with an alternative code-path for older compilers.    I think there are actually Boost pre-processor symbols we could hang that off, aren't there?

Or the easiest thing is just to not bother, and stick with C++11 features only.

**Comment by bobsummerwill** [comment]
So my inclination here is to say that this would be a mistake, and that we should stick with C++11 as a baseline.   CC @gcolvin.

If there are optional C++14 features which could be used within suitable ifdefs then that is probably OK, but I don't think we can require C++14 without seriously affecting our portability, and I just don't think it is worth doing that unless there is some massive performance gain or similar.

**Comment by chfast** [comment]
I think the better way to solve this is to provide the list of supported compilers and rules describing how this list will evolve over time. E.g. "we support 3 recent versions of GCC, 2 recent versions of clang, the recent version of Visual Studio".
