### ISSUE TITLE
Bash for Windows - Had to disable tests for jsonrpccpp CMake to work.   Why?

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3174]
_From @bobsummerwill on June 9, 2016 21:49_

The `setup.sh` for http://github.com/bobsummerwill/cpp-ethereum (merge_repos branch) didn't work vanilla when used on Bash for Windows, where it has been working in TravisCI.

The fix was simple enough ... `-DTESTS=0`, but why didn't this just work.    There is some fragility there which will likely show up in other distros too.    Need to dig in.

_Copied from original issue: ethereum/webthree-umbrella#566_

**Comment by chfast** [comment]
Can you try again?

**Comment by bobsummerwill** [comment]
I try every month or so, whenever there is a new OS release.

The main blocker right now is the incomplete networking stack, so we hit a runtime issue right away.
