### ISSUE TITLE
Require boost >= 1.61

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3186]
_From @chfast on July 1, 2016 15:47_

We still carry the boost 1.58 multiprecision bug workaround in https://github.com/ethereum/libweb3core/blob/develop/libdevcore/boost_multiprecision_number_compare_bug_workaround.hpp

We should require some minimal boost version, the higher the better. Supporting wide set of boost version can cause us trouble.

Unfortunately, Ubuntu 14.04 has boost 1.54 which is 3 years old.

_Copied from original issue: ethereum/webthree-umbrella#605_

**Comment by bobsummerwill** [comment]
Do you have a URL for the code-fix which was made?

I have forgotten the specifics.   Was it just a regression for a single release?

If so, I think it's entirely reasonable to just hard-fail the build for that one specific Boost version "Boost 1.58 not supported due to bug.   Please use a newer version" kind of thing, and remove that workaround.

**Comment by bobsummerwill** [comment]
_From @chfast on July 1, 2016 16:13_

Bug in 1.59: https://svn.boost.org/trac/boost/ticket/11648
Bug in 1.58: https://svn.boost.org/trac/boost/ticket/11328

**Comment by bobsummerwill** [comment]
Right, thanks for the links!

Does sniping out that one version make sense to you?    That wouldn't have been reasonable at the time, but I think it is fine now so many months have passed.

That approach would mean we would NOT break Trusty, but we would remove the workaround code.

**Comment by bobsummerwill** [comment]
_From @chfast on July 1, 2016 16:42_

The bug https://svn.boost.org/trac/boost/ticket/11648 is not a regression, so it is hard to track when it was introduces. It might be there from the beginning of the universe. And it's been fixed in 1.61.

**Comment by bobsummerwill** [comment]
Sorry - I see that now, so the first issue was a single-release issue which we could "snipe out", but the second is an issue for anything before 1.60.

I assume that we are affected by the issue?   Did you do any wrapper/workaround for that one, @chfast?

**Comment by bobsummerwill** [comment]
_From @chfast on July 1, 2016 18:7_

IIRC we were hit by the bug, the workaround was to use `bigint` instead of `u256` in a single place.

**Comment by ijcoe6ru** [comment]
Maybe 1.61 should be required because of #3158.

**Comment by chfast** [comment]
Changed to 1.61 because of https://github.com/ethereum/cpp-ethereum/issues/3158 and https://svn.boost.org/trac/boost/ticket/11648.

**Comment by bobsummerwill** [comment]
Yep - that makes sense.

**Comment by chfast** [comment]
We are building 1.63 (latest) from source.
