### ISSUE TITLE
macOS - TravisCI - Just plain running out of time on the tests - 50 min limit

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3193]
_From @bobsummerwill on July 7, 2016 16:5_

See https://travis-ci.org/bobsummerwill/cpp-ethereum/jobs/142383217, for example.

We are commonly running out of time in TravisCI for running all the tests.

There must be some very long-running ones which we can strip out?

_Copied from original issue: ethereum/webthree-umbrella#620_

**Comment by chfast** [comment]
See https://github.com/ethereum/cpp-ethereum/pull/3427.
