### ISSUE TITLE
Ubuntu Yakkety - Add support for Yakkety

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3194]
_From @bobsummerwill on July 7, 2016 19:58_

We don't have any support for Ubuntu Yakkety yet.

That would involve updating the Ethereum PPA (https://launchpad.net/~ethereum/+archive/ubuntu/ethereum), working through any build issues and runtime issues, and adding appropriate automation.

_Copied from original issue: ethereum/webthree-umbrella#624_

**Comment by themusicgod1** [comment]
issue #1: package libcryptop-dev -> libcrypto++-dev

**Comment by chriseth** [comment]
The PPA system for cpp-ethereum is currently broken and needs some serious work. In the near future, we will only provide docker builds.

**Comment by chfast** [comment]
Ubuntu 16.10 in `install_deps.sh`.
