### ISSUE TITLE
Ubuntu - Support for 32-bit builds

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3195]
_From @bobsummerwill on July 7, 2016 20:49_

So it appears that our PPAs already include i386 binaries.

At least @gcolvin has been successful in getting a 32-bit binaries, just by using `-DEVMJIT=0`, from what I recall.    Is that correct, Greg?

We also have working 32-bit binaries for ARM Linux (https://github.com/doublethinkco/cpp-ethereum-cross), so maybe we can get this to "just work" with a simple conditional somewhere in our CMake files which just force-disables EVMJIT if building for a 32-bit OS.     Or just gives a build-time error saying that EVMJIT is not supported on 32-bit OSes.

What do you think, @chfast?

This is obviously not a high priority issue, just a possible enhancement, which might help out some end-users.

And we might be able to do the same for Windows easily enough too, though we have the burden of https://github.com/ethereum/cpp-dependencies/releases/tag/vc140 to consider in that scenario.

It is really Linux where 32-bit will still be important for many years to come (for mobile, embedded, wearable and IoT scenarios).

_Copied from original issue: ethereum/webthree-umbrella#626_

**Comment by bobsummerwill** [comment]
_From @chfast on July 7, 2016 20:57_

Definitely there should be an fatal error in EVMJIT about building for targets other than x86-64. cpp-ethereum can adjust options accordingly not to scare users with errors.

https://github.com/ethereum/evmjit/issues/17

**Comment by bobsummerwill** [comment]
Thanks for the confirmation, @chfast.   So there would be two TODOs here, right?

1. Check in cpp-ethereum CMake files.
2. Check in evmjit CMake files.

And maybe other "bits" to be determined for any other weirdness which we need to handle in cpp-ethereum other than disabling EVMJIT.

@gcolvin Was it literally just `-DEMVJIT=0` which you needed to do?   Or was there some oddity where the ethbuild.sh scripts worked for you where using the umbrella directly did not?    Or was that just some transitional thing which you got passed?    Are you still using those scripts?   Thanks!

**Comment by bobsummerwill** [comment]
_From @chfast on July 12, 2016 9:50_

How to test that? Possible with docker?

**Comment by bobsummerwill** [comment]
Easiest way is probably just relying on @gcolvin :-)
We have 32-bit users on SBCs too, and it's been "just working" so far.

If we can remove the need for the PPA (I think we can easily enough), then there isn't anything specific to be done, I think.

As-and-when we have automated tests which are running the client, we could do automated tests for 32-bit builds via Docker, I would imagine, yes.

**Comment by gcolvin** [comment]
@bobsummerwill  Can't rely on me for much until after Devcon.  As far as we got we 32-bit builds was https://github.com/ethereum/webthree-umbrella/issues/51

**Comment by bobsummerwill** [comment]
So I don't think there is actually anything more to do here.

32-bit builds work, with JIT disabled.    I've said as much in the docs now.
