### ISSUE TITLE
openSUSE - add support in install_deps.sh 

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3196]
_From @bobsummerwill on July 8, 2016 2:56_

Hey @wainersec,

(moved from https://github.com/ethereum/webthree-umbrella/issues/552 which I have just closed, because openSUSE builds work, and we are on to "docs")

I have been working on an infrastructure-as-code alternative to these tedious per-distro sets of instructions, which will "go live" when we switch back to cpp-ethereum.

You can see my work-in-progress on that here:
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh

I would like to expand this install_deps.sh pattern pattern to cover more distros, so that our ethdocs.org instructions for the distros which we have bothered to do that can be simplified to, with the steps being executed directly and committed in with the code itself.
- git clone --recursive
- ./install_deps.sh
- cmake
- make

So maybe for openSUSE we can take that approach instead, rather than bothering with written instructions?

Please could help me out and copy https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh locally and run it, does it go into the right conditional?

I suspect it won't, and that we will need to do something fancier, as per http://unix.stackexchange.com/questions/92199/how-can-i-reliably-get-the-operating-systems-name

Thanks!

_Copied from original issue: ethereum/webthree-umbrella#630_

**Comment by bobsummerwill** [comment]
You're using Tumbleweed, right?

If you copy https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh locally and run it, does it go into the right conditional?

It looks like openSUSE has only got partial support for LSB (see https://bugzilla.suse.com/show_bug.cgi?id=977054) and that we might need to do something different to identify openSUSE releases.

Is it just Leap 42.1 and Tumbleweed which we would need to account for?

**Comment by wainersec** [comment]
Hi Bob, sorry for the late response, I was out for a few days, I'll go
through the documentation for installation on a clean system and will
feedback for doc enhacement. Regards.

**Comment by bobsummerwill** [comment]
Thanks!

And to be clear, what I am looking to achieve is NOT documentation, but implementation :-)

So the aim is to get openSUSE to the list of distros for which `install_deps.sh` works:

http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html

So that we can actually DELETE the manual documentation steps :-)
