### ISSUE TITLE
Alpine Linux - Add support in install_deps.sh

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3199]
_From @bobsummerwill on July 8, 2016 3:6_

Hey @rainbeam,

(split out from from https://github.com/ethereum/webthree-umbrella/issues/495)

I have been working on an infrastructure-as-code alternative to these tedious per-distro sets of instructions, which will "go live" when we switch back to cpp-ethereum.

You can see my work-in-progress on that here:
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/.travis.yml
- https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh

Now for the TravisCI bit, we're stuck with just Ubuntu Trusty automation for the time being, but we might well be able to expand that via Docker in the future.

Whatever the case, I would like to expand this install_deps.sh pattern pattern to cover more distros, so that our ethdocs.org instructions for the distros which we have bothered to do that can be simplified to, with the steps being executed directly and committed in with the code itself.
- git clone --recursive
- ./install_deps.sh
- cmake
- make

So maybe for Alpine we can take that approach instead, rather than bothering with written instructions?

Please could help me out and copy https://github.com/bobsummerwill/cpp-ethereum/blob/merge_repos/install_deps.sh locally and run it, does it go into the right conditional?

I suspect it won't, and that we will need to do something fancier, as per http://unix.stackexchange.com/questions/92199/how-can-i-reliably-get-the-operating-systems-name

_Copied from original issue: ethereum/webthree-umbrella#633_

**Comment by bobsummerwill** [comment]
_From @rainbeam on July 8, 2016 22:10_

@bobsummerwill: Alpine doesn't have `lsb_release` so the script doesn't work. It does have /etc/os-release:

```
# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.4.0
PRETTY_NAME="Alpine Linux v3.4"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

Yeah, agree on moving from written instructions.

**Comment by bobsummerwill** [comment]
Right - thanks!
Any recommended clever expression which we could use for the conditional here?
Which you could try running :-)

**Comment by chfast** [comment]
https://github.com/ethereum/cpp-ethereum/blob/develop/scripts/install_deps.sh#L209
