### ISSUE TITLE
Frequent Eth crashes since HF block

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3206]
_From @Bunjin on July 20, 2016 14:56_

Since the HF block I got twice this same crash of eth 1.3.0 on ubuntu 15.10 : 

⧎ ✘  16:53:58.653|p2p|5584071f…|Geth/v1.4.10-stable/linux/go1.5.1/JIT  Error reading - Abrupt peer disconnect: End of file
⧎ ✘  16:53:58.654|p2p|8fc5ab5c…|Geth/v1.4.10-stable/windows/go1.6.2  Error reading - Abrupt peer disconnect: End of file
eth: /home/whysos3rious/temp_eth/cpp-ethereum-merge_repos/libethereum/BlockChain.cpp:1125: std::tuplestd::vector<dev::FixedHash<32u, std::allocatordev::FixedHash<32u > >, dev::FixedHash<32u>, unsigned int> dev::eth::BlockChain::treeRoute(const h256&, const h256&, bool, bool, bool) const: Assertion `to' failed.
Abandon (core dumped)

_Copied from original issue: ethereum/webthree-umbrella#667_

**Comment by bobsummerwill** [comment]
_From @chriseth on July 20, 2016 17:22_

Do you still have the `.core` file?

**Comment by bobsummerwill** [comment]
Yes, anything you can do to help us pin this down would be much appreciated, @Bunjin.
Thanks for the report.

**Comment by bobsummerwill** [comment]
_From @Bunjin on July 21, 2016 13:16_

I'd be happy to help but I would need some guidance how to :) This is all rather new for me.

**Comment by bobsummerwill** [comment]
So yeah - that `.core` file which @chriseth refers to is a core dump (https://en.wikipedia.org/wiki/Core_dump) which can help us debug what actually happened.

I am also ignorant of how to use a `.core` file, having spent most of development history on Windows, and then more recently on macOS.

Which directory would that file go into, @chriseth?   The same directory as the executable?

Any other tips for @Bunjin?   Thanks!

**Comment by bobsummerwill** [comment]
_From @destenson on July 22, 2016 4:4_

@Bunjin, if there's no core file after the crash (named `core` or `core.###` where ### is the PID of the process that crashed) and when running `ulimit -c` results in `0`, then you need to enable core dumps by running `ulimit -c unlimited`.  After that, a core dump file is created in the current working directory of a process when it crashes. Normally this is the directory that it is executed from (not necessarily where the executable is located). A developer can use the core file with a tool like gdb to inspect the state of the program at the time of the crash. It's a raw dump of the memory allocated to the process, so essentially all variables and stack traces can be inspected.

Good luck.

**Comment by bobsummerwill** [comment]
_From @Bunjin on July 24, 2016 12:16_

@destenson Hi, thanks a lot for your answer and these very clear explanations. I'll try to catch the core file next time it crashes by enabling it before :)

Thanks

**Comment by axic** [comment]
@gumb0 @chfast is this still relevant?

**Comment by gumb0** [comment]
I don't remember seeing this particular assert failure lately, I'll close it as we don't have any details here anyway.

(We still have other frequent assert failures during sync though, see https://github.com/ethereum/cpp-ethereum/issues/4585 https://github.com/ethereum/cpp-ethereum/issues/4584 https://github.com/ethereum/cpp-ethereum/issues/4578)
