### ISSUE TITLE
Avoid nonce checks on fake (paranoia) miners.

### ISSUE THREAD

**Issue by vecna** [ethereum/cpp-ethereum#321]
*** [ 19:43:00 | miner-0 ] PARANOIA root: a01e907ca5b1ff4b7c802e29e85ca29bc4976718ab840f4f9f50c05159afc607
    *** [ 19:43:00 | miner-3 ] Post-reward stateRoot: ab038cf2…
    *** [ 19:43:00 | miner-1 ] PARANOIA root: a01e907ca5b1ff4b7c802e29e85ca29bc4976718ab840f4f9f50c05159afc607
    *** [ 19:43:00 | miner-3 ] PARANOIA root: a01e907ca5b1ff4b7c802e29e85ca29bc4976718ab840f4f9f50c05159afc607
    *** [ 19:43:00 | miner-2 ] PARANOIA root: a01e907ca5b1ff4b7c802e29e85ca29bc4976718ab840f4f9f50c05159afc607
    !!! [ 19:43:00 | miner-1 ] Bad block: Invalid nonce (h: 7d93eabf219553432b29789f67a83f92ac38cfea68d27f9471b7957b35ddb93d n:0000000000000000000000000000000000000000000000000000000000000000 d:167669)
    !!! [ 19:43:00 | miner-0 ] Bad block: Invalid nonce (h: 7d93eabf219553432b29789f67a83f92ac38cfea68d27f9471b7957b35ddb93d n:0000000000000000000000000000000000000000000000000000000000000000 d:167669)
    !!! [ 19:43:00 | miner-3 ] Bad block: Invalid nonce (h: 7d93eabf219553432b29789f67a83f92ac38cfea68d27f9471b7957b35ddb93d n:0000000000000000000000000000000000000000000000000000000000000000 d:167669)
    !!! [ 19:43:00 | miner-2 ] Bad block: Invalid nonce (h: 7d93eabf219553432b29789f67a83f92ac38cfea68d27f9471b7957b35ddb93d n:0000000000000000000000000000000000000000000000000000000000000000 d:167669)
    !!! [ 19:43:00 | miner-0 ] I'm not just paranoid. Cannot mine. Please file a bug report.

Happen with git head 735507a

**Comment by gavofyork** [comment]
Is this still an issue?

**Comment by vecna** [comment]
No thanks, I guess was just something that I've not understand or something that don't happen anymore.
