### ISSUE TITLE
trace functionality for calls

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3213]
_From @chriseth on August 2, 2016 9:27_

In order to debug calls without executing them (for example to simulate a transaction and see the effects), an rpc endpoint should be added that allows to trace a transaction (potentially unsigned) that is not broadcast. The interface should look like a combination of `eth_call` and `debug_traceTransaction` and should be in the `debug` namespace.

_Copied from original issue: ethereum/webthree-umbrella#688_

**Comment by yann300** [comment]
This story has already be done https://github.com/ethereum/cpp-ethereum/pull/3038
