### ISSUE TITLE
support standalone ethminer build

### ISSUE THREAD

**Issue by nerdralph** [ethereum/cpp-ethereum#3228]
i.e. cmake -DBUNDLE=miner
Most miners use pools now, and have no need to build eth and the other tools.

**Comment by bobsummerwill** [comment]
Just do 'cmake .. && make ethminer`.

Those BUNDLES are a bit weird, and I don't know that they even work.

**Comment by bobsummerwill** [comment]
See also https://github.com/ethereum/cpp-ethereum/issues/3211.

I think that we can massively improve the dependencies for ethminer there.

**Comment by nerdralph** [comment]
cmake -DBUNDLE=miner is how Genoil's works.
using "cmake .. && make ethminer" means cmake will generate makefiles for eth, ethkey, ethvm, ..., and probably spit out errors if you have the necessary dependencies for ethminer but not the other binaries.

**Comment by bobsummerwill** [comment]
OK - I will reopen, though I think the resolution to this will only happen when we have an `ethminer` repo.

**Comment by chfast** [comment]
ethminer builds: https://github.com/ethereum-mining/ethminer/releases.
