### ISSUE TITLE
ethminer/PhoneHome.h being modified by the build process

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3234]
I'm repeatedly seeing `ethminer/PhoneHome.h` being modified as a side-effect of our `cpp-ethereum` build process. Anybody else seeing this?

Line 21. `result.isInt()` gets modified to be `result.isIntegral()`

https://github.com/ethereum/cpp-ethereum/blob/develop/ethminer/PhoneHome.h#L21

Anybody got thoughts on where that might be coming from?

**Comment by chfast** [comment]
PhoneHome removed.
