### ISSUE TITLE
Find real solutions for hanging unit-tests

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3240]
We need to find real long-term solutions for our hanging unit-tests.

We have recently added "helper thread" workarounds for issues we are hitting without our unit-tests.   They make things more tolerable in the short-term and give us some breathing space, but they don't solve the root problems.    We need to solve the root problems.
1. Mining timeouts
2. STDOUT "dots"

This new code also uses `std::future<>` which is not supported on various ARM architectures:

```
[ 75%] /home/crosseth/eth/wd/cpp-ethereum/test/libethereum/test/TestHelper.cpp: In function 'void dev::test::testMiningFunc(void (*)())':
/home/crosseth/eth/wd/cpp-ethereum/test/libethereum/test/TestHelper.cpp:1101:79: error: invalid use of incomplete type 'class std::future<void>'
   auto future = std::async(std::launch::async, &std::thread::join, &threadTest);
```

Because of [this GCC bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64735)

What we should actually do is work out the root cause of the hangs or crashes which are causing these long delays / hangs.     Maybe we create a PR where we the tests run through GDB?    Or we add additional logging, or something?

**Comment by winsvega** [comment]
mining timeouts 
https://github.com/ethereum/cpp-ethereum/pull/3286

**Comment by chfast** [comment]
Hanging BC tests also fixed.
