### ISSUE TITLE
CentOS - Let the use of lib64

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/cpp-ethereum#3244]
Hi
I am building the RPM, and I realized that it always try to install in /usr/lib, which it should be /usr/lib64 for 64 bits systems.
Most distributions use this -DLIB_SUFFIX=64 to tell the architecture. Can you add this support into the CMAKE or maybe LIB_INSTALL_DIR, whatever you consider is the best.

**Comment by chfast** [comment]
After quick search the [GNUInstallDir](https://cmake.org/cmake/help/v3.4/module/GNUInstallDirs.html) module should be helpful.

However, our CMake install code is little obfuscated. What do you think @bobsummerwill? @daniel-lucio do you have capacity to drive this change?

**Comment by daniel-lucio** [comment]
I will add a -DLIBDIR=%{_libdir} and let you know

**Comment by daniel-lucio** [comment]
No, it doesnt work. I will work around and wait for the patch.

**Comment by bobsummerwill** [comment]
This all sounds sensible, but yes, our CMake support, while improving, is still "sub-optimal".

If you have a good idea of "what good looks like" in respect to these 64-bit lib paths then it would certainly make sense to ensure we support that.

**Comment by chfast** [comment]
I used GNUInstallDirs here: https://github.com/ethereum/evmjit/pull/93/files but it still installs to lib on Ubuntu.

**Comment by daniel-lucio** [comment]
It is hardcoded somewhere, sorry my cMake skills are not very good. I did a workaround in the SPEC file.

**Comment by daniel-lucio** [comment]
Reading the cmake files, i found this:
install(TARGETS ethereum RUNTIME DESTINATION bin ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)

as my understanding, by addding like this:
install(TARGETS ethereum RUNTIME DESTINATION bin ARCHIVE DESTINATION lib${LIB_SUFFIX} LIBRARY DESTINATION lib${LIB_SUFFIX})

Not an expert, but I think this could work

**Comment by bobsummerwill** [comment]
Hmm.   See:

- https://bugzilla.redhat.com/show_bug.cgi?id=795542
- https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=126c993d031f6f7be4970a67621da92f580d4e5a

Which says that Debian-based distros don't respect `lib64`.    So I think that your `GNUInstallDirs()` changes are likely adequate and correct, @chfast.    You just won't see any difference from that when running on Ubuntu.

We should make that same change for `cpp-ethereum` and then see what results that gives you on  CentOS, @daniel-lucio.    Want to try to make a PR for that?    It would just be a matter of copying Pawel's pattern, I think.

**Comment by bobsummerwill** [comment]
So maybe ...

Before:

    install(TARGETS ethereum RUNTIME DESTINATION bin ARCHIVE DESTINATION lib LIBRARY DESTINATION lib)

After:

    include(GNUInstallDirs)
    install(TARGETS ethereum RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR} LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR})

**Comment by daniel-lucio** [comment]
Nice,

BTW @chfast , can you put here the files in the debian package? It seems I have a coredump, I just want to discard any missing file.

**Comment by chfast** [comment]
In #3518, I disabled installation of any library.

**Comment by chriseth** [comment]
So can this be closed?
