### ISSUE TITLE
Unable to meet install dependencies when using apt-get on Ubuntu 16.04

### ISSUE THREAD

**Issue by adrianbrink** [ethereum/cpp-ethereum#3245]
Hi,

so I am following this [guide](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/linux-ubuntu-ppa.html).

**What am I trying to achieve?**
Install cpp-ethereum on Ubuntu 16.04 for mining.

**What is the expected result?**
A succeeding installation.

**What is the error?**
```
adrian@adrian:~|⇒  sudo apt-get install cpp-ethereum
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cpp-ethereum : Depends: alethzero but it is not going to be installed
                Depends: mix-ide but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**My solution so far.**
It seems that alethzero was a former part of cpp-ethereum. I'm guessing that the cpp-ethereum release on apt-get hasn't been updated.
Same goes for remix.

**Comment by chriseth** [comment]
This will hopefully be fixed by the next ppa release. In the meantime, does `apt-get install eth` work?

**Comment by bobsummerwill** [comment]
I have just updated that page with a suitable warning.

We have some broken windows right now I am afraid.

This work is being tracked as https://github.com/ethereum/cpp-ethereum/issues/3222
