### ISSUE TITLE
No major in the libs?

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/cpp-ethereum#3248]
Hi, again
As I am doing the RPM, by policy libXXXX should have libxxxx.so.x.y.z files,
and libXXXX-devel should have libxxxx.so (usually symlink)

the package only outputs .so files.  My question is. Does cpp-etherum is planned to be used as a library? if it does, then we need to use the x.y.z, if it doesnt I can pack them in a simple RPM.

**Comment by bobsummerwill** [comment]
We don't publish any API for the libraries, no, @daniel-lucio, so versioned releases make no sense.

The only expectation of stability which end-users can have is for the command-line apps and the RPC/IPC interface which `eth` provides.

Are you doing RPMs for CentOS?   Or RHEL?   Or both?

We should get `scripts/install_deps.sh` working for these distros, if you are working at this stuff at the moment.

**Comment by daniel-lucio** [comment]
I do rpms for centos. But in this specific case, it's for MAGEIA since my mining server uses it. It will be available in MAGEIA 6.
