### ISSUE TITLE
CentOS - add support in install_deps.sh

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3250]
We should get `scripts/install.sh` working for CentOS, so that building on that distro would work just the same as Ubuntu, Debian and macOS already do ...

[Building Linux from source](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html).

CC @daniel-lucio and see also https://github.com/ethereum/cpp-ethereum/issues/3248.

**Comment by bobsummerwill** [comment]
So are you **already** creating RPMs?   Or just started doing that?
Just `cpp-ethereum`, or `solidity` too?

We should get whatever you have done documented in [Installing Binaries](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/index.html).

**Comment by bobsummerwill** [comment]
Aside - We already have [Building from Source for Fedora](http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux-fedora.html) manual instructions, and some partial effort towards getting those into `scripts/install_deps.sh` ...

https://github.com/ethereum/cpp-ethereum/blob/develop/scripts/install_deps.sh#L308

But it looks like Fedora doesn't use RPM, so ignore me!

**Comment by daniel-lucio** [comment]
Im building RPMS as I need it. Let me finish the Mageia and then I will work with Centos6/7. However, its more likely not to find server distros when mining, because hardware support (new hardware, old distro)

**Comment by bobsummerwill** [comment]
@daniel-lucio says ...

Look:
[ 67%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Client.cpp.o
cd /builddir/build/BUILD/cpp-ethereum-develop/build/libethereum && /usr/bin/c++   -DDISABLE_BROKEN_UNIT_TESTS_UNTIL_WE_FIX_THEM -DETH_FATDB -DETH_HAVE_SECP256K1 -DETH_MINIUPNPC -DETH_TRUE -DSHAREDLIB -Dethereum_EXPORTS -isystem /usr/include/jsoncpp -I/builddir/build/BUILD/cpp-ethereum-develop/build -I/builddir/build/BUILD/cpp-ethereum-develop/build/include -I/builddir/build/BUILD/cpp-ethereum-develop/libethereum/.. -I/builddir/build/BUILD/cpp-ethereum-develop/libethereum/../utils  -std=c++11 -fpermissive -fuse-ld=gold -DSTATICLIB -O2 -g -DETH_RELEASE -fPIC   -Wall -Wextra -Werror -Wno-unknown-pragmas -fPIC -o CMakeFiles/ethereum.dir/Client.cpp.o -c /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp
/builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp: In member function 'void dev::eth::Client::onBadBlock(dev::Exception&) const':
/builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:140:51: error: no matching function for call to 'diagnostic_information(dev::Exception&, bool)'
   cwarn << boost::diagnostic_information(_ex, true);
                                                   ^
/builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:140:51: note: candidates are:
In file included from /usr/include/boost/exception/detail/exception_ptr.hpp:21:0,
                 from /usr/include/boost/exception_ptr.hpp:9,
                 from /usr/include/boost/thread/future.hpp:28,
                 from /usr/include/boost/thread.hpp:24,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/../libdevcore/Guards.h:30,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.h:34,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:22:
/usr/include/boost/exception/diagnostic_information.hpp:167:5: note: template<class T> std::string boost::diagnostic_information(const T&)
     diagnostic_information( T const & e )
     ^
/usr/include/boost/exception/diagnostic_information.hpp:167:5: note:   template argument deduction/substitution failed:
/builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:140:51: note:   candidate expects 1 argument, 2 provided
   cwarn << boost::diagnostic_information(_ex, true);
                                                   ^
In file included from /usr/include/boost/exception_ptr.hpp:9:0,
                 from /usr/include/boost/thread/future.hpp:28,
                 from /usr/include/boost/thread.hpp:24,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/../libdevcore/Guards.h:30,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.h:34,
                 from /builddir/build/BUILD/cpp-ethereum-develop/libethereum/Client.cpp:22:
/usr/include/boost/exception/detail/exception_ptr.hpp:470:5: note: std::string boost::diagnostic_information(const boost::exception_ptr&)
     diagnostic_information( exception_ptr const & p )
     ^
/usr/include/boost/exception/detail/exception_ptr.hpp:470:5: note:   candidate expects 1 argument, 2 provided
make[2]: Leaving directory `/builddir/build/BUILD/cpp-ethereum-develop/build'
make[1]: Leaving directory `/builddir/build/BUILD/cpp-ethereum-develop/build'


RPM build errors:
make[2]: *** [libethereum/CMakeFiles/ethereum.dir/Client.cpp.o] Error 1
make[1]: *** [libethereum/CMakeFiles/ethereum.dir/all] Error 2
make: *** [all] Error 2


Is it a minimum release of boost? I am ussing 1.53

**Comment by bobsummerwill** [comment]
Yes, though we haven't added in-build-system enforcement.

You want 1.60 at least, but preferably 1.61.    1.53 is way too old.   2.5 years old!

See https://github.com/ethereum/cpp-ethereum/issues/3186

**Comment by daniel-lucio** [comment]
Well, Mageia has 1.55 and it compiles. I will build the RPM for 1.60

**Comment by bobsummerwill** [comment]
It might compile, but there might be odd runtime issues.

@chfast has the most complete knowledge of what we have need to do for Boost.   He has submitted multiple Boost fixes for bugs which affected us with older versions.

**Comment by chfast** [comment]
For boost, we have to build it from source because:
1. We should ship with the same version everywhere.
2. We should be able to upgrade as soon as needed (in case of bugs detected), not waiting for OS to ship new version after years.
3. We should link boost statically.

**Comment by daniel-lucio** [comment]
http://inside-out.xyz/technology/cpp-ethereum-rpm-for-centos-7.html

RPM's are ready to go :) enjoy!
