### ISSUE TITLE
Windows - error: in "SolidityImports/relative_import": check c.compile() has failed

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3251]
We see this failure in the Windows unit-tests on some runs.   Not 100%.

ie... https://ci.appveyor.com/project/ethereum/solidity/build/1.0.428

    soltest.exe -- --ipcpath \\.\pipe\geth.ipc
    Running 911 test cases...
    C:/projects/solidity/test/libsolidity/Imports.cpp(85): error: in "SolidityImports/relative_import": check c.compile() has failed
    *** 1 failure is detected in the test module "EthereumTests

**Comment by chriseth** [comment]
Fixed in https://github.com/ethereum/solidity/pull/987
