### ISSUE TITLE
Memory requirements when running eth --json-rpc

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/cpp-ethereum#3265]
when running ./eth --json-rpc --rpccorsdomain \*, there is no mining just block management. What are the Memory/CPU minimum requirements for this.  I was thinking about a 2 GB RAM VPS, as it just 'manages' others. Please advise.

**Comment by chriseth** [comment]
2GB sounds about right, but note that this is still a full node, it keeps its own blockchain and verifies all transactions. Furthermore, if you use `--json-rpc --rpccorsdomain *`, you fully expose the node to anyone on the internet (depending on your firewall), so please be prepared for dos attacks and do not store any secrets inside the node.

**Comment by daniel-lucio** [comment]
I know. i port 8545 will be not public :) thanks
