### ISSUE TITLE
Ubuntu 16.04 install_deps.sh does not function correctly

### ISSUE THREAD

**Issue by danyill** [ethereum/cpp-ethereum#3266]
Following http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html#building-linux-from-source I find I get an output indicating that:

`Reading state information... Done`
`Note, selecting 'zlib1g-dev' instead of 'libz-dev'`
`E: Unable to locate package llvm-3.9-dev`
`E: Couldn't find any package by glob 'llvm-3.9-dev'`
`E: Couldn't find any package by regex 'llvm-3.9-dev'`

Looking at this in more detail, it appears that `install_deps.sh` refers to `llvm-3.9-dev` whereas this is only available in Ubuntu Yakkety, not Ubuntu Xenial:

http://packages.ubuntu.com/search?keywords=llvm-3.9-dev

Suggest this dependency be changed to `llvm-3.8-dev`. At least that's what I'm trying at the moment...

**Comment by bobsummerwill** [comment]
Right - thanks for the report, @danyill.

@chfast Please could you add suitable conditionals, so that `scripts/install_deps.sh` works for all supported Ubuntu versions?   Thanks!

`scripts/build.sh` would need a conditional for its hard-coded path for `LLVM_DIR` too.

**Comment by chfast** [comment]
I can add support for Xenial, but not for other versions as they are not supported by LLVM deb packages. Ubuntu provides broken LLVM packages so we cannot use them.

But do you really want to use this script for both Travis and user builds? It is very intrusive, adds additional APT repos,  installs unauthenticated packages.

**Comment by bobsummerwill** [comment]
Xenial would be good.

>> But do you really want to use this script for both Travis and user builds?
>> It is very intrusive, adds additional APT repos, installs unauthenticated packages.

That is the reality of what it takes to build `cpp-ethereum`, so yes.

Though it would also be good to support a nice build-from-source flow for LLVM here too, not sure what that would mean for `scripts/install_deps.sh`.

**Comment by chfast** [comment]
I added prebuilt LLVM for Travis to make it faster. They are not needed for end users. Hm... maybe I will add `if [ TRAVIS ]` for that too?

**Comment by pirapira** [comment]
I met the same problem and posted #3287
