### ISSUE TITLE
macOS Sierra - Enable automated tests

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3268]
We are currently without any automated tests for `cpp-ethereum` on macOS Sierra, because the VMWare VM which we get via TravisCI is just too slow to both build and test consistently within the 48 minute time limit - so we're just building for now.

We might need #3142 (BulkBuild) to make this workable.

**Comment by chfast** [comment]
MacOS builds on Circlec CI: https://circleci.com/gh/ethereum/cpp-ethereum/2645.
