### ISSUE TITLE
CentOS - Please add support for LLVM 3.5

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/cpp-ethereum#3275]
As I see, LLVM 3.8 is needed, but that is too new. Most distributions have 3.5 or older. LLVM is not an easy package to port back.

Can you add support to let compilation against 3.5?

**Comment by bobsummerwill** [comment]
So @chfast will have the best information here, but I doubt we will support LLVM 3.5.  It is way too old.

We don't need to constrain ourselves to package versions shipped with distros.   In fact, we are moving towards build-from-source for most of our dependencies, so we have complete control of versioning and of how binaries are built.

Which CentOS versions are of concern to you?    Other distros?   Thanks!

Let's make this specific, not general.

**Comment by daniel-lucio** [comment]
Centos6 has LLVM 3.4.2 (from EPEL) 
Centos7 has LLVM 3.4.2 (from EPEL)
Mageia5 has LLVM 3.5
Mageia6 (when released) has LLVM 3.8.1

Currently, I am building the EVM support on Magiea5. I have ported back 3.8.1 (and using system libraries. There are many good reasons why using system's is better than using yourselves'). But it was not as trivial as rebuilding the RPM from Mageia6.

**Comment by bobsummerwill** [comment]
You should just build LLVM-3.9 from source for this case.
We have CMake support for doing just that.

**Comment by daniel-lucio** [comment]
Yes, and I have done my patch to disable it. By policy in Mageia, packages can not download stuff themselves. (Don't ask why I didn't write it).

**Comment by bobsummerwill** [comment]
It doesn't have to be download on demand.   You should just be able to grab LLVM sources in your package at the same time as grabbing cpp-ethereum, and to point to that.

I think ... ?

Or if not, maybe we need a minor tweak to the CMake files for `evmjit` such that build-from-source can work without existing source which you just point at.

**Comment by bobsummerwill** [comment]
Or your easiest starting point would be just to use `-DEVMJIT=Off` and not to build the JIT at all.

The performance of the Interpreter is pretty comparable, and skipping the LLVM dependency is very helpful in some cases, like the one you are looking at here.

**Comment by daniel-lucio** [comment]
Start point with -DEVMJIT=Off done.
I am in bloating the package with the missing option. Usually RPM's must have all enabled, that way users don't have to recompile. This is the point of doint packages.

**Comment by bobsummerwill** [comment]
Great!

The issue with pre-compiling anything is that it assumes that there is a single canonical "way to build" which covers everybody's needs.    That is not true.    It is often a decent approximation to reality - except when it isn't :-)

This is something which I learnt over decades at EA - that large software systems are composed of numerous packages, and that the test-matrix of ways in which particular versions of those packages can be combined (let alone when you get into configurations or modes) quickly goes from tractable to being near-infinite.

So prebuilt binaries only work well for packages with no external dependencies, or with very few and very stable dependencies.   Beyond those simple use-cases you are are rapidly stepping into making choices for users, and the only viable approach there is extreme conservatism (like wanting to support LLVM 3.5, even though it is ancient and very buggy).

We have been hurt multiple times by packaging systems with `cpp-ethereum`, where only ancient versions of packages (with bugs which break our code - see `cryptopp, jsoncpp, json-rpc-cpp`) are available, or where only dynamic libraries are available not static libraries (various packages on macOS), or where binaries are built with flags which don't match our needs (see `libcurl`, which is the most configurable thing you can imagine).

**Comment by chfast** [comment]
LLVM is not a runtime dependency, so no need to install it by users. You can just speed up development by providing prebuilt LLVM (3.8 or 3.9). But using prebuilt LLVM is not the suitable for building releases.

**Comment by chfast** [comment]
LLVM 3.5 is too old. We are constantly pushing [fixes and improvements](https://github.com/llvm-mirror/llvm/commits?author=chfast) to LLVM and we need quite recent version of it.

**Comment by bobsummerwill** [comment]
We cannot support LLVM 3.5.   Too old.   Sorry!
