### ISSUE TITLE
CentOS - Core dump

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/cpp-ethereum#3281]
./eth --json-rpc --rpccorsdomain * -a 002a0f8b3d5d866e3ceafb904e7f48741c43026b --network-id 1 --vm smart -v 9 --peer-stretch 1234 --peers 1234  --network-id 1 --upnp off --sociable 

log of logs.... and then.....

⧫   11:05:23 PM.143|p2p|bbe3a82f…|Geth/v1.5.0-unstable/linux/go1.5.1  Transactions ( 1 entries)
 ┅▶  11:05:23 PM.144|txcheck0  Queued vaguely legit-looking transaction #870bead1…
⧎ ◌  11:05:23 PM.144|p2p|c1e0aacc…|Geth/v1.5.0-unstable/linux/go1.5.1  BlocksHeaders ( 0 entries) : NoMoreHeaders
⧎ ○  11:05:23 PM.145|p2p|c1e0aacc…|Geth/v1.5.0-unstable/linux/go1.5.1  Requesting 192  block headers staring from 1930737 
⧎ ◌  11:05:23 PM.145|p2p|6b99a91e…|Geth/v1.4.4-stable/darwin/go1.6  BlocksHeaders ( 0 entries) : NoMoreHeaders
⧎ ○  11:05:23 PM.145|p2p|6b99a91e…|Geth/v1.4.4-stable/darwin/go1.6  Requesting 640  block headers staring from 1927665 
⧎ ◌  11:05:23 PM.146|p2p|176094b9…|Geth/v1.4.4-stable/darwin/go1.6  BlocksHeaders ( 192 entries) 
⧎ ○  11:05:24 PM.065|p2p|176094b9…|Geth/v1.4.4-stable/darwin/go1.6  Requesting 832  block headers staring from 1932977 
⧎ ◌  11:05:24 PM.065|p2p|51360a94…|Geth/v1.4.10-stable-5f55d95a/linux/go1.6.2  GetBlockBodies ( 10 entries)
⧎ ◌  11:05:24 PM.409|p2p|51360a94…|Geth/v1.4.10-stable-5f55d95a/linux/go1.6.2  10 blocks known and returned; 0 blocks unknown; 0 blocks ignored
⧫   11:05:24 PM.410|p2p|6a673afa…|Geth/v1.5.0-unstable/linux/go1.5.1  Transactions ( 1 entries)
⧎ ℹ  11:05:24 PM.410|p2p  p2p.connect.egress recvd hello header
⧎ ◌  11:05:24 PM.411|p2p|e647348e…|Geth/v1.4.9-stable/linux/go1.5.1  BlocksHeaders ( 192 entries) 
▧ ◌  11:05:24 PM.566|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  11:05:24 PM.566|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.568|verifier0  Expected trie root: 1d0e8501fc807139b0d31798e832278cabfd4505b4a66ac73252a56f80c6f4ee
▧ ◌  11:05:24 PM.568|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.568|eth  Expected trie root: 9abd9e9111e9983263e47f2a245abdfaabadb678866de5751fd2cae1498f9170
▧ ◌  11:05:24 PM.568|eth  Expected uncle hash: b2f1927fa2327b2a32e1b5596e3baa3c063eed182e511f3157435698f9c34601
☍ ◌  11:05:24 PM.568|eth  Attempting import of #6c6a48d8… ...
▧ ◌  11:05:24 PM.571|verifier1  Expected trie root: 05b67069e88e19eef1189f391dae9f06b8d33e3a3459f333fa24f1f2828fc937
▧ ◌  11:05:24 PM.571|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.572|verifier0  Expected trie root: 93e9864245f3bbee6498e9faff9ca65ff1603ac483713296612bca589c32b074
▧ ◌  11:05:24 PM.572|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.576|verifier1  Expected trie root: 916ecbe224a2d250364ecb2152a7aec2434c5c1bf207171cc9f75c287ee4eebc
▧ ◌  11:05:24 PM.576|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.577|verifier0  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  11:05:24 PM.577|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.581|verifier0  Expected trie root: e2946a328469e4683d21efc9d125da74ed5d9af39e8af96c2933d3c312400f76
▧ ◌  11:05:24 PM.581|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.583|verifier1  Expected trie root: d3982d737b40229210913a465a6b5bf079360b3826aae05fa334e03b4cff39bb
▧ ◌  11:05:24 PM.583|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.585|verifier0  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  11:05:24 PM.585|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.589|verifier1  Expected trie root: 3afb3b6d21d77c5757d844b148bbaf275e6552243ac81d57dc36890d71a1e577
▧ ◌  11:05:24 PM.589|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.590|verifier0  Expected trie root: 9645c90a9a0eef198d0db6b218bb93b564dbbf2d77c90eae042f7f7c10bcf8d0
▧ ◌  11:05:24 PM.590|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
Segmentation fault (core dumped)
⧫   11:05:23 PM.143|p2p|bbe3a82f…|Geth/v1.5.0-unstable/linux/go1.5.1  Transactions ( 1 entries)
 ┅▶  11:05:23 PM.144|txcheck0  Queued vaguely legit-looking transaction #870bead1…
⧎ ◌  11:05:23 PM.144|p2p|c1e0aacc…|Geth/v1.5.0-unstable/linux/go1.5.1  BlocksHeaders ( 0 entries) : NoMoreHeaders
⧎ ○  11:05:23 PM.145|p2p|c1e0aacc…|Geth/v1.5.0-unstable/linux/go1.5.1  Requesting 192  block headers staring from 1930737 
⧎ ◌  11:05:23 PM.145|p2p|6b99a91e…|Geth/v1.4.4-stable/darwin/go1.6  BlocksHeaders ( 0 entries) : NoMoreHeaders
⧎ ○  11:05:23 PM.145|p2p|6b99a91e…|Geth/v1.4.4-stable/darwin/go1.6  Requesting 640  block headers staring from 1927665 
⧎ ◌  11:05:23 PM.146|p2p|176094b9…|Geth/v1.4.4-stable/darwin/go1.6  BlocksHeaders ( 192 entries) 
⧎ ○  11:05:24 PM.065|p2p|176094b9…|Geth/v1.4.4-stable/darwin/go1.6  Requesting 832  block headers staring from 1932977 
⧎ ◌  11:05:24 PM.065|p2p|51360a94…|Geth/v1.4.10-stable-5f55d95a/linux/go1.6.2  GetBlockBodies ( 10 entries)
⧎ ◌  11:05:24 PM.409|p2p|51360a94…|Geth/v1.4.10-stable-5f55d95a/linux/go1.6.2  10 blocks known and returned; 0 blocks unknown; 0 blocks ignored
⧫   11:05:24 PM.410|p2p|6a673afa…|Geth/v1.5.0-unstable/linux/go1.5.1  Transactions ( 1 entries)
⧎ ℹ  11:05:24 PM.410|p2p  p2p.connect.egress recvd hello header
⧎ ◌  11:05:24 PM.411|p2p|e647348e…|Geth/v1.4.9-stable/linux/go1.5.1  BlocksHeaders ( 192 entries) 
▧ ◌  11:05:24 PM.566|verifier1  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  11:05:24 PM.566|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.568|verifier0  Expected trie root: 1d0e8501fc807139b0d31798e832278cabfd4505b4a66ac73252a56f80c6f4ee
▧ ◌  11:05:24 PM.568|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.568|eth  Expected trie root: 9abd9e9111e9983263e47f2a245abdfaabadb678866de5751fd2cae1498f9170
▧ ◌  11:05:24 PM.568|eth  Expected uncle hash: b2f1927fa2327b2a32e1b5596e3baa3c063eed182e511f3157435698f9c34601
☍ ◌  11:05:24 PM.568|eth  Attempting import of #6c6a48d8… ...
▧ ◌  11:05:24 PM.571|verifier1  Expected trie root: 05b67069e88e19eef1189f391dae9f06b8d33e3a3459f333fa24f1f2828fc937
▧ ◌  11:05:24 PM.571|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.572|verifier0  Expected trie root: 93e9864245f3bbee6498e9faff9ca65ff1603ac483713296612bca589c32b074
▧ ◌  11:05:24 PM.572|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.576|verifier1  Expected trie root: 916ecbe224a2d250364ecb2152a7aec2434c5c1bf207171cc9f75c287ee4eebc
▧ ◌  11:05:24 PM.576|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.577|verifier0  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  11:05:24 PM.577|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.581|verifier0  Expected trie root: e2946a328469e4683d21efc9d125da74ed5d9af39e8af96c2933d3c312400f76
▧ ◌  11:05:24 PM.581|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.583|verifier1  Expected trie root: d3982d737b40229210913a465a6b5bf079360b3826aae05fa334e03b4cff39bb
▧ ◌  11:05:24 PM.583|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.585|verifier0  Expected trie root: 56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
▧ ◌  11:05:24 PM.585|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.589|verifier1  Expected trie root: 3afb3b6d21d77c5757d844b148bbaf275e6552243ac81d57dc36890d71a1e577
▧ ◌  11:05:24 PM.589|verifier1  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
▧ ◌  11:05:24 PM.590|verifier0  Expected trie root: 9645c90a9a0eef198d0db6b218bb93b564dbbf2d77c90eae042f7f7c10bcf8d0
▧ ◌  11:05:24 PM.590|verifier0  Expected uncle hash: 1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
Segmentation fault (core dumped)

**Comment by bobsummerwill** [comment]
Do you have access to the core dump, please?

I believe that @chriseth can do something with that.    I don't have a Linux box myself right now.

**Comment by daniel-lucio** [comment]
No, but if you tell me how I force saving it I can send it to you

**Comment by bobsummerwill** [comment]
I've leave @chriseth to do that :-)

**Comment by chriseth** [comment]
@daniel-lucio in the directory where you ran eth, there should be a file called `core`
