### ISSUE TITLE
OS X El Capitan - Undefined symbols for architecture x86_64 -CryptoPP::Integer::Integer

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3298]
This is a build error I am now getting locally on my OS X El Capitan environment.

Only shows with `-DTESTS=On`, which I note that we do NOT have enabled within TravisCI (because the turnaround time for that build in TravisCI exceeds the 48 min maximum).

I suspect that CryptoPP has changed underneath us again as the "rolling release" pattern of Homebrew strikes again.   The only mitigation we have against this instability is our continuous integration, and it's `brew update && brew upgrade` pattern, so we at least learn about these issues as soon as they happen, and then we have to scramble from there.

https://github.com/Homebrew/homebrew-core/commits/master/Formula/cryptopp.rb

[100%] Linking CXX executable testeth
Undefined symbols for architecture x86_64:
  "CryptoPP::Integer::Integer(unsigned char const_, unsigned long, CryptoPP::Integer::Signedness, CryptoPP::ByteOrder)", referenced from:
      devcrypto::cryptopp_cryptopp_secp256k1libport::test_method() in crypto.cpp.o
      devcrypto::recoverVgt3::test_method() in crypto.cpp.o
      dev::crypto::secretToExponent(dev::SecureFixedHash<32u> const&) in crypto.cpp.o
      CryptoPP::DL_SignerBaseCryptoPP::ECPPoint::SignAndRestart(CryptoPP::RandomNumberGenerator&, CryptoPP::PK_MessageAccumulator&, unsigned char_, bool) const in crypto.cpp.o
      CryptoPP::DL_SimpleKeyAgreementDomainBaseCryptoPP::ECPPoint::Agree(unsigned char_, unsigned char const_, unsigned char const_, bool) const in crypto.cpp.o
      CryptoPP::DL_SimpleKeyAgreementDomainBaseCryptoPP::ECPPoint::GeneratePublicKey(CryptoPP::RandomNumberGenerator&, unsigned char const_, unsigned char*) const in crypto.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by chfast** [comment]
Upstream bug: https://github.com/weidai11/cryptopp/issues/337.
