### ISSUE TITLE
Race condition with BuildInfo.h generation

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3300]
There is a race condition with `buildinfo.h` generation within the build system.

It only manifests when building with very broad parallelism (`-j8` or `-j16`, for example).

The issue occurs because the makefile generated by the CMake process creates a phony target for that generation step, but does not generate any explicit dependencies onto that phony target from the targets for the C++ code compilation which use that generated header file.

With only 2 or 4 cores, that doesn't seem to be a problem.   I assume that the processes are launched in parallel but the codegen step nearly always completes in time.    With 8 or 16 processes racing, one of the C++ processes often gets to requiring that header file before it is actually generated.

We need to work out how to tweak our CMake files so that it generate those dependency edges in the makefile.

**Comment by hobi82** [comment]
Quick question: Is this the same issue I see on my build system (Windows 10 1607, CMake, Visual C++ 2015):

---snip
**command used: src\github.com\ethereum\cpp-ethereum\build>cmake --build . --config RelWithDebInfo**

Build FAILED.

"C:\Users\hobi\src\github.com\ethereum\cpp-ethereum\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\Users\hobi\src\github.com\ethereum\cpp-ethereum\build\bench\bench.vcxproj" (default target) (3) ->
"C:\Users\hobi\src\github.com\ethereum\cpp-ethereum\build\libdevcore\devcore.vcxproj" (default target) (4) ->
(ClCompile target) ->
  **C:\Users\hobi\src\github.com\ethereum\cpp-ethereum\libdevcore\Common.cpp(25): fatal error C1083: Cannot open include
file: 'cpp-ethereum/BuildInfo.h': No such file or directory [C:\Users\hobi\src\github.com\ethereum\cpp-ethereum\build\l**
ibdevcore\devcore.vcxproj]

    0 Warning(s)
    1 Error(s)
---snap

If yes, how can I fix that? I was following this wiki entry to setup my build system: http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html

thank you!

**Comment by hwxie** [comment]
I have the exact same issue as hobi82 with same OS. Is there a flag I can use to limit to building by 2 cores?

**Comment by bobsummerwill** [comment]
@hobi82 @hwxie It could well be the same issue, yes.

How many cores do you both have?  I've only got a dual core Windows 10 Surface Pro 3 and have never seen the issue there (maybe because it only manifests for 4x, 8x, etc).

You are both building on the command-line.   Have you tried from the IDE?   It might be possible to "trick your way past it" with a selective build of just the single project which generates that header file.    You just need to get that step to run once and you are past the issue.

That would only be a workaround, obviously.

**Comment by fredcrs** [comment]
I have the same problem but I didnt understood how to fix it. Trying to compile on ubuntu 14 amd64

**Comment by chriseth** [comment]
A workaround is to use `make` instead of `make -f` - if you use that.

**Comment by fredcrs** [comment]
If I do
$: make
I got this error
CMake Error: File ....cpp-ethereum/BuildInfo.h.in does not exist.
