### ISSUE TITLE
Unable to make project on El Capitan (source file is not valid UTF-8)

### ISSUE THREAD

**Issue by aliyahyaaamir** [ethereum/cpp-ethereum#3305]
I'm unable to make the cpp-ethereum project from source on Mac OS El Capitan 10.11.6 (already tried homebrew and that didn't work) I've included the log files from when I execute "cmake .." and "make -j4" although my errors only occur in the latter instance.

Any help would be appreciated, see my gist below for the log files.

https://gist.github.com/aliyahyaaamir/925c324e795cbdd9e1450abf0c702498

**Comment by bobsummerwill** [comment]
It looks like your xcode install itself is corrupted.   You could probably verify that by opening the `new` file, which appears to be the issue ...

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/new`

... in a text editor and see if you can see obvious corruption.

See, for example, https://github.com/electron/brightray_example/issues/19.

So I think you will just need to reinstall the latest-and-greatest Xcode, and report back.   Thanks!
