### ISSUE TITLE
eth --import hangs unlimited time when blocks are unknown

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#3307]
with this condition eth would hang unlimited time if imported blocks are unknown
https://github.com/ethereum/cpp-ethereum/blob/develop/eth/main.cpp#L1133

**Comment by gumb0** [comment]
This should be fixed with https://github.com/ethereum/cpp-ethereum/pull/3585,  please verify

**Comment by winsvega** [comment]
Martin confirmed that this works 
https://github.com/ethereum/cpp-ethereum/pull/3585
