### ISSUE TITLE
ethminer showing 0 h/s

### ISSUE THREAD

**Issue by daniel-lucio** [ethereum/cpp-ethereum#3309]
I have 2 computers (old ones, more or less). Both are celeron.  When running ethminer -M -C i got 0 as a result. Is something wrong? or is there a hidden requirement.

I have other newer, more powerful machines that are doing CPU hashing without issues.

**Comment by bobsummerwill** [comment]
Hey @daniel-lucio,
Head to https://gitter.im/ethereum/minercommunitysupport for help with mining.
See also https://github.com/ethereum/cpp-ethereum/issues/3211 and https://github.com/ethereum/cpp-ethereum/issues/3124 and https://github.com/ethereum/cpp-ethereum/issues/3125.

The official ethminer is not what you want to be using right now :-(
