### ISSUE TITLE
Unit tests are broken at HEAD

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3311]
See https://travis-ci.org/ethereum/cpp-ethereum/builds/159850071.

Looks like they got broken at https://github.com/ethereum/cpp-ethereum/pull/3306.

CC @chfast.   All PRs after that have shown as broken in TravisCI too.

**Comment by chfast** [comment]
Exactly. There is a bug in the EVMJIT that is going to be fixed by https://github.com/ethereum/evmjit/pull/100.

I would mark the test as XFail but we don't have such feature.

**Comment by chfast** [comment]
Fixed in #3317.
