### ISSUE TITLE
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

### ISSUE THREAD

**Issue by aviadoffer** [ethereum/cpp-ethereum#3315]
C:\Program Files\cpp-ethereum>ethminer.exe --list-devices

Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1060 3GB
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 3221225472
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 805306368
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

C:\Program Files\cpp-ethereum>ethminer.exe -G
No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

latest NVIDIA drivers install. 
What am I missing?

**Comment by bobsummerwill** [comment]
Please use the ethminer from http://github.com/Genoil/cpp-ethereum.

The official ethminer is essentially unmaintained.   Thanks!
