### ISSUE TITLE
Redesign VM output management

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3318]
I would like to propose change in the VM-related API. Now the user have to provide the output buffer where the VM will copy the output (it comes from current CALL semantics).
I want to change that to return the output buffer reference with attached virtual destructor to the user. The user is responsible to copy whatever it wants and release the buffer.

This should be aligned with:
1. The way how CREATE works.
2. https://github.com/ethereum/EIPs/issues/8.
3. Changes planned in EVM-C: aligning external and internal calls.

**Comment by chfast** [comment]
@chriseth @gcolvin can you review this? Details will come with a PR.

**Comment by gcolvin** [comment]
Can't get to Github for some reason.  Will review tomorrow or
      Saturday.  Thanks.
    
    
    On 9/28/16 7:36 PM, Paweł Bylica wrote:
    
    
      @chriseth @gcolvin
        can you review this? Details will come with a PR.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ethereum/cpp-ethereum","title":"ethereum/cpp-ethereum","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ethereum/cpp-ethereum"}},"updates":{"snippets":[{"icon":"PERSON","message":"@chfast in #3318: @chriseth @gcolvin can you review this? Details will come with a PR."}],"action":{"name":"View Issue","url":"https://github.com/ethereum/cpp-ethereum/issues/3318#issuecomment-250142623"}}}

**Comment by chriseth** [comment]
Sounds good! The question would be: How much will be retained? The full memory of the callee or will the return part be copied somewhere else in between? I think it should be quite safe to retain the full memory because it will be deleted in the next step.

**Comment by chfast** [comment]
Exactly. You return full memory and the reference to the output buffer
within this memory. The user frees the memory as soon as it does not need
the output any more.
