### ISSUE TITLE
We need transaction spam tests

### ISSUE THREAD

**Issue by bobsummerwill** [ethereum/cpp-ethereum#3324]
Replicating the transaction spam issues is time-consuming and difficult, but we MUST address these issues in cpp-ethereum as a priority now that we know that the C++ client seemingly chokes on them too (see https://github.com/ethereum/cpp-ethereum/issues/3322).

@winsvega Please can you gather information from Skype, gitter and individuals who were involved in the go-ethereum fixes so that we can construct a representative set of tests to replicate the various attack vectors, and replicate them efficiently?     If it is possible to do that in a cross-client way that would be awesome.   If not, and they end up being cpp-ethereum specific, that is OK too.

This and #3322 (fixing the issues) need to be our highest priority for cpp-ethereum.

**Comment by chriseth** [comment]
Is this fixed?

**Comment by winsvega** [comment]
here are the tests I created during the  devcon attack 
https://github.com/ethereum/cpp-ethereum/pull/3326

**Comment by chfast** [comment]
Does this need more work?

**Comment by chriseth** [comment]
ping @winsvega @holiman

**Comment by winsvega** [comment]
initially this issue was about devcon spam transactions.
for this we have suicide issue and revert tests 
as well as stAttackTest

**Comment by winsvega** [comment]
could be closed
