### ISSUE TITLE
Bus error on ethminer

### ISSUE THREAD

**Issue by programonauta** [ethereum/cpp-ethereum#3328]
Hi,

Running ethminer, when reach 33% I got a `bus error`.

Looking for other similar issues, I found out some tips about lack of memory to run it. I'm running on a Debian with 4GB RAM, in a VPS. 

So, before ask for more memory, I'd like to know if I could try other things.

Thanks

**Comment by bobsummerwill** [comment]
Hey @programonauta,
The official `ethminer` is effectively unsupported.
Please give http://github.com/Genoil/cpp-ethereum a try.
And you can use https://gitter.im/ethereum/minercommunitysupport for support.

Good luck!

**Comment by programonauta** [comment]
Thank you @bobsummerwill
