### ISSUE TITLE
Too much verifiers

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3337]
Suspicious logs when downloading new blocks in eth. Why it has so much verifiers?

```
  ✘  16:22:48.925|verifier4  BlockQueue missing our job: was there a GM?
  ✘  16:22:48.926|verifier3  BlockQueue missing our job: was there a GM?
  ✘  16:22:48.926|verifier0  BlockQueue missing our job: was there a GM?
  ✘  16:22:48.926|verifier1  BlockQueue missing our job: was there a GM?
  ✘  16:22:48.927|verifier5  BlockQueue missing our job: was there a GM?
  ✘  16:22:48.928|verifier2  BlockQueue missing our job: was there a GM?
```

**Comment by chriseth** [comment]
I think there are as many verifiers as there are CPU cores.

**Comment by chriseth** [comment]
@chfast how many are too many for you?

**Comment by chfast** [comment]
Aren't they are for mining? But if I'm not mining, why all 8 are processing all blocks?

**Comment by chriseth** [comment]
No, they are verifying incoming blocks. It is especially useful to have many while syncing the blockchain. If you are up to date, it does not hurt to have lingering threads unless we can show that they take up too many resources.

**Comment by chfast** [comment]
Thanks for explaining that to me.
