### ISSUE TITLE
Implement EIP 150

### ISSUE THREAD

**Issue by chriseth** [ethereum/cpp-ethereum#3343]
Implement EIP 150: https://github.com/ethereum/EIPs/issues/150

**Comment by daniel-lucio** [comment]
Could you tag a release when this is done?

**Comment by chriseth** [comment]
@daniel-lucio it does not make a lot of sense to release this without a fix to the DoS issues which we are still working on. If cpp-ethereum is able to sync to HEAD again, we will make a release.

**Comment by daniel-lucio** [comment]
other silly question,   let's say i got parity or geth after this incoming fork. is ethminer still capable of working?

**Comment by chriseth** [comment]
Yes, ethminer is fully independent and should work with any client. Furthermore, ethminer is mostly maintained by the community now, for example in genoil's miner: https://github.com/Genoil/cpp-ethereum
