### ISSUE TITLE
compilation problem on centos 7

### ISSUE THREAD

**Issue by krsvital** [ethereum/cpp-ethereum#3346]
cmake3 ..

---
## -- Configuring cpp-ethereum

--                  CMake Version                            3.6.1
-- CMAKE_BUILD_TYPE Build type                               RelWithDebInfo
-- TARGET_PLATFORM  Target platform                          Linux
--------------------------------------------------------------- features
--                  Hardware identification support
--                  HTTP Request support
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  ON
-- ROCKSDB          Prefer rocksdb to leveldb                OFF
-- PARANOID         -                                        OFF
-- MINIUPNPC        -                                        ON
------------------------------------------------------------- components
-- TESTS            Build tests                              ON
-- ETHASHCL         Build OpenCL components                  ON
## -- EVMJIT           Build LLVM-based JIT EVM                 OFF

-- JsonCpp headers: /usr/include/jsoncpp
-- JsonCpp lib   : /usr/lib64/libjsoncpp.so
-- json-rpc-cpp headers: /usr/local/include
-- json-rpc-cpp lib   : /usr/local/lib/libjsonrpccpp-common.so;/usr/local/lib/libjsonrpccpp-server.so;/usr/local/lib/libjsonrpccpp-client.so
-- curl headers: /usr/include
-- curl lib   : /usr/lib64/libcurl.so
-- CryptoPP headers: /usr/include
-- CryptoPP lib   : /usr/lib64/libcryptopp.so
-- Cpuid headers: /usr/local/include
-- Cpuid lib   : /usr/local/lib/libcpuid.so
-- Found OpenCL: /usr/lib64/libOpenCL.so (found version "1.2")
-- OpenCL headers: /usr/include
-- OpenCL lib   : /usr/lib64/libOpenCL.so
-- Found miniupnpc: /usr/lib64/libminiupnpc.so
-- miniupnpc headers: /usr/include
-- miniupnpc lib   : /usr/lib64/libminiupnpc.so
-- Found mhd: /usr/lib64/libmicrohttpd.so
-- microhttpd headers: /usr/include
-- microhttpd lib   : /usr/lib64/libmicrohttpd.so
-- jsonrpcstub location    : /usr/local/bin/jsonrpcstub
-- test: ClientBase |  --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=10
-- test: JsonRpc |  --eth_testfile=BlockTests/bcJS_API_Test; --eth_testfile=BlockTests/bcValidBlockTest
-- Found gmp: /usr/lib64/libgmp.so
-- Gmp headers: /usr/include
-- Gmp lib   : /usr/lib64/libgmp.so
-- Configuring done
-- Generating done
-- Build files have been written to: /var/db/pack/cpp-ethereum/build
[root@stream-1 build]# make
Scanning dependencies of target cpp-ethereum_BuildInfo.h
[  0%] Built target cpp-ethereum_BuildInfo.h
Scanning dependencies of target secp256k1
[  0%] Building C object utils/secp256k1/CMakeFiles/secp256k1.dir/secp256k1.c.o
[  1%] Linking C static library libsecp256k1.a
[  1%] Built target secp256k1
Scanning dependencies of target devcore
[  1%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Base58.cpp.o
[  2%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Base64.cpp.o
[  2%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Common.cpp.o
[  2%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonData.cpp.o
[  3%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonIO.cpp.o
[  3%] Building CXX object libdevcore/CMakeFiles/devcore.dir/CommonJS.cpp.o
[  4%] Building CXX object libdevcore/CMakeFiles/devcore.dir/FileSystem.cpp.o
[  4%] Building CXX object libdevcore/CMakeFiles/devcore.dir/FixedHash.cpp.o
[  5%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Guards.cpp.o
[  5%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Hash.cpp.o
[  5%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Log.cpp.o
[  6%] Building CXX object libdevcore/CMakeFiles/devcore.dir/MemoryDB.cpp.o
[  6%] Building CXX object libdevcore/CMakeFiles/devcore.dir/OverlayDB.cpp.o
[  7%] Building CXX object libdevcore/CMakeFiles/devcore.dir/RLP.cpp.o
[  7%] Building CXX object libdevcore/CMakeFiles/devcore.dir/RangeMask.cpp.o
[  7%] Building CXX object libdevcore/CMakeFiles/devcore.dir/SHA3.cpp.o
[  8%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TransientDirectory.cpp.o
[  8%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieCommon.cpp.o
[  9%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieDB.cpp.o
[  9%] Building CXX object libdevcore/CMakeFiles/devcore.dir/TrieHash.cpp.o
[ 10%] Building CXX object libdevcore/CMakeFiles/devcore.dir/Worker.cpp.o
[ 10%] Linking CXX shared library libdevcore.so
[ 10%] Built target devcore
Scanning dependencies of target scrypt
[ 10%] Building C object utils/libscrypt/CMakeFiles/scrypt.dir/b64.c.o
[ 11%] Building C object utils/libscrypt/CMakeFiles/scrypt.dir/crypto-mcf.c.o
[ 11%] Building C object utils/libscrypt/CMakeFiles/scrypt.dir/crypto-scrypt-saltgen.c.o
[ 11%] Building C object utils/libscrypt/CMakeFiles/scrypt.dir/crypto_scrypt-check.c.o
[ 12%] Building C object utils/libscrypt/CMakeFiles/scrypt.dir/crypto_scrypt-hash.c.o
[ 12%] Building C object utils/libscrypt/CMakeFiles/scrypt.dir/crypto_scrypt-hexconvert.c.o
[ 13%] Building C object utils/libscrypt/CMakeFiles/scrypt.dir/crypto_scrypt-nosse.c.o
[ 13%] Building C object utils/libscrypt/CMakeFiles/scrypt.dir/sha256.c.o
[ 13%] Building C object utils/libscrypt/CMakeFiles/scrypt.dir/slowequals.c.o
[ 14%] Linking C shared library libscrypt.so
[ 14%] Built target scrypt
Scanning dependencies of target devcrypto
[ 14%] Building CXX object libdevcrypto/CMakeFiles/devcrypto.dir/AES.cpp.o
[ 15%] Building CXX object libdevcrypto/CMakeFiles/devcrypto.dir/Common.cpp.o
[ 15%] Building CXX object libdevcrypto/CMakeFiles/devcrypto.dir/CryptoPP.cpp.o
[ 16%] Building CXX object libdevcrypto/CMakeFiles/devcrypto.dir/ECDHE.cpp.o
[ 16%] Building CXX object libdevcrypto/CMakeFiles/devcrypto.dir/SecretStore.cpp.o
[ 17%] Building CXX object libdevcrypto/CMakeFiles/devcrypto.dir/WordList.cpp.o
[ 17%] Linking CXX shared library libdevcrypto.so
[ 17%] Built target devcrypto
Scanning dependencies of target ethash
[ 18%] Building C object libethash/CMakeFiles/ethash.dir/io.c.o
[ 18%] Building C object libethash/CMakeFiles/ethash.dir/internal.c.o
[ 18%] Building C object libethash/CMakeFiles/ethash.dir/io_posix.c.o
[ 19%] Building C object libethash/CMakeFiles/ethash.dir/sha3.c.o
[ 19%] Linking C shared library libethash.so
[ 19%] Built target ethash
Scanning dependencies of target ethcore
[ 19%] Building CXX object libethcore/CMakeFiles/ethcore.dir/ABI.cpp.o
[ 20%] Building CXX object libethcore/CMakeFiles/ethcore.dir/BasicAuthority.cpp.o
[ 20%] Building CXX object libethcore/CMakeFiles/ethcore.dir/BlockHeader.cpp.o
[ 21%] Building CXX object libethcore/CMakeFiles/ethcore.dir/ChainOperationParams.cpp.o
[ 21%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Common.cpp.o
[ 21%] Building CXX object libethcore/CMakeFiles/ethcore.dir/CommonJS.cpp.o
[ 22%] Building CXX object libethcore/CMakeFiles/ethcore.dir/ICAP.cpp.o
[ 22%] Building CXX object libethcore/CMakeFiles/ethcore.dir/KeyManager.cpp.o
[ 23%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Precompiled.cpp.o
[ 23%] Building CXX object libethcore/CMakeFiles/ethcore.dir/SealEngine.cpp.o
[ 24%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Transaction.cpp.o
[ 24%] Linking CXX shared library libethcore.so
[ 24%] Built target ethcore
Scanning dependencies of target evmcore
[ 24%] Building CXX object libevmcore/CMakeFiles/evmcore.dir/EVMSchedule.cpp.o
[ 25%] Building CXX object libevmcore/CMakeFiles/evmcore.dir/Instruction.cpp.o
[ 25%] Linking CXX shared library libevmcore.so
[ 25%] Built target evmcore
Scanning dependencies of target evm
[ 25%] Building CXX object libevm/CMakeFiles/evm.dir/ExtVMFace.cpp.o
[ 25%] Building CXX object libevm/CMakeFiles/evm.dir/VM.cpp.o
[ 26%] Building CXX object libevm/CMakeFiles/evm.dir/VMOpt.cpp.o
[ 26%] Building CXX object libevm/CMakeFiles/evm.dir/VMCalls.cpp.o
[ 27%] Building CXX object libevm/CMakeFiles/evm.dir/VMFactory.cpp.o
[ 27%] Linking CXX shared library libevm.so
[ 27%] Built target evm
Scanning dependencies of target p2p
[ 28%] Building CXX object libp2p/CMakeFiles/p2p.dir/Capability.cpp.o
[ 28%] Building CXX object libp2p/CMakeFiles/p2p.dir/Common.cpp.o
[ 29%] Building CXX object libp2p/CMakeFiles/p2p.dir/Host.cpp.o
[ 29%] Building CXX object libp2p/CMakeFiles/p2p.dir/HostCapability.cpp.o
[ 29%] Building CXX object libp2p/CMakeFiles/p2p.dir/Network.cpp.o
[ 30%] Building CXX object libp2p/CMakeFiles/p2p.dir/NodeTable.cpp.o
[ 30%] Building CXX object libp2p/CMakeFiles/p2p.dir/Peer.cpp.o
[ 31%] Building CXX object libp2p/CMakeFiles/p2p.dir/RLPXFrameCoder.cpp.o
[ 31%] Building CXX object libp2p/CMakeFiles/p2p.dir/RLPXFrameReader.cpp.o
[ 32%] Building CXX object libp2p/CMakeFiles/p2p.dir/RLPXFrameWriter.cpp.o
[ 32%] Building CXX object libp2p/CMakeFiles/p2p.dir/RLPXPacket.cpp.o
[ 32%] Building CXX object libp2p/CMakeFiles/p2p.dir/RLPXSocket.cpp.o
[ 33%] Building CXX object libp2p/CMakeFiles/p2p.dir/RLPXSocketIO.cpp.o
[ 33%] Building CXX object libp2p/CMakeFiles/p2p.dir/RLPxHandshake.cpp.o
[ 34%] Building CXX object libp2p/CMakeFiles/p2p.dir/Session.cpp.o
[ 34%] Building CXX object libp2p/CMakeFiles/p2p.dir/UDP.cpp.o
[ 34%] Building CXX object libp2p/CMakeFiles/p2p.dir/UPnP.cpp.o
[ 35%] Linking CXX shared library libp2p.so
[ 35%] Built target p2p
Scanning dependencies of target ethereum
[ 35%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Account.cpp.o
[ 36%] Building CXX object libethereum/CMakeFiles/ethereum.dir/AccountDiff.cpp.o
[ 36%] Building CXX object libethereum/CMakeFiles/ethereum.dir/BasicGasPricer.cpp.o
[ 37%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Block.cpp.o
[ 37%] Building CXX object libethereum/CMakeFiles/ethereum.dir/BlockChain.cpp.o
[ 37%] Building CXX object libethereum/CMakeFiles/ethereum.dir/BlockChainSync.cpp.o
[ 38%] Building CXX object libethereum/CMakeFiles/ethereum.dir/BlockDetails.cpp.o
[ 38%] Building CXX object libethereum/CMakeFiles/ethereum.dir/BlockQueue.cpp.o
[ 39%] Building CXX object libethereum/CMakeFiles/ethereum.dir/CachedAddressState.cpp.o
[ 39%] Building CXX object libethereum/CMakeFiles/ethereum.dir/ChainParams.cpp.o
[ 40%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Client.cpp.o
[ 40%] Building CXX object libethereum/CMakeFiles/ethereum.dir/ClientBase.cpp.o
[ 40%] Building CXX object libethereum/CMakeFiles/ethereum.dir/ClientTest.cpp.o
[ 41%] Building CXX object libethereum/CMakeFiles/ethereum.dir/CommonNet.cpp.o
[ 41%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Defaults.cpp.o
[ 42%] Building CXX object libethereum/CMakeFiles/ethereum.dir/EthereumHost.cpp.o
[ 42%] Building CXX object libethereum/CMakeFiles/ethereum.dir/EthereumPeer.cpp.o
[ 43%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Executive.cpp.o
[ 43%] Building CXX object libethereum/CMakeFiles/ethereum.dir/ExtVM.cpp.o
[ 43%] Building CXX object libethereum/CMakeFiles/ethereum.dir/GasPricer.cpp.o
[ 44%] Building CXX object libethereum/CMakeFiles/ethereum.dir/GenericMiner.cpp.o
[ 44%] Building CXX object libethereum/CMakeFiles/ethereum.dir/GenesisInfo.cpp.o
[ 45%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Interface.cpp.o
[ 45%] Building CXX object libethereum/CMakeFiles/ethereum.dir/LogFilter.cpp.o
[ 45%] Building CXX object libethereum/CMakeFiles/ethereum.dir/MiningClient.cpp.o
[ 46%] Building CXX object libethereum/CMakeFiles/ethereum.dir/State.cpp.o
[ 46%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Transaction.cpp.o
[ 47%] Building CXX object libethereum/CMakeFiles/ethereum.dir/TransactionQueue.cpp.o
[ 47%] Building CXX object libethereum/CMakeFiles/ethereum.dir/TransactionReceipt.cpp.o
[ 48%] Building CXX object libethereum/CMakeFiles/ethereum.dir/Utility.cpp.o
[ 48%] Linking CXX shared library libethereum.so
[ 48%] Built target ethereum
[ 49%] Generating OpenCL Kernel Byte Array
Scanning dependencies of target ethash-cl
[ 49%] Building CXX object libethash-cl/CMakeFiles/ethash-cl.dir/ethash_cl_miner.cpp.o
[ 50%] Linking CXX shared library libethash-cl.so
[ 50%] Built target ethash-cl
Scanning dependencies of target ethashseal
[ 50%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/Ethash.cpp.o
[ 50%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashAux.cpp.o
[ 51%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashCPUMiner.cpp.o
[ 51%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashClient.cpp.o
[ 52%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashGPUMiner.cpp.o
[ 52%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/EthashProofOfWork.cpp.o
[ 53%] Building CXX object libethashseal/CMakeFiles/ethashseal.dir/GenesisInfo.cpp.o
[ 53%] Linking CXX shared library libethashseal.so
[ 53%] Built target ethashseal
Scanning dependencies of target personal.jsonstub
CMake Error at /var/db/pack/cpp-ethereum/cmake/scripts/jsonrpcstub.cmake:56 (file):
  file failed to open for reading (No such file or directory):

```
/var/db/pack/cpp-ethereum/libweb3jsonrpc/PersonalFace.h.tmp
```

make[2]: **\* [personal.jsonstub] Ошибка 1
make[1]: **\* [libweb3jsonrpc/CMakeFiles/personal.jsonstub.dir/all] Ошибка 2
make: **\* [all] Ошибка 2

 uname -a
Linux stream-1 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bobsummerwill** [comment]
Thanks for the report.

Was this using `scripts/install_deps.sh`?   What version of `libjsonrpccpp` do you have?

**Comment by krsvital** [comment]
im using scripts/install_deps.sh, but its modified because no redhat version in

...

        if [ -f "/etc/redhat-release" ]; then

            echo "Installing cpp-ethereum dependencies on RedHat Linux."

            # The majority of our dependencies can be found in the
            # Arch Linux official repositories.
            # See https://wiki.archlinux.org/index.php/Official_repositories
            yum install -y \
                autoconf \
                automake \
                libtool \
                cmake \
                leveldb-devel \
                libcl \
                opencl-headers \
                cryptopp-devel \
                curl-devel \
                gmp-devel \
                leveldb-devel \
                mesa-dri-drivers \
                miniupnpc-devel \
                snappy-devel \
                jsoncpp-devel \
                libargtable2-devel \
                libedit-devel \
                argtable-devel \
                libmicrohttpd-devel \
                cpuid

                # Build libjsonrpccpp-v0.6.0 from source.
                # Rationale for this is given in the Ubuntu comments lower down this file.

                if ! [ -d "libjson-rpc-cpp" ]; then
                    git clone git://github.com/cinemast/libjson-rpc-cpp.git
                fi
                cd libjson-rpc-cpp
                git checkout v0.6.0
                if ! [ -d "build" ]; then
                    mkdir build
                fi
                cd build
                cmake .. -DCOMPILE_TESTS=NO
                make
                sudo make install
                sudo ldconfig
                cd ../..

            exit 0;
        fi
...

**Comment by daniel-lucio** [comment]
Use my RPM 
http://inside-out.xyz/technology/cpp-ethereum-rpm-for-centos-7.html

**Comment by chfast** [comment]
Support for CentOS in `install_deps.sh` has been added.
