### ISSUE TITLE
Drop support for builds without JSON RPC

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3350]
Assigned to: @lymanZerga11 

With the flag `-DJSONRPC=Off` you can configure the build without JSON RPC. But we never test them. At the moment the are not even buildable. I would like to remove all `#if ETH_JSONRPC` checks.

- [x] Remove `-DJSONRPC` CMake option. See EthOptions.cmake file.
- [x] Do not set `-DETH_JSONRPC` compilation flag.
- [x] Remove all `#if ETH_JSONRPC` preprocessor conditionals assuming it is always enabled.

**Comment by axic** [comment]
Probably that was a remnant from Solidity times?

**Comment by yann300** [comment]
yeah it makes sense to remove this.

**Comment by chriseth** [comment]
To anyone (also outside the organisation): Please feel free to work on this. This is about removing the ifdefs and configuration options related to `JSONRPC` to make it active for all builds and non-configurable.

**Comment by lucypher95** [comment]
I want to work on this project

**Comment by chfast** [comment]
Welcome @lucypher95.
Do you mean this particular issue, or cpp-ethereum in general?

This particular one is quite straightforward -- see updated description.

**Comment by lucypher95** [comment]
in general

**Comment by lucypher95** [comment]
how to start?

**Comment by chfast** [comment]
Come to the developers' chat: https://gitter.im/ethereum/cpp-ethereum-development

**Comment by lucypher95** [comment]
okay i dont wanna work on it

**Comment by lymanZerga11** [comment]
I'd like to grab this one, if I may. Seems pretty trivial.

**Comment by chfast** [comment]
Yes, please.

**Comment by chfast** [comment]
Thank you @lymanZerga11
