### ISSUE TITLE
Gas used error

### ISSUE THREAD

**Issue by jtremblaytdst** [ethereum/cpp-ethereum#3352]
Hi,

With Mist or Geth i can't sync the blockchain... I get this error. My friend get it too. I build it with the git source today to be sure i get the last version (2016-10-16).

What i can do ?

E1016 18:41:06.985089 core/blockchain.go:1170] Bad block #2452083 (0xb96ad7e2f578008ad62df82dd433ab0706e4f4d79f696c6797a90902a9843d88)
E1016 18:41:06.985144 core/blockchain.go:1171]     gas used error (491820 / 491260)

**Comment by bobsummerwill** [comment]
Please log an issue against https://github.com/ethereum/go-ethereum/issues.   Thanks!
