### ISSUE TITLE
Replace LLL code in tests with EVM bytecode

### ISSUE THREAD

**Issue by axic** [ethereum/cpp-ethereum#3356]
For example: https://github.com/ethereum/cpp-ethereum/blob/develop/test/libevm/VMTestsFiller/vmIOandFlowOperationsTestFiller.json#L148

There are at least 3 code types being used there:
- EVM bytecode: `"code" : "0x60046000540156655b6001600155",`
- LLL with assembly only: `"code" : "(asm PUSH1 0x03 JUMPDEST PUSH1 0x01 SAWP1 SUB DUP1 PUSH1 0x02 JUMPI PUSH9 0x010000000000000016 JUMP JUMPDEST PUSH4 0xbadf000d PUSH1 0x11 SSTORE STOP )",`
- pure LLL: `"code" : "{(MSTORE 0 0xffffffffff)  (MSTORE 32 0xeeee) [[ 0 ]] (MSIZE)}",`

It would be nice either replacing it with EVM bytecode or EVM opcodes, so the tests could be used outside cpp-ethereum without having LLL as a dependency.

Additionally this relieves the stress from LLL's future development and backwards compatibility.

Lastly, tests using LLL cannot be run on Windows, because the commandline `lllc` is used: https://github.com/ethereum/cpp-ethereum/blob/develop/test/TestHelper.cpp#L551

**Comment by chriseth** [comment]
I think it is very useful to have readable test code. Most of the tests we currently have are just "fire and forget" tests where we do not really know what they do, and replacing the code by mere opcodes will just solidify that.
At the same time, I agree that LLL as a test dependency is not nice. We might provide a more lightweight component, for example the solidity inline assembler, but I'm not sure how many more advanced features of LLL (like loops) are used in the tests.

**Comment by axic** [comment]
> I think it is very useful to have readable test code.

It doesn't need to be mutually exclusive. I suggest to have two fields: `codeSource` and `code` (or `code` and `bytecode`), where the bytecode is used during tests.

> We might provide a more lightweight component, for example the solidity inline assembler

I would definitely vote for some kind of assembler source code, which is supported widely in the ecosystem.

**Comment by axic** [comment]
Could be replaced with Solidity inline assembly or just Solidity assembly.

**Comment by axic** [comment]
Tracked here: https://github.com/ethereum/tests/issues/306
