### ISSUE TITLE
Cannot start eth when not having any account

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3374]
eth tries to generate an account during the start if there is none. But fails to ask for password. I think it is leftover of master password elimination.

**Comment by axic** [comment]
Can the generation of an account be removed? It shouldn't require one.

**Comment by chriseth** [comment]
Is this still an issue?

**Comment by chfast** [comment]
I think it is. The quick fix is to disable generation of an account in eth/main.cpp, but I don't know if that brakes assumptions in other parts of the code. I suggest disabling that and do basic tests.

**Comment by gumb0** [comment]
Should be fixed in #3446
