### ISSUE TITLE
Optimization: Cache information about non-existing accounts

### ISSUE THREAD

**Issue by chriseth** [ethereum/cpp-ethereum#3376]
The cache inside state should store information about non-existing accounts. Currently, it only stores information about existing accounts, so access to a non-existing acocunt always has to go to the database.

**Comment by chfast** [comment]
I would assign -1 for not-existing accounts.

**Comment by chriseth** [comment]
Not sure about the type information there. But perhaps we can still combine that with the missing protection against attacks when clearing m_cache, i.e. extend `m_unchangedCacheEntries` by a data structure that maps from address to 
 - this is a non-existing account
 - this is an account that was not modified
and allow this datastructure to be purged more efficiently.
