### ISSUE TITLE
Some ethash Pow questions, help me!

### ISSUE THREAD

**Issue by jiraiyav5** [ethereum/cpp-ethereum#3380]
I download the sourcecode and do some test about PoW algorithm ethash. 
     But I has not understand how the seed was computed .And In order  to compute the seed ,what kind of parameters should be porovided by the block or the blockheader? 
     Pelease help me understand the probelm , much thanks!

**Comment by chriseth** [comment]
This seems to be a question well suited for https://ethereum.stackexchange.com/ could you please ask there?
