### ISSUE TITLE
RedHat (RHEL) support

### ISSUE THREAD

**Issue by javapark1** [ethereum/cpp-ethereum#3386]
I'm in need of running EthereumJ on RHEL. It fails due to a GLIBC version problem. It's looking for 2.14 but  RHEL has 2.12 and there seems to be no binary support for 2.14 from RedHat. I've tried to build 2.14 myself but I'm having trouble with installing it as it complaints that it's unable to find etc/ld.so.conf. It does compile but installation fails. 

I've also tried to compile cpp-ethereum against GLIBC 2.12 but install_deps.sh fails with the message "ERROR - Unsupported or unidentified Linux distro". I see that RHEL is not even in your road map. Can you provide some insight to why RHEL is not supported and what could I do to make it work?

Thanks in advance,
Dae Song Park

**Comment by daniel-lucio** [comment]
Dear Dae,

I have already done the RPMs for Centos7, they are compatible with RHEL.
http://inside-out.xyz/technology/cpp-ethereum-rpm-for-centos-7.html

**Comment by chriseth** [comment]
You could also use docker: http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/docker.html

**Comment by chriseth** [comment]
You could also use docker: http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/docker.html

**Comment by chriseth** [comment]
You could also use docker: http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/docker.html

**Comment by chriseth** [comment]
You could also use docker: http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/docker.html

**Comment by chriseth** [comment]
You could also use docker: http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/docker.html

**Comment by chriseth** [comment]
You could also use docker: http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/docker.html
