### ISSUE TITLE
Link error: _fatDeviceText: error: undefined reference to 'fatbinData'

### ISSUE THREAD

**Issue by Nisse43** [ethereum/cpp-ethereum#3394]
I am trying to build on arch linux the latest dev branch and everything goes fine but during linking i get the error above

cmake -DBUNDLE=cudaminer -D CUDA_NVCC_FLAGS="-ccbin gcc-5" -D CMAKE_C_COMPILER="/usr/bin/gcc-5" -D CMAKE_CXX_COMPILER="/usr/bin/gcc-5" ..
make -j8

What could be the issue here? I have cuda 8.0.44-2

**Comment by chriseth** [comment]
Sorry, we do not support the GPU mining part anymore. Please use genoil's miner: https://github.com/Genoil/cpp-ethereum
