### ISSUE TITLE
RedHat (RHEL) support #3386 follow up

### ISSUE THREAD

**Issue by javapark1** [ethereum/cpp-ethereum#3398]
Thanks for your reponses @daniel-lucio and @chriseth on Issue #3386. Unfortunately, I'm on a corporate network with the following constraints:

- We are running RHEL 6 (2.6.32-279.39.1.el6.x86_64) - Docker runs on RHEL 7 with 3.10 or higher. Also, Docker cannot be our solution as we are already running on VMs.

- Similarly, RPMS for CentOS 7 won't work for us. Also, we prefer a tar ball for installation.

As I indicated in [Issue #3386](https://github.com/ethereum/cpp-ethereum/issues/3386), it seems GLIBC 2.14 is the culprit. RHEL 6 has GLIBC 2.12 with no support for 2.14.

Do you have any plan to support RHEL 6? If not, how about out-of-the box support for RHEL 7? 

I'm currently evaluating a number of blockchain implementations and Ethereum is in the top of the list. Any insight/help would be greatly appreciated.

**Comment by chriseth** [comment]
Sorry, but we currently don't have the capacity to support many different platforms. The fact that RHEL is missing from install_deps does not mean that it will not work. I think if we do not support the more than 6 years old glibc 2.12 (is that correct?), then there is a reason for that. If you succeed to install the compilation time requirements, we would be very glad to add them to the install_deps.sh file.

**Comment by javapark1** [comment]
Understood. A bit surprised to hear that RHEL is not supported given its popularity. Thanks.
