### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ccminer-net** [ethereum/cpp-ethereum#3412]
Hi I'm on UBUNTU 16.10 
I would like to install ethminer via cpp

I got this error when I run cmake ..

`
(missing:  MHD_LIBRARY MHD_INCLUDE_DIR)
` 

what should I do?

**Comment by chriseth** [comment]
Sorry, we do not support ethminer anymore. Please use the genoil mining software: https://github.com/Genoil/cpp-ethereum

**Comment by spidero** [comment]
apt install libmicrohttpd-dev
