### ISSUE TITLE
cpp-ethereum for debian

### ISSUE THREAD

**Issue by thehumans35** [ethereum/cpp-ethereum#3435]
Hi,
after following the instruction on http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/linux.html

git clone --recursive https://github.com/ethereum/cpp-ethereum.git
cd cpp-ethereum
./scripts/install_deps.sh

I got on bash: 
W: Fehlschlag beim Holen von http://ppa.launchpad.net/ethereum/ethereum-dev/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found
W: Fehlschlag beim Holen von http://ppa.launchpad.net/ethereum/ethereum-dev/ubuntu/dists/jessie/main/binary-i386/Packages  404  Not Found
W: Fehlschlag beim Holen von http://ppa.launchpad.net/ethereum/ethereum/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found
W: Fehlschlag beim Holen von http://ppa.launchpad.net/ethereum/ethereum/ubuntu/dists/jessie/main/binary-i386/Packages  404  Not Found

Looking for ubuntu folder, but I am running debian on my notebook?
Any instructions?
Thank you.

E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

**Comment by chriseth** [comment]
Sorry, we barely support ubuntu now. You could try to use the docker image, that should work best.

**Comment by thehumans35** [comment]
Dear Chriseth,

thank you for your message, could you please send me a link for docker image.


Best regards,

Hakan

________________________________
Von: chriseth <notifications@github.com>
Gesendet: Freitag, 2. Dezember 2016 10:28:46
An: ethereum/cpp-ethereum
Cc: thehumans35; Author
Betreff: Re: [ethereum/cpp-ethereum] cpp-ethereum for debian (#3435)


Sorry, we barely support ubuntu now. You could try to use the docker image, that should work best.

-

**Comment by chriseth** [comment]
Here are the instructions: http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/docker.html
It seems they do not reflect the latest changes, you need to replace "cpp-client" by "client-cpp".

**Comment by krzyszp** [comment]
This is strange, that you support Ubuntu only, as this distribution quite often has inconsistency in packages with other distros... Also, Debian is more widely used on servers then Ubuntu really...

**Comment by chfast** [comment]
I will try to fix Debian, but what version should I target? Can I relay on backports?
