### ISSUE TITLE
install_deps.sh failing on macOS 10.12 Sierra

### ISSUE THREAD

**Issue by serj-by** [ethereum/cpp-ethereum#3440]
Error: Permission denied - /Users/xxx/Library/Logs/Homebrew/cryptopp
if running under user. In the case you are running using sudo, brew -v failed since brew son't like to work using root priveledges so install_deps.sh failing to make a check if brew is installed and exits with:
ERROR - cpp-ethereum requires a Homebrew install.  See http://brew.sh.
However /Users/xxx/Library/Logs/Homebrew is root owned and not writable for others. Fixing ownership seems like solving the problem.

**Comment by axic** [comment]
If still a problem please reopen.
