### ISSUE TITLE
Incompatible version of CryptoPP from brew when using Eth in a testnet

### ISSUE THREAD

**Issue by clar** [ethereum/cpp-ethereum#3451]
The default version of CryptoPP in brew is 5.6.5 now, it can still pass the cmake build.
Requirment for CryptoPP is too loose,  we should add the 'EXACT' to give a notice. 
https://github.com/ethereum/cpp-ethereum/blob/develop/cmake/UseCryptopp.cmake

If the mac build use CryptoPP5.6.5 and anther ubuntu build use 5.6.2 version, the handshake will fail..

To install an older version, take a look at the answer by 'halfcube'
http://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula

**Comment by chfast** [comment]
CryptoPP from brew is not needed any more as of #3486. Can you confirm?
