### ISSUE TITLE
Windows 7 build error

### ISSUE THREAD

**Issue by bnrmaster** [ethereum/cpp-ethereum#3459]
I met an error：
c:\users\administrator\cpp-ethereum\libweb3jsonrpc\UnixSocketServer.h(28): fatal error C1083: can not open include file: “sys/un.h”: No such file or directory

when trying to build the "web3jsonrpc" project using VS 2015 on Window 7

Can anyone give me some advice？

**Comment by chriseth** [comment]
I just created a pull request that might fix your problem.

**Comment by bnrmaster** [comment]
It works,thx for your answer! @chriseth
