### ISSUE TITLE
scripts/install_deps.sh installs a too new Crypto++ on Mac OS X

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#3468]
The script `scripts/install_deps.sh` uses `brew install cryptopp` to install Crypto++.  This installs Crypto++ 5.6.5 currently, which implements SHA3, not keccak256.  This caused #3465.

**Comment by pirapira** [comment]
This is related to #3451.

**Comment by chfast** [comment]
"Fixed" in https://github.com/ethereum/cpp-ethereum/pull/3486. Please confirm.

**Comment by chfast** [comment]
Also https://github.com/ethereum/cpp-ethereum/pull/3491 might be needed.

**Comment by pirapira** [comment]
I tried to make sure #3465 is gone, but I'm seeing something else:
```
build❯ ./test/testeth -t '*/test_secrets_cpp_vectors/'
[1]    16985 segmentation fault  ./test/testeth -t '*/test_secrets_cpp_vectors/'
```

I'll file an issue tomorrow.

**Comment by pirapira** [comment]
For a segmentation fault #3492, I cannot check if the issue is gone.
