### ISSUE TITLE
curl in scripts/install_deps.sh

### ISSUE THREAD

**Issue by dmartino** [ethereum/cpp-ethereum#3489]
Ubuntu 16.04 Desktop is up to date. after running the script to get dependencies, and running cmake, it complains about no 

curl. sudo apt-get install libcurl4-openssl-dev 
boost
leveldb
cpuiid
OpenCL - export AMDAPPSDKROOT=/path/to/installed AMD sdk
miniupnpc - add that and libminiupnpc-dev

I do have AMD cards, so that is understandable to get the right libs for openCL.
Rest of it is possibly becuase I am using a desktop version of 16.04. 
Maybe this will help someone...

**Comment by chfast** [comment]
We just dropped the OpenCL support in cpp-ethereum. Whould you be so kind and update the install_deps.sh script by removing any OpenCL packages for Ubuntu?

**Comment by dmartino** [comment]
Cool, I looked into it. Seems you made the changes in scripts/install_deps.sh
Is there more you need done? One think I can think of asking is what are the alternatives to OpenCL?
How can I find out rationale for dropping OpenCL? 

Here are my observations:
1. I used ethminer to benchmark my gpu's and it seems to work fine - meaning I got activity on the gpu's when I fired up ethminer -G -M etc. 
2. I believe the AMD APP libraries are installed and were being brought in by OpenCL, but I don't know that for sure. 

Thanks chfast.

**Comment by chfast** [comment]
OpenCL was dropped because we don't have capacities to support it and community driven miners are doing good job...

**Comment by dmartino** [comment]
Cool I will give them a shot. Nice to be able to drop something because others are doing a good job! Where does that point the ongoing efforts? I can have a look at the github.

**Comment by chfast** [comment]
From my point of view, we try to package some pieces into reusable components. There is a lot of EVM optimization and research. And test framework used to create JSON compliance tests.
