### ISSUE TITLE
Crypo++ Crash - Windows 10

### ISSUE THREAD

**Issue by jola0855** [ethereum/cpp-ethereum#3490]
eth.exe immediatly crashes upon launch. Fresh build.
## Replication

Pretty much just follow [steps](http://ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html).

1. `git clone --recursive https://github.com/ethereum/cpp-ethereum.git`
2. `cd cpp-ethereum`
3. `scripts\install_deps.bat`
4. `mkdir build`
5. `cd build`
6. `cmake -G "Visual Studio 14 2015 Win64" ..`
7. Open VS 2015 as admin (to allow INSTALL to work)
8. Open `cpp-ethereum.sln`
9. Set to `RelWithDebInfo`
10. Build solution - Pass
11. Direct run of eth.exe leads to immediate 'stopped responding'.
12. Start new debug instance of eth project via `cpp-ethereum.sln` leads to break. `Exception thrown at 0x00007FF6BD35BD55 in eth.exe: 0xC0000005: Access violation reading location 0x0000000000000010.`
13. Breaks to `...\cpp-ethereum\build\deps\cryptopp\include\cryptopp\integer.h - Line 670`

Error also shows after install.
Error also shows with Release or Debug config.
Immediate crash also shows with build via `cmake --build . --config RelWithDebInfo`
## Environment

- CMake - 3.7.1
- Winows 10 Pro - Version 1607 - OS Build 14393.576
- Visual Studio 2015 Pro - Version 14.0.25431.01 Update 3
- Git - 2.9.2.windows.1
- Added `...\cpp-ethereum\deps\install\x64\bin` and `...\cpp-ethereum\deps\install\win64\bin` to PATH

## Stack Dump

 
	eth.exe!CryptoPP::Integer::operator=(class CryptoPP::Integer const &)	C++
 	eth.exe!CryptoPP::PositiveDivide(class CryptoPP::Integer &,class CryptoPP::Integer &,class CryptoPP::Integer const &,class CryptoPP::Integer const &)	C++
 	eth.exe!CryptoPP::Integer::Divide(class CryptoPP::Integer &,class CryptoPP::Integer &,class CryptoPP::Integer const &,class CryptoPP::Integer const &)	C++
 	eth.exe!CryptoPP::Integer::Modulo(class CryptoPP::Integer const &)	C++
	>eth.exe!CryptoPP::operator%(const CryptoPP::Integer & a, const CryptoPP::Integer & b) Line 670	C++
 	eth.exe!CryptoPP::MontgomeryRepresentation::ConvertIn(class CryptoPP::Integer const &)	C++
 	eth.exe!CryptoPP::ECP::ECP(class CryptoPP::ECP const &,bool)	C++
 	eth.exe!CryptoPP::EcPrecomputation<class CryptoPP::ECP>::SetCurve(class CryptoPP::ECP const &)	C++
 	eth.exe!CryptoPP::DL_GroupParameters_EC<class CryptoPP::ECP>::Initialize(class CryptoPP::OID const &)	C++
 	eth.exe!CryptoPP::DL_GroupParameters_EC<CryptoPP::ECP>::DL_GroupParameters_EC<CryptoPP::ECP>(const CryptoPP::OID & oid) Line 50	C++
 	eth.exe!dev::crypto::Secp256k1PP::Secp256k1PP() Line 157	C++
 	eth.exe!dev::crypto::Secp256k1PP::get() Line 100	C++
 	eth.exe!dev::KeyPair::populateFromSecret(const dev::SecureFixedHash<32> & _sec) Line 302	C++
 	eth.exe!dev::KeyPair::KeyPair(const dev::SecureFixedHash<32> & _k) Line 161	C++
 	eth.exe!dev::eth::`dynamic initializer for 'FluidityTreasure''() Line 29	C++
 	ucrtbase.dll!00007ffd9c399bde()	Unknown
 	eth.exe!__scrt_common_main_seh() Line 223	C++
 	kernel32.dll!00007ffd9da28364()	Unknown
 	ntdll.dll!00007ffd9f9870d1()	Unknown

**Comment by chfast** [comment]
I guess this is a regression, right?

**Comment by gumb0** [comment]
@jola0855 Please try building from latest develop

**Comment by jola0855** [comment]
No longer crashes. Awesome work. Thank you.
