### ISSUE TITLE
eth/eth --test with a specific fee schedule or a specific block number

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#3504]
When I test Solidity's gas estimator, I use
```
eth/eth --test --ipcpath /tmp/test
```
but this activates old fee schedule (before EIP 150 and EIP160).

Somehow I need a way to specify either the block number or the fee schedule where the test happens.

**Comment by pirapira** [comment]
Alternatively, for testing Solidity, I'm happy if  `eth/eth --test` activates the most recent fee schedule.

**Comment by chriseth** [comment]
Even better: We might allow setting the gas schedule as part of the genesis config block (at least for the pre-defined schedules).

**Comment by chriseth** [comment]
So it seems that we can at least specify the fork block number as part of the chain config. This unblocks the Solidity issue, but regardless of that, it probably makes sense to have a default that sets the `--test` params to the latest params of the main network.

**Comment by pirapira** [comment]
That makes sense.

**Comment by winsvega** [comment]
you could set the block fork number in a genesis file. 
this will activate specific fork rules and schedule
see https://github.com/ethereum/cpp-ethereum/tree/develop/libethashseal/genesis

**Comment by chriseth** [comment]
Yes, this is what we are doing now. I think this can be closed.
