### ISSUE TITLE
centos is not recognized by install_deps.sh

### ISSUE THREAD

**Issue by lhirlimann** [ethereum/cpp-ethereum#3511]
[root@poney cpp-ethereum]# ./scripts/install_deps.sh
./scripts/install_deps.sh: line 145: lsb_release: command not found
ERROR - Unsupported or unidentified Linux distro.
See http://cpp-ethereum.org/building-from-source/linux.html for manual instructions.
If you would like to get your distro working, that would be fantastic.
Drop us a message at https://gitter.im/ethereum/cpp-ethereum-development.

**Comment by chriseth** [comment]
Sorry, I think you have to resort to the manual instructions. If you manage to get it working, we can turn your manual instructions into automatic ones for others to benefit.

**Comment by lhirlimann** [comment]
cmake for centos is 2.18 so bleh :(

**Comment by chfast** [comment]
For cmake, you can download binaries from cmake download page.

**Comment by lhirlimann** [comment]
Yeah then I run in dependancy issues :(

**Comment by chfast** [comment]
Can you elaborate on that? Does this downloaded binary not work?

I can try to check CentOS in docker (already did that for Debian, Fedora and SuSE)...

**Comment by lhirlimann** [comment]
It fails to compile the lbjsonrpc library with json errors. Camke building and installing was fine.

**Comment by chfast** [comment]
I managed to install everything needed except leveldb-devel. Is this packages available for CentOS?

**Comment by chfast** [comment]
Fixed in #3524.
