### ISSUE TITLE
is there any replacement for ethrpctest tool

### ISSUE THREAD

**Issue by clar** [ethereum/cpp-ethereum#3515]
I just wanted to try https://github.com/ethereum/rpc-tests to do some tests for the cpp client, but I can not find the ethrpctest tool.
I check the cmakefile history, developer removed it  https://github.com/ethereum/cpp-ethereum/commit/16372b2d01e5a716c6edd075d3b60479426a4a99#diff-af3b638bc2a3e6c650974192a53c7291.

**Comment by chriseth** [comment]
As far as I know, the rpc tests are way out of date and do not test much, so if you would like to write some tests, that would be very much apprechiated! As the defined interface is the RPC interface itself, we thought it is a cleaner solution to run a unified test tool against each client, so there is not really a need for an "rpctesttool" that is part of the cpp-ethereum repository. As a lightweight tool, I would recommend https://github.com/ethereum/ethereum-console

**Comment by clar** [comment]
ok , thanks for the clarification!
