### ISSUE TITLE
Fix "make install"

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3516]
Some people try to build cpp-ethereum from source, but even `make install` does not work.

Proposed changes:
- [ ] Do not install headers. There is a mess there, and I suspect nobody is going to use them anyway.
- [ ] Check if every shared libs are installed.
- [ ] Add integration test for it?
- [ ] Build static libs (without installing them) to limit number of targets being installed?

**Comment by gcolvin** [comment]
I don't understand. The usual

> git clone recursive https://github.com/ethereum/cpp-ethereum.git
> cd cpp-ethereum
> mkdir build
> cd build
> cmake ..
> make

works just fine.

**Comment by chfast** [comment]
It's not for developer, but for advanced user. `make install` is quite common and we also have that in official documentation. The worst case is right now, where `make install` copies random files and nothing works. We can also disable `install` command, but I prefer to fix it.

**Comment by chriseth** [comment]
I agree, let's remove the headers (I thought I already did this?) and let's also make sure that `make install` works without you having to run `ldconfig` afterwards.

**Comment by chriseth** [comment]
Sorry, accidentally closed.
