### ISSUE TITLE
Implement EIP5 - better gas for call output

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3520]
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-5.md
https://github.com/ethereum/EIPs/issues/8

Implementing https://github.com/ethereum/cpp-ethereum/issues/3318 first would be helpful.

**Comment by chfast** [comment]
This is dead, right @chriseth ?

**Comment by chriseth** [comment]
Yes.
