### ISSUE TITLE
Issues sending work

### ISSUE THREAD

**Issue by lhirlimann** [ethereum/cpp-ethereum#3526]
For the last few days I'm getting the following while mining using nanopool.org : 
[ludo@Oulanl ethminer]$   ✘  15:40:39.325|ethminer  Failed to submit hashrate.
  ✘  15:40:39.325|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out

JSON-RPC problem. Probably couldn't connect. Retrying in 1... 
miner  15:40:51.334|ethminer  Mining on PoWhash #c2aaa0c6… : 91049 H/s = 2004000 hashes / 22.01 s
  ✘  15:41:01.339|ethminer  Failed to submit hashrate.
  ✘  15:41:01.339|ethminer  Dynamic exception type: jsonrpc::JsonRpcException
std::exception::what: Exception -32003 : Client connector error: libcurl error: 28 -> Operation timed out

JSON-RPC problem. Probably couldn't connect. Retrying in 1...

culprit seems to be     Upgraded libmicrohttpd-0.9.46-2.fc24.x86_64             @fedora/24
    Upgrade                0.9.52-1.fc25.x86_64             @updates
    Upgraded libmicrohttpd-devel-0.9.46-2.fc24.x86_64       @fedora
    Upgrade                      0.9.52-1.fc25.x86_64       @updates

Nanopool si working correctly from my windows machine.

**Comment by lhirlimann** [comment]
This looks exactly like https://github.com/ethereum/go-ethereum/issues/1695 :(

**Comment by lhirlimann** [comment]
How can I debug what's going on ? I've downgraded libmicrohttpd and it still fails :(

**Comment by chfast** [comment]
I think microhttpd is not related, because ethminer works in RPC client mode and only uses libcurl.

**Comment by lhirlimann** [comment]
Yeah so I've rebuild linjson-rpc and it still fails :( I whish I know what broke it.

**Comment by lhirlimann** [comment]
fixed issue with the firewall that got updated. Sorry for the noise.

**Comment by chfast** [comment]
No problem, thanks for the information.
