### ISSUE TITLE
ethminer -M -G returns "Invalid argument: -G"

### ISSUE THREAD

**Issue by irmas** [ethereum/cpp-ethereum#3528]
Hello,

I just installed ethminer from source on ubuntu 16.10 (and  the ethereum-git package from the AUR on archlinux).

When I run `ethminer -M -G` I get : `Invalid argument: -G`

I didn't find any topics discussing this issue.

Did I miss a step ?

**Comment by chfast** [comment]
Yes. No GPU mining here any more. Sorry.

Alternative: https://github.com/Genoil/cpp-ethereum

**Comment by megacrypto** [comment]
How come? Genoil been out of updates since last Sep.?

**Comment by chfast** [comment]
This looks even worse for ethminer here. We have not made any changes there since the release.

**Comment by axic** [comment]
Closed as mining is not supported here. Ethminer is maintained at https://github.com/ethereum-mining/ethminer
