### ISSUE TITLE
Fix eth solo build

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3535]
This should work:
```
make eth
make install
```

- [x] `make eth` is broken -- BuildInfo.h header is not generated.
- [x] If only eth has been built, `make install` should only install eth. For this we might want to mark other install targets as `OPTIONAL`.

**Comment by chriseth** [comment]
Sorry, but what is this issue about?

**Comment by chfast** [comment]
Updated description.

**Comment by chriseth** [comment]
Ok, now it is clearer - I though this was a bug and the proposed solution was `make eth; make install` ;-)
