### ISSUE TITLE
Update mining docs

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3538]
Update official mining docs. Place there information that cpp-ethereum does not support high performance mining any more.

http://ethdocs.org/en/latest/mining.html

- [ ] Update docs.
- [ ] Create `ethminer` branch or tag with latest commit supporting OpenCL.
- [ ] Redirect users looking for mining to https://github.com/Genoil/cpp-ethereum.

**Comment by dindinw** [comment]
Hi, @chfast, just curious, Why the GPU mining was removed?

**Comment by chfast** [comment]
No capacity to support it.

**Comment by axic** [comment]
@chfast is this still pending?

**Comment by chfast** [comment]
It is, but seems like maintaining these docs is pointless.
