### ISSUE TITLE
Account abstraction - EIP 86

### ISSUE THREAD

**Issue by chriseth** [ethereum/cpp-ethereum#3546]
Implement https://github.com/ethereum/EIPs/issues/86

TODO
 - [x] Transactions with signature (0, 0, 0) (ie. v = r = s = 0 0) are valid and msg.sender is set to uint120(-1) during execution.
 - [x] Accept those transactions if they are coming in from blocks, but do not forward such transactions if they are coming in not yet in a block.

**Comment by gumb0** [comment]
Reminder: we need to disable incrementing the nonce of the sender in case of zero signature

**Comment by pirapira** [comment]
Reminder: we need to change the way the addresses of new contracts are calculated.

Reminder: we need to add CREATE_P2SH instruction.

**Comment by yann300** [comment]
@pirapira yep I think I could do that next week.

**Comment by chfast** [comment]
What do we do with this?

**Comment by pirapira** [comment]
@chfast we leave it until there is a decision whether Constantinople includes this or not.

**Comment by pirapira** [comment]
@chfast since there is nothing to do currently, we can close this issue, I think.

**Comment by chfast** [comment]
Based on AllCoreDev https://github.com/ethereum/pm/issues/52, the EIP-86 is probably not going to be accepted in this "big" variant.
