### ISSUE TITLE
Install failed, possibly "Wrong Crypto++ version"

### ISSUE THREAD

**Issue by scrambler803** [ethereum/cpp-ethereum#3548]
Hi, I'm brand new to all this and have very limited scripting experience. I tried to research the issue best I could, but now I need somebody more experienced to throw eyes on this.

I'm unable to install 'cpp-ethereum' using the following command:

`brew install cpp-ethereum --verbose`

I get the following error:

`make: *** [all] Error 2`
and
`Error: ethereum/ethereum/cpp-ethereum 1.3.0 did not build`

My best guess is the problem could be related to the Cryptopp version number. The following line indicates version 570, but my Homebrew version is 565.
`/tmp/cpp-ethereum-20170208-71388-1g9mo8t/libdevcrypto/CryptoPP.cpp:31:1: error: static_assert failed "Wrong Crypto++ version"
static_assert(CRYPTOPP_VERSION == 570, "Wrong Crypto++ version");`

 After doing some digging here, it seems that these versions are referring to the local and global versions respectively, as mentioned here #3493 

In this thread, it appears that a patch had been committed to address this issue:
[**Add HeaderVersion() and LibraryVersion() functions #371**](https://github.com/weidai11/cryptopp/issues/371)

So I can't tell if this is an actual problem for me, or a red herring.

The other error that occurs just before the installation terminates looks like this:
`[ 27%] Built target llvm-project
make: *** [all] Error 2`

I have no idea what this means. Can someone look at the output from my terminal session and help me get pointed in the right direction? Please :crossed_fingers: I've attached it as .txt file
[failed brew_install_cpp-ethereum_verbose.txt](https://github.com/ethereum/cpp-ethereum/files/760402/failed.brew_install_cpp-ethereum_verbose.txt)

macOS: 10.11.6-x86_64

**Comment by momchilov** [comment]
I'm having the same issue on macOS 10.12.3

**Comment by scrambler803** [comment]
@momchilov Are you encountering both errors? Or one or the other?

**Comment by chfast** [comment]
I just pushed the fix for this. Sorry for inconvenience.

BTW, Crypto++ is not the system dependency any more.

**Comment by scrambler803** [comment]
Thank you, I uninstalled Cryptopp using
`brew uninstall cryptopp`

Then I installed using
`brew reinstall cpp-ethereum --with-gpu-mining --devel --headless --build-from-source`

The install was successful, however I can't seem to get up and mining with GPU. But I suppose that's an issue for another thread.
And if I'm reading it correctly, according to #3528 GPU mining is no longer possible?

**Comment by chfast** [comment]
Yes. Unfortunately, we don't support OpenCL (GPU mining) any more.

**Comment by chfast** [comment]
Fixed by https://github.com/ethereum/cpp-ethereum/pull/3542.
