### ISSUE TITLE
Prepare Metropolis Tests

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#3561]
- [x] define metropolis test genesis
- [x] define metropolis transition block in the mainnetwork genesis
- [x] implement metropolis rules
- [x] add test run on metropolis rules
- [ ] implement metropolis tests
- - [x] precompiled add tests
- - [x] precompiled mul tests
- - [x] precompiled pairing tests
- - [ ] new transaction rule tests
- - - [ ] correct block number in transaction tests once metropolis transition number is determined
- [x] check and seal expect section for metropolis on old state tests
- [x] fill statetests and statetests as blockchain on metropolis

**Comment by chfast** [comment]
Is this done?

**Comment by winsvega** [comment]
yes. transaction changes were not implemented. new transaction tests are disabled

**Comment by gumb0** [comment]
This is outdated

**Comment by winsvega** [comment]
new transaction rules was not included in Metropolis
