### ISSUE TITLE
Installation problem cpp-ethereum

### ISSUE THREAD

**Issue by pikachew-ensimag** [ethereum/cpp-ethereum#3563]
Hi, I am installing cpp-ethereum  by building the code source from git(I tried the easier installation: apt-get ethereum but the package is not found). My OS is Ubuntu 14.04. I have installed all the dependencies required and the CMake 's version is  3.4.1. After the command(cmake ..), I did a make and I got the following error. Does anyone have a solution? Thanks in advanced.

[  0%] Built target cpp-ethereum_BuildInfo.h
[  1%] Performing download step (download, verify and extract) for 'cryptopp-project'
-- downloading...
     src='https://github.com/weidai11/cryptopp/archive/bccc6443c4d4d611066c2de4c17109380cf97704.tar.gz'
     dst='/home/chews/cpp-ethereum/deps/src/CRYPTOPP_bccc6443.tar.gz'
     timeout='none'
CMake Error at /home/chews/cpp-ethereum/build/deps/cryptopp/src/cryptopp-project-stamp/download-cryptopp-project.cmake:27 (message):
  error: downloading
  'https://github.com/weidai11/cryptopp/archive/bccc6443c4d4d611066c2de4c17109380cf97704.tar.gz'
  failed
  status_code: 1
  status_string: "Unsupported protocol"
  log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

**Comment by chfast** [comment]
Have you built the CMake yourself? It lacks SSL support.

If not, you might need to install a libcurl with SSL support.
