### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by moneta** [ethereum/cpp-ethereum#3572]
I got the error when building from source. Any idea?

[ 77%] Linking CXX static library libtestutils.a
[ 77%] Built target testutils
Scanning dependencies of target testeth
[ 78%] Building CXX object test/CMakeFiles/testeth.dir/boostTest.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
test/CMakeFiles/testeth.dir/build.make:62: recipe for target 'test/CMakeFiles/testeth.dir/boostTest.cpp.o' failed
make[2]: *** [test/CMakeFiles/testeth.dir/boostTest.cpp.o] Error 4
CMakeFiles/Makefile2:1508: recipe for target 'test/CMakeFiles/testeth.dir/all' failed
make[1]: *** [test/CMakeFiles/testeth.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chriseth** [comment]
This is usually an out of memory error on your build machine. Perhaps reduce the number of parallel builds (remove the `-j` option to make)

**Comment by moneta** [comment]
I killed other running programs and re-built successfully. Thanks a lot.
