### ISSUE TITLE
scripts/install_deps.sh failed

### ISSUE THREAD

**Issue by NuclearManD** [ethereum/cpp-ethereum#3575]
Upon executing `scripts/install_deps.sh` I received this message:
`Unsupported Linux distribution: openSUSE Leap.`
No further information was given.

**Comment by chriseth** [comment]
Sorry, but this script cannot support any distribution out there. For openSUSE Leap, it seems you are on your own and have to figure out the exact packages to install yourself. Alternatively, you can use the docker image.

**Comment by chfast** [comment]
Hi @NuclearManD,

To build it you need basic C++ tools: a compiler, git, cmake >= 3.4, 
and 4 system libraries in develop variant:

- leveldb-devel
- curl-devel
- libmicrohttpd-devel
- gmp-devel

I can update the script for openSUSE if you can change if the given package names are correct and how to install them on your distribution.

**Comment by tysun** [comment]
Hello. Docs 

> We now have a “one button” script which installs all required external dependencies on macOS: `./scripts/install_deps.sh`

Am I correct in assuming we can just execute that command in Terminal as is to install all dependencies? Or do we actually need to use the name of a specific dependency? I get 

> no such file or directory: ./scripts/install_deps.sh

**Comment by chfast** [comment]
@tysun you should know what you are doing. Don't run any script with sudo.
