### ISSUE TITLE
cmake .. fails on fedora

### ISSUE THREAD

**Issue by lhirlimann** [ethereum/cpp-ethereum#3583]
running latest fedora25 cmake fails : 
[ludo@Oulanl cpp-ethereum]$ mv build build.one
[ludo@Oulanl cpp-ethereum]$ mkdir build
[ludo@Oulanl cpp-ethereum]$ cd build
[ludo@Oulanl build]$ cmake .. -DBUNDLE=miner
-- The C compiler identification is GNU 6.3.1
-- The CXX compiler identification is GNU 6.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CURL: /usr/lib64/libcurl.so  
-- Found mhd: /usr/lib64/libmicrohttpd.so  
CMake Error at CMakeLists.txt:50 (include):
  include could not find load file:

    deps/boost.cmake

------------------------------------------------------------------------
-- Configuring cpp-ethereum
------------------------------------------------------------------------
-- CMake 3.6.2 (/usr/bin/cmake)
-- CMAKE_BUILD_TYPE Build type                               RelWithDebInfo
-- TARGET_PLATFORM  Target platform                          Linux
-- STATIC BUILD                                              
--------------------------------------------------------------- features
--                  Hardware identification support          
--                  HTTP Request support                     TRUE
-- VMTRACE          VM execution tracing                     OFF
-- PROFILING        Profiling support                        OFF
-- FATDB            Full database exploring                  ON
-- ROCKSDB          Prefer rocksdb to leveldb                OFF
-- PARANOID         -                                        OFF
-- MINIUPNPC        -                                        ON
------------------------------------------------------------- components
-- TESTS            Build tests                              ON
-- EVMJIT           Build LLVM-based JIT EVM                 OFF
------------------------------------------------------------------------

-- Found leveldb: /usr/lib64/libleveldb.so  
-- Cpuid headers: CPUID_INCLUDE_DIR-NOTFOUND
-- Cpuid lib   : CPUID_LIBRARY-NOTFOUND
-- Found miniupnpc: /usr/lib64/libminiupnpc.so  
-- miniupnpc headers: /usr/include
-- miniupnpc lib   : /usr/lib64/libminiupnpc.so
-- test: ClientBase |  --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=1; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=3; --eth_testfile=BlockTests/bcJS_API_Test --eth_threads=10; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=1; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=3; --eth_testfile=BlockTests/bcValidBlockTest --eth_threads=10
-- test: JsonRpc |  --eth_testfile=BlockTests/bcJS_API_Test; --eth_testfile=BlockTests/bcValidBlockTest
-- Found gmp: /usr/lib64/libgmp.so  
-- Gmp headers: /usr/include
-- Gmp lib   : /usr/lib64/libgmp.so
-- Configuring incomplete, errors occurred!
See also "/home/ludo/ethereum/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".

[CMakeOutput.txt](https://github.com/ethereum/cpp-ethereum/files/792790/CMakeOutput.txt)

**Comment by chfast** [comment]
You have to initialize/update the git submodules. Do `git submodule update --init`.

**Comment by lhirlimann** [comment]
Thanks .... it worked.
