### ISSUE TITLE
Load keys.info file

### ISSUE THREAD

**Issue by Levino** [ethereum/cpp-ethereum#3598]
I still have a keys.info file. Should contain the private keys, right? How do I load it today?

**Comment by chriseth** [comment]
It only contains things like the names of the keys, it does not contain the actual private data. You should be able to import keys even without a `keys.info` file.

**Comment by Levino** [comment]
So where are the keys stored? in the .web3 folder?

**Comment by chriseth** [comment]
Yes, `.web3/keys`.

**Comment by Levino** [comment]
Was that always the case? I created this early 2016. I think I used ```eth```. I only have the files ```keys.info``` and ```keys.info.salt```. In ```.web3``` there is no file ```keys```.

**Comment by Levino** [comment]
Just as additional info, I find this:

https://www.reddit.com/r/ethereum/comments/378fpw/extracting_keys_from_a_backed_up_ethereum_folder/

https://forum.ethereum.org/discussion/2949/backup-keystore-in-eth

**Comment by Levino** [comment]
I would try to install eth from february 2016 then. But the build instructions seem to be gone. Anyone able to help on this?

**Comment by chriseth** [comment]
As long as you do not use things like brain wallets, the keys are in `~/.web3/`, each one in their own file. I'm also pretty sure that it was like that one year ago.

**Comment by westlywright** [comment]
@chriseth is there a way to export brain wallets then?

**Comment by chriseth** [comment]
@westlywright I think `ethkey` can still handle them. I would advise you to export them using 
`ethkey --inspect --show-me-the-secret`

**Comment by chriseth** [comment]
I mean it's not that brain wallets are "stored" in keys.info, they are stored in your brain, but I cannot promise that we will maintain the algorithm to generate the secret key from the phrase (although you can always use an old binary to do that for you).

**Comment by westlywright** [comment]
@chriseth I get you know, sorry for this disconnect. I'll try you're suggestion when I get home tonight and see if I can export the key. thanks!

**Comment by westlywright** [comment]
@chriseth I was able to run the command and got the following error. I am using the same password I have to enter when just inspecting the key which doesnt throw and error.


`libc++abi.dylib: terminating with uncaught exception of type dev::eth::PasswordUnknown: std::exception`

**Comment by westlywright** [comment]
@chriseth @Levino Just a heads up, I was able to extract my private keys using an old build of Alethzero.  Not sure if this was the right way to do it but I was able to import my wallet into another app via the private key. I pulled the build (for mac) from this old WebThree Umbrealla release. I could not figure out how to pull the old PPA for ubuntu which is why i used the mac build.  https://github.com/ethereum/webthree-umbrella/releases/tag/v1.2.9

**Comment by Levino** [comment]
Thank you Westly, will give a spin. Should be able to recover 400$ worth of ether if that works :)

**Comment by westlywright** [comment]
Awesome. My process was just placing the key files in the corresponding cpp-ethereum folder. I start Alethzero and it saw the keys right away. Selected the wallet and then selected export keys from the menu. Worked like a charm! Hopefully it works for you too!

**Comment by Levino** [comment]
It looks like my issue is actually another one as I thought. The keys are stored in ```~/.web3/keys``` as it looks. I have some json files there. I tried to extract the private keys with ethkey but get this error while inspecting them bare:
```bash
Account address is either not defined or not in hex format
```
And this error when trying to decrypt them:
```bash
Invalid key - MAC mismatch; expected 226[reducted]b0 , got 02d[reducted]a0
```
It looks like literally the only other person ever having this issue was @winsvega [here](https://gitter.im/ethereum/cpp-ethereum?at=56e2e5490055f8f35a825216)

![selection_033](https://cloud.githubusercontent.com/assets/1150767/25524408/bc595b38-2c0a-11e7-8a78-2a9be578aea3.jpg)

How can I decrypt keys of the old format?
