### ISSUE TITLE
Better command line argument handling  (Boost Program Options)

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3628]
For historical reason, we parse command line options in our tools (eth, rlp, ethvm, ...) manually. Let's improve this by using Boost.Program_options (http://www.boost.org/doc/libs/1_63_0/doc/html/program_options.html).

Pay attention for classes like `MinerAux` that _injects_ its options when included. Maybe Boost have a solution for that.

We can leave ethminer untouched if possible.

**Comment by vjvishjn** [comment]
Hi Paweł, I want to work on this issue.

**Comment by chfast** [comment]
Hi @vjvishjn,

you can take it.

Please inform us on the progress if any. Also this seems to be a big task, bo it might be worth to split it into smaller pieces after research and design is done.

Sorry for late response, I was away for a week.

Thanks!

**Comment by vjvishjn** [comment]
Great, I'll start to work on the issue. I'll reach you about the progress and in case of any doubt.

**Comment by demon1999** [comment]
Hello, I want to work on it.

**Comment by chfast** [comment]
Go ahead!

**Comment by chfast** [comment]
Most of it is done. testeth left.
