### ISSUE TITLE
CodeCov: disable fixing data

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#3647]
Add option `-X fix` to codecov script config in .travis.yml.

**Comment by narendravardi** [comment]
Hi Paweł,

I am a newbie and want to work on this issue. Can I work on this?

**Comment by chfast** [comment]
Hi Narendra,
yes you can take it.

**Comment by narendravardi** [comment]
@chfast,

I have raised a pull request for this issue. Please review and let me know if any changes required.

**Comment by chfast** [comment]
Fixed.
