### ISSUE TITLE
host rpc server(s) instead of using webthreedirect

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#380]
re: https://github.com/ethereum/cpp-ethereum/pull/373/files#r18884723

WebThreeDirect shouldn't be altered - it should not set up an RPC server.

The RPC server functionality should be in another class (perhaps derived from WebThreeDirect or with it as a member).

WebThreeDirect is for those that don't want other processes potentially calling in (perhaps for a private block chain or whatever).

**Comment by debris** [comment]
Can we close this? I think it's not up to date.
