### ISSUE TITLE
ethvm aborts

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4018]
On develop `aab2744c4dcfcfc0cf0fe8d7ec112bb1348842a9` with Ubuntu 16.04.2, I get an error when I run `ethvm`.

```
$ ethvm/ethvm
terminate called after throwing an instance of 'std::runtime_error'
  what():  value type is 6 not 0
zsh: abort (core dumped)  ethvm/ethvm
```

**Comment by gumb0** [comment]
Thanks for the report! I think I've already fixed this in https://github.com/ethereum/cpp-ethereum/pull/3635
Merge this commit https://github.com/ethereum/cpp-ethereum/pull/3635/commits/2d042db472d4ca6ea5c8b654ffb326be2ace0d58 if it's blocking you

**Comment by pirapira** [comment]
Thank you!  I'll wait.  (I just wanted to try Klee, to see if it can search contracts' code paths, for fun.)

**Comment by gumb0** [comment]
@pirapira I've merged the PR, please try if this works for you

**Comment by pirapira** [comment]
Yes, the problem has disappeared from `develop`.
