### ISSUE TITLE
ethminer failes to generate DAG file for any block larger than 3870000 (serious bug)

### ISSUE THREAD

**Issue by kenshirothefist** [ethereum/cpp-ethereum#4021]
When trying to generate DAG file for any block larger than 3870000, it will only produce a 0-size file.

Try this:

`ethminer.exe -D 3870000`

It will run just of a few seconds, generate 0-bytes file "full-R23-3868abc5dcee2334" and exit (or even crash in some cases).

If you try to generate DAG for any previous block, for example:

`ethminer.exe -D 3840000`

it will work just fine.

**Comment by nicehashdev** [comment]
Hint: I suspect this may something to do with "int" overflow? Since DAG file is now nearly 2^32 / 2 in size, standard int would overflow at that number.

**Comment by gumb0** [comment]
Thank you for reporting this!

@nicehashdev is right, good old int overflow happens for me on Windows here:
https://github.com/ethereum/cpp-ethereum/blob/develop/libethash/io.c#L94

@kenshirothefist Which OS do you use?

**Comment by kenshirothefist** [comment]
@gumb0 I was testing under Windows 7 / 10.

**Comment by gumb0** [comment]
Thanks, I'll look into this

**Comment by gumb0** [comment]
@kenshirothefist Could you please check if this branch works for you https://github.com/ethereum/cpp-ethereum/tree/fix-mining-fseek ?

**Comment by kenshirothefist** [comment]
@gumb0 I just tested [fix-mining-fseek branch ](https://github.com/ethereum/cpp-ethereum/tree/fix-mining-fseek) and it works ... DAG file was correctly generated for "-D 3870000". So this looks good. I'll also test under Windows, but I have to prepare build env...

**Comment by gumb0** [comment]
@kenshirothefist Thanks for your help, it works for me on Windows.
