### ISSUE TITLE
Deps: integrate rocksdb into Hunter

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#4036]
This is issue goes full outside of cpp-ethereum but we would benefit from it a lot.

Hunter is a C++ package manager based on CMake.
RocksDB is leveldb-like database with CMake build system and Windows support.

To bring the rocksdb to the Hunter start by reading the Hunter docs https://docs.hunter.sh about how to add a new project to it. Because rocksdb is CMake already and has no mandatory deps, it should be quite simple.

**Comment by unkemptArc99** [comment]
Hi, @chfast! I am new to the open-source contribution (tbh, it is my first time here). This task seems very rudimentary (though I might be wrong about it's complexity). Can I work with you on this issue?

**Comment by chfast** [comment]
The actual work is being done in https://github.com/ruslo/hunter/pull/991. You can help there if you know CMake.

But I'm not sure rocksdb is so good replacement for leveldb considering parity's problems with it.

**Comment by isaachier** [comment]
Have you considered LMDB? Supposedly has better performance than either LevelDB or RocksDB.

**Comment by chfast** [comment]
No, but we can try if anyone is willing to work on this.

RocksDB looks like being hard to tune... but getting it packaged for Hunter is easier.

**Comment by isaachier** [comment]
I'm already working on making getting rocksdb into Hunter. LMDB is already in Hunter. I'd be willing to help out with porting over to whichever database you think is best. I think rocksdb will have a very similar if not identical API to leveldb because it is a fork of it. LMDB uses `void*` instead of strings, etc.

**Comment by chfast** [comment]
Thanks @isaachier for all this work.

We also need proper OOP API for database.

**Comment by isaachier** [comment]
Np I was doing some work to port packages to Hunter when I came across your pull request regarding rocksdb. Somehow that led me to this discussion. I am very interested in ethereum and would love to contribute, but I probably to spend some time researching the background. Once I get up to speed, I'd be glad to help out.

**Comment by chfast** [comment]
Done: https://docs.hunter.sh/en/latest/packages/pkg/rocksdb.html#pkg-rocksdb.
