### ISSUE TITLE
Consider adding a new EVM Schedule called "experimental"

### ISSUE THREAD

**Issue by axic** [ethereum/cpp-ethereum#4056]
This would enable all the experimental features (bitwise shifting, static jumps, subroutines, etc.)

**Comment by axic** [comment]
cc @gumb0

**Comment by gumb0** [comment]
@chfast Do you work on something like this already?

**Comment by chfast** [comment]
I added EWASM schedule: https://github.com/ethereum/cpp-ethereum/pull/4776.
