### ISSUE TITLE
DAG never starts...

### ISSUE THREAD

**Issue by dev00100000** [ethereum/cpp-ethereum#4067]
When I run ethminer I get this message:

> Genoil's ethminer 0.9.41-genoil-1.1.9
> =====================================================================
> Forked from github.com/ethereum/cpp-ethereum
> CUDA kernel ported from Tim Hughes' OpenCL kernel
> With contributions from nerdralph, nicehash, RoBiK and sp_ 
> 
> Please consider a donation to:
> ETH: 0xeb9310b185455f863f526dab3d245809f6854b4d

But thats it... it never attempts DAG creation or anything. I am running this on Ubuntu 16.04.

**Comment by dev00100000** [comment]
Ok so, I didn't do anything (maybe my third restart did the trick? lol) but now it looks like it's trying but it keeps saying this:

  m  19:01:43|ethminer  Waiting for work package...
  m  19:01:43|ethminer  Waiting for work package...
  m  19:01:44|ethminer  Waiting for work package...
  ✘  19:01:44|stratum  :-( Rejected in 89564 ms.

I'm not sure why it is rejecting...

**Comment by dev00100000** [comment]
I ran ethminer -M -G and the Trials are all giving a big fat zero.

```
  ℹ  19:27:13|GPU0  Initialising miner...
[OPENCL]:Using platform: AMD Accelerated Parallel Processing
[OPENCL]:Using device: Ellesmere(OpenCL 1.2 AMD-APP (2348.3))
[OPENCL]:Printing program log
[OPENCL]:
[OPENCL]:Creating cache buffer
[OPENCL]:Creating DAG buffer
[OPENCL]:Loading kernels
[OPENCL]:Writing cache buffer
[OPENCL]:Creating buffer for header.
[OPENCL]:Creating mining buffer 0
[OPENCL]:Creating mining buffer 1
Trial 1... 0
Trial 2... 0
Trial 3... 0
Trial 4... 0
Trial 5... 0

```

I don't know what to do. I checked and I can see one of my GPU's when I run:

```
root@DEV00100000:~# lspci -nn | grep VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [8086:0402] (rev 06)
02:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:67df] (rev ff)
```

Anyone have any ideas why it won't work?

**Comment by chfast** [comment]
Try https://github.com/ethereum-mining/ethminer.

**Comment by dev00100000** [comment]
I did try that... and I just realized I posted this in the wrong github, my apologies!
