### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by hteijiz** [ethereum/cpp-ethereum#4069]
Hello, I newby in ethereum. I install all components in AWS (Amazon Web Services). When I start de miner i have the error "(anonymous): Line 1:12 Unexpected identifier (and 3 more errors)"

This is the geth command line, i executed:
geth --syncmode fast --cache 4096 --rpc console

This is the ethminer command line:
ethminer --opencl-device 0 -G -F http://eth-eu.dwarfpool.com:80/<Address>

Could you help me? 
I get it once the miner works, but then I try to do a mining against a pool and since then it gives me this error.
Thanks in advance!

Best regards

Hugo

**Comment by chfast** [comment]
There is not enough information here. But if you want to use ethminer try this fork: https://github.com/ethereum-mining/ethminer.
