### ISSUE TITLE
CMake build failed (on Windows)

### ISSUE THREAD

**Issue by EzBar** [ethereum/cpp-ethereum#4078]
Hi,
I'm trying to build the latest version (develop branch, db8a4a2d9b) using CMake 3.8.1.
I'm getting the following error: 

"E:\Ethereum\cpp-ethereum\build\ALL_BUILD.vcxproj" (default target) (1) ->
"E:\Ethereum\cpp-ethereum\build\eth\eth.vcxproj" (default target) (11) ->
"E:\Ethereum\cpp-ethereum\build\libethashseal\ethashseal.vcxproj" (default target) (13) ->
"E:\Ethereum\cpp-ethereum\build\libethereum\ethereum.vcxproj" (default target) (15) ->
"E:\Ethereum\cpp-ethereum\build\libevm\evm.vcxproj" (default target) (16) ->
(ClCompile target) ->
  e:\ethereum\cpp-ethereum\libethereum\Executive.h(22): fatal error C1083: Cannot open include file: 'json/json.h': No such file or directory (compiling source file E:\Ethereum\cpp-ethereum\libevm\VM.cpp) [
E:\Ethereum\cpp-ethereum\build\libevm\evm.vcxproj]
  e:\ethereum\cpp-ethereum\libethereum\Executive.h(22): fatal error C1083: Cannot open include file: 'json/json.h': No such file or directory (compiling source file E:\Ethereum\cpp-ethereum\libevm\VMOpt.cpp
) [E:\Ethereum\cpp-ethereum\build\libevm\evm.vcxproj]
  e:\ethereum\cpp-ethereum\libethereum\Executive.h(22): fatal error C1083: Cannot open include file: 'json/json.h': No such file or directory (compiling source file E:\Ethereum\cpp-ethereum\libevm\VMCalls.c
pp) [E:\Ethereum\cpp-ethereum\build\libevm\evm.vcxproj]
  e:\ethereum\cpp-ethereum\libethereum\Executive.h(22): fatal error C1083: Cannot open include file: 'json/json.h': No such file or directory (compiling source file E:\Ethereum\cpp-ethereum\libevm\VMValidat
e.cpp) [E:\Ethereum\cpp-ethereum\build\libevm\evm.vcxproj]

    92 Warning(s)
    4 Error(s)

I've followed the instructions on the README file. I'm running Windows 10 with Visual Studio 2015 installed.
Any suggestion?

Best,
Ez

**Comment by chfast** [comment]
Should work for you environment. I will try to reproduce it.

**Comment by a651694192** [comment]
Have you solved your problem? I get the same settings with you, and I get 119 errors.

**Comment by chfast** [comment]
What console (cmd, powershell, bash) do you use?

**Comment by chfast** [comment]
Can you remove `deps` dir (in the source directory) and try again?

**Comment by chfast** [comment]
One more suggestion that is sometimes useful for Visual Studio is to reload the project (restart Visual Studio).

**Comment by pmelon** [comment]
I'm having the same issue. Fresh everything, multiple attempts. What info would help most?

**Comment by jbrache** [comment]
Same issue for me.

**Comment by chfast** [comment]
It looks like some kind of dependency issue. I will try to fix it.

As a workaround you may try to build "jsoncpp" target first.

**Comment by chfast** [comment]
Can you check now?
