### ISSUE TITLE
--vmtrace without --verbosity 3 should cause a warning

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4081]
When `testeth` takes a `--vmtrace` option but the verbosity is not enough to show the vmtrace, a reminder about increasing the verbosity would be helpful.

**Comment by winsvega** [comment]
perhaps it should autoset verbosity to 3 without additional flag?

**Comment by pirapira** [comment]
That makes sense.

**Comment by winsvega** [comment]
hm. this is already done 
https://github.com/ethereum/cpp-ethereum/blob/develop/test/tools/libtesteth/Options.cpp#L143
