### ISSUE TITLE
0.00MH/s, Allocating DAG buffer fails [clCreateBuffer(-61)]

### ISSUE THREAD

**Issue by batalanga** [ethereum/cpp-ethereum#4083]
Hello everyone, I'm trying to set up an ethereum miner for testing purposes. Here is the issue: i synced the blockchain and all, but the miner just wont mine. I checked forums all over, and figured maybe it can be an insufficient GPU memory. But i read the minimum required memory is 2GB, shouldn't this be enough?
![capture](https://cloud.githubusercontent.com/assets/10946682/26252951/ff40eefe-3cb1-11e7-9394-b1e894506013.PNG)
here is my log dump:
![ethminer1](https://cloud.githubusercontent.com/assets/10946682/26253216/dd0ee7f4-3cb2-11e7-8ca5-5f00ae121ec0.PNG)
![ethminer2](https://cloud.githubusercontent.com/assets/10946682/26253226/e55ad15c-3cb2-11e7-9062-d01b64369112.PNG)
The call stack was:
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -G --opencl-device 0 --opencl-platform 1 -S eu2.ethermine.org:4444 -FS eu1.ethermine.org:4444 -O address.name
Thanks for the help :)

**Comment by chfast** [comment]
1. Current cpp-ethereum does not support GPU mining any more. For GPU mining go https://github.com/ethereum-mining/ethminer.
2. You are not able to mine with GPU with 2 GB memory, because the dataset for mining is bigger than 2 GB already.
