### ISSUE TITLE
Ethminer stops working after getting a new work package?!

### ISSUE THREAD

**Issue by nixe321** [ethereum/cpp-ethereum#4087]
I tried a lot of different pools and also a lot of different miners and I always get the same problem. The miner starts with 0.00MH/s until it gets a new job and then it just stops working. 

m  17:54:37|main  Mining on PoWhash #2ade336c : 0.00MH/s [A0+0:R0+0:F0]
m  17:54:37|main  Mining on PoWhash #2ade336c : 0.00MH/s [A0+0:R0+0:F0]
m  17:54:38|main  Mining on PoWhash #2ade336c : 0.00MH/s [A0+0:R0+0:F0]
m  17:54:39|main  Mining on PoWhash #2ade336c : 0.00MH/s [A0+0:R0+0:F0]
m  17:54:39|main  Mining on PoWhash #2ade336c : 0.00MH/s [A0+0:R0+0:F0]
m  17:54:39|main  Got work package: #08237dd3

**Comment by chfast** [comment]
This is just a quirk. It will start working after finishing generating DAG.

Anyway, for all ethminer related issues or questions go to https://github.com/ethereum-mining/ethminer.
