### ISSUE TITLE
testeth should raise an error when a test case has a too long name

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4090]
When I was preparing test fillers for @winsvega, he met problems when a test case has a too long name.

A name with 58 characters was OK, but when a test case had a name with 98 characters, @winsvega said he could not `git clone` the `test` repository with the filled tests.

This issue keeps track of making `testeth` error out (or at least give a warning) when it sees a very long test name.

**Comment by winsvega** [comment]
58 chars 
is that includes full test path?

**Comment by pirapira** [comment]
@winsvega no, just the base name, excluding the directories.

**Comment by winsvega** [comment]
currently there are tests with like 73 chars in its filename. this is not really ok. but the git repo works.

**Comment by pirapira** [comment]
I close the issue if it works for you now.  I originally opened this when you experienced a problem on your local machine.

**Comment by winsvega** [comment]
hm. I guess having some kind of limit on test filename is actually good. but 50 chars would require to rename actually lots of tests. and refill.
