### ISSUE TITLE
Drop CPUID support

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#4097]
Remove all code withing `#if ETH_CPUID` macro guards and all related CMake options.

**Comment by jain98** [comment]
Hello, I'm just getting started with open source contribution. I have followed the provided setup steps and am pretty much ready to do some actual work. I want to solve this issue as it seems easy enough and would give me an understanding of the general workflow involved while contributing to open source. I just had one quick question. Which project is this for? Is this regarding a specific file or numerous files in the concerned project?

**Comment by chfast** [comment]
Which project? This one: cpp-ethereum. CPUID was supposed to be used to report stats about mining performance. Just remove all related to this: code, CMake config, etc.

**Comment by jain98** [comment]
So using visual studio I found that the files in which the above macro guard appears are in the libethashseal  folder within cpp-ethereum. But how was I supposed to know/determine that?

**Comment by chfast** [comment]
Just by searching in the source code. You can also search for CPUID in CMake files.

**Comment by jain98** [comment]
Ok, that makes sense. For the next part,  do I need to modify one of the CMakeLists.txt ?

**Comment by chfast** [comment]
If you find some CMake code that searches for cpuid lib and adds it as the dependency, you can remove it too.
The final goal is to remove some code and do not break tests. If you will not remove all of related code, it will be still fine.

**Comment by jain98** [comment]
Is there a way I can test my changes? I'm actually not able to run any of the projects.

**Comment by chfast** [comment]
Build and run testeth.exe.

**Comment by chfast** [comment]
How is this going?

**Comment by arunsethupat** [comment]
I wish to start contributing to this project with this. Shall I take this up?

**Comment by chfast** [comment]
Yes @arunsethupat, you can take it.

**Comment by arunsethupat** [comment]
@chfast Are you sure, this issue persists? Can't find any occurrence of CPUID.

**Comment by arunsethupat** [comment]
Hi @chfast 

Kindly check. Excuse me and let me know if I have made any mistakes.
