### ISSUE TITLE
Ubuntu build issue - jsonrpccpp

### ISSUE THREAD

**Issue by jczernia** [ethereum/cpp-ethereum#4101]
Hello
I went trough all steps, but my build fails with following message. Did I miss anything? 

[ 73%] Building CXX object eth/CMakeFiles/eth.dir/main.cpp.o
/home/emila/Documents/Jacek/cpp-ethereum/eth/main.cpp:49:53: fatal error: jsonrpccpp/client/connectors/httpclient.h: No such file or directory
compilation terminated.
Regards
Jacek

**Comment by matthod** [comment]
+1

**Comment by chfast** [comment]
Hi there, I will try to fix it. This seems to be small dependency issue. Can you build `jsonrpccpp` target first?
```
make jsonrpccpp
```

**Comment by chfast** [comment]
Nevermind, the fix is in the way.

If you have some knowledge of CMake you can help reviewing it in https://github.com/ethereum/cpp-ethereum/pull/4096.
