### ISSUE TITLE
miner build error on Arch (in libethash)

### ISSUE THREAD

**Issue by AntouanK** [ethereum/cpp-ethereum#4107]
Hi.

I'm trying to compile ethminer, to use it on an arch machine.
( I first run `cmake -DBUNDLE=miner ..` in /build )

Here's the error I get on `make`:
![screen shot 2017-06-02 at 15 54 16](https://cloud.githubusercontent.com/assets/4569111/26726450/c87df3e4-47ab-11e7-8578-04424b33d8fc.png)

I've installed leveldb, json-rpc-cpp and the CUDA stuff.
Any idea why I'm getting this error?

**Comment by AntouanK** [comment]
I tried the genoil fork ( https://github.com/genoil/cpp-ethereum ) and I can build `ethminer` there.
Feel free to close this issue if you think it's not useful.

**Comment by chfast** [comment]
No miner here any more. https://github.com/ethereum-mining/ethminer.
