### ISSUE TITLE
Compilation error fix on ARM64 (undefined reference trap_instruction())

### ISSUE THREAD

**Issue by innovina** [ethereum/cpp-ethereum#4110]
**Compilation on ARM fails due to undefined reference trap_instruction() in  libdevcore/debugbreak.h**

HAVE_TRAP_INSTRUCTION is set to 0 but in the code trap_instruction() is still active even if it is never called, that's why the error occurs.

**Code:**
#else
enum { HAVE_TRAP_INSTRUCTION = 0, };
#endif

**Bugfix:**
#else
enum { HAVE_TRAP_INSTRUCTION = 0, };
static void __inline__ trap_instruction(void)
{
}
#endif

**Comment by chfast** [comment]
We accept patches in form of Pull Requests, if you know how to fix it nicely.

In general, I think we can drop this debug support. I will try to fix it if I find some free time.
