### ISSUE TITLE
GPU can't allocate the DAG in a single chunk. 

### ISSUE THREAD

**Issue by testemunha200** [ethereum/cpp-ethereum#4113]
Hi, I looked on the other topics but wasn't able to got this working. I have a AMD R7 265x 2 GB graphics card. I'm able to mine UBIQ without problem, but when I try to mine Ethereum this error occurs.
Allocating/mapping DAG buffer failed with: clCreateBuffer(-61). GPU can't allocate the DAG in a single chunk. Bailing.
clEnqueueWriteBuffer(-38)

My .bat file looks like this:

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_SINGLE_ALLOC_PERCENT 100
set GPU_MAX_ALLOC_PERCENT = 100

ethminer.exe -G -SP 2 -S eth.suprnova.cc:5000 -O ***.***:***

With the **** configured correctly. Can someone help me? Tried everything already. Thanks.

**Comment by chfast** [comment]
2 GB is not enough any more.

And GPU mining support was dropped from cpp-ethereum project. See https://github.com/ethereum-mining/ethminer.
