### ISSUE TITLE
eth --ipcpath in Windows 10

### ISSUE THREAD

**Issue by SebLKMa** [ethereum/cpp-ethereum#4123]
I have built cpp-ethereum 1.3.0 and have it running in Windows 10.
Have anyone used the command line arg --ipcpath to specify the pipe name?
Seems like this does not work in Windows.

From FileSystem.cpp, line 56, dev::getIpcPath(), seems like this function has not been invoked by WindowsPipeServer.cpp

-Seb

**Comment by chfast** [comment]
Thanks for the report, I will take a look.

**Comment by chfast** [comment]
Can you test the provided PR: <https://github.com/ethereum/cpp-ethereum/pull/4131>?

**Comment by SebLKMa** [comment]
Please refer to comments in #4131
