### ISSUE TITLE
revert bug

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#4130]
We discovered that cpp does wrong revert of the state in case of address collision. 

The test is here (with wrong cpp results):
https://github.com/ethereum/tests/blob/cffb263d6c9075e1396e72d5d8febc21329b6600/BlockchainTests/GeneralStateTests/stRevertTest/RevertDepthCreateAddressCollision.json#L642-L665

The source for this test is here:
https://github.com/ethereum/tests/blob/develop/src/GeneralStateTestsFiller/stRevertTest/RevertDepthCreateAddressCollisionFiller.json#L188-L205

It appears to be that cpp won't restore the code of the original account after collision overwrite and then OOG revert. (case d0g0 - double oog). Python is failing the test.

**Comment by pirapira** [comment]
I changed the filler https://github.com/ethereum/tests/tree/fix-revert-bug

**Comment by pirapira** [comment]
Now I hit this problem #4148 which prevents me from filling tests.
