### ISSUE TITLE
Mining - Not sure If I'm doing this right.

### ISSUE THREAD

**Issue by hypop** [ethereum/cpp-ethereum#4134]
Newbie with this Need some help.
Whenever I run my bat file it just closes.
![cmd error](https://user-images.githubusercontent.com/26885884/27003578-79572002-4dc7-11e7-9835-d4dfcdf9e538.PNG)
This is my config:
**setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
ethminer.exe -F http://us-west1.nanopool.org:8888/0x627086ECa8D597a96fE8aBA86575C33FeFd7f379 -G --farm-recheck 200 --cl-local-work 256 --cl-global-work 8192
pause**
I have Geth --rpc --fast --cache 2048 running in the background.

**Comment by chfast** [comment]
Go https://github.com/ethereum-mining/ethminer.
