### ISSUE TITLE
ethminer stopped working

### ISSUE THREAD

**Issue by RavenZero** [ethereum/cpp-ethereum#4137]
I folowed the Solo Mining tutorial on etherbasics.
It all works until it finished building the DAG file.
After building it, or loading it when it is already built, ethminer crashes and tells me "ethminer stopped working". After that the batch closes without any other message why.
screenshot: http://imgur.com/a/BuxwN

Any ideas?

**Comment by chfast** [comment]
There is no ethminer here any more. Ask in https://github.com/ethereum-mining/ethminer.
