### ISSUE TITLE
Keccak.h is missing.

### ISSUE THREAD

**Issue by kryztoval** [ethereum/cpp-ethereum#4138]
I keep getting this after "make":
```
[  2%] Building CXX object libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o
[ 51%] Built target devcore
[ 51%] Built target BuildInfo.h
/opt/Packages/cpp-ethereum/libethash/sha3_cryptopp.cpp:25:29: fatal error: cryptopp/keccak.h: No such file or directory
 #include <cryptopp/keccak.h>
                             ^
compilation terminated.
libethash/CMakeFiles/ethash.dir/build.make:134: recipe for target 'libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o' failed
make[2]: *** [libethash/CMakeFiles/ethash.dir/sha3_cryptopp.cpp.o] Error 1
CMakeFiles/Makefile2:177: recipe for target 'libethash/CMakeFiles/ethash.dir/all' failed
make[1]: *** [libethash/CMakeFiles/ethash.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Any idea?

**Comment by chfast** [comment]
Can you do `make cryptopp`?

**Comment by axelsimon** [comment]
What's happening is `make` is looking for `keccak.h` in `/usr/lib/include/cryptopp` but it's not there, so it fails.

Here's a hack suggested to force it to not use the cryptopp libraries from `/usr/lib/include/cryptopp`:
https://github.com/Genoil/cpp-ethereum/issues/190#issuecomment-307375864

**Comment by kryztoval** [comment]
I'll try it. Or just get the precompuled binary. :(

**Comment by pwuertz** [comment]
Do not use the hack from https://github.com/Genoil/cpp-ethereum/issues/190#issuecomment-307375864. It completely breaks ethminer (without notice) because of a change in cryptopp 5.6.4 that was taken care of in #111. You have to manually add the missing header file `keccak.h` from the cryptopp source for compiling ethminer or manually update the debian package.

**Comment by axelsimon** [comment]
Thanks a lot @pwuertz for the warning!
If it can help others, to add the missing headier file `keccak.h` to cryptopp's available hashes, you can use wget: `sudo wget -O /usr/include/cryptopp/keccak.h https://github.com/weidai11/cryptopp/raw/master/keccak.h` on Debian (and probably derivatives like Ubuntu, Mint etc.).

I'm getting another error on compile now, but at least the keccak headers are there :)
