### ISSUE TITLE
"No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument" 

### ISSUE THREAD

**Issue by JRtoujours** [ethereum/cpp-ethereum#4144]
hi, i get the message about wenn I try to launch my bat file to ethereum mining. i have a 6gb video card and 12 gb ram so I guest it is enough. what can be the problem and how can I get around it. 
![unbenannt1](https://user-images.githubusercontent.com/28475974/27141992-08ffb3f8-512a-11e7-8fda-86f50d08f12f.JPG)
I am new at cryptocurrencies. thank you for the help!

**Comment by pilere** [comment]
ADD --opencl-platform 1
it try to use the internal video card not the external.

**Comment by chfast** [comment]
Go to https://github.com/ethereum-mining/ethminer for GPU mining solutions and support.

**Comment by MasterCATZ** [comment]
Thank you 

--opencl-platform 1

worked a treat I was wondering why this started happening after my on-board had been disabled
