### ISSUE TITLE
testeth --fillchain should by default use only one cpu core

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4150]
It does not make much sense to use all CPU cores for mining in `testeth --fillchain` because

* the initial blocktime can be regulated by changing the difficulty
* eventually the blocktime will converge to ten or twenty seconds

This issue keeps track of changing the default behavior of `testeth --fillchain` so that it only uses one CPU core for mining.

**Comment by winsvega** [comment]
the tests use minimum difficulty defined by the YP:  0x020000
so for the sake of tests we could either decrease the minimum difficulty to even smaller value and have tests mining faster or use some trick like you proposed with changing the unix time or something.

Pawel sugested to decrease minimum difficulty so he could create unit tests with mining for travis. 
 
the fact that it uses multiple cores when mining goes down to libethereum algos.  (outside of the test scope)

**Comment by pirapira** [comment]
This issue is about the libethereum algos.

**Comment by winsvega** [comment]
this line 
https://github.com/ethereum/cpp-ethereum/blob/develop/test/tools/libtesteth/TestHelper.cpp#L71
should solve the issue

**Comment by axic** [comment]
You mean it was fixed already?

**Comment by winsvega** [comment]
yes. just tried stExample -- --fillchain. only one core displays 100% load
