### ISSUE TITLE
No rule to make target '../deps/lib/libmpir.a'

### ISSUE THREAD

**Issue by moneroexamples** [ethereum/cpp-ethereum#4159]
The issue is based on this issue: https://github.com/moneroexamples/compile-cpp-ethereum-on-arch/issues/1

problem on arch/manjaro:

```
make[2]: *** No rule to make target '../deps/lib/libmpir.a', needed by 'rlp/rlp'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '../deps/lib/libmpir.a', needed by 'bench/bench'.  Stop.
make[2]: *** Waiting for unfinished jobs....
```

And this is copy and paste of the comment explaining how manually it can be fixed:

The problem is that `libmpir.a` is in `deps/lib64` rather than in `deps/lib`. So the compilation blows up as its looking for `libmpir.a` in wrong folder.

I will be making issues on cpp-ethereum about this  shortly. In the meantime, have to manually fix it:

edit file `~/cpp-ethereum/cmake/ProjectMPIR.cmake`

and change: 
```
set(MPIR_LIBRARY ${INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}mpir${CMAKE_STATIC_LIBRARY_SUFFIX})
```
into 

```
set(MPIR_LIBRARY ${INSTALL_DIR}/lib64/${CMAKE_STATIC_LIBRARY_PREFIX}mpir${CMAKE_STATIC_LIBRARY_SUFFIX})
```

and re-compile.

**Comment by mariouriarte** [comment]
Thank you, it helped me a lot

**Comment by SingingBush** [comment]
@moneroexamples thanks. after pulling the changes for #4115 I ran into this problem also. changing the cmake file was the last piece of the puzzle for compiling on Fedora 26.

**Comment by moneroexamples** [comment]
@SingingBush 

Glad it helped.
