### ISSUE TITLE
Testeth options --filltest and --filltests are confusing

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4165]
It seems that `testeth` has similarly named but different options `--filltest` and `--filltests`.  Is it reasonable to rename one of them?

**Comment by pirapira** [comment]
@winsvega what do you think?

**Comment by winsvega** [comment]
the old one which tries to read a json file could be removed. along with the --checktest 
so (--filltest  and --checktest)  could be removed
