### ISSUE TITLE
error in install_deps.cmake

### ISSUE THREAD

**Issue by ValMass** [ethereum/cpp-ethereum#4176]
Hi all,
I'm trynig to build cpp-ethereum from source for windows platform.
Following the istructions, i tried to launch the scripts/install_deps.bat, but the script cannot find the target file : cmake/scripts/install_deps.bat
I think you have to change the install_deps.bat from:
 cmake -P cmake\scripts\install_deps.cmake
to:
cmake -P ..\cmake\scripts\install_deps.cmake

Regards.

**Comment by chfast** [comment]
Yes, it depends on your working dir. What do you think of switching to using cmake directly?

**Comment by bpetridis** [comment]
You need to run it from the root of the of the code repository - I had the same problem as I was running it from the \scripts directory - wont't work from there. If you run it from the root of solidity-develop and have cmake installed t works fine.
