### ISSUE TITLE
windows install_deps fix

### ISSUE THREAD

**Issue by DreadnaughtSec** [ethereum/cpp-ethereum#4179]
\scripts\install_deps.bat needs to have ..\ added to the start of the path for it to work properly.

`cmake -P cmake\scripts\install_deps.cmake`
needs to be changed to 

`cmake -P ..\cmake\scripts\install_deps.cmake`

Changes work fine on win10 x64.

**Comment by PrimOox** [comment]
Hello, i've changed here but still doesn't work for me. Do I need to have CMake installation on the same drive?

**Comment by axic** [comment]
Duplicate #4176?
