### ISSUE TITLE
CPU mining race condition, deadlock, thread issue

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#4202]
When mining this still happens: mining function never finish it's job. 
Potentially at line 
https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/BlockQueue.cpp#L99

I've found out that this issue is likely to reproduce when mining with a lower difficulty like  
"difficulty" : "0x02"

also this opens an error at this line 
https://github.com/ethereum/cpp-ethereum/blob/develop/libethcore/BlockHeader.h#L151
 Error in `./testeth': double free or corruption (fasttop): 0x00007feee0000990 ***

**Comment by pirapira** [comment]
@winsvega how did you identify the problematic line in BlockQueue.cpp?  By experiment or by some reasoning?

**Comment by winsvega** [comment]
debugger attach. interupt. it goes into an endless loop around atomic variable condition

**Comment by chfast** [comment]
Try also using thread sanitizer. `cmake -DSTANITIZE=thread`.

**Comment by chfast** [comment]
Is this still relevant?

**Comment by winsvega** [comment]
@pirapira  did some work around deadlocks. should be working now.
