### ISSUE TITLE
Using CUDA with win10 and gtx970 lets the miner crash. Opencl works fine.

### ISSUE THREAD

**Issue by chross** [ethereum/cpp-ethereum#4207]
Hi,
I'm using the ethminer genoil version 1.1.7 on Win10 Pro Insider 16226 with the following options:
setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -X --allow-opencl-cpu --verbosity 4 -S eth-eu1.nanopool.org:9999 -FS etc-eu2.nanopool.org:19999 -O address.worker

I have a GTX970 with 4 GB VRAM using the NVIDIA driver 382.53 with "Optimize for compute performance" activated. Using opencl, the GPU yields around 20 Mh/s. Whenever I'm trying to use CUDA, the miner will crash.

Debugging using a Visual Studio trial says:
"Unhandled exception at 0x00007FF6BE9E6A2A in ethminer.exe: 0xC0000005: Access violation writing location 0x0000000000000000."

The log itself says:
"CUDA error in func 'ethash_cuda_miner::init' at line 243 : out of memory."

My system has got 32GB of RAM with plenty available when running the miner.

Any help is greatly appreciated as I want to combine CPU and GPU mining for more performance.

**Comment by chfast** [comment]
Ask there: https://github.com/ethereum-mining/ethminer.
