### ISSUE TITLE
testeth error message should be more informative when a filler JSON is malformed

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4211]
When I place a garbage byte in front of a filler file like
```
--- a/src/GeneralStateTestsFiller/stReturnDataTest/returndatacopy_initialFiller.json
+++ b/src/GeneralStateTestsFiller/stReturnDataTest/returndatacopy_initialFiller.json
@@ -1,4 +1,4 @@
-{
+n{
     "returndatacopy_initial" : {
         "env" : {
         "currentCoinbase" : "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba"
```

`testeth --filltest` complains
```
/home/yh/src/cpp-ethereum/test/tools/libtesteth/TestHelper.cpp(462): error: in "StateTestsGeneral/stReturnDataTest": n/a Failed filling test with Exception: value type is 6 not 0
```

but it should instead complain about malformed JSON.

**Comment by axic** [comment]
Please! :)

cc @winsvega @jwasinger

**Comment by winsvega** [comment]
currently it shows this kind of error if you place something before the json object. 
```
 /home/wins/Ethereum/tests/src/GeneralStateTestsFiller/stExample/add11Filler.json A GeneralStateTest file should contain an object.
```

Not all json field names are displayed when json object is incorrect. 
I suggest to add more debug info around .yml tests and develop new tests in .yml format.

**Comment by axic** [comment]
@jwasinger @lrettig have had these cryptic error messages last week. Can you please point to a sample which triggers it?

**Comment by winsvega** [comment]
ok. let me see around state tests where such thing could happen

**Comment by lrettig** [comment]
When I've gotten this error (`value type is 6 not 0`), it's not because of malformed JSON, per se, but rather because the JSON data does not match the expected format. I think this error has something to do with `testeth` expecting a list and getting a scalar.

**Comment by winsvega** [comment]
right. such error does not display the field key at the moment.

**Comment by pirapira** [comment]
Also the numbers 6 and 0 are cryptic.

**Comment by lrettig** [comment]
It would be very helpful to add that :)

**Comment by lrettig** [comment]
My best guess is that the numbers refer to this enum:

`obj_type, array_type, str_type, bool_type, int_type, real_type, null_type`

from https://github.com/ethereum/cpp-ethereum/blob/367a25d2af2355557cb0f52a87c3ea8ab33abb1c/utils/json_spirit/json_spirit_value.h#L26.

**Comment by pirapira** [comment]
Right, so, the messages should contain `obj, array, str, ...` instead of `0, 1, 2, ...`.

**Comment by jwasinger** [comment]
Ah so this is one of the reasons we have JSONSchema for tests and fillers.  Let me wrap up an existing PR which should cover the "expect" section for fillers and then it should be (somewhat more) comprehensive:

https://github.com/ethereum/tests/pull/367

**Comment by winsvega** [comment]
this check should be done in testeth. otherwise it is hard to see where the issue in a test filler.

**Comment by pirapira** [comment]
@winsvega  can you call @jwasinger's checker from `testeth`?

**Comment by winsvega** [comment]
I am working on a PR that would do better check of the test fillers while you run --filltests

**Comment by winsvega** [comment]
https://github.com/ethereum/cpp-ethereum/pull/4794

**Comment by winsvega** [comment]
implemented
