### ISSUE TITLE
Mining threads make Blockchain tests slow

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#4212]
seems like blockchain tests taking so long not because of mining but because of starting and closing threads
https://github.com/ethereum/cpp-ethereum/blob/develop/libdevcore/Worker.cpp#L93

the loop calls 
this_thread::sleep_for(chrono::milliseconds(20));  
203 times

could we make it faster?

**Comment by gumb0** [comment]
where is that loop and sleep?

**Comment by winsvega** [comment]
sorry, fixed the link

**Comment by chfast** [comment]
Is this still an issue?

**Comment by winsvega** [comment]
added some fixes around threads regarding this issue.
it is better now. up to 1 second  faster per chain params reset in the test.
but sill could be even more better
