### ISSUE TITLE
Rename test cases with `SUICIDE` into `SELFDESTRUCT`

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4213]
Since the LLL compiler has already made the rename, the code in the test filler files already contain the new nmemonic `SELFDESTRUCT`.  This issue keeps track of renaming the filler files and the test names so that they contain the new name `SELFDESTRUCT` instead of the old name `SUICIDE`.

**Comment by winsvega** [comment]
do we have such tests left? I remember changing it.
