### ISSUE TITLE
testeth --fillchain --filltests should not modify the GeneralStateTest

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4258]
The command `testeth --fillchain --filltests` is for translating a GeneralStateTest into a BlockChainTest.  This command currently modifies the GeneralStateTest.  However, it should only write to the BlockChainTest file, not to the GeneralStateTest file.

**Comment by winsvega** [comment]
currently this command fills both GeneralStateTest and BlockchainTest out of the source.

**Comment by pirapira** [comment]
Right.  There was a change.

**Comment by winsvega** [comment]
the issue was that this command deleted general tests content because test was filled in the same json object. you changed that logic so now a new json object is being created
