### ISSUE TITLE
Build error - failing CMake @ "boost-build-Debug.cmake " - for windows 

### ISSUE THREAD

**Issue by BlockBit** [ethereum/cpp-ethereum#4271]
Doing build on the Windows - stuck with following error.

Here is the log .

Performing configure step for 'boost'
-- boost configure command succeeded. See also GitHub/cpp-ethereum/deps/src/boost-stamp/boost-configure-*.log
Performing build step for 'boost'
**CMake Error at GitHub/cpp-ethereum/deps/src/boost-stamp/boost-build-Debug.cmake:16 (message):
Command failed: 1

 'b2.exe' '--ignore-site-config' 'stage' 'threading=multi' 'link=static' 'variant=release' 'address-model=64' '--with-chrono' '--with-date_time' '--with-filesystem' '--with-random' '--with-regex' '--with-test' '--with-thread' '--with-program_options'**
Boost-build-out.log have following additional info

GitHub/cpp-ethereum/deps/src/boost/tools/build/src/tools\msvc.jam:834: in generate-setup-cmd
*** argument error

rule maybe-rewrite-setup ( toolset : setup-script : setup-options : version : rewrite-setup ? )
called with: ( msvc : : : default : )
missing argument setup-script
GitHub/cpp-ethereum/deps/src/boost/tools/build/src/tools\msvc.jam:746:see definition of rule 'maybe-rewrite-setup' being called

**Comment by chfast** [comment]
We switched to Hunter.
