### ISSUE TITLE
Cmake build failed Windows 10 @ CMakeLists.txt:47

### ISSUE THREAD

**Issue by himrasmussen** [ethereum/cpp-ethereum#4272]
A:\Dropbox\dokumenter\cpp-ethereum-develop\build>cmake ..
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:47 (message):
  Git submodules not initialized, execute:

    git submodule update --init

-- Configuring incomplete, errors occurred!
See also "A:/Dropbox/dokumenter/cpp-ethereum-develop/build/CMakeFiles/CMakeOutput.log".

CMakeOutput.log here (cmd admin):            https://pastebin.com/EkRZTni2
CMakeOutput.log here (powershell admin):  https://pastebin.com/qA4pkcBH
Both  Powershell and Cmd with and without running as admin result in error.

**Comment by chfast** [comment]
Did you do `git submodule update --init` as reported in the error message?

**Comment by himrasmussen** [comment]
@chfast I didn't. I abandoned the project though.
