### ISSUE TITLE
testeth --filltests should remove fields starting from "//"

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4309]
For instance, when a filler file contains
```
"//comment1" : "something",
"//comment2" : "something"
```
these fields should not be copied into the filled test files.

**Comment by winsvega** [comment]
yes this might be a solution for unneeded comments in the final tests.

**Comment by ars860** [comment]
Hello. Is this problem already solved?

**Comment by winsvega** [comment]
yes. fields starting with // are removed first. then the test is filled
