### ISSUE TITLE
A new empty account in Byzantium poststate

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4362]
`testeth` filling creates an empty account and leaves it in the postState.  This should not happen on the Byzantium network (or anywhere after the EIP158 changes) but `testeth` does that on Byzantium.

https://github.com/ethereum/tests/blob/develop/BlockchainTests/bcWalletTest/wallet2outOf3txsRevoke.json#L284
```
       "postState" : {
            "0x00000000000000000000000000000000000000f0" : {
                "balance" : "0x00",
                "code" : "",
                "nonce" : "0x00",
                "storage" : {
                }
       },
```

**Comment by pirapira** [comment]
@winsvega any idea?

**Comment by winsvega** [comment]
hmm. that's strange. something in Byzantine and this contract make this empty contract.

**Comment by pirapira** [comment]
I'm trying to fill the test now.

**Comment by pirapira** [comment]
I'm filling the test with
```
 ETHEREUM_TEST_PATH='../../tests' nice test/testeth -t 'BlockchainTests/bcWalletTest' -- --singletest wallet2outOf3txsRevoke --filltests --all
```
Notice the last `--all`.  It took a bit to figure this out.

**Comment by pirapira** [comment]
Filling it again solves the problem.

I find the same problem in other files in the same directory.  Also filling them.

**Comment by pirapira** [comment]
This was not a `cpp-ethereum` problem.

**Comment by winsvega** [comment]
not cpp?  I gues at some point there was an issue and test was filled wrong. but not anymore

**Comment by pirapira** [comment]
not cpp because `testeth` could fill the tests differently.

**Comment by winsvega** [comment]
what you mean? there was a bug in testeth leading to an empty accont?

**Comment by pirapira** [comment]
When I opened this issue, there was no bug in `testeth` causing the empty account.
