### ISSUE TITLE
Travis should fill some tests with testeth --filltests

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4369]
Currently, `testeth --filltests` is not tested in Travis builds.  This leads to issues like #4365.

**Comment by jwasinger** [comment]
@pirapira  I took a look at this one.  Looks like we need to add steps to Travis that runs `testeth -- --filltests` and then run schema linting against the resulting filled tests?

**Comment by pirapira** [comment]
Yes.  Filling the whole test suite will take too much time, so I was thinking about running just
```
testeth -t StateTestsGeneral/stExample -- --filltests
```
and
```
testeth -t BlockchainTests -- --singletest <some short filler file>
```
during the Travis build.

**Comment by jwasinger** [comment]
Adding schemas for blockchain tests and fillers is the next step.

**Comment by pirapira** [comment]
This was done in #4387.
