### ISSUE TITLE
Shall we remove --inputlimits option and instead use --all?

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4393]
Currently, `testeth --inputlimits` runs vmInputLimitTest but `testeth` does not.  Maybe we can use `-t 'VMTests/vmInputLimitTest' --all` instead of this option.

**Comment by pirapira** [comment]
@winsvega what do you think?

**Comment by winsvega** [comment]
yes I think we could remove those special flags. 
like wallet memory perfomance quadratic. 

do not forget to add a warning if those conditions are not meet and test is skipped.
https://github.com/ethereum/cpp-ethereum/pull/4367
