### ISSUE TITLE
Too much gas consumption during address collision?

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4405]
@karalabe reports https://github.com/ethereum/pm/issues/21#issuecomment-324863680 that the consensus test suite assumes too much gas consumption in case of address collision.  This needs to be investigated.

**Comment by karalabe** [comment]
No, as I've updated, and also wrote on gitter, it was a bug in my code. I just falsely misinterpreted the result.

**Comment by pirapira** [comment]
Thanks for the update!
