### ISSUE TITLE
libethashseal subfolders dissapear with cmake configuration

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#4411]
smth has changed and now cmake does not configure subfolders of ethashseal to be listed in qtcreator

**Comment by chfast** [comment]
Yes, because these files are included directly by GenesisInfo.cpp, so I cannot add them to the library without being compiled twice.

**Comment by axic** [comment]
Is this a problem? Should anything be changed?

**Comment by winsvega** [comment]
not really. just annoying that qt-creator does not display those folders in project view.
