### ISSUE TITLE
testeth -t GeneralStateTests --filltests --fillchain shows some errors

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4413]
On 7b8143d38e47e5d20067934c32007e9c33d82507 with `ethereum/tests:1d30b4795664f64b1b157971754e14a10cfd9115`, when I run

```
test/testeth -t StateTestsGeneral -- --filltests --fillchain &> fillchain.out
```

I see errors.  Most urgently, I see errors on the Frontier network.
* [x] `/home/ubuntu/yoichi/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(483): error: in "StateTestsGeneral/stRefundTest": refund600_d0g0v0_Frontier Check State: 2adc25665018aa1fe0e6bc666dac8fc2697ff9ba: incorrect balance 5000000000000038105, expected 5000000000000038050 refund600_d0g0v0_Frontier`  https://github.com/ethereum/tests/pull/280 solves it
* [x] `/home/ubuntu/yoichi/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(483): error: in "StateTestsGeneral/stRefundTest": refund50percentCap_d0g0v0_Frontier Check State: 2adc25665018aa1fe0e6bc666dac8fc2697ff9ba: incorrect balance 5000000000000045600, expected 5000000000000045545
refund50percentCap_d0g0v0_Frontier` I cannot reproduce the issue anymore https://github.com/ethereum/tests/pull/281
* [x] `/home/ubuntu/yoichi/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(494): error: in "StateTestsGeneral/stEIP150singleCodeGasPrices": RawBalanceGas_d0g0v0_Frontier Check State: b94f5374fce5edbc8e2a8697c15331677e6ebf0b: incorrect storage [0x01] = 0x088778, expected [0x01] = 0x088791
RawBalanceGas_d0g0v0_Frontier` I cannot reproduce this locally.
* [ ] `/home/ubuntu/yoichi/cpp-ethereum/test/tools/libtesteth/ImportTest.cpp(494): error: in "StateTestsGeneral/stTransactionTest": zeroSigTransactionOrigin_d0g0v0_Constantinople Check State: 1000000000000000000000000000000000000000: incorrect storage [0x] = 0x, expected [0x] = 0xffffffffffffffffffffffffffffffffffffffff
zeroSigTransactionOrigin_d0g0v0_Constantinople`

**Comment by pirapira** [comment]
It looks like the fillers were mistakenly modified in this commit https://github.com/ethereum/tests/commit/613bb864dc25045169e7fc58b3d138ff13eb66bf#diff-8ed59e530097cdd9a8466261432001afR26

**Comment by winsvega** [comment]
if you see small gas changes it could be due to the solidity lllc compiles it differently (if there any solidity code in the tests)

**Comment by pirapira** [comment]
@winsvega that could be the case.  I saw the error on the server, but I don't see it locally.

**Comment by pirapira** [comment]
The remaining Constantinople issue should be https://github.com/ethereum/cpp-ethereum/issues/4299
