### ISSUE TITLE
MaxAddress should be checked only on transaction and only on Constantinople

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#4461]
Check for sender is here
https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/Executive.cpp#L332

and here
https://github.com/ethereum/cpp-ethereum/blob/develop/libethereum/Executive.cpp#L256

those rules should be applied only for transaction creation. and only if a constantinople rules are enabled.
and we have a case here when   MaxAddress is an account that does a create. what YP says about that situation?

**Comment by pirapira** [comment]
YP says nothing special about the max address.  I agree this is a bug.

**Comment by pirapira** [comment]
I think I can pick this one in 11 weeks.

**Comment by winsvega** [comment]
I'll fix the bug eralier. so cpp wont produce the same test error again.

**Comment by pirapira** [comment]
@winsvega which test is failing?

**Comment by winsvega** [comment]
https://github.com/ethereum/tests/pull/304/files#diff-58312ae074ea63512b1cfbd19524f434R4

**Comment by pirapira** [comment]
OK.  Thanks.
