### ISSUE TITLE
feature request: cmake flag to set EVM_OPTIMIZE=false

### ISSUE THREAD

**Issue by cdetrio** [ethereum/cpp-ethereum#4475]
This is needed to support standardized tracing.  Without a cmake flag, the code needs to be patched as done [here](https://github.com/cdetrio/cpp-ethereum/commit/7154c17542034031bcb56c9fb90089c2d4139428#diff-11510de5169187b42a8e4bb8ae298582R64).

See also  https://github.com/ethereum/tests/issues/249

**Comment by axic** [comment]
Is this still the case?

**Comment by holiman** [comment]
This is still the case, yes. I tried using `-DEVM_OPTIMIZE=0`, but no luck.

**Comment by chfast** [comment]
Resolved in https://github.com/ethereum/cpp-ethereum/pull/4883.

**Comment by chfast** [comment]
Sorry it took so long.
