### ISSUE TITLE
Missing DLL libmicrohttpd-dll.dll

### ISSUE THREAD

**Issue by jkbrasch7303** [ethereum/cpp-ethereum#4484]
I followed the build instructions on http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html, and I used the command line to build the program like it says at the end of the article. I also tried to build the program manually from Visual Studio 2015, and I get the same result. I run Windows 10, Visual Studio 2015 Community with Windows 10 SDK, and CMake 3.9.1. When run cpp-ethereum/build/eth/RelWithDebInfo/eth.exe, I get the error message "The code execution cannot proceed because libmicrohttpd-dll.dll was not found. Reinstalling the program may fix this problem." I did run scripts\install_deps.bat before running cmake like it says in the build instructions.

**Comment by jkbrasch7303** [comment]
The file was inside deps\x64\bin. I copied and pasted the file the the build\eth directory and it worked.

**Comment by gumb0** [comment]
Yes, copying or adding to PATH should help with this
