### ISSUE TITLE
RFC: Changes to testeth (TestEthereum)

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#449]
### Test tree

Boost.Test places tests in a tree structure where test cases (TC) are leafs and test suites (TS) are branches. Tests to run can be filtered, i.e. `-t "vm/*/*push*"`

### JSON tests

1. Test engine should load all tests from all JSON files in test-dir
2. JSON file path defines test suites (`test-dir/vm/memory/load.json`: `TS(vm) -> TS(memory) -> TS(load)`)
3. Every test in JSON file is separated Test Case.

### Namings

Names should be shorter than current ones (`vmtests/vmIOandFlowOperationsTest.json` could be `vm/io.json` and `vm/flow.json`)

### Command line options

1. If no additional options load tests from `ETHEREUM_TEST_PATH` and built-in tests
2. If path to directory provided load tests form this directory
3. If path to JSON file provided load tests from this file

**Comment by debris** [comment]
@chfast @CJentzsch can we close this issue?

**Comment by chfast** [comment]
I'm still thinking about implementing better test filtering for testeth and probably will do sooner or later. But if you are cleaning up the issue list, I'm ok with shutting it down.
