### ISSUE TITLE
genesis configuration parsing should fail when there is an unknown field

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4514]
There was a misspelled option "startBlock" in many genesis configuration files: https://github.com/ethereum/cpp-ethereum/pull/4513

In order to detect these at least at runtime, the genesis configuration parsing should fail when it sees an unknown field.

**Comment by gumb0** [comment]
Also invalid JSON should fail, it somehow still works now when there's comma missing in object
