### ISSUE TITLE
libfuzzer-friendly GeneralStateTest generation

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4515]
Currently, `test/tools/fuzzTesting` can randomly generate a GeneralStateTest.

This issue keeps track of replacing the randomly generated numbers with some input byte string (given at runtime) so that `libfuzzer` can explore the VM implementation.

Concretely, the task involves implementing a function
```
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size)
```
that generates a GeneralStateTest and then run it.  The input `Data` should be used in a straightforward way (not going through compression/encryption/decryption).  The whole function should be deterministic, without relying on pseudo random numbers or timestamps.

When we connect `libfuzzer` with this function, `libfuzzer` will try to find inputs that cover different execution paths in the VM implementation.

**Comment by winsvega** [comment]
so we need to timplement LLVMFuzzerTestOneInput function in testeth which would take  array of uint8_t as data and parse it into general state test which would then be executed. 
what is the return int value means?

**Comment by pirapira** [comment]
@winsvega the return value is not useful.  Currently only zero is supported, or something like that.  You can throw an exception to indicate an error.  The most interesting data is the code coverage, which is collected by the libfuzzer instrumentation `cmake -DSANITIZE=fuzzer` .  After a nights execution, the `CORPUS` directory will contain hundreds of bytestrings that translate to interesting GeneralStateTests.

**Comment by winsvega** [comment]
what would be the entry point with libfuzzer?

**Comment by pirapira** [comment]
`libfuzzer` contains the `main()` function.  When you link something with `libfuzzer`, `libfuzzer`'s `main()` will be the entry point.

**Comment by winsvega** [comment]
I wonder how boost would work if the entry point is different

**Comment by pirapira** [comment]
No idea.  In the worst case, we introduce another macro.

**Comment by winsvega** [comment]
Guido does not want to use testeth randomtest generator for smart random state tests

**Comment by pirapira** [comment]
OK.
