### ISSUE TITLE
Redefine byte

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#4598]
Redefine `dev::byte` as `enum class byte: unsigned char {};` to map `std::byte` from C++17.

**Comment by rutayanp** [comment]
i am a newbie in etherum blockchain and open source but an experienced c programmer. Should I try fixing this ?

**Comment by rutayanp** [comment]
I am new to blockchain but proficient c developer. May I take this one ?

**Comment by chfast** [comment]
Yes. Please take it @rutayanp.

The replacing definition should be simple. Then you will have to fix compiler warnings and errors if any. If there will be a lot of them let us know.

**Comment by chfast** [comment]
Any progress on this?

**Comment by rutayanp** [comment]
I was able to clone cpp-ethereum and build it on my windows machine but haven't worked on this yet. I was targeting the weekend for this :)

**Comment by rutayanp** [comment]
@chfast I apologise for the thrash...my "cmake --build . " step failed and I did not spend time on this. I don't want to hinder the work. If anyone else wants to take it, I will be fine with it. :) 

I again apologise for the thrash. :(

**Comment by cogle** [comment]
I can try building and taking a look at this, tonight.

**Comment by chfast** [comment]
C++17 introduces `std::byte` as `enum class byte : unsigned char {} ;`
http://en.cppreference.com/w/cpp/types/byte 

@rutayanp don't worry. We just need to know the current progress to avoid duplicated efforts.
@cogle, yes, please give it a try.

Also please come to https://gitter.im/ethereum/cpp-ethereum-development if you'd like to discuss anything.

**Comment by lazyGoose** [comment]
Anyone still on this? I can take it over.

**Comment by chfast** [comment]
@rutayanp are you working on this?

**Comment by chfast** [comment]
Assigned to @lazyGoose.

**Comment by LoveULin** [comment]
hi, I redefined `<dev::byte>` as `<enum class byte: unsigned char {};`> in libdevcore/Common.h simply.I tried to build, and then found so many errors. (There was no errors or warnings before this modification, and the branch I used was develop)

Should I create a new file and add the std::byte supported functions in C++17 to make the compilation OK??

**Comment by chfast** [comment]
This requires a lot of code changes. Probably not worth it. It will be hard to finish this by external contributors.

**Comment by LoveULin** [comment]
OK, I got it.I'll try some other issues :D

**Comment by lazyGoose** [comment]
I'm able to compile the new codebase with refined byte, but some tests failed. I'm trying to fix those bugs in test cases. Let me know if someone else is already taking care of this issue.
