### ISSUE TITLE
CMake Error: Error processing file: cmake\scripts\install_deps.cmake

### ISSUE THREAD

**Issue by AmaalK** [ethereum/cpp-ethereum#4601]
I am trying to set up my ethereum c++ client on Windows.

I already ran this command line

`git clone --recursive https://github.com/ethereum/cpp-ethereum.git`
which successfully worked. 
Now, in the second step, I opened my command prompt, and I went into the directory that contains the scripts folder in the cpp-ethereum directory, and typed `install_deps.bat`
where I found this error 

CMake Error: Error processing file: cmake\scripts\install_deps.cmake

What am I doing wrong? I never used cmake before, so I have no clue..

**Comment by gumb0** [comment]
Try to run it from the directory above (cpp-ethereum) like `scripts\install_deps.bat`

**Comment by AmaalK** [comment]
@gumb0, I did but it didn't work. Someone advised me to switch to the master branch, which I did.
And, the CMake file was found successfully, however, now I have a new error
```
ERROR FILE:    https://build.ethdev.com/builds/windows-precompiled/boost-1.55.0
ERROR CODE:    0x80072efd - A connection with the server could not be establish
ERROR CONTEXT: 0x00000005 - The error occurred while the remote file was being
```

**Comment by gumb0** [comment]
master branch is long abandoned, build from default `develop` branch
