### ISSUE TITLE
CMake: Build errors if project path contains spaces

### ISSUE THREAD

**Issue by JohnnyGlobe** [ethereum/cpp-ethereum#4602]
hi everyone

I am trying to build ethereum on elementry OS following this guide: https://github.com/ethereum/cpp-ethereum/, when i get to the step "cmake --build ." I keep running into this error:

[ 5%] Completed 'jsonrpccpp'
[ 6%] Built target jsonrpccpp
[ 9%] Built target mpir
[ 12%] Built target snark
/bin/sh: 1: Syntax error: Unterminated quoted string
CMakeFiles/BuildInfo.h.dir/build.make:57: recipe for target 'CMakeFiles/BuildInfo.h' failed
make[2]: [CMakeFiles/BuildInfo.h] Error 2
CMakeFiles/Makefile2:247: recipe for target 'CMakeFiles/BuildInfo.h.dir/all' failed
make[1]: [CMakeFiles/BuildInfo.h.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: * [all] Error 2

I cant seem to find online what the cause is, any ideas?
thanks!

**Comment by chfast** [comment]
I have no idea what's going on there, but can you do `ls -l /bin/sh`?

**Comment by JohnnyGlobe** [comment]
Thanks for the reply chfast!
I get this from doing ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jul 14 22:24 /bin/sh -> dash

**Comment by chfast** [comment]
Please try following commands to give us more information:

1. In build dir do `make BuildInfo.h VERBOSE=1`
2. `cat CMakeCache.txt`
3. Do you by chance have you spaces in the project dir path?

**Comment by JohnnyGlobe** [comment]
It looks like BuildInfo.h was not generated... it is not in the build directory

No I do not have spaces

By doing cat CMakeCache.txt i get:

# This is the CMakeCache file.
# For build in directory: /home/john/John's Linux Folder/cpp-ethereum/build
# It was generated by CMake: /usr/local/bin/cmake
# You can edit this file to change values found and used by cmake.
# If you do not want to change any of the values, simply exit the editor.
# If you do want to change a value, simply edit, save, and exit the editor.
# The syntax for the file is as follows:
# KEY:TYPE=VALUE
# KEY is the name of a variable in the cache.
# TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
# VALUE is the current value for the KEY.

########################
# EXTERNAL cache entries
########################

//Build project libraries shared
BUILD_SHARED_LIBS:BOOL=OFF

//The directory containing a CMake configuration file for Boost.
Boost_DIR:PATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/cmake/Boost

//Boost filesystem library (debug)
Boost_FILESYSTEM_LIBRARY_DEBUG:FILEPATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/libboost_filesystem-mt-d.a

//Boost filesystem library (release)
Boost_FILESYSTEM_LIBRARY_RELEASE:FILEPATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/libboost_filesystem-mt.a

//Path to a file.
Boost_INCLUDE_DIR:PATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/include

//Boost library directory DEBUG
Boost_LIBRARY_DIR_DEBUG:PATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib

//Boost library directory RELEASE
Boost_LIBRARY_DIR_RELEASE:PATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib

//Boost system library (debug)
Boost_SYSTEM_LIBRARY_DEBUG:FILEPATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/libboost_system-mt-d.a

//Boost system library (release)
Boost_SYSTEM_LIBRARY_RELEASE:FILEPATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/libboost_system-mt.a

//Boost thread library (debug)
Boost_THREAD_LIBRARY_DEBUG:FILEPATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/libboost_thread-mt-d.a

//Boost thread library (release)
Boost_THREAD_LIBRARY_RELEASE:FILEPATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/libboost_thread-mt.a

//ccache tool path; set to OFF to disable
CCACHE:FILEPATH=CCACHE-NOTFOUND

//Path to a program.
CMAKE_AR:FILEPATH=/usr/bin/ar

//Build type on single-configuration generators
CMAKE_BUILD_TYPE:STRING=RelWithDebInfo

//Enable/Disable color output during build.
CMAKE_COLOR_MAKEFILE:BOOL=ON

//CXX compiler
CMAKE_CXX_COMPILER:FILEPATH=/usr/bin/c++

//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=

//Flags used by the compiler during debug builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=-g

//Flags used by the compiler during release builds for minimum
// size.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

//Flags used by the compiler during release builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the compiler during release builds with debug info.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG

//C compiler
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc

//Flags used by the compiler during all build types.
CMAKE_C_FLAGS:STRING=

//Flags used by the compiler during debug builds.
CMAKE_C_FLAGS_DEBUG:STRING=-g

//Flags used by the compiler during release builds for minimum
// size.
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

//Flags used by the compiler during release builds.
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the compiler during release builds with debug info.
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG

//Flags used by the linker.
CMAKE_EXE_LINKER_FLAGS:STRING=

//Flags used by the linker during debug builds.
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during release minsize builds.
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during release builds.
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during Release with Debug Info builds.
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Enable/Disable output of compile commands during generation.
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=OFF

//user executables (bin)
CMAKE_INSTALL_BINDIR:PATH=bin

//read-only architecture-independent data (DATAROOTDIR)
CMAKE_INSTALL_DATADIR:PATH=

//read-only architecture-independent data root (share)
CMAKE_INSTALL_DATAROOTDIR:PATH=share

//documentation root (DATAROOTDIR/doc/PROJECT_NAME)
CMAKE_INSTALL_DOCDIR:PATH=

//C header files (include)
CMAKE_INSTALL_INCLUDEDIR:PATH=include

//info documentation (DATAROOTDIR/info)
CMAKE_INSTALL_INFODIR:PATH=

//object code libraries (lib)
CMAKE_INSTALL_LIBDIR:PATH=lib

//program executables (libexec)
CMAKE_INSTALL_LIBEXECDIR:PATH=libexec

//locale-dependent data (DATAROOTDIR/locale)
CMAKE_INSTALL_LOCALEDIR:PATH=

//modifiable single-machine data (var)
CMAKE_INSTALL_LOCALSTATEDIR:PATH=var

//man documentation (DATAROOTDIR/man)
CMAKE_INSTALL_MANDIR:PATH=

//C header files for non-gcc (/usr/include)
CMAKE_INSTALL_OLDINCLUDEDIR:PATH=/usr/include

//Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=/usr/local

//system admin executables (sbin)
CMAKE_INSTALL_SBINDIR:PATH=sbin

//modifiable architecture-independent data (com)
CMAKE_INSTALL_SHAREDSTATEDIR:PATH=com

//read-only single-machine data (etc)
CMAKE_INSTALL_SYSCONFDIR:PATH=etc

//Path to a program.
CMAKE_LINKER:FILEPATH=/usr/bin/ld

//Path to a program.
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make

//Flags used by the linker during the creation of modules.
CMAKE_MODULE_LINKER_FLAGS:STRING=

//Flags used by the linker during debug builds.
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during release minsize builds.
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during release builds.
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during Release with Debug Info builds.
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Path to a program.
CMAKE_NM:FILEPATH=/usr/bin/nm

//Path to a program.
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy

//Path to a program.
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump

//Value Computed by CMake
CMAKE_PROJECT_NAME:STATIC=cpp-ethereum

//Path to a program.
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib

//Flags used by the linker during the creation of dll's.
CMAKE_SHARED_LINKER_FLAGS:STRING=

//Flags used by the linker during debug builds.
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during release minsize builds.
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during release builds.
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during Release with Debug Info builds.
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//If set, runtime paths are not added when installing shared libraries,
// but are added when building.
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO

//If set, runtime paths are not added when using shared libraries.
CMAKE_SKIP_RPATH:BOOL=NO

//Flags used by the linker during the creation of static libraries.
CMAKE_STATIC_LINKER_FLAGS:STRING=

//Flags used by the linker during debug builds.
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during release minsize builds.
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during release builds.
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during Release with Debug Info builds.
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Path to a program.
CMAKE_STRIP:FILEPATH=/usr/bin/strip

//The CMake toolchain file
CMAKE_TOOLCHAIN_FILE:FILEPATH=/home/john/John's Linux Folder/cpp-ethereum/cmake/toolchain.cmake

//If this value is on, makefiles will be generated without the
// .SILENT directive, and all commands will be echoed to the console
// during the make.  This is useful for debugging only. With Visual
// Studio IDE projects all commands are done without /nologo.
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE

//Path to the root directory for cpp-ethereum
CPP_ETHEREUM_DIR:PATH=/home/john/John's Linux Folder/cpp-ethereum

//Path to a program.
CTEST_COMMAND:FILEPATH=/usr/local/bin/ctest

//The path to the cmake directory
ETH_CMAKE_DIR:PATH=/home/john/John's Linux Folder/cpp-ethereum/cmake

//Build with EVMJIT module enabled
EVMJIT:BOOL=Off

//Enable fast ctest
FASTCTEST:BOOL=OFF

//Enable fat state database
FATDB:BOOL=ON

//Enable Hunter package manager support
HUNTER_ENABLED:BOOL=ON

//Print a lot info
HUNTER_STATUS_DEBUG:BOOL=OFF

//Print working status
HUNTER_STATUS_PRINT:BOOL=ON

//leveldb include dir
LEVELDB_INCLUDE_DIR:PATH=/usr/include

//leveldb library
LEVELDB_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libleveldb.so

//microhttpd include dir
MHD_INCLUDE_DIR:PATH=/usr/include

//microhttpd library
MHD_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libmicrohttpd.so

//Build with UPnP support
MINIUPNPC:BOOL=OFF

//Enable additional checks when validating transactions (deprecated)
PARANOID:BOOL=OFF

//Enable profiling (deprecated)
PROFILING:BOOL=OFF

//Path to a program.
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python

//Build with RocksDB instead of LevelDB
ROCKSDB:BOOL=OFF

//The directory containing a CMake configuration file for Snappy.
Snappy_DIR:PATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/cmake/Snappy

//Testeth arguments for ctest tests
TESTETH_ARGS:STRING=

//Build with tests
TESTS:BOOL=ON

//Build additional tools
TOOLS:BOOL=ON

//Use GNU gold linker
USE_LD_GOLD:BOOL=ON

//Enable VM tracing
VMTRACE:BOOL=OFF

//Value Computed by CMake
cpp-ethereum_BINARY_DIR:STATIC=/home/john/John's Linux Folder/cpp-ethereum/build

//Value Computed by CMake
cpp-ethereum_SOURCE_DIR:STATIC=/home/john/John's Linux Folder/cpp-ethereum

//The directory containing a CMake configuration file for cryptopp.
cryptopp_DIR:PATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/cmake/cryptopp

//Dependencies for the target
devcore_LIB_DEPENDS:STATIC=general;Boost::filesystem;general;Boost::system;general;Boost::thread;general;/usr/lib/x86_64-linux-gnu/libleveldb.so;

//Dependencies for the target
devcrypto_LIB_DEPENDS:STATIC=general;devcore;general;Secp256k1;general;Snark;general;cryptopp-static;general;scrypt;

//Dependencies for target
ethash_LIB_DEPENDS:STATIC=

//Dependencies for the target
ethashseal_LIB_DEPENDS:STATIC=general;ethereum;general;ethcore;general;ethash;

//Dependencies for the target
ethcore_LIB_DEPENDS:STATIC=general;devcrypto;general;devcore;

//Dependencies for the target
ethereum_LIB_DEPENDS:STATIC=general;evm;general;ethcore;general;p2p;general;devcrypto;general;devcore;general;jsoncpp_lib_static;general;Snappy::snappy;

//Dependencies for the target
evm_LIB_DEPENDS:STATIC=general;ethcore;general;devcore;general;jsoncpp_lib_static;

//The directory containing a CMake configuration file for jsoncpp.
jsoncpp_DIR:PATH=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib/cmake/jsoncpp

//Dependencies for the target
p2p_LIB_DEPENDS:STATIC=general;devcrypto;general;devcore;

//Dependencies for target
scrypt_LIB_DEPENDS:STATIC=

//Dependencies for the target
web3jsonrpc_LIB_DEPENDS:STATIC=general;ethashseal;general;webthree;general;whisper;general;JsonRpcCpp::Server;

//Dependencies for the target
webthree_LIB_DEPENDS:STATIC=general;ethereum;general;whisper;general;p2p;general;devcore;

//Dependencies for the target
whisper_LIB_DEPENDS:STATIC=general;p2p;general;devcrypto;general;devcore;


########################
# INTERNAL cache entries
########################

//ADVANCED property for variable: Boost_FILESYSTEM_LIBRARY_DEBUG
Boost_FILESYSTEM_LIBRARY_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_FILESYSTEM_LIBRARY_RELEASE
Boost_FILESYSTEM_LIBRARY_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_INCLUDE_DIR
Boost_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_LIBRARY_DIR_DEBUG
Boost_LIBRARY_DIR_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_LIBRARY_DIR_RELEASE
Boost_LIBRARY_DIR_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_SYSTEM_LIBRARY_DEBUG
Boost_SYSTEM_LIBRARY_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_SYSTEM_LIBRARY_RELEASE
Boost_SYSTEM_LIBRARY_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_THREAD_LIBRARY_DEBUG
Boost_THREAD_LIBRARY_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_THREAD_LIBRARY_RELEASE
Boost_THREAD_LIBRARY_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_AR
CMAKE_AR-ADVANCED:INTERNAL=1
//This is the directory where this CMakeCache.txt was created
CMAKE_CACHEFILE_DIR:INTERNAL=/home/john/John's Linux Folder/cpp-ethereum/build
//Major version of cmake used to create the current loaded cache
CMAKE_CACHE_MAJOR_VERSION:INTERNAL=3
//Minor version of cmake used to create the current loaded cache
CMAKE_CACHE_MINOR_VERSION:INTERNAL=7
//Patch version of cmake used to create the current loaded cache
CMAKE_CACHE_PATCH_VERSION:INTERNAL=1
//ADVANCED property for variable: CMAKE_COLOR_MAKEFILE
CMAKE_COLOR_MAKEFILE-ADVANCED:INTERNAL=1
//Path to CMake executable.
CMAKE_COMMAND:INTERNAL=/usr/local/bin/cmake
//Path to cpack program executable.
CMAKE_CPACK_COMMAND:INTERNAL=/usr/local/bin/cpack
//Path to ctest program executable.
CMAKE_CTEST_COMMAND:INTERNAL=/usr/local/bin/ctest
//ADVANCED property for variable: CMAKE_CXX_COMPILER
CMAKE_CXX_COMPILER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS
CMAKE_CXX_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_DEBUG
CMAKE_CXX_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_MINSIZEREL
CMAKE_CXX_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_RELEASE
CMAKE_CXX_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_CXX_FLAGS_RELWITHDEBINFO
CMAKE_CXX_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_COMPILER
CMAKE_C_COMPILER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS
CMAKE_C_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS_DEBUG
CMAKE_C_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS_MINSIZEREL
CMAKE_C_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS_RELEASE
CMAKE_C_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_FLAGS_RELWITHDEBINFO
CMAKE_C_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//Path to cache edit program executable.
CMAKE_EDIT_COMMAND:INTERNAL=/usr/local/bin/ccmake
//Executable file format
CMAKE_EXECUTABLE_FORMAT:INTERNAL=ELF
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS
CMAKE_EXE_LINKER_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_DEBUG
CMAKE_EXE_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_MINSIZEREL
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_RELEASE
CMAKE_EXE_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_EXPORT_COMPILE_COMMANDS
CMAKE_EXPORT_COMPILE_COMMANDS-ADVANCED:INTERNAL=1
//Name of external makefile project generator.
CMAKE_EXTRA_GENERATOR:INTERNAL=
//Name of generator.
CMAKE_GENERATOR:INTERNAL=Unix Makefiles
//Name of generator platform.
CMAKE_GENERATOR_PLATFORM:INTERNAL=
//Name of generator toolset.
CMAKE_GENERATOR_TOOLSET:INTERNAL=
//Have symbol pthread_create
CMAKE_HAVE_LIBC_CREATE:INTERNAL=
//Have library pthreads
CMAKE_HAVE_PTHREADS_CREATE:INTERNAL=
//Have library pthread
CMAKE_HAVE_PTHREAD_CREATE:INTERNAL=1
//Have include pthread.h
CMAKE_HAVE_PTHREAD_H:INTERNAL=1
//Source directory with the top level CMakeLists.txt file for this
// project
CMAKE_HOME_DIRECTORY:INTERNAL=/home/john/John's Linux Folder/cpp-ethereum
//ADVANCED property for variable: CMAKE_INSTALL_BINDIR
CMAKE_INSTALL_BINDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_DATADIR
CMAKE_INSTALL_DATADIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_DATAROOTDIR
CMAKE_INSTALL_DATAROOTDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_DOCDIR
CMAKE_INSTALL_DOCDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_INCLUDEDIR
CMAKE_INSTALL_INCLUDEDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_INFODIR
CMAKE_INSTALL_INFODIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_LIBDIR
CMAKE_INSTALL_LIBDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_LIBEXECDIR
CMAKE_INSTALL_LIBEXECDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_LOCALEDIR
CMAKE_INSTALL_LOCALEDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_LOCALSTATEDIR
CMAKE_INSTALL_LOCALSTATEDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_MANDIR
CMAKE_INSTALL_MANDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_OLDINCLUDEDIR
CMAKE_INSTALL_OLDINCLUDEDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_SBINDIR
CMAKE_INSTALL_SBINDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_SHAREDSTATEDIR
CMAKE_INSTALL_SHAREDSTATEDIR-ADVANCED:INTERNAL=1
//Install .so files without execute permission.
CMAKE_INSTALL_SO_NO_EXE:INTERNAL=1
//ADVANCED property for variable: CMAKE_INSTALL_SYSCONFDIR
CMAKE_INSTALL_SYSCONFDIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_LINKER
CMAKE_LINKER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MAKE_PROGRAM
CMAKE_MAKE_PROGRAM-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS
CMAKE_MODULE_LINKER_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_DEBUG
CMAKE_MODULE_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_RELEASE
CMAKE_MODULE_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_NM
CMAKE_NM-ADVANCED:INTERNAL=1
//number of local generators
CMAKE_NUMBER_OF_MAKEFILES:INTERNAL=19
//ADVANCED property for variable: CMAKE_OBJCOPY
CMAKE_OBJCOPY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_OBJDUMP
CMAKE_OBJDUMP-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_RANLIB
CMAKE_RANLIB-ADVANCED:INTERNAL=1
CMAKE_RELEASE_POSTFIX:INTERNAL=
//Path to CMake installation.
CMAKE_ROOT:INTERNAL=/usr/local/share/cmake-3.7
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS
CMAKE_SHARED_LINKER_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_DEBUG
CMAKE_SHARED_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_RELEASE
CMAKE_SHARED_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SKIP_INSTALL_RPATH
CMAKE_SKIP_INSTALL_RPATH-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_SKIP_RPATH
CMAKE_SKIP_RPATH-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS
CMAKE_STATIC_LINKER_FLAGS-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_DEBUG
CMAKE_STATIC_LINKER_FLAGS_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_RELEASE
CMAKE_STATIC_LINKER_FLAGS_RELEASE-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_STRIP
CMAKE_STRIP-ADVANCED:INTERNAL=1
//uname command
CMAKE_UNAME:INTERNAL=/bin/uname
//ADVANCED property for variable: CMAKE_VERBOSE_MAKEFILE
CMAKE_VERBOSE_MAKEFILE-ADVANCED:INTERNAL=1
//Details about finding Threads
FIND_PACKAGE_MESSAGE_DETAILS_Threads:INTERNAL=[TRUE][v()]
//Details about finding leveldb
FIND_PACKAGE_MESSAGE_DETAILS_leveldb:INTERNAL=[/usr/lib/x86_64-linux-gnu/libleveldb.so][/usr/include][v()]
//Details about finding mhd
FIND_PACKAGE_MESSAGE_DETAILS_mhd:INTERNAL=[/usr/lib/x86_64-linux-gnu/libmicrohttpd.so][/usr/include][v()]
HUNTER_CACHED_CONFIGURATION_TYPES:INTERNAL=Release
HUNTER_CACHED_ROOT:INTERNAL=/home/john/.hunter
HUNTER_CONFIG_SHA1:INTERNAL=9d3cb74c3131740ef7788372d9bf4b316e376f5b
HUNTER_SHA1:INTERNAL=b96750beadc41207e88abf1bcdbe3baeb38f09c4
HUNTER_TOOLCHAIN_SHA1:INTERNAL=0452b62c3d2446e03cbe37cac54aad9d538306d1
HUNTER_VERSION:INTERNAL=0.19.105
//ADVANCED property for variable: LEVELDB_INCLUDE_DIR
LEVELDB_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: LEVELDB_LIBRARY
LEVELDB_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: MHD_INCLUDE_DIR
MHD_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: MHD_LIBRARY
MHD_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: PYTHON_EXECUTABLE
PYTHON_EXECUTABLE-ADVANCED:INTERNAL=1
//Test Wimplicit-fallthrough
Wimplicit-fallthrough:INTERNAL=
//Last used BOOST_ROOT value.
_BOOST_ROOT_LAST:INTERNAL=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install
//Components requested for this build tree.
_Boost_COMPONENTS_SEARCHED:INTERNAL=filesystem;system;thread
//Last used Boost_INCLUDE_DIR value.
_Boost_INCLUDE_DIR_LAST:INTERNAL=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/include
//Last used Boost_LIBRARY_DIR_DEBUG value.
_Boost_LIBRARY_DIR_DEBUG_LAST:INTERNAL=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib
//Last used Boost_LIBRARY_DIR_RELEASE value.
_Boost_LIBRARY_DIR_RELEASE_LAST:INTERNAL=/home/john/.hunter/_Base/b96750b/0452b62/9d3cb74/Install/lib
//Last used Boost_NAMESPACE value.
_Boost_NAMESPACE_LAST:INTERNAL=boost
//Last used Boost_NO_SYSTEM_PATHS value.
_Boost_NO_SYSTEM_PATHS_LAST:INTERNAL=ON
//Last used Boost_USE_MULTITHREADED value.
_Boost_USE_MULTITHREADED_LAST:INTERNAL=TRUE
//Last used Boost_USE_STATIC_LIBS value.
_Boost_USE_STATIC_LIBS_LAST:INTERNAL=ON
//CMAKE_INSTALL_PREFIX during last run
_GNUInstallDirs_LAST_CMAKE_INSTALL_PREFIX:INTERNAL=/usr/local
//Have symbol clock_gettime
_hunter_boost_have_clock_gettime:INTERNAL=1
//Test fstack-protector-strong
fstack-protector-strong:INTERNAL=1

**Comment by chfast** [comment]
@JohnnyGlobe You actually have spaces in the path because the project is in `/home/john/John's Linux Folder/cpp-ethereum`.
I expected than can break some day. I will work on fixing it, but for a quick workaround clone cpp-ethereum in a dir without spaces in path.

**Comment by isaaccandell** [comment]
I am running into a similar issue. Can you elaborate a bit more on this solution? @chfast
