### ISSUE TITLE
Ethereum

### ISSUE THREAD

**Issue by Pesho8505** [ethereum/cpp-ethereum#4603]
I am a beginner! Could it be possibly for someone to explain me the basic things? Thanks in advance

**Comment by gumb0** [comment]
What kind of things? Maybe start here https://www.reddit.com/r/ethereum/comments/61y5ix/welcome_to_rethereum_the_reddit_front_page_of_the/
This is the repository for C++ Ethereum client and the issues here are supposed to be used to report problems with it.
