### ISSUE TITLE
OnRequest is undefined

### ISSUE THREAD

**Issue by mapennell** [ethereum/cpp-ethereum#4607]
https://github.com/ethereum/cpp-ethereum/blob/b5a95200d0d0b703e03f72bfbdddf6b6ba171382/libweb3jsonrpc/IpcServerBase.cpp#L145

**Comment by gumb0** [comment]
It's defined in the base class.

Did you have build failure or what's exactly your issue?

**Comment by SleepyNab** [comment]
I got the same error... Workaround:

 in IpcServerBase.h change the include to its absolute path:
`#include </Users/xxxxxxx/cpp-ethereum/build/deps/src/jsonrpccpp/src/jsonrpccpp/server/abstractserverconnector.h>`

**Comment by mapennell** [comment]
Thank you, @gumb0, @SleepyNab. I was having issues building until I fixed the header as above.

**Comment by ton4ar** [comment]
thx 2 @SleepyNab it worked (^_^)/
