### ISSUE TITLE
ChainID not allowed to be larger than 110

### ISSUE THREAD

**Issue by karalabe** [ethereum/cpp-ethereum#4618]
The chain ID is currently implemented as an unsigned 64bit int in all Ethereum clients, but cpp-ethereum limits signature V values to a single byte. As such, a chain ID of 111 would already result in overflowing the signature V (2 * 111 + 35 = 227). In its current state cpp-ethereum is incompatible with all networks with EIP155 enabled and a chain ID larger than 110.

**Comment by gumb0** [comment]
Addressed in https://github.com/ethereum/cpp-ethereum/pull/4625
