### ISSUE TITLE
ETH feature request.

### ISSUE THREAD

**Issue by foxjazz** [ethereum/cpp-ethereum#4619]
Ethereum sidechain feature...

ETH nodes would have a private key to decrypt the code it would run, this code is copied x times based on keys that would have access to the data, one encryption for the sender, one for the receiver, and one for the computer and more for 3rd parties listed. 
The way to seed this process would be hardware accessed as the secret key owners, nodes would have to carry a hardware wallet copy for all running nodes which ETH would use to decrypt and process code.
This ensure ultimate privacy of the contract.

Currently contracts are open, and not private, they may contain things like listing of properties or trade in volume.

**Comment by chfast** [comment]
We have not idea what are you talking about.
