### ISSUE TITLE
install_deps.sh supports CentOS7 but not RHEL7.

### ISSUE THREAD

**Issue by nnachefski** [ethereum/cpp-ethereum#4626]
# ./install_deps.sh 
Unsupported Linux distribution: Red Hat Enterprise Linux Server.

# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.4 (Maipo)

I think it would be safe to include RHEL as an alias for CentOS (or the othey way around).

**Comment by chfast** [comment]
Please do.

**Comment by chfast** [comment]
The "Red Hat" is there: https://github.com/ethereum/cpp-ethereum/blob/develop/scripts/install_deps.sh#L188.
If that's not enough let me know.

**Comment by bahelit** [comment]
Have access to RHEL 7 installations and am verifying that the current state of install_deps.sh is correct.

/etc/os-release contains:
`NAME="Red Hat Enterprise Linux Server"`

Line 188 satisfies the look up:
`CentOS*|Oracle*|"Red Hat Enterprise Linux"*)`

**Comment by chfast** [comment]
Oh, great!
