### ISSUE TITLE
Feature request: logarithm  proof of share

### ISSUE THREAD

**Issue by happyjack27** [ethereum/cpp-ethereum#4634]
Both income and balance follow "zipf's law" - a power law - in the same way that bits or decimals do.  Is not information theory valid here?

especially in that stock market retransmit are multiplicative.   An investment is always multiplicative not additive.   This means that when you are in time - when you parameterized the function by "t", it's exponential not cumulative.

Does it not then follow that "proof of share" should be logarithmic "; that the likelihood of starting the next block should be proportional to the logarithm of the wealth?

**Comment by happyjack27** [comment]
There is one very good answer to this question I want to see who gets it.

**Comment by gumb0** [comment]
What it exactly the feature that you request?

**Comment by happyjack27** [comment]
that the likelihood of starting the next block should be proportional to the logarithm of the wealth.  proof of share should be logarithmic to the wealth, not linear to it.

unfortunately there's a problem logarithmic proof of share: the problem is that a person could split up their wealth into smaller accounts to increase their probability of starting a block.  so it doesn't work.  it has to be linear so that a person can't change their share by redistribution their wealth.
