### ISSUE TITLE
"std::string" parameter could be improved with "const std::string&"

### ISSUE THREAD

**Issue by orpillar** [ethereum/cpp-ethereum#4641]
To avoid copying strings around, the following "std::string" parameter could be improved with "const std::string&":

- eth/MinerAux.h: void doBenchmark(std::string _m, unsigned _warmupDuration = 15, unsigned _trialDuration = 3, unsigned _trials = 5)
- libdevcore/CommonData.h:std::string toHex(Iterator _it, Iterator _end, std::string _prefix)
- libdevcore/CommonIO.h:template <class T> inline std::string toString(std::chrono::time_point<T> const& _e, std::string _format = "%Y-%m-%d %H:%M:%S")
- libdevcore/CommonIO.h:template <class T> inline std::string toString(std::chrono::time_point<T> const& _e, std::string _format = "%F %T")
- libdevcore/Exceptions.h:struct InterfaceNotSupported: virtual Exception { public: InterfaceNotSupported(std::string _f): Exception("Interface " + _f + " not supported.") {} };
- libdevcore/Exceptions.h:struct ExternalFunctionFailure: virtual Exception { public: ExternalFunctionFailure(std::string _f): Exception("Function " + _f + "() failed.") {} };
- libdevcore/FileSystem.cpp:fs::path dev::getDataDir(string _prefix)
- libdevcore/FileSystem.cpp:fs::path dev::getDefaultDataDir(string _prefix)
- libdevcore/FileSystem.h:boost::filesystem::path getDataDir(std::string _prefix = "ethereum");
- libdevcore/FileSystem.h:boost::filesystem::path getDefaultDataDir(std::string _prefix = "ethereum");
- libweb3jsonrpc/Web3.h:  Web3(std::string _clientVersion = "C++ (ethereum-cpp)"): m_clientVersion(_clientVersion) {}

**Comment by chfast** [comment]
I mostly agree, but that requires a Pull Request.

**Comment by pushkarmoi** [comment]
If no one has already done this,, should I implement these changes and create a pull request? 
I'm new here :D

**Comment by chfast** [comment]
Fixed in #4644.

**Comment by orpillar** [comment]
Without handy working environment, browsing code may be better fit for me for now.
Thanks for looking into the issue.
