### ISSUE TITLE
Getting this error cmake ..

### ISSUE THREAD

**Issue by nijeeshjoshy** [ethereum/cpp-ethereum#4645]
CMake Error: Problem extracting tar: /home/centos/.hunter/_Base/Download/Boost/1.65.0/f926007/boost_1_65_0.tar.bz2
-- extracting... [error clean up]
CMake Error at Build/Boost-prefix/src/Boost-stamp/extract-Boost.cmake:33 (message):
  error: extract of
  '/home/centos/.hunter/_Base/Download/Boost/1.65.0/f926007/boost_1_65_0.tar.bz2'
  failed

gmake[2]: *** [Boost-prefix/src/Boost-stamp/Boost-download] Error 1
gmake[1]: *** [CMakeFiles/Boost.dir/all] Error 2
gmake: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /home/centos/.hunter/_Base/b96750b/759e7ed/9d3cb74/Build/Boost
[hunter ** FATAL ERROR **] [Directory:/home/centos/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/projects/Boost]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at /home/centos/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /home/centos/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  /home/centos/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_download.cmake:596 (hunter_fatal_error)
  /home/centos/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/projects/Boost/hunter.cmake:272 (hunter_download)
  /home/centos/.hunter/_Base/Download/Hunter/0.19.105/b96750b/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:101 (hunter_add_package)

**Comment by TMit** [comment]
My case was not enough space on the SSD. apt autoremove and apt clean, then made it.

**Comment by chfast** [comment]
It might be the case. Boost is very big pack of source files.
