### ISSUE TITLE
crypto: Rename Public -> Pubkey, Secret -> Seckey

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#4671]
The name `Public` conflicts with `public` keyword (we have methods like `pub()` instead of `public()` and vars `pub` instead of `public`).

The name `Secret` is confusing.

**Comment by gumb0** [comment]
I would prefer then `PublicKey` and `SecretKey`

**Comment by chfast** [comment]
I think `PrivateKey` might be a bit better name, but on the same time it is too similar to `PublicKey`. I'm keeping the `SecretKey`, ok?

**Comment by gumb0** [comment]
ok
