### ISSUE TITLE
The issue while Building on Windows

### ISSUE THREAD

**Issue by skMikhail** [ethereum/cpp-ethereum#4720]
Hi,
I unpacked the cpp-ethereum-1.1.2.zip archive, then ran the getstuff.bat script, then received the following issue:
`DISPLAY: '{9010D98A-87A5-44E0-9ECE-29E6C9552225}' TYPE: DOWNLOAD STATE: TRANSIE
PRIORITY: NORMAL FILES: 0 / 1 BYTES: 0 / UNKNOWN
ERROR FILE:    https://build.ethdev.com/builds/windows-precompiled/boost-1.55.0
ERROR CODE:    0x80072efd - can not connect to the server
ERROR CONTEXT: 0x00000005 - An error occurred while processing the remote file.`

OS: Win7
cmake version 3.10.1

**Comment by gumb0** [comment]
If you're interested in cpp-ethereum, you should build it from source, this zip archive you used is clearly outdated
