### ISSUE TITLE
Solidity sintax not working in Sublime Text

### ISSUE THREAD

**Issue by FernandoJefferson** [ethereum/cpp-ethereum#4722]
I have installed Ethereum Package for Sublime Text 2/3 but it is not working
Solidity does not appear in the options under "VIew / Syntax"
Any idea?
Thanks in advance

**Comment by xefdan3ms** [comment]
You might want to open an issue on the repository for the SublimeEthereum package then. https://github.com/davidhq/SublimeEthereum

You are posting your issue to 'cpp-ethereum' which isn't where the source for this package is located.
