### ISSUE TITLE
cpp-ethereum do not support macOS 10.12.X (sierra) yet ?

### ISSUE THREAD

**Issue by yuji-for-co** [ethereum/cpp-ethereum#4736]
I saw this information
http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/osx-homebrew.html

**Comment by qubey** [comment]
It looks like you can build it yourself from source for 10.12, it's just not in their automated build system yet.

**Comment by gumb0** [comment]
ethdocs.org is very outdated, sorry, we support only building from source right now. It should be buildable on Sierra

**Comment by yuji-for-co** [comment]
Thank you guys for giving those infomation!
