### ISSUE TITLE
"--peerset required:" doesn't work with the enode returned by "bootnode"

### ISSUE THREAD

**Issue by trungtt1981** [ethereum/cpp-ethereum#4759]
If adding peer for "eth" node in private chain with the "bootnode" via the option "--peerset required:", then the peer adding is not succeeded. But if passing the "eth" node for "--peerset", then it works fine
What is exactly the stuff of "bootnode"? I cannot find an equivalence in cpp-ethereum code?

**Comment by gumb0** [comment]
I don't get the first sentence, what do you mean by "bootnode"?

I'm not an expert but I think geth's bootnodes are special nodes that don't act as full validating nodes, but are just helping with node discovery for the rest of the network somehow. We don't have this feature in cpp-ethereum, only fulll validating nodes can participate in the network.
(I think Parity's hard-coded bootnodes are also full validating nodes)

**Comment by trungtt1981** [comment]
I use the "bootnode" binary from go-ethereum in order to start a bootstrap node for my private chain with the hope that this kind of bootstrap node can help the nodes in my private chain to discover each other. However, it doesn't work as expected. 

Even worse that this kind of bootstrap node cannot be added peers with any "eth" node via the option "--peerset required" nor the JavaScript API admin.addPeer().

From your above explanation, my understanding is that such a bootstrap node cannot participate in the private chain of the "eth" nodes, right?? If so, then I will no longer use "bootnode" for my private chain of "eth" nodes. Thanks for this clarification.

**Comment by gumb0** [comment]
Closing this because https://github.com/ethereum/cpp-ethereum/issues/4855 has a better problem description
