### ISSUE TITLE
Owner balance is 0 ETH

### ISSUE THREAD

**Issue by nobody93** [ethereum/cpp-ethereum#4768]
Hi, I am running "eth --ropsten" on Debian 9, but I could not deploy contract it always indicated Owner balance is 0 ETH at address 0x0077222ebad26d4835e3ca5789dc2e74e3cf63ac, but I can see that address acutally has 12 ether at https://ropsten.etherscan.io/address/0x0077222ebad26d4835e3ca5789dc2e74e3cf63ac

**Comment by gumb0** [comment]
You need to sync to the top of the chain first.

**Comment by axic** [comment]
@nobody93 please reopen if still happens after syncing to the current block height
