### ISSUE TITLE
Genesis: add an option to load account code from a file

### ISSUE THREAD

**Issue by axic** [ethereum/cpp-ethereum#4774]
e.g.

```
  "accounts": {
    "0000000000000000000000000000000000000001": { "codeFromFile": "/path/to/ecrecover.wasm" }
  }
```

**Comment by axic** [comment]
@chfast @gumb0 what do you think?

**Comment by winsvega** [comment]
so the "code" : ""  should work directly from json file. 
I guess we could just add a syntax to parse the code if it contains link to a file. 

but speaking of wasm first there should be a support for wasm code
https://github.com/ethereum/cpp-ethereum/pull/4754

**Comment by axic** [comment]
This only cares about filling the account code with raw data, whatever that data is. Nothing in the genesis should be processed or compiled afterwards.

The above feature isn't good only for ewasm, but for example the blockhash EVM bytecode could be placed there too.

**Comment by chfast** [comment]
The `.wasm` files in the example contain a bytecode already. No compilation is needed here.

I'm just worried about using relative paths in the JSON file...

**Comment by gumb0** [comment]
Maybe just require all code files to be in the same dir as json? and `codeFromFile` will have only the name

**Comment by winsvega** [comment]
hm. yes this sounds like a nice feauture. 

in the same dir might become with too many files. a subdir would be reasonable

**Comment by chfast** [comment]
I can make the relative paths to work relatively to the config.json file. But we also use string literals for config :)

**Comment by axic** [comment]
I think another decision to be made is whether the file referenced should have:
- binary code
- hex string
- hex string prefixed `0x`

**Comment by winsvega** [comment]
the function importCode deals with hex and prefixed hex.

**Comment by axic** [comment]
I don't think `importCode` from testeth is relevant here?

I would personally prefer to take the file as binary but considering all tools output EVM bytecode as hexadecimal (without the `0x` prefix) probably that is the most sane choice.
