### ISSUE TITLE
Calc DAG failed, CUDA error 6 - cannot write buffer for DAG

### ISSUE THREAD

**Issue by andyleong112** [ethereum/cpp-ethereum#4778]
CAN SOMEONE HELP ME WITH THIS???????????? I DONT UNDERSTAND AT ALL
THANKSSSSSSS

GPU #0: GeForce GTX 1060 6GB, 6144 MB available, 10 compute units, capability: 6.1

GPU #1: GeForce GTX 1060 6GB, 6144 MB available, 10 compute units, capability: 6.1

GPU #2: GeForce GTX 1060 6GB, 6144 MB available, 10 compute units, capability: 6.1

Total cards: 3
ETH: Stratum - connecting to 'asia1.nanopool.org' <103.3.62.64> port 9999
ETHEREUM-ONLY MINING MODE ENABLED (-mode 1)
ETH: Stratum - Connected (asia1.nanopool.org:9999)
ETH: eth-proxy stratum mode
Watchdog enabled
Remote management (READ-ONLY MODE) is enabled on port 3333

ETH: Authorized
Setting DAG epoch #163...
Setting DAG epoch #163 for GPU2
Setting DAG epoch #163 for GPU0
Setting DAG epoch #163 for GPU1
Create GPU buffer for GPU0
Create GPU buffer for GPU2
Create GPU buffer for GPU1
**_GPU 1, GpuMiner cu_kd failed 6 (1), the launch timed out and was terminated
GPU 2, GpuMiner cu_kd failed 6 (0), the launch timed out and was terminated
GPU 0, GpuMiner cu_kd failed 6 (0), the launch timed out and was terminated
GPU 2, Calc DAG failed!
GPU 1, Calc DAG failed!
GPU 0, Calc DAG failed!
ETH: 01/17/18-04:17:30 - New job from asia1.nanopool.org:9999
ETH - Total Speed: 0.000 Mh/s, Total Shares: 0, Rejected: 0, Time: 00:00
ETH: GPU0 0.000 Mh/s, GPU1 0.000 Mh/s, GPU2 0.000 Mh/s
Setting DAG epoch #163 for GPU1
GPU 1 failed
Setting DAG epoch #163 for GPU2
GPU 2 failed
GPU 1, CUDA error 6 - cannot write buffer for DAG
GPU 0 failed
Setting DAG epoch #163 for GPU0
GPU 2, CUDA error 6 - cannot write buffer for DAG
GPU 0, CUDA error 6 - cannot write buffer for DAG
GPU 1 failed
GPU 2 failed
GPU 0 failed
GPU0 t=32C fan=41%, GPU1 t=31C fan=41%, GPU2 t=30C fan=41%
WATCHDOG: GPU error, you need to restart miner :(_**
Restarting OK, exit...

**Comment by gumb0** [comment]
Submit this to https://github.com/ethereum-mining/ethminer/issues
