### ISSUE TITLE
eth --ropsten sync problems

### ISSUE THREAD

**Issue by nobody93** [ethereum/cpp-ethereum#4780]
Hi,

I have run the command of eth --ropsten for 3 days, it still hasn't reached the top the block, the currentBlock is 501635, the highestBlock is 2463262. The problem is it stuck on many following messages, looks like it does not sync to the rapsten any more. While I learned from Andrei Maiboroda those messages should not cause the problems, but could anyone have a look at and explain why it stops sync? I've just checked it again, within 2 hours there is no change for the currentBlock, stuck at block number 501635. The eth process seems halted despaired continuing to display following messages. Not quite sure if there are bugs in eth or I did wrong thing here.

⧎ ✘  20:32:55.005|p2p|a979fb57…|Geth/v1.7.3-stable/linux-amd64/go1.7  Error reading - Abrupt peer disconnect: End of file
⧎ ✘  20:36:43.589|p2p|2d11cfe9…|Ethereum(J)/v1.6.3/Linux/Release/Java/Dev  Error reading - Abrupt peer disconnect: End of file
⧎ ✘  20:38:51.849|p2p|7793fede…|Parity/v1.8.2-beta-1b6588c-20171025/x86_64-linux-gnu/rustc1.21.0  Error reading - Abrupt peer disconnect: End of file
⧎ ✘  20:45:42.782|p2p|a979fb57…|Geth/v1.7.3-stable/linux-amd64/go1.7  Error reading - Abrupt peer disconnect: End of file
.......

08:22:43.722|p2p|3f1d1204…|Geth/v1.7.2-stable-1db4ecdc/linux-amd64/go1.7  Error reading - Abrupt peer disconnect: End of file

**Comment by gumb0** [comment]
It looses all peers, might be similar to what I see in https://github.com/ethereum/cpp-ethereum/issues/4773

Try deleting `~\.ethereum\network.rlp`

**Comment by gumb0** [comment]
Could you please try with the latest `develop`, we've made a fix that should help with stuck sync
