### ISSUE TITLE
Please delete the master branch, it is super confusing.

### ISSUE THREAD

**Issue by axic** [ethereum/cpp-ethereum#4791]

**Comment by chfast** [comment]
I'm for moving the work to master, deleting develop.

**Comment by axic** [comment]
That is even better, but felt like more opposition against it.

**Comment by pirapira** [comment]
We can do both.  Nobody should be using `master` right now.  I'll remove it.  When `develop` moves over to `master` that will be even better.

**Comment by axic** [comment]
You know that branches can be changed in PRs, so it is possible to push a copy of `develop` under the branch `master`, change all the PRs and then update github settings to consider `master` as master :)
