### ISSUE TITLE
Rename `develop` into `master`

### ISSUE THREAD

**Issue by pirapira** [ethereum/cpp-ethereum#4792]
A very obsolete `master` was confusing https://github.com/ethereum/cpp-ethereum/issues/4791.  That was removed.

Moreover, @chfast had an [idea](https://github.com/ethereum/cpp-ethereum/issues/4791#issuecomment-359284406) of renaming `develop` into `master`.

**Comment by chfast** [comment]
For reference, the master and develop come from "Git Workflow": http://nvie.com/posts/a-successful-git-branching-model/.

However, in cases where we care about contributors more than the users, the single branch might be better.

go-ethereum is using master branch for some time.

How about solidity? @chriseth @axic

**Comment by chfast** [comment]
@gumb0 are you ok with this change?

**Comment by gumb0** [comment]
Yes, please do it. `develop` is confusing
