### ISSUE TITLE
low level tcp error

### ISSUE THREAD

**Issue by alhb** [ethereum/cpp-ethereum#4798]
at random points  eth stops working logging the message 'abrupt peer disconnect - low Level tcp error' and displaying the ip of the polluter. After restart of eth everything is ok until next time this message occurs. It happens in randomly distances, sometimes 1 hour sometimes ten minutes

**Comment by alhb** [comment]
idea to fix it are welcome

**Comment by divinity76** [comment]
is claymore miner stable on the same computer?

**Comment by alhb** [comment]
i found i funny solution to prevent the exits of eth during sync: i let it run in gdb
