### ISSUE TITLE
libscrypt_scrypt js and c

### ISSUE THREAD

**Issue by barron9** [ethereum/cpp-ethereum#4814]
I am trying to compare to code with c and js same library.

my c code:

```
int main(void) {
     char *salt[32] = {
"47","6d","90","72","7b","b3","f3","70","52","ac","99","84","19","e8","81","80","34","83","05","b9","92","60","5d","ae","22","3b","e1","d5","44","5e","52","c1"};

     const char *passw[8] = {"44","65","65","70","73","65","65","61"};
    uint8_t data[64] ;
    char outbuf[128] ;

    libscrypt_scrypt((const uint8_t *)passw, 8, (const uint8_t *)salt, 32, 262144U,
                     8U, 1U, /*@out@*/ (uint8_t *)data, 32);
```

and my js code
```
`
        derivedKey = ethUtil.scrypt(Buffer.from(password), new Buffer(kdfparams.salt, 'hex'), kdfparams.n, kdfparams.r, kdfparams.p, kdfparams.dklen)
`
```

both outputs different hex

c output : 664d45617967576e4255612f6f426e6b493454767264566a4667517449793936
js output: <Buffer 7e 65 ec f6 3a fb d8 15 03 df 59 47 4d 33 42 77 91 e7 3b f7 1c 52 f8 89 fb 0f 30 85 13 f5 53 61>

**Comment by axic** [comment]
I do not know how this is related to cpp-ethereum, but you the syntax you are using for your inputs does not do what you want. You should try
```
const char salt[32] = { 0x47, 0x6d, 0x90... }
```

The libraries official source is https://github.com/technion/libscrypt, please discuss issues there.
