### ISSUE TITLE
Split testeth (filling) into its own project

### ISSUE THREAD

**Issue by axic** [ethereum/cpp-ethereum#4816]
I think it would really make sense having it as a separate project as the project boundaries and hopefully complexity would be reduced.

Is it possible to run test filling over RPC only (using the `admin_` methods)?

**Comment by chfast** [comment]
That would make sense. Although, I'm concerned about performance. We need an IPC expert here. But that might also benefit future P2P service integration.

**Comment by axic** [comment]
I don't think the IPC part is the slowest, but the PoW?

**Comment by axic** [comment]
@winsvega how does the filling works at the moment? Can you explain the architecture?

**Comment by winsvega** [comment]
it depends on libethereum ethashseal and so on. basically it is easier to just disable it from the build.

**Comment by chfast** [comment]
This is not about end users, but about the main testing tool is too much coupled with a node implementation. E.g. there is a code in libethereum that loads JSON description of accounts for tests.

**Comment by winsvega** [comment]
only at one place - the account shouldnotexist field. other then that testeth does not have any logic in the client.

**Comment by winsvega** [comment]
*and test genesis configs (in ethash seal)

**Comment by axic** [comment]
I think it would make sense if the two projects could be decoupled, because `eth` becomes a regular node, could have a release cycle, while `testeth` can have a different development speed. `testeth` doesn't even need releases.

**Comment by chfast** [comment]
Also we can have different C++ compatibility restrictions in eth and testeth. E.g. we could use C++17 in testeth.

**Comment by winsvega** [comment]
Its not like testeth just edit the json files. It must have the full implementation of the protocol. If you isolate testeth from the core, you will have to make it an ethereum client.(implementation). 

I don't really get what you are trying to propose. Please explain how do you see testeth cuted off cpp

**Comment by winsvega** [comment]
Testeth was not the unit testing tool from the beginning. Its purpose is to manage consensus tests for all clients.

**Comment by gumb0** [comment]
Testeth is now splitted in https://github.com/ethereum/testeth
