### ISSUE TITLE
NodeMode::PeerServer not used

### ISSUE THREAD

**Issue by trungtt1981** [ethereum/cpp-ethereum#4821]
So far, the NodeMode::PeerServer has not been used nor implemented. 
Should it be removed completely or still leave there for later implementation??

**Comment by chfast** [comment]
I think we can remove it if nobody knows what it is for.
cc @gumb0.

**Comment by gumb0** [comment]
I think it's for "bootnode" functionality and plan to revive it, see https://github.com/ethereum/cpp-ethereum/issues/4703
