### ISSUE TITLE
Post-import of snapshot failure. "Assertion `sha3(_code) == m_codeHash' failed."

### ISSUE THREAD

**Issue by VERTlG0** [ethereum/cpp-ethereum#4842]
⧫ ◎  03:47:15 PM.709|eth  Safely dropping transaction #b2a12b46…                                                                                                        
⧫ ◎  03:47:15 PM.709|eth  Safely dropping transaction #6fd4bf93…                                                                                                        
⧫ ◎  03:47:15 PM.709|eth  Live block: #1c1c30ef…                                                                                                                        
ℹ    03:47:15 PM.709|eth  noteChanged: { chain }                                                                                                                        
⧫ ◎  03:47:15 PM.709|eth  Since 2018-02-11 20:44:31.686Z (164): 15ticks                                                                                                 
☍ ◌  03:47:15 PM.710|eth  Attempting import of #42e6cdc3… ...                                                                                                           
⧎ ℹ  03:47:15 PM.797|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##d4686d21…                                                                                          
⧎ ℹ  03:47:16 PM.199|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##893b12a4…                                                                                          
⧎ ℹ  03:47:16 PM.902|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##690fd767…                                                                                          
⧎ ℹ  03:47:16 PM.902|p2p  p2p.host.peers.events.peerAdded ##690fd767… 5.22.134.1763291130303                                                                            
⧎ ℹ  03:47:17 PM.189|p2p  p2p.connect.egress recvd hello header                                                                                                         
⧎ ℹ  03:47:17 PM.404|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##690fd767…                                                                                          
⧎ ℹ  03:47:17 PM.404|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##b7cd1a14…                                                                                          
⧎ ℹ  03:47:17 PM.404|p2p  p2p.host.peers.events.peerAdded ##b7cd1a14… 35.153.24.2523030130301                                                                           
⧎ ℹ  03:47:17 PM.441|p2p  p2p.connect.egress recvd hello header                                                                                                         
⧎ ℹ  03:47:17 PM.505|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##16671b13…                                                                                          
⧎ ℹ  03:47:17 PM.505|p2p  p2p.host.peers.events.peerAdded ##16671b13… 188.166.99.1253030330303                                                                          
⧎ ℹ  03:47:17 PM.505|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##12017df0…                                                                                          
⧎ ℹ  03:47:17 PM.505|p2p  p2p.host.peers.events.peerAdded ##12017df0… 35.167.135.2153030330303                                                                          
⧎ ℹ  03:47:17 PM.505|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##83de7cee…                                                                                          
⧎ ℹ  03:47:17 PM.505|p2p  p2p.host.peers.events.peerAdded ##83de7cee… 79.160.161.1343030330303                                                                          
⧎ ℹ  03:47:17 PM.605|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##654c36c6…                                                                                          
⧎ ℹ  03:47:17 PM.605|p2p  p2p.host.peers.events.peerAdded ##654c36c6… 39.104.106.2363030330303                                                                          
⧎ ℹ  03:47:17 PM.605|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##0538ec5b…                                                                                          
⧎ ℹ  03:47:17 PM.605|p2p  p2p.host.peers.events.peerAdded ##0538ec5b… 54.250.244.262100021000                                                                           
⧎ ℹ  03:47:17 PM.706|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##654c36c6…                                                                                          
⧎ ℹ  03:47:17 PM.706|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##18f60a97…                                                                                          
⧎ ℹ  03:47:17 PM.706|p2p  p2p.host.peers.events.peerAdded ##18f60a97… 114.206.60.983030330303                                                                           
⧎ ℹ  03:47:18 PM.007|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##b9337858…                                                                                          
⧎ ℹ  03:47:18 PM.007|p2p  p2p.host.peers.events.peerAdded ##b9337858… 78.69.44.293030330303                                                                             
⧎ ℹ  03:47:18 PM.107|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##893b12a4…                                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##d029394a…                                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.peers.events.peerAdded ##d029394a… 54.197.186.1913030330303                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##574e263a…                                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.peers.events.peerAdded ##574e263a… 13.72.104.1433030330303                                                                           
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##0b681e95…                                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.peers.events.peerAdded ##0b681e95… 128.199.177.1353030330303                                                                         
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##c89d548e…                                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.peers.events.peerAdded ##c89d548e… 178.33.101.163030330303                                                                           
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##1e800fee…                                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.peers.events.peerAdded ##1e800fee… 54.187.252.763030330303                                                                           
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##dda46ccb…                                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.peers.events.peerAdded ##dda46ccb… 5.135.184.973030530305                                                                            
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##2866b6c9…                                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.peers.events.peerAdded ##2866b6c9… 217.182.90.433030330303                                                                           
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##bae15090…                                                                                          
⧎ ℹ  03:47:18 PM.610|p2p  p2p.host.peers.events.peerAdded ##bae15090… 148.251.177.2061091210912                                                                         
⧎ ℹ  03:47:18 PM.710|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##9b42c5ed…                                                                                          
⧎ ℹ  03:47:18 PM.710|p2p  p2p.host.peers.events.peerAdded ##9b42c5ed… 207.154.249.543030330303                                                                          
⧎ ℹ  03:47:18 PM.710|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##89bf2870…                                                                                          
⧎ ℹ  03:47:18 PM.710|p2p  p2p.host.peers.events.peerAdded ##89bf2870… 93.115.6.43030330303                                                                              
⧎ ℹ  03:47:18 PM.710|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##1b189cdc…                                                                                          
⧎ ℹ  03:47:18 PM.710|p2p  p2p.host.peers.events.peerAdded ##1b189cdc… 45.33.71.623040330403                                                                             
⧎ ℹ  03:47:18 PM.710|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##93ce01db…                                                                                          
⧎ ℹ  03:47:18 PM.710|p2p  p2p.host.peers.events.peerAdded ##93ce01db… 172.104.81.2213030730307                                                                          
⧎ ℹ  03:47:18 PM.811|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##650b2561…                                                                                          
⧎ ℹ  03:47:18 PM.811|p2p  p2p.host.peers.events.peerAdded ##650b2561… 35.177.203.643030330303                                                                           
⧎ ℹ  03:47:18 PM.911|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##a1c553c8…                                                                                          
⧎ ℹ  03:47:18 PM.911|p2p  p2p.host.peers.events.peerAdded ##a1c553c8… 107.155.29.1484014540145                                                                          
⧎ ℹ  03:47:18 PM.911|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##a8ca586d…                                                                                          
⧎ ℹ  03:47:18 PM.911|p2p  p2p.host.peers.events.peerAdded ##a8ca586d… 13.231.49.613030330303                                                                            
⧎ ℹ  03:47:18 PM.911|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##fd903558…                                                                                          
⧎ ℹ  03:47:18 PM.911|p2p  p2p.host.peers.events.peerAdded ##fd903558… 182.211.173.1843030030300                                                                         
⧎ ℹ  03:47:19 PM.032|p2p  p2p.connect.egress recvd hello header                                                                                                         
⧎ ℹ  03:47:19 PM.212|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##130e5d13…                                                                                          
⧎ ℹ  03:47:19 PM.212|p2p  p2p.host.peers.events.peerAdded ##130e5d13… 172.113.36.474493730303                                                                           
⧎ ℹ  03:47:19 PM.212|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##c89d548e…                                                                                          
⧎ ℹ  03:47:19 PM.212|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##e0e6a741…                                                                                          
⧎ ℹ  03:47:19 PM.213|p2p  p2p.host.peers.events.peerAdded ##e0e6a741… 195.181.213.1186268862688                                                                         
⧎ ℹ  03:47:19 PM.213|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##6ab6dcf6…                                                                                          
⧎ ℹ  03:47:19 PM.213|p2p  p2p.host.peers.events.peerAdded ##6ab6dcf6… 37.143.10.1493031330313                                                                           
⧎ ℹ  03:47:19 PM.213|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##1f0cfe48…                                                                                          
⧎ ℹ  03:47:19 PM.213|p2p  p2p.host.peers.events.peerAdded ##1f0cfe48… 88.99.136.703030630306                                                                            
⧎ ℹ  03:47:19 PM.313|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##4749abc0…                                                                                          
⧎ ℹ  03:47:19 PM.313|p2p  p2p.host.peers.events.peerAdded ##4749abc0… 139.59.122.573060330603                                                                           
⧎ ℹ  03:47:19 PM.313|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##6caa00a6…                                                                                          
⧎ ℹ  03:47:19 PM.313|p2p  p2p.host.peers.events.peerAdded ##6caa00a6… 141.20.33.2373030330303                                                                           
⧎ ℹ  03:47:19 PM.715|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##130e5d13…                                                                                          
⧎ ℹ  03:47:19 PM.916|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##0b681e95…                                                                                          
⧎ ℹ  03:47:20 PM.016|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##833258a1…                                                                                          
⧎ ℹ  03:47:20 PM.026|p2p  p2p.connect.egress recvd hello header                                                                                                         
⧎ ℹ  03:47:20 PM.117|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##d4686d21…                                                                                          
⧎ ℹ  03:47:22 PM.510|p2p  p2p.connect.egress recvd hello header                                                                                                         
⧎ ℹ  03:47:22 PM.685|p2p  p2p.connect.egress recvd hello header                                                                                                         
⧎ ℹ  03:47:23 PM.230|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##61953b86…                                                                                          
⧎ ℹ  03:47:24 PM.033|p2p  p2p.host.nodeTable.events.nodeEntryAdded ##ca0bb09a…                                                                                          
⧎ ℹ  03:47:24 PM.259|p2p  p2p.connect.egress recvd hello header                                                                                                         
⧎ ℹ  03:47:25 PM.159|p2p  p2p.connect.egress recvd hello header                                                                                                         
eth: /root/cryptomining/cppethereumSnapshot/cpp-ethereum/libethereum/Account.h:159: void dev::eth::Account::noteCode(dev::bytesConstRef): Assertion `sha3(_code) == m_codeHash' failed.
Aborted

**Comment by gumb0** [comment]
I've got the same assert failure and additional debug output shows that it's the same `Too many open files` error as in https://github.com/ethereum/cpp-ethereum/issues/4493

```
!!! Exception FailedLookupInDB during overlay db lookup! /home/ethnode/cpp-ethereum/libdevcore/LevelDB.cpp(100): Throw in function virtual std::string dev::db::LevelDB::lookup(dev::db::Slice) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::db::FailedLookupInDB>
std::exception::what: std::exception
[dev::tag_comment*] = IO error: /home/ethnode/.ethereum/d4e56740/12041/state/3581284.ldb: Too many open files

std::exception!!! Exception FailedLookupInDB during overlay db lookup! /home/ethnode/cpp-ethereum/libdevcore/LevelDB.cpp(100): Throw in function virtual std::string dev::db::LevelDB::lookup(dev::db::Slice) const
Dynamic exception type: boost::exception_detail::clone_impl<dev::db::FailedLookupInDB>
std::exception::what: std::exception
[dev::tag_comment*] = IO error: /home/ethnode/.ethereum/d4e56740/12041/state/4413490.ldb: Too many open files

std::exceptioneth: /home/ethnode/cpp-ethereum/libethereum/Account.h:159: void dev::eth::Account::noteCode(dev::bytesConstRef): Assertion `sha3(_code) == m_codeHash' failed.
```

DB lookup fails because of too many open files.

**Comment by gumb0** [comment]
Actually we already have this reported: https://github.com/ethereum/cpp-ethereum/issues/4584
