### ISSUE TITLE
 choco install cpp-ethereum failed

### ISSUE THREAD

**Issue by fatrat1117** [ethereum/cpp-ethereum#4865]
PS D:\share> choco install cpp-ethereum
Chocolatey v0.10.8
Installing the following packages:
cpp-ethereum
By installing you accept licenses for the packages.
cpp-ethereum not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - cpp-ethereum - cpp-ethereum not installed. The package was not found with the source(s) listed.
 If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
 Version: ""
 Source(s): "https://chocolatey.org/api/v2/"

**Comment by fatrat1117** [comment]
I follow the doc http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/installing-binaries/windows-chocolatey.html. But can not install

**Comment by gumb0** [comment]
These instructions are very outdated, sorry. We don't support chocolatey package anymore.

**Comment by fatrat1117** [comment]
then, how to install it if I do not want to build? where is the latest installation doc?

**Comment by gumb0** [comment]
At the moment it's only possible to build from source
