### ISSUE TITLE
how can i transfer eth by client

### ISSUE THREAD

**Issue by ruoshui1314** [ethereum/cpp-ethereum#4869]
how can i get the balance of the special address  and how can i transfer the balance to other address. thank you

**Comment by gumb0** [comment]
If you need corresponding RPC methods, please refer to https://github.com/ethereum/wiki/wiki/JSON-RPC

**Comment by ruoshui1314** [comment]
It is nice to hear from you.How do I exactly check transfer to another address successful ?
Should I check eth_getTransactionByHash several seconds or any other suggestions?
thank you

**Comment by axic** [comment]
This question is better suited for https://ethereum.stackexchange.com
