### ISSUE TITLE
Update JSON-RPC wiki page

### ISSUE THREAD

**Issue by gumb0** [ethereum/cpp-ethereum#4871]
https://github.com/ethereum/wiki/wiki/JSON-RPC
The instructions to start HTTP RPC server of `eth` are not up-to-date and should be replaced with instructions to start `jsonrpcproxy.py`

**Comment by bartleyg** [comment]
@gumb0 should this just be changed to
`scripts/jsonrpcproxy.py ~/.ethereum/geth.ipc http://127.0.0.1:8545`?

**Comment by gumb0** [comment]
Yes, it should be mentioned that it should be started together with the node.
`~/.ethereum/geth.ipc` argument may be left out, it's default on linux and macos anyway.

Also `eth` is now renamed to `aleth`

**Comment by bartleyg** [comment]
Would this work?

### C++

First start the node by running `aleth` application:
```bash
build/aleth/aleth
```

Then start the JSON-RPC proxy (defaults to '~/.ethereum/geth.ipc' and 'http://127.0.0.1:8545'): 
```bash
scripts/jsonrpcproxy.py
```

If you use non-default IPC path or JSON-RPC options, you can specify  :
```bash
scripts/jsonrpcproxy.py <path to your node's geth.ipc> <URL for this proxy server>
```

**Comment by gumb0** [comment]
@bartleyg  Yes, that's fine, can you edit the wiki page?

**Comment by bartleyg** [comment]
@gumb0 I made the change https://github.com/ethereum/wiki/wiki/JSON-RPC/85c24ddda45130a54c20d24f4012ecc6ec9ad1e1

You can close this issue.

**Comment by gumb0** [comment]
@bartleyg  Thank you for your help!
