### ISSUE TITLE
Setting Genesis Previous hash lead to crash, if called BLOCKHASH(0)

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#4877]
if genesis has PreviousHash set to 
`5e20a0453cecd065ea59c37ac63e079ee08998b6045136a8ce6635c7912ec0b6`

and if you run this code

```
0x7f000000000000000000000000000000000000000000000000000000000000c3507f00000000000000000000000000000000000000000000000000000000000000017f000000000000000000000000000000000000000000000000000000000000000040
```

cpp eth crashes with rong RLP exception.

**Comment by pirapira** [comment]
How can I reproduce this?  Through RPC?

**Comment by winsvega** [comment]
you will need to start a client with such a genesis and send a transaction with this code

**Comment by pirapira** [comment]
Can you paste the genesis file, and the command to launch the client?

**Comment by gumb0** [comment]
I think genesis parent hash must be 0 according to YP, right @pirapira ? So we should reject it somewhere when initializing the blockchain. For the call stack where it crashes (I saw it on @winsvega's machine), non-zero parent hash is a reasonable assumption to make.

**Comment by pirapira** [comment]
@gumb0 that's true.  The parent hash of the genesis is specified to be zero.
