### ISSUE TITLE
Getting errors when I run 'cmake ..' from build directory.

### ISSUE THREAD

**Issue by vixadd** [ethereum/cpp-ethereum#4880]
```
CMake Error at CMakeLists.txt:91 (find_package):
  Found package configuration file:

    C:/.hunter/_Base/8f7cf6d/e425e8e/8c70749/Install/lib/cmake/Boost/BoostConfig.cmake

  but it set Boost_FOUND to FALSE so package "Boost" is considered to be NOT
  FOUND.
```

The following error is stopping the configuration.

**Comment by chfast** [comment]
At least remove the `CMakeCache.txt` file. I'd recommend cleaning the whole build directory.

**Comment by vixadd** [comment]
Thanks for responding so quickly! Sorry about that. You never learn unless you get your hands dirty...

**Comment by chfast** [comment]
No problem. CMake caches a lot of information. If the environment changes in important way (new compiler, big upstream update, new CMake version) it refuses to just update the config. You have to start from empty configuration.
