### ISSUE TITLE
Windows : ethcore.lib can't be found 

### ISSUE THREAD

**Issue by TravisBacon** [ethereum/cpp-ethereum#4887]
I followed README.md and I got the cpp-ethereum.sln . 
But when I started the program in Visual Studio 2015 (version 14.0.25431.01 Update 3) , some symbols can't be recognized and there was a LINK error told me that system can't open ethcore.lib ( as an input file ).

The error gave me a path , but when I opened the file according the path I found that it was empty .(..\libethcore\Release\ethcore.lib) (LNK 1181)

gosh I am totally confused and don't know how to do now QAQ

**Comment by halfalicious** [comment]
Have you tried building from the command line? I've been doing that successfully using both VS 2015 and VS 2017 build tools on Windows 10. The command for 2015 is here:
http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/building-from-source/windows.html#build-on-the-command-line
