### ISSUE TITLE
cmake --build . fails on ubuntu

### ISSUE THREAD

**Issue by mankan1** [ethereum/cpp-ethereum#4896]
[ 33%] Building C object libethash/CMakeFiles/ethash.dir/io.c.o
79% [2 libssl-doc 841 kB/1,491 kB 56%]                         │cc: error: unrecognized command line option ‘-fstack-protector-
85% [2 libssl-doc 1,034 kB/1,491 kB 69%]                       │strong’
91% [2 libssl-doc 1,220 kB/1,491 kB 82%]                       │make[2]: *** [libethash/CMakeFiles/ethash.dir/io.c.o] Error 1
95% [2 libssl-doc 1,339 kB/1,491 kB 90%]                       │make[1]: *** [libethash/CMakeFiles/ethash.dir/all] Error 2
100% [Working]                                                 │make: *** [all] Error 2

**Comment by mankan1** [comment]
gcc (Ubuntu 4.8.5-2ubuntu1~14.04.1) 4.8.5
Description: Ubuntu 14.04.5 LTS
95% [2 libssl-doc 1,339 kB/1,491 kB 90%] │Release: 14.04

**Comment by chfast** [comment]
Is this a clean build?
Can you send full cmake log?

We are dropping support for GCC 4.8 anytime soon.
