### ISSUE TITLE
issue of checking duplicate node in bucket within "NodeTable::noteActiveNode"

### ISSUE THREAD

**Issue by bean88** [ethereum/cpp-ethereum#4900]
https://github.com/ethereum/cpp-ethereum/blob/a24880812b7be8ceb96fa51cfad050c09fd95e97/libp2p/NodeTable.cpp#L342-L348

removed is passed by reference, so once we got an duplicate element to node, all the items after it will also be removed from the bucket

**Comment by gumb0** [comment]
Wow yeah, I think you're right, thanks for the report

**Comment by bean88** [comment]
you are welcome😁
