### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by hero5512** [ethereum/cpp-ethereum#4921]
/home/hero/Desktop/cpp-ethereum/libevm/VM.cpp: In function ‘evm_result {anonymous}::execute(evm_instance*, evm_context*, evm_revision, const evm_message*, const uint8_t*, size_t)’:
/home/hero/Desktop/cpp-ethereum/libevm/VM.cpp:42:26: error: missing initializer for member ‘evm_result::status_code’ [-Werror=missing-field-initializers]
     evm_result result = {};
                          ^
/home/hero/Desktop/cpp-ethereum/libevm/VM.cpp:42:26: error: missing initializer for member ‘evm_result::gas_left’ [-Werror=missing-field-initializers]
/home/hero/Desktop/cpp-ethereum/libevm/VM.cpp:42:26: error: missing initializer for member ‘evm_result::output_data’ [-Werror=missing-field-initializers]
/home/hero/Desktop/cpp-ethereum/libevm/VM.cpp:42:26: error: missing initializer for member ‘evm_result::output_size’ [-Werror=missing-field-initializers]
/home/hero/Desktop/cpp-ethereum/libevm/VM.cpp:42:26: error: missing initializer for member ‘evm_result::release’ [-Werror=missing-field-initializers]
/home/hero/Desktop/cpp-ethereum/libevm/VM.cpp:42:26: error: missing initializer for member ‘evm_result::create_address’ [-Werror=missing-field-initializers]
/home/hero/Desktop/cpp-ethereum/libevm/VM.cpp:42:26: error: missing initializer for member ‘evm_result::padding’ [-Werror=missing-field-initializers]
cc1plus: all warnings being treated as errors
make[2]: *** [libevm/CMakeFiles/evm.dir/VM.cpp.o] Error 1
make[1]: *** [libevm/CMakeFiles/evm.dir/all] Error 2
make: *** [all] Error 2

**Comment by gumb0** [comment]
If you use GCC 4.8, we've dropped the support for it, you should update the compiler

**Comment by gumb0** [comment]
This was definitely the error I saw with GCC4
