### ISSUE TITLE
download project dependenct library "leveldb" not found

### ISSUE THREAD

**Issue by codinggg** [ethereum/cpp-ethereum#4929]
Hi, I want to build this client project , and follow README.md file. When I install cmake and type shell

`scripts/install_deps.bat` 

and show me this error
`Downloading leveldb-1.2.tar.gz
ERROR! Downloading 'leveldb-1.2.tar.gz' failed.
-- URL:   https://github.com/ethereum/cpp-dependencies/releases/download/vc140/leveldb-1.2.tar.gz
-- Error: 7 "Couldn't connect to server"`

It's mean this file is not exist.

**Comment by chfast** [comment]
It does: https://github.com/ethereum/cpp-dependencies/releases/download/vc140/leveldb-1.2.tar.gz.
