### ISSUE TITLE
CI: Nightly full tests

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#4930]
Configure Circle CI to run nightly tests: i.e. `testeth -- --all`.

**Comment by chfast** [comment]
cc @gumb0 @winsvega

**Comment by winsvega** [comment]
This will require to implement test RPC methods in cpp client. and then we could run tests via RPC. 
Tests via RPC are 10 times slower so I hope that running it on threads will help to achieve reasonable testing time.

**Comment by chfast** [comment]
It has nothing to do with RPC tests.

**Comment by farfromunique** [comment]
@chfast I'm happy to work on this (it looks pretty straightforward). I have a couple questions about it:  
* What environment(s)? I'm assuming all
* What Branch(es)? Just `develop`?
* Are there build steps in the standard `aleth` jobs that are not needed for the nightly jobs? I'm assuming i can remove the "test" and "test-evmc-interpreter" jobs, as they would be duplicating effort.

**Comment by chfast** [comment]
@farfromunique We don't want to remove any testing, actually we want more: `testeth -- --all`.

**Comment by farfromunique** [comment]
@chfast does `testeth -- --all` cover the same tests as either of these?  
* `test/testeth -t GeneralStateTests -- --vm interpreter`  
* `ctest --output-on-failure -j $TEST_PARALLEL_JOBS`

I only removed the "test" and "test-evmc-interpreter" because i figured "testeth -- --all" included both of them.

**Comment by winsvega** [comment]
I think it only runs tests for default vm

**Comment by gumb0** [comment]
We are kind of a platform for running various VMs now, maybe nightly tests should cover several of them
