### ISSUE TITLE
cpp-ethereum cannot work with ethminer in private network

### ISSUE THREAD

**Issue by azazhu** [ethereum/cpp-ethereum#4958]
**OS:**
Ubuntu 16.04.4 LTS
**Issue:**
In private network, I launch cpp-ethereum and scripts/jsonrpcproxy.py. but ethminer fails to get work.
scripts/jsonrpcproxy.py prints:
"127.0.0.1 - - [16/Apr/2018 18:07:57] "POST / HTTP/1.1" 200" 
and ethminer prints:
_"not-connected
18:06:16|getwork | Retrying in 2 ...
18:06:17|getwork | Retrying in 1 ...
18:06:19|getwork | Failed getting work!
18:06:19|getwork | Disconnected from 127.0.0.1"_
-in public network, cpp-ethereum can work with ethminer
-in public/private network, geth can work with ethminer
**Repro:**
cmdline of cpp-ethereum:
_./eth --genesis .../genesis.json -m on -v 5  --network-id 45678 --ipc --listen 30309 --port 30309 --db-path .../data --private "private_eth_45678"_
cmdline of scripts/jsonrpcproxy.py:
_scripts/jsonrpcproxy.py .../geth.ipc http://127.0.0.1:8545_
cmdline of ethminer:
_./ethminer  -U --cuda-devices 2 -F http://127.0.0.1:8545_
screen of scripts/jsonrpcproxy.py:
_127.0.0.1 - - [16/Apr/2018 18:24:47] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Apr/2018 18:24:48] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Apr/2018 18:24:48] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Apr/2018 18:26:40] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Apr/2018 18:26:40] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Apr/2018 18:26:41] "POST / HTTP/1.1" 200 -_
screen of ethminer:
  _m  18:37:15|ethminer|  not-connected
  18:37:15|getwork |  Failed getting work!
  18:37:15|getwork |  Disconnected from 127.0.0.1
  18:37:15|getwork |  Retrying in 3 ... 
  18:37:16|getwork |  Retrying in 2 ... 
  18:37:17|getwork |  Retrying in 1 ... 
  18:37:19|getwork |  Failed getting work!
  18:37:19|getwork |  Disconnected from 127.0.0.1_
screen of cpp-ethereum
  _✘  18:36:28.817|eth  ODD: Import queue contains a block with future time.
⧎ ◌  18:36:28.850|p2p|6f6cfcca…|eth/v1.3.0/Linux/g++/Interpreter/RelWithDebInfo/cf60d417/  Status: 63 / 45678 / #33e3ec67… , TD: 131074 = #dbdd1751…
⧎ ○  18:36:28.850|p2p|6f6cfcca…|eth/v1.3.0/Linux/g++/Interpreter/RelWithDebInfo/cf60d417/  Requesting 1  block headers starting from 4294967295 
⧎ ◌  18:36:28.851|p2p|6f6cfcca…|eth/v1.3.0/Linux/g++/Interpreter/RelWithDebInfo/cf60d417/  GetBlockHeaders ( 4294967295 max: 1 skip: 0 )
⧎ ◌  18:36:28.851|p2p|6f6cfcca…|eth/v1.3.0/Linux/g++/Interpreter/RelWithDebInfo/cf60d417/  BlocksHeaders ( 0 entries) : NoMoreHeaders
18:36:29.817|eth  Tried to seal sealed block...
18:36:30.818|eth  Tried to seal sealed block...
18:36:31.818|eth  Tried to seal sealed block...
18:36:32.818|eth  Tried to seal sealed block...
18:36:33.819|eth  Tried to seal sealed block...
18:36:34.819|eth  Tried to seal sealed block..._

**Comment by chfast** [comment]
My guess is `eth_getWork` does not work in private mode. @gumb0 @winsvega @yann300 are you able to quickly check this?

**Comment by gumb0** [comment]
The code looks like it should work as long as `genesis.json` has `"sealEngine": "Ethash"`


eth log looks like sync requests unreasonable block number:
```
⧎ ○ 18:36:28.850|p2p|6f6cfcca…|eth/v1.3.0/Linux/g++/Interpreter/RelWithDebInfo/cf60d417/ Requesting 1 block headers starting from 4294967295
```
@azazhu What do you have in `genesis.json` for `daoHardforkBlock`? Try using `"daoHardforkBlock": "0x00"`

**Comment by winsvega** [comment]
setting daoHardforkBlcok to 0  will require next 10 blocks to have specific extradate field. otherwise blocks will be considered invalid.

**Comment by gumb0** [comment]
But cpp-ethereum doesn't enforce this rule I think, neither in block validation nor in mining.
Ropsten lives without it; setting daoHardforkBlock to 0 means never do DAO transfers.

**Comment by azazhu** [comment]
here is my genesis.json. Do I miss some key/value?
{
        "nonce": "0x0000000000000042",
	"difficulty": "0x020000",
	"mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
	"author": "0x0000000000000000000000000000000000000000",
	"timestamp": "0x00",
	"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
	"extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
	"gasLimit": "0x4c4b40"
	"alloc": {}
}

**Comment by azazhu** [comment]
Updated genesis.json. But still doesn't work.
{
        "nonce": "0x0000000000000042",
        "difficulty": "0x020000",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "author": "0x0000000000000000000000000000000000000000",
        "timestamp": "0x00",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "extraData": "0x11bbe8db4e347b4e8c937c1c8370e4b5ed33adb3db69cbdb7a38e1e50b1b82fa",
        "gasLimit": "0x4c4b40"
        "alloc": {}
        **"sealEngine": "Ethash"
        "daoHardforkBlock": "0x00"**
}

**Comment by gumb0** [comment]
I see, you specify only genesis block with `--genesis` but not any chain params, and by default it's not `Ethash`, but `NoProof`.

Try using `--config` instead of `--genesis`, the format of the file should be similar to this:
https://github.com/ethereum/cpp-ethereum/blob/55c63cf616c7c612c319b54f7beff704583b4eb5/libethashseal/genesis/test/constantinopleTest.cpp#L21-L63

**Comment by azazhu** [comment]
thanks guys. It is not a bug. 
After using @gumb0 's genesis.json, ethminer can work with eth in private network.
We can close this issue.Sorry for the wrong alarm.

**Comment by chfast** [comment]
No problem, it was also beneficial to us.

**Comment by gumb0** [comment]
I wonder if anyone still needs `--genesis`, the default chain params it creates are not clear to anyone

**Comment by chfast** [comment]
I would go with having single JSON config and one way of loading it.
