### ISSUE TITLE
Implement Hybrid Casper FFG

### ISSUE THREAD

**Issue by gumb0** [ethereum/cpp-ethereum#4985]
Summary of what should be done according to [EIP-1011](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1011.md).

- [ ] At fork block deploy SigHasher, PurityChecker and Casper contracts https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1011.md#deploying-casper-contract
This is similar to how we deploy BlockHash contract, see `Block::updateBlockhashContract()`
- [ ] Once at each epoch start call Casper contract to init epoch https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1011.md#initialize-epochs
This is similar to how BlockHash contract is called each block, see `Block::updateBlockhashContract()`

#### Handling vote transactions 
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1011.md#casper-votes
- [ ] Allow zero signature transactions execution - we already have this mostly implemented for Account Abstraction EIP
- [ ] Make sure we can send out vote transactions through RPC (currently we reject transactions with 0 gas price)
- [ ] Keep all vote transactions at the end of the block
  - [ ] Enforce this in block validation - should be easy
  - [ ] Enforce this in mining/pending block construction - might be problematic, as currently we just append new pending transactions to the end of the pending block. We probably would need to split the pending block to "block without all vote transactions" and "block after applying vote transactions".
- [ ] Track gas spent on votes separately and check that it doesn't exceed block gas limit
- [ ] Unsuccessful vote transactions are not included into the block
  - [ ] Enforce this in block validation
  - [ ] Enforce this in mining/pending block construction
  - [ ] Remove unsuscessful votes from pending transaction list

#### New fork choice rules
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1011.md#fork-choice
- [ ] When we check whether current canonical chain chainges, instead of comparing only `totalDifficulty`, use the new rules taking into account `highest_justified_epoch`, finalization of blocks etc. (these rules are still not completely clear to me) This check is currently in `BlockChain::insertBlockAndExtras()` https://github.com/ethereum/cpp-ethereum/blob/b387b5713738da12444af8d3a0f6390f2c87b76e/libethereum/BlockChain.cpp#L801-L802

This might require some changes in the database, like we might store the current last finalized block, fork score in each block details etc.

See also relevant python implementation  https://github.com/karlfloersch/pyethereum/blob/a66ab671e0bb19327bb8cd11d69664146451c250/ethereum/hybrid_casper/chain.py#L183

- [ ] https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1011.md#block-reward Change POW block rewards

#### New command line parameteres
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1011.md#client-settings
- [ ] `--casper-fork-choice` -- enables/disables new fork choice rules
- [ ] `--non-revert-min-deposit` -- used in fork choice logic
- [ ] `--exclude`  -- used in fork choice logic
- [ ] `--join-fork`  -- somewhat similar to `rewindToBlock` But also updates finalized epoch/block values in the DB
- [ ] (optional) `--monitor-votes` - monitor vote transactions for slashing conditions and notify Casper contracts about them

**Comment by djrtwo** [comment]
Just published some updates to the EIP that affect some of the components of this issue. See the changelog [here](https://github.com/djrtwo/EIPs/issues/5).

**Comment by 5chdn** [comment]
Are you still planning to do this?

**Comment by gumb0** [comment]
@5chdn We don't, as the plans for Casper & sharding changed significantly, I will close this issue
