### ISSUE TITLE
install Cmake in Windows failed

### ISSUE THREAD

**Issue by StupidTAO** [ethereum/cpp-ethereum#4989]
**after the command 'scripts/install_cmake.sh --prefix /usr/local', execute the fllowing** 
mkdir build; cd build  
cmake ..

**exist the error message:**
Downloading CMake (https://cmake.org/files/v3.7/cmake-3.7.1-MINGW32_NT-10.0-WOW-x86_64.tar.gz)...
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by chfast** [comment]
Do not use this script to install CMake, just download the CMake from their web page. The script is only CI linux / macOS builds.

**Comment by StupidTAO** [comment]
thank you！
