### ISSUE TITLE
libevm missing initializer

### ISSUE THREAD

**Issue by red0bear** [ethereum/cpp-ethereum#5004]
There is something missing folks ? I want to compile but seems something is missing. Someone
could give some help ?

cpp-ethereum/libevm/VM.cpp: In function ‘evmc_result {anonymous}::execute(evmc_instance*, evmc_context*, evmc_revision, const evmc_message*, const uint8_t*, size_t)’:
cpp-ethereum/libevm/VM.cpp:44:27: error: missing initializer for member ‘evmc_result::status_code’ [-Werror=missing-field-initializers]
     evmc_result result = {};
                           ^
cpp-ethereum/libevm/VM.cpp:44:27: error: missing initializer for member ‘evmc_result::gas_left’ [-Werror=missing-field-initializers]
cpp-ethereum/libevm/VM.cpp:44:27: error: missing initializer for member ‘evmc_result::output_data’ [-Werror=missing-field-initializers]
cpp-ethereum/libevm/VM.cpp:44:27: error: missing initializer for member ‘evmc_result::output_size’ [-Werror=missing-field-initializers]
cpp-ethereum/libevm/VM.cpp:44:27: error: missing initializer for member ‘evmc_result::release’ [-Werror=missing-field-initializers]
cpp-ethereum/libevm/VM.cpp:44:27: error: missing initializer for member ‘evmc_result::create_address’ [-Werror=missing-field-initializers]
cpp-ethereum/libevm/VM.cpp:44:27: error: missing initializer for member ‘evmc_result::padding’ [-Werror=missing-field-initializers]
cpp-ethereum/libevm/VMCalls.cpp: In member function ‘void dev::eth::VM::caseCreate()’:
cpp-ethereum/libevm/VMCalls.cpp:141:29: error: missing initializer for member ‘evmc_message::destination’ [-Werror=missing-field-initializers]
         evmc_message msg = {};

**Comment by gumb0** [comment]
Probably you are using too old compiler, we don't support GCC older than 5

**Comment by red0bear** [comment]
Hummmmm thats strange  .... cause it start do that cause evmc_message msg = {}; and evmc_result result = {}; are empty on initialization.

**Comment by chfast** [comment]
What compiler version do you have?

**Comment by red0bear** [comment]
gcc version 4.8.5 (SUSE Linux)

**Comment by Tejas9999** [comment]
Upgrade GCC compiler to GCC-5. Works with upgraded compiler
