### ISSUE TITLE
eth doesn't support web3.eth.sendSignedTransaction

### ISSUE THREAD

**Issue by halfalicious** [ethereum/cpp-ethereum#5013]
When poking around in the codebase I noticed that eth doesn't appear to support `web3.eth.sendSignedTransaction` ([API doc](https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendsignedtransaction)) - I don't see any function called `Eth::eth_sendSignedTransaction` and searching the codebase for `sendSignedTransaction` didn't return any hits. Additionally:

```
C:\Users\nilse\temp>geth attach
Welcome to the Geth JavaScript console!
	
instance: eth/v1.3.0/Windows/msvc/Interpreter/RelWithDebInfo/94828523*/
coinbase: 0x0000000000000000000000000000000000000000
at block: 3201865 (Wed, 09 May 2018 20:34:10 PDT)
modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 web3:1.0
	
> web3.eth.sendSignedTransaction
undefined
```

**Comment by gumb0** [comment]
I think it's called `eth_sendRawTransaction` at the RPC levehttps://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendrawtransactionl 
And we support it

**Comment by halfalicious** [comment]
Ah, so to support `web3.eth.sendSignedTransaction` presumably someone just needs to add a JSON-RPC function which calls `Eth::eth_sendRawTransaction?`

**Comment by gumb0** [comment]
We have it already https://github.com/ethereum/cpp-ethereum/blob/ec23ff4a5890dad54171099bb0662c49fbd25493/libweb3jsonrpc/Eth.cpp#L318

**Comment by gumb0** [comment]
geth's console calls it also `web3.eth.sendRawTransaction`, so if you do it through geth, use this.

If you would do that through web3.js I guess `sendSignedTransaction` would call `eth.sendRawTransaction`

**Comment by halfalicious** [comment]
Ah, it looks like `sendSignedTransaction` replaced `sendRawTransaction ` in [web3.js 1.0](http://web3js.readthedocs.io/en/1.0/index.html). For what it's worth, it looks like geth doesn't support `web3.eth.sendSignedTransaction` either: 

```
C:\Users\nilse\temp>geth attach
Welcome to the Geth JavaScript console!

instance: Geth/v1.7.2-stable-1db4ecdc/windows-amd64/go1.9
coinbase: 0x1cbb11b72a335b709a61d22bca90f7e54bfcf8b1
at block: 2336354 (Mon, 25 Dec 2017 17:53:31 PST)
 datadir: C:\Users\nilse\AppData\Roaming\Ethereum\testnet
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> web3.eth.sendSignedTransaction
undefined
```

**Comment by gumb0** [comment]
I still think `sendSignedTransaction` is just the name for this thing in higher level web3.js 1.0. At RPC level the method in all clients is still called `sendRawTransaction` and will probably continue like that, it's not like `sendSignedTransaction` is "not supported". It's just web3.js calls `sendRawTransaction` under the hood.

geth's console doesn't use web3.js 1.0.

**Comment by halfalicious** [comment]
Thanks for the clarification @gumb0 , I didn't fully understand the distinction between the web3 APIs and eth's RPC level but after re-reading your replies it makes perfect sense.

Sorry about the mixup regarding geth's console version, I had assumed that the 1.0 next to each module name in the console module list was a version number but it turns out you get the version number by calling `web3.version` and you're right, geth console is using 0.20.1. Since the `sendSignedTransaction` isn't defined in 0.20.1, the current behavior is by design.
