### ISSUE TITLE
web3.eth.signTransaction appears to also submit the transaction

### ISSUE THREAD

**Issue by halfalicious** [ethereum/cpp-ethereum#5014]
When poking around in the codebase I noticed that `web3.eth.signTransaction` appears to both sign AND submit the signed transaction, whereas according to the [API behavior documentation](https://web3js.readthedocs.io/en/1.0/web3-eth-accounts.html#signtransaction) it's supposed to only sign the transaction. This signed transaction can then be submitted via `web3.eth.sendSignedTransaction` ([API doc link](https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendsignedtransaction)). Note that eth doesn't currently implement `web3.eth.sendSignedTransaction`, I've filed issue #5013  to track this. 

Additional details:

`Eth::eth_signTransaction()` calls `AccountHolder::Authenticate()`, and both `AccountHolder `subclasses (`FixedAccountHolder `and `SimpleAccountHolder`) implement this abstract function with implementations which submit the signed transaction e.g.:

https://github.com/ethereum/cpp-ethereum/blob/3db4290a7dcca4bb3241ae1fd9189ec518edbd1b/libweb3jsonrpc/AccountHolder.cpp#L132-L136

**Comment by gumb0** [comment]
Does go-ethereum not send it?

**Comment by halfalicious** [comment]
Correct, as far as I can tell geth only signs but doesn't send. Here's output of a test I ran yesterday, note that the signed tx (hash: 0xa91fc20b2...) doesn't show up in the pending tx set:

```
> web3.eth.signTransaction({to: '0x884ae368b946a7e5b11462b1333248388b463cc3', value:1000})
{
  raw: "0xf8670285029470747983015f9094884ae368b946a7e5b11462b1333248388b463cc38203e8802aa09b7eb00e2675c4c8e905d70b98466b7e93a394905b28438c4d6c294b03313f59a0442739b945a09562e1656d69c3b129775dbe7cde772d819fac43dd756a16eb05",
  tx: {
    gas: "0x15f90",
    gasPrice: "0x294707479",
    hash: "0xa91fc20b253af1e23f42d3820179c5cabf9385e3a0f0de69f1777bc297ddab8b",
    input: "0x",
    nonce: "0x2",
    r: "0x9b7eb00e2675c4c8e905d70b98466b7e93a394905b28438c4d6c294b03313f59",
    s: "0x442739b945a09562e1656d69c3b129775dbe7cde772d819fac43dd756a16eb05",
    to: "0x884ae368b946a7e5b11462b1333248388b463cc3",
    v: "0x2a",
    value: "0x3e8"
  }
}
> web3.eth.pendingTransactions
[{
    blockHash: null,
    blockNumber: null,
    from: "0x1cbb11b72a335b709a61d22bca90f7e54bfcf8b1",
    gas: 90000,
    gasPrice: 10526315789,
    hash: "0x7375026ff56417cb3e9c4c73a705e956174393261dd0ff057e74bd87434e2c72",
    input: "0x",
    nonce: 0,
    r: "0x98e84508f9f79b38cd240841e65486441b6838194c46e429880d02b6ae38951e",
    s: "0x6236869b5e094d36dd5b663f6f86289f7adf7183a708e68c28b135a893970f57",
    to: "0x884ae368b946a7e5b11462b1333248388b463cc3",
    transactionIndex: 0,
    v: "0x2a",
    value: 1000000000000000
}, {
    blockHash: null,
    blockNumber: null,
    from: "0x1cbb11b72a335b709a61d22bca90f7e54bfcf8b1",
    gas: 90000,
    gasPrice: 11080332409,
    hash: "0x157244d1a61cb9c7d935c4ac97a8c0dc666bc907e27b5c31a50286798d4a0eaa",
    input: "0x",
    nonce: 1,
    r: "0x928f327e22419434186c30567433077f84506d261b23aa1e0401e0f8f7ec4222",
    s: "0x701e1919dec8dc8fa93902f306e439f594e4aff9305c3d246bc4b66dc0a1e515",
    to: "0x884ae368b946a7e5b11462b1333248388b463cc3",
    transactionIndex: 0,
    v: "0x29",
    value: 1000
}]
>

```

**Comment by halfalicious** [comment]
I've taken a quick look at this, my proposed changes involve decoupling tx submission from account authentication and decoupling tx signing from tx submission. This will also make it significantly easier to implement `web3.eth.sign` (i.e. fix #4269 ). Change details:

1. Update `SimpleAccountHolder::Authenticate` and `FixedAccountHolder::Authenticate` to just perform account authentication...they will return the authentication result code and the secret in the form of `std::pair<TransactionRepercussion, Secret>`.

2. Update `Client::submitTransaction` to accept a signed transaction (i.e. a `Transaction ` object rather than `TransactionSkeleton`) and just validate + import that transaction into the transaction queue as before. This will of course also require an update to the signature of the overridden virtual function (`Interface::submitTransaction`).

3. Update the RPC function `Eth::eth_signTransaction` to create the signed transaction object using the `Secret `returned by `SimpleAccountHolder::Authenticate` and return a JSON version of the object to the caller.

On a related note, I don't see `FixedAccountHolder` being instantiated by anything but tests...can this class be removed? 

@gumb0 / @chfast : Would love to get your thoughts on this

**Comment by gumb0** [comment]
This sounds good, but I'm not sure why the change 2 is needed? 
`eth_signTransaction` could create `TransactionSkeleton`, get `Secret` from `SimpleAccountHolder::authenticate`, then use `Client::submitTransaction` in its current form like `submitTransaction(skeleton, secret)`. Am I missing something?

`FixedAccountHolder` is still useful for tests I think, but nowhere else, so we could move it into testeth

**Comment by halfalicious** [comment]
Actually, you're right - we don't need to change the signature of `Client::submitTransaction`. I think my original motivation was wanting to scope down the function to just the minimum functionality required (i.e. validating and submitting a tx), but in retrospect I think it makes sense for the client to also sign the transaction.
