### ISSUE TITLE
Mining deadlocks

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#5047]
It looks like all mining threads quickly deadlocks after the fist round of mining waiting on conditional variable in Worker class.

eth:
```
eth/eth --private ethash --config ../ewasm.json -a aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa -m yes -C -t 1
```

This is critical issue with eWASM testnet.

**Comment by gumb0** [comment]
Can you describe steps to reproduce?

**Comment by gumb0** [comment]
Does it happen with less mining threads?

**Comment by chfast** [comment]
Yes, it happens with single mining thread. I will check if the backtrace is not smaller in this case.

**Comment by chfast** [comment]
Oh it happens after a block is mined.

**Comment by gumb0** [comment]
The stack looks like mining threads are going to finish (and wait on CV in the very end)

**Comment by chfast** [comment]
Backtrace updated.

**Comment by gumb0** [comment]
Blocks are mined fine for me on Windows with 4 threads and Debug build. I'll try RelWithDebInfo

**Comment by gumb0** [comment]
@chfast try this https://github.com/ethereum/cpp-ethereum/pull/5048

**Comment by gumb0** [comment]
I reproduce it on Linux, and the fix doesn't help. It looks more like some problem in the `Client` class than something with the mining threads.
Looks like `Client::rejigSealing()` is not working for some reason, while on Windows it keeps outputting `Rejigging seal engine...` to log

**Comment by gumb0** [comment]
Ok with `--no-discovery` addede to the command line it is working fine.

Without it `BlockChainSync` starts the sync for some reason (But I think it should not) and because of this the sealing stops.

**Comment by gumb0** [comment]
Wait, no, now it works for me even without `--no-discovery`
And actually `--private` should disable discovery by itself.

**Comment by gumb0** [comment]
@pirapira take config from https://github.com/ewasm/testnet/blob/master/ewasm-testnet-cpp-config.json

**Comment by chfast** [comment]
Ok, so it seems it's not a deadlock. It works with `--no-discovery`. My node is bombarded with connections from Ethereum mainet, but those should be ignored.

**Comment by gumb0** [comment]
This is anyway weird because when I reproduced it it seemed that sync was started but was not making any progress. It should start downloading headers and blocks etc.

**Comment by gumb0** [comment]
Also `--private` should disable discovery, so there should be no difference between `--private` and `--no-discovery` and only `--private`

**Comment by gumb0** [comment]
BTW adding `--pin` I think should disable other peers connecting to you

**Comment by chfast** [comment]
Ok, with changed config it also works. There must be some eWASM nodes there... Sorry for false report.

Still would like to add a log that mining stopped because the sync is not finished.
