### ISSUE TITLE
Building on Windows in excruciatingly slow

### ISSUE THREAD

**Issue by rustyx** [ethereum/cpp-ethereum#5056]
For some reason on Windows CMake is building Boost one module at a time.
It extract the entire Boost package, configures it numerous times, which result in cmake configure times upwards of **3 hours**.

Wouldn't it be great to extract and configure Boost only once, specifying all the needed packages in a single b2 command?

Something like this: `b2 address-model=64 threading=multi runtime-link=static link=static variant=release variant=debug --with-program_options --with-filesystem --with-system --with-thread --with-context --with-fiber --with-log stage`

**Comment by chfast** [comment]
It's done once. But I agree Windows sucks. Unfortunately, there is nothing we can do about it.
