### ISSUE TITLE
Mining problems

### ISSUE THREAD

**Issue by vadimVoloshanov** [ethereum/cpp-ethereum#5063]
OS:
Ubuntu 16.04.4 LTS
Issue:
1. «Import queue contains a block with future time.»
In private network, I launch cpp-ethereum but ethminer fails to get work.
Message: «Import queue contains a block with future time.»

![2018-06-01 10-44-29](https://user-images.githubusercontent.com/30472334/40840499-a2ff0fe0-65af-11e8-9e9c-212178c59c97.png)

I know that problem emerge when we create several blocks in 1 seconds. But i don't know what thats correctly behavior and we can't creates blocks more frequent than 1 in second because "timestamp" be the same or this it bug and message «Import queue contains a block with future time.» mustn't emerge.
If thats not correct behavior how i can fix this without raise «difficulty»?

2. End of the «epoch»
After the epoch ends (30,000 blocks), the standard cpp-ethereum node cpu miner can not create the block(it is solved by restarting the node). Is this behavior correct and if not how to solve it?

**Comment by chfast** [comment]
By Ethereum rules you are not allowed to create a block with the same timestamp as the parent block. So it looks the block producer artificially bumps the timestamp but later the block import module complains about it.

It's hard to decide where to set the limit for future blocks. What I can do about it is to check what is the value in other clients.

**Comment by vadimVoloshanov** [comment]
Thank you for the answer of the first question, but what about second question about end "epoch"?

**Comment by chfast** [comment]
Sorry, I missed the second question.

How long have you waited for the block 30000 to be mined? The CPU miner has to create new DAG. It does that on the fly, usually takes 1 ~ 2 minutes so the hashrate is low at the beginning of new epoch.
Try waiting a bit more. You can also see the hash rate via RPC.

**Comment by vadimVoloshanov** [comment]
I waited about a day, DAG at the start of a new era was not created. After restarting the node DAG was generated and the blocks continued to be generated. This is not a critical issue, it is solved by restarting the node, but I would like to understand how to solve this problem without restarting node

**Comment by chfast** [comment]
What version do you use?
