### ISSUE TITLE
Bug in Instruction declration

### ISSUE THREAD

**Issue by MattRh** [ethereum/cpp-ethereum#5094]
Declaration for Instruction::XOOR is missing, Instruction::XOR is declared twice instead.
This bug may be critical as XOOR declaration is lower and so can(should?) overwrite standart XOR declaration and therefore lead to GAS usage misscalculation.

Issue is here: https://github.com/ethereum/cpp-ethereum/blob/70d52b8f384126c75ae1830b6364616fc2eb1da1/libevm/Instruction.cpp#L183

**Comment by axic** [comment]
What is XOOR?

**Comment by MattRh** [comment]
@axic idk, why is it introduced, but it was declared here: https://github.com/ethereum/cpp-ethereum/blob/70d52b8f384126c75ae1830b6364616fc2eb1da1/libevm/Instruction.h#L199

**Comment by axic** [comment]
Good catch, `XOOR` is part of the "SIMD proposal".
