### ISSUE TITLE
Build error main.cpp libmpir in /lib64 and libff in /lib

### ISSUE THREAD

**Issue by NickNamerr** [ethereum/cpp-ethereum#5106]
There are something wrong in latest building procedure:
in file cmake/ProjectLibFF.cmake :

set(libff_library "${prefix}/**lib**/${CMAKE_STATIC_LIBRARY_PREFIX}ff${CMAKE_STATIC_LIBRARY_SUFFIX}")

but in cmake/ProjectMPIR.cmake :
set(MPIR_LIBRARY "${prefix}/${**_CMAKE_INSTALL_LIBDIR_**}/${CMAKE_STATIC_LIBRARY_PREFIX}mpir${CMAKE_STATIC_LIBRARY_SUFFIX}")

Manually changing does not help at all, libff.a compiling into build/deps/lib/ and libmpir.a into/build/deps/lib64

Scanning dependencies of target aleth
[ 68%] Building CXX object aleth/CMakeFiles/aleth.dir/AccountManager.cpp.o
[ 68%] Building CXX object aleth/CMakeFiles/aleth.dir/main.cpp.o
gmake[2]: *** No rule to make target 'deps/lib/libmpir.a', needed by 'aleth/aleth'.  Stop.

**Comment by NickNamerr** [comment]
copied files from lib to lib64 and vice versa.

compiled till :
[ 99%] Building CXX object test/CMakeFiles/testeth.dir/unittests/libweb3jsonrpc/jsonrpc.cpp.o
gmake[2]: *** No rule to make target 'deps/src/binaryen-build/lib64/libwasm.a', needed by 'test/testeth'.  Stop.
gmake[1]: *** [CMakeFiles/Makefile2:1313: test/CMakeFiles/testeth.dir/all] Error 2
gmake: *** [Makefile:163: all] Error 2

**Comment by NickNamerr** [comment]
Faced these issues on OpenSuse thumbleweed with gcc8 - testeth stuck in execution process.
Ubuntu 18.04 with gcc7 - everything compiled and testeth executed

**Comment by chfast** [comment]
This was fixed in https://github.com/ethereum/cpp-ethereum/pull/5145/commits/3960a83b6c08ed5c44a0c532722b977c88586495.
