### ISSUE TITLE
RPC response sheme 

### ISSUE THREAD

**Issue by winsvega** [ethereum/cpp-ethereum#5113]
I think the current RPC response that cpp client provide are inconsistent with geth 
https://github.com/ethereum/wiki/wiki/JSON-RPC#web3_clientversion

The result should be a json object and the actual return is stored in return field
```
// Result
{
  "id":67,
  "jsonrpc":"2.0",
  "result": "Mist/v0.9.3/darwin/go1.4.1"
}
```

**Comment by gumb0** [comment]
We return the same

**Comment by winsvega** [comment]
I see. it is the RPC session that parse the output.
