### ISSUE TITLE
Implement Skinny CREATE2 opcode

### ISSUE THREAD

**Issue by gumb0** [ethereum/cpp-ethereum#5119]
https://eips.ethereum.org/EIPS/eip-1014

I think we should have CREATE2 implementation already in place, but the formula in the latest spec slightly changed.

Some backgrund:
Account abstraction EIP where CREATE2 idea originated https://github.com/ethereum/EIPs/pull/208
Some discussion in Skinny CREATE2 PR https://github.com/ethereum/EIPs/pull/1014

**Comment by gumb0** [comment]
This will involve passing `salt` parameter through EVMC

**Comment by axic** [comment]
I think this is done now, via #5121 and #5125.
