### ISSUE TITLE
Allow codeFromFile field in account in config

### ISSUE THREAD

**Issue by gumb0** [ethereum/cpp-ethereum#5136]
Currently it's being rejected as invalid by validation form `ValidationSchemes.cpp`. It should be fixed as it's supported by config parser.

**Comment by winsvega** [comment]
is this correct? 

1) c_codeFromFile excludes c_code option
2) c_codeFromFile only present in genesis config
3) c_codeFromFile exclude c_precompiled option

**Comment by winsvega** [comment]
logically I think it would have been better to just parse a link to the file from the c_code field.
