### ISSUE TITLE
ethminer aborting after running

### ISSUE THREAD

**Issue by trace86** [ethereum/cpp-ethereum#5143]
I've got it to work before but I wiped the system clean and installed it again.

Everything was smooth but once I start the application i get the below error.

`ethminer -U -M 8192`
`terminate called without an active exception`
`Aborted (core dumped)`

I'm using Ubuntu 18.04, with Nvidia drivers 396, gcc5 or gcc6 (tried both) and the latest ethminer software.  

I can't find the core dump files to read the error, and have no idea what to do next.  Please help if anyone has any idea.

**Comment by chfast** [comment]
https://github.com/ethereum-mining/ethminer
