### ISSUE TITLE
AZ exception on PUSH

### ISSUE THREAD

**Issue by ethers** [ethereum/cpp-ethereum#525]
AZ version 6fa0cbf

paste this code (from dup2error test)
7f10112233445566778899aabbccddeeff00112233445566778899aabbccddeeff81600355

Click Debug and move slider to debug the first instruction, PUSH.  AZ has exception immediately.
Compare with this code
swap2error
7f10112233445566778899aabbccddeeff00112233445566778899aabbccddeeff60039155
and AZ allows the PUSH.

**Comment by debris** [comment]
That's probably outdated. Please reopen if I'm wrong
