### ISSUE TITLE
Improve UPnP support

### ISSUE THREAD

**Issue by kapacorn** [ethereum/cpp-ethereum#570]
Windows 7 and 8 issue for alethzero

*N* [ 14:13:32 | main ] Id: 8a569788…
*** [ 14:13:32 | main ] UPnP device not found.
*N* [ 14:13:32 | main ] Id: 8a569788…
!!! [ 14:13:58 | p2p ] Error reading: The semaphore timeout period has expired
*** [ 14:17:33 | main ] UPnP device not found.
*N* [ 14:17:33 | main ] Id: 8a569788…
*** [ 14:17:33 | main ] UPnP device not found.
*N* [ 14:17:33 | main ] Id: 8a569788…
*** [ 14:17:34 | main ] UPnP device not found.
*N* [ 14:17:34 | main ] Id: 8a569788…
*** [ 14:17:35 | main ] UPnP device not found.
*N* [ 14:17:35 | main ] Id: 8a569788…
*** [ 14:17:36 | main ] UPnP device not found.
*N* [ 14:17:36 | main ] Id: 8a569788…
*** [ 14:17:36 | main ] UPnP device not found.

**Comment by loreV** [comment]
Hey guys.. I found this similar to the problem I have: I receive a message "UPnP device not found" followed by "Terminating discover after 0 rounds", after clicking "Go". Is there anybody who has experienced this issue?

**Comment by debris** [comment]
should be fixed in #2022
