### ISSUE TITLE
AlethZero needs a warning for Serpent contract with no code()

### ISSUE THREAD

**Issue by linagee** [ethereum/cpp-ethereum#592]
As I found out when debugging KenK's tutorial 3 (https://forum.ethereum.org/discussion/1636/tutorial-3-introduction-to-the-javascript-api#latest), when you have a serpent contract with no code(), it does not go into the Contracts pane. Could there please be a warning when you submit such contracts to avoid this confusion in the future? Thanks.

**Comment by chriseth** [comment]
Closing as currently out of scope.
