### ISSUE TITLE
Create new ethereum address via JS API

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/cpp-ethereum#598]
I want to request an API method to create a new ethereum address; just like web3.shh.newIdentity; but then for web3.eth. 

This would allow DApps to be consistent in creating a new identity for Whisper + eth, as well as help (automated) integration testing without requiring the AlethZero UI to be used.

**Comment by debris** [comment]
I'm closing. Please reopen if it's a planned feature for upcoming releases.
