### ISSUE TITLE
macos compiler flags for 1stgen i5 and core2duo

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#661]

**Comment by debris** [comment]
@subtly , can you check if #1454 fixes the issue?

**Comment by subtly** [comment]
Update/TL;DR
I dug into my notes and resolving this in cmake would mean compiling cryptopp from source. The easiest solution would be to modify the homebrew recipe for cryptopp on the macos build-server. It's also possible that by now clang has been updated to this is no longer an issue; or, if the build-server is running in a VM or older CPU, this may not be an issue anyways.

**Comment by debris** [comment]
@subtly can we close this? We will reopen if someone reports that it's not working on possibly affected machine.
