### ISSUE TITLE
windows build instructions

### ISSUE THREAD

**Issue by step21** [ethereum/cpp-ethereum#691]
as far as I can tell, Windows build instructions for cmake are incomplete. I stilll have cryptopp from the old build process, but neither for the old buidl dir or a fresh one, cmake is able to find cryptopp (and presumably it would fail on subsequent libs too) The build instructions make it sound like it would fetch everything that is necessary. However, this does not seem to be the case.
So, what is necessary for a current build and what needs to be done by hand/what is automated?
I would very much appreciated if the build instructions would be updated.

**Comment by debris** [comment]
so `cmake -G Visual Studio 12` is valid only for cmake 2.8x
for cmake 3.x you can use `cmake -G Visual Studio 12 2013` or simply just `cmake`, cause visual studio generator is the default one for cmake 3.x

About the rest of the issues... there have been fixed some time ago. @step21 can you confirm, that everything is working fine now?

**Comment by step21** [comment]
Thanks for the clarification re cmake.
Extdep step works fine now anyway. I tested again once w/o doing a fresh git pull, then after rebuilding deps and git pull. This resulted in the following errors http://pastebin.com/uw7znq16
```
"D:\Users\Florian\cpp-ethereum\ethereum.sln" (default target) (1) ->
"D:\Users\Florian\cpp-ethereum\ALL_BUILD.vcxproj.metaproj" (default target) (2) ->
"D:\Users\Florian\cpp-ethereum\mix\mix.vcxproj.metaproj" (default target) (46) ->
"D:\Users\Florian\cpp-ethereum\mix\mix.vcxproj" (default target) (47) ->
(ClCompile target) ->
  d:\users\florian\cpp-ethereum\mix\DebuggingStateWrapper.h(91): error C2079: 'dev::mix ::QQMLMap::m_map' uses undefined class 'QMap<int,int>' [D:\Users\Florian\cpp-ethereum\m ix\mix.vcxproj]
  d:\users\florian\cpp-ethereum\mix\DebuggingStateWrapper.h(87): error C2440: 'initiali zing' : cannot convert from 'QMap<int,int>' to 'int' [D:\Users\Florian\cpp-ethereum\mix \mix.vcxproj]
  d:\users\florian\cpp-ethereum\mix\DebuggingStateWrapper.h(87): error C2439: 'dev::mix ::QQMLMap::m_map' : member could not be initialized [D:\Users\Florian\cpp-ethereum\mix\ mix.vcxproj]
  d:\users\florian\cpp-ethereum\mix\DebuggingStateWrapper.h(88): error C2228: left of ' .value' must have class/struct/union [D:\Users\Florian\cpp-ethereum\mix\mix.vcxproj]
  moc_KeyEventManager.cpp(77): error C2664: 'void KeyEventManager::keyPressed(QVariant) ' : cannot convert argument 1 from 'QVariant' to 'QVariant' [D:\Users\Florian\cpp-ether eum\mix\mix.vcxproj]
```

After doing a `git pull` there are differen errors - http://pastebin.com/15BeMaTR
So this might very well be different errors, that are very unrelated, I have no idea. Just reporting on build status on my end, looks much better, but getting it to build consistently still seems to be an issue on Windows.

**Comment by step21** [comment]
In a freshly cloned directory, with everything done as recommended I get the same errors.
http://pastebin.com/qb0y1QZB At first it seems mostly related to mix (but not only) is there an easy way to exclude mix from the build with cmake or so?

**Comment by step21** [comment]
(closed by accident, though you can close and I can open a new issue if the errors now are too unrelated)

**Comment by step21** [comment]
Closed and instead opened https://github.com/ethereum/cpp-ethereum/issues/778
