### ISSUE TITLE
'weird port being recorded: ' error message and then core dump

### ISSUE THREAD

**Issue by tglauner** [ethereum/cpp-ethereum#693]
I am running Ubuntu 14.04 and the latest cpp-ethereum build. When I start mining, then stop mining and then go back to mining I get after a while the following error in the terminal from where I run alethZero:

--- [ 06:14:11 PM | p2p ] Spawning anon
--- [ 06:14:28 PM | miner-5 ] Completing mine!
!!! [ 06:14:32 PM | p2p ] Weird port being recorded: 20202
!!! [ 06:14:32 PM | p2p ] Weird port being recorded: 112
!!! [ 06:14:54 PM | p2p ] Weird port being recorded: 7
!!! [ 06:14:54 PM | p2p ] Weird port being recorded: 10101
!!! [ 06:14:54 PM | p2p ] Weird port being recorded: 10101
!!! [ 06:15:07 PM | p2p ] Weird port being recorded: 255
!!! [ 06:15:07 PM | p2p ] Weird port being recorded: 112
!!! [ 06:15:07 PM | p2p ] Weird port being recorded: 24364
!!! [ 06:15:21 PM | p2p ] Weird port being recorded: 20202
!!! [ 06:15:21 PM | p2p ] Weird port being recorded: 10101
!!! [ 06:15:32 PM | p2p ] Weird port being recorded: 112
!!! [ 06:15:32 PM | p2p ] Weird port being recorded: 10101
!!! [ 06:15:49 PM | p2p ] Weird port being recorded: 333
!!! [ 06:15:49 PM | p2p ] Weird port being recorded: 992
!!! [ 06:15:49 PM | p2p ] Weird port being recorded: 112
!!! [ 06:15:49 PM | p2p ] Weird port being recorded: 3657
Segmentation fault (core dumped)
cmt@ubuntu:~/workspace/ethereum/cpp-ethereum/build/alethzero$

**Comment by gavofyork** [comment]
Could you grab the latest build again (btw are you on master or develop branch?) and re-run to check it's still there and get the line numbers up to date?

**Comment by tglauner** [comment]
looks good now. No crash even after I ran for an hour with multiple Go/NoGo and Mine/NoMine. You can close it. And lastly, I am on the developer branch.
