### ISSUE TITLE
neth crashes while fetching blocks on Ubuntu

### ISSUE THREAD

**Issue by caktux** [ethereum/cpp-ethereum#696]
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<dev::BadCast>'

**Comment by gavofyork** [comment]
odd... got a more detailed trace? reproducible with eth?

**Comment by caktux** [comment]
I've switched to eth since, doesn't seem reproducible as it's running fine, will try the latest and get a trace.

**Comment by caktux** [comment]
seems fine now, closing

**Comment by caktux** [comment]
spoke too soon, still happens after mining a block with neth
