### ISSUE TITLE
Better compiler detection wrt C++11

### ISSUE THREAD

**Issue by sveneh** [ethereum/cpp-ethereum#700]
still open issue by @subtly from closed PR #587 

 Test that MSVC compiler supports c++11. Error: Your compiler does not support C++11 ... OR Error: Your compiler is not tested...
Ex: Someone may try w/old MSVC that doesn't support c++11. Or, they may try with intel compiler which does support c++11 but we haven't tested.

**Comment by debris** [comment]
with cmake 3.1 it will be possible to set [CXX_STANDARD](http://www.cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html#prop_tgt:CXX_STANDARD) and [CXX_STANDARD_REQUIRED](http://www.cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD_REQUIRED.html#prop_tgt:CXX_STANDARD_REQUIRED) to require c++11
