### ISSUE TITLE
Better handle if boost exception diagnostic is not supported

### ISSUE THREAD

**Issue by sveneh** [ethereum/cpp-ethereum#701]
still open issue by @subtly from closed PR #587 

If boost exception diagnostic is not supported on a platform (Windows) , don't silently ignore that, as it is currently done e.g. in https://github.com/ethereum/cpp-ethereum/blob/develop/libdevcore/CommonData.cpp

look into formally ensuring we can use same exceptions for windows.

**Comment by arkpar** [comment]
Not the case anymore
