### ISSUE TITLE
implement structured logging in cpp-ethereum

### ISSUE THREAD

**Issue by sveneh** [ethereum/cpp-ethereum#705]
Implement the structured logging spec from @heikoheiko defined at https://github.com/ethereum/system-testing/wiki/Log-Events

This is a requirement for https://github.com/ethereum/system-testing/issues/18

**Comment by debris** [comment]
@LefterisJP can we close this?

**Comment by LefterisJP** [comment]
Implemented here: https://github.com/ethereum/cpp-ethereum/pull/1169 and here: https://github.com/ethereum/cpp-ethereum/pull/1340
