### ISSUE TITLE
Avoid crash when locale is not set

### ISSUE THREAD

**Issue by hackappcom** [ethereum/cpp-ethereum#709]
Hi, when I'm launching eth, I get  "can't allocate memory". How much memory do I need?

 ~/c/build> ./eth/eth  -u 127.0.0.1 -l 30300 -d /tmp
Ethereum (++) 0.8.0
  Code by Gav Wood, (c) 2013, 2014.
  Based on a design by Vitalik Buterin.

*N* [ 04:02:55 | main ] IP Address: 192.168.1.224  = [LOCAL]
*N* [ 04:02:55 | main ] IP Address: 192.168.56.1  = [LOCAL]
*N* [ 04:02:55 | main ] Id: f8f7a571…
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
fish: Job 1, “./eth/eth  -u 127.0.0.1 -l 30300 -d /tmp” terminated by signal SIGABRT (Abort)

**Comment by gavofyork** [comment]
Quick fix is type the following in a terminal.

```
sudo apt-get -y install language-pack-en-base
sudo dpkg-reconfigure locales
```

**Comment by dagi3d** [comment]
It happens the same to me:

    Ethereum (++) 0.8.0
      Code by Gav Wood, (c) 2013, 2014.
      Based on a design by Vitalik Buterin.

    *N* [ 10:18:20 | main ] IP Address: 10.0.2.15  = [LOCAL]
    *N* [ 10:18:20 | main ] IP Address: 192.168.33.10  = [LOCAL]
    *N* [ 10:18:20 | main ] Id: 7a50ff09…
    terminate called after throwing an instance of 'std::bad_alloc'
      what():  std::bad_alloc
    [1]    28511 abort (core dumped)  eth

I configured the locales as suggested but didn't work
Its a ubuntu 14.04(64 bit) at it was installed through the ppa

**Comment by chriseth** [comment]
Replaced by https://github.com/ethereum/webthree-umbrella/issues/169
