### ISSUE TITLE
Change of call depth limit semantics

### ISSUE THREAD

**Issue by chfast** [ethereum/cpp-ethereum#710]
From Skype chat:

Current implementation works like this: we can execute a code on max depth limit without problems unless CALL instruction is used. then current execution is killed and OOG returned.

What do you think about this change: instead of killing current execution CALL would return 0 what can mean OOG.

In current implementation the call depth limit is placed somewhere in the middle of execution unit. If a code is being executed "on the limit" you can expect some results unless CALL/CREATE is used. In other words, your instruction set is limited.
In the proposition the call depth limit is placed between excution units. If you are under the limit you can do everything you want. In the worst case you will get 0 from CALL/CREATE. If you are above the limit no code is executed.

**Comment by gavofyork** [comment]
Fixed in latest develop.

**Comment by chfast** [comment]
Thanks!
