### ISSUE TITLE
Move back to libsecp256k1 for ECDSA functions

### ISSUE THREAD

**Issue by gavofyork** [ethereum/cpp-ethereum#727]
crypto++ is slooooooow.

**Comment by subtly** [comment]
git subcodething for https://github.com/bitcoin/secp256k1

**Comment by gavofyork** [comment]
that would be good. i'll leave it to you & marek to work out the details :-D

**Comment by subtly** [comment]
Tested adding this back in last weekend and all unit tests passed. Need to sit down and work out the compile flags for all the different OS's and/or script cmake to run autogen/make/etc commands so secp256k1 makefile can make those choices for us.

**Comment by gavofyork** [comment]
testing and compiling linux and mac os - just need a windows build now.

**Comment by caktux** [comment]
I'll be more than happy to remove that libcryptopp package, good call

**Comment by subtly** [comment]
@caktux CryptoPP be replaced with openssl.

**Comment by gavofyork** [comment]
done.
