### ISSUE TITLE
flag Node's endpoint as stale

### ISSUE THREAD

**Issue by subtly** [ethereum/cpp-ethereum#737]
If outbound TCP connection fails cryptographic handshake then mark Node's endpoint as stale. We may receive updates/information about this node via discovery, however, if the update doesn't alter the node's failed endpoint then it will remain marked as stale.
It is also possible that UDP is failing (ping) and TCP is successful. Said node will only be kept if it's required and UDP endpoint is flagged as stale. (This doesn't exclude future enhancements to recover node's connectivity).

**Comment by subtly** [comment]
When availability of a publicKey:endpoint changes (publicKey is seen on another endpoint or endpoint is seen with different publicKey), stale entries should be removed from node-table. We continue to keep the nodes information but the node will not be shared with others or used for connectivity.

**Comment by gavofyork** [comment]
fixed, i guess.
