### ISSUE TITLE
Unable to download blockchain

### ISSUE THREAD

**Issue by drupalnomad** [ethereum/cpp-ethereum#759]
Fresh compile of cpp-ethereum from develop branch. .ethereum and .config/ethereum dirs deleted.

I run AlethZero and press "Go". It connects to peers, but does not download the blockchain.

It worked a few days ago.

**Comment by jorisbontje** [comment]
Same happening for me on both a clean ubuntu build as well as latest successful build on OSX. @caktux independently reported this last night on IRC: "19:40 < caktux > gah.. cpp no longer downloads blocks.."

**Comment by gavofyork** [comment]
Fixed now.

**Comment by drupalnomad** [comment]
Thanks Gav!
