### ISSUE TITLE
[AlethZero] Owned Accounts not shown upon startup

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/cpp-ethereum#776]
After starting AZ (latest develop build on OSX), the "Owned Accounts" aren't shown. After manually creating a new account (Tools > New Address), all accounts do appear. Expected is that all owned accounts do show in the "Owned Accounts" pane upon startup.

![screen shot 2015-01-12 at 10 10 58](https://cloud.githubusercontent.com/assets/620959/5700805/88b3de9e-9a43-11e4-820b-51e44094145a.png)

**Comment by gavofyork** [comment]
Fixed in commit 6e62485aa2c92ce815b8a1c1ac915413bf7df39d.
