### ISSUE TITLE
add instructions for windows build to find extdep

### ISSUE THREAD

**Issue by step21** [ethereum/cpp-ethereum#778]
Currently, as far as I can tell, after a successful build on windows pursuant to the instructions on the wiki, (at least) any exectuables dependant on Qt are not easily launchable, as certrain parts of Qt are not found, even though all compile dlls and so on were copied to the same directory. (but normal binaries such as ./eth work)
The error is 

``` 
This application failed to start because it could not find or load the Qt platform plugin "windows".

Reinstalling the application may fix this problem.
```

So, if possible, it would be really great if either the build script could aggregate all necessary parts to quickly test a build, instructions could be added what to do manually to quickly test a build under "building for windows" or at least mention somewhere where the relevant Qt parts have to be placed. Non-Windows builds are not affected, obviously.

**Comment by debris** [comment]
what are the steps to reproduce your issue? i made a clean build now, and everything was working fine.

here are the [lines](https://github.com/ethereum/cpp-ethereum/blob/develop/cmake/EthExecutableHelper.cmake#L110-L114) responsible for copying Qt plafrom plugin 'windows' to the install directory.

Please provide more details, OS version, cmake version, cmake logs and build steps

**Comment by step21** [comment]
steps to reproduce: build. build fails, f.e. everything builds but mix fails. Then even when copying most dlls manually, an executable with qt can't be run because seen above. Maybe the problem is that the 'Install' part isn't run (as it seems) Does it have to be run manually?
OS: Windows 7 Service Pack 1 (with all updates)
Build steps: 
(for extdep)
```
cmake . 
msbuild project.sln /p:Configuration=Release
```
(for main)
```
cmake . 
msbuild ethereum.sln /p:Configuration=Release

```
After doing this the first time and not working properly, I did a new 'git pull' and then ran the extdep step and the main part again. I am not sure if this is enough to reproduce. Which cmake logs do you need exactly? Not sure which are the correct ones/where they are stored.

**Comment by debris** [comment]
run `cmake --system-information log.txt` and paste here output from log.txt

**Comment by step21** [comment]
I pastebin'd it, as it is a rather long log. http://pastebin.com/SCv30vbC

**Comment by debris** [comment]
should be fixed by now
