### ISSUE TITLE
jsoncpp upgrade will need adressing

### ISSUE THREAD

**Issue by LefterisJP** [ethereum/cpp-ethereum#781]
So, over the weekend there was a new release of [jsoncpp](https://github.com/open-source-parsers/jsoncpp) (0.7.1.). which kind of breaks building things for us. I already got the problem since I am on ArchLinux. They changed the root of the library's include from `jsoncpp/json/json.h` to `json/json.h`.

Since this is the recommended way by the library itself to use includes now we should also comply. A quick patch I tried was to simply add to jsoncpp's cmake find function as suggested by @debris 
```cmake
find_path(
	JSONCPP_INCLUDE_DIR 
	NAMES jsoncpp/json/json.h json/json.h
	DOC "jsoncpp include dir"
)
```

and then change the 3 places where jsoncpp was included in the code, to comply with both the new root directory and the old.
```
libsolidity/InterfaceHandler.h:31:24:#include <jsoncpp/json/json.h>
test/SolidityABIJSON.cpp:25:24:#include <jsoncpp/json/json.h>
test/SolidityNatspecJSON.cpp:24:24:#include <jsoncpp/json/json.h>
```

The problem with this is that `jsonrpccpp` also includes `jsoncpp` and at least the version we are using is trying to include the old root directory.
```
In file included from /usr/local/include/jsonrpccpp/server/abstractserver.h:16:0,
                 from /usr/local/include/jsonrpccpp/server.h:13,
                 from /home/lefteris/ew/cpp-ethereum/libqethereum/QEthereum.h:28,
                 from /home/lefteris/ew/cpp-ethereum/libqethereum/QEthereum.cpp:25:
/usr/local/include/jsonrpccpp/common/procedure.h:16:31: fatal error: jsoncpp/json/json.h: No such file or directory
 #include <jsoncpp/json/json.h>
                               ^
compilation terminated.
libqethereum/CMakeFiles/qethereum.dir/build.make:54: recipe for target 'libqethereum/CMakeFiles/qethereum.dir/QEthereum.cpp.o' failed
make[2]: *** [libqethereum/CMakeFiles/qethereum.dir/QEthereum.cpp.o] Error 1
CMakeFiles/Makefile2:1501: recipe for target 'libqethereum/CMakeFiles/qethereum.dir/all' failed
make[1]: *** [libqethereum/CMakeFiles/qethereum.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Whenever in any OS the new jsoncpp library is used there will be problems. We should address that somehow.

A recommendation would be to do the suggested change above and also
1) Either use a patched version of jsonrpcpp
2) Wait for the maintainer to change it to use the new jsoncpp root

**Comment by LefterisJP** [comment]
P.S. : For those who may be using Archlinux and want the quicker and dirtiest temporary fix, simply create a temporary symlink for a jsoncpp in /usr/include like this:
```
cd /usr/include  && sudo ln -s . jsoncpp
```

**Comment by gavofyork** [comment]
Won't fix (yet) since it only concerns a community-maintained platform and there is already a simple workaround.

**Comment by sveneh** [comment]
@subtly @caktux I assume this will affect OS X  homebrew sooner or later?

**Comment by LefterisJP** [comment]
@gavofyork , the above fix did not really work after all. Had to build from source the same version we use in Ubuntu. The new jsoncpp does not play well with the version of Jsonrpcpp we are using. 

If as sven mentions, this gets to OSX the build will break.

**Comment by subtly** [comment]
json-cpp and json-rpc-cpp are conspiring!
@sveneh Yes and no. This is same story as json-rpc-cpp debacle. I recommend creating upstream issues and pull-requests with json-cpp and talk to developer. At least confirm that this won't happen again and 0.7 is stable :)

**Comment by LefterisJP** [comment]
I opened an issue with the author of json-rpc-cpp just for the headers include directory thing. I can't claim that `json-rpc-cpp` does not play well with the new `jsoncpp` since we have a specific commit checked out for `json-rpc-cpp` and whatever caused the segfault inside the library when used with the new `jsoncpp` can be due to us using an older version(?).

Anyway no reason to waste any more resources on this right now since OSX still uses old jsoncpp. We just need to be ready for it when it comes.

**Comment by wanderer** [comment]
+1
