### ISSUE TITLE
alethzero segfault?

### ISSUE THREAD

**Issue by youlian** [ethereum/cpp-ethereum#792]
got the source, compiled it and alethzero segfaulted on me. no matter what cmake options always segfaults. that's the first version that segfaulted on me in 8 months or so.
no windows open. os is linux all updates applied (3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux).
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
./alethzero 
QMetaObject::connectSlotsByName: Connecting slot on_idealPeers_valueChanged() with the first of the following compatible signals: ("valueChanged(int)", "valueChanged(QString)") 
QMetaObject::connectSlotsByName: Connecting slot on_value_valueChanged() with the first of the following compatible signals: ("valueChanged(int)", "valueChanged(QString)") 
QMetaObject::connectSlotsByName: Connecting slot on_gas_valueChanged() with the first of the following compatible signals: ("valueChanged(int)", "valueChanged(QString)") 
QMetaObject::connectSlotsByName: Connecting slot on_valueUnits_currentIndexChanged() with the first of the following compatible signals: ("currentIndexChanged(int)", "currentIndexChanged(QString)") 
QMetaObject::connectSlotsByName: Connecting slot on_gasPriceUnits_currentIndexChanged() with the first of the following compatible signals: ("currentIndexChanged(int)", "currentIndexChanged(QString)") 
QMetaObject::connectSlotsByName: Connecting slot on_gasPrice_valueChanged() with the first of the following compatible signals: ("valueChanged(int)", "valueChanged(QString)") 
QMetaObject::connectSlotsByName: No matching signal for on_log_doubleClicked()
QMetaObject::connectSlotsByName: No matching signal for on_debugDumpState_triggered(int)
State root: c67c70f5d7d3049337d1dcc0503a249881120019a8e7322774dbfe57b463718c
Block Hash: 779b1b620b03c0fb24963e183d5e88e3dbe4484e3f6e2aa05942e3be7b48e179
Block RLP: [ [ "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x1DCC4DE8DEC75D7AAB85B567B6CCD41AD312451B948A7413F0A142FD40D49347, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0xC67C70F5D7D3049337D1DCC0503A249881120019A8E7322774DBFE57B463718C, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, 0x56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00", 0x20000, 0x0, 0xF4240, 0x0, 0x0, 0x0, 0x4994F67DC55B09E814AB7FFC8DF3686B4AFB2BB53E60EAE97EF043FE03FB829 ], [ ], [ ] ]
Block Hex: f9012ef90129a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a0c67c70f5d7d3049337d1dcc0503a249881120019a8e7322774dbfe57b463718ca056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b840000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008302000080830f4240808080a004994f67dc55b09e814ab7ffc8df3686b4afb2bb53e60eae97ef043fe03fb829c0c0
Network protocol version: 51
Client database version: 5
*N* [ 07:35:42 PM | main ] IP Address: 192.168.0.112  = [LOCAL]
*N* [ 07:35:42 PM | main ] Id: d6e29c2e\u2026
*** [ 07:35:42 PM | main ] Opened blockchain DB. Latest: 779b1b620b03c0fb24963e183d5e88e3dbe4484e3f6e2aa05942e3be7b48e179
*** [ 07:35:42 PM | main ] Opened state DB.
"http://about:blank" 
(o) [ 07:35:42 PM | main ] +++ 0 d71582dc50f3f9b67a84e23d8f04956ffefdee53852b5063a65f02a7019d921d
(o) [ 07:35:42 PM | main ] +++ 1 d71582dc50f3f9b67a84e23d8f04956ffefdee53852b5063a65f02a7019d921d
(o) [ 07:35:42 PM | main ] +++ 2 0000000000000000000000000000000000000000000000000000000000000000
(o) [ 07:35:42 PM | main ] +++ 3 0000000000000000000000000000000000000000000000000000000000000001
Segmentation fault (core dumped)

**Comment by LefterisJP** [comment]
Would you by any chance be able to run it through GDB and give us a stacktrace?

```
gdb ./alethzero
run
... wait for segfault ...
bt
... copy the output of bt ...
```

Also can you tell us the commit hash? You can see it by writting the following inside `cpp-ethereum`:
```
git show HEAD
```

**Comment by youlian** [comment]
git show HEAD
commit 8719a4dbe8749421931f03436c84b2c202605fda
Merge: 74e8322 42940c1
Author: Gav Wood <g@ethdev.com>
Date:   Mon Jan 12 17:06:41 2015 +0000

    Merge pull request #787 from CJentzsch/bugfix
    
    addmod mulmod div by zero tests

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

(gdb) bt
#0  0x00007fff8ce577b1 in ?? () from /usr/lib/x86_64-linux-gnu/libLLVM-3.4.so.1
#1  0x00007ffff7dea13a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffdc68, env=env@entry=0x7fffffffdc78) at dl-init.c:78
#2  0x00007ffff7dea223 in call_init (env=<optimized out>, argv=<optimized out>, argc=<optimized out>, l=<optimized out>) at dl-init.c:36
#3  _dl_init (main_map=main_map@entry=0xb877c0, argc=1, argv=0x7fffffffdc68, env=0x7fffffffdc78) at dl-init.c:126
#4  0x00007ffff7deec70 in dl_open_worker (a=a@entry=0x7fffffffbd28) at dl-open.c:577
#5  0x00007ffff7de9ff4 in _dl_catch_error (objname=objname@entry=0x7fffffffbd18, errstring=errstring@entry=0x7fffffffbd20, mallocedp=mallocedp@entry=0x7fffffffbd10, 
    operate=operate@entry=0x7ffff7dee9a0 <dl_open_worker>, args=args@entry=0x7fffffffbd28) at dl-error.c:187
#6  0x00007ffff7dee3bb in _dl_open (file=0x7fffffffbf90 "/usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so", mode=-2147483390, caller_dlopen=<optimized out>, nsid=-2, argc=1, argv=0x7fffffffdc68, 
    env=0x7fffffffdc78) at dl-open.c:661
#7  0x00007fffee1e502b in dlopen_doit (a=a@entry=0x7fffffffbf40) at dlopen.c:66
#8  0x00007ffff7de9ff4 in _dl_catch_error (objname=0x9111a0, errstring=0x9111a8, mallocedp=0x911198, operate=0x7fffee1e4fd0 <dlopen_doit>, args=0x7fffffffbf40) at dl-error.c:187
#9  0x00007fffee1e562d in _dlerror_run (operate=operate@entry=0x7fffee1e4fd0 <dlopen_doit>, args=args@entry=0x7fffffffbf40) at dlerror.c:163
#10 0x00007fffee1e50c1 in __dlopen (file=<optimized out>, mode=<optimized out>) at dlopen.c:87
#11 0x00007fffe864500c in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#12 0x00007fffe8648beb in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#13 0x00007fffe862552c in ?? () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#14 0x00007fffe86219c7 in glXGetFBConfigs () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#15 0x00007fffe8622493 in glXChooseFBConfigSGIX () from /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1
#16 0x00007fffe2f8250f in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#17 0x00007fffe2f8265c in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#18 0x00007fffe2f6ce7d in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#19 0x00007fffe2f5f731 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#20 0x00007ffff0f42efe in QWindow::create() () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#21 0x00007ffff163a33a in QWidgetPrivate::create_sys(unsigned long long, bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff1616dcc in QWidget::create(unsigned long long, bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff16170b8 in QWidget::create(unsigned long long, bool, bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff161f81a in QWidget::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff17cc238 in QDialog::setVisible(bool) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff17cbc91 in QDialog::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff17e7b5f in QInputDialog::getText(QWidget*, QString const&, QString const&, QLineEdit::EchoMode, QString const&, bool*, QFlags<Qt::WindowType>, QFlags<Qt::InputMethodHint>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00000000005be491 in Main::readSettings (this=0x7fffffffd260, _skipGeometry=false) at /home/test/repos3/ethereum/cpp-ethereum/o/cpp-ethereum/alethzero/MainWin.cpp:716
#29 0x00000000005b7401 in Main::Main (this=0x7fffffffd260, parent=0x0) at /home/test/repos3/ethereum/cpp-ethereum/o/cpp-ethereum/alethzero/MainWin.cpp:190
#30 0x00000000005b0532 in main (argc=1, argv=0x7fffffffdc68) at /home/test/repos3/ethereum/cpp-ethereum/o/cpp-ethereum/alethzero/main.cpp:8
(gdb)

**Comment by gavofyork** [comment]
looks like it's a Qt issue...

**Comment by gavofyork** [comment]
any better with latest commits?

**Comment by youlian** [comment]
i just removed all versions of llvm < 3.5.
that's the problem - llvm versions used by x.org drivers and therefore by qt and llvm versions suitable for ethereum could clash.
so this could be closed. there are still problems with alethzero though...
gives me segfaults after working a bit, and also the gui very frequently just freezes for many many seconds, but that's another problem, far harder to reproduce.
