### ISSUE TITLE
Bus Error crash when downloading blockchain.

### ISSUE THREAD

**Issue by Smithgift** [ethereum/cpp-ethereum#806]
Like the title says, alethzero was downloading the blockchain (on an Ubuntu laptop), when it froze, followed by a "Bus error (core dumped)"

I do have the core dump in question. I'm just not sure where to put it up. 

EDIT: This was on the stable binary for Ubuntu from the package manager.

**Comment by LefterisJP** [comment]
You can simply open the core file with `gdb` and paste the stacktrace here.
[Here](http://stackoverflow.com/a/5745312/110395) are instruction how to do that just in case you are not familiar with core files.

**Comment by Smithgift** [comment]
Hmm. It appears what I thought was a core dump was actually what apport made after the crash. It doesn't have a stacktrace OR a core dump inside.

apport did say: "Your computer does not have enough free memory to automatically analyze the problem and send a report to the developers." I suspect that is why there is no core dump to be found. (This computer has 1.9 GiB of RAM.)

Right now I have to go, but soon I'll try to get it to crash again.

**Comment by Smithgift** [comment]
I couldn't get it to crash again, though I noted that it never ran too low on RAM, either.

Just in case it's related, I did find this in apport.log (after the alethzero crash):

"ERROR: apport (pid 3077) Wed Jan 14 13:33:12 2015: debug: session gdbus call: (true,)"

**Comment by immon** [comment]
I also hit "bus error" bug.
```
$ dpkg -s alethzero  | grep Ver
Version: 0.9.20+840SNAPSHOT20150513174051trusty-0ubuntu1
$ dpkg -s libethereum | grep Ver
Version: 0.9.20+840SNAPSHOT20150513174051trusty-0ubuntu1
$ dpkg -s libcryptopp-dev | grep Ver
Version: 5.6.2-0~trusty6
```
My backtrace
```
Core was generated by `alethzero'.
Program terminated with signal SIGBUS, Bus error.
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
35	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
(gdb) bt
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
#1  0x00007f33d0c94c06 in CryptoPP::SHA3::TruncatedFinal(unsigned char*, unsigned long) () from /usr/lib/libcryptopp.so
#2  0x00007f33c84cc7b5 in SHA3_512 () from /usr/lib/libethash.so
#3  0x00007f33c84caca8 in ethash_calculate_dag_item () from /usr/lib/libethash.so
#4  0x00007f33c84cb05c in ethash_compute_full_data () from /usr/lib/libethash.so
#5  0x00007f33c84cbbc1 in ethash_full_new_internal () from /usr/lib/libethash.so
#6  0x00007f33c84cbdf2 in ethash_full_new () from /usr/lib/libethash.so
#7  0x00007f33d2ad1bff in dev::eth::EthashAux::FullAllocation::FullAllocation(ethash_light*, int (*)(unsigned int)) () from /usr/lib/libethcore.so
#8  0x00007f33d2ad3d65 in dev::eth::EthashAux::full(unsigned long, std::function<int (unsigned int)> const&) () from /usr/lib/libethcore.so
#9  0x00007f33d2af7cd6 in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/lib/libethcore.so
#10 0x00007f33cf7e3326 in ?? () from /usr/lib/libdevcore.so
#11 0x00007f33ceaf3bf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#12 0x00007f33ced4e182 in start_thread (arg=0x7f33333f4700) at pthread_create.c:312
#13 0x00007f33ce25a47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by LefterisJP** [comment]
This is a totally unrelated issue. Bus error can occur for many different reasons. If it happens during DAG calculation as the backtrace above shows I would say you don't have enough disk space or memory. How much space do you have in the machine?

**Comment by immon** [comment]
I managed somehow to run alethzero - could be some memory has been freed.
I have ~50GB of free space. 
Here is an another bus error I just had. Alethzero was working for sometime correctly, but after I clicked "Mine" it crashed.
If it is a problem with free memory or free space why it gives bus error but not a nice error message?
 
```
Core was generated by `alethzero'.
Program terminated with signal SIGBUS, Bus error.
#0  0x00002b698871af80 in ethash_calculate_dag_item () from /usr/lib/libethash.so
(gdb) bt
#0  0x00002b698871af80 in ethash_calculate_dag_item () from /usr/lib/libethash.so
#1  0x00002b698871b05c in ethash_compute_full_data () from /usr/lib/libethash.so
#2  0x00002b698871bbc1 in ethash_full_new_internal () from /usr/lib/libethash.so
#3  0x00002b698871bdf2 in ethash_full_new () from /usr/lib/libethash.so
#4  0x00002b697e149bff in dev::eth::EthashAux::FullAllocation::FullAllocation(ethash_light*, int (*)(unsigned int)) () from /usr/lib/libethcore.so
#5  0x00002b697e14bd65 in dev::eth::EthashAux::full(unsigned long, std::function<int (unsigned int)> const&) () from /usr/lib/libethcore.so
#6  0x00002b697e16fcd6 in dev::eth::Ethash::CPUMiner::workLoop() () from /usr/lib/libethcore.so
#7  0x00002b6981401326 in ?? () from /usr/lib/libdevcore.so
#8  0x00002b6981f5bbf0 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x00002b6981c93182 in start_thread (arg=0x2b6a2628a700) at pthread_create.c:312
#10 0x00002b69827c547d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by LefterisJP** [comment]
Yes it seems like a memory issue. We should indeed try to provide better error message for this.

The reason you are seeing this now is due to having a memory mapped DAG file. You need to have at least 4GB of memory in your machine in order to mine.
