### ISSUE TITLE
Crashes while making on OS X

### ISSUE THREAD

**Issue by hierophantos** [ethereum/cpp-ethereum#808]
Here's the output I get while running Hombrew Tap:

`cd /tmp/ethereum-Wt6PGS/libsolidity && /usr/local/Cellar/cmake/3.1.0/bin/cmake -E cmake_link_script CMakeFiles/solidity.dir/link.txt --verbose=1
/usr/bin/clang++  -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -DSTATICLIB -O3 -DNDEBUG -DETH_RELEASE -dynamiclib -Wl,-headerpad_max_install_names  -o libsolidity.dylib -install_name /tmp/ethereum-Wt6PGS/libsolidity/libsolidity.dylib CMakeFiles/solidity.dir/AST.cpp.o CMakeFiles/solidity.dir/ASTPrinter.cpp.o CMakeFiles/solidity.dir/CallGraph.cpp.o CMakeFiles/solidity.dir/Compiler.cpp.o CMakeFiles/solidity.dir/CompilerContext.cpp.o CMakeFiles/solidity.dir/CompilerStack.cpp.o CMakeFiles/solidity.dir/CompilerUtils.cpp.o CMakeFiles/solidity.dir/DeclarationContainer.cpp.o CMakeFiles/solidity.dir/ExpressionCompiler.cpp.o CMakeFiles/solidity.dir/GlobalContext.cpp.o CMakeFiles/solidity.dir/InterfaceHandler.cpp.o CMakeFiles/solidity.dir/NameAndTypeResolver.cpp.o CMakeFiles/solidity.dir/Parser.cpp.o CMakeFiles/solidity.dir/Scanner.cpp.o CMakeFiles/solidity.dir/SourceReferenceFormatter.cpp.o CMakeFiles/solidity.dir/Token.cpp.o CMakeFiles/solidity.dir/Types.cpp.o /usr/local/lib/libjsoncpp.dylib ../libevmcore/libevmcore.dylib ../libdevcore/libdevcore.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_date_time-mt.a /usr/local/lib/libboost_system-mt.a /usr/local/lib/libboost_chrono-mt.a 
/usr/local/Cellar/cmake/3.1.0/bin/cmake -E cmake_progress_report /tmp/ethereum-Wt6PGS/CMakeFiles  70 71 72 73 74 75 76 77 78
[ 30%] Built target solidity
make: *** [all] Error 2

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/ethereum/homebrew-ethereum/issues`

**Comment by debris** [comment]
probably outdated
