### ISSUE TITLE
Compile just the languages

### ISSUE THREAD

**Issue by ebuchman** [ethereum/cpp-ethereum#859]
It used to be possible to compile just the language cli's with 

`cmake .. -DCMAKE_BUILD_TYPE=Release -DLANGUAGES=1 && make`

But it appears this is no longer possible (ie. I need qt and jsonrpc installed).

Can we get that compile option back, or has it changed and I'm just not finding the solution?

**Comment by gavofyork** [comment]
languages was used just for serpent and lll. now that serpent has its own repo and lll is deprecated, there's no option. if you just want the solidity compiler, use -DHEADLESS=1
