### ISSUE TITLE
jsonrpc service rejecting all calls

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/cpp-ethereum#870]
JSONRPC calls no longer work; this seems to be introduced by a recent change to  `libweb3jsonrpc/CorsHttpServer.cpp`

```
XMLHttpRequest cannot load http://localhost:8080/.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://localhost:8000' is therefore not allowed access.
```

This might be introduced in commit 8c2c08e869462c3ec05f6275f59a8dee9df98825 by @debris  

By always returning `0` in `HttpServer::callback` it rejects all JSONRPC requests which would otherwise be handled by `libweb3jsonrpc/CorsHttpServer.cpp`
See https://www.gnu.org/software/libmicrohttpd/manual/html_node/microhttpd_002dcb.html

**Comment by jorisbontje** [comment]
Still investigating if I can narrow down the commit.

**Comment by gavofyork** [comment]
please check and close if fixed.

**Comment by jorisbontje** [comment]
Fixed
