### ISSUE TITLE
all solidity tests failing

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#872]
| test_name  | tests         | failing  |
| --------------- |:-------------:| ---------:|
| SolidityABIJSON | 6 | 6 |
| SolidityCompiler | 4 | 4 |
| SolidityEndToEndTest | 79 | 79 |
| SolidityExpressionCompiler | 14 | 14 |
| SolidityNameAndTypeResolution | 51 | 51 |
| SolidityNatspecJSON | 20 | 20 |
| SolidityOptimizer | 5 | 5 | 
| SolidityParser | 38 | 37 |
| SolidityScanner | 20 | 20 |

tested on mac 10.9
commit 9e57eb26a5e3b6894f3485286ea869639d342991

@chriseth , @LefterisJP  please make tests up to date. it's important.

**Comment by LefterisJP** [comment]
no idea why this is happening. All was fine on my branch last night. Will checkout develop and investigate.

**Comment by LefterisJP** [comment]
I am sorry Marek but locally having checkout the latest develop I can't reproduce any of the failures you report. All is green for me. Could it be an issue on your end? If it's such a total failure it can't be a Mac only issue.

I will make clean from scratch and try again.

**Comment by debris** [comment]
i will also try clean build

**Comment by debris** [comment]
cannot reproduce any longer. i'm closing
