### ISSUE TITLE
shh: filtered watcher, callbacks are fired always, even if not all filter match

### ISSUE THREAD

**Issue by frozeman** [ethereum/cpp-ethereum#884]
E.g. if i have a watcher for two topics `['appName','topic1']` and a another one for  `['appName','topic2']`.

If a message with  `['appName','topic1']` arrives, the callbacks in ethereum.js for both watchers are called. 
I expect only the first watcher callback to be called.

(@debris told me its a cpp issue).

**Comment by gavofyork** [comment]
cannot reproduce this. check?
