### ISSUE TITLE
Uninstalling watchers with the same topics but different "to" and "from", uninstalling all of them.

### ISSUE THREAD

**Issue by frozeman** [ethereum/cpp-ethereum#898]
if i create a watcher in js with:
topic: ['x'], to: '0x43234', from: '0x43234'
and another one with
topic: ['x'], to: '0x43234'

and i uninstall the first one, the second one will also be uninstalled. as they are in the whisper node the same. Means the callback of none of them will be fired anymore.

Though it seems to work, when you have watchers with different topics.

**Comment by gavofyork** [comment]
whisper bugs should be resubmitted.
