### ISSUE TITLE
calling web3.shh.watch().getMessages() is unimplemented

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#899]
calling web3.shh.watch().getMessages() is unimplemented. the result is  "{code: -32601, message: "METHOD_NOT_FOUND: The method being requested is not available on this server"}"

**Comment by frozeman** [comment]
Ideally a call to this method, will call the `arrived()` callback of this watcher as many times as still floating messages are in the system matching this watcher.

**Comment by gavofyork** [comment]
calling this, well actually, `web3.ssh.watch(...).messages()` will return an array, possibly empty, of all of the known messages that fit the `...` description.

fwiw it just needs hooking up to `shh::WhisperHost`/`shh::Interface` `::watchMessages(unsigned)`.
