### ISSUE TITLE
SHA in Solidity

### ISSUE THREAD

**Issue by joeykrug** [ethereum/cpp-ethereum#920]
I was wondering if it'll ever be possible to pass things to the sha functions in solidity that are less than or greater than exactly 256 bits?  In Serpent we can do this (including passing strings, arrays, etc.) and it'd be great to have in Solidity as well.

**Comment by jorisbontje** [comment]
+1

**Comment by SilentCicero** [comment]
+1

**Comment by gavofyork** [comment]
generic SHA3 is planned. once we have byte arrays this'll be possible.

**Comment by chriseth** [comment]
Functionality is there. Passed arguments are *not* padded to multiples of 32 bytes.
