### ISSUE TITLE
eth is not respecting -x 0 (--peers) argument anymore

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/cpp-ethereum#926]
starting `eth -j -m on -x 0`
after a while the eth process starts to connect to other nodes; even though it shouldn't based on the `-x 0` argument

```
-N- [ 14:51:18 | p2p | 22 ] Hello: Ethereum(++)/Develop Server Eight/v0.8.0/Release/linux/int V[ 2 ] a1949fd1… (eth,52)(shh,2) 30303
-N- [ 14:51:18 | p2p | 22 ] Transition! State from Nothing , holding
-N- [ 14:51:18 | p2p | 22 ] Status: 52 / 0 / c9cb614f… , TD: 11251189782 = 9df6bca1…
-N- [ 14:51:18 | p2p | 22 ] Transition! Nothing from State , holding & needed
-N- [ 14:51:18 | p2p | 22 ] Transition! Hashes from Nothing , holding & needed
-N- [ 14:51:18 | p2p | 22 ] Status: 2
-N- [ 14:51:18 | p2p | 22 ] Transactions ( 0 entries)
-N- [ 14:51:18 | p2p | 22 ] Transactions ( 0 entries)
-N- [ 14:51:18 | p2p | 22 ] BlockHashes ( 64 entries)
-N- [ 14:51:18 | p2p | 22 ] Transition! Hashes from Hashes , syncing
etc
```

this is with cpp-ethereum 88087d4 on OSX

**Comment by gavofyork** [comment]
-x is for setting the "ideal peer count", it doesn't prevent short-term deviations from it. it's not (meant to be) a hard limit on the connections.

this is all about to be completely replaced by alex's code anyway.

**Comment by jorisbontje** [comment]
What I want to accomplish is to run a local `eth` node that doesn't connect to the testnet. Any suggestion on how I could do this?

**Comment by gavofyork** [comment]
try `--hermit`
