### ISSUE TITLE
mix: scrolling sidebar

### ISSUE THREAD

**Issue by debris** [ethereum/cpp-ethereum#930]
Tested on mac 10.9

That's probably mac only (qt) issue. Whenever I scroll recorded transactions in mix, the sidebar is going crazy, and it's scrolling to the bottom.

before:
![screen shot 2015-02-02 at 16 55 29](https://cloud.githubusercontent.com/assets/2613714/6003506/97dd12b8-aafc-11e4-8306-81f4d5f0b269.png)

after:
![screen shot 2015-02-02 at 16 55 32](https://cloud.githubusercontent.com/assets/2613714/6003509/9c2dad50-aafc-11e4-8730-7a529a3c0175.png)

**Comment by gavofyork** [comment]
linux as well.
