### ISSUE TITLE
eth stable client does not connect

### ISSUE THREAD

**Issue by sveneh** [ethereum/cpp-ethereum#939]
fresh Ubuntu 14.04, installed from scratch
Installed ethereum stable ppa

Following the instructions at https://github.com/ethereum/cpp-ethereum/wiki/Using-Ethereum-CLI-Client

I started two clients on the same machines with the example given. In addition to the example, I also added local-networking and turned upnp off.
 
these are the commands:
```
mkdir c1
eth -d c1 -L --upnp off -v 9 -u 127.0.0.1 -l 30303 
```
and
```
mkdir c2
eth -d c2 -L --upnp off -v 9 -u 127.0.0.1 -l 30300 -p 30303 127.0.0.1
```

I only get 
```
Ethereum (++) 0.7.14
  Code by Gav Wood, (c) 2013, 2014.
  Based on a design by Vitalik Buterin.

*N* [ 12:22:30 | main ] IP Address: 10.10.42.122  = [LOCAL]
*N* [ 12:22:30 | main ] Id: dd676498…
*** [ 12:22:30 | main ] Opened blockchain DB. Latest: 779b1b620b03c0fb24963e183d5e88e3dbe4484e3f6e2aa05942e3be7b48e179
*** [ 12:22:30 | main ] Opened state DB.
Address: 
2b7df1e71031a0eb00baacb0c354abd4272c70a9
*N* [ 12:22:30 | p2p ] Id: dd676498…
*** [ 12:22:30 | eth ] New block on chain: Restarting mining operation.
```

It stays there forever. In both clients. 

How do I connect those two nodes?

**Comment by romanman** [comment]
@sveneh  : maybe you can set the income port for the 
first one to 30302 or something like that

**Comment by sveneh** [comment]
I tried what @romanman proposed, but it doesn't change anything.

**Comment by gavofyork** [comment]
looking into it today

**Comment by gavofyork** [comment]
Fixed in latest develop. Please reopen if doesn't work for you.
