### ISSUE TITLE
mix: should combine toolbar/status text and titlebar as is standard on Mac

### ISSUE THREAD

**Issue by gavofyork** [ethereum/cpp-ethereum#961]
See http://blog.qt.io/blog/2011/04/08/mac-toolbars-for-qt-quick/ for a possible solution.

**Comment by subtly** [comment]
I've done this before w/native macos and can provide the source code; if that sounds like it'll help w/figuring out what API calls to make to Qt, let me know and I'll post the code on dropbox. One can create full-bleed dialogues and customized toolbars similar to this: http://mac.appstorm.net/reviews/productivity-review/organize-your-tasks-with-cheddar/
I think code for cheddar mac app is also available.

**Comment by yann300** [comment]
Could you send us the code you use to make this possible?

**Comment by chriseth** [comment]
Closing as out of scope.
