### ISSUE TITLE
solidity: Can access local variable out of scope 

### ISSUE THREAD

**Issue by drcode** [ethereum/cpp-ethereum#974]
The following function should probably create a compiler error since baz isn't defined when it is used (though this oddball behavior might be by design, if you guys have a really weird model for variable scope)

    function foo(){                                                                                                                    
        uint bar=5;
        if(true){
            bar+=baz;
        }
        else{
            uint baz=10;
        }
    }

**Comment by chriseth** [comment]
We actually inherited the really weird scoping rules from JavaScript. This might be revisited, though. The current rules are: All local variables are zero-initialized, there can only be one declaration of each variable, variables are visible in a complete function, no matter where they are declared.

**Comment by drcode** [comment]
Totally understandable.
