### ISSUE TITLE
error building

### ISSUE THREAD

**Issue by youlian** [ethereum/cpp-ethereum#992]
cpp-ethereum/libethereum/MessageFilter.cpp: In member function 
bool dev::eth::MessageFilter::matches(const dev::eth::State&, unsigned int) const:
cpp-ethereum/libethereum/MessageFilter.cpp:77:14: error: 
const class dev::eth::State has no member named changesFromPending\
  h256 b = _s.changesFromPending(_i).bloom();

**Comment by gavofyork** [comment]
is this master or develop?

looks like you've got some old files in there. MessageFilter was removed *ages* ago. try a clean checkout of develop branch.

**Comment by youlian** [comment]
thank you for the hint. didn't even thought about that sorry :(
