### ISSUE TITLE
mix: Menu item "Open Project" doesn't do anything

### ISSUE THREAD

**Issue by christianpeel** [ethereum/cpp-ethereum#995]
Using mix on OS X (built as described below), I find that mix doesn't do anything when I try to "Open a project" using the menu or cmd-O (⌘-O), though it does allow me to make a "New Project".   

I'm using a 2013 Macbook Pro with OS X 10.10.2.  I installed all the prerequisites using homebrew, and compiled mix from source using the instructions at https://github.com/ethereum/cpp-ethereum/wiki/Building-on-MacOS 

I had the same problem five days ago, so this is not just a temporary problem.

**Comment by yann300** [comment]
reference for this: 
https://bugreports.qt.io/browse/QTBUG-43248

**Comment by christianpeel** [comment]
So to be clear, there is a problem with the QT code on OS X, but you've found a workaround; is that right?  Thanks for looking at this

**Comment by christianpeel** [comment]
Thanks!  Tested it out and it works.

**Comment by yann300** [comment]
You're welcome! 
Feel free to give us your feedback on Mix.
